import {objectiveQuestions} from '@/lib/hris/learning-objective-exams';
import {z} from 'zod';
import {developmentContext,visibleDevelopment,saveDevelopmentMany} from '@/lib/hris/development-repository';
import {applyLearningExamTask,examTaskOpen} from '@/lib/hris/learning-exam-tasks';
import {learningStageSubmissionOpen,learningStageOpen} from '@/lib/hris/learning-requirements';
import {json,failure,readBody} from '@/lib/hris/http';
const kinds=['homeworkDefinition','homeworkTask','homeworkSubmission','learningAssignment','enrollment','learningExamDefinition','learningExamTask','learningExamAttempt'] as const;
export async function GET(){try{const c=await developmentContext(kinds),visible=visibleDevelopment(c),tasks=visible.filter(r=>r.kind==='learningExamTask'),papers=c.records.filter(r=>r.kind==='learningExamDefinition'&&tasks.some(t=>t.referenceId===r.id&&(['admin','hr'].includes(c.member.role)||examTaskOpen(t,c.state)&&learningStageSubmissionOpen(t,c.records)&&learningStageOpen(t,c.records,undefined,c.state)||visible.some(a=>a.kind==='learningExamAttempt'&&a.referenceId===t.id)))).map(r=>({...r,createdBy:'',payload:{title:r.payload.title,objectiveQuestions:objectiveQuestions(r).map(({correct,...q})=>q),questions:r.payload.questions?.map(({correct,...q})=>q),passingScore:r.payload.passingScore,maxAttempts:r.payload.maxAttempts,version:r.payload.version}}));return json({records:visible.filter(r=>r.kind!=='learningExamDefinition'),papers,revision:c.row.revision,employeeId:c.member.employeeId,role:c.member.role});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const b=z.object({revision:z.number().int().nonnegative(),command:z.unknown()}).strict().parse(await readBody(request)),c=await developmentContext(kinds),records=applyLearningExamTask(c.records,c.state,c.member,b.command);await saveDevelopmentMany(c,b.revision,records,'独立考试：'+String((b.command as {action:string}).action));return json({ids:records.map(r=>r.id),revision:c.row.revision+1});}catch(e){return failure(e);}}
