'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={submitted:'待复核',approved:'已认证',rejected:'未通过',withdrawn:'已撤回',revoked:'已撤销'};
export default function Instructors(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/instructors',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 const hr=['admin','hr'].includes(data?.role??''),records=data?.records??[],record=records.find(r=>r.id===detail),today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date()),rows=records.filter(r=>r.kind==='instructorCertification'&&[r.payload.title,r.payload.name,labels[r.status]].join(' ').includes(search)).reverse();
 function open(action:string,r?:R,accepted?:boolean){setError('');setForm({action,id:r?.id??'',employeeId:data?.employeeId??'none',courseId:'none',start:'',end:'',evidence:'',accepted:String(accepted)});}
 async function submit(e:FormEvent){e.preventDefault();if(!data||!form)return;setBusy(true);setError('');try{const command={...form,...(form.action==='review'?{accepted:form.accepted==='true'}:{})};const r=await fetch('/api/instructors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('讲师认证记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function status(r:R){return r.status==='approved'?(r.payload.end!<today?'已到期':r.payload.start!>today?'已认证 · 未生效':'已认证'):labels[r.status];}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex flex-wrap gap-5 text-sm"><Link href="/instructor-directory" className="text-link">内部讲师名册</Link><Link href="/reports?dataset=instructorSchedule" className="text-link">授课安排台账</Link><Link href="/" className="text-link">导航台</Link><Link href="/learning" className="text-link">学习中心</Link><Link href="/training-sessions" className="text-link">培训排期</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">INSTRUCTOR CERTIFICATION</div><h1>内部讲师认证</h1><p className="mt-2 text-sm text-slate-500">认证绑定员工和课程版本，经独立HR复核后，可在有效期内引用安排培训场次。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}
 <section className="panel"><div className="section-head gap-4"><Input className="max-w-md" aria-label="搜索讲师认证" placeholder="搜索讲师、课程或状态" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{(hr||data?.employeeId)&&<Button onClick={()=>open('submit')}>申请认证</Button>}</div><Table><TableHeader><TableRow>{['讲师','课程版本','认证期间','状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*15,page*15).map(r=><TableRow key={r.id}><TableCell>{r.payload.name}</TableCell><TableCell>{r.payload.title} · V{r.payload.version}</TableCell><TableCell>{r.payload.start} 至 {r.payload.end}</TableCell><TableCell>{status(r)}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={()=>setDetail(r.id)}>详情</Button>{r.status==='submitted'&&r.createdBy===data?.userId&&<Button size="sm" variant="outline" onClick={()=>open('withdraw',r)}>撤回</Button>}{hr&&r.employeeId!==data?.employeeId&&r.createdBy!==data?.userId&&<>{r.status==='submitted'&&<><Button size="sm" onClick={()=>open('review',r,true)}>认证通过</Button><Button size="sm" variant="outline" onClick={()=>open('review',r,false)}>不通过</Button></>}{r.status==='approved'&&<Button size="sm" variant="outline" onClick={()=>open('revoke',r)}>撤销认证</Button>}</>}</div></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">暂无可见的讲师认证</p>}<div className="flex justify-end items-center gap-3 mt-4"><span className="text-sm">{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{form?.action==='submit'?'申请讲师认证':form?.action==='review'?(form.accepted==='true'?'独立复核并通过':'独立复核并不予通过'):form?.action==='withdraw'?'撤回申请':'撤销认证'}</DialogTitle><DialogDescription>同员工和课程版本的认证期间不能重叠；申请人及认证本人不能复核。撤销后禁止新排期引用，既有排期保留原认证快照，需由HR检查安排。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='submit'&&<>{[{key:'employeeId',label:'讲师员工',options:(core?.employees??[]).filter(e=>e.status!=='离职'&&(hr||e.id===data?.employeeId)).map(e=>[e.id,e.name])},{key:'courseId',label:'课程版本',options:records.filter(r=>r.kind==='course'&&r.status==='published').map(r=>[r.id,`${r.payload.title} · V${r.payload.version}`])}].map(f=><label className="field" key={f.key}><span>{f.label}</span><Select value={form[f.key]} onValueChange={v=>setForm({...form,[f.key]:v})}><SelectTrigger aria-label={f.label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{f.options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>)}{[['start','有效期起'],['end','有效期止']].map(([k,l])=><label key={k} className="field"><span>{l}</span><Input required type="date" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</>}<label className="field"><span>申请依据 / 办理意见</span><textarea required minLength={5} maxLength={2000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{record?.payload.name} · {record?.payload.title}</DialogTitle><DialogDescription>{record&&status(record)} · {record?.payload.start} 至 {record?.payload.end}</DialogDescription></DialogHeader>{record&&<>{Object.entries({申请依据:record.payload.evidence,复核意见:record.payload.verification,撤回原因:record.payload.closedReason,撤销原因:record.payload.revocationReason}).filter(([,v])=>v).map(([k,v])=><div key={k}><p className="text-sm text-slate-500">{k}</p><p className="whitespace-pre-wrap">{v}</p></div>)}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></>}</DialogContent></Dialog></main>;
}
