'use client';
import {useState,useEffect,useRef} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {clientIntent,sendClientCommand,queryClientCommand} from '@/lib/hris/r1-client-command';
const names:Record<string,string>={pending:'待审批',approved:'已批准',rejected:'已拒绝',withdrawn:'已撤回',cancelled:'已取消',not_requested:'尚未申请生效',waiting:'待生效',waiting_external:'待外部回执',applied:'已生效',failed:'生效失败',blocked:'生效受阻',transferNode:'转交节点',intervene:'干预至许可节点',revokeFlow:'撤销流程与原单',withdraw:'撤回本人申请',remind:'登记催办',pending_acceptance:'待接受',accepted:'已接受',revoked:'已撤销'};
function Pick({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{id:string;name:string}[];label:string}){return <select aria-label={label} className="rounded border p-2" value={value} onChange={e=>onChange(e.target.value)}><option value="">请选择{label}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select>;}
export default function Workspace({user}:{user:string}){
 const [data,setData]=useState<any>(null),[orgs,setOrgs]=useState<any[]>([]),[org,setOrg]=useState(''),[options,setOptions]=useState<any>(null),[partition,setPartition]=useState('all'),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState<string|null>(null),[selected,setSelected]=useState<string[]>([]),[action,setAction]=useState<any>(null),[reason,setReason]=useState(''),[target,setTarget]=useState(''),[templateId,setTemplateId]=useState(''),[sourceId,setSourceId]=useState(''),[sources,setSources]=useState<any[]>([]),[templateKey,setTemplateKey]=useState('regularize'),[nodes,setNodes]=useState<{who:string[];pass:string;reject:string}[]>([{who:[],pass:'all',reject:'any_reject'}]),[delegate,setDelegate]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[history,setHistory]=useState<any>(null),[actionDelegation,setActionDelegation]=useState('');
 const epoch=useRef(0),pendingBatch=useRef<any>(null);
 const clear=()=>{epoch.current++;setData(null);setOptions(null);setSources([]);setHistory(null);setSelected([]);setReason('');};
 const read=async(url:string)=>{const r=await fetch(url,{cache:'no-store'}),b=await r.json() as any;if(!r.ok){if([401,403,409].includes(r.status))clear();throw Error(b.error??'暂时无法读取');}return b;};
 const load=async(cursor?:string)=>{const generation=++epoch.current;try{const b=await read('/api/r1/workflows?'+new URLSearchParams({partition,q:query,...(cursor?{cursor}:{})}));if(generation===epoch.current)setData((old:any)=>cursor&&old?{...b,items:[...old.items,...b.items]}:b);}catch(e){setError((e as Error).message);}};
 useEffect(()=>{void load();return()=>{epoch.current++;};},[partition,query]);
 useEffect(()=>{let live=true;read('/api/r1/m01?kind=org&limit=100').then(b=>{if(live)setOrgs(b.items.map((i:any)=>({id:i.id,name:i.payload.name??i.code})));}).catch(e=>setError(e.message));return()=>{live=false;};},[]);
 const loadOptions=async()=>{if(!org)return;const generation=epoch.current;try{const o=await read('/api/r1/workflows/options?'+new URLSearchParams({orgId:org})),s=await read('/api/r1/m01?kind=regularize_request&limit=100');if(generation===epoch.current){setOptions(o);setSources(s.items.filter((i:any)=>i.orgId===org&&i.status==='pending'));}}catch(e){setError((e as Error).message);}};
 useEffect(()=>{setOptions(null);void loadOptions();},[org]);
 const send=async(payload:any)=>{if(!data||busy||unknown)return;setBusy(true);setError('');try{const intent=clientIntent(data,payload.operation,payload);intent.action='M19.'+payload.operation;const r=await sendClientCommand(intent);if(r.state==='unknown'){setUnknown(intent.commandId);setNotice(r.message);}else if(r.state==='rejected')setError(r.message);else{setNotice('办理已提交');setAction(null);setSelected([]);await load();await loadOptions();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const batch=async(decision:string,resume=false)=>{if(!data||busy||unknown)return;setBusy(true);try{const b=resume?pendingBatch.current:{batchId:crypto.randomUUID(),expectedAuthorizationRevision:data.securityStamp.authorizationRevision,expectedWriterEpoch:data.securityStamp.writerEpoch,expectedRecoveryEpoch:data.securityStamp.recoveryEpoch,items:data.items.filter((i:any)=>selected.includes(i.id)).map((i:any)=>({itemId:i.id,commandId:crypto.randomUUID(),payload:{operation:'decide',id:i.id,expectedRevision:i.revision,generation:i.generation,nodeRevision:i.nodeRevision,decision,reason}}))};pendingBatch.current=b;const r=await fetch('/api/r1/workflows/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),body=await r.json() as any;if(!r.ok)throw Error(body.error??'批量结果待核对');setNotice(body.items.map((i:any)=>`${i.itemId}：${i.status==='committed'?'已提交':i.status==='rejected'?'未提交（'+i.machineCode+'）':'结果待核对'}`).join('；'));if(body.items.every((i:any)=>i.status!=='unknown'))pendingBatch.current=null;await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <main className="mx-auto max-w-6xl space-y-5 p-6"><nav className="flex gap-5"><Link href="/">工作台</Link><Link href="/r1-personnel">人事办理</Link><Link href="/approvals">调动专用审批</Link><span>{user}</span></nav><h1 className="text-2xl font-semibold">审批中心</h1><p>审批进度与业务生效分别展示。待办清空后，可继续查看待生效和失败事项。</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}{unknown&&<Button onClick={async()=>{try{const r=await queryClientCommand(unknown);if(r.state==='committed'){setUnknown(null);setNotice('已查到原办理回执');await load();}else setNotice('尚未确认，继续保留原办理记录');}catch(e){setError((e as Error).message);}}}>查询原办理结果</Button>}{pendingBatch.current&&<Button disabled={busy} onClick={()=>batch('',true)}>核对原批量结果</Button>}
 <div className="flex flex-wrap gap-3"><Pick label="列表" value={partition} onChange={setPartition} items={[{id:'all',name:'全部'},{id:'approval',name:'审批中'},{id:'execution',name:'待生效／失败'},{id:'closed',name:'已结束'}]}/><Input aria-label="搜索申请" placeholder="搜索申请" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="outline" onClick={()=>load()}>刷新</Button></div>
 <p>匹配 {data?.total??0} 项；审批中 {data?.partitionCounts?.approval??0} 项；待生效／失败 {data?.partitionCounts?.execution??0} 项</p>
 <table className="w-full text-left"><thead><tr><th>选择</th><th>事项</th><th>审批</th><th>生效</th><th>操作</th></tr></thead><tbody>{data?.items.map((i:any)=><tr key={i.id} className="border-b"><td><input type="checkbox" aria-label={'选择'+i.title} disabled={!i.actions.includes('decide')||selected.length>=20&&!selected.includes(i.id)} checked={selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(id=>id!==i.id))}/></td><td>{i.title}<p className="text-xs">{i.businessId}</p></td><td>{names[i.approvalStatus]??i.approvalStatus}</td><td>{names[i.effectStatus]??i.effectStatus}</td><td className="flex flex-wrap gap-2 py-3">{i.protectedPath?<Link href={i.href}>进入调动原单</Link>:<><Button variant="outline" onClick={async()=>{try{const b=await read('/api/r1/workflows?'+new URLSearchParams({id:i.id}));setHistory(b.history??{items:[],restricted:true});}catch(e){setError((e as Error).message);}}}>历史</Button>{i.actions.includes('decide')&&['approved','rejected'].map(decision=><Button key={decision} disabled={busy||!!unknown} onClick={()=>{setAction({i,operation:'decide',decision});setReason('');}}>{decision==='approved'?'批准':'拒绝'}</Button>)}{i.actions.filter((a:string)=>a!=='decide').map((operation:string)=><Button key={operation} variant="outline" disabled={busy||!!unknown} onClick={()=>{setAction({i,operation});setActionDelegation('');setTarget('');setReason('');}}>{names[operation]}</Button>)}</>}</td></tr>)}</tbody></table>{data?.nextCursor&&<Button onClick={()=>load(data.nextCursor)}>加载下一页</Button>}
 {selected.length>0&&<section className="rounded border p-4"><p>已选 {selected.length} 项</p><Input aria-label="批量审批原因" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={!reason||busy||!!unknown} onClick={()=>batch('approved')}>批量批准</Button><Button disabled={!reason||busy||!!unknown} onClick={()=>batch('rejected')}>批量拒绝</Button></section>}
 {history&&<section className="rounded border p-4"><h2>不可变办理历史</h2>{history.restricted?<p>当前未获历史读取权限。</p>:history.items.map((e:any)=><p key={e.id}>{e.at} · {names[e.action]??e.action} · 实际办理人 {e.actorId}{e.principalId?' · 原管理人 '+e.principalId:''}</p>)}{history.next&&<p>更多历史可按记录游标继续查询。</p>}<Button variant="outline" onClick={()=>setHistory(null)}>收起</Button></section>}
 <section className="space-y-3 rounded border p-4"><h2 className="text-lg">组织流程与管理委托</h2><Pick label="组织" value={org} onChange={setOrg} items={orgs}/>{options&&<>
 {options.start&&<div className="flex flex-wrap gap-2"><Pick label="流程模板" value={templateId} onChange={setTemplateId} items={options.templates.filter((t:any)=>!t.disabled).map((t:any)=>({id:t.id,name:`${t.id} · 版本${t.version}`}))}/><Pick label="转正原单" value={sourceId} onChange={setSourceId} items={sources.map(s=>({id:s.id,name:s.payload.reason??s.id}))}/><Button disabled={!sourceId||!templateId||busy||!!unknown} onClick={()=>send({operation:'start',templateId,businessType:'personnel.regularize',businessId:sourceId,applicationVersion:1})}>发起审批</Button></div>}
 {options.configure&&<details><summary>发布转正流程模板</summary><Input aria-label="模板编号" value={templateKey} onChange={e=>setTemplateKey(e.target.value)}/>{nodes.map((n,index)=><div key={index} className="my-3 rounded border p-3"><p>节点 {index+1}</p>{options.members.map((m:any)=><label key={m.id} className="mr-3"><input type="checkbox" checked={n.who.includes(m.id)} onChange={e=>setNodes(nodes.map((r,j)=>j===index?{...r,who:e.target.checked?[...r.who,m.id]:r.who.filter(id=>id!==m.id)}:r))}/>{m.name}</label>)}<Pick label="通过规则" value={n.pass} onChange={pass=>setNodes(nodes.map((r,j)=>j===index?{...r,pass}:r))} items={[{id:'all',name:'全部批准'},{id:'any',name:'任一批准'}]}/><Pick label="拒绝规则" value={n.reject} onChange={reject=>setNodes(nodes.map((r,j)=>j===index?{...r,reject}:r))} items={[{id:'any_reject',name:'任一拒绝即拒绝'},{id:'all_reject',name:'全部拒绝才拒绝'},{id:'block_for_review',name:'出现拒绝则暂停核对'}]}/></div>)}<Button variant="outline" disabled={nodes.length>=5} onClick={()=>setNodes([...nodes,{who:[],pass:'all',reject:'any_reject'}])}>添加后续节点</Button><Button disabled={!templateKey||nodes.some(n=>!n.who.length)||busy||!!unknown} onClick={()=>send({operation:'publish',id:templateKey,orgId:org,definition:{businessType:'personnel.regularize',adapterVersion:'r1-regularize-v1',entry:'node1',fields:{},nodes:[...nodes.map((n,i)=>({id:'node'+(i+1),type:'review',assignees:n.who,passPolicy:n.pass,rejectPolicy:n.reject,next:i===nodes.length-1?'end':'node'+(i+2)})),{id:'end',type:'end'}],interventionTargets:nodes.map((_,i)=>'node'+(i+1)),notificationTemplateVersion:null}})}>发布新版本</Button></details>}
 <details><summary>登记管理委托</summary><p>开始与结束相同会登记为空有效期，不产生管理权限。</p><p>所选组织的查询、转交、干预和撤销；双方仍须具有当前权限。</p><Pick label="受托人" value={delegate} onChange={setDelegate} items={options.members.filter((m:any)=>m.id!==options.userId)}/><label>开始时间<Input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束时间<Input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><Button disabled={!delegate||!start||!end||busy||!!unknown} onClick={()=>send({operation:'createDelegation',delegateId:delegate,actions:['read','manage.transfer','manage.intervene','manage.revoke'],businessTypes:['personnel.regularize'],scope:[org],fields:['record'],startAt:Date.parse(start),endAt:Date.parse(end)})}>登记待接受委托</Button></details>
 {options.delegations.map((d:any)=><div key={d.id} className="rounded border p-2"><p>{d.principalId} → {d.delegateId} · {names[d.status]} · {new Date(d.endAt).toLocaleString()}</p>{d.status==='pending_acceptance'&&d.delegateId===options.userId&&<Button disabled={busy||!!unknown} onClick={()=>send({operation:'acceptDelegation',id:d.id,expectedRevision:d.revision,reason:'受托人确认接受'})}>接受</Button>}{['pending_acceptance','accepted'].includes(d.status)&&<Button variant="outline" disabled={busy||!!unknown} onClick={()=>send({operation:'revokeDelegation',id:d.id,expectedRevision:d.revision,reason:'当事人主动撤销'})}>撤销委托</Button>}</div>)}
 </>}</section>
 {action&&<section className="space-y-3 rounded border-2 p-5"><h2>{names[action.operation]??(action.decision==='approved'?'批准':'拒绝')} · {action.i.title}</h2>{['transferNode','intervene','revokeFlow','remind'].includes(action.operation)&&<Pick label="管理委托（可留空）" value={actionDelegation} onChange={setActionDelegation} items={(options?.delegations??[]).filter((d:any)=>d.status==='accepted'&&d.delegateId===options.userId).map((d:any)=>({id:d.id,name:d.principalId+' 的委托'}))}/>}<Input aria-label="办理原因" placeholder="填写办理原因" value={reason} onChange={e=>setReason(e.target.value)}/>{action.operation==='transferNode'&&<Pick label="新审批人" value={target} onChange={setTarget} items={options?.members??[]}/>} {action.operation==='intervene'&&<Input aria-label="模板许可节点" placeholder="模板许可节点编号" value={target} onChange={e=>setTarget(e.target.value)}/>}<Button disabled={!reason||busy||!!unknown||['transferNode','intervene'].includes(action.operation)&&!target} onClick={()=>send({operation:action.operation,id:action.i.id,expectedRevision:action.i.revision,generation:action.i.generation,reason,...(actionDelegation&&action.operation!=='decide'?{delegationId:actionDelegation}:{}),...(action.operation==='decide'?{nodeRevision:action.i.nodeRevision,decision:action.decision}:action.operation==='transferNode'?{nodeRevision:action.i.nodeRevision,assignees:[target]}:action.operation==='intervene'?{targetNode:target}:{})})}>提交</Button><Button variant="outline" onClick={()=>setAction(null)}>关闭</Button></section>}
 </main>;
}
