'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={records:R[];employees:{id:string;name:string;code:string;status:string;org:string}[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={submitted:'待复核',active:'在用',rejected:'未通过',withdrawn:'已撤回',suspended:'已停用'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[status,setStatus]=useState('all');
 async function load(){try{const response=await fetch('/api/instructor-directory',{cache:'no-store'}),d=await response.json() as Data&{error?:string};if(!response.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 const hr=['admin','hr'].includes(data?.role??''),records=data?.records??[],record=records.find(r=>r.id===detail),employee=(r:R)=>data?.employees.find(e=>e.id===r.employeeId),rows=records.filter(r=>(status==='all'||r.status===status)&&[r.payload.name,r.payload.title,r.payload.description,employee(r)?.org,labels[r.status]].join(' ').includes(search)).reverse();
 function open(action:string,r?:R,accepted?:boolean){setError('');setForm({action,id:r?.id??'',employeeId:'',title:'',description:'',evidence:'',accepted:String(accepted)});}
 async function submit(e:FormEvent){e.preventDefault();if(!data||!form||busy)return;setBusy(true);setError('');try{const command={...form,...(form.action==='review'?{accepted:form.accepted==='true'}:{})},response=await fetch('/api/instructor-directory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await response.json() as {error?:string};if(!response.ok)throw Error(d.error);setForm(null);setNotice('内部讲师记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex flex-wrap gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/instructor-campaigns" className="text-link">认证报名</Link><Link href="/instructor-development" className="text-link">培养任务</Link><Link href="/instructor-trials" className="text-link">试讲评审</Link><Link href="/instructors" className="text-link">课程讲师认证</Link><Link href="/reports?dataset=instructorSchedule" className="text-link">授课安排</Link><Link href="/training-sessions" className="text-link">培训场次</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">INTERNAL INSTRUCTORS</div><h1>内部讲师名册</h1><p className="mt-2 text-sm text-slate-500">HR提名，经其他HR独立复核后入册。讲师等级按核定依据登记，授课领域说明用于培训安排参考。</p></div><Button variant="outline" onClick={load}>刷新</Button></div><p className="mb-5 text-sm text-slate-500">入册不替代课程版本认证，也不自动授予积分或课酬。停用保留原记录；重新提名产生新版本。离职人员的历史记录保留，不能重新入册。</p>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}
 <section className="panel"><div className="section-head gap-4 flex-wrap"><Input className="max-w-md" aria-label="搜索内部讲师" placeholder="搜索姓名、等级、领域或组织" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><select className="rounded border p-2" aria-label="讲师记录状态" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">全部可见状态</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{hr&&<Button onClick={()=>open('nominate')}>提名内部讲师</Button>}</div><Table><TableHeader><TableRow>{['讲师 / 当前组织','等级 / 授课领域','版本','状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*15,page*15).map(r=><TableRow key={r.id}><TableCell>{employee(r)?.name??r.payload.name}<div className="text-sm text-slate-500">{employee(r)?.org} · {employee(r)?.status}</div></TableCell><TableCell>{r.payload.title}<p className="max-w-md whitespace-pre-wrap text-sm text-slate-500">{r.payload.description}</p></TableCell><TableCell>V{r.payload.version}</TableCell><TableCell>{employee(r)?.status==='离职'&&r.status==='active'?'人员已离职 · 待HR停用':labels[r.status]}</TableCell><TableCell><div className="flex flex-wrap gap-2">{hr&&<Button size="sm" variant="ghost" onClick={()=>setDetail(r.id)}>办理记录</Button>}{hr&&r.status==='submitted'&&r.createdBy===data?.userId&&<Button size="sm" variant="outline" onClick={()=>open('withdraw',r)}>撤回</Button>}{hr&&r.employeeId!==data?.employeeId&&r.status==='submitted'&&r.createdBy!==data?.userId&&<><Button size="sm" onClick={()=>open('review',r,true)}>复核通过</Button><Button size="sm" variant="outline" onClick={()=>open('review',r,false)}>不通过</Button></>}{hr&&r.employeeId!==data?.employeeId&&r.status==='active'&&<Button size="sm" variant="outline" onClick={()=>open('suspend',r)}>停用</Button>}</div></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">暂无可见的内部讲师记录</p>}<div className="flex justify-end items-center gap-3 mt-4"><span className="text-sm">{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{form?.action==='nominate'?'提名内部讲师':form?.action==='review'?(form.accepted==='true'?'独立复核通过':'独立复核不予通过'):form?.action==='withdraw'?'撤回提名':'停用内部讲师'}</DialogTitle><DialogDescription>请根据已核实的人才培养或师资管理依据办理。停用不自动取消已有排期或课程认证，应另行核对相关安排。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='nominate'&&<><label className="field"><span>员工</span><select required className="rounded border p-2" value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">请选择员工</option>{data?.employees.filter(e=>e.status!=='离职').map(e=><option key={e.id} value={e.id}>{e.code} · {e.name} · {e.org}</option>)}</select></label><label className="field"><span>讲师等级（按核定依据登记）</span><Input required maxLength={100} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field"><span>授课领域说明</span><textarea required minLength={5} maxLength={1000} rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></>}<label className="field"><span>提名依据 / 办理意见</span><textarea required minLength={5} maxLength={2000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{record?.payload.name} · V{record?.payload.version}</DialogTitle><DialogDescription>{record&&labels[record.status]}</DialogDescription></DialogHeader>{record&&<>{Object.entries({提名依据:record.payload.evidence,复核意见:record.payload.verification,撤回或停用原因:record.payload.closedReason}).filter(([,v])=>v).map(([k,v])=><div key={k}><p className="text-sm text-slate-500">{k}</p><p className="whitespace-pre-wrap">{v}</p></div>)}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></>}</DialogContent></Dialog></main>;
}
