 'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {RatingLevel} from '@/lib/hris/performance-ratings';
import type {State} from '@/lib/hris/model';
const initial:RatingLevel[]=[{label:'优秀',min:80,max:100,minInclusive:true,maxInclusive:true,description:'',talentBand:3},{label:'达成',min:60,max:80,minInclusive:true,maxInclusive:false,description:'',talentBand:2},{label:'待改进',min:0,max:60,minInclusive:true,maxInclusive:false,description:'',talentBand:1}];
const interval=(l:RatingLevel)=>`${l.minInclusive?'[':'('}${l.min}, ${l.max}${l.maxInclusive?']':')'}`;
export default function Workspace(){
 const [data,setData]=useState<{records:R[];revision:number}|null>(null),[orgs,setOrgs]=useState<State['orgs']>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[form,setForm]=useState<{id?:string;title:string;orgId:string}|null>(null),[levels,setLevels]=useState<RatingLevel[]>(initial),[detail,setDetail]=useState<R|null>(null);
 async function load(){try{const [r,h]=await Promise.all([fetch('/api/performance-ratings',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]);const d=await r.json() as {records:R[];revision:number;error?:string},c=await h.json() as {state:State;error?:string};if(!r.ok)throw Error(d.error);if(!h.ok)throw Error(c.error);setData(d);setOrgs(c.state.orgs);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 async function send(command:unknown){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/performance-ratings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('等级方案已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function edit(r?:R){setError('');setForm({...(r?{id:r.id}:{}),title:r?.payload.title??'',orgId:r?.payload.orgId??''});setLevels(r?.payload.ratingLevels?.map(l=>({...l}))??initial.map(l=>({...l})));}
 function update(i:number,patch:Partial<RatingLevel>){setLevels(levels.map((l,j)=>j===i?{...l,...patch}:l));}
 function submit(e:FormEvent){e.preventDefault();send({action:form?.id?'edit':'create',...form,levels});}
 return <main className="main-content mx-auto max-w-7xl"><Link className="text-link" href="/performance">返回绩效管理</Link><div className="page-head mt-5"><div><h1>绩效等级方案</h1><p className="mt-2 text-sm text-slate-500">按总分匹配等级，定版后供同组织周期选择。周期保留创建时的版本，后续修订不改变既有结果。</p></div><Button disabled={!data||busy} onClick={()=>edit()}>新增方案</Button></div>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel"><Table><TableHeader><TableRow>{['方案','组织','版本 / 状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.records.slice().reverse().map(r=><TableRow key={r.id}><TableCell>{r.payload.title}</TableCell><TableCell>{orgs.find(o=>o.id===r.payload.orgId)?.name??'—'}</TableCell><TableCell>v{r.payload.version} · {({draft:'草稿',sealed:'已定版',archived:'已归档'} as Record<string,string>)[r.status]}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setDetail(r)}>详情</Button>{r.status==='draft'&&<><Button variant="outline" disabled={busy} onClick={()=>edit(r)}>编辑</Button><Button disabled={busy} onClick={()=>send({action:'seal',id:r.id})}>定版</Button></>}{r.status==='sealed'&&!data.records.some(x=>x.payload.definitionRootId===r.payload.definitionRootId&&(x.status==='draft'||(x.status==='sealed'&&x.payload.version!>r.payload.version!)))&&<Button variant="outline" disabled={busy} onClick={()=>send({action:'revise',id:r.id})}>创建修订版</Button>}{r.status!=='archived'&&<Button variant="ghost" disabled={busy} onClick={()=>send({action:'archive',id:r.id})}>归档</Button>}</div></TableCell></TableRow>)}</TableBody></Table>{data&&!data.records.length&&<p className="p-6 text-slate-500">尚无等级方案；现有周期继续沿用原三档规则。</p>}</section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{form?.id?'编辑等级草稿':'新增等级方案'}</DialogTitle><DialogDescription>等级从高到低排列，区间不能重叠；留有空隙时，未匹配总分不能发布。人才档位用于已有三档盘点，请明确映射。</DialogDescription></DialogHeader>{form&&<form className="space-y-4" onSubmit={submit}>{error&&<p role="alert" className="text-red-700">{error}</p>}<label className="field"><span>方案名称</span><Input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field"><span>所属组织</span><Select disabled={!!form.id} value={form.orgId||'none'} onValueChange={orgId=>setForm({...form,orgId})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择组织</SelectItem>{orgs.filter(o=>o.status==='启用').map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></label>{levels.map((l,i)=><fieldset className="rounded border p-4 space-y-3" key={i}><legend>等级 {i+1} · {interval(l)}</legend><label className="field"><span>等级名称</span><Input required maxLength={200} value={l.label} onChange={e=>update(i,{label:e.target.value})}/></label><div className="form-grid">{(['min','max'] as const).map(k=><label className="field" key={k}><span>{k==='min'?'下限':'上限'}</span><Input type="number" required min={-1000000} max={1000000} step="0.01" value={Number.isFinite(l[k])?l[k]:''} onChange={e=>update(i,{[k]:e.target.value===''?NaN:Number(e.target.value)})}/></label>)}</div><div className="flex flex-wrap gap-5">{(['minInclusive','maxInclusive'] as const).map(k=><label className="flex items-center gap-2" key={k}><Checkbox checked={l[k]} onCheckedChange={v=>update(i,{[k]:v===true})}/>{k==='minInclusive'?'包含下限':'包含上限'}</label>)}</div><label className="field"><span>人才盘点档位</span><Select value={String(l.talentBand)} onValueChange={v=>update(i,{talentBand:Number(v) as 1|2|3})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[['1','低档'],['2','中档'],['3','高档']].map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label><label className="field"><span>等级说明</span><textarea className="w-full rounded border p-2" maxLength={2000} value={l.description} onChange={e=>update(i,{description:e.target.value})}/></label><Button type="button" variant="ghost" disabled={levels.length<=2} onClick={()=>setLevels(levels.filter((_,j)=>i!==j))}>移除等级</Button></fieldset>)}<Button type="button" variant="outline" disabled={levels.length>=20} onClick={()=>setLevels([...levels,{label:'',min:0,max:1,minInclusive:true,maxInclusive:false,description:'',talentBand:1}])}>在末尾添加等级</Button><div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setForm(null)}>取消</Button><Button disabled={busy||!form.orgId||form.orgId==='none'}>{busy?'保存中…':'保存草稿'}</Button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{detail?.payload.title} · v{detail?.payload.version}</DialogTitle><DialogDescription>已被周期采用的版本和历史结果不随归档或修订改变。</DialogDescription></DialogHeader>{detail?.payload.ratingLevels?.map(l=><div className="rounded border p-3" key={l.label}><b>{l.label} · {interval(l)}</b><p>人才盘点：{['','低档','中档','高档'][l.talentBand]}</p><p className="whitespace-pre-wrap">{l.description}</p></div>)}</DialogContent></Dialog></main>;
}
