import { CONTRACT_FIELDS } from '../contracts/rules.js';
/** Real schema/DTO catalogs for DEC-080. Functional rights never imply a data scope. */
import type { ButtonDefinition, DataOperation, ObjectDefinition } from './object-permission.js';

export const ORG_EMPLOYEE_APP = 'TenantBase';
const systemFields = [
  'id',
  'tenantId',
  'revision',
  'versionId',
  'versionNo',
  'previousVersionId',
  'createdAt',
  'updatedAt',
  'createdBy',
];
const button = (code: string, level: ButtonDefinition['level'], requires?: DataOperation): ButtonDefinition =>
  requires ? { code, level, requires } : { code, level };
const crud = [
  button('create', 'list', 'create'),
  button('update', 'detail', 'update'),
  button('delete', 'detail', 'delete'),
];
function object(code: string, fields: readonly string[], buttons = crud, system: readonly string[] = []) {
  const systems = new Set([...systemFields, ...system]);
  return {
    code: `TenantBase.${code}`,
    application: ORG_EMPLOYEE_APP,
    fields: [...new Set([...fields, ...systems])].map((code) => ({ code, system: systems.has(code) })),
    buttons,
  } satisfies ObjectDefinition;
}
const jobCommon = [
  'name',
  'code',
  'startDate',
  'stopDate',
  'effectiveDate',
  'enabled',
  'establishedOn',
  'displayOrder',
  'qualificationId',
  'sourceCode',
];
const ranges = ['levelTypeId', 'minLevelId', 'maxLevelId', 'minGradeId', 'maxGradeId'];
const assignment = [
  'sequenceId',
  'professionalLineId',
  ...ranges,
  'isKey',
  'isConfidential',
  'syncSequenceToAssignments',
];
const jobButtons = [...crud, button('import', 'list'), button('validate', 'detail')];
const job = (code: string, fields: readonly string[], system: readonly string[] = []) =>
  object(code, [...jobCommon, ...fields], jobButtons, [...system, 'kind', 'objectId']);

export const MODULE_OBJECTS = {
  contract: object(
    'EmploymentContract',
    [...CONTRACT_FIELDS, 'employeeId'],
    [
      ...crud,
      button('renew', 'detail', 'update'),
      button('change', 'detail', 'update'),
      button('terminate', 'detail', 'update'),
      button('import', 'list'),
      button('withdraw', 'detail', 'update'),
      button('createApplication', 'list', 'create'),
      button('renewApplication', 'detail', 'update'),
      button('changeApplication', 'detail', 'update'),
      button('terminateApplication', 'detail', 'update'),
    ],
    [
      'status',
      'approvalStatus',
      'signingCount',
      'previousContractId',
      'rootContractId',
      'versionNo',
      'operation',
      'mode',
      'targetId',
      'targetRevision',
      'resultId',
      'systemInitiated',
      'rowType',
    ],
  ),
  contractSettings: object('ContractSettings', [
    'autoRenew',
    'autoTerminate',
    'autoNumber',
    'accumulateRehire',
    'postExitTypeIds',
    'renewalTypeIds',
    'indefiniteTypeIds',
    'uniqueFields',
  ]),
  contractRules: object('ContractRenewalRule', ['name', 'priority', 'orgIds', 'personIds', 'enabled', 'details']),
  contractType: object('ContractType', ['code', 'name', 'enabled']),
  contractCompany: object('ContractCompany', ['code', 'name', 'enabled']),
  organization: object(
    'Organization',
    [
      'code',
      'name',
      'shortName',
      'broadType',
      'enabled',
      'startDate',
      'stopDate',
      'effectiveDate',
      'establishedOn',
      'personInChargeId',
      'hrbpId',
      'shopOwnerId',
      'costCenterId',
      'location',
      'remarks',
      'displayOrder',
      'isVirtual',
      'parents',
      'sourceCode',
      'parentId',
    ],
    [
      ...crud,
      button('reserve', 'list', 'create'),
      button('release', 'detail', 'delete'),
      button('validate', 'detail'),
      button('import', 'list'),
    ],
    ['fullName', 'level', 'resource', 'dimension', 'status', 'reason', 'orgId'],
  ),
  jobLayer: job('JobLayer', ['layerLevel']),
  jobGrade: job('JobGrade', ['grade', 'scoreLow', 'scoreHigh', 'layerId']),
  jobLevelType: job('JobLevelType', []),
  jobLevel: job('JobLevel', ['level', 'levelTypeId', 'minGradeId', 'maxGradeId']),
  jobSequence: job(
    'JobSequence',
    ['parentId', 'levelTypeId', 'source', 'externalId'],
    [
      'level',
      ...['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth'].map(
        (prefix) => `${prefix}SequenceId`,
      ),
    ],
  ),
  jobProfessionalLine: job('JobProfessionalLine', ['parentId'], ['level']),
  jobPost: job('JobPost', [...assignment, 'competencyModelId', 'responsibilities', 'requirements', 'evaluationScore']),
  jobPosition: job(
    'Position',
    [...assignment, 'orgId', 'postId', 'parents', 'workLocation', 'standardPositionId'],
    ['directParentId', 'dottedParentId', 'directSequence', 'dottedSequence'],
  ),
  establishment: object(
    'OrganizationEstablishment',
    [
      'name',
      'code',
      'periodType',
      'maintenanceMode',
      'startMonth',
      'subdivision',
      'unmatchedPolicy',
      'enabled',
      'startDate',
      'stopDate',
      'effectiveDate',
      'excludedOrgIds',
      'occupancyRanges',
      'orgId',
      'schemeId',
      'periodStart',
      'localCapacity',
      'inclusiveCapacity',
      'reservedLocal',
      'reservedInclusive',
      'strictControl',
      'syncParents',
      'subdivisions',
      'positionId',
      'adjustmentThrough',
      'capacityIds',
      'transferIn',
      'transferOut',
    ],
    [...crud, button('copy', 'list', 'create'), button('execute', 'detail', 'update'), button('report', 'detail')],
    [
      'capacityId',
      'status',
      'reason',
      'periodEnd',
      'scheme',
      'actualLocal',
      'actualInclusive',
      'pendingLocal',
      'pendingInclusive',
      'availableLocal',
      'availableInclusive',
      'isOverstaffed',
      'error',
      'sourceCapacityId',
      'targetCapacityId',
      'successCount',
      'failureCount',
      'items',
      'jobId',
      'attempts',
      'message',
      'recipientUserId',
      'readAt',
      'completedAt',
      'startedAt',
      'failureReason',
      'attempt',
    ],
  ),
  employmentSettings: object('EmploymentSettings', [
    'allowDirectTransfer',
    'unrestrictTargetDepartment',
    'autoPopulate',
  ]),
  employmentCustomField: object('EmploymentCustomField', ['name', 'objectType', 'valueType', 'inherit'], crud, [
    'code',
  ]),
  employee: object('Employee', ['code', 'name'], [button('Employee.Create', 'list', 'create')], ['status']),
  employmentRecord: object(
    'EmploymentRecord',
    [
      'kind',
      'mode',
      'initiator',
      'transferTypeCode',
      'reasonCode',
      'effectiveDate',
      'lastWorkDate',
      'formId',
      'staffId',
      'departmentId',
      'positionId',
      'postId',
      'levelId',
      'gradeId',
      'place',
      'directManagerId',
      'dottedManagerId',
      'employmentType',
      'employmentSource',
      'employmentForm',
      'sequenceId',
      'professionalLineId',
      'isKeyPerson',
      'dimension1',
      'dimension2',
      'dimension3',
      'dimension4',
      'dimension5',
      'jobNumber',
      'remarks',
      'isDepartmentHead',
      'isStoreManager',
      'addedSubordinateIds',
      'transferTypeCode',
      'reasonCode',
      'employType',
    ],
    [
      button('Employment.Create', 'detail', 'create'),
      button('Transfer.Hr', 'detail', 'create'),
      button('Transfer.Manager', 'detail', 'create'),
      button('Transfer.Self', 'detail', 'create'),
      button('EmploymentRecord.LineOp.Transfer', 'list_row', 'create'),
      button('Employment.Tranfer', 'list', 'create'),
      button('Employment.Edit', 'detail', 'update'),
      button('Employment.Delete', 'detail', 'delete'),
      button('Employment.Submit', 'detail', 'update'),
      button('Employment.Withdraw', 'detail', 'update'),
      // R1-T11：调动管理视图「撤销」未审批完成的申请（`08` §6，AC-TRF-07）
      button('Employment.Revoke', 'detail', 'update'),
      button('Employment.Import', 'list'),
      button('Employment.Preview', 'detail'),
      // R1-T08：生效失败 / 挂起的申请修正后重试（DEC-052）
      button('Employment.RetryActivation', 'detail', 'update'),
    ],
    [
      'employeeId',
      'employeeRevision',
      'status',
      'entryDate',
      'serviceType',
      'stopDate',
      'previousRecordId',
      'isCurrent',
      'isLatest',
      'isInserted',
      // 变动类型由系统联动写入（F-006，W-416），不是可编辑字段。
      'changeType',
      'activation',
    ],
  ),
} as const satisfies Record<string, ObjectDefinition>;

export type ModuleAction =
  | { readonly kind: 'object'; readonly objectCode: string; readonly operation: 'view' | DataOperation }
  | { readonly kind: 'admin'; readonly capability: string };
const tenantConfiguration: ModuleAction = { kind: 'admin', capability: 'other_settings' };
const actions: Record<string, ModuleAction> = {
  'tenant.settings.read': tenantConfiguration,
  'tenant.settings.write': tenantConfiguration,
  'tenant.employment.configuration.write': tenantConfiguration,
};
for (const [name, definition] of Object.entries({
  org: MODULE_OBJECTS.organization,
  job: MODULE_OBJECTS.jobPost,
  establishment: MODULE_OBJECTS.establishment,
  employment: MODULE_OBJECTS.employmentRecord,
})) {
  for (const [verb, operation] of Object.entries({
    read: 'view',
    write: 'update',
    create: 'create',
    update: 'update',
    delete: 'delete',
  } as const)) {
    actions[`tenant.${name}.${verb}`] = { kind: 'object', objectCode: definition.code, operation };
  }
}
export const MODULE_ACTIONS: Readonly<Record<string, ModuleAction>> = actions;
