/**
 * 直接依赖图：区域 api-modules-permission（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
/* eslint-disable max-len -- 生成文件，键含完整路径 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/permission/admin-http.ts#adminGuard': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/permission/admin-http.ts#platformCommandId': ['#COMMAND_ID'],
  'apps/api/src/modules/permission/admins.ts#assertCanDelegate': [
    '#assertProfilesExist',
    '#grantableSetsOf',
    'apps/api/src/modules/permission/auto-held.ts#assertNotAutoHeld',
  ],
  'apps/api/src/modules/permission/admins.ts#assertContractConfigurationGrant': ['#grantableSetsOf'],
  'apps/api/src/modules/permission/admins.ts#createAdmin': [
    '#assertCanDelegate',
    '#assertContractConfigurationGrant',
    '#viewOf',
    '#writeGrantableSets',
    'apps/api/src/modules/permission/audit.ts#audit',
    'apps/api/src/modules/permission/members.ts#assertActiveMember',
  ],
  'apps/api/src/modules/permission/admins.ts#getAdmin': ['#loadAdmin', '#viewOf'],
  'apps/api/src/modules/permission/admins.ts#grantableSetsOf': [
    'packages/domain/src/permission/admin-roles.ts#isAdminRole',
  ],
  'apps/api/src/modules/permission/admins.ts#listAdmins': ['#viewOf'],
  'apps/api/src/modules/permission/admins.ts#updateAdmin': [
    '#assertCanDelegate',
    '#assertContractConfigurationGrant',
    '#loadAdmin',
    '#viewOf',
    '#writeGrantableSets',
    'apps/api/src/modules/permission/audit.ts#audit',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
  ],
  'apps/api/src/modules/permission/admins.ts#viewOf': ['packages/domain/src/permission/admin-roles.ts#isAdminRole'],
  'apps/api/src/modules/permission/audit.ts#audit': ['#auditAs'],
  'apps/api/src/modules/permission/audit.ts#auditAs': ['apps/api/src/audit/record.ts#recordAudit', '#revisionOf'],
  'apps/api/src/modules/permission/auto-held.ts#AUTO_HELD_CODES': [
    'packages/domain/src/platform/standard-presets.ts#STANDARD_PROFILES',
  ],
  'apps/api/src/modules/permission/auto-held.ts#assertNotAutoHeld': ['#isAutoHeld'],
  'apps/api/src/modules/permission/auto-held.ts#isAutoHeld': ['#AUTO_HELD_CODES'],
  'apps/api/src/modules/permission/catalog.ts#objectCatalog': [
    'packages/domain/src/evaluation/catalog.ts#EVALUATION_OBJECTS',
    'packages/domain/src/evaluation/flow-catalog.ts#EVALUATION_FLOW_OBJECTS',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
    'packages/domain/src/permission/object-permission.ts#ObjectCatalog',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_PAGES',
    'packages/domain/src/survey360/catalog.ts#SURVEY360_OBJECTS',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#applyGrantScopes': ['#assignUserAppScope'],
  'apps/api/src/modules/permission/data-scope-admin.ts#assignUserAppScope': [
    '#getMou',
    '#getUserAppScope',
    '#notFound',
    '#recordScopeChange',
    '#validateRefs',
    '#virtualMou',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
    'apps/api/src/modules/permission/members.ts#assertActiveMember',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#createMou': [
    '#lockMouHierarchy',
    '#recordScopeChange',
    '#replaceRefs',
    '#validateParent',
    '#validateRefs',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#getMou': ['#notFound', '#orgRefs'],
  'apps/api/src/modules/permission/data-scope-admin.ts#getUserAppScope': [
    '#orgRefs',
    'apps/api/src/modules/permission/members.ts#assertActiveMember',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#grantScopePrefill': [
    'apps/api/src/modules/permission/members.ts#assertActiveMember',
    'apps/api/src/modules/permission/profiles.ts#loadProfile',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#lockMouHierarchy': ['#lockMouHierarchyOf'],
  'apps/api/src/modules/permission/data-scope-admin.ts#lockMouHierarchyOf': [
    'apps/api/src/advisory-lock.ts#advisoryLock',
    'apps/api/src/advisory-lock.ts#asUuid',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#recordScopeChange': [
    'apps/api/src/modules/permission/audit.ts#audit',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#updateMou': [
    '#assertMouDeletable',
    '#lockMouHierarchy',
    '#notFound',
    '#orgRefs',
    '#recordScopeChange',
    '#replaceRefs',
    '#validateParent',
    '#validateRefs',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
  ],
  'apps/api/src/modules/permission/data-scope-admin.ts#validateParent': ['#getMou', '#notFound'],
  'apps/api/src/modules/permission/data-scope-admin.ts#validateRefs': ['#notFound'],
  'apps/api/src/modules/permission/data-scope-admin.ts#virtualMou': ['#orgRefs', '#recordScopeChange', '#replaceRefs'],
  'apps/api/src/modules/permission/data-scope-routes.ts#appParam': [
    'apps/api/src/modules/permission/data-scope-schemas.ts#scopeAppCode',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#mouViewGuard': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:DELETE /api/tenant/permission/mous/:id': [
    'apps/api/src/modules/permission/data-scope-admin.ts#updateMou',
    '#BASE',
    '#scopeAdminCommand',
    '#scopeAdminGuard',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:GET /api/tenant/permission/grant-prefill/:userId/:profileId':
    [
      'apps/api/src/modules/permission/data-scope-admin.ts#grantScopePrefill',
      '#BASE',
      '#scopeAdminGuard',
      'apps/api/src/modules/permission/http.ts#idParam',
    ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:GET /api/tenant/permission/mous': [
    'apps/api/src/modules/permission/data-scope-admin.ts#listMous',
    '#BASE',
    '#mouViewGuard',
    '#page',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:GET /api/tenant/permission/mous/:id': [
    'apps/api/src/modules/permission/data-scope-admin.ts#getMou',
    '#BASE',
    '#mouViewGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:GET /api/tenant/permission/scopes/:userId/:appCode': [
    'apps/api/src/modules/permission/data-scope-admin.ts#getUserAppScope',
    '#BASE',
    '#appParam',
    '#scopeAdminGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:POST /api/tenant/permission/mous': [
    'apps/api/src/modules/permission/data-scope-admin.ts#createMou',
    '#BASE',
    '#scopeAdminCommand',
    '#scopeAdminGuard',
    'apps/api/src/modules/permission/data-scope-schemas.ts#mouBody',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    'apps/api/src/modules/permission/http.ts#parseBody',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:PUT /api/tenant/permission/mous/:id': [
    'apps/api/src/modules/permission/data-scope-admin.ts#updateMou',
    '#BASE',
    '#scopeAdminCommand',
    '#scopeAdminGuard',
    'apps/api/src/modules/permission/data-scope-schemas.ts#mouBody',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    'apps/api/src/modules/permission/http.ts#parseBody',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#route:PUT /api/tenant/permission/scopes/:userId/:appCode': [
    'apps/api/src/modules/permission/data-scope-admin.ts#assignUserAppScope',
    '#BASE',
    '#appParam',
    '#scopeAdminCommand',
    '#scopeAdminGuard',
    'apps/api/src/modules/permission/data-scope-schemas.ts#scopeAssignmentBody',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    'apps/api/src/modules/permission/http.ts#parseBody',
  ],
  'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminGuard': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/permission/data-scope-schemas.ts#grantScopeBody': [
    '#defaultScope',
    '#grantScopeFields',
    '#mouScope',
    '#orgScope',
  ],
  'apps/api/src/modules/permission/data-scope-schemas.ts#grantScopeFields': ['#scopeAppCode'],
  'apps/api/src/modules/permission/data-scope-schemas.ts#mouBody': ['#orgRanges'],
  'apps/api/src/modules/permission/data-scope-schemas.ts#orgRanges': ['#scopeOrgRefBody'],
  'apps/api/src/modules/permission/data-scope-schemas.ts#orgScope': ['#orgRanges'],
  'apps/api/src/modules/permission/data-scope-schemas.ts#scopeAssignmentBody': [
    '#defaultScope',
    '#mouScope',
    '#orgScope',
  ],
  'apps/api/src/modules/permission/data-scope-schemas.ts#scopeOrgRefBody': [
    'packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS',
  ],
  'apps/api/src/modules/permission/employment-replay.ts#assertScope': [
    'apps/api/src/modules/employment/visibility.ts#isEmploymentRecordVisible',
    'apps/api/src/modules/permission/module-access.ts#scopeAllowsInTransaction',
  ],
  'apps/api/src/modules/permission/employment-replay.ts#authorizeEmploymentResult': [
    '#OBJECT',
    '#assertScope',
    '#currentTargets',
    '#footprints',
    '#linkedOnly',
    '#responseSnapshots',
    '#transferException',
    'apps/api/src/modules/permission/establishment-replay.ts#authorizeEstablishmentReplay',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/permission/employment-replay.ts#currentTargets': ['#rows'],
  'apps/api/src/modules/permission/employment-replay.ts#footprints': ['#MAX_EVENTS', '#rows'],
  'apps/api/src/modules/permission/employment-replay.ts#linkedOnly': ['#LINKED_ACTIONS'],
  'apps/api/src/modules/permission/employment-replay.ts#responseSnapshots': ['#responseSnapshots'],
  'apps/api/src/modules/permission/employment-replay.ts#transferException': ['#rows'],
  'apps/api/src/modules/permission/establishment-replay.ts#COPY_FIELDS': ['#CHANGED_FIELDS'],
  'apps/api/src/modules/permission/establishment-replay.ts#authorizeEstablishmentReplay': [
    '#CHANGED_FIELDS',
    '#COPY_FIELDS',
    '#MAX_FOOTPRINTS',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/permission/grants.ts#assertGrantable': [
    'apps/api/src/modules/permission/admins.ts#grantableSetsOf',
  ],
  'apps/api/src/modules/permission/grants.ts#createGrant': [
    'apps/api/src/modules/permission/audit.ts#audit',
    'apps/api/src/modules/permission/auto-held.ts#assertNotAutoHeld',
    'apps/api/src/modules/permission/data-scope-admin.ts#applyGrantScopes',
    '#assertGrantable',
    '#view',
    'apps/api/src/modules/permission/licenses.ts#consumeSeat',
    'apps/api/src/modules/permission/members.ts#assertActiveMember',
    'apps/api/src/modules/permission/profiles.ts#loadProfile',
  ],
  'apps/api/src/modules/permission/grants.ts#grantableProfiles': [
    'apps/api/src/modules/permission/admins.ts#grantableSetsOf',
  ],
  'apps/api/src/modules/permission/grants.ts#listGrants': ['#view'],
  'apps/api/src/modules/permission/grants.ts#revokeGrant': [
    'apps/api/src/modules/permission/audit.ts#audit',
    '#assertGrantable',
    '#view',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
    'apps/api/src/modules/permission/licenses.ts#lockLicenseType',
    'apps/api/src/modules/permission/licenses.ts#releaseSeat',
    'apps/api/src/modules/permission/profiles.ts#loadProfile',
  ],
  'apps/api/src/modules/permission/http.ts#idParam': ['#UUID'],
  'apps/api/src/modules/permission/http.ts#ifMatch': ['#IF_MATCH'],
  'apps/api/src/modules/permission/http.ts#objectCodeParam': ['#OBJECT_CODE'],
  'apps/api/src/modules/permission/job-result-scope.ts#authorizeJobResult': [
    'apps/api/src/modules/permission/module-contracts.ts#jobScopeReader',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/licenses.ts#consumeSeat': ['#currentOverage', '#lockLicenseType'],
  'apps/api/src/modules/permission/licenses.ts#currentOverage': ['#overageOf'],
  'apps/api/src/modules/permission/licenses.ts#licenseTypeKnown': ['#LICENSE_TYPE'],
  'apps/api/src/modules/permission/licenses.ts#listSeats': ['#licenseTypeKnown'],
  'apps/api/src/modules/permission/licenses.ts#lockLicenseType': [
    'apps/api/src/advisory-lock.ts#advisoryLock',
    'apps/api/src/advisory-lock.ts#asUuid',
  ],
  'apps/api/src/modules/permission/licenses.ts#releaseSeat': ['#lockLicenseType'],
  'apps/api/src/modules/permission/manager-identity.ts#managerIdentity': [
    'apps/api/src/modules/permission/scope-hierarchy.ts#expandScopeRoots',
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
    'apps/api/src/modules/permission/scope-persons.ts#currentPersons',
  ],
  'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction': ['#providers'],
  'apps/api/src/modules/permission/module-access.ts#editableModuleFields': [
    '#providers',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields': [
    '#providers',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/module-access.ts#getModuleViewableFieldsInTransaction': [
    '#providers',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/module-access.ts#linkedObjectScope': [
    '#providers',
    '#scopeAppOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/module-access.ts#personSql': [
    '#inIds',
    'apps/api/src/modules/permission/scope-persons.ts#managedPersonsSql',
    'apps/api/src/modules/permission/scope-persons.ts#reportingPersonsSql',
  ],
  'apps/api/src/modules/permission/module-access.ts#registerScopeProvider': ['#providers'],
  'apps/api/src/modules/permission/module-access.ts#resolveModuleScope': [
    '#providers',
    '#scopeAppOf',
    'apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE',
    'packages/domain/src/permission/module-actions.ts#ORG_EMPLOYEE_APP',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction': [
    '#providers',
    '#scopeAppOf',
    'apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/module-access.ts#scopeAllows': ['#terms'],
  'apps/api/src/modules/permission/module-access.ts#scopeAllowsInTransaction': ['#scopeSql'],
  'apps/api/src/modules/permission/module-access.ts#scopeAppOf': [
    'apps/api/src/modules/permission/catalog.ts#objectCatalog',
    'packages/domain/src/permission/module-actions.ts#ORG_EMPLOYEE_APP',
  ],
  'apps/api/src/modules/permission/module-access.ts#scopeSql': ['#inIds', '#personSql', '#terms'],
  'apps/api/src/modules/permission/module-access.ts#trimModuleResponse': ['#getModuleViewableFields'],
  'apps/api/src/modules/permission/module-capacity-authorization.ts#capacityContext': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/permission/module-capacity-authorization.ts#employmentCapacityContext': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    '#capacityContext',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/permission/module-contracts.ts#jobScopeReader': ['#jobReader'],
  'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES': [
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/permission/module-route-access.ts#button': [
    'apps/api/src/authorization.ts#requirePermission',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/permission/module-route-access.ts#objectContext': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/permission/module-route-access.ts#requestScope': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    '#requestScopes',
  ],
  'apps/api/src/modules/permission/module-route-access.ts#visible': [
    'apps/api/src/modules/permission/module-access.ts#scopeAllows',
  ],
  'apps/api/src/modules/permission/module-route-access.ts#visibleJob': [
    'apps/api/src/modules/permission/module-contracts.ts#jobScopeReader',
    '#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/permission/module-route-access.ts#writeFields': [
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/permission/object-write.ts#requireObjectWrite': [
    'apps/api/src/authorization.ts#requirePermission',
  ],
  'apps/api/src/modules/permission/org-result-scope.ts#authorizeOrgResult': [
    'apps/api/src/modules/permission/module-access.ts#scopeAllows',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/owner-units.ts#authorizedUnits': ['#MAX_UNITS'],
  'apps/api/src/modules/permission/owner-units.ts#chooseUnit': [
    '#UNIT_NOT_FOUND',
    '#authorizedUnits',
    '#noUnit',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/owner-units.ts#noUnit': ['#NO_UNIT_MESSAGE'],
  'apps/api/src/modules/permission/profiles.ts#createProfile': [
    'apps/api/src/modules/permission/audit.ts#audit',
    '#view',
  ],
  'apps/api/src/modules/permission/profiles.ts#getProfileDetail': [
    'apps/api/src/modules/permission/catalog.ts#objectCatalog',
    '#loadProfile',
    '#loadProfileApps',
    '#view',
    'apps/api/src/modules/permission/subject.ts#loadObjectPermissions',
    'apps/api/src/modules/permission/tenant-catalog.ts#tenantObjectCatalog',
    'packages/domain/src/platform/standard-grants.ts#objectCatalogDigest',
  ],
  'apps/api/src/modules/permission/profiles.ts#listProfiles': ['#view'],
  'apps/api/src/modules/permission/profiles.ts#setObjectPermission': [
    'apps/api/src/modules/permission/audit.ts#audit',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
    '#getProfileDetail',
    '#loadProfile',
    '#loadProfileApps',
    '#replaceObjectRows',
    'apps/api/src/modules/permission/subject.ts#loadObjectPermissions',
    'apps/api/src/modules/permission/tenant-catalog.ts#tenantObjectCatalog',
    'apps/api/src/seeds/grant-ledger.ts#recordTenantSave',
    'packages/domain/src/permission/object-permission.ts#isWithinProfileApps',
    'packages/domain/src/permission/object-permission.ts#validateObjectPermission',
    'packages/domain/src/platform/standard-grants.ts#objectCatalogDigest',
  ],
  'apps/api/src/modules/permission/profiles.ts#view': ['apps/api/src/modules/permission/auto-held.ts#isAutoHeld'],
  'apps/api/src/modules/permission/public-down.ts#publicDownSql': [
    '#scopeOrgIds',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/permission/public-down.ts#readableSql': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    '#publicDownSql',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/admin-roles': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    '#BASE',
    'packages/domain/src/permission/admin-roles.ts#ADMIN_ROLES',
    'packages/domain/src/permission/admin-roles.ts#ADMIN_ROLE_NAMES',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/admins': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/admins.ts#listAdmins',
    '#BASE',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/admins/:id': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/admins.ts#getAdmin',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    '#BASE',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/grantable-profiles': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/grants.ts#grantableProfiles',
    '#BASE',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/grants': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/grants.ts#listGrants',
    '#BASE',
    'apps/api/src/modules/permission/schemas.ts#grantQuery',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/licenses': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/licenses.ts#listBalances',
    '#BASE',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/licenses/:licenseType/seats': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/licenses.ts#listSeats',
    '#BASE',
    '#seatPage',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/profiles': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/profiles.ts#listProfiles',
    '#BASE',
  ],
  'apps/api/src/modules/permission/routes.ts#route:GET /api/tenant/permission/profiles/:id': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/profiles.ts#getProfileDetail',
    '#BASE',
  ],
  'apps/api/src/modules/permission/routes.ts#route:POST /api/tenant/permission/admins': [
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/admins.ts#createAdmin',
    'apps/api/src/modules/permission/http.ts#parseBody',
    '#BASE',
    'apps/api/src/modules/permission/schemas.ts#adminBody',
  ],
  'apps/api/src/modules/permission/routes.ts#route:POST /api/tenant/permission/grants': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/grants.ts#createGrant',
    'apps/api/src/modules/permission/http.ts#parseBody',
    '#BASE',
    'apps/api/src/modules/permission/schemas.ts#grantBody',
  ],
  'apps/api/src/modules/permission/routes.ts#route:POST /api/tenant/permission/grants/:id/revoke': [
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/grants.ts#revokeGrant',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    '#BASE',
  ],
  'apps/api/src/modules/permission/routes.ts#route:POST /api/tenant/permission/profiles': [
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/http.ts#parseBody',
    'apps/api/src/modules/permission/profiles.ts#createProfile',
    '#BASE',
    'apps/api/src/modules/permission/schemas.ts#profileBody',
  ],
  'apps/api/src/modules/permission/routes.ts#route:PUT /api/tenant/permission/admins/:id': [
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/admins.ts#updateAdmin',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    'apps/api/src/modules/permission/http.ts#parseBody',
    '#BASE',
    'apps/api/src/modules/permission/schemas.ts#adminSetsBody',
  ],
  'apps/api/src/modules/permission/routes.ts#route:PUT /api/tenant/permission/profiles/:id/objects/:objectCode': [
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/catalog.ts#objectCatalog',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    'apps/api/src/modules/permission/http.ts#objectCodeParam',
    'apps/api/src/modules/permission/http.ts#parseBody',
    'apps/api/src/modules/permission/profiles.ts#setObjectPermission',
    '#BASE',
    'apps/api/src/modules/permission/schemas.ts#objectPermissionBody',
  ],
  'apps/api/src/modules/permission/schemas.ts#adminBody': [
    '#adminSetsBody',
    'packages/domain/src/permission/admin-roles.ts#ADMIN_ROLES',
  ],
  'apps/api/src/modules/permission/schemas.ts#adminSetsBody': [
    '#MAX_ITEMS',
    'packages/domain/src/permission/admin-roles.ts#ADMIN_ROLES',
  ],
  'apps/api/src/modules/permission/schemas.ts#grantBody': [
    'apps/api/src/modules/permission/data-scope-schemas.ts#grantScopeBody',
  ],
  'apps/api/src/modules/permission/schemas.ts#grantQuery': ['#optionalUuid'],
  'apps/api/src/modules/permission/schemas.ts#objectPermissionBody': [
    '#ITEM_CODE',
    '#MAX_ITEMS',
    '#code',
    'packages/domain/src/permission/object-permission.ts#BUTTON_LEVELS',
  ],
  'apps/api/src/modules/permission/schemas.ts#profileBody': ['#APP_CODE', '#LICENSE_TYPE', '#PROFILE_CODE', '#code'],
  'apps/api/src/modules/permission/scope-hierarchy.ts#expandScopeOrgSet': ['#MAX_SCOPE_IDS', '#scopeRows'],
  'apps/api/src/modules/permission/scope-hierarchy.ts#expandScopeRoots': ['#scopeHierarchyReader'],
  'apps/api/src/modules/permission/scope-hierarchy.ts#scopeHierarchyReader': ['#MAX_SCOPE_IDS', '#scopeRows'],
  'apps/api/src/modules/permission/scope-persons.ts#managedPersonsSql': ['#currentPersons'],
  'apps/api/src/modules/permission/scope-persons.ts#reportingPersonsSql': ['#currentPersons'],
  'apps/api/src/modules/permission/scope-policy-routes.ts#appParam': [
    'apps/api/src/modules/permission/data-scope-schemas.ts#scopeAppCode',
  ],
  'apps/api/src/modules/permission/scope-policy-routes.ts#configRoutes': [
    'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminCommand',
    'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    'apps/api/src/modules/permission/http.ts#parseBody',
  ],
  'apps/api/src/modules/permission/scope-policy-routes.ts#personLinkRoutes': [
    'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    '#BASE',
    'apps/api/src/modules/permission/scope-policy-service.ts#getPersonLink',
  ],
  'apps/api/src/modules/permission/scope-policy-routes.ts#route:GET /api/tenant/permission/person-links/:userId': [
    'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/scope-policy-service.ts#getPersonLink',
  ],
  'apps/api/src/modules/permission/scope-policy-routes.ts#route:GET /api/tenant/permission/profiles/:id/data-scopes/:appCode':
    [
      'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminGuard',
      'apps/api/src/modules/permission/http.ts#etag',
      'apps/api/src/modules/permission/http.ts#idParam',
      '#appParam',
      'apps/api/src/modules/permission/scope-policy-service.ts#getIdentityScope',
      'apps/api/src/modules/permission/scope-policy-service.ts#identityScopeBody',
    ],
  'apps/api/src/modules/permission/scope-policy-routes.ts#route:PUT /api/tenant/permission/profiles/:id/data-scopes/:appCode':
    [
      'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminCommand',
      'apps/api/src/modules/permission/data-scope-routes.ts#scopeAdminGuard',
      'apps/api/src/modules/permission/http.ts#etag',
      'apps/api/src/modules/permission/http.ts#idParam',
      'apps/api/src/modules/permission/http.ts#ifMatch',
      'apps/api/src/modules/permission/http.ts#parseBody',
      '#appParam',
      'apps/api/src/modules/permission/scope-policy-service.ts#identityScopeBody',
      'apps/api/src/modules/permission/scope-policy-service.ts#setIdentityScope',
    ],
  'apps/api/src/modules/permission/scope-policy-service.ts#BUILTIN_SCOPE_DATASOURCES': [
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
    'packages/domain/src/platform/standard-presets.ts#ESTABLISHMENT_SCHEME_DATASOURCE',
  ],
  'apps/api/src/modules/permission/scope-policy-service.ts#getIdentityScope': ['#identityTarget', '#identityWhere'],
  'apps/api/src/modules/permission/scope-policy-service.ts#getPersonLink': [
    'apps/api/src/modules/permission/members.ts#assertActiveMember',
    '#lastRevision',
  ],
  'apps/api/src/modules/permission/scope-policy-service.ts#identityTarget': [
    'apps/api/src/modules/permission/catalog.ts#objectCatalog',
    'apps/api/src/modules/permission/profiles.ts#loadProfile',
    '#BUILTIN_SCOPE_DATASOURCES',
    '#invalid',
  ],
  'apps/api/src/modules/permission/scope-policy-service.ts#lockIdentityScope': [
    'apps/api/src/advisory-lock.ts#asUuid',
    '#lockScopeObject',
    '#scopeLockProbe',
  ],
  'apps/api/src/modules/permission/scope-policy-service.ts#lockScopeObject': [
    'apps/api/src/advisory-lock.ts#advisoryLock',
    'apps/api/src/advisory-lock.ts#asUuid',
  ],
  'apps/api/src/modules/permission/scope-policy-service.ts#setIdentityScope': [
    'apps/api/src/modules/permission/data-scope-admin.ts#recordScopeChange',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
    'apps/api/src/modules/permission/profiles.ts#loadProfile',
    '#getIdentityScope',
    '#lockIdentityScope',
  ],
  'apps/api/src/modules/permission/scope-resolver.ts#linkedPerson': [
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
  ],
  'apps/api/src/modules/permission/scope-resolver.ts#managementRoots': [
    'apps/api/src/modules/permission/manager-identity.ts#managerIdentity',
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
    '#roleRoots',
  ],
  'apps/api/src/modules/permission/scope-resolver.ts#personnelCreationScope': [
    'apps/api/src/modules/permission/scope-hierarchy.ts#expandScopeRoots',
    '#managementRoots',
  ],
  'apps/api/src/modules/permission/scope-resolver.ts#roleRoots': [
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
    '#linkedPerson',
  ],
  'apps/api/src/modules/permission/subject.ts#loadObjectPermissions': ['#loadObjectPermissionRows'],
  'apps/api/src/modules/permission/tenant-catalog.ts#tenantObjectCatalog': [
    '#TENANT_FIELD_LIMIT',
    '#sources',
    'packages/domain/src/permission/object-permission.ts#ObjectCatalog',
  ],
  'apps/api/src/modules/permission/tenant-users.ts#accountsOf': [
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
  ],
  'apps/api/src/modules/permission/tenant-users.ts#getTenantUser': ['#memberQuery', '#notFound', '#viewsOf'],
  'apps/api/src/modules/permission/tenant-users.ts#listTenantUsers': ['#memberQuery', '#typeFilter', '#viewsOf'],
  'apps/api/src/modules/permission/tenant-users.ts#provisionAccount': [
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
  ],
  'apps/api/src/modules/permission/tenant-users.ts#registerExternalUser': [
    'apps/api/src/modules/permission/audit.ts#audit',
    '#getTenantUser',
    '#insertMembership',
    '#memberQuery',
    '#memberSnapshot',
    '#provisionAccount',
    '#updateMembership',
  ],
  'apps/api/src/modules/permission/tenant-users.ts#updateExternalUser': [
    'apps/api/src/modules/permission/audit.ts#audit',
    'apps/api/src/modules/permission/http.ts#revisionConflict',
    '#getTenantUser',
    '#memberQuery',
    '#notFound',
    '#updateMembership',
  ],
  'apps/api/src/modules/permission/tenant-users.ts#updateMembership': [
    'apps/api/src/modules/permission/http.ts#revisionConflict',
  ],
  'apps/api/src/modules/permission/tenant-users.ts#viewsOf': [
    'apps/api/src/modules/avatar/references.ts#userAvatars',
    '#accountsOf',
  ],
  'apps/api/src/modules/permission/user-provisioning.ts#keepBinding': [
    'apps/api/src/modules/permission/audit.ts#audit',
    'apps/api/src/modules/permission/tenant-users.ts#getTenantUser',
    'apps/api/src/modules/permission/tenant-users.ts#memberSnapshot',
    'apps/api/src/modules/permission/tenant-users.ts#provisionAccount',
    'apps/api/src/modules/permission/tenant-users.ts#updateMembership',
    '#conflict',
  ],
  'apps/api/src/modules/permission/user-provisioning.ts#lockPersonLink': [
    'apps/api/src/advisory-lock.ts#advisoryLock',
    'apps/api/src/advisory-lock.ts#asUuid',
  ],
  'apps/api/src/modules/permission/user-provisioning.ts#provisionEmployeeUser': [
    'apps/api/src/modules/permission/audit.ts#audit',
    'apps/api/src/modules/permission/tenant-users.ts#getTenantUser',
    'apps/api/src/modules/permission/tenant-users.ts#insertMembership',
    'apps/api/src/modules/permission/tenant-users.ts#memberSnapshot',
    'apps/api/src/modules/permission/tenant-users.ts#provisionAccount',
    'apps/api/src/modules/permission/tenant-users.ts#updateMembership',
    '#conflict',
    '#keepBinding',
    '#lockPersonLink',
  ],
  'apps/api/src/modules/permission/user-routes.ts#currentAvatar': [
    'apps/api/src/modules/avatar/references.ts#userAvatars',
  ],
  'apps/api/src/modules/permission/user-routes.ts#currentUser': [
    'apps/api/src/modules/permission/tenant-users.ts#getTenantUser',
  ],
  'apps/api/src/modules/permission/user-routes.ts#lifecycleRequest': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/admin-http.ts#platformCommandId',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    '#CAPABILITY',
    '#currentUser',
  ],
  'apps/api/src/modules/permission/user-routes.ts#registerBody': ['#businessIdentity'],
  'apps/api/src/modules/permission/user-routes.ts#route:GET /api/tenant/permission/users': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/tenant-users.ts#listTenantUsers',
    '#BASE',
    '#CAPABILITY',
    '#listQuery',
  ],
  'apps/api/src/modules/permission/user-routes.ts#route:GET /api/tenant/permission/users/:userId': [
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    '#BASE',
    '#CAPABILITY',
    '#currentUser',
  ],
  'apps/api/src/modules/permission/user-routes.ts#route:POST /api/tenant/permission/users': [
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/http.ts#parseBody',
    'apps/api/src/modules/permission/tenant-users.ts#internalUserByProfile',
    'apps/api/src/modules/permission/tenant-users.ts#registerExternalUser',
    '#BASE',
    '#CAPABILITY',
    '#currentAvatar',
    '#registerBody',
  ],
  'apps/api/src/modules/permission/user-routes.ts#route:PUT /api/tenant/permission/users/:userId': [
    'apps/api/src/modules/permission/admin-http.ts#adminCommand',
    'apps/api/src/modules/permission/admin-http.ts#adminGuard',
    'apps/api/src/modules/permission/http.ts#etag',
    'apps/api/src/modules/permission/http.ts#idParam',
    'apps/api/src/modules/permission/http.ts#ifMatch',
    'apps/api/src/modules/permission/http.ts#parseBody',
    'apps/api/src/modules/permission/tenant-users.ts#internalUserByProfile',
    'apps/api/src/modules/permission/tenant-users.ts#updateExternalUser',
    '#BASE',
    '#CAPABILITY',
    '#currentAvatar',
    '#updateBody',
  ],
  'apps/api/src/modules/permission/user-routes.ts#updateBody': ['#businessIdentity'],
};
