/**
 * 直接依赖图：区域 api-modules-approval（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/approval/access.ts#IDP_PLAN_OBJECT': ['packages/domain/src/idp/catalog.ts#IDP_OBJECTS'],
  'apps/api/src/modules/approval/access.ts#adminScope': ['#byBusinessScope', '#hasButton', '#listScopeOf'],
  'apps/api/src/modules/approval/access.ts#adminTargetScope': [
    '#businessScopes',
    '#listScopeOf',
    '#perBusinessType',
    'apps/api/src/modules/idp/plan-mentor.ts#isStageMentor',
    'apps/api/src/modules/idp/plan-mentor.ts#mentorSourcesOf',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/approval/access.ts#businessScopes': [
    '#IDP_PLAN_OBJECT',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/approval/access.ts#byBusinessScope': [
    '#businessScopes',
    '#instanceScopeSql',
    '#perBusinessType',
  ],
  'apps/api/src/modules/approval/access.ts#hasButton': [
    'packages/domain/src/approval/catalog.ts#APPROVAL_INSTANCE_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/approval/access.ts#instanceScopeSql': [
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/approval/access.ts#isProcessAdmin': ['#PROCESS_ADMIN'],
  'apps/api/src/modules/approval/access.ts#listScopeOf': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
  ],
  'apps/api/src/modules/approval/access.ts#requireIdpOwnerRight': [
    'apps/api/src/authorization.ts#requirePermission',
    '#IDP_PLAN_OBJECT',
    '#instanceScopeSql',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/approval/access.ts#requireProcessButton': [
    'apps/api/src/authorization.ts#requirePermission',
    '#PROCESS_ADMIN',
    '#requireProcessView',
  ],
  'apps/api/src/modules/approval/access.ts#requireProcessView': [
    'apps/api/src/authorization.ts#requirePermission',
    '#isProcessAdmin',
    'packages/domain/src/approval/catalog.ts#APPROVAL_PROCESS_OBJECT',
  ],
  'apps/api/src/modules/approval/access.ts#requireResubmitRight': [
    'apps/api/src/authorization.ts#requirePermission',
    '#requireIdpOwnerRight',
    '#requireSelfServiceSubmit',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
    'apps/api/src/modules/approval/store.ts#loadInstance',
    'apps/api/src/modules/contracts/context.ts#checkFields',
    'apps/api/src/modules/contracts/context.ts#checkOperationScope',
    'apps/api/src/modules/contracts/input.ts#fieldsSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/modules/contracts/service.ts#loadContract',
    'apps/api/src/modules/contracts/service.ts#loadRequest',
    'apps/api/src/modules/contracts/service.ts#mergeFields',
    'apps/api/src/modules/contracts/service.ts#requestWriteFields',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'packages/domain/src/approval/policies.ts#mayResubmit',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/contracts/rules.ts#contractAction',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/approval/access.ts#requireSelfServiceSubmit': [
    'apps/api/src/authorization.ts#requirePermission',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
  ],
  'apps/api/src/modules/approval/access.ts#requireWithdrawRight': [
    'apps/api/src/authorization.ts#requirePermission',
    '#IDP_PLAN_OBJECT',
    '#instanceScopeSql',
    '#requireSelfServiceSubmit',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/approval/store.ts#loadInstance',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/approval/actions.ts#addSign': [
    '#assertAddSignType',
    '#assertAddSigners',
    '#assertNotNodeAssignee',
    '#assertOpen',
    '#auditDelegation',
    '#blindReview',
    '#delegate',
    '#ok',
    '#openTask',
    '#parallelAddSign',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/rules.ts#addSignAllowed',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#insertTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/actions.ts#adminAct': [
    '#assertTargetInScope',
    '#performAdmin',
    '#targetNotFound',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/approval/engine.ts#openRun',
    'apps/api/src/modules/idp/plan-mentor.ts#foldMentorFailure',
  ],
  'apps/api/src/modules/approval/actions.ts#adminJump': [
    '#ok',
    '#startHistoryAfter',
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/engine.ts#advanceFrom',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#cancelPending',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/actions.ts#applyEdit': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/store.ts#appendLog',
  ],
  'apps/api/src/modules/approval/actions.ts#approveTask': [
    '#applyEdit',
    '#assertApprovalEdit',
    '#assertExit',
    '#assertNotBlindAfterEdit',
    '#assertOpen',
    '#auditTask',
    '#blindReview',
    '#editableInput',
    '#ok',
    '#openTask',
    '#outcomeAction',
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/add-sign.ts#assertNotAddSigner',
    'apps/api/src/modules/approval/add-sign.ts#continueAfterApproval',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/actions.ts#assertAddSignType': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'packages/domain/src/approval/types.ts#NODE_ADD_SIGN_TYPES',
    'packages/domain/src/approval/types.ts#nodeKindOf',
  ],
  'apps/api/src/modules/approval/actions.ts#assertAddSigners': [
    '#assertReviewer',
    'apps/api/src/modules/approval/context.ts#approvalError',
  ],
  'apps/api/src/modules/approval/actions.ts#assertApprovalEdit': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/actions.ts#assertExit': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'packages/domain/src/approval/types.ts#EXIT_LABELS',
    'packages/domain/src/approval/types.ts#hasExit',
  ],
  'apps/api/src/modules/approval/actions.ts#assertNotBlindAfterEdit': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'packages/domain/src/approval/policies.ts#blindReviewFields',
  ],
  'apps/api/src/modules/approval/actions.ts#assertNotNodeAssignee': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/rules.ts#nodeParticipantsOf',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/actions.ts#assertOpen': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#assertRevision',
    'apps/api/src/modules/approval/engine.ts#assertBusinessUnchanged',
  ],
  'apps/api/src/modules/approval/actions.ts#assertRejectEnabled': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'packages/domain/src/approval/types.ts#rejectAllowed',
  ],
  'apps/api/src/modules/approval/actions.ts#assertReviewer': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/recusal.ts#assertNotRecused',
    'apps/api/src/modules/approval/recusal.ts#eligibilityScope',
    'apps/api/src/modules/approval/resolver.ts#isEligibleApprover',
  ],
  'apps/api/src/modules/approval/actions.ts#assertTargetInScope': [
    '#targetNotFound',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
  ],
  'apps/api/src/modules/approval/actions.ts#assertUrgeInterval': [
    '#URGE_INTERVAL_MS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#rowsOf',
  ],
  'apps/api/src/modules/approval/actions.ts#auditDelegation': ['#auditTask'],
  'apps/api/src/modules/approval/actions.ts#auditTask': ['apps/api/src/modules/approval/context.ts#auditApproval'],
  'apps/api/src/modules/approval/actions.ts#blindReview': [
    '#auditTask',
    '#blindRejection',
    'apps/api/src/modules/approval/countersign.ts#mergeSeat',
    'apps/api/src/modules/approval/countersign.ts#mergesSeat',
    'apps/api/src/modules/approval/countersign.ts#resettle',
    'apps/api/src/modules/approval/engine.ts#currentRouting',
    'apps/api/src/modules/approval/engine.ts#exceptionAdminFor',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#insertTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/policies.ts#blindReviewFields',
  ],
  'apps/api/src/modules/approval/actions.ts#cancel': [
    'apps/api/src/modules/approval/engine.ts#openRun',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#cancelPending',
  ],
  'apps/api/src/modules/approval/actions.ts#delegate': [
    '#DELEGATION_EVENTS',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/actions.ts#disagreeTask': [
    '#assertExit',
    '#assertOpen',
    '#auditTask',
    '#blindReview',
    '#ok',
    '#openTask',
    '#outcomeAction',
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/countersign.ts#settleCountersign',
    'apps/api/src/modules/approval/engine.ts#followExit',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/rules.ts#votesInTransition',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/actions.ts#editTask': [
    '#applyEdit',
    '#assertApprovalEdit',
    '#assertNotBlindAfterEdit',
    '#assertOpen',
    '#editableInput',
    '#ok',
    '#openTask',
    'apps/api/src/modules/approval/add-sign.ts#assertNotAddSigner',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/actions.ts#editableInput': ['apps/api/src/modules/approval/context.ts#approvalError'],
  'apps/api/src/modules/approval/actions.ts#jumpTask': [
    '#assertOpen',
    '#auditTask',
    '#ok',
    '#openTask',
    '#outcomeAction',
    '#startHistoryAfter',
    'apps/api/src/modules/approval/add-sign.ts#assertNotAddSigner',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#advanceFrom',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#cancelPending',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/types.ts#jumpAllowed',
  ],
  'apps/api/src/modules/approval/actions.ts#openOwn': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#assertRevision',
    'apps/api/src/modules/approval/engine.ts#openRun',
  ],
  'apps/api/src/modules/approval/actions.ts#openTask': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/engine.ts#openRun',
    'apps/api/src/modules/approval/recusal.ts#assertNotRecused',
    'apps/api/src/modules/approval/store.ts#instanceOfTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/actions.ts#outcomeAction': ['#OUTCOME_ACTIONS'],
  'apps/api/src/modules/approval/actions.ts#parallelAddSign': [
    '#delegate',
    '#ok',
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/engine.ts#persistRun',
  ],
  'apps/api/src/modules/approval/actions.ts#performAdmin': [
    '#adminJump',
    '#assertNotNodeAssignee',
    '#assertReviewer',
    '#delegate',
    '#ok',
    '#startHistoryAfter',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#assertRevision',
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/engine.ts#assertBusinessUnchanged',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/recusal.ts#recusalFactsOf',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/recusal.ts#instanceRecusal',
  ],
  'apps/api/src/modules/approval/actions.ts#rejectTask': [
    '#assertOpen',
    '#assertRejectEnabled',
    '#auditTask',
    '#blindReview',
    '#ok',
    '#openTask',
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/engine.ts#returnInstance',
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeTask',
  ],
  'apps/api/src/modules/approval/actions.ts#rejectToPreviousTask': [
    '#assertOpen',
    '#auditTask',
    '#blindReview',
    '#ok',
    '#openTask',
    '#outcomeAction',
    '#startHistoryAfter',
    'apps/api/src/modules/approval/add-sign.ts#assertNotAddSigner',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#advanceFrom',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#cancelPending',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/types.ts#isCountersign',
    'packages/domain/src/approval/types.ts#rejectToPreviousAllowed',
  ],
  'apps/api/src/modules/approval/actions.ts#resubmit': [
    '#openOwn',
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#startOrResume',
  ],
  'apps/api/src/modules/approval/actions.ts#targetNotFound': ['apps/api/src/modules/approval/context.ts#approvalError'],
  'apps/api/src/modules/approval/actions.ts#transferTask': [
    '#assertNotNodeAssignee',
    '#assertOpen',
    '#assertReviewer',
    '#auditDelegation',
    '#delegate',
    '#ok',
    '#openTask',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/store.ts#closeTask',
  ],
  'apps/api/src/modules/approval/actions.ts#urge': ['#openOwn', '#urgeRun'],
  'apps/api/src/modules/approval/actions.ts#urgeAsAdmin': [
    '#urgeRun',
    'apps/api/src/modules/approval/engine.ts#openRun',
  ],
  'apps/api/src/modules/approval/actions.ts#urgeRun': [
    '#assertUrgeInterval',
    '#ok',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/context.ts#emitOutbox',
    'apps/api/src/modules/approval/notifications.ts#notifyUrge',
    'apps/api/src/modules/approval/rules.ts#urgeOpen',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/actions.ts#withdraw': [
    '#ok',
    '#openOwn',
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#openRun',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#cancelPending',
    'packages/domain/src/approval/types.ts#revokeAllowed',
  ],
  'apps/api/src/modules/approval/adapters.ts#ADAPTERS': [
    '#employmentAdapter',
    '#personnelAdapter',
    'apps/api/src/modules/contracts/adapter.ts#contractAdapter',
    'apps/api/src/modules/idp/approval-adapter.ts#idpAdapter',
    'apps/api/src/modules/talent-review/approval-adapter.ts#talentReviewAdapter',
  ],
  'apps/api/src/modules/approval/adapters.ts#HELD_STATUSES': ['apps/api/src/modules/approval/store.ts#OPEN_STATUSES'],
  'apps/api/src/modules/approval/adapters.ts#businessRevision': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/adapters.ts#completedTransferDates': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
  ],
  'apps/api/src/modules/approval/adapters.ts#employeeHeader': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/adapters.ts#employmentAdapter': [
    '#businessRevision',
    '#completedTransferDates',
    '#customValues',
    '#employeeHeader',
    '#employmentPatch',
    '#employmentTransition',
    '#latestPayload',
    '#mayMergeSeat',
    '#profileValues',
    '#ref',
    '#same',
    '#transferMetadata',
    '#transferProcessCode',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferBusiness',
    'apps/api/src/modules/employment/types.ts#PRESET_FIELD_NAMES',
    'apps/api/src/modules/employment/write-service.ts#updateEmploymentBusiness',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/org/locks.ts#lockOrganizationSettings',
    'apps/api/src/modules/transfer/linkage/approval.ts#linkageApproval',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
    'packages/domain/src/approval/types.ts#PROFILE_FORM_FIELDS',
    'packages/domain/src/approval/types.ts#approvalTypeOfBusiness',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/approval/adapters.ts#employmentTransition': [
    '#businessRevision',
    'apps/api/src/modules/employment/transitions.ts#transitionEmployment',
  ],
  'apps/api/src/modules/approval/adapters.ts#latestPayload': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/adapters.ts#mayMergeSeat': [
    '#HELD_STATUSES',
    'apps/api/src/modules/approval/context.ts#rowsOf',
  ],
  'apps/api/src/modules/approval/adapters.ts#personnelAdapter': [
    '#employeeHeader',
    '#personnelChange',
    '#same',
    '#subsetVersion',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'apps/api/src/modules/personnel/change-requests.ts#applyApprovedChangeInTransaction',
    'apps/api/src/modules/personnel/change-requests.ts#currentChangeValues',
    'apps/api/src/modules/personnel/change-requests.ts#disapproveChangeInTransaction',
    'apps/api/src/modules/personnel/change-requests.ts#resubmitChangeInTransaction',
    'apps/api/src/modules/personnel/change-requests.ts#withdrawChangeInTransaction',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/subsets.ts#loadSubset',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
    'packages/domain/src/approval/types.ts#subsetProcessCode',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/approval/adapters.ts#personnelChange': [
    'apps/api/src/modules/personnel/change-requests.ts#loadChange',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/approval/adapters.ts#profileValues': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'packages/domain/src/personnel/tenure.ts#ageOn',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/approval/adapters.ts#subsetVersion': [
    '#camelRow',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/approval/adapters.ts#transferMetadata': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/adapters.ts#transferProcessCode': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
  ],
  'apps/api/src/modules/approval/add-sign.ts#activateNext': [
    '#handToExceptionAdmin',
    'apps/api/src/modules/approval/engine.ts#currentRouting',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/recusal.ts#canTake',
    'apps/api/src/modules/approval/store.ts#activateTask',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeQueued',
  ],
  'apps/api/src/modules/approval/add-sign.ts#assertNotAddSigner': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/rules.ts#addSignLink',
  ],
  'apps/api/src/modules/approval/add-sign.ts#continueAfterApproval': [
    '#activateNext',
    '#continueBeforeChain',
    '#returnToSigner',
    'apps/api/src/modules/approval/countersign.ts#settleCountersign',
    'apps/api/src/modules/approval/engine.ts#afterNodeApproved',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/rules.ts#addSignLink',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/add-sign.ts#continueBeforeChain': [
    '#activateNext',
    '#handToExceptionAdmin',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/countersign.ts#mergeSeat',
    'apps/api/src/modules/approval/countersign.ts#mergesSeat',
    'apps/api/src/modules/approval/countersign.ts#resettle',
    'apps/api/src/modules/approval/engine.ts#currentRouting',
    'apps/api/src/modules/approval/engine.ts#exceptionAdminFor',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/recusal.ts#canTake',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeAddSigned',
    'apps/api/src/modules/approval/store.ts#resumeAddSigned',
  ],
  'apps/api/src/modules/approval/add-sign.ts#handToExceptionAdmin': [
    'apps/api/src/modules/approval/engine.ts#currentRouting',
    'apps/api/src/modules/approval/engine.ts#exceptionAdminFor',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/add-sign.ts#returnToSigner': [
    '#handToExceptionAdmin',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/engine.ts#currentRouting',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/recusal.ts#canTake',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/context.ts#auditApproval': [
    'apps/api/src/audit/record.ts#recordAudit',
    '#actorOf',
    '#changed',
  ],
  'apps/api/src/modules/approval/countersign.ts#HELD': ['apps/api/src/modules/approval/store.ts#OPEN_STATUSES'],
  'apps/api/src/modules/approval/countersign.ts#activationVotes': [
    '#votingTasks',
    'packages/domain/src/approval/countersign.ts#countersignVote',
  ],
  'apps/api/src/modules/approval/countersign.ts#countersignFlowed': [
    'apps/api/src/modules/approval/store.ts#OPEN_STATUSES',
  ],
  'apps/api/src/modules/approval/countersign.ts#holdersAfterRetrieve': ['#seatHolders'],
  'apps/api/src/modules/approval/countersign.ts#mergeSeat': [
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/countersign.ts#mergesSeat': [
    '#activationOf',
    '#seatHolders',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/rules.ts#votesInTransition',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/countersign.ts#reopenEnded': [
    '#RESTORE_ORIGINS',
    '#mergeSeat',
    '#votingTasks',
    'apps/api/src/modules/approval/engine.ts#currentRouting',
    'apps/api/src/modules/approval/engine.ts#exceptionAdminFor',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/recusal.ts#canTake',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/countersign.ts#resettle': [
    '#settleCountersign',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/countersign.ts#seatHolders': ['#HELD', '#votingTasks'],
  'apps/api/src/modules/approval/countersign.ts#settleCountersign': [
    '#activationOf',
    '#activationVotes',
    'apps/api/src/modules/approval/engine.ts#followExit',
    'apps/api/src/modules/approval/engine.ts#logEnded',
    'apps/api/src/modules/approval/engine.ts#returnInstance',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#endOpenTasks',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/countersign.ts#countersignOutcome',
    'packages/domain/src/approval/countersign.ts#exitRulesOf',
    'packages/domain/src/approval/policies.ts#STALLED_COUNTERSIGN_HANDLING',
    'packages/domain/src/approval/policies.ts#countersignEndedReason',
    'packages/domain/src/approval/types.ts#nodeExits',
  ],
  'apps/api/src/modules/approval/countersign.ts#votingTasks': [
    'apps/api/src/modules/approval/rules.ts#votesInTransition',
  ],
  'apps/api/src/modules/approval/definition-input.ts#approvalTypeOf': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'packages/domain/src/approval/types.ts#isApprovalType',
  ],
  'apps/api/src/modules/approval/definition-input.ts#conditionItem': [
    '#text',
    'packages/domain/src/approval/types.ts#CONDITION_OPERATORS',
  ],
  'apps/api/src/modules/approval/definition-input.ts#createSchema': ['#definitionSchema'],
  'apps/api/src/modules/approval/definition-input.ts#definitionSchema': [
    'apps/api/src/modules/approval/context.ts#canonicalId',
    '#conditionItem',
    '#node',
    '#optionalText',
    '#text',
  ],
  'apps/api/src/modules/approval/definition-input.ts#exitRule': [
    'packages/domain/src/approval/types.ts#EXIT_RULE_KINDS',
  ],
  'apps/api/src/modules/approval/definition-input.ts#messageRule': [
    '#text',
    'packages/domain/src/approval/types.ts#MESSAGE_CHANNELS',
    'packages/domain/src/approval/types.ts#MESSAGE_RECIPIENTS',
    'packages/domain/src/approval/types.ts#MESSAGE_TRIGGERS',
  ],
  'apps/api/src/modules/approval/definition-input.ts#node': [
    '#avoidSubjectsResult',
    '#codeList',
    '#messageRule',
    '#text',
    '#transitionRule',
    'packages/domain/src/approval/types.ts#APPROVER_EXPRESSIONS',
    'packages/domain/src/approval/types.ts#AUTO_RESULTS',
    'packages/domain/src/approval/types.ts#EDIT_MODES',
    'packages/domain/src/approval/types.ts#NODE_EXITS',
    'packages/domain/src/approval/types.ts#NODE_KINDS',
    'packages/domain/src/approval/types.ts#NO_ASSIGNEE_POLICIES',
    'packages/domain/src/approval/types.ts#REJECT_RESUBMIT_MODES',
    'packages/domain/src/approval/types.ts#URGE_MODES',
  ],
  'apps/api/src/modules/approval/definition-input.ts#toDefinition': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#nodeTypeViolations',
    '#toNode',
    'packages/domain/src/approval/definition.ts#avoidSubjectsViolations',
    'packages/domain/src/approval/definition.ts#definitionViolations',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/definition-input.ts#transitionRule': [
    '#exitRule',
    'packages/domain/src/approval/types.ts#TRANSITION_RULE_TYPES',
  ],
  'apps/api/src/modules/approval/definitions.ts#approversOf': ['#transitionRuleOf'],
  'apps/api/src/modules/approval/definitions.ts#assertExceptionAdminMember': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/resolver.ts#isAssignable',
  ],
  'apps/api/src/modules/approval/definitions.ts#assertUniquePriority': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#rowsOf',
  ],
  'apps/api/src/modules/approval/definitions.ts#audited': [
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/context.ts#emitOutbox',
    '#loadProcess',
    '#snapshot',
  ],
  'apps/api/src/modules/approval/definitions.ts#createProcess': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#assertRevision',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#audited',
    '#insertVersion',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/definitions.ts#discardProcess': ['#audited', '#bump', '#lockedForChange'],
  'apps/api/src/modules/approval/definitions.ts#inheritRecusalSwitches': [
    'packages/domain/src/approval/types.ts#avoidsSelf',
    'packages/domain/src/approval/types.ts#avoidsSubjects',
  ],
  'apps/api/src/modules/approval/definitions.ts#insertVersion': ['#writeVersionContent'],
  'apps/api/src/modules/approval/definitions.ts#installPresets': [
    'apps/api/src/modules/approval/context.ts#assertRevision',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#createProcess',
    '#loadProcess',
    'packages/domain/src/approval/presets.ts#PRESET_PROCESSES',
  ],
  'apps/api/src/modules/approval/definitions.ts#listProcesses': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/definitions.ts#loadProcess': ['#loadVersion', '#processRow', '#versionId'],
  'apps/api/src/modules/approval/definitions.ts#loadVersion': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#conditionItem',
    '#nodeOf',
  ],
  'apps/api/src/modules/approval/definitions.ts#lockedForChange': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#assertRevision',
    '#loadProcess',
    '#processRow',
  ],
  'apps/api/src/modules/approval/definitions.ts#newVersion': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#audited',
    '#bump',
    '#insertVersion',
    '#lockedForChange',
  ],
  'apps/api/src/modules/approval/definitions.ts#nodeOf': ['#approversOf'],
  'apps/api/src/modules/approval/definitions.ts#nodeTypeColumns': [
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/definitions.ts#processRow': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/definitions.ts#publishProcess': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#assertExceptionAdminMember',
    '#assertUniquePriority',
    '#audited',
    '#bump',
    '#lockedForChange',
    'packages/domain/src/approval/conditions.ts#conditionViolations',
    'packages/domain/src/approval/definition.ts#publishViolations',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/definitions.ts#replaceDraft': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#audited',
    '#bump',
    '#inheritRecusalSwitches',
    '#lockedForChange',
    '#writeVersionContent',
  ],
  'apps/api/src/modules/approval/definitions.ts#republishWithExceptionAdmin': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#audited',
    '#bump',
    '#insertVersion',
    '#loadProcess',
    '#processRow',
  ],
  'apps/api/src/modules/approval/definitions.ts#transitionRuleOf': [
    '#exitRuleOf',
    'packages/domain/src/approval/countersign.ts#exitRulesOf',
  ],
  'apps/api/src/modules/approval/definitions.ts#versionId': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/definitions.ts#writeVersionContent': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#nodeTypeColumns',
    '#textArray',
    'packages/domain/src/approval/definition.ts#avoidSubjectsViolations',
    'packages/domain/src/approval/types.ts#DEFAULT_AVOID_SUBJECTS_RESULT',
    'packages/domain/src/approval/types.ts#avoidsSelf',
    'packages/domain/src/approval/types.ts#avoidsSubjects',
    'packages/domain/src/approval/types.ts#jumpAllowed',
    'packages/domain/src/approval/types.ts#nodeExits',
    'packages/domain/src/approval/types.ts#rejectAllowed',
    'packages/domain/src/approval/types.ts#rejectToPreviousAllowed',
    'packages/domain/src/approval/types.ts#revokeAllowed',
  ],
  'apps/api/src/modules/approval/disclosure.ts#actionsFor': [
    '#initiatorActions',
    'apps/api/src/modules/approval/rules.ts#addSignAllowed',
    'apps/api/src/modules/approval/rules.ts#addSignLink',
    'apps/api/src/modules/approval/rules.ts#retrievableTask',
    'apps/api/src/modules/approval/rules.ts#votesInTransition',
    'packages/domain/src/approval/recusal.ts#instanceRecusal',
    'packages/domain/src/approval/recusal.ts#nodeRecusal',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
    'packages/domain/src/approval/types.ts#hasExit',
    'packages/domain/src/approval/types.ts#isCountersign',
    'packages/domain/src/approval/types.ts#jumpAllowed',
    'packages/domain/src/approval/types.ts#rejectAllowed',
    'packages/domain/src/approval/types.ts#rejectToPreviousAllowed',
  ],
  'apps/api/src/modules/approval/disclosure.ts#adminCovers': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/disclosure.ts#assertCanOpen': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#adminCovers',
  ],
  'apps/api/src/modules/approval/disclosure.ts#ccNodeOf': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/disclosure.ts#detailView': [
    '#COMMENT_NOTICE',
    '#actionsFor',
    '#disclosedFields',
    '#pick',
    '#projectLog',
    '#recordsHidden',
    '#viewerNode',
    '#visibleTasks',
    'packages/domain/src/approval/policies.ts#blindReviewFields',
  ],
  'apps/api/src/modules/approval/disclosure.ts#disclosedFields': [
    '#viewerNode',
    'apps/api/src/modules/approval/foreign-fields.ts#formFieldsWithForeign',
    'packages/domain/src/approval/policies.ts#disclosedFieldNames',
  ],
  'apps/api/src/modules/approval/disclosure.ts#initiatorActions': [
    'apps/api/src/modules/approval/rules.ts#urgeOpen',
    'packages/domain/src/approval/types.ts#revokeAllowed',
  ],
  'apps/api/src/modules/approval/disclosure.ts#readDetail': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/definitions.ts#loadVersion',
    '#SHOW_ORIGINALS_SETTING',
    '#adminCovers',
    '#assertCanOpen',
    '#ccNodeOf',
    'apps/api/src/modules/approval/store.ts#displayWindow',
    'apps/api/src/modules/approval/store.ts#loadInstance',
    'apps/api/src/modules/approval/store.ts#loadLogs',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'apps/api/src/modules/approval/subjects.ts#loadRecusalFacts',
    'apps/api/src/modules/tenant-settings/service.ts#readEffectiveSetting',
  ],
  'apps/api/src/modules/approval/disclosure.ts#recordsHidden': [
    '#ownTasks',
    'packages/domain/src/approval/policies.ts#recordsHiddenFor',
  ],
  'apps/api/src/modules/approval/disclosure.ts#viewerNode': ['#ownTasks'],
  'apps/api/src/modules/approval/disclosure.ts#visibleTasks': [
    '#recordsHidden',
    'packages/domain/src/approval/policies.ts#visibleWhenHidden',
  ],
  'apps/api/src/modules/approval/engine.ts#advanceFrom': [
    '#complete',
    '#enterCountersign',
    '#enterSingle',
    '#routingFacts',
    '#routingSubject',
    'apps/api/src/modules/approval/recusal.ts#recusalFactsOf',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/engine.ts#afterNodeApproved': [
    '#advanceFrom',
    '#nodeIndex',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/engine.ts#announceAssignment': [
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/store.ts#appendLog',
  ],
  'apps/api/src/modules/approval/engine.ts#assertActorUsable': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/resolver.ts#isAssignable',
  ],
  'apps/api/src/modules/approval/engine.ts#assertBusinessUnchanged': [
    'apps/api/src/modules/approval/context.ts#approvalError',
  ],
  'apps/api/src/modules/approval/engine.ts#assertExceptionAdminAvailable': ['#currentRouting', '#exceptionAdminFor'],
  'apps/api/src/modules/approval/engine.ts#assign': ['#insertAssigned', '#recordSelfSkip', '#settleAssignee'],
  'apps/api/src/modules/approval/engine.ts#autoProcess': [
    '#MECHANISMS',
    'apps/api/src/modules/approval/notifications.ts#applyMessageRules',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/engine.ts#blindReviewSeat': [
    '#logEnded',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/engine.ts#complete': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/store.ts#appendLog',
  ],
  'apps/api/src/modules/approval/engine.ts#countersignSeats': [
    '#decide',
    '#firstNodeEmpty',
    '#noAssignee',
    '#seatOf',
    '#seatUser',
  ],
  'apps/api/src/modules/approval/engine.ts#currentRouting': [
    '#nodeIndex',
    '#routingFacts',
    '#routingSubject',
    'apps/api/src/modules/approval/recusal.ts#recusalFactsOf',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/engine.ts#decide': [
    'apps/api/src/modules/approval/resolver.ts#directManagerOf',
    'apps/api/src/modules/approval/resolver.ts#resolveCandidate',
    'packages/domain/src/approval/routing.ts#decideNode',
  ],
  'apps/api/src/modules/approval/engine.ts#endDisapproved': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#cancelPending',
  ],
  'apps/api/src/modules/approval/engine.ts#enterCountersign': [
    '#countersignSeats',
    '#recordSelfSkip',
    '#returnInstance',
    '#writeSeat',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/countersign.ts#countersignOutcome',
    'packages/domain/src/approval/countersign.ts#exitRulesOf',
    'packages/domain/src/approval/policies.ts#STALLED_COUNTERSIGN_HANDLING',
    'packages/domain/src/approval/policies.ts#countersignEndedReason',
    'packages/domain/src/approval/types.ts#nodeExits',
  ],
  'apps/api/src/modules/approval/engine.ts#enterSingle': [
    '#assign',
    '#autoProcess',
    '#blindReviewSeat',
    '#decide',
    '#exceptionAdminFor',
    '#firstNodeEmpty',
    '#hiddenForAuto',
    '#noAssignee',
  ],
  'apps/api/src/modules/approval/engine.ts#exceptionAdminFor': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/resolver.ts#directManagerOf',
    'apps/api/src/modules/approval/resolver.ts#isAssignable',
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
    'apps/api/src/modules/approval/resolver.ts#tenantAdminTakeover',
    'packages/domain/src/approval/routing.ts#adminRecused',
    'packages/domain/src/approval/routing.ts#avoidSelfExceptionAdmin',
    'packages/domain/src/approval/routing.ts#submitBlockers',
  ],
  'apps/api/src/modules/approval/engine.ts#firstNodeEmpty': ['apps/api/src/modules/approval/context.ts#approvalError'],
  'apps/api/src/modules/approval/engine.ts#followExit': [
    '#advanceFrom',
    '#endDisapproved',
    '#nodeIndex',
    'packages/domain/src/approval/types.ts#EXIT_TARGETS',
  ],
  'apps/api/src/modules/approval/engine.ts#hiddenForAuto': [
    'apps/api/src/modules/approval/foreign-fields.ts#viewableWithForeign',
    'apps/api/src/modules/approval/resolver.ts#memo',
    'packages/domain/src/approval/policies.ts#blindReviewFields',
  ],
  'apps/api/src/modules/approval/engine.ts#insertAssigned': [
    '#announceAssignment',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/engine.ts#insertInstance': [
    'apps/api/src/modules/approval/store.ts#loadInstance',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/engine.ts#launch': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/definitions.ts#loadVersion',
    '#advanceFrom',
    '#assertExceptionAdminAvailable',
    '#insertInstance',
    '#persistRun',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/subjects.ts#freezeSubjects',
  ],
  'apps/api/src/modules/approval/engine.ts#logEnded': ['apps/api/src/modules/approval/store.ts#appendLog'],
  'apps/api/src/modules/approval/engine.ts#matchProcess': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/matching.ts#candidates',
    'apps/api/src/modules/approval/matching.ts#conditionContext',
    'apps/api/src/modules/approval/matching.ts#evaluate',
    'apps/api/src/modules/approval/matching.ts#noProcessMessage',
    'apps/api/src/modules/approval/matching.ts#replicaMatch',
    'packages/domain/src/approval/conditions.ts#conditionViolations',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/approval/engine.ts#noAssignee': ['apps/api/src/modules/approval/context.ts#approvalError'],
  'apps/api/src/modules/approval/engine.ts#nodeIndex': ['apps/api/src/modules/approval/context.ts#approvalError'],
  'apps/api/src/modules/approval/engine.ts#openRun': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/definitions.ts#loadVersion',
    '#assertActorUsable',
    'apps/api/src/modules/approval/store.ts#loadInstance',
  ],
  'apps/api/src/modules/approval/engine.ts#persistRun': [
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/context.ts#emitOutbox',
    '#instanceAudit',
    'apps/api/src/modules/approval/store.ts#updateInstance',
  ],
  'apps/api/src/modules/approval/engine.ts#recordSelfSkip': [
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/engine.ts#resume': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#advanceFrom',
    '#assertExceptionAdminAvailable',
    '#nodeIndex',
    '#openRun',
    '#persistRun',
    'apps/api/src/modules/approval/recusal.ts#freezeRunSubjects',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'packages/domain/src/approval/policies.ts#mayResubmit',
  ],
  'apps/api/src/modules/approval/engine.ts#returnInstance': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/store.ts#cancelPending',
  ],
  'apps/api/src/modules/approval/engine.ts#routingFacts': [
    'packages/domain/src/approval/policies.ts#effectiveHistory',
    'packages/domain/src/approval/policies.ts#previousNodeComparand',
  ],
  'apps/api/src/modules/approval/engine.ts#routingSubject': ['packages/domain/src/tenant-time.ts#tenantLocalDate'],
  'apps/api/src/modules/approval/engine.ts#seatOf': ['#exceptionAdminFor', '#hiddenForAuto', '#settleAssignee'],
  'apps/api/src/modules/approval/engine.ts#settleAssignee': ['#exceptionAdminFor'],
  'apps/api/src/modules/approval/engine.ts#startOrResume': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#assertActorUsable',
    '#launch',
    '#matchProcess',
    '#resume',
    'apps/api/src/modules/approval/store.ts#resumableInstanceOf',
  ],
  'apps/api/src/modules/approval/engine.ts#startSpecified': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#assertActorUsable',
    '#launch',
    '#matchProcess',
    'apps/api/src/modules/approval/store.ts#resumableInstanceOf',
  ],
  'apps/api/src/modules/approval/engine.ts#writeSeat': [
    '#autoProcess',
    '#blindReviewSeat',
    '#insertAssigned',
    '#logEnded',
    'apps/api/src/modules/approval/store.ts#insertTask',
  ],
  'apps/api/src/modules/approval/foreign-fields.ts#foreignVisibility': [
    '#objectAccess',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/approval/foreign-fields.ts#objectAccess': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFieldsInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
  ],
  'apps/api/src/modules/approval/handover.ts#assertTenantMember': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#rowsOf',
  ],
  'apps/api/src/modules/approval/handover.ts#byLockOrder': ['#compareUuid'],
  'apps/api/src/modules/approval/handover.ts#designateSuccessor': [
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/context.ts#rowsOf',
  ],
  'apps/api/src/modules/approval/handover.ts#discloseHandover': ['#visibleInstances'],
  'apps/api/src/modules/approval/handover.ts#handoverExceptionAdmin': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#assertRevision',
    'apps/api/src/modules/approval/definitions.ts#assertExceptionAdminMember',
    '#BATCH',
    '#assertTenantMember',
    '#byLockOrder',
    '#compareUuid',
    '#designateSuccessor',
    '#handoverInstance',
    '#lockHandoverParticipants',
    '#ownRequestBlocker',
    '#republishProcesses',
    '#transferableInstances',
    '#unlistedCount',
    'apps/api/src/modules/approval/resolver.ts#isEligibleApprover',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/approval/handover.ts#handoverInstance': [
    'apps/api/src/modules/approval/engine.ts#currentRouting',
    'apps/api/src/modules/approval/engine.ts#openRun',
    '#pendingExceptionTasks',
    '#reassignAll',
    'apps/api/src/modules/approval/resolver.ts#directManagerOf',
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
    'packages/domain/src/approval/routing.ts#adminRecused',
    'packages/domain/src/approval/routing.ts#avoidSelfExceptionAdmin',
  ],
  'apps/api/src/modules/approval/handover.ts#lockHandoverParticipants': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
  ],
  'apps/api/src/modules/approval/handover.ts#ownRequestBlocker': [
    'apps/api/src/modules/approval/store.ts#loadInstance',
    'apps/api/src/modules/approval/subjects.ts#loadRecusalFacts',
    'packages/domain/src/approval/recusal.ts#instanceRecusal',
  ],
  'apps/api/src/modules/approval/handover.ts#pendingExceptionTasks': [
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/handover.ts#reassignAll': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/countersign.ts#mergeSeat',
    'apps/api/src/modules/approval/countersign.ts#mergesSeat',
    'apps/api/src/modules/approval/countersign.ts#resettle',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#notifyTodo',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#closeTask',
    'apps/api/src/modules/approval/store.ts#insertTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
  ],
  'apps/api/src/modules/approval/handover.ts#republishProcesses': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/approval/definitions.ts#republishWithExceptionAdmin',
    '#BATCH',
  ],
  'apps/api/src/modules/approval/handover.ts#transferableInstances': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#BATCH',
    '#LOCK_EMPLOYEE',
    '#pendingExceptionOf',
  ],
  'apps/api/src/modules/approval/handover.ts#unlistedCount': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#pendingExceptionOf',
  ],
  'apps/api/src/modules/approval/handover.ts#visibleInstances': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/matching.ts#candidateBatch': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/approval/definitions.ts#conditionItem',
    '#BATCH',
  ],
  'apps/api/src/modules/approval/matching.ts#candidates': ['#BATCH', '#candidateBatch'],
  'apps/api/src/modules/approval/matching.ts#conditionContext': [
    'apps/api/src/modules/approval/resolver.ts#adminAncestors',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/matching.ts#evaluate': [
    'packages/domain/src/approval/conditions.ts#evaluateCondition',
  ],
  'apps/api/src/modules/approval/matching.ts#noProcessMessage': [
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/matching.ts#originalSiteMatch': ['#byCode'],
  'apps/api/src/modules/approval/matching.ts#replicaMatch': ['#byCode'],
  'apps/api/src/modules/approval/node-actions.ts#copySend': [
    'apps/api/src/modules/approval/actions.ts#assertOpen',
    'apps/api/src/modules/approval/actions.ts#ok',
    'apps/api/src/modules/approval/actions.ts#openTask',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/notifications.ts#notifyCc',
    'apps/api/src/modules/approval/recusal.ts#assertNotRecused',
    'apps/api/src/modules/approval/resolver.ts#isActiveAccount',
    'apps/api/src/modules/approval/store.ts#appendLog',
  ],
  'apps/api/src/modules/approval/node-actions.ts#retrieveTask': [
    'apps/api/src/modules/approval/actions.ts#ok',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#assertRevision',
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/countersign.ts#activationOf',
    'apps/api/src/modules/approval/countersign.ts#countersignFlowed',
    'apps/api/src/modules/approval/countersign.ts#holdersAfterRetrieve',
    'apps/api/src/modules/approval/countersign.ts#reopenEnded',
    'apps/api/src/modules/approval/countersign.ts#resettle',
    'apps/api/src/modules/approval/engine.ts#assertBusinessUnchanged',
    'apps/api/src/modules/approval/engine.ts#nodeIndex',
    'apps/api/src/modules/approval/engine.ts#openRun',
    'apps/api/src/modules/approval/engine.ts#persistRun',
    'apps/api/src/modules/approval/recusal.ts#assertNotRecused',
    'apps/api/src/modules/approval/rules.ts#retrievableTask',
    'apps/api/src/modules/approval/store.ts#appendLog',
    'apps/api/src/modules/approval/store.ts#cancelPending',
    'apps/api/src/modules/approval/store.ts#insertTask',
    'apps/api/src/modules/approval/store.ts#instanceOfTask',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/notifications.ts#applyMessageRules': ['#insertNotice', '#recipientOf'],
  'apps/api/src/modules/approval/notifications.ts#insertNotice': [
    'apps/api/src/modules/approval/resolver.ts#isActiveAccount',
  ],
  'apps/api/src/modules/approval/notifications.ts#notifyCc': ['#insertNotice'],
  'apps/api/src/modules/approval/notifications.ts#notifyTodo': ['#insertNotice'],
  'apps/api/src/modules/approval/notifications.ts#notifyUrge': ['#insertNotice'],
  'apps/api/src/modules/approval/notifications.ts#recipientOf': [
    'apps/api/src/modules/approval/resolver.ts#userOfPerson',
  ],
  'apps/api/src/modules/approval/queries.ts#listAdminLogs': ['apps/api/src/modules/approval/context.ts#rowsOf', '#iso'],
  'apps/api/src/modules/approval/queries.ts#listInstances': ['apps/api/src/modules/approval/context.ts#rowsOf', '#iso'],
  'apps/api/src/modules/approval/queries.ts#listNotifications': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#iso',
  ],
  'apps/api/src/modules/approval/queries.ts#listTodos': ['apps/api/src/modules/approval/context.ts#rowsOf', '#iso'],
  'apps/api/src/modules/approval/recusal.ts#assertNotRecused': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#messageOf',
    '#recusalOf',
  ],
  'apps/api/src/modules/approval/recusal.ts#canTake': [
    '#recusalOf',
    'apps/api/src/modules/approval/resolver.ts#isEligibleApprover',
  ],
  'apps/api/src/modules/approval/recusal.ts#eligibilityScope': ['packages/domain/src/tenant-time.ts#tenantLocalDate'],
  'apps/api/src/modules/approval/recusal.ts#freezeRunSubjects': [
    'apps/api/src/modules/approval/subjects.ts#freezeSubjects',
  ],
  'apps/api/src/modules/approval/recusal.ts#recusalFactsOf': [
    'apps/api/src/modules/approval/subjects.ts#loadRecusalFacts',
  ],
  'apps/api/src/modules/approval/recusal.ts#recusalOf': [
    '#recusalFactsOf',
    'packages/domain/src/approval/recusal.ts#instanceRecusal',
    'packages/domain/src/approval/recusal.ts#nodeRecusal',
    'packages/domain/src/approval/types.ts#avoidsSubjects',
  ],
  'apps/api/src/modules/approval/resolver.ts#adminAncestors': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/resolver.ts#candidateOf': ['#NOBODY', '#departed', '#isAssignable', '#userOfPerson'],
  'apps/api/src/modules/approval/resolver.ts#departed': [
    '#memo',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
  ],
  'apps/api/src/modules/approval/resolver.ts#directManagerOf': ['#managerFresh', '#memo'],
  'apps/api/src/modules/approval/resolver.ts#enterAssigneeGate': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#assigneeGate',
  ],
  'apps/api/src/modules/approval/resolver.ts#firstLevelOrg': ['#adminAncestors'],
  'apps/api/src/modules/approval/resolver.ts#isActiveAccount': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/resolver.ts#isAssignable': ['#enterAssigneeGate', '#isActiveAccount'],
  'apps/api/src/modules/approval/resolver.ts#isEligibleApprover': ['#departed', '#isAssignable', '#personOfUser'],
  'apps/api/src/modules/approval/resolver.ts#managerFresh': [
    '#NOBODY',
    '#candidateOf',
    '#personOfUser',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
  ],
  'apps/api/src/modules/approval/resolver.ts#orgRole': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/resolver.ts#personOfUser': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/resolver.ts#resolveCandidate': ['#memo', '#resolveFresh'],
  'apps/api/src/modules/approval/resolver.ts#resolveFresh': [
    '#NOBODY',
    '#candidateOf',
    '#directManagerOf',
    '#firstLevelOrg',
    '#isEligibleApprover',
    '#orgRole',
    '#personOfUser',
  ],
  'apps/api/src/modules/approval/resolver.ts#tenantAdminPage': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#ADMIN_PAGE',
  ],
  'apps/api/src/modules/approval/resolver.ts#tenantAdminTakeover': [
    '#ADMIN_PAGE',
    '#directManagerOf',
    '#isEligibleApprover',
    '#personOfUser',
    '#tenantAdminPage',
    'packages/domain/src/approval/routing.ts#adminRecused',
    'packages/domain/src/approval/routing.ts#avoidSelfExceptionAdmin',
  ],
  'apps/api/src/modules/approval/resolver.ts#userOfPerson': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/routes.ts#adminBody': ['#userIdInput'],
  'apps/api/src/modules/approval/routes.ts#command': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#LOCK_CONFLICTS',
  ],
  'apps/api/src/modules/approval/routes.ts#detailViewable': [
    'apps/api/src/modules/approval/foreign-fields.ts#foreignVisibility',
    'apps/api/src/modules/approval/foreign-fields.ts#viewableWithForeign',
    '#ownViewable',
  ],
  'apps/api/src/modules/approval/routes.ts#fieldAccess': [
    'apps/api/src/modules/approval/foreign-fields.ts#foreignVisibility',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFieldsInTransaction',
  ],
  'apps/api/src/modules/approval/routes.ts#fieldRights': [
    'apps/api/src/modules/approval/foreign-fields.ts#foreignVisibility',
    'apps/api/src/modules/approval/foreign-fields.ts#viewableWithForeign',
    '#readCtx',
    '#snapshotOfTask',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
  ],
  'apps/api/src/modules/approval/routes.ts#ownViewable': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/modules/approval/routes.ts#processResponse': ['#tenantCtx', '#trimProcess'],
  'apps/api/src/modules/approval/routes.ts#readCtx': ['#fieldAccess', '#tenantCtx'],
  'apps/api/src/modules/approval/routes.ts#registerInstanceRoutes': [
    'apps/api/src/modules/approval/access.ts#adminScope',
    'apps/api/src/modules/approval/access.ts#adminTargetScope',
    'apps/api/src/modules/approval/access.ts#requireResubmitRight',
    'apps/api/src/modules/approval/access.ts#requireWithdrawRight',
    'apps/api/src/modules/approval/actions.ts#adminAct',
    'apps/api/src/modules/approval/actions.ts#resubmit',
    'apps/api/src/modules/approval/actions.ts#urge',
    'apps/api/src/modules/approval/actions.ts#withdraw',
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#adminBody',
    '#command',
    '#fields',
    '#respondOutcome',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#registerProcessRoutes': [
    'apps/api/src/modules/approval/access.ts#requireProcessButton',
    'apps/api/src/modules/approval/access.ts#requireProcessView',
    'apps/api/src/modules/approval/definition-input.ts#approvalTypeOf',
    'apps/api/src/modules/approval/definition-input.ts#createSchema',
    'apps/api/src/modules/approval/definition-input.ts#definitionSchema',
    'apps/api/src/modules/approval/definition-input.ts#toDefinition',
    'apps/api/src/modules/approval/definitions.ts#createProcess',
    'apps/api/src/modules/approval/definitions.ts#discardProcess',
    'apps/api/src/modules/approval/definitions.ts#listProcesses',
    'apps/api/src/modules/approval/definitions.ts#loadProcess',
    'apps/api/src/modules/approval/definitions.ts#newVersion',
    'apps/api/src/modules/approval/definitions.ts#publishProcess',
    'apps/api/src/modules/approval/definitions.ts#replaceDraft',
    '#command',
    '#processResponse',
    '#readCtx',
    '#tenantCtx',
    '#trimProcess',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#parseBody',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/routes.ts#registerTaskRoutes': [
    'apps/api/src/modules/approval/actions.ts#addSign',
    'apps/api/src/modules/approval/actions.ts#approveTask',
    'apps/api/src/modules/approval/actions.ts#disagreeTask',
    'apps/api/src/modules/approval/actions.ts#editTask',
    'apps/api/src/modules/approval/actions.ts#jumpTask',
    'apps/api/src/modules/approval/actions.ts#rejectTask',
    'apps/api/src/modules/approval/actions.ts#rejectToPreviousTask',
    'apps/api/src/modules/approval/actions.ts#transferTask',
    'apps/api/src/modules/approval/node-actions.ts#copySend',
    'apps/api/src/modules/approval/node-actions.ts#retrieveTask',
    '#command',
    '#comment',
    '#fieldRights',
    '#fields',
    '#respondOutcome',
    '#userIdInput',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
    'packages/domain/src/approval/types.ts#ADD_SIGN_TYPES',
    'packages/domain/src/approval/types.ts#MAX_ADD_SIGNERS',
  ],
  'apps/api/src/modules/approval/routes.ts#respondDetail': [
    'apps/api/src/modules/approval/disclosure.ts#detailView',
    'apps/api/src/modules/approval/disclosure.ts#readDetail',
    '#detailViewable',
    '#readCtx',
    '#viewerOf',
  ],
  'apps/api/src/modules/approval/routes.ts#respondHistory': [
    'apps/api/src/modules/approval/disclosure.ts#disclosedFields',
    'apps/api/src/modules/approval/disclosure.ts#projectLog',
    'apps/api/src/modules/approval/disclosure.ts#readDetail',
    'apps/api/src/modules/approval/disclosure.ts#recordsHidden',
    'apps/api/src/modules/approval/disclosure.ts#visibleTasks',
    '#detailViewable',
    '#readCtx',
    '#uuidParam',
    '#viewerOf',
    'apps/api/src/modules/approval/store.ts#pageLogs',
    'apps/api/src/modules/approval/store.ts#pageTasks',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/approval/routes.ts#respondOutcome': ['#respondDetail'],
  'apps/api/src/modules/approval/routes.ts#route:GET /admin-logs': [
    'apps/api/src/modules/approval/access.ts#adminScope',
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/queries.ts#listAdminLogs',
    '#readCtx',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/approval/routes.ts#route:GET /instances': [
    'apps/api/src/modules/approval/queries.ts#listInstances',
    '#readCtx',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/approval/routes.ts#route:GET /notifications': [
    'apps/api/src/modules/approval/queries.ts#listNotifications',
    '#readCtx',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/approval/routes.ts#route:GET /processes': [
    'apps/api/src/modules/approval/access.ts#requireProcessView',
    'apps/api/src/modules/approval/definitions.ts#listProcesses',
    '#readCtx',
    '#trimProcess',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/approval/routes.ts#route:GET /processes/:id': [
    'apps/api/src/modules/approval/access.ts#requireProcessView',
    'apps/api/src/modules/approval/definitions.ts#loadProcess',
    '#readCtx',
    '#trimProcess',
    '#uuidParam',
  ],
  'apps/api/src/modules/approval/routes.ts#route:GET /todos': [
    'apps/api/src/modules/approval/queries.ts#listTodos',
    '#readCtx',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/approval/routes.ts#route:GET /types': [
    'apps/api/src/modules/approval/access.ts#requireProcessView',
    '#tenantCtx',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /exception-admins/handover': [
    'apps/api/src/modules/approval/access.ts#adminScope',
    'apps/api/src/modules/approval/access.ts#requireProcessButton',
    'apps/api/src/modules/approval/handover.ts#discloseHandover',
    'apps/api/src/modules/approval/handover.ts#handoverExceptionAdmin',
    '#command',
    '#userIdInput',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /instances/:id/resubmit': [
    'apps/api/src/modules/approval/access.ts#requireResubmitRight',
    'apps/api/src/modules/approval/actions.ts#resubmit',
    '#command',
    '#fields',
    '#respondOutcome',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /presets/install': [
    'apps/api/src/modules/approval/access.ts#requireProcessButton',
    'apps/api/src/modules/approval/definitions.ts#installPresets',
    '#command',
    '#processResponse',
    '#writeCtx',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /processes': [
    'apps/api/src/modules/approval/access.ts#requireProcessButton',
    'apps/api/src/modules/approval/definition-input.ts#approvalTypeOf',
    'apps/api/src/modules/approval/definition-input.ts#createSchema',
    'apps/api/src/modules/approval/definition-input.ts#toDefinition',
    'apps/api/src/modules/approval/definitions.ts#createProcess',
    '#command',
    '#processResponse',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /processes/:id/simulate': [
    'apps/api/src/modules/approval/access.ts#requireProcessButton',
    '#readCtx',
    '#scope',
    '#simulationData',
    '#uuidParam',
    'apps/api/src/modules/approval/simulation.ts#simulateProcess',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /simulate': [
    'apps/api/src/modules/approval/access.ts#requireProcessButton',
    'apps/api/src/modules/approval/definition-input.ts#approvalTypeOf',
    '#readCtx',
    '#scope',
    '#simulationData',
    'apps/api/src/modules/approval/simulation.ts#simulateByObject',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /tasks/:id/add-sign': [
    'apps/api/src/modules/approval/actions.ts#addSign',
    '#command',
    '#comment',
    '#fieldRights',
    '#respondOutcome',
    '#userIdInput',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
    'packages/domain/src/approval/types.ts#ADD_SIGN_TYPES',
    'packages/domain/src/approval/types.ts#MAX_ADD_SIGNERS',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /tasks/:id/cc': [
    'apps/api/src/modules/approval/node-actions.ts#copySend',
    '#command',
    '#comment',
    '#respondOutcome',
    '#userIdInput',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /tasks/:id/edit': [
    'apps/api/src/modules/approval/actions.ts#editTask',
    '#command',
    '#fieldRights',
    '#fields',
    '#respondOutcome',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /tasks/:id/jump': [
    'apps/api/src/modules/approval/actions.ts#jumpTask',
    '#command',
    '#comment',
    '#respondOutcome',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /tasks/:id/retrieve': [
    'apps/api/src/modules/approval/node-actions.ts#retrieveTask',
    '#command',
    '#respondOutcome',
    '#uuidParam',
    '#writeCtx',
  ],
  'apps/api/src/modules/approval/routes.ts#route:POST /tasks/:id/transfer': [
    'apps/api/src/modules/approval/actions.ts#transferTask',
    '#command',
    '#comment',
    '#respondOutcome',
    '#userIdInput',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#route:PUT /processes/:id/draft': [
    'apps/api/src/modules/approval/access.ts#requireProcessButton',
    'apps/api/src/modules/approval/definition-input.ts#definitionSchema',
    'apps/api/src/modules/approval/definition-input.ts#toDefinition',
    'apps/api/src/modules/approval/definitions.ts#loadProcess',
    'apps/api/src/modules/approval/definitions.ts#replaceDraft',
    '#command',
    '#processResponse',
    '#uuidParam',
    '#writeCtx',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/approval/routes.ts#simulationData': [
    'apps/api/src/modules/approval/context.ts#canonicalId',
    '#userIdInput',
    'packages/domain/src/approval/types.ts#APPROVER_EXPRESSIONS',
  ],
  'apps/api/src/modules/approval/routes.ts#snapshotOfTask': [
    'apps/api/src/modules/approval/adapters.ts#ADAPTERS',
    '#readCtx',
    'apps/api/src/modules/approval/store.ts#instanceOfTask',
    'apps/api/src/modules/approval/store.ts#loadInstance',
  ],
  'apps/api/src/modules/approval/routes.ts#tenantCtx': [
    'apps/api/src/modules/approval/context.ts#canonicalId',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/approval/routes.ts#trimProcess': [
    'apps/api/src/modules/approval/access.ts#isProcessAdmin',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'packages/domain/src/approval/catalog.ts#APPROVAL_PROCESS_OBJECT',
  ],
  'apps/api/src/modules/approval/routes.ts#userIdInput': ['apps/api/src/modules/approval/context.ts#canonicalId'],
  'apps/api/src/modules/approval/routes.ts#uuidParam': [
    'apps/api/src/modules/approval/context.ts#canonicalId',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/approval/routes.ts#viewerOf': ['apps/api/src/modules/approval/access.ts#adminScope'],
  'apps/api/src/modules/approval/routes.ts#writeCtx': ['#readCtx', 'apps/api/src/modules/job/context.ts#revision'],
  'apps/api/src/modules/approval/rules.ts#addSignAllowed': ['#addSignLink'],
  'apps/api/src/modules/approval/rules.ts#addSignLink': ['#ADD_SIGN_ORIGINS', '#REASSIGN_ORIGINS'],
  'apps/api/src/modules/approval/rules.ts#countersignRetrievable': [
    '#addSignLink',
    '#untouchedStatus',
    'apps/api/src/modules/approval/store.ts#OPEN_STATUSES',
  ],
  'apps/api/src/modules/approval/rules.ts#nodeParticipantsOf': ['apps/api/src/modules/approval/store.ts#OPEN_STATUSES'],
  'apps/api/src/modules/approval/rules.ts#retrievableTask': [
    '#AUTO_ORIGINS',
    '#addSignLink',
    '#countersignRetrievable',
    '#nodeOf',
    '#startedAddSign',
    '#untouchedStatus',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'apps/api/src/modules/approval/rules.ts#startedAddSign': ['#ADD_SIGN_ORIGINS'],
  'apps/api/src/modules/approval/rules.ts#untouchedStatus': ['#AUTO_ORIGINS', '#SYSTEM_CLOSED'],
  'apps/api/src/modules/approval/rules.ts#urgeOpen': ['#nodeOf', 'packages/domain/src/approval/types.ts#urgeAllowed'],
  'apps/api/src/modules/approval/rules.ts#votesInTransition': [
    '#ADD_SIGN_TYPE_OF',
    '#addSignLink',
    'packages/domain/src/approval/policies.ts#addSignerVotes',
  ],
  'apps/api/src/modules/approval/simulation.ts#conditionContext': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    '#UUID',
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/simulation.ts#countersignSummary': [
    '#STATUS_RANK',
    'packages/domain/src/approval/countersign.ts#exitRulesOf',
    'packages/domain/src/approval/types.ts#isCountersign',
    'packages/domain/src/approval/types.ts#nodeExits',
  ],
  'apps/api/src/modules/approval/simulation.ts#decideVirtual': [
    '#NOBODY',
    '#candidateOf',
    '#managerOf',
    'packages/domain/src/approval/routing.ts#decideNode',
  ],
  'apps/api/src/modules/approval/simulation.ts#describe': [
    '#managerOf',
    'packages/domain/src/approval/routing.ts#adminRecused',
    'packages/domain/src/approval/routing.ts#avoidSelfExceptionAdmin',
  ],
  'apps/api/src/modules/approval/simulation.ts#preflight': [
    '#NOBODY',
    '#decideVirtual',
    '#managerOf',
    '#virtualFacts',
    'packages/domain/src/approval/routing.ts#adminRecused',
    'packages/domain/src/approval/routing.ts#avoidSelfExceptionAdmin',
    'packages/domain/src/approval/routing.ts#submitBlockers',
    'packages/domain/src/approval/types.ts#approverExpressionsOf',
  ],
  'apps/api/src/modules/approval/simulation.ts#simulateByObject': [
    'apps/api/src/modules/approval/definitions.ts#loadVersion',
    'apps/api/src/modules/approval/matching.ts#candidates',
    'apps/api/src/modules/approval/matching.ts#evaluate',
    'apps/api/src/modules/approval/matching.ts#noProcessMessage',
    'apps/api/src/modules/approval/matching.ts#originalSiteMatch',
    'apps/api/src/modules/approval/matching.ts#replicaMatch',
    '#conditionContext',
    '#preflight',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/simulation.ts#simulateNodes': [
    '#candidateOf',
    '#countersignSummary',
    '#simulatedSeats',
    '#virtualFacts',
    'packages/domain/src/approval/types.ts#approverExpressionsOf',
    'packages/domain/src/approval/types.ts#isCountersign',
    'packages/domain/src/approval/types.ts#nodeExits',
    'packages/domain/src/approval/types.ts#nodeKindOf',
  ],
  'apps/api/src/modules/approval/simulation.ts#simulateProcess': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/definitions.ts#loadProcess',
    '#conditionContext',
    '#preflight',
    '#simulateNodes',
    'packages/domain/src/approval/conditions.ts#evaluateCondition',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
  ],
  'apps/api/src/modules/approval/simulation.ts#simulatedSeats': ['#candidateOf', '#decideVirtual', '#describe'],
  'apps/api/src/modules/approval/simulation.ts#virtualFacts': ['packages/domain/src/approval/recusal.ts#recusalFacts'],
  'apps/api/src/modules/approval/store.ts#activateTask': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#assertPendingRoom',
    '#auditTask',
  ],
  'apps/api/src/modules/approval/store.ts#appendLog': ['apps/api/src/modules/approval/context.ts#actorOf'],
  'apps/api/src/modules/approval/store.ts#assertAssigneeUsable': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/resolver.ts#isAssignable',
  ],
  'apps/api/src/modules/approval/store.ts#assertPendingRoom': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#MAX_PENDING',
  ],
  'apps/api/src/modules/approval/store.ts#auditTask': ['apps/api/src/modules/approval/context.ts#auditApproval'],
  'apps/api/src/modules/approval/store.ts#cancelPending': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#auditTask',
  ],
  'apps/api/src/modules/approval/store.ts#closeAddSigned': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#auditTask',
  ],
  'apps/api/src/modules/approval/store.ts#closeQueued': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#auditTask',
  ],
  'apps/api/src/modules/approval/store.ts#closeTask': ['apps/api/src/modules/approval/context.ts#rowsOf', '#auditTask'],
  'apps/api/src/modules/approval/store.ts#displayWindow': ['#RECENT'],
  'apps/api/src/modules/approval/store.ts#endOpenTasks': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#OPEN_STATUSES',
    '#auditTask',
  ],
  'apps/api/src/modules/approval/store.ts#insertTask': [
    '#assertAssigneeUsable',
    '#assertPendingRoom',
    '#auditTask',
    '#uuidArray',
  ],
  'apps/api/src/modules/approval/store.ts#instanceOf': ['#iso'],
  'apps/api/src/modules/approval/store.ts#instanceOfTask': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/store.ts#loadInstance': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#instanceOf',
  ],
  'apps/api/src/modules/approval/store.ts#loadLogs': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#RECENT',
    '#logOf',
  ],
  'apps/api/src/modules/approval/store.ts#loadTasks': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#BATCH',
    '#taskOf',
  ],
  'apps/api/src/modules/approval/store.ts#logOf': ['#iso'],
  'apps/api/src/modules/approval/store.ts#pageLogs': ['apps/api/src/modules/approval/context.ts#rowsOf', '#logOf'],
  'apps/api/src/modules/approval/store.ts#pageTasks': ['apps/api/src/modules/approval/context.ts#rowsOf', '#taskOf'],
  'apps/api/src/modules/approval/store.ts#resumableInstanceOf': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#instanceOf',
  ],
  'apps/api/src/modules/approval/store.ts#resumeAddSigned': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#assertPendingRoom',
    '#auditTask',
  ],
  'apps/api/src/modules/approval/store.ts#taskOf': ['#iso'],
  'apps/api/src/modules/approval/subjects.ts#freezeSubjects': [
    'apps/api/src/modules/approval/context.ts#approvalError',
    'apps/api/src/modules/approval/context.ts#auditApproval',
    'apps/api/src/modules/approval/context.ts#canonicalId',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#MAX_INSTANCE_SUBJECTS',
    '#UUID',
    '#frozenRows',
    '#unknownSubject',
  ],
  'apps/api/src/modules/approval/subjects.ts#frozenRows': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/approval/subjects.ts#loadRecusalFacts': [
    'apps/api/src/modules/approval/context.ts#canonicalId',
    'apps/api/src/modules/approval/resolver.ts#userOfPerson',
    '#frozenRows',
    'packages/domain/src/approval/recusal.ts#recusalFacts',
  ],
  'apps/api/src/modules/approval/subjects.ts#unknownSubject': [
    'apps/api/src/modules/approval/context.ts#approvalError',
  ],
};
