/**
 * 直接依赖图：区域 api-modules-transfer（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/transfer/access.ts#inTeam': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/permission/manager-identity.ts#managerIdentity',
    'apps/api/src/modules/permission/scope-persons.ts#currentPersons',
  ],
  'apps/api/src/modules/transfer/access.ts#requireManagerBusinessSource': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/manager-identity.ts#managerIdentity',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    '#requireTransferSource',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/access.ts#requireTransferButton': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    '#ROLE_BUTTONS',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/transfer/access.ts#requireTransferSource': [
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#scopeAllowsInTransaction',
    'apps/api/src/modules/permission/scope-persons.ts#currentPersons',
    '#inTeam',
    '#requireTransferButton',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/access.ts#transferDirectActions': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/transfer/completion.ts#completionQuery': [
    'apps/api/src/modules/employment/record-events.ts#recordEventDueSql',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/completion.ts#listCompletionTodos': [
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/context.ts#employmentScopePredicate',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#openTodos',
  ],
  'apps/api/src/modules/transfer/completion.ts#openCompletion': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/completion.ts#openTodos': [
    '#completionQuery',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/completion.ts#reconcileCompletion': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#completionQuery',
    '#openCompletion',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/configuration.ts#mergeDictionary': [
    'packages/domain/src/transfer/catalog.ts#sortTransferDictionary',
  ],
  'apps/api/src/modules/transfer/configuration.ts#readTransferCatalog': [
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    '#mergeDictionary',
    'apps/api/src/modules/transfer/form-configuration.ts#listTransferForms',
    'packages/domain/src/transfer/catalog.ts#TRANSFER_REASONS',
    'packages/domain/src/transfer/catalog.ts#TRANSFER_TYPES',
  ],
  'apps/api/src/modules/transfer/configuration.ts#readTransferSettings': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/transfer/configuration.ts#updateTransferSettings': [
    'apps/api/src/modules/employment/context.ts#assertRevision',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    '#readTransferSettings',
    '#settingInput',
  ],
  'apps/api/src/modules/transfer/employee-managers.ts#managerChoices': [
    'apps/api/src/modules/employment/employees.ts#listEmployees',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    '#managerScope',
  ],
  'apps/api/src/modules/transfer/employee-managers.ts#managerScope': [
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE',
  ],
  'apps/api/src/modules/transfer/employee-managers.ts#requireManagerCandidate': [
    'apps/api/src/modules/employment/employees.ts#getEmployee',
    '#managerScope',
  ],
  'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferBusiness': [
    'apps/api/src/modules/employment/record-store.ts#camelRow',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/record-store.ts#snapshotFields',
    '#requireEmployeeTransferFields',
  ],
  'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferFields': [
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/transfer/employee-managers.ts#requireManagerCandidate',
    '#EMPLOYEE_READONLY_FIELDS',
  ],
  'apps/api/src/modules/transfer/form-configuration.ts#formInput': ['#modes'],
  'apps/api/src/modules/transfer/form-configuration.ts#listTransferForms': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    '#selectForm',
    'packages/domain/src/transfer/catalog.ts#TRANSFER_FORMS',
  ],
  'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm': [
    'apps/api/src/modules/employment/configuration.ts#getCustomFieldsForInheritance',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    'apps/api/src/modules/employment/types.ts#PRESET_FIELD_NAMES',
    'apps/api/src/modules/transfer/configuration.ts#readTransferSettings',
    '#selectForm',
    'packages/domain/src/transfer/catalog.ts#TRANSFER_FORMS',
  ],
  'apps/api/src/modules/transfer/form-configuration.ts#saveTransferForm': [
    'apps/api/src/modules/employment/configuration.ts#getCustomFieldsForInheritance',
    'apps/api/src/modules/employment/context.ts#assertRevision',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    'apps/api/src/modules/employment/types.ts#PRESET_FIELD_NAMES',
    '#formInput',
    '#resolveTransferForm',
    'packages/domain/src/transfer/catalog.ts#TRANSFER_FORMS',
  ],
  'apps/api/src/modules/transfer/initiator-fields.ts#applyInitiatorFieldModes': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#editableModuleFields',
  ],
  'apps/api/src/modules/transfer/linkage/access.ts#ORG_OBJECT': [
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/transfer/linkage/access.ts#authorizeContractChange': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/context.ts#checkFields',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#changedContractFields',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/contracts/rules.ts#contractAction',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/transfer/linkage/access.ts#authorizeLinkageWrite': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    '#authorizeContractChange',
    '#authorizeOrgRole',
    '#authorizeSubordinateField',
    '#changedLinkageFields',
  ],
  'apps/api/src/modules/transfer/linkage/access.ts#authorizeOrgRole': [
    'apps/api/src/modules/org/write-service.ts#requireTransferOrganizationScope',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    '#ORG_OBJECT',
    'apps/api/src/modules/transfer/linkage/validation.ts#ROLE_FIELDS',
  ],
  'apps/api/src/modules/transfer/linkage/access.ts#authorizeSubordinateField': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'apps/api/src/modules/transfer/linkage/validation.ts#RELATION_FIELDS',
  ],
  'apps/api/src/modules/transfer/linkage/access.ts#changedContractFields': ['#changedCustom'],
  'apps/api/src/modules/transfer/linkage/access.ts#changedLinkageFields': [
    'apps/api/src/modules/transfer/linkage/approval.ts#linkageFieldValues',
  ],
  'apps/api/src/modules/transfer/linkage/access.ts#resolveLinkageAccess': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/transfer/linkage/approval.ts#contractFieldEntries': ['#CONTAINER'],
  'apps/api/src/modules/transfer/linkage/approval.ts#contractOwner': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/transfer/linkage/approval.ts#linkageApproval': [
    '#CONTAINER',
    '#contractFieldEntries',
    '#contractOwner',
    '#linkageFieldValues',
    'apps/api/src/modules/transfer/linkage/store.ts#latestLinkage',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/transfer/linkage/contract.ts#assertNoInFlightContract': [
    'apps/api/src/modules/contracts/ports.ts#assertNoInFlightForTransfer',
    '#contractContext',
  ],
  'apps/api/src/modules/transfer/linkage/contract.ts#changeContractOnActivation': [
    'apps/api/src/modules/contracts/ports.ts#changeContractForTransfer',
    '#contractContext',
    '#loadTarget',
    '#validateContractChange',
  ],
  'apps/api/src/modules/transfer/linkage/contract.ts#loadTarget': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/transfer/linkage/contract.ts#validateContractChange': [
    '#assertNoInFlightContract',
    '#loadTarget',
  ],
  'apps/api/src/modules/transfer/linkage/execute.ts#applyTransferCrossLinkage': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/transfer/linkage/contract.ts#changeContractOnActivation',
    '#createItems',
    '#executionDate',
    '#linkageExecuted',
    '#originalPlannedDate',
    '#recordTrialAndHandover',
    'apps/api/src/modules/transfer/linkage/items.ts#attemptLinkageItem',
    'apps/api/src/modules/transfer/linkage/store.ts#latestLinkage',
  ],
  'apps/api/src/modules/transfer/linkage/execute.ts#createItems': [
    'apps/api/src/modules/transfer/linkage/store.ts#dutyLines',
    'packages/domain/src/contracts/rules.ts#addDays',
  ],
  'apps/api/src/modules/transfer/linkage/execute.ts#executionDate': [
    'packages/domain/src/employment/late-execution.ts#resolveLateExecution',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/execute.ts#linkageExecuted': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/transfer/linkage/execute.ts#originalPlannedDate': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
  ],
  'apps/api/src/modules/transfer/linkage/execute.ts#recordTrialAndHandover': [
    'packages/domain/src/contracts/rules.ts#termEnd',
  ],
  'apps/api/src/modules/transfer/linkage/input.ts#linkageSchema': [
    'apps/api/src/modules/contracts/input.ts#fieldsSchema',
    '#ORG_ROLES',
    '#day',
    '#uuid',
  ],
  'apps/api/src/modules/transfer/linkage/input.ts#normalizeLinkage': ['#assertUnique', '#linkageSchema'],
  'apps/api/src/modules/transfer/linkage/items.ts#attemptLinkageItem': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    '#executeItem',
    '#itemFailure',
  ],
  'apps/api/src/modules/transfer/linkage/items.ts#executeItem': [
    'apps/api/src/modules/employment/org-people.ts#ineligibleOrgPeople',
    'apps/api/src/modules/employment/record-edit.ts#editEmploymentRecord',
    'apps/api/src/modules/org/write-service.ts#assignTransferOrganizationPeople',
    'apps/api/src/modules/transfer/linkage/part-time.ts#transferPartTimePort',
    'apps/api/src/modules/transfer/linkage/validation.ts#RELATION_FIELDS',
    'apps/api/src/modules/transfer/linkage/validation.ts#ROLE_FIELDS',
    'apps/api/src/modules/transfer/linkage/validation.ts#requireReportingSubordinate',
    'apps/api/src/modules/transfer/linkage/validation.ts#requireRoleHolder',
  ],
  'apps/api/src/modules/transfer/linkage/items.ts#itemFailure': [
    'apps/api/src/modules/employment/activation-checks.ts#ruleRejection',
  ],
  'apps/api/src/modules/transfer/linkage/items.ts#retryLinkageItem': [
    'apps/api/src/modules/employment/context.ts#assertRevision',
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    'apps/api/src/modules/transfer/linkage/access.ts#authorizeOrgRole',
    'apps/api/src/modules/transfer/linkage/access.ts#authorizeSubordinateField',
    '#attemptLinkageItem',
    '#itemView',
    '#loadLinkageItem',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/part-time.ts#port': ['#UNAVAILABLE'],
  'apps/api/src/modules/transfer/linkage/part-time.ts#transferPartTimePort': ['#port'],
  'apps/api/src/modules/transfer/linkage/routes.ts#authorizeRetry': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/linkage/access.ts#authorizeOrgRole',
    'apps/api/src/modules/transfer/linkage/access.ts#authorizeSubordinateField',
    'apps/api/src/modules/transfer/linkage/items.ts#loadLinkageItem',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/routes.ts#preauthorizeLinkage': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/linkage/access.ts#authorizeLinkageWrite',
    'apps/api/src/modules/transfer/linkage/access.ts#resolveLinkageAccess',
    'apps/api/src/modules/transfer/linkage/store.ts#linkageBeforeCommand',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/transfer/linkage/routes.ts#route:GET /transfers/:id/linkage': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/transfer/linkage/view.ts#readTransferLinkage',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/transfer/linkage/routes.ts#route:GET /transfers/employees/:id/contracts': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/transfer/linkage/routes.ts#route:POST /transfers/linkage-items/:id/retry': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/transfer/linkage/items.ts#retryLinkageItem',
    '#authorizeRetry',
    '#parse',
  ],
  'apps/api/src/modules/transfer/linkage/routes.ts#route:PUT /transfers/:id/linkage': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/transfer/linkage/input.ts#normalizeLinkage',
    '#preauthorizeLinkage',
    'apps/api/src/modules/transfer/linkage/service.ts#requireLinkageSource',
    'apps/api/src/modules/transfer/linkage/service.ts#updateTransferLinkage',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/service.ts#assertTransferLinkageSubmittable': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/transfer/linkage/contract.ts#validateContractChange',
    'apps/api/src/modules/transfer/linkage/store.ts#latestLinkage',
  ],
  'apps/api/src/modules/transfer/linkage/service.ts#requireLinkageSource': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
  ],
  'apps/api/src/modules/transfer/linkage/service.ts#saveNewTransferLinkage': [
    'apps/api/src/modules/transfer/linkage/access.ts#authorizeLinkageWrite',
    'apps/api/src/modules/transfer/linkage/execute.ts#applyTransferCrossLinkage',
    'apps/api/src/modules/transfer/linkage/store.ts#appendLinkageVersion',
    'apps/api/src/modules/transfer/linkage/store.ts#hasLinkage',
    'apps/api/src/modules/transfer/linkage/validation.ts#validateLinkage',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/service.ts#updateTransferLinkage': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    'apps/api/src/modules/employment/write-service.ts#requireSavedBusiness',
    'apps/api/src/modules/transfer/linkage/access.ts#authorizeLinkageWrite',
    'apps/api/src/modules/transfer/linkage/execute.ts#assertLinkageMutable',
    'apps/api/src/modules/transfer/linkage/execute.ts#linkageExecuted',
    'apps/api/src/modules/transfer/linkage/input.ts#dutySubordinateIds',
    '#requireLinkageSource',
    'apps/api/src/modules/transfer/linkage/store.ts#appendLinkageVersion',
    'apps/api/src/modules/transfer/linkage/store.ts#latestLinkage',
    'apps/api/src/modules/transfer/linkage/validation.ts#validateLinkage',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/store.ts#appendLinkageVersion': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    '#dutyLines',
    '#latestLinkage',
  ],
  'apps/api/src/modules/transfer/linkage/store.ts#hasPendingCrossLinkage': ['#hasLinkage', '#latestLinkage'],
  'apps/api/src/modules/transfer/linkage/store.ts#latestLinkage': ['#linkageVersion'],
  'apps/api/src/modules/transfer/linkage/store.ts#linkageBeforeCommand': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#linkageVersion',
  ],
  'apps/api/src/modules/transfer/linkage/store.ts#linkageVersion': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#optionsOf',
  ],
  'apps/api/src/modules/transfer/linkage/validation.ts#requireEligiblePeople': [
    'apps/api/src/modules/employment/org-people.ts#ineligibleOrgPeople',
    '#notEligible',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/validation.ts#requireReportingSubordinate': [
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    '#RELATION_FIELDS',
    '#notEligible',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/validation.ts#requireRoleHolder': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#ROLE_COLUMNS',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/validation.ts#validateLinkage': [
    'apps/api/src/modules/transfer/linkage/contract.ts#validateContractChange',
    'apps/api/src/modules/transfer/linkage/part-time.ts#transferPartTimePort',
    '#notEligible',
    '#requireEligiblePeople',
    '#requireReportingSubordinate',
    '#requireRoleHolder',
  ],
  'apps/api/src/modules/transfer/linkage/view.ts#contractVisible': [
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/transfer/linkage/view.ts#dutyTransferView': [
    'apps/api/src/modules/transfer/linkage/items.ts#itemView',
  ],
  'apps/api/src/modules/transfer/linkage/view.ts#linkageResults': [
    'apps/api/src/modules/transfer/linkage/items.ts#itemView',
    '#dutyTransferView',
    '#trialView',
  ],
  'apps/api/src/modules/transfer/linkage/view.ts#readTransferLinkage': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/transfer/linkage/store.ts#latestLinkage',
    '#contractVisible',
    '#linkageResults',
    '#visibleOptions',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/linkage/view.ts#visibleOptions': ['#pickContractFields', '#trialView'],
  'apps/api/src/modules/transfer/manager-business-references.ts#requireManagerBusinessReferences': [
    'apps/api/src/modules/employment/record-store.ts#camelRow',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/record-store.ts#snapshotFields',
    'apps/api/src/modules/employment/write-service.ts#normalizePatchedInput',
    'apps/api/src/modules/transfer/manager-references.ts#requireManagerReferenceValues',
  ],
  'apps/api/src/modules/transfer/manager-references.ts#effectiveJobs': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
  ],
  'apps/api/src/modules/transfer/manager-references.ts#managerReferenceQuery': [
    'apps/api/src/modules/permission/manager-identity.ts#managerIdentity',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    '#effectiveJobs',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/manager-references.ts#readManagerReferences': [
    'apps/api/src/modules/avatar/references.ts#employeeAvatars',
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
    'apps/api/src/modules/permission/scope-persons.ts#currentPersons',
    '#effectiveJobs',
    '#jobKinds',
    '#managerReferenceQuery',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/manager-references.ts#requireManagerReferenceValues': [
    '#managerReferenceFields',
    '#readManagerReferences',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#managerContext': [
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/permission/manager-identity.ts#managerIdentity',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#managerHasHr': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#route:GET /transfers/manager': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    '#managerContext',
    '#managerHasHr',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#route:GET /transfers/manager/employees': [
    'apps/api/src/modules/employment/context.ts#EMPLOYEE_OBJECT',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/access.ts#requireTransferButton',
    '#managerContext',
    'apps/api/src/modules/transfer/manager-team.ts#managerRowLabels',
    'apps/api/src/modules/transfer/manager-team.ts#readManagerTeam',
    'apps/api/src/modules/transfer/response-disclosure.ts#trimEmploymentManagerReferences',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#route:GET /transfers/manager/references/:field': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/manager-references.ts#readManagerReferences',
    '#managerContext',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#route:GET /transfers/manager/reporting': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#managerContext',
    '#managerHasHr',
    'apps/api/src/modules/transfer/manager-team.ts#readManagerTeam',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#route:GET /transfers/manager/search': [
    'apps/api/src/modules/employment/context.ts#EMPLOYEE_OBJECT',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/access.ts#requireTransferButton',
    '#managerContext',
    'apps/api/src/modules/transfer/manager-team.ts#managerRowLabels',
    'apps/api/src/modules/transfer/manager-team.ts#readManagerTeam',
    'apps/api/src/modules/transfer/response-disclosure.ts#trimEmploymentManagerReferences',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#route:GET /transfers/manager/team': [
    'apps/api/src/modules/employment/context.ts#EMPLOYEE_OBJECT',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/access.ts#requireTransferButton',
    '#managerContext',
    'apps/api/src/modules/transfer/manager-team.ts#managerRowLabels',
    'apps/api/src/modules/transfer/manager-team.ts#readManagerTeam',
    'apps/api/src/modules/transfer/response-disclosure.ts#trimEmploymentManagerReferences',
  ],
  'apps/api/src/modules/transfer/manager-routes.ts#route:GET /transfers/manager/todos': [
    'apps/api/src/modules/approval/queries.ts#listInstances',
    'apps/api/src/modules/approval/queries.ts#listTodos',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
    '#managerContext',
  ],
  'apps/api/src/modules/transfer/manager-team.ts#managerRowLabels': [
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/manager-team.ts#managerTeamQuery': [
    'apps/api/src/modules/permission/manager-identity.ts#managerIdentity',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/manager-team.ts#readManagerTeam': [
    'apps/api/src/modules/avatar/references.ts#employeeAvatars',
    'apps/api/src/modules/permission/scope-hierarchy.ts#scopeRows',
    '#managerTeamQuery',
  ],
  'apps/api/src/modules/transfer/preview-defaults.ts#managerForTransferDepartment': [
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
  ],
  'apps/api/src/modules/transfer/preview.ts#previewTransfer': [
    'apps/api/src/modules/employment/configuration.ts#getCustomFieldsForInheritance',
    'apps/api/src/modules/employment/configuration.ts#readEmploymentSettings',
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/inheritance.ts#inheritancePreview',
    'apps/api/src/modules/employment/inheritance.ts#prepareInheritance',
    'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance',
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/record-store.ts#readEmploymentEmployee',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
    'apps/api/src/modules/transfer/access.ts#transferDirectActions',
    'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferFields',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/service.ts#transferTargetContext',
  ],
  'apps/api/src/modules/transfer/required-fields.ts#assertRequiredTransferFields': [
    'packages/domain/src/transfer/required.ts#missingTransferRequiredFields',
  ],
  'apps/api/src/modules/transfer/response-disclosure.ts#managerCode': ['#MANAGERS'],
  'apps/api/src/modules/transfer/response-disclosure.ts#mapManagerReferences': [
    '#MANAGERS',
    '#managerCode',
    '#mapManagerReferences',
  ],
  'apps/api/src/modules/transfer/response-disclosure.ts#trimEmploymentManagerReferences': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
    'apps/api/src/modules/permission/scope-persons.ts#currentPersons',
    '#mapManagerReferences',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/routes.ts#configurationContext': [
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/job/context.ts#revision',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:GET /transfers/catalog': [
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'apps/api/src/modules/permission/module-access.ts#editableModuleFields',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/access.ts#requireTransferButton',
    'apps/api/src/modules/transfer/configuration.ts#readTransferCatalog',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
    'packages/domain/src/transfer/catalog.ts#TRANSFER_FORMS',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:GET /transfers/departments': [
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/configuration.ts#readTransferSettings',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/manager-references.ts#readManagerReferences',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:GET /transfers/self': [
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/transfer/access.ts#requireTransferButton',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:GET /transfers/settings': [
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/transfer/configuration.ts#readTransferSettings',
    '#configurationContext',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:POST /transfers/employees/:id': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
    'apps/api/src/modules/transfer/linkage/routes.ts#preauthorizeLinkage',
    'apps/api/src/modules/transfer/preview.ts#previewTransfer',
    'apps/api/src/modules/transfer/service.ts#createTransfer',
    'apps/api/src/modules/transfer/service.ts#normalizeTransferInput',
    'apps/api/src/modules/transfer/service.ts#requireDirectTransfer',
    'apps/api/src/modules/transfer/service.ts#requireTransferWrite',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:POST /transfers/employees/:id/preview': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/preview.ts#previewTransfer',
    '#visibleTransferForm',
    'apps/api/src/modules/transfer/service.ts#normalizeTransferInput',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:PUT /transfers/forms/:formId': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/transfer/form-configuration.ts#saveTransferForm',
    '#configurationContext',
    '#parse',
  ],
  'apps/api/src/modules/transfer/routes.ts#route:PUT /transfers/settings': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/transfer/configuration.ts#updateTransferSettings',
    '#configurationContext',
    '#parse',
  ],
  'apps/api/src/modules/transfer/routes.ts#visibleTransferForm': [
    'apps/api/src/modules/permission/module-access.ts#editableModuleFields',
  ],
  'apps/api/src/modules/transfer/service.ts#createTransfer': [
    'apps/api/src/modules/employment/approval-hooks.ts#employmentApprovalHooks',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/inheritance.ts#prepareInheritance',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    'apps/api/src/modules/employment/transitions.ts#transitionEmployment',
    'apps/api/src/modules/employment/write-service.ts#createEmploymentBusiness',
    'apps/api/src/modules/employment/write-service.ts#requireSavedBusiness',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/linkage/input.ts#dutySubordinateIds',
    'apps/api/src/modules/transfer/linkage/service.ts#saveNewTransferLinkage',
    '#normalizeTransferInput',
    '#requireDirectTransfer',
    '#requireTransferWrite',
    '#transferTargetContext',
  ],
  'apps/api/src/modules/transfer/service.ts#normalizeTransferInput': [
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/transfer/configuration.ts#readTransferCatalog',
    'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferFields',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/linkage/input.ts#normalizeLinkage',
    'apps/api/src/modules/transfer/linkage/store.ts#hasLinkage',
    '#schema',
  ],
  'apps/api/src/modules/transfer/service.ts#requireDirectTransfer': [
    'apps/api/src/modules/employment/configuration.ts#readEmploymentSettings',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/access.ts#transferDirectActions',
  ],
  'apps/api/src/modules/transfer/service.ts#requireTransferWrite': [
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
  ],
  'apps/api/src/modules/transfer/service.ts#transferBusinessContext': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    'apps/api/src/modules/transfer/access.ts#requireManagerBusinessSource',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
    'apps/api/src/modules/transfer/configuration.ts#readTransferSettings',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/manager-business-references.ts#requireManagerBusinessReferences',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/transfer/service.ts#transferTargetContext': [
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
    'apps/api/src/modules/transfer/configuration.ts#readTransferSettings',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/manager-references.ts#requireManagerReferenceValues',
  ],
};
