/**
 * 直接依赖图：区域 api-modules-establishment（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/establishment/capacity-read.ts#batchLocalSums': [
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/capacity-read.ts#capacityFor': ['#readCapacity'],
  'apps/api/src/modules/establishment/capacity-read.ts#listCapacities': [
    '#readCapacityBatch',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
  ],
  'apps/api/src/modules/establishment/capacity-read.ts#readCapacity': [
    '#sumLocal',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
  ],
  'apps/api/src/modules/establishment/capacity-read.ts#readCapacityBatch': [
    '#batchLocalSums',
    '#batchSubdivisions',
    'apps/api/src/modules/establishment/schemes.ts#loadSchemeBatch',
  ],
  'apps/api/src/modules/establishment/capacity-read.ts#sumLocal': [
    'apps/api/src/modules/establishment/org-reader.ts#subtreeIds',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/capacity-service.ts#append': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    '#normalize',
    'apps/api/src/modules/establishment/org-reader.ts#assertOrg',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/schemes.ts#periodEnd',
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#invalid',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/capacity-service.ts#createCapacity': [
    '#append',
    '#createCapacity',
    '#syncAncestors',
    'apps/api/src/modules/establishment/constraints.ts#validateCapacity',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/schemes.ts#nextPeriod',
    'apps/api/src/modules/establishment/schemes.ts#periodEnd',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/capacity-service.ts#normalize': [
    'apps/api/src/modules/establishment/org-reader.ts#subtreeIds',
    'apps/api/src/modules/establishment/store.ts#invalid',
    'apps/api/src/modules/establishment/store.ts#nonnegative',
  ],
  'apps/api/src/modules/establishment/capacity-service.ts#propagate': [
    'apps/api/src/modules/establishment/capacity-read.ts#capacityFor',
    '#subdivisionDelta',
    '#updateCapacity',
    'apps/api/src/modules/establishment/schemes.ts#nextPeriod',
    'apps/api/src/modules/establishment/schemes.ts#periodEnd',
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#invalid',
  ],
  'apps/api/src/modules/establishment/capacity-service.ts#syncAncestors': [
    'apps/api/src/modules/establishment/capacity-read.ts#capacityFor',
    '#append',
    '#subdivisionDelta',
    'apps/api/src/modules/establishment/constraints.ts#validateCapacity',
    'apps/api/src/modules/establishment/org-reader.ts#parentOrg',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#audit',
  ],
  'apps/api/src/modules/establishment/capacity-service.ts#updateCapacity': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    '#append',
    '#propagate',
    '#syncAncestors',
    'apps/api/src/modules/establishment/constraints.ts#validateCapacity',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#invalid',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
  ],
  'apps/api/src/modules/establishment/carried-candidates.ts#carriedCandidates': [
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/carried-transfer.ts#applyDelta': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    'apps/api/src/modules/establishment/capacity-service.ts#updateCapacity',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#audit',
  ],
  'apps/api/src/modules/establishment/carried-transfer.ts#assertReleasedEstablishment': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    'apps/api/src/modules/establishment/employment-check.ts#employmentEstablishmentExceeded',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/establishment/carried-transfer.ts#carryEstablishment': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    'apps/api/src/modules/establishment/carried-candidates.ts#carriedCandidates',
    '#applyDelta',
    '#assertReleasedEstablishment',
    '#carriedAllocations',
    '#delta',
    '#reverseCarriedEstablishment',
    '#signature',
    'apps/api/src/modules/establishment/constraints.ts#validateCapacity',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
    'apps/api/src/modules/permission/module-capacity-authorization.ts#employmentCapacityContext',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/establishment/carried-transfer.ts#reconcileCarriedEstablishment': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
    '#carryEstablishment',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/carried-transfer.ts#reverseCarriedEstablishment': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    '#applyDelta',
    '#carriedAllocations',
    'apps/api/src/modules/establishment/constraints.ts#validateCapacity',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/permission/module-capacity-authorization.ts#employmentCapacityContext',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/establishment/constraints.ts#sumChildren': [
    'apps/api/src/modules/establishment/org-reader.ts#subtreeIds',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/constraints.ts#validateCapacity': [
    'apps/api/src/modules/establishment/capacity-read.ts#capacityFor',
    '#sumChildren',
    'apps/api/src/modules/establishment/org-reader.ts#parentOrg',
    'apps/api/src/modules/establishment/store.ts#invalid',
  ],
  'apps/api/src/modules/establishment/copy-service.ts#copyCapacity': [
    'apps/api/src/modules/establishment/capacity-service.ts#createCapacity',
    'apps/api/src/modules/establishment/schemes.ts#nextPeriod',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/copy-service.ts#enqueueCopyJob': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    '#appendJobVersion',
    '#readCopyJob',
    '#validateCapacityIds',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/copy-service.ts#executeCopyJob': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    '#appendJobVersion',
    '#classifyBusinessFailure',
    '#copyCapacity',
    '#readCopyJob',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/store.ts#notify',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/copy-service.ts#listNotifications': [
    'apps/api/src/modules/establishment/store.ts#invalid',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/establishment/copy-service.ts#readCopyJob': [
    'apps/api/src/modules/establishment/store.ts#invalid',
  ],
  'apps/api/src/modules/establishment/copy-service.ts#readCopyJobReport': ['#readCopyJob'],
  'apps/api/src/modules/establishment/copy-service.ts#validateCapacityIds': [
    'apps/api/src/modules/establishment/store.ts#invalid',
  ],
  'apps/api/src/modules/establishment/default-scheme.ts#ensureDefaultScheme': [
    'apps/api/src/audit/record.ts#recordAudit',
    '#DEFAULT_SCHEME_CODE',
    '#action',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#adjustmentProjection': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#affectsEstablishmentOccupancy': [
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/transfer-service.ts#targetCapacities',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#employmentEstablishmentExceeded': [
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/establishment/carried-transfer.ts#reconcileCarriedEstablishment',
    '#matchesOccupancy',
    '#projectedMembers',
    'apps/api/src/modules/establishment/membership-windows.ts#membershipWindows',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/transfer-service.ts#targetCapacities',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#establishmentPeriodStartsWithin': [
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#nextReservedTransfer': [
    'apps/api/src/modules/employment/activation-store.ts#pendingActivationState',
    'apps/api/src/modules/employment/timeline.ts#operationKey',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#occupancyRows': [
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#pendingTransfers': [
    'apps/api/src/modules/employment/activation-store.ts#pendingActivationState',
    'apps/api/src/modules/employment/timeline.ts#operationKey',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#projectAdjustments': [
    'apps/api/src/modules/employment/org-adjustment-projection.ts#projectOrgAdjustmentRecords',
    'packages/domain/src/contracts/rules.ts#addDays',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#projectTarget': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/reporting-cycle.ts#insertedWindow',
    'apps/api/src/modules/employment/reporting-cycle.ts#recordWindow',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
    '#nextReservedTransfer',
    '#projectAdjustments',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#projectedMembers': [
    'apps/api/src/modules/employment/record-store.ts#camelRow',
    'apps/api/src/modules/employment/record-store.ts#snapshotFields',
    'apps/api/src/modules/employment/reporting-cycle.ts#insertedWindow',
    '#adjustmentProjection',
    '#camelFields',
    '#maximumMembers',
    '#occupancyRows',
    '#pendingTransfers',
    '#projectAdjustments',
    '#projectTarget',
    '#resolveProjectedTransfer',
    'apps/api/src/modules/establishment/membership-windows.ts#clipMembership',
    'apps/api/src/modules/establishment/settings.ts#readSettings',
  ],
  'apps/api/src/modules/establishment/employment-check.ts#resolveProjectedTransfer': [
    'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
  ],
  'apps/api/src/modules/establishment/membership-windows.ts#membershipWindows': [
    'apps/api/src/modules/establishment/org-reader.ts#subtreeIds',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
  'apps/api/src/modules/establishment/org-reader.ts#assertOrg': ['#createTxOrgHierarchyReader'],
  'apps/api/src/modules/establishment/org-reader.ts#createTxOrgHierarchyReader': [
    'apps/api/src/modules/establishment/store.ts#rowsOf',
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
    'packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS',
  ],
  'apps/api/src/modules/establishment/org-reader.ts#subtreeIds': ['#createTxOrgHierarchyReader'],
  'apps/api/src/modules/establishment/routes.ts#OBJECT': [
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/establishment/routes.ts#capacity': ['#amount', '#date'],
  'apps/api/src/modules/establishment/routes.ts#capacityPatch': ['#capacity', '#date'],
  'apps/api/src/modules/establishment/routes.ts#checkCapacity': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#checkScheme': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#date': ['apps/api/src/modules/org/read-model.ts#validIsoDate'],
  'apps/api/src/modules/establishment/routes.ts#route:DELETE /api/tenant/establishment/schemes/:id': [
    '#BASE',
    '#OBJECT',
    '#checkScheme',
    'apps/api/src/modules/establishment/schemes.ts#deleteScheme',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'packages/domain/src/platform/standard-presets.ts#ESTABLISHMENT_SCHEME_DATASOURCE',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/capacities': [
    'apps/api/src/modules/establishment/capacity-read.ts#listCapacities',
    '#BASE',
    '#OBJECT',
    '#queryUuid',
    '#trimCapacities',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/capacities/:id': [
    '#BASE',
    '#OBJECT',
    '#trimCapacities',
    '#visibleCapacity',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/copy-jobs/:id': [
    '#BASE',
    '#OBJECT',
    '#visibleCopyJob',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/copy-jobs/:id/report': [
    'apps/api/src/modules/establishment/copy-service.ts#readCopyJobReport',
    '#BASE',
    '#OBJECT',
    '#visibleCopyJob',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/notifications': [
    'apps/api/src/modules/establishment/copy-service.ts#listNotifications',
    '#BASE',
    '#OBJECT',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/schemes': [
    '#BASE',
    '#OBJECT',
    'apps/api/src/modules/establishment/schemes.ts#loadSchemeBatch',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    'packages/domain/src/platform/standard-presets.ts#ESTABLISHMENT_SCHEME_DATASOURCE',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/schemes/:id': [
    '#BASE',
    '#OBJECT',
    '#visibleScheme',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'packages/domain/src/platform/standard-presets.ts#ESTABLISHMENT_SCHEME_DATASOURCE',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:GET /api/tenant/establishment/settings': [
    '#BASE',
    'apps/api/src/modules/establishment/settings.ts#readSettings',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#readContext',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:PATCH /api/tenant/establishment/capacities/:id': [
    'apps/api/src/modules/establishment/capacity-service.ts#updateCapacity',
    '#BASE',
    '#OBJECT',
    '#capacityPatch',
    '#checkCapacity',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-capacity-authorization.ts#capacityContext',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:PATCH /api/tenant/establishment/schemes/:id': [
    '#BASE',
    '#OBJECT',
    '#checkScheme',
    '#schemePatch',
    'apps/api/src/modules/establishment/schemes.ts#updateScheme',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/platform/standard-presets.ts#ESTABLISHMENT_SCHEME_DATASOURCE',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:POST /api/tenant/establishment/capacities': [
    'apps/api/src/modules/establishment/capacity-service.ts#createCapacity',
    '#BASE',
    '#OBJECT',
    '#capacity',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/permission/module-capacity-authorization.ts#capacityContext',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:POST /api/tenant/establishment/copy-jobs': [
    'apps/api/src/modules/establishment/copy-service.ts#enqueueCopyJob',
    '#BASE',
    '#OBJECT',
    '#visibleCapacity',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:POST /api/tenant/establishment/copy-jobs/:id/execute': [
    'apps/api/src/modules/establishment/copy-service.ts#executeCopyJob',
    '#BASE',
    '#OBJECT',
    '#visibleCopyJob',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-capacity-authorization.ts#capacityContext',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:POST /api/tenant/establishment/schemes': [
    '#BASE',
    '#OBJECT',
    '#scheme',
    'apps/api/src/modules/establishment/schemes.ts#createScheme',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/platform/standard-presets.ts#ESTABLISHMENT_SCHEME_DATASOURCE',
  ],
  'apps/api/src/modules/establishment/routes.ts#route:PUT /api/tenant/establishment/settings': [
    '#BASE',
    '#settings',
    'apps/api/src/modules/establishment/settings.ts#updateSettings',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#readContext',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
  ],
  'apps/api/src/modules/establishment/routes.ts#scheme': ['#date'],
  'apps/api/src/modules/establishment/routes.ts#schemePatch': ['#date', '#scheme'],
  'apps/api/src/modules/establishment/routes.ts#settings': ['#date'],
  'apps/api/src/modules/establishment/routes.ts#trimCapacities': [
    '#OBJECT',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
  ],
  'apps/api/src/modules/establishment/routes.ts#visibleCapacity': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/establishment/routes.ts#visibleCopyJob': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    'apps/api/src/modules/establishment/copy-service.ts#readCopyJob',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
  ],
  'apps/api/src/modules/establishment/routes.ts#visibleScheme': [
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/establishment/schemes.ts#appendScheme': [
    'apps/api/src/modules/establishment/org-reader.ts#assertOrg',
    '#loadScheme',
    '#normalize',
  ],
  'apps/api/src/modules/establishment/schemes.ts#checkSchemeLifecycle': [
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/schemes.ts#createScheme': [
    '#appendScheme',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
  ],
  'apps/api/src/modules/establishment/schemes.ts#deleteScheme': [
    '#loadScheme',
    '#updateScheme',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/schemes.ts#nextPeriod': [
    '#periodEnd',
    'apps/api/src/modules/establishment/store.ts#invalid',
  ],
  'apps/api/src/modules/establishment/schemes.ts#normalize': [
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#invalid',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/schemes.ts#periodEnd': [
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#invalid',
  ],
  'apps/api/src/modules/establishment/schemes.ts#updateScheme': [
    '#appendScheme',
    '#checkSchemeLifecycle',
    '#loadScheme',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
  ],
  'apps/api/src/modules/establishment/settings.ts#updateSettings': [
    '#readSettings',
    'apps/api/src/modules/establishment/store.ts#assertRevision',
    'apps/api/src/modules/establishment/store.ts#audit',
    'apps/api/src/modules/establishment/store.ts#businessDate',
    'apps/api/src/modules/establishment/store.ts#lockEstablishment',
    'apps/api/src/modules/establishment/store.ts#today',
  ],
  'apps/api/src/modules/establishment/store.ts#audit': ['apps/api/src/audit/record.ts#recordAudit'],
  'apps/api/src/modules/establishment/store.ts#businessDate': [
    '#invalid',
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
  ],
  'apps/api/src/modules/establishment/store.ts#lockEstablishment': [
    'apps/api/src/modules/establishment/default-scheme.ts#ensureDefaultScheme',
    'apps/api/src/modules/org/locks.ts#lockOrganizationSettings',
  ],
  'apps/api/src/modules/establishment/store.ts#nonnegative': ['#invalid'],
  'apps/api/src/modules/establishment/store.ts#notify': ['#audit'],
  'apps/api/src/modules/establishment/store.ts#today': ['packages/domain/src/tenant-time.ts#tenantLocalDate'],
  'apps/api/src/modules/establishment/transfer-service.ts#targetCapacities': [
    'apps/api/src/modules/establishment/capacity-read.ts#readCapacity',
    'apps/api/src/modules/establishment/schemes.ts#loadScheme',
    'apps/api/src/modules/establishment/store.ts#rowsOf',
  ],
};
