/**
 * 直接依赖图：区域 api-modules-contracts（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/contracts/adapter.ts#contractAdapter': [
    '#transition',
    'apps/api/src/modules/contracts/context.ts#audit',
    'apps/api/src/modules/contracts/context.ts#checkFields',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/contracts/context.ts#lockEmployee',
    'apps/api/src/modules/contracts/input.ts#fieldsSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/modules/contracts/quarantine.ts#assertNotQuarantined',
    'apps/api/src/modules/contracts/service.ts#applyRequest',
    'apps/api/src/modules/contracts/service.ts#assertNoInFlight',
    'apps/api/src/modules/contracts/service.ts#businessFields',
    'apps/api/src/modules/contracts/service.ts#loadContract',
    'apps/api/src/modules/contracts/service.ts#loadRequest',
    'apps/api/src/modules/contracts/service.ts#mergeFields',
    'apps/api/src/modules/contracts/service.ts#prepare',
    'apps/api/src/modules/contracts/service.ts#requestWriteFields',
    'packages/domain/src/contracts/rules.ts#CONTRACT_FLOW',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/adapter.ts#transition': [
    'apps/api/src/modules/contracts/context.ts#audit',
    'apps/api/src/modules/contracts/service.ts#loadRequest',
  ],
  'apps/api/src/modules/contracts/configuration.ts#saveMaster': [
    'apps/api/src/modules/contracts/context.ts#audit',
    'apps/api/src/modules/contracts/context.ts#revision',
    'apps/api/src/modules/contracts/input.ts#parse',
  ],
  'apps/api/src/modules/contracts/configuration.ts#saveRule': [
    'apps/api/src/modules/approval/resolver.ts#isActiveAccount',
    '#rules',
    '#verifyIds',
    'apps/api/src/modules/contracts/context.ts#audit',
    'apps/api/src/modules/contracts/context.ts#revision',
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/modules/contracts/input.ts#ruleSchema',
  ],
  'apps/api/src/modules/contracts/configuration.ts#saveSettings': [
    '#settings',
    '#verifyIds',
    'apps/api/src/modules/contracts/context.ts#audit',
    'apps/api/src/modules/contracts/context.ts#revision',
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/modules/contracts/input.ts#settingsSchema',
  ],
  'apps/api/src/modules/contracts/configuration.ts#verifyIds': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/contracts/context.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/context.ts#checkFields': [
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/context.ts#checkOperationScope': ['#checkScope'],
  'apps/api/src/modules/contracts/context.ts#checkScope': [
    '#currentPrimary',
    'apps/api/src/modules/employment/visibility.ts#isEmploymentRecordVisible',
    'apps/api/src/modules/permission/scope-resolver.ts#personnelCreationScope',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/context.ts#currentPrimary': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
  ],
  'apps/api/src/modules/contracts/context.ts#lockEmployee': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/contracts/imports.ts#applyRows': [
    'apps/api/src/modules/contracts/configuration.ts#settings',
    'apps/api/src/modules/contracts/context.ts#lockEmployee',
    '#checkImportScope',
    '#importTarget',
    '#initializePeople',
    'apps/api/src/modules/contracts/service.ts#createCommand',
  ],
  'apps/api/src/modules/contracts/imports.ts#checkImportScope': [
    'apps/api/src/modules/contracts/configuration.ts#settings',
    'apps/api/src/modules/contracts/context.ts#checkOperationScope',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    '#importTarget',
  ],
  'apps/api/src/modules/contracts/imports.ts#importContracts': [
    'apps/api/src/audit/record.ts#recordImportLog',
    '#applyRows',
    '#importFailure',
    '#importSchema',
    '#previewImport',
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/imports.ts#importSchema': [
    'apps/api/src/modules/contracts/input.ts#fieldsSchema',
    'apps/api/src/modules/contracts/input.ts#uuid',
  ],
  'apps/api/src/modules/contracts/imports.ts#initializePeople': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/contracts/context.ts#revision',
    'apps/api/src/modules/contracts/service.ts#deleteContract',
    'apps/api/src/modules/contracts/service.ts#portfolioRevision',
  ],
  'apps/api/src/modules/contracts/imports.ts#previewImport': [
    '#PreviewRollback',
    '#applyRows',
    '#importSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
  ],
  'apps/api/src/modules/contracts/input.ts#commandSchema': ['#fieldsSchema', '#uuid'],
  'apps/api/src/modules/contracts/input.ts#fieldsSchema': ['#day', '#money', '#uuid'],
  'apps/api/src/modules/contracts/input.ts#ruleSchema': ['#uuid'],
  'apps/api/src/modules/contracts/input.ts#settingsSchema': ['#uuid'],
  'apps/api/src/modules/contracts/ports.ts#assertNoInFlightForTransfer': [
    'apps/api/src/modules/contracts/service.ts#assertNoInFlight',
  ],
  'apps/api/src/modules/contracts/ports.ts#changeContractForTransfer': ['#portCommand'],
  'apps/api/src/modules/contracts/ports.ts#portCommand': [
    '#constraintName',
    'apps/api/src/modules/contracts/service.ts#createCommand',
  ],
  'apps/api/src/modules/contracts/quarantine.ts#assertNotQuarantined': ['#isQuarantined'],
  'apps/api/src/modules/contracts/quarantine.ts#isQuarantined': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/contracts/queries.ts#allContracts': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
  ],
  'apps/api/src/modules/contracts/queries.ts#listContracts': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/contracts/configuration.ts#settings',
    '#allContracts',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
    'apps/api/src/modules/permission/scope-persons.ts#currentPersons',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/recovery.ts#cancelFailedRequest': [
    'apps/api/src/modules/approval/actions.ts#cancel',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/contracts/context.ts#audit',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/contracts/context.ts#lockEmployee',
    'apps/api/src/modules/contracts/context.ts#revision',
    'apps/api/src/modules/contracts/quarantine.ts#isQuarantined',
    'apps/api/src/modules/contracts/service.ts#loadRequest',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/routes.ts#authorizeImport': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/context.ts#checkFields',
    'apps/api/src/modules/contracts/imports.ts#checkImportScope',
    'apps/api/src/modules/contracts/imports.ts#importSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/routes.ts#downloadErrors': [
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/audit/record.ts#recordOperationLog',
    'apps/api/src/modules/contracts/imports.ts#errorsCsv',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/routes.ts#importPreview': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/modules/contracts/imports.ts#importSchema',
    'apps/api/src/modules/contracts/imports.ts#previewImport',
    'apps/api/src/modules/contracts/input.ts#parse',
    '#authorizeImport',
    '#downloadErrors',
  ],
  'apps/api/src/modules/contracts/routes.ts#registerConfiguration': [
    'apps/api/src/modules/contracts/configuration.ts#rules',
    'apps/api/src/modules/contracts/configuration.ts#saveRule',
    'apps/api/src/modules/contracts/configuration.ts#saveSettings',
    'apps/api/src/modules/contracts/configuration.ts#settings',
    '#registerMasters',
    '#routeContext',
    '#trim',
    '#write',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
  ],
  'apps/api/src/modules/contracts/routes.ts#registerImports': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/imports.ts#importContracts',
    '#authorizeImport',
    '#importPreview',
    '#routeContext',
    '#write',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/contracts/routes.ts#registerMasters': [
    'apps/api/src/modules/contracts/configuration.ts#saveMaster',
    '#routeContext',
    '#trim',
    '#write',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:GET /': [
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/modules/contracts/queries.ts#listContracts',
    '#routeContext',
    '#trim',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:GET /employees/:id/revision': [
    'apps/api/src/modules/contracts/context.ts#checkScope',
    '#routeContext',
    'apps/api/src/modules/contracts/service.ts#portfolioRevision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:GET /failures': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    '#routeContext',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:GET /records/:id': [
    'apps/api/src/modules/contracts/context.ts#checkScope',
    '#routeContext',
    '#trim',
    'apps/api/src/modules/contracts/service.ts#loadContract',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:GET /requests/:id': [
    'apps/api/src/modules/contracts/context.ts#checkScope',
    '#routeContext',
    '#trim',
    'apps/api/src/modules/contracts/service.ts#loadRequest',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:GET /rules': [
    'apps/api/src/modules/contracts/configuration.ts#rules',
    '#routeContext',
    '#trim',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:GET /settings': [
    'apps/api/src/modules/contracts/configuration.ts#settings',
    '#routeContext',
    '#trim',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:POST /batch': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/context.ts#checkFields',
    'apps/api/src/modules/contracts/context.ts#checkOperationScope',
    'apps/api/src/modules/contracts/input.ts#commandSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
    '#routeContext',
    '#write',
    'apps/api/src/modules/contracts/service.ts#batchCommands',
    'apps/api/src/modules/contracts/service.ts#loadContract',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/contracts/rules.ts#contractAction',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:POST /commands': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/context.ts#checkFields',
    'apps/api/src/modules/contracts/context.ts#checkOperationScope',
    'apps/api/src/modules/contracts/input.ts#commandSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
    '#routeContext',
    '#write',
    'apps/api/src/modules/contracts/service.ts#createCommand',
    'apps/api/src/modules/contracts/service.ts#loadContract',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/contracts/rules.ts#contractAction',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:POST /imports': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/imports.ts#importContracts',
    '#authorizeImport',
    '#importPreview',
    '#routeContext',
    '#write',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:POST /imports/errors': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/imports.ts#importContracts',
    '#authorizeImport',
    '#importPreview',
    '#routeContext',
    '#write',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:POST /imports/preview': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/imports.ts#importContracts',
    '#authorizeImport',
    '#importPreview',
    '#routeContext',
    '#write',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:POST /requests/:id/cancel': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/modules/contracts/recovery.ts#cancelFailedRequest',
    '#routeContext',
    '#write',
    'apps/api/src/modules/contracts/service.ts#loadRequest',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/contracts/routes.ts#route:PUT /settings': [
    'apps/api/src/modules/contracts/configuration.ts#saveSettings',
    '#routeContext',
    '#write',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
  ],
  'apps/api/src/modules/contracts/routes.ts#routeContext': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFieldsInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/routes.ts#trim': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
  ],
  'apps/api/src/modules/contracts/routes.ts#write': [
    'apps/api/src/modules/contracts/context.ts#checkScope',
    '#requireMasterScope',
    '#trim',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/service.ts#appliedFields': ['#businessFields', '#normalizedActualDate'],
  'apps/api/src/modules/contracts/service.ts#applyRequest': [
    'apps/api/src/modules/contracts/context.ts#audit',
    'apps/api/src/modules/contracts/context.ts#checkScope',
    'apps/api/src/modules/contracts/context.ts#lockEmployee',
    '#appliedFields',
    '#assertActivationAllowed',
    '#assertOperationState',
    '#assertSourceRevision',
    '#bumpPortfolio',
    '#correctedState',
    '#loadContract',
    '#loadRequest',
    '#setContractState',
    'packages/domain/src/contracts/rules.ts#addDays',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/service.ts#assertActivationAllowed': [
    'apps/api/src/modules/contracts/quarantine.ts#assertNotQuarantined',
    '#assertNoInFlight',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/service.ts#assertNoInFlight': ['apps/api/src/modules/approval/context.ts#rowsOf'],
  'apps/api/src/modules/contracts/service.ts#assertRestorationAllowed': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
  ],
  'apps/api/src/modules/contracts/service.ts#assertSourceRevision': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/contracts/context.ts#revision',
  ],
  'apps/api/src/modules/contracts/service.ts#batchCommands': [
    'apps/api/src/audit/record.ts#recordOperationLog',
    'apps/api/src/modules/contracts/context.ts#lockEmployee',
    'apps/api/src/modules/contracts/input.ts#commandSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
    '#createCommand',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'apps/api/src/modules/contracts/service.ts#businessFields': [
    'packages/domain/src/contracts/rules.ts#CONTRACT_FIELDS',
  ],
  'apps/api/src/modules/contracts/service.ts#correctedState': ['#assertRestorationAllowed'],
  'apps/api/src/modules/contracts/service.ts#createCommand': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/approval/engine.ts#startOrResume',
    'apps/api/src/modules/contracts/context.ts#audit',
    '#applyRequest',
    '#assertNoInFlight',
    '#correctedState',
    '#prepare',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/service.ts#deleteContract': [
    'apps/api/src/modules/contracts/context.ts#audit',
    '#bumpPortfolio',
  ],
  'apps/api/src/modules/contracts/service.ts#nextSigningCount': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/service.ts#prepare': [
    'apps/api/src/modules/contracts/configuration.ts#settings',
    'apps/api/src/modules/contracts/context.ts#checkFields',
    'apps/api/src/modules/contracts/context.ts#checkOperationScope',
    'apps/api/src/modules/contracts/context.ts#lockEmployee',
    'apps/api/src/modules/contracts/context.ts#revision',
    'apps/api/src/modules/contracts/input.ts#commandSchema',
    'apps/api/src/modules/contracts/input.ts#parse',
    '#assertOperationState',
    '#businessFields',
    '#loadContract',
    '#nextSigningCount',
    '#normalizedActualDate',
    '#preparedFields',
    '#validateReferences',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/contracts/service.ts#requestWriteFields': ['#businessFields'],
  'apps/api/src/modules/contracts/service.ts#setContractState': [
    'apps/api/src/modules/contracts/context.ts#audit',
    '#bumpPortfolio',
  ],
  'apps/api/src/modules/contracts/service.ts#validateReferences': [
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/contracts/configuration.ts#verifyIds',
    'apps/api/src/modules/contracts/context.ts#checkOperationScope',
    'apps/api/src/modules/contracts/context.ts#currentPrimary',
    'apps/api/src/modules/employment/fields.ts#validateCustomValue',
  ],
  'apps/api/src/modules/contracts/todos.ts#receiptError': ['apps/api/src/audit/failures.ts#isDefiniteFailure'],
  'apps/api/src/modules/contracts/todos.ts#registerMergedTodos': [
    'apps/api/src/modules/approval/access.ts#requireResubmitRight',
    'apps/api/src/modules/approval/actions.ts#approveTask',
    'apps/api/src/modules/approval/actions.ts#disagreeTask',
    'apps/api/src/modules/approval/actions.ts#rejectTask',
    'apps/api/src/modules/approval/actions.ts#resubmit',
    'apps/api/src/modules/approval/context.ts#rowsOf',
    'apps/api/src/modules/approval/store.ts#instanceOfTask',
    'apps/api/src/modules/approval/store.ts#loadInstance',
    'apps/api/src/modules/contracts/input.ts#parse',
    'apps/api/src/modules/contracts/routes.ts#routeContext',
    '#receiptError',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
};
