/**
 * 直接依赖图：区域 api-modules-talent（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/talent/access.ts#canSee': ['apps/api/src/modules/permission/module-route-access.ts#visible'],
  'apps/api/src/modules/talent/access.ts#checkWriteFields': [
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    '#UNIT_SELECTION',
    '#codeOf',
  ],
  'apps/api/src/modules/talent/access.ts#codeOf': ['packages/domain/src/talent/catalog.ts#TALENT_OBJECTS'],
  'apps/api/src/modules/talent/access.ts#listEnvelope': [
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    '#isDictionary',
  ],
  'apps/api/src/modules/talent/access.ts#nestedDimensionReader': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#NESTED_DIMENSION_FIELDS',
    '#canSee',
    '#codeOf',
    '#talentScope',
  ],
  'apps/api/src/modules/talent/access.ts#requireCreatable': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    '#TALENT_LABELS',
  ],
  'apps/api/src/modules/talent/access.ts#requireVisible': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    '#TALENT_LABELS',
  ],
  'apps/api/src/modules/talent/access.ts#scopeColumns': ['#isDictionary'],
  'apps/api/src/modules/talent/access.ts#talentContext': [
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    '#codeOf',
  ],
  'apps/api/src/modules/talent/access.ts#talentScope': [
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    '#codeOf',
  ],
  'apps/api/src/modules/talent/access.ts#talentWriteContext': [
    'apps/api/src/modules/permission/module-route-access.ts#button',
    '#DATA_OPERATION',
    '#WRITE_BUTTONS',
    '#codeOf',
    '#talentContext',
  ],
  'apps/api/src/modules/talent/access.ts#trimTalentList': [
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    '#codeOf',
  ],
  'apps/api/src/modules/talent/access.ts#viewableFields': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#codeOf',
  ],
  'apps/api/src/modules/talent/access.ts#visibleSql': ['apps/api/src/modules/permission/module-access.ts#scopeSql'],
  'apps/api/src/modules/talent/candidates.ts#candidateContext': [
    'apps/api/src/modules/talent/access.ts#checkWriteFields',
    'apps/api/src/modules/talent/access.ts#talentContext',
    'apps/api/src/modules/talent/access.ts#talentWriteContext',
  ],
  'apps/api/src/modules/talent/candidates.ts#organizationAccess': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/talent/candidates.ts#ownerObject': ['#OWNER_OBJECTS'],
  'apps/api/src/modules/talent/candidates.ts#registerCandidates': [
    'apps/api/src/modules/talent/access.ts#fieldVisible',
    'apps/api/src/modules/talent/access.ts#listEnvelope',
    'apps/api/src/modules/talent/access.ts#scopeColumns',
    'apps/api/src/modules/talent/access.ts#talentContext',
    'apps/api/src/modules/talent/access.ts#talentScope',
    'apps/api/src/modules/talent/access.ts#trimTalentList',
    'apps/api/src/modules/talent/access.ts#viewableFields',
    'apps/api/src/modules/talent/access.ts#visibleSql',
    '#candidateContext',
    '#organizationAccess',
    '#ownerObject',
    'apps/api/src/modules/talent/http.ts#TALENT_BASE',
    'apps/api/src/modules/talent/http.ts#nameQuery',
    'apps/api/src/modules/talent/http.ts#pageQuery',
    'apps/api/src/modules/talent/http.ts#typeQuery',
    'apps/api/src/modules/talent/owner-units.ts#authorizedUnits',
    'apps/api/src/modules/talent/read-model.ts#listDescriptionTypes',
    'apps/api/src/modules/talent/read-model.ts#listDimensions',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#checkReferences': [
    'apps/api/src/modules/talent/access.ts#fieldVisible',
    'apps/api/src/modules/talent/access.ts#requireVisible',
    '#VIOLATION_MESSAGES',
    'apps/api/src/modules/talent/write-support.ts#rowsOf',
    'packages/domain/src/talent/rules.ts#criterionDimensionValues',
    'packages/domain/src/talent/rules.ts#criterionDimensionViolation',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#createCategory': [
    '#N',
    'apps/api/src/modules/talent/owner-units.ts#ownerUnit',
    'apps/api/src/modules/talent/read-model.ts#loadCategory',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#created',
    'apps/api/src/modules/talent/write-support.ts#owned',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#createCriterion': [
    '#C',
    '#auditCriterion',
    '#checkReferences',
    '#replaceReferences',
    'apps/api/src/modules/talent/owner-units.ts#ownerUnit',
    'apps/api/src/modules/talent/read-model.ts#loadCriterion',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#created',
    'apps/api/src/modules/talent/write-support.ts#owned',
    'apps/api/src/modules/talent/write-support.ts#referenced',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#deleteCategory': [
    '#N',
    'apps/api/src/modules/talent/read-model.ts#loadCategory',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
    'apps/api/src/modules/talent/write-support.ts#rejectInUse',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#deleteCriterion': [
    '#C',
    '#auditCriterion',
    'apps/api/src/modules/talent/model-image-service.ts#cleanupCriterionImages',
    'apps/api/src/modules/talent/read-model.ts#loadCriterion',
    'apps/api/src/modules/talent/references.ts#criterionReferrer',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#setDimensionCategory': [
    '#C',
    '#auditCriterion',
    'apps/api/src/modules/talent/read-model.ts#loadCriterion',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#bumped',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#updateCategory': [
    '#N',
    'apps/api/src/modules/talent/read-model.ts#loadCategory',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#bumped',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/criterion-service.ts#updateCriterion': [
    '#C',
    '#auditCriterion',
    '#checkReferences',
    '#replaceReferences',
    'apps/api/src/modules/talent/owner-units.ts#relationUnit',
    'apps/api/src/modules/talent/read-model.ts#loadCriterion',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#bumped',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
    'apps/api/src/modules/talent/write-support.ts#referenced',
  ],
  'apps/api/src/modules/talent/dimension-service.ts#checkSuggestionTypes': [
    'apps/api/src/modules/talent/write-support.ts#rowsOf',
  ],
  'apps/api/src/modules/talent/dimension-service.ts#createDimension': [
    '#D',
    '#checkSuggestionTypes',
    '#duplicate',
    '#referencedCategory',
    '#replaceDetails',
    '#requireUnique',
    'apps/api/src/modules/talent/owner-units.ts#ownerUnit',
    'apps/api/src/modules/talent/read-model.ts#loadDimension',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#created',
    'apps/api/src/modules/talent/write-support.ts#owned',
    'apps/api/src/modules/talent/write-support.ts#referenced',
    'apps/api/src/modules/talent/write-support.ts#requireLibraryCreatable',
  ],
  'apps/api/src/modules/talent/dimension-service.ts#deleteDimension': [
    '#D',
    'apps/api/src/modules/talent/read-model.ts#loadDimension',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
    'apps/api/src/modules/talent/write-support.ts#rejectInUse',
  ],
  'apps/api/src/modules/talent/dimension-service.ts#duplicate': ['#duplicateError'],
  'apps/api/src/modules/talent/dimension-service.ts#duplicateError': [
    'packages/domain/src/talent/catalog.ts#TALENT_DUPLICATE_MESSAGE',
  ],
  'apps/api/src/modules/talent/dimension-service.ts#referencedCategory': [
    'apps/api/src/modules/talent/write-support.ts#referenced',
    'apps/api/src/modules/talent/write-support.ts#rowsOf',
  ],
  'apps/api/src/modules/talent/dimension-service.ts#requireUnique': ['#D', '#duplicateError'],
  'apps/api/src/modules/talent/dimension-service.ts#updateDimension': [
    '#D',
    '#checkSuggestionTypes',
    '#duplicate',
    '#referencedCategory',
    '#replaceDetails',
    '#requireUnique',
    'apps/api/src/modules/talent/read-model.ts#loadDimension',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#bumped',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/form-access.ts#schemaFields': ['apps/api/src/modules/talent/access.ts#UNIT_SELECTION'],
  'apps/api/src/modules/talent/form-access.ts#talentFormHandler': [
    'apps/api/src/modules/permission/module-access.ts#editableModuleFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/owner-units.ts#NO_UNIT_MESSAGE',
    'apps/api/src/modules/talent/access.ts#TALENT_LABELS',
    'apps/api/src/modules/talent/access.ts#codeOf',
    'apps/api/src/modules/talent/access.ts#fieldVisible',
    'apps/api/src/modules/talent/access.ts#isDictionary',
    'apps/api/src/modules/talent/access.ts#requireCreatable',
    'apps/api/src/modules/talent/access.ts#requireVisible',
    'apps/api/src/modules/talent/access.ts#talentContext',
    'apps/api/src/modules/talent/access.ts#talentWriteContext',
    'apps/api/src/modules/talent/access.ts#viewableFields',
    '#schemaFields',
    'apps/api/src/modules/talent/http.ts#uuidQuery',
    'apps/api/src/modules/talent/owner-units.ts#authorizedUnits',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/talent/http.ts#pageQuery': ['#queryInteger'],
  'apps/api/src/modules/talent/http.ts#typeQuery': ['packages/domain/src/talent/catalog.ts#TALENT_DIMENSION_TYPES'],
  'apps/api/src/modules/talent/input.ts#behavior': ['#note', '#order'],
  'apps/api/src/modules/talent/input.ts#categoryCreate': ['#name', '#order', '#ownerOrgId'],
  'apps/api/src/modules/talent/input.ts#categoryPatch': ['#categoryCreate'],
  'apps/api/src/modules/talent/input.ts#criterionCreate': ['#criterionFields', '#ownerOrgId'],
  'apps/api/src/modules/talent/input.ts#criterionDimension': ['#dimensionCategory', '#oneDecimal', '#order', '#uuid'],
  'apps/api/src/modules/talent/input.ts#criterionFields': [
    '#MAX_CRITERION_DIMENSIONS',
    '#criterionDimension',
    '#name',
    '#note',
    '#uuid',
  ],
  'apps/api/src/modules/talent/input.ts#criterionPatch': ['#criterionFields', '#ownerOrgId'],
  'apps/api/src/modules/talent/input.ts#descriptionTypeCreate': ['#order'],
  'apps/api/src/modules/talent/input.ts#descriptionTypePatch': ['#descriptionTypeCreate'],
  'apps/api/src/modules/talent/input.ts#dimensionCategoryBatch': [
    '#MAX_CRITERION_DIMENSIONS',
    '#dimensionCategory',
    '#uuid',
  ],
  'apps/api/src/modules/talent/input.ts#dimensionCategoryCreate': ['#ownerOrgId', '#uuid'],
  'apps/api/src/modules/talent/input.ts#dimensionCategoryPatch': ['#dimensionCategoryCreate'],
  'apps/api/src/modules/talent/input.ts#dimensionCreate': ['#code', '#dimensionFields', '#ownerOrgId', '#uuid'],
  'apps/api/src/modules/talent/input.ts#dimensionFields': [
    '#MAX_DETAILS',
    '#behavior',
    '#grade',
    '#name',
    '#note',
    '#order',
    '#question',
    '#suggestion',
    '#uuid',
  ],
  'apps/api/src/modules/talent/input.ts#dimensionPatch': ['#dimensionFields'],
  'apps/api/src/modules/talent/input.ts#grade': ['#note', '#shortText'],
  'apps/api/src/modules/talent/input.ts#libraryCreate': [
    '#name',
    '#order',
    '#ownerOrgId',
    'packages/domain/src/talent/catalog.ts#TALENT_DIMENSION_TYPES',
  ],
  'apps/api/src/modules/talent/input.ts#libraryPatch': ['#libraryCreate'],
  'apps/api/src/modules/talent/input.ts#ownerOrgId': ['#uuid'],
  'apps/api/src/modules/talent/input.ts#question': ['#note', '#order'],
  'apps/api/src/modules/talent/input.ts#suggestion': ['#order', '#uuid'],
  'apps/api/src/modules/talent/library-service.ts#createDescriptionType': [
    'apps/api/src/modules/talent/access.ts#requireCreatable',
    '#uniqueName',
    'apps/api/src/modules/talent/read-model.ts#loadDescriptionType',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#created',
  ],
  'apps/api/src/modules/talent/library-service.ts#createDimensionCategory': [
    'apps/api/src/modules/talent/owner-units.ts#ownerUnit',
    'apps/api/src/modules/talent/read-model.ts#loadDimensionCategory',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#created',
    'apps/api/src/modules/talent/write-support.ts#owned',
    'apps/api/src/modules/talent/write-support.ts#referenced',
    'apps/api/src/modules/talent/write-support.ts#requireLibraryCreatable',
  ],
  'apps/api/src/modules/talent/library-service.ts#createLibrary': [
    'apps/api/src/modules/talent/owner-units.ts#ownerUnit',
    'apps/api/src/modules/talent/read-model.ts#loadLibrary',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#created',
    'apps/api/src/modules/talent/write-support.ts#owned',
  ],
  'apps/api/src/modules/talent/library-service.ts#deleteDescriptionType': [
    'apps/api/src/modules/talent/read-model.ts#loadDescriptionType',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
    'apps/api/src/modules/talent/write-support.ts#rejectInUse',
  ],
  'apps/api/src/modules/talent/library-service.ts#deleteDimensionCategory': [
    'apps/api/src/modules/talent/read-model.ts#loadDimensionCategory',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
    'apps/api/src/modules/talent/write-support.ts#rejectInUse',
  ],
  'apps/api/src/modules/talent/library-service.ts#deleteLibrary': [
    'apps/api/src/modules/talent/read-model.ts#loadLibrary',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
    'apps/api/src/modules/talent/write-support.ts#rejectInUse',
  ],
  'apps/api/src/modules/talent/library-service.ts#updateDescriptionType': [
    '#uniqueName',
    'apps/api/src/modules/talent/read-model.ts#loadDescriptionType',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#bumped',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/library-service.ts#updateDimensionCategory': [
    'apps/api/src/modules/talent/read-model.ts#loadDimensionCategory',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#bumped',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/library-service.ts#updateLibrary': [
    'apps/api/src/modules/talent/read-model.ts#loadLibrary',
    'apps/api/src/modules/talent/write-support.ts#audit',
    'apps/api/src/modules/talent/write-support.ts#bumped',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/model-image-format.ts#decodeImage': ['#MODEL_IMAGE_MAX_BYTES'],
  'apps/api/src/modules/talent/model-image-format.ts#staticGif': [
    '#gifPixels',
    '#skipGifBlocks',
    'apps/api/src/modules/talent/model-image-gif.ts#completeGifPixels',
  ],
  'apps/api/src/modules/talent/model-image-format.ts#staticPng': ['#crc32'],
  'apps/api/src/modules/talent/model-image-format.ts#validateImageContent': [
    '#bmp',
    '#jpeg',
    '#staticGif',
    '#staticPng',
    '#unsupported',
  ],
  'apps/api/src/modules/talent/model-image-format.ts#validateImageMetadata': [
    '#MIME',
    '#MODEL_IMAGE_MAX_BYTES',
    '#unsupported',
  ],
  'apps/api/src/modules/talent/model-image-routes.ts#BASE': ['apps/api/src/modules/talent/http.ts#TALENT_BASE'],
  'apps/api/src/modules/talent/model-image-routes.ts#detailScope': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/talent/access.ts#codeOf',
  ],
  'apps/api/src/modules/talent/model-image-routes.ts#imageWriteContext': [
    'apps/api/src/modules/talent/access.ts#talentContext',
    'apps/api/src/modules/talent/access.ts#talentWriteContext',
    'apps/api/src/modules/talent/http.ts#revision',
  ],
  'apps/api/src/modules/talent/model-image-routes.ts#present': [
    'apps/api/src/modules/talent/access.ts#talentWriteContext',
    '#detailScope',
    'apps/api/src/modules/talent/model-image-service.ts#currentImage',
    'apps/api/src/modules/talent/model-image-service.ts#imageOwner',
  ],
  'apps/api/src/modules/talent/model-image-routes.ts#registerModelImageRoutes': [
    'apps/api/src/modules/talent/access.ts#talentContext',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#uuidParam',
    '#BASE',
    '#detailScope',
    '#imageWriteContext',
    '#metadata',
    '#present',
    '#sameOrigin',
    '#upload',
    '#write',
    'apps/api/src/modules/talent/model-image-service.ts#deleteModelImage',
    'apps/api/src/modules/talent/model-image-service.ts#imageContent',
    'apps/api/src/modules/talent/model-image-service.ts#imageOwner',
    'apps/api/src/modules/talent/model-image-service.ts#registerModelImage',
    'apps/api/src/modules/talent/model-image-service.ts#registeredImage',
    'apps/api/src/modules/talent/model-image-service.ts#uploadModelImage',
  ],
  'apps/api/src/modules/talent/model-image-routes.ts#write': [
    'apps/api/src/modules/talent/access.ts#talentScope',
    '#detailScope',
    'apps/api/src/modules/talent/model-image-service.ts#imageOwner',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#bump': [
    '#C',
    'apps/api/src/modules/talent/write-support.ts#bumped',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#cleanupCriterionImages': [
    '#A',
    '#imageAudit',
    '#metadataColumns',
    '#whereImage',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#currentImage': ['#A', '#metadataColumns', '#whereImage'],
  'apps/api/src/modules/talent/model-image-service.ts#deleteModelImage': [
    '#A',
    '#bump',
    '#currentImage',
    '#imageAudit',
    '#imageOwner',
    '#whereImage',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#imageAudit': [
    'apps/api/src/audit/record.ts#recordAudit',
    '#MODEL_IMAGE_AUDIT_TYPE',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#imageContent': ['#A', '#whereImage'],
  'apps/api/src/modules/talent/model-image-service.ts#imageOwner': [
    'apps/api/src/modules/talent/access.ts#requireVisible',
    'apps/api/src/modules/talent/write-support.ts#rowsOf',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#metadataColumns': ['#A'],
  'apps/api/src/modules/talent/model-image-service.ts#registerModelImage': [
    'apps/api/src/modules/talent/model-image-format.ts#validateImageMetadata',
    '#A',
    '#bump',
    '#imageAudit',
    '#imageOwner',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#registeredImage': ['#A', '#metadataColumns', '#whereImage'],
  'apps/api/src/modules/talent/model-image-service.ts#uploadModelImage': [
    'apps/api/src/modules/talent/model-image-format.ts#decodeImage',
    'apps/api/src/modules/talent/model-image-format.ts#validateImageContent',
    '#A',
    '#bump',
    '#currentImage',
    '#imageAudit',
    '#imageOwner',
    '#registeredImage',
    '#whereImage',
    'apps/api/src/modules/talent/write-support.ts#lockOwned',
  ],
  'apps/api/src/modules/talent/model-image-service.ts#whereImage': ['#A'],
  'apps/api/src/modules/talent/owner-units.ts#authorizedUnits': [
    'apps/api/src/modules/permission/owner-units.ts#authorizedUnits',
    'packages/domain/src/talent/catalog.ts#TALENT_APP',
  ],
  'apps/api/src/modules/talent/owner-units.ts#ownerUnit': [
    'apps/api/src/modules/permission/owner-units.ts#UNIT_NOT_FOUND',
    'apps/api/src/modules/permission/owner-units.ts#chooseUnit',
    'apps/api/src/modules/talent/access.ts#requireCreatable',
    'packages/domain/src/talent/catalog.ts#TALENT_APP',
  ],
  'apps/api/src/modules/talent/owner-units.ts#relationUnit': [
    'apps/api/src/modules/permission/owner-units.ts#chooseUnit',
    'packages/domain/src/talent/catalog.ts#TALENT_APP',
  ],
  'apps/api/src/modules/talent/read-model.ts#categoryColumns': ['#N', '#owned'],
  'apps/api/src/modules/talent/read-model.ts#criterionColumns': ['#C', '#owned'],
  'apps/api/src/modules/talent/read-model.ts#descriptionTypeColumns': ['#T'],
  'apps/api/src/modules/talent/read-model.ts#dimensionCategoryColumns': ['#K', '#owned'],
  'apps/api/src/modules/talent/read-model.ts#dimensionColumns': ['#D', '#K', '#L'],
  'apps/api/src/modules/talent/read-model.ts#dimensionsFrom': ['#D', '#K', '#L', '#dimensionColumns'],
  'apps/api/src/modules/talent/read-model.ts#libraryColumns': ['#L', '#owned'],
  'apps/api/src/modules/talent/read-model.ts#listCategories': ['#N', '#categoryColumns'],
  'apps/api/src/modules/talent/read-model.ts#listCriteria': ['#C', '#criterionColumns', '#nameLike', '#withReferences'],
  'apps/api/src/modules/talent/read-model.ts#listDescriptionTypes': ['#T', '#descriptionTypeColumns'],
  'apps/api/src/modules/talent/read-model.ts#listDimensionCategories': ['#K', '#dimensionCategoryColumns'],
  'apps/api/src/modules/talent/read-model.ts#listDimensionRecords': [
    '#D',
    '#L',
    '#dimensionsFrom',
    '#nameLike',
    '#withDetails',
  ],
  'apps/api/src/modules/talent/read-model.ts#listDimensions': ['#dimensionView', '#listDimensionRecords'],
  'apps/api/src/modules/talent/read-model.ts#listLibraries': ['#L', '#libraryColumns'],
  'apps/api/src/modules/talent/read-model.ts#loadCategory': ['#N', '#categoryColumns'],
  'apps/api/src/modules/talent/read-model.ts#loadCriterion': ['#C', '#criterionColumns', '#withReferences'],
  'apps/api/src/modules/talent/read-model.ts#loadDescriptionType': ['#T', '#descriptionTypeColumns'],
  'apps/api/src/modules/talent/read-model.ts#loadDimension': ['#dimensionView', '#loadDimensionRecords'],
  'apps/api/src/modules/talent/read-model.ts#loadDimensionCategory': ['#K', '#dimensionCategoryColumns'],
  'apps/api/src/modules/talent/read-model.ts#loadDimensionRecords': ['#D', '#dimensionsFrom', '#withDetails'],
  'apps/api/src/modules/talent/read-model.ts#loadLibrary': ['#L', '#libraryColumns'],
  'apps/api/src/modules/talent/read-model.ts#withDetails': ['#T'],
  'apps/api/src/modules/talent/read-model.ts#withReferences': ['#loadDimensionRecords'],
  'apps/api/src/modules/talent/references.ts#criterionReferrer': ['#guards'],
  'apps/api/src/modules/talent/routes.ts#CATEGORIES': [
    'apps/api/src/modules/talent/criterion-service.ts#createCategory',
    'apps/api/src/modules/talent/criterion-service.ts#deleteCategory',
    'apps/api/src/modules/talent/criterion-service.ts#updateCategory',
    'apps/api/src/modules/talent/input.ts#categoryCreate',
    'apps/api/src/modules/talent/input.ts#categoryPatch',
    'apps/api/src/modules/talent/read-model.ts#listCategories',
    'apps/api/src/modules/talent/read-model.ts#loadCategory',
    '#ownedBy',
  ],
  'apps/api/src/modules/talent/routes.ts#CRITERIA': [
    'apps/api/src/modules/talent/criterion-service.ts#createCriterion',
    'apps/api/src/modules/talent/criterion-service.ts#deleteCriterion',
    'apps/api/src/modules/talent/criterion-service.ts#updateCriterion',
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#nameQuery',
    'apps/api/src/modules/talent/http.ts#uuidQuery',
    'apps/api/src/modules/talent/input.ts#criterionCreate',
    'apps/api/src/modules/talent/input.ts#criterionPatch',
    'apps/api/src/modules/talent/read-model.ts#listCriteria',
    'apps/api/src/modules/talent/read-model.ts#loadCriterion',
    '#ownedBy',
  ],
  'apps/api/src/modules/talent/routes.ts#DESCRIPTION_TYPES': [
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/input.ts#descriptionTypeCreate',
    'apps/api/src/modules/talent/input.ts#descriptionTypePatch',
    'apps/api/src/modules/talent/library-service.ts#createDescriptionType',
    'apps/api/src/modules/talent/library-service.ts#deleteDescriptionType',
    'apps/api/src/modules/talent/library-service.ts#updateDescriptionType',
    'apps/api/src/modules/talent/read-model.ts#listDescriptionTypes',
    'apps/api/src/modules/talent/read-model.ts#loadDescriptionType',
  ],
  'apps/api/src/modules/talent/routes.ts#DIMENSIONS': [
    'apps/api/src/modules/talent/dimension-service.ts#createDimension',
    'apps/api/src/modules/talent/dimension-service.ts#deleteDimension',
    'apps/api/src/modules/talent/dimension-service.ts#updateDimension',
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#nameQuery',
    'apps/api/src/modules/talent/http.ts#typeQuery',
    'apps/api/src/modules/talent/http.ts#uuidQuery',
    'apps/api/src/modules/talent/input.ts#dimensionCreate',
    'apps/api/src/modules/talent/input.ts#dimensionPatch',
    'apps/api/src/modules/talent/read-model.ts#listDimensions',
    'apps/api/src/modules/talent/read-model.ts#loadDimension',
    '#ownedBy',
  ],
  'apps/api/src/modules/talent/routes.ts#DIMENSION_CATEGORIES': [
    'apps/api/src/modules/talent/http.ts#uuidQuery',
    'apps/api/src/modules/talent/input.ts#dimensionCategoryCreate',
    'apps/api/src/modules/talent/input.ts#dimensionCategoryPatch',
    'apps/api/src/modules/talent/library-service.ts#createDimensionCategory',
    'apps/api/src/modules/talent/library-service.ts#deleteDimensionCategory',
    'apps/api/src/modules/talent/library-service.ts#updateDimensionCategory',
    'apps/api/src/modules/talent/read-model.ts#listDimensionCategories',
    'apps/api/src/modules/talent/read-model.ts#loadDimensionCategory',
    '#ownedBy',
  ],
  'apps/api/src/modules/talent/routes.ts#LIBRARIES': [
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#typeQuery',
    'apps/api/src/modules/talent/input.ts#libraryCreate',
    'apps/api/src/modules/talent/input.ts#libraryPatch',
    'apps/api/src/modules/talent/library-service.ts#createLibrary',
    'apps/api/src/modules/talent/library-service.ts#deleteLibrary',
    'apps/api/src/modules/talent/library-service.ts#updateLibrary',
    'apps/api/src/modules/talent/read-model.ts#listLibraries',
    'apps/api/src/modules/talent/read-model.ts#loadLibrary',
    '#ownedBy',
  ],
  'apps/api/src/modules/talent/routes.ts#presenter': [
    'apps/api/src/modules/talent/access.ts#nestedDimensionReader',
    'apps/api/src/modules/talent/access.ts#trimTalentList',
  ],
  'apps/api/src/modules/talent/routes.ts#referenceAccess': [
    'apps/api/src/modules/talent/access.ts#codeOf',
    'apps/api/src/modules/talent/access.ts#talentScope',
    'apps/api/src/modules/talent/access.ts#viewableFields',
  ],
  'apps/api/src/modules/talent/routes.ts#registerDimensionCategoryBatch': [
    'apps/api/src/modules/talent/access.ts#checkWriteFields',
    'apps/api/src/modules/talent/access.ts#talentWriteContext',
    'apps/api/src/modules/talent/criterion-service.ts#setDimensionCategory',
    'apps/api/src/modules/talent/http.ts#TALENT_BASE',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
    'apps/api/src/modules/talent/input.ts#dimensionCategoryBatch',
    '#CRITERIA',
    '#runTalentWrite',
  ],
  'apps/api/src/modules/talent/routes.ts#registerObject': [
    'apps/api/src/modules/talent/access.ts#TALENT_LABELS',
    'apps/api/src/modules/talent/access.ts#checkWriteFields',
    'apps/api/src/modules/talent/access.ts#listEnvelope',
    'apps/api/src/modules/talent/access.ts#requireVisible',
    'apps/api/src/modules/talent/access.ts#scopeColumns',
    'apps/api/src/modules/talent/access.ts#talentContext',
    'apps/api/src/modules/talent/access.ts#talentScope',
    'apps/api/src/modules/talent/access.ts#talentWriteContext',
    'apps/api/src/modules/talent/access.ts#visibleSql',
    'apps/api/src/modules/talent/form-access.ts#talentFormHandler',
    'apps/api/src/modules/talent/http.ts#TALENT_BASE',
    'apps/api/src/modules/talent/http.ts#pageQuery',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
    '#presenter',
    '#runTalentWrite',
  ],
  'apps/api/src/modules/talent/routes.ts#registerTalentRoutes': [
    'apps/api/src/modules/talent/candidates.ts#registerCandidates',
    'apps/api/src/modules/talent/http.ts#TALENT_BASE',
    'apps/api/src/modules/talent/model-image-routes.ts#registerModelImageRoutes',
    '#CATEGORIES',
    '#CRITERIA',
    '#DESCRIPTION_TYPES',
    '#DIMENSIONS',
    '#DIMENSION_CATEGORIES',
    '#LIBRARIES',
    '#registerDimensionCategoryBatch',
    '#registerObject',
  ],
  'apps/api/src/modules/talent/routes.ts#runTalentWrite': [
    'apps/api/src/modules/talent/access.ts#requireVisible',
    'apps/api/src/modules/talent/access.ts#talentScope',
    '#presenter',
    '#referenceAccess',
  ],
  'apps/api/src/modules/talent/write-support.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/modules/talent/access.ts#TALENT_AUDIT_ACTIONS',
    'apps/api/src/modules/talent/access.ts#codeOf',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/talent/write-support.ts#lockOwned': [
    'apps/api/src/modules/talent/access.ts#TALENT_LABELS',
    'apps/api/src/modules/talent/access.ts#requireVisible',
    '#lockRow',
    '#ownerOf',
  ],
  'apps/api/src/modules/talent/write-support.ts#lockRow': [
    'apps/api/src/modules/talent/access.ts#isDictionary',
    '#TALENT_TABLES',
    '#rowsOf',
  ],
  'apps/api/src/modules/talent/write-support.ts#referenced': [
    'apps/api/src/modules/talent/access.ts#TALENT_LABELS',
    'apps/api/src/modules/talent/access.ts#requireVisible',
    '#lockRow',
    '#ownerOf',
  ],
  'apps/api/src/modules/talent/write-support.ts#rejectInUse': ['apps/api/src/modules/talent/read-model.ts#usageCount'],
  'apps/api/src/modules/talent/write-support.ts#requireLibraryCreatable': [
    'apps/api/src/modules/talent/access.ts#TALENT_LABELS',
    'apps/api/src/modules/talent/access.ts#requireCreatable',
  ],
};
