/**
 * 直接依赖图：区域 api-modules-succession（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/succession/access.ts#codeOf': ['packages/domain/src/succession/catalog.ts#SUCCESSION_OBJECTS'],
  'apps/api/src/modules/succession/access.ts#requireFilterVisible': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#codeOf',
  ],
  'apps/api/src/modules/succession/access.ts#successionContext': [
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    '#codeOf',
  ],
  'apps/api/src/modules/succession/access.ts#successionScope': [
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    '#codeOf',
  ],
  'apps/api/src/modules/succession/audit-scope.ts#SUCCESSION_AUDIT': ['#recordSelfRestrict'],
  'apps/api/src/modules/succession/audit-scope.ts#recordSelfRestrict': [
    'apps/api/src/modules/succession/read-sql.ts#selfRecordHiddenSql',
  ],
  'apps/api/src/modules/succession/candidates.ts#searchCandidates': [
    '#escapeLike',
    'apps/api/src/modules/succession/read-sql.ts#SUCCESSOR_INACTIVE_STATUSES',
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
  ],
  'apps/api/src/modules/succession/input.ts#date': ['apps/api/src/modules/org/read-model.ts#validIsoDate'],
  'apps/api/src/modules/succession/input.ts#recordCreate': ['#backupType', '#date', '#reason', '#uuid'],
  'apps/api/src/modules/succession/input.ts#recordEnd': ['#MAX_END_ITEMS', '#date', '#reason', '#uuid'],
  'apps/api/src/modules/succession/input.ts#recordPatch': ['#backupType', '#date', '#reason', '#uuid'],
  'apps/api/src/modules/succession/input.ts#rejectImmutable': ['#IMMUTABLE'],
  'apps/api/src/modules/succession/ports.ts#installSuccessionPorts': [
    '#SUCCESSION_PORTS',
    'apps/api/src/modules/talent-review/health-port.ts#registerOrgHealthComputePort',
  ],
  'apps/api/src/modules/succession/projection.ts#OBJECT_OF': [
    'packages/domain/src/succession/catalog.ts#SUCCESSION_OBJECTS',
  ],
  'apps/api/src/modules/succession/projection.ts#buildRecordViews': [
    'apps/api/src/modules/succession/read-sql.ts#loadIncumbentIds',
    'apps/api/src/modules/succession/read-sql.ts#loadPeople',
    'apps/api/src/modules/succession/read-sql.ts#loadPersonInChargeIds',
    'apps/api/src/modules/succession/record-read.ts#isOpenEnded',
  ],
  'apps/api/src/modules/succession/projection.ts#projectSuccession': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#GOVERNING_FIELD',
    '#OBJECT_OF',
  ],
  'apps/api/src/modules/succession/read-sql.ts#loadIncumbentIds': [
    '#INCUMBENT_EXCLUDED_STATUSES',
    '#rowsOf',
    '#uuidArray',
  ],
  'apps/api/src/modules/succession/read-sql.ts#loadPeople': ['#personLabel', '#rowsOf', '#uuidArray'],
  'apps/api/src/modules/succession/read-sql.ts#loadPersonInChargeIds': ['#rowsOf', '#uuidArray'],
  'apps/api/src/modules/succession/read-sql.ts#selfRecordHiddenSql': ['#selfSuccessorsHiddenSql', '#selfTargetSql'],
  'apps/api/src/modules/succession/read-sql.ts#selfSuccessorsHiddenSql': ['#SELF_VISIBLE_KEY'],
  'apps/api/src/modules/succession/record-read.ts#conditions': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/succession/read-sql.ts#selfRecordHiddenSql',
    '#statusPredicate',
  ],
  'apps/api/src/modules/succession/record-read.ts#listRecordRows': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#conditions',
    '#from',
    '#selectColumns',
    '#toRow',
  ],
  'apps/api/src/modules/succession/record-read.ts#loadRecordRow': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#conditions',
    '#from',
    '#selectColumns',
    '#toRow',
  ],
  'apps/api/src/modules/succession/record-read.ts#toRow': ['#toIso'],
  'apps/api/src/modules/succession/record-write.ts#RECORD': ['apps/api/src/modules/succession/access.ts#codeOf'],
  'apps/api/src/modules/succession/record-write.ts#anchorOrg': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#notFound',
  ],
  'apps/api/src/modules/succession/record-write.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    '#RECORD',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/succession/record-write.ts#checkDates': ['#invalid'],
  'apps/api/src/modules/succession/record-write.ts#checkOverlap': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#conflict',
  ],
  'apps/api/src/modules/succession/record-write.ts#createRecord': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#COLUMNS',
    '#audit',
    '#checkDates',
    '#checkOverlap',
    '#guardExclusion',
    '#lockActiveSuccessor',
    '#lockTargets',
    '#rejectSelfTarget',
    '#requireTarget',
    '#snapshot',
    'apps/api/src/modules/succession/sync-barrier.ts#assertNoSyncBarrier',
    'apps/api/src/modules/talent-review/readiness-port.ts#selectReadiness',
  ],
  'apps/api/src/modules/succession/record-write.ts#deleteRecord': [
    '#anchorOrg',
    '#audit',
    '#checkRevision',
    '#lockRows',
    '#lockTargets',
    '#notFound',
    '#peekRows',
    '#requireWritable',
    '#snapshot',
    '#targetOf',
    'apps/api/src/modules/succession/sync-barrier.ts#assertNoSyncBarrier',
  ],
  'apps/api/src/modules/succession/record-write.ts#endRecords': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#COLUMNS',
    '#anchorOrg',
    '#audit',
    '#checkRevision',
    '#conflict',
    '#invalid',
    '#lockRows',
    '#lockTargets',
    '#notFound',
    '#peekRows',
    '#requireWritable',
    '#snapshot',
    '#targetOf',
    'apps/api/src/modules/succession/sync-barrier.ts#assertNoSyncBarrier',
  ],
  'apps/api/src/modules/succession/record-write.ts#guardExclusion': ['#conflict'],
  'apps/api/src/modules/succession/record-write.ts#lockActiveSuccessor': [
    'apps/api/src/modules/succession/read-sql.ts#SUCCESSOR_INACTIVE_STATUSES',
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#invalid',
  ],
  'apps/api/src/modules/succession/record-write.ts#lockRows': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#COLUMNS',
    '#notFound',
    '#toLocked',
  ],
  'apps/api/src/modules/succession/record-write.ts#lockTargets': ['#keyOf'],
  'apps/api/src/modules/succession/record-write.ts#peekRows': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#COLUMNS',
    '#toLocked',
  ],
  'apps/api/src/modules/succession/record-write.ts#rejectSelfTarget': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    'apps/api/src/modules/succession/read-sql.ts#selfTargetSql',
    '#notFound',
  ],
  'apps/api/src/modules/succession/record-write.ts#requireTarget': [
    'apps/api/src/modules/permission/module-access.ts#scopeAllows',
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#invalid',
  ],
  'apps/api/src/modules/succession/record-write.ts#requireWritable': [
    'apps/api/src/modules/succession/record-read.ts#listRecordRows',
    '#notFound',
    '#rejectSelfTarget',
    '#targetOf',
  ],
  'apps/api/src/modules/succession/record-write.ts#updateRecord': [
    'apps/api/src/modules/succession/read-sql.ts#rowsOf',
    '#COLUMNS',
    '#anchorOrg',
    '#audit',
    '#checkDates',
    '#checkOverlap',
    '#checkRevision',
    '#guardExclusion',
    '#lockActiveSuccessor',
    '#lockRows',
    '#lockTargets',
    '#notFound',
    '#peekRows',
    '#requireTarget',
    '#requireWritable',
    '#snapshot',
    '#targetOf',
    'apps/api/src/modules/succession/sync-barrier.ts#assertNoSyncBarrier',
    'apps/api/src/modules/talent-review/readiness-port.ts#selectReadiness',
  ],
  'apps/api/src/modules/succession/routes.ts#RECORDS': ['apps/api/src/modules/succession/access.ts#SUCCESSION_BASE'],
  'apps/api/src/modules/succession/routes.ts#candidateLimit': [
    'apps/api/src/modules/succession/candidates.ts#CANDIDATE_DEFAULT',
    'apps/api/src/modules/succession/candidates.ts#CANDIDATE_MAX',
  ],
  'apps/api/src/modules/succession/routes.ts#recordFilter': [
    'apps/api/src/modules/succession/access.ts#requireFilterVisible',
    'apps/api/src/modules/succession/record-read.ts#RECORD_STATUS_FILTERS',
    '#optional',
    'apps/api/src/modules/talent/http.ts#uuidQuery',
  ],
  'apps/api/src/modules/succession/routes.ts#recordVisibility': [
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
    'apps/api/src/modules/succession/access.ts#successionScope',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/succession/routes.ts#registerRecordWrites': [
    'apps/api/src/modules/succession/access.ts#SUCCESSION_BASE',
    'apps/api/src/modules/succession/candidates.ts#searchCandidates',
    'apps/api/src/modules/succession/input.ts#recordCreate',
    'apps/api/src/modules/succession/input.ts#recordEnd',
    'apps/api/src/modules/succession/input.ts#recordPatch',
    'apps/api/src/modules/succession/input.ts#rejectImmutable',
    'apps/api/src/modules/succession/record-write.ts#createRecord',
    'apps/api/src/modules/succession/record-write.ts#deleteRecord',
    'apps/api/src/modules/succession/record-write.ts#endRecords',
    'apps/api/src/modules/succession/record-write.ts#updateRecord',
    '#RECORDS',
    '#candidateLimit',
    '#writeRecord',
    'apps/api/src/modules/succession/write-support.ts#checkCandidateAccess',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/succession/routes.ts#registerSuccessionRoutes': [
    'apps/api/src/modules/succession/access.ts#SUCCESSION_BASE',
    'apps/api/src/modules/succession/access.ts#successionContext',
    'apps/api/src/modules/succession/ports.ts#installSuccessionPorts',
    'apps/api/src/modules/succession/projection.ts#buildRecordViews',
    'apps/api/src/modules/succession/projection.ts#projectSuccession',
    'apps/api/src/modules/succession/record-read.ts#listRecordRows',
    'apps/api/src/modules/succession/record-read.ts#loadRecordRow',
    '#RECORDS',
    '#recordFilter',
    '#recordVisibility',
    '#registerRecordWrites',
    'apps/api/src/modules/talent-review/readiness-port.ts#readinessPort',
    'apps/api/src/modules/talent/http.ts#pageQuery',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/succession/routes.ts#respond': [
    'apps/api/src/modules/succession/write-support.ts#authorizeSuccessionResult',
  ],
  'apps/api/src/modules/succession/routes.ts#writeRecord': [
    '#respond',
    'apps/api/src/modules/succession/write-support.ts#checkWriteAccess',
    'apps/api/src/modules/succession/write-support.ts#runSuccessionCommand',
  ],
  'apps/api/src/modules/succession/sync-barrier.ts#assertNoSyncBarrier': ['#probe'],
  'apps/api/src/modules/succession/write-support.ts#authorizeSuccessionResult': [
    'apps/api/src/modules/succession/projection.ts#projectSuccession',
    '#visibleViews',
  ],
  'apps/api/src/modules/succession/write-support.ts#checkCandidateAccess': ['#checkWriteAccess'],
  'apps/api/src/modules/succession/write-support.ts#checkWriteAccess': [
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'apps/api/src/modules/succession/access.ts#codeOf',
    'apps/api/src/modules/succession/access.ts#successionContext',
  ],
  'apps/api/src/modules/succession/write-support.ts#recheck': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/succession/access.ts#codeOf',
    '#checkWriteAccess',
    '#todayOf',
  ],
  'apps/api/src/modules/succession/write-support.ts#runSuccessionCommand': ['#recheck', '#visibleViews'],
  'apps/api/src/modules/succession/write-support.ts#todayOf': ['packages/domain/src/tenant-time.ts#tenantLocalDate'],
  'apps/api/src/modules/succession/write-support.ts#visibleViews': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/succession/access.ts#codeOf',
    'apps/api/src/modules/succession/projection.ts#buildRecordViews',
    'apps/api/src/modules/succession/record-read.ts#listRecordRows',
    '#todayOf',
  ],
};
