/**
 * 直接依赖图：区域 api-modules-job（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/job/context.ts#pageQuery': ['#queryInteger'],
  'apps/api/src/modules/job/context.ts#queryDate': [
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/context.ts#readContext': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/job/context.ts#runWrite': [
    'apps/api/src/modules/permission/establishment-replay.ts#authorizeEstablishmentReplay',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/job/employment-port.ts#EMPLOYMENT_OBJECT': [
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/job/employment-port.ts#employmentJobPersonnel': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/personnel-reader.ts#readPositionAssignments',
    'apps/api/src/modules/employment/write-service.ts#createEmploymentBusiness',
    '#EMPLOYMENT_OBJECT',
    '#INCUMBENT_LIMIT',
    '#withinEmploymentScope',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
  ],
  'apps/api/src/modules/job/employment-port.ts#trimManagerSync': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    '#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/employment-port.ts#withinEmploymentScope': [
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    'apps/api/src/modules/permission/module-access.ts#scopeAllowsInTransaction',
  ],
  'apps/api/src/modules/job/fields.ts#associations': ['#reference'],
  'apps/api/src/modules/job/fields.ts#businessDate': ['apps/api/src/modules/org/read-model.ts#validIsoDate'],
  'apps/api/src/modules/job/fields.ts#common': ['#businessDate', '#order', '#reference'],
  'apps/api/src/modules/job/fields.ts#jobCreationSchema': ['#common', '#specific'],
  'apps/api/src/modules/job/fields.ts#jobPatchSchema': ['#businessDate', '#jobCreationSchema'],
  'apps/api/src/modules/job/fields.ts#normalizeFields': [
    '#jobCreationSchema',
    '#rejectUnsupported',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/fields.ts#order': ['#integer'],
  'apps/api/src/modules/job/fields.ts#parent': ['#order'],
  'apps/api/src/modules/job/fields.ts#ranges': ['#reference'],
  'apps/api/src/modules/job/fields.ts#specific': [
    '#associations',
    '#characteristics',
    '#number',
    '#order',
    '#parent',
    '#ranges',
    '#reference',
    '#text',
  ],
  'apps/api/src/modules/job/import-service.ts#authorizeJobImportRows': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/store.ts#rowsOf',
    'apps/api/src/modules/job/store.ts#snakeCase',
  ],
  'apps/api/src/modules/job/import-service.ts#importJobObjects': [
    'apps/api/src/audit/record.ts#recordImportLog',
    'apps/api/src/modules/job/fields.ts#jobCreationSchema',
    '#assertRows',
    '#assertUpdateRevisions',
    '#conflictReason',
    '#importRow',
    '#importSnapshot',
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/settings.ts#lockJobTenant',
    'apps/api/src/modules/job/store.ts#auditJob',
    'apps/api/src/modules/job/store.ts#insertRow',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/job/import-service.ts#importRow': [
    '#updateMapped',
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/store.ts#auditJob',
    'apps/api/src/modules/job/store.ts#insertRow',
    'apps/api/src/modules/job/write-service.ts#createJobObject',
  ],
  'apps/api/src/modules/job/import-service.ts#importSnapshot': [
    'apps/api/src/modules/job/metadata.ts#JOB_KINDS',
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/store.ts#rowsOf',
    'apps/api/src/modules/job/store.ts#snakeCase',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/import-service.ts#updateMapped': [
    'apps/api/src/modules/job/read-model.ts#latestJobObject',
    'apps/api/src/modules/job/write-service.ts#updateJobObject',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/metadata.ts#assignment': ['#ranges'],
  'apps/api/src/modules/job/metadata.ts#catalog': ['#SEQUENCE_ANCESTORS', '#assignment', '#tables'],
  'apps/api/src/modules/job/metadata.ts#jobTables': ['#catalog'],
  'apps/api/src/modules/job/metadata.ts#tables': ['#common'],
  'apps/api/src/modules/job/personnel.ts#applyPositionPersonnelRules': [
    '#assertIncumbents',
    '#dayAfter',
    '#synchronizeManagers',
  ],
  'apps/api/src/modules/job/personnel.ts#synchronizeManagers': [
    'apps/api/src/modules/employment/field-derivations.ts#soleOtherPositionManager',
    '#POSITION_MANAGER_SYNC_RECORD',
    '#assertIncumbents',
    'apps/api/src/modules/job/store.ts#auditJob',
  ],
  'apps/api/src/modules/job/read-model.ts#assertLevelInPost': ['#numericRange', '#requiredObject'],
  'apps/api/src/modules/job/read-model.ts#countEnabledPositions': ['#resultRows'],
  'apps/api/src/modules/job/read-model.ts#effectiveVersions': ['apps/api/src/modules/job/metadata.ts#jobTables'],
  'apps/api/src/modules/job/read-model.ts#jobCandidates': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    '#assertLevelInPost',
    '#checkPage',
    '#effectiveVersions',
    '#numericRange',
    '#queryRecords',
    '#requiredObject',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
  ],
  'apps/api/src/modules/job/read-model.ts#latestJobObject': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    '#queryRecords',
  ],
  'apps/api/src/modules/job/read-model.ts#listJobObjects': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    '#checkPage',
    '#effectiveVersions',
    '#queryRecords',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
  ],
  'apps/api/src/modules/job/read-model.ts#loadJobObject': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    '#queryRecords',
  ],
  'apps/api/src/modules/job/read-model.ts#numericRange': ['#requiredObject'],
  'apps/api/src/modules/job/read-model.ts#queryRecords': ['#record', '#resultRows'],
  'apps/api/src/modules/job/read-model.ts#requiredObject': ['#loadJobObject'],
  'apps/api/src/modules/job/routes.ts#assignment': ['apps/api/src/modules/job/fields.ts#businessDate'],
  'apps/api/src/modules/job/routes.ts#assignmentReferences': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#visibleJob',
  ],
  'apps/api/src/modules/job/routes.ts#importJobRows': [
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/fields.ts#jobCreationSchema',
    'apps/api/src/modules/job/import-service.ts#authorizeJobImportRows',
    'apps/api/src/modules/job/import-service.ts#importJobObjects',
    'apps/api/src/modules/job/metadata.ts#JOB_KINDS',
    'apps/api/src/modules/permission/job-result-scope.ts#authorizeJobResult',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#visibleJob',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/job/routes.ts#objectKind': ['apps/api/src/modules/job/metadata.ts#JOB_KINDS'],
  'apps/api/src/modules/job/routes.ts#registerCandidates': [
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/read-model.ts#jobCandidates',
    '#BASE',
    '#assignment',
    '#assignmentReferences',
    'apps/api/src/modules/job/validation.ts#validateJobAssignment',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/job/routes.ts#route:GET /api/tenant/job/:kind': [
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/read-model.ts#listJobObjects',
    '#BASE',
    '#enabledFilter',
    '#objectKind',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/routes.ts#route:GET /api/tenant/job/:kind/:id': [
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#uuidParam',
    '#BASE',
    '#objectKind',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visibleJob',
  ],
  'apps/api/src/modules/job/routes.ts#route:GET /api/tenant/job/settings': [
    'apps/api/src/modules/job/context.ts#queryDate',
    'apps/api/src/modules/job/context.ts#readContext',
    '#BASE',
    'apps/api/src/modules/job/settings.ts#readJobSettings',
  ],
  'apps/api/src/modules/job/routes.ts#route:PATCH /api/tenant/job/:kind/:id': [
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/job/employment-port.ts#employmentJobPersonnel',
    'apps/api/src/modules/job/employment-port.ts#trimManagerSync',
    'apps/api/src/modules/job/fields.ts#jobPatchSchema',
    '#BASE',
    '#objectKind',
    'apps/api/src/modules/job/write-service.ts#updateJobObject',
    'apps/api/src/modules/permission/job-result-scope.ts#authorizeJobResult',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#visibleJob',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/job/routes.ts#route:POST /api/tenant/job/:kind': [
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/fields.ts#jobCreationSchema',
    '#BASE',
    '#objectKind',
    'apps/api/src/modules/job/write-service.ts#createJobObject',
    'apps/api/src/modules/permission/job-result-scope.ts#authorizeJobResult',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/job/routes.ts#route:POST /api/tenant/job/import': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/metadata.ts#JOB_KINDS',
    '#BASE',
    '#importJobRows',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/job/routes.ts#route:POST /api/tenant/job/validate-assignment': [
    'apps/api/src/modules/job/context.ts#parseBody',
    '#BASE',
    '#assignment',
    '#assignmentReferences',
    'apps/api/src/modules/job/validation.ts#validateJobAssignment',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/job/routes.ts#route:PUT /api/tenant/job/settings': [
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#readContext',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    '#BASE',
    'apps/api/src/modules/job/settings.ts#jobSettingsCommandSchema',
    'apps/api/src/modules/job/settings.ts#writeJobSettings',
  ],
  'apps/api/src/modules/job/sequence-receipts.ts#visibleSequenceReceipts': [
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
    'apps/api/src/modules/job/store.ts#rowsOf',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFieldsInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/job/sequence-routes.ts#route:GET /api/tenant/job/sequence-sync/messages': [
    'apps/api/src/modules/job/sequence-receipts.ts#visibleSequenceReceipts',
    'apps/api/src/modules/job/store.ts#rowsOf',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/job/sequence-routes.ts#route:GET /api/tenant/job/sequence-sync/tasks/:id': [
    'apps/api/src/modules/job/sequence-receipts.ts#visibleSequenceReceipts',
    'apps/api/src/modules/job/store.ts#rowsOf',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/job/sequence-routes.ts#route:POST /api/tenant/job/positions/sync-sequence': [
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/read-model.ts#latestJobObject',
    '#inputSchema',
    'apps/api/src/modules/job/sequence-sync.ts#queueSequenceSync',
    'apps/api/src/modules/job/settings.ts#lockJobTenant',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visibleJob',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/sequence-routes.ts#route:POST /api/tenant/job/posts/sync-sequence': [
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#runWrite',
    'apps/api/src/modules/job/read-model.ts#latestJobObject',
    '#inputSchema',
    'apps/api/src/modules/job/sequence-sync.ts#queueSequenceSync',
    'apps/api/src/modules/job/settings.ts#lockJobTenant',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visibleJob',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/sequence-sync.ts#queueSequenceSync': [
    '#SEQUENCE_REQUESTED',
    'apps/api/src/modules/job/sequence-targets.ts#authorizeSequenceTargets',
    'apps/api/src/modules/job/sequence-targets.ts#normalizeSequenceSources',
    'apps/api/src/modules/job/sequence-targets.ts#sequenceTargets',
    'apps/api/src/modules/job/store.ts#auditJob',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
  ],
  'apps/api/src/modules/job/sequence-targets.ts#authorizeSequenceTargets': [
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
  ],
  'apps/api/src/modules/job/sequence-targets.ts#sequenceTargets': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#camelRow',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/record-store.ts#snapshotFields',
    'apps/api/src/modules/employment/timeline.ts#operationKey',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
    '#SEQUENCE_TARGET_LIMIT',
    '#normalizeSequenceSources',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/settings.ts#assertUniquePositionNames': ['apps/api/src/modules/job/store.ts#rowsOf'],
  'apps/api/src/modules/job/settings.ts#jobSettingsCommandSchema': ['apps/api/src/modules/job/fields.ts#businessDate'],
  'apps/api/src/modules/job/settings.ts#jobSettingsSchema': ['#jobSettingsCommandSchema'],
  'apps/api/src/modules/job/settings.ts#writeJobSettings': [
    '#assertUniquePositionNames',
    '#jobSettingsSchema',
    '#lockJobTenant',
    '#readJobSettings',
    'apps/api/src/modules/job/store.ts#auditJob',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/job/store.ts#auditJob': ['apps/api/src/audit/record.ts#recordAudit'],
  'apps/api/src/modules/job/store.ts#insertRow': ['#snakeCase'],
  'apps/api/src/modules/job/uniqueness.ts#assertJobCodeAvailable': [
    'apps/api/src/modules/job/metadata.ts#JOB_KINDS',
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/store.ts#rowsOf',
  ],
  'apps/api/src/modules/job/uniqueness.ts#assertPositionNameAvailable': [
    'apps/api/src/modules/job/read-model.ts#listJobObjects',
    'apps/api/src/modules/job/settings.ts#readJobSettings',
    '#positionBoundaries',
  ],
  'apps/api/src/modules/job/uniqueness.ts#positionBoundaries': ['apps/api/src/modules/job/store.ts#rowsOf'],
  'apps/api/src/modules/job/validation.ts#assertNoFutureAncestorMove': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/store.ts#rowsOf',
  ],
  'apps/api/src/modules/job/validation.ts#checkRanges': ['#invalid'],
  'apps/api/src/modules/job/validation.ts#checkScoreRange': ['#invalid'],
  'apps/api/src/modules/job/validation.ts#checkSelectedRange': ['#invalid', '#requiredJob'],
  'apps/api/src/modules/job/validation.ts#requiredJob': [
    'apps/api/src/modules/job/read-model.ts#loadJobObject',
    '#invalid',
  ],
  'apps/api/src/modules/job/validation.ts#treeFields': [
    '#SEQUENCE_ANCESTOR_FIELDS',
    '#assertNoFutureAncestorMove',
    '#invalid',
    '#requiredJob',
  ],
  'apps/api/src/modules/job/validation.ts#validateJobAssignment': ['#checkSelectedRange', '#invalid', '#requiredJob'],
  'apps/api/src/modules/job/validation.ts#validateJobFields': [
    '#checkRanges',
    '#checkScoreRange',
    '#positionParents',
    '#requiredJob',
    '#targets',
    '#treeFields',
    '#validateOrganizationReference',
    '#validatePositionHierarchy',
  ],
  'apps/api/src/modules/job/validation.ts#validateOrganizationReference': [
    'apps/api/src/modules/job/store.ts#rowsOf',
    '#invalid',
    'apps/api/src/modules/org/employment-validity.ts#employmentDepartmentDisable',
  ],
  'apps/api/src/modules/job/validation.ts#validatePositionHierarchy': ['#invalid', '#requiredJob'],
  'apps/api/src/modules/job/write-service.ts#appendVersion': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/read-model.ts#latestJobObject',
    'apps/api/src/modules/job/store.ts#insertRow',
  ],
  'apps/api/src/modules/job/write-service.ts#assertFutureHierarchy': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/read-model.ts#loadJobObject',
    'apps/api/src/modules/job/store.ts#rowsOf',
    'apps/api/src/modules/job/uniqueness.ts#positionBoundaries',
    'apps/api/src/modules/job/validation.ts#invalid',
  ],
  'apps/api/src/modules/job/write-service.ts#createJobObject': [
    'apps/api/src/modules/job/fields.ts#normalizeFields',
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/settings.ts#lockJobTenant',
    'apps/api/src/modules/job/store.ts#auditJob',
    'apps/api/src/modules/job/store.ts#insertRow',
    'apps/api/src/modules/job/uniqueness.ts#assertJobCodeAvailable',
    'apps/api/src/modules/job/uniqueness.ts#assertPositionNameAvailable',
    'apps/api/src/modules/job/validation.ts#validateJobFields',
    '#appendVersion',
    '#assertFutureHierarchy',
    '#assertRevision',
  ],
  'apps/api/src/modules/job/write-service.ts#jobRecordInput': ['apps/api/src/modules/job/fields.ts#jobCreationSchema'],
  'apps/api/src/modules/job/write-service.ts#lockObject': [
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/read-model.ts#latestJobObject',
    'apps/api/src/modules/job/store.ts#rowsOf',
  ],
  'apps/api/src/modules/job/write-service.ts#mergeInput': ['#jobRecordInput'],
  'apps/api/src/modules/job/write-service.ts#synchronizeDescendantTrees': [
    'apps/api/src/modules/job/fields.ts#normalizeFields',
    'apps/api/src/modules/job/metadata.ts#jobTables',
    'apps/api/src/modules/job/store.ts#auditJob',
    'apps/api/src/modules/job/store.ts#rowsOf',
    'apps/api/src/modules/job/validation.ts#treeFields',
    '#appendVersion',
    '#assertTemporalOrder',
    '#jobRecordInput',
    '#lockObject',
    '#updateRevision',
  ],
  'apps/api/src/modules/job/write-service.ts#updateJobObject': [
    'apps/api/src/modules/job/employment-port.ts#employmentJobPersonnel',
    'apps/api/src/modules/job/fields.ts#jobPatchSchema',
    'apps/api/src/modules/job/fields.ts#normalizeFields',
    'apps/api/src/modules/job/personnel.ts#applyPositionPersonnelRules',
    'apps/api/src/modules/job/sequence-sync.ts#queueSequenceSync',
    'apps/api/src/modules/job/settings.ts#lockJobTenant',
    'apps/api/src/modules/job/store.ts#auditJob',
    'apps/api/src/modules/job/uniqueness.ts#assertJobCodeAvailable',
    'apps/api/src/modules/job/uniqueness.ts#assertPositionNameAvailable',
    'apps/api/src/modules/job/validation.ts#invalid',
    'apps/api/src/modules/job/validation.ts#validateJobFields',
    '#appendVersion',
    '#assertFutureHierarchy',
    '#assertRevision',
    '#assertTemporalOrder',
    '#lockObject',
    '#mergeInput',
    '#synchronizeDescendantTrees',
    '#updateRevision',
  ],
  'apps/api/src/modules/job/write-service.ts#updateRevision': ['apps/api/src/modules/job/metadata.ts#jobTables'],
};
