/**
 * 直接依赖图：区域 api-modules-personnel（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
/* eslint-disable max-len -- 生成文件，键含完整路径 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/personnel/access.ts#access': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/scope-resolver.ts#personnelCreationScope',
    '#authorize',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/personnel/access.ts#authorize': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/personnel/access.ts#authorizeTx': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    '#authorize',
  ],
  'apps/api/src/modules/personnel/access.ts#personScope': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/access.ts#preflight': ['#requirePerson'],
  'apps/api/src/modules/personnel/access.ts#requirePerson': [
    '#personScope',
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/access.ts#trim': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#trimWithFields',
  ],
  'apps/api/src/modules/personnel/approval-hooks.ts#personnelApprovalHooks': ['#hooks'],
  'apps/api/src/modules/personnel/attachments.ts#registerAttachment': [
    'apps/api/src/modules/personnel/store.ts#insert',
  ],
  'apps/api/src/modules/personnel/attachments.ts#validateAttachments': [
    '#ATTACHMENT_FIELDS',
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#appendVersion': ['apps/api/src/modules/personnel/store.ts#insert'],
  'apps/api/src/modules/personnel/change-requests.ts#applyApprovedChangeInTransaction': [
    '#currentChangeValues',
    '#loadChange',
    'apps/api/src/modules/personnel/store.ts#assertRevision',
    'apps/api/src/modules/personnel/store.ts#audit',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/store.ts#update',
    'apps/api/src/modules/personnel/subsets.ts#saveSubset',
    'apps/api/src/modules/personnel/validation.ts#subsetInput',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#assertSelfServiceFields': [
    'apps/api/src/modules/tenant-settings/service.ts#readEffectiveSetting',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#createChange': [
    '#appendVersion',
    '#requireSelf',
    'apps/api/src/modules/personnel/store.ts#assertRevision',
    'apps/api/src/modules/personnel/store.ts#audit',
    'apps/api/src/modules/personnel/store.ts#insert',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/subset-policy.ts#runSubsetRequestPolicy',
    'apps/api/src/modules/personnel/subsets.ts#loadSubset',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#currentChangeValues': [
    '#loadChange',
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#disapproveChangeInTransaction': [
    '#loadChange',
    'apps/api/src/modules/personnel/store.ts#audit',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/store.ts#update',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#loadChange': [
    'apps/api/src/modules/personnel/store.ts#camel',
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#requireSelf': ['apps/api/src/modules/personnel/store.ts#rows'],
  'apps/api/src/modules/personnel/change-requests.ts#resubmitChangeInTransaction': [
    '#appendVersion',
    '#assertSelfServiceFields',
    '#currentChangeValues',
    '#loadChange',
    'apps/api/src/modules/personnel/store.ts#audit',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/store.ts#update',
    'apps/api/src/modules/personnel/subset-policy.ts#runSubsetRequestPolicy',
    'apps/api/src/modules/personnel/validation.ts#subsetInput',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
  ],
  'apps/api/src/modules/personnel/change-requests.ts#withdrawChangeInTransaction': [
    '#loadChange',
    'apps/api/src/modules/personnel/store.ts#audit',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/store.ts#update',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
  ],
  'apps/api/src/modules/personnel/employee-read.ts#employeeAttributes': [
    'apps/api/src/modules/avatar/references.ts#avatarSql',
    'apps/api/src/modules/personnel/sorting.ts#sortRankColumns',
  ],
  'apps/api/src/modules/personnel/employee-read.ts#employeeDto': [
    'apps/api/src/modules/personnel/store.ts#camel',
    'packages/domain/src/personnel/fields.ts#EMPLOYEE_FIELDS',
    'packages/domain/src/personnel/tenure.ts#ageOn',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/personnel/employee-read.ts#employeeJoins': [
    '#jobJoin',
    'apps/api/src/modules/personnel/sorting.ts#sortRankJoins',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/personnel/employee-read.ts#readEmployee': [
    '#employeeAttributes',
    '#employeeDto',
    '#employeeJoins',
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/employee-read.ts#readTenure': [
    'apps/api/src/modules/personnel/store.ts#rows',
    'packages/domain/src/personnel/tenure.ts#computeTenure',
  ],
  'apps/api/src/modules/personnel/employee-write.ts#appendEmployee': [
    'apps/api/src/modules/personnel/attachments.ts#validateAttachments',
    '#employeeSnapshot',
    'apps/api/src/modules/personnel/store.ts#assertRevision',
    'apps/api/src/modules/personnel/store.ts#audit',
    'apps/api/src/modules/personnel/store.ts#insert',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/store.ts#rows',
    'apps/api/src/modules/personnel/validation.ts#validateDates',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
    'packages/domain/src/personnel/fields.ts#EMPLOYEE_FIELDS',
  ],
  'apps/api/src/modules/personnel/employee-write.ts#employeeSnapshot': [
    'apps/api/src/modules/personnel/store.ts#camel',
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/http.ts#write': [
    'apps/api/src/modules/avatar/references.ts#employeeAvatars',
    'apps/api/src/modules/personnel/access.ts#authorizeTx',
    'apps/api/src/modules/personnel/access.ts#requirePerson',
    'apps/api/src/modules/personnel/access.ts#trim',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/modules/personnel/lists.ts#STATUS_FILTERS': [
    'packages/domain/src/employment/employee-status.ts#isEmployeeStatusCode',
    'packages/domain/src/employment/employee-status.ts#isEntryStatusCode',
  ],
  'apps/api/src/modules/personnel/lists.ts#listEmployees': [
    'apps/api/src/modules/personnel/access.ts#personScope',
    'apps/api/src/modules/personnel/employee-read.ts#employeeAttributes',
    'apps/api/src/modules/personnel/employee-read.ts#employeeDto',
    'apps/api/src/modules/personnel/employee-read.ts#employeeJoins',
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/lists.ts#listFieldVisibility': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/modules/personnel/lists.ts#listOptions': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#STATUS_FILTERS',
    '#sortColumns',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
    'packages/domain/src/personnel/catalog.ts#SUBSET_EMPLOYEE_ATTRIBUTES',
  ],
  'apps/api/src/modules/personnel/lists.ts#listSubsets': [
    'apps/api/src/modules/personnel/access.ts#personScope',
    'apps/api/src/modules/personnel/employee-read.ts#employeeJoins',
    '#subsetDto',
    'apps/api/src/modules/personnel/sorting.ts#sortRankColumns',
    'apps/api/src/modules/personnel/store.ts#rows',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/lists.ts#subsetDto': [
    'apps/api/src/modules/personnel/store.ts#camel',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/lists.ts#trimSubset': [
    'apps/api/src/modules/personnel/access.ts#trimWithFields',
    'packages/domain/src/personnel/catalog.ts#SUBSET_EMPLOYEE_ATTRIBUTES',
  ],
  'apps/api/src/modules/personnel/order-code-query.ts#orderCodeProjection': [
    '#jobJoin',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/personnel/order-code-routes.ts#registerOrderCodeRoutes': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/personnel/http.ts#body',
    'apps/api/src/modules/personnel/http.ts#safe',
    '#base',
    '#resource',
    'apps/api/src/modules/personnel/order-code-settings.ts#orderSettingsInput',
    'apps/api/src/modules/personnel/order-code-settings.ts#readOrderSettings',
    'apps/api/src/modules/personnel/order-code-settings.ts#saveOrderSettings',
    'apps/api/src/modules/personnel/order-code.ts#recomputeOrderCodes',
    'apps/api/src/modules/personnel/validation.ts#parse',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/personnel/order-code-routes.ts#route:GET /api/tenant/personnel/order-code/settings': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/personnel/http.ts#safe',
    '#base',
    '#resource',
    'apps/api/src/modules/personnel/order-code-settings.ts#readOrderSettings',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/personnel/order-code-settings.ts#lockOrderSettings': ['#readOrderSettings'],
  'apps/api/src/modules/personnel/order-code-settings.ts#readOrderSettings': [
    'apps/api/src/modules/personnel/store.ts#rows',
  ],
  'apps/api/src/modules/personnel/order-code-settings.ts#saveOrderSettings': [
    'apps/api/src/audit/record.ts#recordAudit',
    '#lockOrderSettings',
    'apps/api/src/modules/personnel/store.ts#assertRevision',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/personnel/order-code.ts#recomputeOrderCodes': [
    'apps/api/src/audit/request-context.ts#currentAuditRequest',
    'apps/api/src/modules/personnel/order-code-query.ts#orderCodeProjection',
    'apps/api/src/modules/personnel/order-code-settings.ts#lockOrderSettings',
    '#columns',
    '#recordRun',
    'apps/api/src/modules/personnel/store.ts#assertRevision',
    'apps/api/src/modules/personnel/store.ts#rows',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/personnel/order-code.ts#recordRun': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/personnel/request-routes.ts#route:GET /api/tenant/personnel/change-requests/:id': [
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/access.ts#preflight',
    'apps/api/src/modules/personnel/access.ts#trim',
    'apps/api/src/modules/personnel/change-requests.ts#loadChange',
    'apps/api/src/modules/personnel/change-requests.ts#requireSelf',
    'apps/api/src/modules/personnel/http.ts#safe',
    '#base',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
  ],
  'apps/api/src/modules/personnel/request-routes.ts#route:POST /api/tenant/personnel/change-requests': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/personnel/approval-hooks.ts#personnelApprovalHooks',
    'apps/api/src/modules/personnel/change-requests.ts#assertSelfServiceFields',
    'apps/api/src/modules/personnel/change-requests.ts#createChange',
    'apps/api/src/modules/personnel/change-requests.ts#requireSelf',
    'apps/api/src/modules/personnel/http.ts#body',
    'apps/api/src/modules/personnel/http.ts#safe',
    '#base',
    '#requestSchema',
    'apps/api/src/modules/personnel/validation.ts#parse',
    'apps/api/src/modules/personnel/validation.ts#subsetInput',
    'apps/api/src/modules/personnel/validation.ts#subsetKind',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
  ],
  'apps/api/src/modules/personnel/routes.ts#nestedSubsets': [
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/personnel/lists.ts#UNSORTED',
    'apps/api/src/modules/personnel/lists.ts#listFieldVisibility',
    'apps/api/src/modules/personnel/lists.ts#listSubsets',
    'apps/api/src/modules/personnel/lists.ts#trimSubset',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/routes.ts#route:GET /api/tenant/personnel/employees': [
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/access.ts#trimWithFields',
    'apps/api/src/modules/personnel/http.ts#safe',
    'apps/api/src/modules/personnel/lists.ts#listEmployees',
    'apps/api/src/modules/personnel/lists.ts#listOptions',
    '#base',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/modules/personnel/routes.ts#route:GET /api/tenant/personnel/employees/:id': [
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/access.ts#preflight',
    'apps/api/src/modules/personnel/access.ts#trim',
    'apps/api/src/modules/personnel/employee-read.ts#readEmployee',
    'apps/api/src/modules/personnel/employee-read.ts#readTenure',
    'apps/api/src/modules/personnel/http.ts#safe',
    '#base',
    '#nestedSubsets',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/personnel/routes.ts#route:GET /api/tenant/personnel/employees/:id/history': [
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/access.ts#preflight',
    'apps/api/src/modules/personnel/access.ts#trimWithFields',
    'apps/api/src/modules/personnel/http.ts#safe',
    '#base',
    'apps/api/src/modules/personnel/store.ts#camel',
    'apps/api/src/modules/personnel/store.ts#rows',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/modules/personnel/routes.ts#route:GET /api/tenant/personnel/employees/:id/tenure': [
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/access.ts#preflight',
    'apps/api/src/modules/personnel/access.ts#trim',
    'apps/api/src/modules/personnel/employee-read.ts#readTenure',
    'apps/api/src/modules/personnel/http.ts#safe',
    '#base',
    'apps/api/src/modules/personnel/validation.ts#dateValue',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/personnel/routes.ts#route:PATCH /api/tenant/personnel/employees/:id': [
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/employee-read.ts#readEmployee',
    'apps/api/src/modules/personnel/employee-write.ts#appendEmployee',
    'apps/api/src/modules/personnel/http.ts#body',
    'apps/api/src/modules/personnel/http.ts#safe',
    'apps/api/src/modules/personnel/http.ts#write',
    '#base',
    'apps/api/src/modules/personnel/validation.ts#employeeInput',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/modules/personnel/routes.ts#route:POST /api/tenant/personnel/employees/:id/attachments': [
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/attachments.ts#registerAttachment',
    'apps/api/src/modules/personnel/http.ts#body',
    'apps/api/src/modules/personnel/http.ts#safe',
    'apps/api/src/modules/personnel/http.ts#write',
    '#base',
    'apps/api/src/modules/personnel/validation.ts#parse',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/modules/personnel/store.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    '#insert',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/personnel/store.ts#insert': ['#column'],
  'apps/api/src/modules/personnel/store.ts#lockPerson': ['#rows'],
  'apps/api/src/modules/personnel/store.ts#update': ['#column'],
  'apps/api/src/modules/personnel/subset-policy.ts#registerSubsetPolicy': ['#POLICIES'],
  'apps/api/src/modules/personnel/subset-policy.ts#runSubsetRequestPolicy': ['#POLICIES'],
  'apps/api/src/modules/personnel/subset-policy.ts#runSubsetSavePolicy': ['#POLICIES'],
  'apps/api/src/modules/personnel/subset-routes.ts#base': ['#root'],
  'apps/api/src/modules/personnel/subset-routes.ts#route:DELETE /api/tenant/personnel/employees/:employeeId/subsets/:kind/:id':
    [
      'apps/api/src/modules/job/context.ts#revision',
      'apps/api/src/modules/job/context.ts#uuidParam',
      'apps/api/src/modules/personnel/access.ts#access',
      'apps/api/src/modules/personnel/http.ts#safe',
      'apps/api/src/modules/personnel/http.ts#write',
      '#base',
      'apps/api/src/modules/personnel/subsets.ts#saveSubset',
      'apps/api/src/modules/personnel/validation.ts#subsetKind',
      'packages/domain/src/personnel/fields.ts#SUBSETS',
    ],
  'apps/api/src/modules/personnel/subset-routes.ts#route:GET /api/tenant/personnel/employees/:employeeId/subsets/:kind':
    [
      'apps/api/src/modules/job/context.ts#pageQuery',
      'apps/api/src/modules/job/context.ts#uuidParam',
      'apps/api/src/modules/personnel/access.ts#access',
      'apps/api/src/modules/personnel/access.ts#preflight',
      'apps/api/src/modules/personnel/http.ts#safe',
      'apps/api/src/modules/personnel/lists.ts#listFieldVisibility',
      'apps/api/src/modules/personnel/lists.ts#listOptions',
      'apps/api/src/modules/personnel/lists.ts#listSubsets',
      'apps/api/src/modules/personnel/lists.ts#trimSubset',
      'apps/api/src/modules/personnel/validation.ts#subsetKind',
      'packages/domain/src/personnel/fields.ts#SUBSETS',
    ],
  'apps/api/src/modules/personnel/subset-routes.ts#route:GET /api/tenant/personnel/employees/:employeeId/subsets/:kind/:id':
    [
      'apps/api/src/modules/job/context.ts#uuidParam',
      'apps/api/src/modules/personnel/access.ts#access',
      'apps/api/src/modules/personnel/access.ts#preflight',
      'apps/api/src/modules/personnel/access.ts#trim',
      'apps/api/src/modules/personnel/http.ts#safe',
      'apps/api/src/modules/personnel/lists.ts#subsetDto',
      '#base',
      'apps/api/src/modules/personnel/subsets.ts#loadSubset',
      'apps/api/src/modules/personnel/validation.ts#subsetKind',
      'packages/domain/src/personnel/fields.ts#SUBSETS',
    ],
  'apps/api/src/modules/personnel/subset-routes.ts#route:GET /api/tenant/personnel/employees/:employeeId/subsets/:kind/:id/history':
    [
      'apps/api/src/modules/job/context.ts#pageQuery',
      'apps/api/src/modules/job/context.ts#uuidParam',
      'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
      'apps/api/src/modules/personnel/access.ts#access',
      'apps/api/src/modules/personnel/access.ts#preflight',
      'apps/api/src/modules/personnel/access.ts#trimWithFields',
      'apps/api/src/modules/personnel/http.ts#safe',
      'apps/api/src/modules/personnel/lists.ts#subsetDto',
      'apps/api/src/modules/personnel/store.ts#rows',
      '#base',
      'apps/api/src/modules/personnel/subsets.ts#loadSubset',
      'apps/api/src/modules/personnel/validation.ts#subsetKind',
      'packages/domain/src/personnel/fields.ts#SUBSETS',
    ],
  'apps/api/src/modules/personnel/subset-routes.ts#route:GET /api/tenant/personnel/subsets/:kind': [
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/access.ts#preflight',
    'apps/api/src/modules/personnel/http.ts#safe',
    'apps/api/src/modules/personnel/lists.ts#listFieldVisibility',
    'apps/api/src/modules/personnel/lists.ts#listOptions',
    'apps/api/src/modules/personnel/lists.ts#listSubsets',
    'apps/api/src/modules/personnel/lists.ts#trimSubset',
    'apps/api/src/modules/personnel/validation.ts#subsetKind',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/subset-routes.ts#route:PATCH /api/tenant/personnel/employees/:employeeId/subsets/:kind/:id':
    [
      'apps/api/src/modules/job/context.ts#revision',
      'apps/api/src/modules/job/context.ts#uuidParam',
      'apps/api/src/modules/personnel/access.ts#access',
      'apps/api/src/modules/personnel/http.ts#body',
      'apps/api/src/modules/personnel/http.ts#safe',
      'apps/api/src/modules/personnel/http.ts#write',
      '#base',
      'apps/api/src/modules/personnel/subsets.ts#saveSubset',
      'apps/api/src/modules/personnel/validation.ts#subsetInput',
      'apps/api/src/modules/personnel/validation.ts#subsetKind',
      'packages/domain/src/personnel/fields.ts#SUBSETS',
    ],
  'apps/api/src/modules/personnel/subset-routes.ts#route:POST /api/tenant/personnel/employees/:employeeId/subsets/:kind':
    [
      'apps/api/src/modules/job/context.ts#revision',
      'apps/api/src/modules/job/context.ts#uuidParam',
      'apps/api/src/modules/personnel/access.ts#access',
      'apps/api/src/modules/personnel/http.ts#body',
      'apps/api/src/modules/personnel/http.ts#safe',
      'apps/api/src/modules/personnel/http.ts#write',
      '#base',
      'apps/api/src/modules/personnel/subsets.ts#saveSubset',
      'apps/api/src/modules/personnel/validation.ts#subsetInput',
      'apps/api/src/modules/personnel/validation.ts#subsetKind',
      'packages/domain/src/personnel/fields.ts#SUBSETS',
    ],
  'apps/api/src/modules/personnel/subsets.ts#clearFlags': [
    'apps/api/src/modules/personnel/store.ts#camel',
    'apps/api/src/modules/personnel/store.ts#rows',
    '#FLAG_MAP',
    '#persistSubset',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/subsets.ts#loadSubset': [
    'apps/api/src/modules/personnel/store.ts#camel',
    'apps/api/src/modules/personnel/store.ts#rows',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/subsets.ts#persistSubset': [
    'apps/api/src/modules/personnel/store.ts#audit',
    'apps/api/src/modules/personnel/store.ts#insert',
    'apps/api/src/modules/personnel/store.ts#update',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/subsets.ts#reflectFlags': [
    'apps/api/src/modules/personnel/employee-write.ts#appendEmployee',
    'apps/api/src/modules/personnel/employee-write.ts#employeeSnapshot',
    'apps/api/src/modules/personnel/store.ts#camel',
    'apps/api/src/modules/personnel/store.ts#rows',
    '#FLAG_MAP',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/subsets.ts#saveSubset': [
    'apps/api/src/modules/personnel/attachments.ts#validateAttachments',
    'apps/api/src/modules/personnel/store.ts#assertRevision',
    'apps/api/src/modules/personnel/store.ts#lockPerson',
    'apps/api/src/modules/personnel/subset-policy.ts#runSubsetSavePolicy',
    '#clearFlags',
    '#loadSubset',
    '#persistSubset',
    '#reflectFlags',
    'apps/api/src/modules/personnel/validation.ts#validateDates',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/validation.ts#dateValue': ['#isoDate', '#parse'],
  'apps/api/src/modules/personnel/validation.ts#employeeInput': [
    '#parseFields',
    'packages/domain/src/personnel/fields.ts#EMPLOYEE_FIELDS',
  ],
  'apps/api/src/modules/personnel/validation.ts#fieldSchema': ['#isoDate'],
  'apps/api/src/modules/personnel/validation.ts#parseFields': ['#fieldSchema', '#parse'],
  'apps/api/src/modules/personnel/validation.ts#subsetInput': [
    '#parseFields',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/personnel/validation.ts#subsetKind': ['packages/domain/src/personnel/fields.ts#SUBSETS'],
};
