/**
 * 直接依赖图：区域 api-modules-org（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/org/codes.ts#consumeCode': [
    '#assertCodeAvailable',
    '#ensureOrgSetup',
    '#ownedReservation',
    '#reservationAudit',
    '#reserveCode',
  ],
  'apps/api/src/modules/org/codes.ts#ensureOrgSetup': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/modules/org/locks.ts#lockOrganizationSettings',
  ],
  'apps/api/src/modules/org/codes.ts#nextCode': ['#available'],
  'apps/api/src/modules/org/codes.ts#releaseCode': ['#ensureOrgSetup', '#ownedReservation', '#reservationAudit'],
  'apps/api/src/modules/org/codes.ts#reservationAudit': ['apps/api/src/audit/record.ts#recordAudit'],
  'apps/api/src/modules/org/codes.ts#reserveCode': ['#ensureOrgSetup', '#nextCode', '#reservationAudit'],
  'apps/api/src/modules/org/correction.ts#assertCodeFree': ['apps/api/src/modules/org/read-model.ts#rowsOf'],
  'apps/api/src/modules/org/correction.ts#assertNotBeforeParents': [
    '#earliest',
    '#rejected',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS',
  ],
  'apps/api/src/modules/org/correction.ts#assertNothingBefore': ['#earliest', '#rejected'],
  'apps/api/src/modules/org/correction.ts#earliest': ['apps/api/src/modules/org/read-model.ts#rowsOf'],
  'apps/api/src/modules/org/correction.ts#planEstablishedOnCorrection': [
    '#assertCodeFree',
    '#assertNotBeforeParents',
    '#assertNothingBefore',
    '#dayBefore',
    '#rejected',
    'apps/api/src/modules/org/deactivation.ts#assertParentAvailable',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
  ],
  'apps/api/src/modules/org/deactivation.ts#assertParentAvailable': ['#dayAfter'],
  'apps/api/src/modules/org/deactivation.ts#assertSubtreeVacant': [
    'apps/api/src/modules/employment/org-people.ts#countDepartmentStaff',
    'apps/api/src/modules/job/read-model.ts#countEnabledPositions',
    '#REPORT_LIMIT',
    '#countPendingTransfers',
  ],
  'apps/api/src/modules/org/deactivation.ts#countPendingTransfers': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/org/deactivation.ts#planDeactivation': [
    '#CASCADE_LIMIT',
    '#assertSubtreeVacant',
    '#rejectFutureDescendantVersions',
    '#subtree',
    'apps/api/src/modules/org/read-model.ts#futureBoundaries',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
  ],
  'apps/api/src/modules/org/deactivation.ts#unavailableFrom': ['#dayAfter'],
  'apps/api/src/modules/org/employment-linkage.ts#applyOrgEmploymentLinkage': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/org-adjustment.ts#appendOrgAdjustment',
    '#orgEmploymentTargets',
  ],
  'apps/api/src/modules/org/employment-linkage.ts#authorizeOrgEmploymentReplay': [
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#ORG_EMPLOYMENT_LIMIT',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/employment-linkage.ts#hasPendingOrgEmployment': [
    'apps/api/src/modules/employment/activation-store.ts#pendingActivationState',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
    '#subtree',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/employment-linkage.ts#lockOrgEmploymentEmployees': [
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    '#idsSql',
  ],
  'apps/api/src/modules/org/employment-linkage.ts#lockOrgEmploymentTargets': [
    '#lockOrgEmploymentEmployees',
    '#orgEmploymentTargets',
  ],
  'apps/api/src/modules/org/employment-linkage.ts#orgEmploymentTargets': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#ORG_EMPLOYMENT_LIMIT',
    '#subtree',
  ],
  'apps/api/src/modules/org/employment-linkage.ts#subtree': ['#idsSql'],
  'apps/api/src/modules/org/employment-linkage.ts#validateEmploymentChoice': [
    '#requiresEmploymentChoice',
    'apps/api/src/modules/org/validation.ts#invalid',
  ],
  'apps/api/src/modules/org/import-employment.ts#planImportEmployment': [
    'apps/api/src/modules/org/employment-linkage.ts#ORG_EMPLOYMENT_LIMIT',
    'apps/api/src/modules/org/employment-linkage.ts#lockOrgEmploymentEmployees',
    'apps/api/src/modules/org/employment-linkage.ts#orgEmploymentTargets',
    'apps/api/src/modules/org/employment-linkage.ts#requiresEmploymentChoice',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/import-service.ts#importOrganizations': [
    'apps/api/src/audit/record.ts#recordImportLog',
    'apps/api/src/modules/org/codes.ts#ensureOrgSetup',
    'apps/api/src/modules/org/import-employment.ts#planImportEmployment',
    '#assertBatch',
    '#assertRequiredRevisions',
    '#importRow',
    '#importSnapshot',
    '#preflightConflict',
    '#rowError',
    '#saveReceipt',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/org/import-service.ts#importRow': [
    'apps/api/src/modules/org/employment-linkage.ts#requiresEmploymentChoice',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'apps/api/src/modules/org/write-service.ts#createOrganization',
    'apps/api/src/modules/org/write-service.ts#updateOrganization',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/import-service.ts#importSnapshot': [
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/import-service.ts#saveReceipt': ['apps/api/src/audit/record.ts#recordAudit'],
  'apps/api/src/modules/org/people.ts#assertOrgPeopleEligible': [
    'apps/api/src/modules/employment/org-people.ts#ineligibleOrgPeople',
    'apps/api/src/modules/org/validation.ts#ORG_PERSON_FIELDS',
  ],
  'apps/api/src/modules/org/people.ts#submittedPeople': ['apps/api/src/modules/org/validation.ts#ORG_PERSON_FIELDS'],
  'apps/api/src/modules/org/read-model.ts#currentOrgVersions': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
  ],
  'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot': ['#orgSnapshotQuery', '#resolveOrgPaths'],
  'apps/api/src/modules/org/read-model.ts#orgSnapshotQuery': ['#currentOrgVersions'],
  'apps/api/src/modules/org/read-model.ts#resolveOrgPaths': ['#MAX_PATH_DEPTH', '#rowsOf'],
  'apps/api/src/modules/org/routes.ts#OBJECT': ['packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS'],
  'apps/api/src/modules/org/routes.ts#anyPersonFieldEditable': [
    '#OBJECT',
    'apps/api/src/modules/org/validation.ts#ORG_PERSON_FIELDS',
  ],
  'apps/api/src/modules/org/routes.ts#context': [
    'apps/api/src/authorization.ts#requirePermission',
    '#OBJECT',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/org/routes.ts#correction': ['#date'],
  'apps/api/src/modules/org/routes.ts#creation': [
    'apps/api/src/modules/employment/fields.ts#normalizedUuid',
    '#fields',
    '#parents',
  ],
  'apps/api/src/modules/org/routes.ts#date': ['apps/api/src/modules/org/read-model.ts#validIsoDate'],
  'apps/api/src/modules/org/routes.ts#fields': [
    'apps/api/src/modules/employment/fields.ts#normalizedUuid',
    '#date',
    '#order',
  ],
  'apps/api/src/modules/org/routes.ts#importOrgRows': [
    'apps/api/src/modules/org/import-service.ts#authorizeOrgImportRows',
    'apps/api/src/modules/org/import-service.ts#importOrganizations',
    '#OBJECT',
    '#body',
    '#importRow',
    '#write',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'apps/api/src/modules/permission/org-result-scope.ts#authorizeOrgResult',
    'apps/api/src/modules/permission/org-result-scope.ts#originalOrgImportRows',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/org/routes.ts#importRow': [
    'apps/api/src/modules/employment/fields.ts#normalizedUuid',
    '#date',
    '#fields',
  ],
  'apps/api/src/modules/org/routes.ts#organizationResponse': [
    'apps/api/src/modules/org/read-model.ts#displayOrganization',
    'apps/api/src/modules/org/settings.ts#readOrgSettings',
  ],
  'apps/api/src/modules/org/routes.ts#parent': ['apps/api/src/modules/employment/fields.ts#normalizedUuid', '#order'],
  'apps/api/src/modules/org/routes.ts#parents': ['#parent'],
  'apps/api/src/modules/org/routes.ts#queryDate': [
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/routes.ts#route:DELETE /api/tenant/org/code-reservations/:id': [
    'apps/api/src/modules/org/codes.ts#releaseCode',
    '#BASE',
    '#OBJECT',
    '#context',
    '#orgId',
    '#revision',
    '#write',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
  ],
  'apps/api/src/modules/org/routes.ts#route:GET /api/tenant/org/organizations': [
    'apps/api/src/modules/org/read-model.ts#displayOrganization',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    '#BASE',
    '#OBJECT',
    '#context',
    '#queryDate',
    '#queryInteger',
    'apps/api/src/modules/org/settings.ts#readOrgSettings',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS',
  ],
  'apps/api/src/modules/org/routes.ts#route:GET /api/tenant/org/organizations/:id': [
    'apps/api/src/modules/org/read-model.ts#displayOrganization',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    '#BASE',
    '#OBJECT',
    '#context',
    '#orgId',
    '#queryDate',
    'apps/api/src/modules/org/settings.ts#readOrgSettings',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/org/routes.ts#route:GET /api/tenant/org/person-candidates': [
    'apps/api/src/modules/employment/org-people.ts#listOrgPersonCandidates',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/org/read-model.ts#validIsoDate',
    '#BASE',
    '#anyPersonFieldEditable',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/routes.ts#route:GET /api/tenant/org/settings': [
    '#BASE',
    '#context',
    'apps/api/src/modules/org/settings.ts#readOrgSettings',
  ],
  'apps/api/src/modules/org/routes.ts#route:GET /api/tenant/org/views': [
    '#BASE',
    '#OBJECT',
    '#context',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
  ],
  'apps/api/src/modules/org/routes.ts#route:PATCH /api/tenant/org/organizations/:id': [
    '#BASE',
    '#OBJECT',
    '#body',
    '#context',
    '#orgId',
    '#organizationResponse',
    '#revision',
    '#update',
    '#visibleParents',
    '#write',
    'apps/api/src/modules/org/write-service.ts#updateOrganization',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'apps/api/src/modules/permission/org-result-scope.ts#authorizeOrgResult',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/routes.ts#route:PATCH /api/tenant/org/organizations/:id/correction': [
    '#BASE',
    '#OBJECT',
    '#body',
    '#context',
    '#correction',
    '#orgId',
    '#organizationResponse',
    '#revision',
    '#write',
    'apps/api/src/modules/org/write-service.ts#correctEstablishedOn',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/org/routes.ts#route:POST /api/tenant/org/code-reservations': [
    'apps/api/src/modules/org/codes.ts#reserveCode',
    '#BASE',
    '#OBJECT',
    '#body',
    '#context',
    '#requireNew',
    '#revision',
    '#write',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/org/routes.ts#route:POST /api/tenant/org/import': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/audit/record.ts#withFailedImportLog',
    '#BASE',
    '#context',
    '#importOrgRows',
    '#requireNew',
    '#revision',
  ],
  'apps/api/src/modules/org/routes.ts#route:POST /api/tenant/org/organizations': [
    '#BASE',
    '#OBJECT',
    '#body',
    '#context',
    '#creation',
    '#organizationResponse',
    '#requireNew',
    '#revision',
    '#visibleParents',
    '#write',
    'apps/api/src/modules/org/write-service.ts#createOrganization',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/org/routes.ts#route:POST /api/tenant/org/organizations/:id/employment-preview': [
    'apps/api/src/modules/org/employment-linkage.ts#hasPendingOrgEmployment',
    'apps/api/src/modules/org/employment-linkage.ts#validateEmploymentChoice',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    '#BASE',
    '#OBJECT',
    '#body',
    '#context',
    '#orgId',
    '#update',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'apps/api/src/modules/permission/org-result-scope.ts#authorizeOrgResult',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/routes.ts#route:POST /api/tenant/org/validate': [
    '#BASE',
    '#OBJECT',
    '#body',
    '#context',
    '#creation',
    '#visibleParents',
    'apps/api/src/modules/org/write-service.ts#validateOrganization',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/module-route-access.ts#button',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
  ],
  'apps/api/src/modules/org/routes.ts#route:PUT /api/tenant/org/settings': [
    '#BASE',
    '#body',
    '#context',
    '#revision',
    '#settings',
    '#write',
    'apps/api/src/modules/org/settings.ts#writeOrgSettings',
  ],
  'apps/api/src/modules/org/routes.ts#settings': ['packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS'],
  'apps/api/src/modules/org/routes.ts#update': ['#date', '#fields', '#parents'],
  'apps/api/src/modules/org/routes.ts#visibleParents': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/org/routes.ts#write': [
    'apps/api/src/modules/org/employment-linkage.ts#authorizeOrgEmploymentReplay',
    '#OBJECT',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/permission/org-result-scope.ts#authorizeOrgResult',
  ],
  'apps/api/src/modules/org/settings.ts#writeOrgSettings': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/modules/org/codes.ts#ensureOrgSetup',
    '#readOrgSettings',
  ],
  'apps/api/src/modules/org/validation.ts#assertNoCycle': ['#invalid'],
  'apps/api/src/modules/org/validation.ts#assertSnapshotAcyclic': [
    '#assertNoCycle',
    'packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS',
  ],
  'apps/api/src/modules/org/validation.ts#date': ['#invalid'],
  'apps/api/src/modules/org/validation.ts#flag': ['#invalid'],
  'apps/api/src/modules/org/validation.ts#integer': ['#invalid'],
  'apps/api/src/modules/org/validation.ts#normalizeCreation': [
    '#date',
    '#invalid',
    '#normalizeOrganization',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/org/validation.ts#normalizeOrganization': [
    '#costCenterNotEnabled',
    '#date',
    '#flag',
    '#integer',
    '#invalid',
    '#normalizeParents',
    '#optionalText',
    '#reference',
    '#requiredText',
    '#validateCodeFields',
  ],
  'apps/api/src/modules/org/validation.ts#normalizeParents': [
    '#integer',
    '#invalid',
    'packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS',
  ],
  'apps/api/src/modules/org/validation.ts#optionalText': ['#invalid'],
  'apps/api/src/modules/org/validation.ts#reference': ['#invalid'],
  'apps/api/src/modules/org/validation.ts#requiredText': ['#invalid'],
  'apps/api/src/modules/org/validation.ts#validateCodeFields': ['#flag', '#invalid', '#requiredText'],
  'apps/api/src/modules/org/validation.ts#validateHierarchy': [
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    '#assertNoCycle',
    '#invalid',
    'packages/domain/src/contracts/org-hierarchy.ts#ORG_DIMENSIONS',
  ],
  'apps/api/src/modules/org/write-service.ts#assignTransferOrganizationPeople': [
    'apps/api/src/modules/org/codes.ts#ensureOrgSetup',
    '#objectKey',
    '#requireTransferOrganizationScope',
    '#updateOrganization',
  ],
  'apps/api/src/modules/org/write-service.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    '#auditFields',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/org/write-service.ts#correctEstablishedOn': [
    'apps/api/src/modules/org/correction.ts#applyEstablishedOnCorrection',
    'apps/api/src/modules/org/correction.ts#planEstablishedOnCorrection',
    'apps/api/src/modules/org/validation.ts#date',
    'apps/api/src/modules/org/validation.ts#invalid',
    '#assertRevision',
    '#audit',
    '#objectKey',
    '#recordAt',
  ],
  'apps/api/src/modules/org/write-service.ts#createOrganization': [
    'apps/api/src/modules/org/codes.ts#consumeCode',
    'apps/api/src/modules/org/codes.ts#ensureOrgSetup',
    'apps/api/src/modules/org/validation.ts#normalizeCreation',
    'apps/api/src/modules/org/validation.ts#validateHierarchy',
    '#appendVersion',
    '#assertCanSubmit',
    '#assertRevision',
    '#audit',
    '#noEstablishmentRule',
    '#parentPath',
    '#validateOrganization',
  ],
  'apps/api/src/modules/org/write-service.ts#disableDescendants': [
    'apps/api/src/modules/org/validation.ts#normalizeOrganization',
    '#appendVersion',
    '#audit',
    '#objectKey',
  ],
  'apps/api/src/modules/org/write-service.ts#recordAt': [
    'apps/api/src/modules/org/read-model.ts#resolveOrgPaths',
    'apps/api/src/modules/org/validation.ts#invalid',
  ],
  'apps/api/src/modules/org/write-service.ts#requireTransferOrganizationScope': [
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
    'apps/api/src/modules/permission/module-access.ts#linkedObjectScope',
  ],
  'apps/api/src/modules/org/write-service.ts#updateOrganization': [
    'apps/api/src/modules/org/codes.ts#assertCodeAvailable',
    'apps/api/src/modules/org/codes.ts#ensureOrgSetup',
    'apps/api/src/modules/org/deactivation.ts#assertParentAvailable',
    'apps/api/src/modules/org/deactivation.ts#planDeactivation',
    'apps/api/src/modules/org/deactivation.ts#unavailableFrom',
    'apps/api/src/modules/org/employment-linkage.ts#applyOrgEmploymentLinkage',
    'apps/api/src/modules/org/employment-linkage.ts#lockOrgEmploymentTargets',
    'apps/api/src/modules/org/employment-linkage.ts#validateEmploymentChoice',
    'apps/api/src/modules/org/people.ts#assertOrgPeopleEligible',
    'apps/api/src/modules/org/people.ts#submittedPeople',
    'apps/api/src/modules/org/validation.ts#date',
    'apps/api/src/modules/org/validation.ts#invalid',
    'apps/api/src/modules/org/validation.ts#normalizeOrganization',
    'apps/api/src/modules/org/validation.ts#validateHierarchy',
    '#appendVersion',
    '#assertEstablishedOnUnchanged',
    '#assertRevision',
    '#audit',
    '#disableDescendants',
    '#mergePatch',
    '#objectKey',
    '#parentPath',
    '#recordAt',
    '#rejectEarlierThanFutureVersion',
    '#validateFutureSnapshots',
  ],
  'apps/api/src/modules/org/write-service.ts#validateFutureSnapshots': [
    'apps/api/src/modules/org/read-model.ts#futureBoundaries',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'apps/api/src/modules/org/validation.ts#assertSnapshotAcyclic',
  ],
  'apps/api/src/modules/org/write-service.ts#validateOrganization': [
    'apps/api/src/modules/org/deactivation.ts#assertParentAvailable',
    'apps/api/src/modules/org/people.ts#assertOrgPeopleEligible',
    'apps/api/src/modules/org/people.ts#submittedPeople',
    'apps/api/src/modules/org/validation.ts#normalizeCreation',
    'apps/api/src/modules/org/validation.ts#validateHierarchy',
    '#noEstablishmentRule',
  ],
};
