/**
 * 直接依赖图：区域 api-modules-idp（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/idp/access.ts#accessOf': [
    '#rowsOf',
    'apps/api/src/modules/permission/module-access.ts#scopeAllows',
    'apps/api/src/modules/permission/public-down.ts#publicDownSql',
  ],
  'apps/api/src/modules/idp/access.ts#checkWriteFields': [
    '#codeOf',
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'packages/domain/src/idp/catalog.ts#withLinkedFields',
  ],
  'apps/api/src/modules/idp/access.ts#codeOf': ['packages/domain/src/idp/catalog.ts#IDP_OBJECTS'],
  'apps/api/src/modules/idp/access.ts#idpContext': [
    '#codeOf',
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
  ],
  'apps/api/src/modules/idp/access.ts#idpScope': [
    '#codeOf',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
  ],
  'apps/api/src/modules/idp/access.ts#idpWriteContext': [
    '#codeOf',
    '#idpContext',
    'apps/api/src/modules/permission/module-route-access.ts#button',
  ],
  'apps/api/src/modules/idp/access.ts#objectFields': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'packages/domain/src/idp/catalog.ts#linkedViewable',
  ],
  'apps/api/src/modules/idp/access.ts#projectionOf': ['#codeOf', '#objectFields'],
  'apps/api/src/modules/idp/access.ts#replayChecks': [
    '#codeOf',
    '#objectFields',
    '#requireViewable',
    '#requireWrite',
    '#sourceHidden',
    '#viewable',
  ],
  'apps/api/src/modules/idp/access.ts#requireCreatable': [
    '#IDP_LABELS',
    'apps/api/src/modules/permission/module-route-access.ts#visible',
  ],
  'apps/api/src/modules/idp/access.ts#requireEditable': ['#IDP_LABELS', '#accessOf'],
  'apps/api/src/modules/idp/access.ts#requireNestedWrite': [
    '#codeOf',
    '#requireWrite',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'packages/domain/src/idp/catalog.ts#withLinkedFields',
  ],
  'apps/api/src/modules/idp/access.ts#requireReadable': ['#IDP_LABELS', '#accessOf'],
  'apps/api/src/modules/idp/access.ts#requireViewable': ['#IDP_LABELS', '#viewable'],
  'apps/api/src/modules/idp/access.ts#requireWrite': ['apps/api/src/authorization.ts#requirePermission', '#codeOf'],
  'apps/api/src/modules/idp/approval-adapter.ts#deletedInstance': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/approval-adapter.ts#deletedSubject': ['#deletedInstance'],
  'apps/api/src/modules/idp/approval-adapter.ts#deletedType': ['#deletedInstance'],
  'apps/api/src/modules/idp/approval-adapter.ts#idpAdapter': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#deletedSubject',
    '#deletedType',
    '#requireGoals',
    '#stageOf',
    'apps/api/src/modules/idp/plan-store.ts#loadStage',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/stage-service.ts#onStageApproved',
    'apps/api/src/modules/idp/stage-service.ts#onStageDisapproved',
    'apps/api/src/system-actor.ts#SYSTEM_USER_ID',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
    'packages/domain/src/idp/catalog.ts#IDP_OBJECTS',
  ],
  'apps/api/src/modules/idp/approval-adapter.ts#requireGoals': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#stageOf',
  ],
  'apps/api/src/modules/idp/approval-adapter.ts#stageOf': ['apps/api/src/modules/idp/plan-store.ts#loadStage'],
  'apps/api/src/modules/idp/cascade-audit.ts#auditContents': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/cascade-audit.ts#auditGoalChildren': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#scoped',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/competency.ts#competencyCandidates': ['#provider'],
  'apps/api/src/modules/idp/employment-source.ts#sourceRecordVisible': [
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/visibility.ts#isEmploymentRecordVisible',
    'apps/api/src/modules/idp/access.ts#rowsOf',
  ],
  'apps/api/src/modules/idp/execution-service.ts#addGoal': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#executorFor',
    '#finish',
    '#indicatorFor',
    '#requireGoalModule',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/execution-service.ts#addTask': [
    '#finish',
    '#goalExecutor',
    '#insertTask',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/execution-service.ts#candidates': [
    '#libraryCandidates',
    '#moduleOf',
    '#requireGoalModule',
    'apps/api/src/modules/idp/plan-access.ts#requireExecutor',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
  ],
  'apps/api/src/modules/idp/execution-service.ts#deleteGoal': [
    'apps/api/src/modules/idp/cascade-audit.ts#auditGoalChildren',
    '#executorFor',
    '#finish',
    '#goalOf',
    '#recheckExecutor',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/execution-service.ts#deleteTask': [
    '#finish',
    '#goalExecutor',
    '#taskOf',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/execution-service.ts#executorFor': [
    '#moduleOf',
    'apps/api/src/modules/idp/plan-access.ts#requireExecutor',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/write-support.ts#requireRevision',
  ],
  'apps/api/src/modules/idp/execution-service.ts#finish': [
    'apps/api/src/modules/idp/plan-store.ts#bumpPlan',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/execution-service.ts#goalExecutor': [
    '#executorFor',
    '#goalOf',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
  ],
  'apps/api/src/modules/idp/execution-service.ts#goalOf': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/execution-service.ts#indicatorFor': [
    '#libraryCandidates',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/execution-service.ts#insertTask': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/execution-service.ts#libraryCandidates': [
    'apps/api/src/modules/idp/competency.ts#competencyCandidates',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/execution-service.ts#moduleOf': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/execution-service.ts#recheckExecutor': [
    'apps/api/src/modules/idp/plan-access.ts#requireExecutor',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
  ],
  'apps/api/src/modules/idp/execution-service.ts#requireGoalModule': [
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/execution-service.ts#saveAnalysis': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/execution-service.ts#saveGoalReview': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#finish',
    '#goalExecutor',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/execution-service.ts#saveModuleContent': [
    '#CONTENT_FIELDS',
    '#executorFor',
    '#finish',
    '#saveAnalysis',
    '#saveReview',
  ],
  'apps/api/src/modules/idp/execution-service.ts#saveReview': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/execution-service.ts#taskOf': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/execution-service.ts#updateGoal': [
    '#GOAL_COLUMNS',
    '#executorFor',
    '#finish',
    '#goalOf',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/execution-service.ts#updateTask': [
    '#TASK_COLUMNS',
    '#finish',
    '#goalExecutor',
    '#taskOf',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/executor.ts#runIdpCommand': ['apps/api/src/modules/idp/access.ts#replayChecks'],
  'apps/api/src/modules/idp/input.ts#commonGoalCreate': ['#text', '#uuid'],
  'apps/api/src/modules/idp/input.ts#commonGoalPatch': ['#text'],
  'apps/api/src/modules/idp/input.ts#moduleCreate': [
    '#moduleSettings',
    '#name',
    'packages/domain/src/idp/catalog.ts#MODULE_TYPES',
  ],
  'apps/api/src/modules/idp/input.ts#modulePatch': ['#moduleSettings', '#name'],
  'apps/api/src/modules/idp/input.ts#moduleSettings': [
    '#nodeSetting',
    '#text',
    '#uuid',
    'packages/domain/src/idp/catalog.ts#COMPETENCY_SOURCES',
    'packages/domain/src/idp/catalog.ts#KEY_INFO_SOURCES',
    'packages/domain/src/idp/catalog.ts#PLAN_TIME_BASES',
    'packages/domain/src/idp/catalog.ts#REVIEW_TIME_BASES',
  ],
  'apps/api/src/modules/idp/input.ts#nodeSetting': ['#uuid'],
  'apps/api/src/modules/idp/input.ts#processCreate': ['#name', '#subProcesses', '#uuid'],
  'apps/api/src/modules/idp/input.ts#processPatch': ['#name', '#subProcesses', '#uuid'],
  'apps/api/src/modules/idp/input.ts#subProcess': [
    '#isoDate',
    '#name',
    '#uuid',
    'packages/domain/src/idp/catalog.ts#IDP_APPROVAL_TYPES',
    'packages/domain/src/idp/catalog.ts#REFERENCE_POINTS',
    'packages/domain/src/idp/catalog.ts#START_FROM',
    'packages/domain/src/idp/catalog.ts#START_MODES',
    'packages/domain/src/idp/catalog.ts#START_TIME_TYPES',
    'packages/domain/src/idp/catalog.ts#SUB_PROCESS_CATEGORIES',
  ],
  'apps/api/src/modules/idp/input.ts#subProcesses': [
    '#subProcess',
    'packages/domain/src/idp/rules.ts#MAX_SUB_PROCESSES',
  ],
  'apps/api/src/modules/idp/input.ts#templateCopy': ['#name', '#uuid'],
  'apps/api/src/modules/idp/input.ts#templateCreate': ['#name', '#text', '#uuid'],
  'apps/api/src/modules/idp/input.ts#templatePatch': ['#name', '#text', '#uuid'],
  'apps/api/src/modules/idp/intervention-service.ts#auditIntervention': [
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#eachPlan': [
    '#notOwnPlan',
    '#receiptOf',
    'apps/api/src/modules/idp/plan-access.ts#hrSees',
    'apps/api/src/modules/idp/plan-store.ts#loadPlanRow',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#issueTasks': [
    'apps/api/src/modules/idp/access.ts#accessOf',
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/access.ts#viewable',
    'apps/api/src/modules/idp/execution-service.ts#insertTask',
    '#ISSUE_SOURCE_FIELDS',
    '#hiddenGoal',
    '#notActive',
    'apps/api/src/modules/idp/plan-access.ts#hrSees',
    'apps/api/src/modules/idp/plan-store.ts#bumpPlan',
    'apps/api/src/modules/idp/plan-store.ts#loadPlanRow',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#jumpPlan': [
    'apps/api/src/modules/approval/actions.ts#adminAct',
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#auditIntervention',
    '#hrApproval',
    '#runningInstance',
    'apps/api/src/modules/idp/plan-service.ts#lockPlanForHr',
    'apps/api/src/modules/idp/plan-store.ts#bumpPlan',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#notActive': ['apps/api/src/modules/idp/write-support.ts#conflict'],
  'apps/api/src/modules/idp/intervention-service.ts#notOwnPlan': [
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#requireTargetInScope': [
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
    '#targetHidden',
    'apps/api/src/modules/idp/plan-access.ts#employeeInScope',
    'apps/api/src/modules/idp/plan-mentor.ts#isPlanMentor',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#runningInstance': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#runningStage',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#runningStage': [
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#startNextStages': [
    '#actorOf',
    '#eachPlan',
    '#notActive',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/stage-service.ts#endRunningStage',
    'apps/api/src/modules/idp/stage-service.ts#openStage',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'packages/domain/src/idp/plan-rules.ts#nextOpenableStage',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#terminatePlans': [
    '#actorOf',
    '#auditIntervention',
    '#eachPlan',
    '#notActive',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/stage-service.ts#cancelStageInstance',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#transferPlan': [
    'apps/api/src/modules/approval/actions.ts#adminAct',
    'apps/api/src/modules/approval/store.ts#loadTasks',
    '#auditIntervention',
    '#hrApproval',
    '#requireTargetInScope',
    '#runningInstance',
    '#targetHidden',
    'apps/api/src/modules/idp/plan-mentor.ts#foldMentorFailure',
    'apps/api/src/modules/idp/plan-service.ts#lockPlanForHr',
    'apps/api/src/modules/idp/plan-store.ts#bumpPlan',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail',
    'apps/api/src/modules/idp/write-support.ts#invalid',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/intervention-service.ts#urgePlans': [
    'apps/api/src/modules/approval/actions.ts#urgeAsAdmin',
    '#auditIntervention',
    '#eachPlan',
    '#hrApproval',
    '#runningStage',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/key-info-routes.ts#ROUTES': [
    'apps/api/src/modules/idp/plan-input.ts#careerCreate',
    'apps/api/src/modules/idp/plan-input.ts#careerPatch',
    'apps/api/src/modules/idp/plan-input.ts#tutorshipCreate',
    'apps/api/src/modules/idp/plan-input.ts#tutorshipPatch',
    'apps/api/src/modules/idp/plan-input.ts#workShiftCreate',
    'apps/api/src/modules/idp/plan-input.ts#workShiftPatch',
  ],
  'apps/api/src/modules/idp/key-info-routes.ts#registerReads': [
    'apps/api/src/modules/idp/access.ts#idpContext',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#listEnvelope',
    'apps/api/src/modules/idp/access.ts#project',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    '#BASE',
    'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO',
    'apps/api/src/modules/idp/key-info-scope.ts#keyInfoColumn',
    'apps/api/src/modules/idp/key-info-scope.ts#keyInfoScopeSql',
    'apps/api/src/modules/idp/key-info-service.ts#inScope',
    'apps/api/src/modules/idp/key-info-service.ts#listKeyInfo',
    'apps/api/src/modules/idp/key-info-service.ts#loadKeyInfo',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/key-info-routes.ts#registerWrites': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    '#BASE',
    '#respondKeyInfo',
    '#stillInScope',
    'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO',
    'apps/api/src/modules/idp/key-info-service.ts#createKeyInfo',
    'apps/api/src/modules/idp/key-info-service.ts#deleteKeyInfo',
    'apps/api/src/modules/idp/key-info-service.ts#updateKeyInfo',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/key-info-routes.ts#respondKeyInfo': [
    'apps/api/src/modules/idp/access.ts#project',
    'apps/api/src/modules/idp/access.ts#projectionOf',
  ],
  'apps/api/src/modules/idp/key-info-routes.ts#stillInScope': [
    'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO',
    'apps/api/src/modules/idp/key-info-service.ts#inScope',
    'apps/api/src/modules/idp/key-info-service.ts#loadKeyInfo',
  ],
  'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO': ['#dated'],
  'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO_KINDS': ['#KEY_INFO'],
  'apps/api/src/modules/idp/key-info-scope.ts#keyInfoScopeSql': [
    '#positionOrg',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/idp/key-info-service.ts#cast': ['#UUID_COLUMNS'],
  'apps/api/src/modules/idp/key-info-service.ts#createKeyInfo': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#auditAnchor',
    '#cast',
    '#guarded',
    '#loadKeyInfo',
    '#requireInScope',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#created',
  ],
  'apps/api/src/modules/idp/key-info-service.ts#deleteKeyInfo': [
    '#auditAnchor',
    '#loadKeyInfo',
    '#requireInScope',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#requireRevision',
  ],
  'apps/api/src/modules/idp/key-info-service.ts#guarded': ['apps/api/src/modules/idp/write-support.ts#conflict'],
  'apps/api/src/modules/idp/key-info-service.ts#inScope': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/key-info-scope.ts#keyInfoScopeSql',
  ],
  'apps/api/src/modules/idp/key-info-service.ts#listKeyInfo': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#selectList',
  ],
  'apps/api/src/modules/idp/key-info-service.ts#loadKeyInfo': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#selectList',
  ],
  'apps/api/src/modules/idp/key-info-service.ts#requireInScope': ['#inScope'],
  'apps/api/src/modules/idp/key-info-service.ts#updateKeyInfo': [
    '#auditAnchor',
    '#cast',
    '#guarded',
    '#loadKeyInfo',
    '#requireInScope',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#requireRevision',
  ],
  'apps/api/src/modules/idp/plan-access.ts#employeeInScope': [
    'apps/api/src/modules/permission/module-access.ts#scopeAllowsInTransaction',
  ],
  'apps/api/src/modules/idp/plan-access.ts#hrSees': ['#employeeInScope'],
  'apps/api/src/modules/idp/plan-access.ts#nodeButtons': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/plan-access.ts#participation': [
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
    'apps/api/src/modules/idp/plan-store.ts#pendingNodeOf',
  ],
  'apps/api/src/modules/idp/plan-access.ts#requireExecutor': ['#denied', '#hrSees', '#nodeButtons', '#participation'],
  'apps/api/src/modules/idp/plan-access.ts#requireViewer': ['#hrSees', '#participation'],
  'apps/api/src/modules/idp/plan-input.ts#batchItems': ['#items', '#text'],
  'apps/api/src/modules/idp/plan-input.ts#careerCreate': ['#DATE_ORDER', '#ordered', '#span', '#text', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#careerPatch': ['#isoDate', '#text', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#goalCreate': ['#DATE_ORDER', '#goalFields', '#ordered', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#goalFields': ['#isoDate', '#text'],
  'apps/api/src/modules/idp/plan-input.ts#goalPatch': ['#DATE_ORDER', '#goalFields', '#ordered'],
  'apps/api/src/modules/idp/plan-input.ts#goalReview': ['#text'],
  'apps/api/src/modules/idp/plan-input.ts#items': ['#MAX_BATCH', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#jump': ['#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#moduleContent': ['#text'],
  'apps/api/src/modules/idp/plan-input.ts#planCreate': [
    '#DATE_ORDER',
    '#isoDate',
    '#ordered',
    '#uuid',
    'packages/domain/src/idp/catalog.ts#TUTOR_ROLES',
  ],
  'apps/api/src/modules/idp/plan-input.ts#planPatch': [
    '#DATE_ORDER',
    '#isoDate',
    '#ordered',
    '#uuid',
    'packages/domain/src/idp/catalog.ts#TUTOR_ROLES',
  ],
  'apps/api/src/modules/idp/plan-input.ts#span': ['#isoDate'],
  'apps/api/src/modules/idp/plan-input.ts#startNext': ['#items', 'packages/domain/src/idp/catalog.ts#START_NEXT_MODES'],
  'apps/api/src/modules/idp/plan-input.ts#taskCreate': ['#DATE_ORDER', '#ordered', '#taskFields'],
  'apps/api/src/modules/idp/plan-input.ts#taskFields': ['#isoDate', '#text', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#taskIssue': ['#DATE_ORDER', '#items', '#ordered', '#taskFields', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#taskPatch': ['#DATE_ORDER', '#ordered', '#taskFields'],
  'apps/api/src/modules/idp/plan-input.ts#transfer': ['#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#tutorshipCreate': ['#DATE_ORDER', '#ordered', '#span', '#text', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#tutorshipPatch': ['#isoDate', '#text', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#workShiftCreate': ['#DATE_ORDER', '#ordered', '#span', '#uuid'],
  'apps/api/src/modules/idp/plan-input.ts#workShiftPatch': ['#isoDate', '#uuid'],
  'apps/api/src/modules/idp/plan-mentor.ts#isPlanMentor': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/access.ts#viewable',
    '#TUTORSHIP_FIELDS',
  ],
  'apps/api/src/modules/idp/plan-mentor.ts#isStageMentor': [
    '#isPlanMentor',
    'apps/api/src/modules/idp/plan-store.ts#loadPlanRow',
    'apps/api/src/modules/idp/plan-store.ts#loadStage',
  ],
  'apps/api/src/modules/idp/plan-mentor.ts#mentorSourcesOf': ['apps/api/src/modules/idp/access.ts#projectionOf'],
  'apps/api/src/modules/idp/plan-routes.ts#baseContext': ['apps/api/src/tenant-context.ts#tenantOf'],
  'apps/api/src/modules/idp/plan-routes.ts#goalModule': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/plan-access.ts#requireViewer',
    'apps/api/src/modules/idp/plan-store.ts#loadPlanRow',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#hrScopeOf': [
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/idp/access.ts#idpScope',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#planCommand': ['apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE'],
  'apps/api/src/modules/idp/plan-routes.ts#receiptsNow': [
    'apps/api/src/modules/idp/plan-access.ts#hrSees',
    'apps/api/src/modules/idp/plan-store.ts#loadPlanRow',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#registerContentRoutes': [
    'apps/api/src/modules/idp/execution-service.ts#addTask',
    'apps/api/src/modules/idp/execution-service.ts#deleteTask',
    'apps/api/src/modules/idp/execution-service.ts#saveGoalReview',
    'apps/api/src/modules/idp/execution-service.ts#saveModuleContent',
    'apps/api/src/modules/idp/execution-service.ts#updateTask',
    'apps/api/src/modules/idp/plan-input.ts#goalReview',
    'apps/api/src/modules/idp/plan-input.ts#moduleContent',
    'apps/api/src/modules/idp/plan-input.ts#taskCreate',
    'apps/api/src/modules/idp/plan-input.ts#taskPatch',
    '#BASE',
    '#goalModule',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#registerGoalRoutes': [
    'apps/api/src/modules/idp/execution-service.ts#GOAL_DELETE_BUTTONS',
    'apps/api/src/modules/idp/execution-service.ts#addGoal',
    'apps/api/src/modules/idp/execution-service.ts#candidates',
    'apps/api/src/modules/idp/execution-service.ts#deleteGoal',
    'apps/api/src/modules/idp/execution-service.ts#updateGoal',
    'apps/api/src/modules/idp/plan-input.ts#goalCreate',
    'apps/api/src/modules/idp/plan-input.ts#goalPatch',
    '#BASE',
    '#baseContext',
    '#goalModule',
    '#hrScopeOf',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#registerInterventions': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    'apps/api/src/modules/idp/intervention-service.ts#issueTasks',
    'apps/api/src/modules/idp/intervention-service.ts#jumpPlan',
    'apps/api/src/modules/idp/intervention-service.ts#startNextStages',
    'apps/api/src/modules/idp/intervention-service.ts#terminatePlans',
    'apps/api/src/modules/idp/intervention-service.ts#transferPlan',
    'apps/api/src/modules/idp/intervention-service.ts#urgePlans',
    'apps/api/src/modules/idp/plan-input.ts#batchItems',
    'apps/api/src/modules/idp/plan-input.ts#jump',
    'apps/api/src/modules/idp/plan-input.ts#startNext',
    'apps/api/src/modules/idp/plan-input.ts#taskIssue',
    'apps/api/src/modules/idp/plan-input.ts#transfer',
    '#BASE',
    '#planCommand',
    '#receiptsNow',
    '#respondPlan',
    '#stillVisible',
    '#transferScope',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#registerInterventions>batches': [
    'apps/api/src/modules/idp/intervention-service.ts#startNextStages',
    'apps/api/src/modules/idp/intervention-service.ts#terminatePlans',
    'apps/api/src/modules/idp/intervention-service.ts#urgePlans',
    'apps/api/src/modules/idp/plan-input.ts#batchItems',
    'apps/api/src/modules/idp/plan-input.ts#startNext',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#respondPlan': ['#showPlan'],
  'apps/api/src/modules/idp/plan-routes.ts#route:DELETE /api/tenant/idp/plans/:id': [
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    'apps/api/src/modules/idp/plan-access.ts#hrSees',
    '#BASE',
    '#planCommand',
    'apps/api/src/modules/idp/plan-service.ts#deletePlan',
    'apps/api/src/modules/idp/plan-view.ts#planProjections',
    'apps/api/src/modules/idp/plan-view.ts#presentPlan',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:DELETE /api/tenant/idp/plans/:id/goals/:goalId': [
    'apps/api/src/modules/idp/execution-service.ts#GOAL_DELETE_BUTTONS',
    'apps/api/src/modules/idp/execution-service.ts#deleteGoal',
    '#goalModule',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:DELETE /api/tenant/idp/plans/:id/goals/:goalId/tasks/:taskId': [
    'apps/api/src/modules/idp/execution-service.ts#deleteTask',
    '#goalModule',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:GET /api/tenant/idp/my-plans': [
    'apps/api/src/modules/approval/resolver.ts#personOfUser',
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#BASE',
    '#baseContext',
    '#summaries',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:GET /api/tenant/idp/plans': [
    'apps/api/src/modules/idp/access.ts#idpContext',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#listEnvelope',
    'apps/api/src/modules/idp/access.ts#project',
    '#BASE',
    '#statusQuery',
    '#summaries',
    'apps/api/src/modules/idp/plan-view.ts#planListProjections',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:GET /api/tenant/idp/plans/:id': [
    '#BASE',
    '#baseContext',
    '#hrScopeOf',
    '#respondPlan',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:GET /api/tenant/idp/plans/:id/competency-candidates': [
    'apps/api/src/modules/idp/execution-service.ts#candidates',
    '#baseContext',
    '#hrScopeOf',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:PATCH /api/tenant/idp/plans/:id': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    'apps/api/src/modules/idp/plan-input.ts#planPatch',
    '#BASE',
    '#planCommand',
    '#respondPlan',
    '#stillVisible',
    'apps/api/src/modules/idp/plan-service.ts#carrySources',
    'apps/api/src/modules/idp/plan-service.ts#updatePlan',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:PATCH /api/tenant/idp/plans/:id/goals/:goalId': [
    'apps/api/src/modules/idp/execution-service.ts#updateGoal',
    'apps/api/src/modules/idp/plan-input.ts#goalPatch',
    '#goalModule',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:PATCH /api/tenant/idp/plans/:id/goals/:goalId/tasks/:taskId': [
    'apps/api/src/modules/idp/execution-service.ts#updateTask',
    'apps/api/src/modules/idp/plan-input.ts#taskPatch',
    '#goalModule',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:POST /api/tenant/idp/plans': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    'apps/api/src/modules/idp/plan-input.ts#planCreate',
    '#BASE',
    '#planCommand',
    '#respondPlan',
    '#stillVisible',
    '#templateCheck',
    'apps/api/src/modules/idp/plan-service.ts#carrySources',
    'apps/api/src/modules/idp/plan-service.ts#createPlan',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:POST /api/tenant/idp/plans/:id/goals': [
    'apps/api/src/modules/idp/execution-service.ts#addGoal',
    'apps/api/src/modules/idp/plan-input.ts#goalCreate',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:POST /api/tenant/idp/plans/:id/goals/:goalId/tasks': [
    'apps/api/src/modules/idp/execution-service.ts#addTask',
    'apps/api/src/modules/idp/plan-input.ts#taskCreate',
    '#goalModule',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:POST /api/tenant/idp/plans/:id/jump': [
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    'apps/api/src/modules/idp/intervention-service.ts#jumpPlan',
    'apps/api/src/modules/idp/plan-input.ts#jump',
    '#BASE',
    '#planCommand',
    '#respondPlan',
    '#stillVisible',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:POST /api/tenant/idp/plans/:id/start': [
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    '#BASE',
    '#planCommand',
    '#respondPlan',
    '#stillVisible',
    'apps/api/src/modules/idp/plan-service.ts#startPlan',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:POST /api/tenant/idp/plans/:id/transfer': [
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    'apps/api/src/modules/idp/intervention-service.ts#transferPlan',
    'apps/api/src/modules/idp/plan-input.ts#transfer',
    '#BASE',
    '#planCommand',
    '#respondPlan',
    '#stillVisible',
    '#transferScope',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:POST /api/tenant/idp/plans/tasks/issue': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    'apps/api/src/modules/idp/intervention-service.ts#issueTasks',
    'apps/api/src/modules/idp/plan-input.ts#taskIssue',
    '#BASE',
    '#planCommand',
    '#stillVisible',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#revision',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:PUT /api/tenant/idp/plans/:id/goals/:goalId/review': [
    'apps/api/src/modules/idp/execution-service.ts#saveGoalReview',
    'apps/api/src/modules/idp/plan-input.ts#goalReview',
    '#goalModule',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#route:PUT /api/tenant/idp/plans/:id/modules/:moduleId/content': [
    'apps/api/src/modules/idp/execution-service.ts#saveModuleContent',
    'apps/api/src/modules/idp/plan-input.ts#moduleContent',
    '#BASE',
    '#runExecutorWrite',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#runExecutorWrite': [
    'apps/api/src/modules/idp/execution-service.ts#recheckExecutor',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
    '#baseContext',
    '#hrScopeOf',
    '#planCommand',
    '#respondPlan',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#showPlan': [
    'apps/api/src/modules/idp/plan-access.ts#requireViewer',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail',
    'apps/api/src/modules/idp/plan-view.ts#planProjections',
    'apps/api/src/modules/idp/plan-view.ts#presentPlan',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#statusQuery': ['packages/domain/src/idp/catalog.ts#PLAN_STATUSES'],
  'apps/api/src/modules/idp/plan-routes.ts#stillVisible': [
    'apps/api/src/modules/idp/plan-access.ts#hrSees',
    'apps/api/src/modules/idp/plan-store.ts#loadPlanRow',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#summaries': [
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-view.ts#currentStageShown',
    'apps/api/src/modules/idp/plan-view.ts#stageSourcesOf',
    'apps/api/src/modules/idp/plan-view.ts#stageViews',
    'apps/api/src/modules/idp/plan-view.ts#stagesShown',
    'packages/domain/src/idp/plan-rules.ts#currentStageName',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#templateCheck': [
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#requireReadable',
    'apps/api/src/modules/idp/access.ts#rowsOf',
  ],
  'apps/api/src/modules/idp/plan-routes.ts#transferScope': [
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/plan-mentor.ts#mentorSourcesOf',
  ],
  'apps/api/src/modules/idp/plan-service.ts#carryCommonGoals': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#sees',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/plan-service.ts#carrySources': [
    '#objectProjection',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/idp/plan-service.ts#createPlan': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#carryCommonGoals',
    '#detailOf',
    '#requireEmployeeInScope',
    '#requirePublishedTemplate',
    '#resolveTutor',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#planRecord',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/plan-service.ts#deletePlan': [
    'apps/api/src/modules/idp/access.ts#requireNestedWrite',
    'apps/api/src/modules/idp/cascade-audit.ts#auditContents',
    'apps/api/src/modules/idp/cascade-audit.ts#auditGoalChildren',
    '#actorOf',
    '#lockPlanForHr',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail',
    'apps/api/src/modules/idp/plan-view.ts#planRecord',
    'apps/api/src/modules/idp/stage-service.ts#cancelStageInstance',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/plan-service.ts#detailOf': [
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/plan-service.ts#lockPlanForHr': [
    'apps/api/src/modules/idp/plan-access.ts#hrSees',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/write-support.ts#requireRevision',
  ],
  'apps/api/src/modules/idp/plan-service.ts#objectProjection': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
  ],
  'apps/api/src/modules/idp/plan-service.ts#orgRoleOf': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/plan-service.ts#orgVisible': [
    'apps/api/src/modules/permission/module-access.ts#scopeAllows',
    'apps/api/src/modules/permission/scope-audit.ts#creatorOf',
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/idp/plan-service.ts#requireEmployeeInScope': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/plan-access.ts#employeeInScope',
  ],
  'apps/api/src/modules/idp/plan-service.ts#requirePublishedTemplate': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/plan-service.ts#resolveTutor': [
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'apps/api/src/modules/idp/employment-source.ts#sourceRecordVisible',
    '#orgRoleOf',
    '#orgVisible',
    '#sees',
    '#unresolved',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/plan-service.ts#startPlan': [
    '#actorOf',
    '#detailOf',
    '#lockPlanForHr',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/stage-service.ts#openStage',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/plan-service.ts#unresolved': ['apps/api/src/modules/idp/write-support.ts#conflict'],
  'apps/api/src/modules/idp/plan-service.ts#updatePlan': [
    '#detailOf',
    '#isActive',
    '#lockPlanForHr',
    '#resolveTutor',
    'apps/api/src/modules/idp/plan-store.ts#requirePlanRow',
    'apps/api/src/modules/idp/plan-view.ts#planRecord',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/plan-store.ts#currentNodes': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/plan-store.ts#loadStage': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#STAGE_COLUMNS',
    '#stage',
  ],
  'apps/api/src/modules/idp/plan-store.ts#loadStages': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#STAGE_COLUMNS',
    '#stage',
  ],
  'apps/api/src/modules/idp/plan-store.ts#pendingNodeOf': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/plan-store.ts#requirePlanRow': ['#loadPlanRow'],
  'apps/api/src/modules/idp/plan-view.ts#configScopes': [
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
  ],
  'apps/api/src/modules/idp/plan-view.ts#configVisible': [
    'apps/api/src/modules/idp/access.ts#accessOf',
    'apps/api/src/modules/idp/access.ts#rowsOf',
  ],
  'apps/api/src/modules/idp/plan-view.ts#configuredBlocks': ['#BLOCK_KINDS'],
  'apps/api/src/modules/idp/plan-view.ts#currentStageShown': [
    '#sees',
    'packages/domain/src/idp/catalog.ts#IMPROVING_STAGE_NAME',
  ],
  'apps/api/src/modules/idp/plan-view.ts#dueBasisOf': ['#REFERENCE_BASIS'],
  'apps/api/src/modules/idp/plan-view.ts#employmentEffective': [
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
  ],
  'apps/api/src/modules/idp/plan-view.ts#employmentSources': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/idp/plan-view.ts#employmentVisible': [
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'apps/api/src/modules/idp/employment-source.ts#sourceRecordVisible',
    '#sees',
  ],
  'apps/api/src/modules/idp/plan-view.ts#keyInfoShown': [
    'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO',
    'apps/api/src/modules/idp/key-info-service.ts#inScope',
    '#KIND_KEYS',
    '#configuredBlocks',
    '#listOf',
  ],
  'apps/api/src/modules/idp/plan-view.ts#listOf': ['apps/api/src/modules/idp/access.ts#project'],
  'apps/api/src/modules/idp/plan-view.ts#loadContents': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/plan-view.ts#loadGoals': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/plan-view.ts#loadKeyInfo': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'packages/domain/src/idp/plan-rules.ts#periodsIntersect',
  ],
  'apps/api/src/modules/idp/plan-view.ts#loadPlanDetail': [
    'apps/api/src/modules/idp/plan-store.ts#currentNodes',
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    '#loadContents',
    '#loadGoals',
    '#loadKeyInfo',
    '#planRecord',
    '#stageViews',
    '#templateModules',
    'packages/domain/src/idp/plan-rules.ts#currentStageName',
  ],
  'apps/api/src/modules/idp/plan-view.ts#planListProjections': [
    'apps/api/src/modules/idp/access.ts#projectionOf',
    '#configScopes',
    '#employmentSources',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/plan-view.ts#planProjections': [
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO_KINDS',
    '#PROJECTED',
    '#configScopes',
    '#employmentSources',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/idp/plan-view.ts#presentPlan': [
    'apps/api/src/modules/idp/access.ts#project',
    'apps/api/src/modules/idp/plan-access.ts#nodeButtons',
    '#PARTICIPANT_PLAN_KEYS',
    '#configVisible',
    '#currentStageShown',
    '#keyInfoConfigVisible',
    '#keyInfoShown',
    '#listOf',
    '#stageSourcesOf',
    '#stagesShown',
  ],
  'apps/api/src/modules/idp/plan-view.ts#stageSourcesOf': ['#configVisible'],
  'apps/api/src/modules/idp/plan-view.ts#stageViews': [
    '#dueBasisOf',
    '#employmentEffective',
    'packages/domain/src/idp/plan-rules.ts#stageDueDate',
  ],
  'apps/api/src/modules/idp/plan-view.ts#stagesShown': [
    '#employmentVisible',
    '#sees',
    'packages/domain/src/idp/catalog.ts#RULE_TEXT_SOURCES',
  ],
  'apps/api/src/modules/idp/plan-view.ts#templateModules': [
    'apps/api/src/modules/idp/read-model.ts#loadModuleRows',
    'apps/api/src/modules/idp/read-model.ts#loadNodeSettings',
    'apps/api/src/modules/idp/read-model.ts#moduleView',
  ],
  'apps/api/src/modules/idp/process-service.ts#applySubProcessChanges': [
    '#SEQ_SHIFT',
    '#insertSubProcesses',
    '#subAudit',
    'apps/api/src/modules/idp/read-model.ts#loadSubProcessRows',
    'apps/api/src/modules/idp/read-model.ts#subProcessView',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/process-service.ts#changedFields': [
    'packages/domain/src/idp/catalog.ts#SUB_PROCESS_FIELDS',
  ],
  'apps/api/src/modules/idp/process-service.ts#checkSubProcessChanges': [
    'apps/api/src/modules/idp/access.ts#requireNestedWrite',
    '#fieldsOf',
    '#hasNodeSettings',
    '#keys',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'apps/api/src/modules/idp/write-support.ts#requireApprovalProcess',
  ],
  'apps/api/src/modules/idp/process-service.ts#createProcess': [
    'apps/api/src/modules/idp/access.ts#requireCreatable',
    'apps/api/src/modules/idp/access.ts#requireNestedWrite',
    '#fieldsOf',
    '#insertSubProcesses',
    '#processRecord',
    '#subAudit',
    '#validateRules',
    'apps/api/src/modules/idp/read-model.ts#loadProcess',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#created',
    'apps/api/src/modules/idp/write-support.ts#invalid',
    'apps/api/src/modules/idp/write-support.ts#requireApprovalProcess',
    'apps/api/src/modules/idp/write-support.ts#requireOrg',
  ],
  'apps/api/src/modules/idp/process-service.ts#deleteProcess': [
    'apps/api/src/modules/idp/access.ts#requireNestedWrite',
    '#lockProcess',
    '#processRecord',
    '#subAudit',
    'apps/api/src/modules/idp/read-model.ts#loadProcess',
    'apps/api/src/modules/idp/read-model.ts#processReferenced',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/process-service.ts#insertSubProcesses': [
    '#fieldsOf',
    'apps/api/src/modules/idp/write-support.ts#created',
  ],
  'apps/api/src/modules/idp/process-service.ts#lockProcess': [
    'apps/api/src/modules/idp/access.ts#requireEditable',
    'apps/api/src/modules/idp/write-support.ts#requireRevision',
  ],
  'apps/api/src/modules/idp/process-service.ts#planSubProcesses': [
    '#changedFields',
    '#fieldsOf',
    '#rowFields',
    'apps/api/src/modules/idp/write-support.ts#invalid',
  ],
  'apps/api/src/modules/idp/process-service.ts#replaceSubProcesses': [
    '#applySubProcessChanges',
    '#checkSubProcessChanges',
    '#keys',
    '#planSubProcesses',
    '#validateRules',
    'apps/api/src/modules/idp/read-model.ts#loadSubProcessRows',
    'apps/api/src/modules/idp/read-model.ts#processReferenced',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'packages/domain/src/idp/rules.ts#referencedProcessChangeViolation',
  ],
  'apps/api/src/modules/idp/process-service.ts#updateProcess': [
    'apps/api/src/modules/idp/access.ts#requireCreatable',
    '#lockProcess',
    '#processRecord',
    '#replaceSubProcesses',
    'apps/api/src/modules/idp/read-model.ts#loadProcess',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#bumped',
    'apps/api/src/modules/idp/write-support.ts#requireOrg',
  ],
  'apps/api/src/modules/idp/process-service.ts#validateRules': [
    'apps/api/src/modules/idp/write-support.ts#invalid',
    'packages/domain/src/idp/rules.ts#startRuleViolation',
  ],
  'apps/api/src/modules/idp/read-model.ts#listProcesses': ['#processViews'],
  'apps/api/src/modules/idp/read-model.ts#listTemplates': ['#templateSummary'],
  'apps/api/src/modules/idp/read-model.ts#loadProcess': ['#processViews'],
  'apps/api/src/modules/idp/read-model.ts#loadTemplate': ['#templateView'],
  'apps/api/src/modules/idp/read-model.ts#moduleView': [
    'packages/domain/src/idp/catalog.ts#keyInfoBlocksOf',
    'packages/domain/src/idp/rules.ts#nodeButtonsOf',
  ],
  'apps/api/src/modules/idp/read-model.ts#processView': ['#iso', '#subProcessView'],
  'apps/api/src/modules/idp/read-model.ts#processViews': ['#processView'],
  'apps/api/src/modules/idp/read-model.ts#subProcessView': ['packages/domain/src/idp/rules.ts#startRuleText'],
  'apps/api/src/modules/idp/read-model.ts#templateSummary': ['#iso'],
  'apps/api/src/modules/idp/read-model.ts#templateView': [
    '#loadCommonGoals',
    '#loadModuleRows',
    '#loadNodeSettings',
    '#moduleView',
    '#templateSummary',
    'apps/api/src/modules/idp/references.ts#templateReferencedByPlans',
  ],
  'apps/api/src/modules/idp/references.ts#templateReferencedByPlans': ['#guard'],
  'apps/api/src/modules/idp/routes.ts#approvalCandidates': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'packages/domain/src/idp/catalog.ts#IDP_APPROVAL_TYPES',
  ],
  'apps/api/src/modules/idp/routes.ts#currentEditable': [
    'apps/api/src/modules/idp/access.ts#requireEditable',
    '#currentAnchor',
  ],
  'apps/api/src/modules/idp/routes.ts#currentReadable': [
    'apps/api/src/modules/idp/access.ts#requireReadable',
    '#currentAnchor',
  ],
  'apps/api/src/modules/idp/routes.ts#editable': ['#currentEditable', '#currentReadable'],
  'apps/api/src/modules/idp/routes.ts#processPresenter': [
    'apps/api/src/modules/idp/access.ts#project',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    '#subProcessShown',
  ],
  'apps/api/src/modules/idp/routes.ts#processScopeFor': [
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/idp/access.ts#idpScope',
  ],
  'apps/api/src/modules/idp/routes.ts#registerTemplateActions': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    'apps/api/src/modules/idp/input.ts#templateCopy',
    '#BASE',
    '#currentReadable',
    '#editable',
    '#processScopeFor',
    '#templateWriter',
    '#writeContext',
    'apps/api/src/modules/idp/template-service.ts#copyTemplate',
    'apps/api/src/modules/idp/template-service.ts#setTemplateStatus',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#registerTemplatePartRoutes': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/idp/input.ts#commonGoalCreate',
    'apps/api/src/modules/idp/input.ts#commonGoalPatch',
    'apps/api/src/modules/idp/input.ts#moduleCreate',
    'apps/api/src/modules/idp/input.ts#modulePatch',
    '#BASE',
    '#currentEditable',
    '#runIdpWrite',
    '#templatePresenter',
    'apps/api/src/modules/idp/template-service.ts#addCommonGoal',
    'apps/api/src/modules/idp/template-service.ts#addModule',
    'apps/api/src/modules/idp/template-service.ts#deleteCommonGoal',
    'apps/api/src/modules/idp/template-service.ts#deleteModule',
    'apps/api/src/modules/idp/template-service.ts#updateCommonGoal',
    'apps/api/src/modules/idp/template-service.ts#updateModule',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#registerTemplatePartRoutes>write': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    '#currentEditable',
    '#runIdpWrite',
    '#templatePresenter',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#requireSubProcessInputVisible': [
    'apps/api/src/modules/idp/access.ts#projectionOf',
    'apps/api/src/modules/idp/access.ts#viewable',
    'packages/domain/src/idp/catalog.ts#SUB_PROCESS_FIELDS',
  ],
  'apps/api/src/modules/idp/routes.ts#route:DELETE /api/tenant/idp/processes/:id': [
    'apps/api/src/modules/idp/access.ts#requireEditable',
    'apps/api/src/modules/idp/process-service.ts#deleteProcess',
    '#anchorOf',
    '#processPresenter',
    '#runIdpWrite',
    '#writeContext',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#route:DELETE /api/tenant/idp/templates/:id': [
    'apps/api/src/modules/idp/access.ts#requireEditable',
    '#anchorOf',
    '#writeContext',
    'apps/api/src/modules/idp/template-service.ts#deleteTemplate',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#route:GET /api/tenant/idp/approval-processes': [
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/modules/idp/access.ts#idpContext',
    '#BASE',
    '#approvalCandidates',
    '#enumQuery',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'packages/domain/src/idp/catalog.ts#IDP_APPROVAL_TYPES',
  ],
  'apps/api/src/modules/idp/routes.ts#route:GET /api/tenant/idp/processes': [
    'apps/api/src/modules/idp/access.ts#idpContext',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#listEnvelope',
    'apps/api/src/modules/idp/read-model.ts#listProcesses',
    '#booleanQuery',
    '#processPresenter',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/public-down.ts#readableSql',
  ],
  'apps/api/src/modules/idp/routes.ts#route:GET /api/tenant/idp/processes/:id': [
    'apps/api/src/modules/idp/access.ts#idpContext',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#requireReadable',
    'apps/api/src/modules/idp/read-model.ts#loadProcess',
    '#anchorOf',
    '#processPresenter',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#route:GET /api/tenant/idp/templates': [
    'apps/api/src/modules/idp/access.ts#idpContext',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#listEnvelope',
    'apps/api/src/modules/idp/read-model.ts#listTemplates',
    '#enumQuery',
    '#templateSummaryPresenter',
    '#uuidQuery',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/public-down.ts#readableSql',
  ],
  'apps/api/src/modules/idp/routes.ts#route:GET /api/tenant/idp/templates/:id': [
    'apps/api/src/modules/idp/access.ts#idpContext',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#requireReadable',
    'apps/api/src/modules/idp/read-model.ts#loadTemplate',
    '#anchorOf',
    '#templatePresenter',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#route:PATCH /api/tenant/idp/processes/:id': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/input.ts#processPatch',
    'apps/api/src/modules/idp/process-service.ts#updateProcess',
    '#currentEditable',
    '#processPresenter',
    '#requireSubProcessInputVisible',
    '#runIdpWrite',
    '#writeContext',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#route:PATCH /api/tenant/idp/templates/:id': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/input.ts#templatePatch',
    '#editable',
    '#processScopeFor',
    '#writeContext',
    'apps/api/src/modules/idp/template-service.ts#updateTemplate',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#route:POST /api/tenant/idp/processes': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/input.ts#processCreate',
    'apps/api/src/modules/idp/process-service.ts#createProcess',
    '#currentEditable',
    '#processPresenter',
    '#runIdpWrite',
    '#writeContext',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
  ],
  'apps/api/src/modules/idp/routes.ts#route:POST /api/tenant/idp/templates': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/input.ts#templateCreate',
    '#editable',
    '#processScopeFor',
    '#writeContext',
    'apps/api/src/modules/idp/template-service.ts#createTemplate',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
  ],
  'apps/api/src/modules/idp/routes.ts#route:POST /api/tenant/idp/templates/:id/copy': [
    'apps/api/src/modules/idp/access.ts#checkWriteFields',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    'apps/api/src/modules/idp/input.ts#templateCopy',
    '#currentReadable',
    '#editable',
    '#processScopeFor',
    '#writeContext',
    'apps/api/src/modules/idp/template-service.ts#copyTemplate',
    'apps/api/src/modules/job/context.ts#parseBody',
    'apps/api/src/modules/job/context.ts#requireNew',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/idp/routes.ts#runIdpWrite': [
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/executor.ts#runIdpCommand',
  ],
  'apps/api/src/modules/idp/routes.ts#subProcessShown': [
    'apps/api/src/modules/idp/access.ts#project',
    'packages/domain/src/idp/catalog.ts#RULE_TEXT_SOURCES',
  ],
  'apps/api/src/modules/idp/routes.ts#templatePresenter': [
    'apps/api/src/modules/idp/access.ts#project',
    'apps/api/src/modules/idp/access.ts#projectionOf',
  ],
  'apps/api/src/modules/idp/routes.ts#templateSummaryPresenter': [
    'apps/api/src/modules/idp/access.ts#project',
    'apps/api/src/modules/idp/access.ts#projectionOf',
  ],
  'apps/api/src/modules/idp/routes.ts#templateWriter': ['#runIdpWrite', '#templatePresenter', '#warningsVisible'],
  'apps/api/src/modules/idp/routes.ts#warningsVisible': [
    'apps/api/src/modules/idp/access.ts#accessOf',
    'apps/api/src/modules/idp/access.ts#idpScope',
    'apps/api/src/modules/idp/access.ts#projectionOf',
    '#currentAnchor',
    '#sees',
  ],
  'apps/api/src/modules/idp/routes.ts#writeContext': [
    'apps/api/src/modules/idp/access.ts#idpWriteContext',
    'apps/api/src/modules/job/context.ts#revision',
  ],
  'apps/api/src/modules/idp/stage-service.ts#approvalContext': ['apps/api/src/system-actor.ts#SYSTEM_USER_ID'],
  'apps/api/src/modules/idp/stage-service.ts#approvalUnavailable': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/stage-service.ts#auditStage': [
    '#stageAudit',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/stage-service.ts#businessDate': ['packages/domain/src/tenant-time.ts#tenantLocalDate'],
  'apps/api/src/modules/idp/stage-service.ts#cancelStageInstance': [
    'apps/api/src/modules/approval/actions.ts#cancel',
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#approvalContext',
  ],
  'apps/api/src/modules/idp/stage-service.ts#endRunningStage': ['#cancelStageInstance', '#endStage'],
  'apps/api/src/modules/idp/stage-service.ts#endStage': [
    'apps/api/src/modules/idp/plan-store.ts#bumpPlan',
    '#auditStage',
    '#businessDate',
  ],
  'apps/api/src/modules/idp/stage-service.ts#onStageApproved': [
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    '#endStage',
    '#openStage',
    '#opensOnPreviousEnd',
    '#settlePlan',
  ],
  'apps/api/src/modules/idp/stage-service.ts#onStageDisapproved': [
    'apps/api/src/modules/idp/plan-store.ts#bumpPlan',
    '#auditStage',
  ],
  'apps/api/src/modules/idp/stage-service.ts#openStage': [
    'apps/api/src/modules/approval/engine.ts#startSpecified',
    'apps/api/src/modules/idp/plan-store.ts#bumpPlan',
    '#approvalContext',
    '#approvalUnavailable',
    '#auditStage',
    '#businessDate',
  ],
  'apps/api/src/modules/idp/stage-service.ts#settlePlan': [
    'apps/api/src/modules/idp/plan-store.ts#loadStages',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/template-service.ts#addCommonGoal': [
    '#finish',
    '#loadGoal',
    '#lockTemplate',
    '#nextOrder',
    '#requireGoalModule',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#created',
  ],
  'apps/api/src/modules/idp/template-service.ts#addModule': [
    '#checkGoalSettings',
    '#checkSettingKeys',
    '#defaultsOf',
    '#finish',
    '#lockTemplate',
    '#moduleColumns',
    '#moduleSnapshot',
    '#nextOrder',
    '#referenced',
    '#validateNodeSettings',
    '#writeNodeSettings',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'apps/api/src/modules/idp/write-support.ts#created',
    'packages/domain/src/idp/rules.ts#SINGLETON_MODULES',
  ],
  'apps/api/src/modules/idp/template-service.ts#allowedSettings': [
    '#GOAL_SETTINGS',
    '#REVIEW_SETTINGS',
    'packages/domain/src/idp/rules.ts#nodeButtonsOf',
  ],
  'apps/api/src/modules/idp/template-service.ts#auditCreated': [
    'apps/api/src/modules/idp/read-model.ts#loadTemplate',
    '#templateRecord',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/template-service.ts#checkCopyWritable': [
    'apps/api/src/modules/idp/access.ts#requireNestedWrite',
    'apps/api/src/modules/idp/read-model.ts#moduleView',
    '#COMMON_GOAL_COPY_FIELDS',
    '#validateNodeSettings',
  ],
  'apps/api/src/modules/idp/template-service.ts#checkGoalSettings': [
    'apps/api/src/modules/idp/write-support.ts#invalid',
  ],
  'apps/api/src/modules/idp/template-service.ts#checkSettingKeys': [
    '#allowedSettings',
    'apps/api/src/modules/idp/write-support.ts#invalid',
  ],
  'apps/api/src/modules/idp/template-service.ts#copyTemplate': [
    'apps/api/src/modules/idp/access.ts#requireCreatable',
    'apps/api/src/modules/idp/access.ts#requireReadable',
    'apps/api/src/modules/idp/read-model.ts#loadCommonGoals',
    'apps/api/src/modules/idp/read-model.ts#loadModuleRows',
    'apps/api/src/modules/idp/read-model.ts#loadNodeSettings',
    '#NAME_TAKEN',
    '#auditCreated',
    '#checkCopyWritable',
    '#requireCopyViewable',
    '#requireUsableProcess',
    '#writeNodeSettings',
    'apps/api/src/modules/idp/write-support.ts#created',
    'apps/api/src/modules/idp/write-support.ts#requireOrg',
    'apps/api/src/modules/idp/write-support.ts#unique',
  ],
  'apps/api/src/modules/idp/template-service.ts#createTemplate': [
    'apps/api/src/modules/idp/access.ts#requireCreatable',
    '#NAME_TAKEN',
    '#auditCreated',
    '#requireUsableProcess',
    'apps/api/src/modules/idp/write-support.ts#created',
    'apps/api/src/modules/idp/write-support.ts#requireOrg',
    'apps/api/src/modules/idp/write-support.ts#unique',
  ],
  'apps/api/src/modules/idp/template-service.ts#defaultsOf': ['packages/domain/src/idp/catalog.ts#KEY_INFO_SOURCES'],
  'apps/api/src/modules/idp/template-service.ts#deleteCommonGoal': [
    '#finish',
    '#loadGoal',
    '#lockTemplate',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/template-service.ts#deleteModule': [
    'apps/api/src/modules/idp/access.ts#requireNestedWrite',
    'apps/api/src/modules/idp/read-model.ts#loadCommonGoals',
    '#finish',
    '#loadModule',
    '#lockTemplate',
    '#moduleSnapshot',
    '#referenced',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/template-service.ts#deleteTemplate': [
    'apps/api/src/modules/idp/access.ts#requireNestedWrite',
    'apps/api/src/modules/idp/read-model.ts#loadTemplate',
    '#lockTemplate',
    '#referenced',
    '#templateRecord',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/template-service.ts#discardedApprovals': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/template-service.ts#finish': [
    'apps/api/src/modules/idp/read-model.ts#loadTemplate',
    'apps/api/src/modules/idp/write-support.ts#bumped',
  ],
  'apps/api/src/modules/idp/template-service.ts#keyInfoColumns': [
    'apps/api/src/modules/idp/write-support.ts#invalid',
    'packages/domain/src/idp/catalog.ts#KEY_INFO_BLOCK_FIELDS',
    'packages/domain/src/idp/catalog.ts#encodeKeyInfoBlocks',
  ],
  'apps/api/src/modules/idp/template-service.ts#loadGoal': ['apps/api/src/modules/idp/read-model.ts#loadCommonGoals'],
  'apps/api/src/modules/idp/template-service.ts#lockTemplate': [
    'apps/api/src/modules/idp/access.ts#requireEditable',
    'apps/api/src/modules/idp/write-support.ts#requireRevision',
  ],
  'apps/api/src/modules/idp/template-service.ts#moduleColumns': ['#keyInfoColumns'],
  'apps/api/src/modules/idp/template-service.ts#moduleSnapshot': [
    'apps/api/src/modules/idp/read-model.ts#loadNodeSettings',
    'apps/api/src/modules/idp/read-model.ts#moduleView',
  ],
  'apps/api/src/modules/idp/template-service.ts#nextOrder': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/template-service.ts#referenced': [
    'apps/api/src/modules/idp/references.ts#templateReferencedByPlans',
  ],
  'apps/api/src/modules/idp/template-service.ts#requireCopyViewable': [
    'apps/api/src/modules/idp/access.ts#requireViewable',
    '#COMMON_GOAL_COPY_FIELDS',
    'packages/domain/src/idp/catalog.ts#TEMPLATE_MODULE_FIELDS',
  ],
  'apps/api/src/modules/idp/template-service.ts#requireGoalModule': [
    '#loadModule',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/template-service.ts#requireUsableProcess': [
    'apps/api/src/modules/idp/access.ts#requireReadable',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/template-service.ts#setTemplateStatus': [
    'apps/api/src/modules/idp/read-model.ts#loadTemplate',
    '#discardedApprovals',
    '#lockTemplate',
    '#templateRecord',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#bumped',
    'apps/api/src/modules/idp/write-support.ts#conflict',
  ],
  'apps/api/src/modules/idp/template-service.ts#updateCommonGoal': [
    '#finish',
    '#loadGoal',
    '#lockTemplate',
    'apps/api/src/modules/idp/write-support.ts#audit',
  ],
  'apps/api/src/modules/idp/template-service.ts#updateModule': [
    '#checkGoalSettings',
    '#checkSettingKeys',
    '#finish',
    '#loadModule',
    '#lockTemplate',
    '#moduleColumns',
    '#moduleSnapshot',
    '#referenced',
    '#validateNodeSettings',
    '#writeNodeSettings',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'packages/domain/src/idp/rules.ts#EDITABLE_AFTER_REFERENCED',
  ],
  'apps/api/src/modules/idp/template-service.ts#updateTemplate': [
    'apps/api/src/modules/idp/access.ts#requireCreatable',
    'apps/api/src/modules/idp/read-model.ts#loadTemplate',
    '#NAME_TAKEN',
    '#lockTemplate',
    '#referenced',
    '#requireUsableProcess',
    '#templateRecord',
    'apps/api/src/modules/idp/write-support.ts#audit',
    'apps/api/src/modules/idp/write-support.ts#bumped',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'apps/api/src/modules/idp/write-support.ts#requireOrg',
    'apps/api/src/modules/idp/write-support.ts#unique',
  ],
  'apps/api/src/modules/idp/template-service.ts#validateNodeSettings': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    'apps/api/src/modules/idp/write-support.ts#conflict',
    'apps/api/src/modules/idp/write-support.ts#invalid',
    'packages/domain/src/idp/rules.ts#nodeButtonsOf',
  ],
  'apps/api/src/modules/idp/write-support.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/modules/idp/access.ts#IDP_AUDIT_ACTIONS',
    'apps/api/src/modules/idp/access.ts#codeOf',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/idp/write-support.ts#requireApprovalProcess': [
    'apps/api/src/modules/idp/access.ts#rowsOf',
    '#conflict',
  ],
  'apps/api/src/modules/idp/write-support.ts#requireOrg': ['apps/api/src/modules/idp/access.ts#rowsOf'],
  'apps/api/src/modules/idp/write-support.ts#unique': ['#conflict'],
};
