/**
 * 直接依赖图：区域 api-modules-qualification（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/qualification/access.ts#accessSql': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    '#column',
    '#qlReadable',
    '#qlStandardReadable',
  ],
  'apps/api/src/modules/qualification/access.ts#assertQualificationRefs': [
    '#QUALIFICATION_LABELS',
    '#REF_OBJECTS',
    '#REF_TABLES',
    '#qlViewable',
    '#rowsOf',
  ],
  'apps/api/src/modules/qualification/access.ts#checkWriteFields': [
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    '#CONTROLS',
    '#codeOf',
  ],
  'apps/api/src/modules/qualification/access.ts#codeOf': [
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
  ],
  'apps/api/src/modules/qualification/access.ts#listEnvelope': [
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/qualification/access.ts#objectFields': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#codeOf',
  ],
  'apps/api/src/modules/qualification/access.ts#qlReadable': [
    'apps/api/src/modules/permission/public-down.ts#readableSql',
    '#column',
  ],
  'apps/api/src/modules/qualification/access.ts#qlViewable': ['#OPEN_READ', '#qlReadable'],
  'apps/api/src/modules/qualification/access.ts#qualificationContext': [
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    '#codeOf',
  ],
  'apps/api/src/modules/qualification/access.ts#qualificationScope': [
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    '#codeOf',
  ],
  'apps/api/src/modules/qualification/access.ts#qualificationWriteContext': [
    'apps/api/src/modules/permission/module-route-access.ts#button',
    '#BUTTON_LEVEL',
    '#codeOf',
    '#qualificationContext',
  ],
  'apps/api/src/modules/qualification/access.ts#requireEditable': [
    '#OPEN_READ',
    '#QUALIFICATION_LABELS',
    '#requireReadable',
  ],
  'apps/api/src/modules/qualification/access.ts#requireReadable': ['#QUALIFICATION_LABELS'],
  'apps/api/src/modules/qualification/access.ts#trimQualification': [
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    '#codeOf',
  ],
  'apps/api/src/modules/qualification/candidates.ts#OWNER_OBJECTS': [
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OWNED_OBJECTS',
  ],
  'apps/api/src/modules/qualification/candidates.ts#organizationAccess': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/modules/qualification/candidates.ts#ownerObject': ['#OWNER_OBJECTS'],
  'apps/api/src/modules/qualification/candidates.ts#registerQualificationCandidates': [
    'apps/api/src/modules/permission/owner-units.ts#authorizedUnits',
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    'apps/api/src/modules/qualification/access.ts#qualificationContext',
    '#organizationAccess',
    '#ownerObject',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_APP',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/qualification/config-service.ts#asOf': ['packages/domain/src/tenant-time.ts#tenantLocalDate'],
  'apps/api/src/modules/qualification/config-service.ts#createCategory': [
    '#insertCategory',
    '#reload',
    '#replaceJobLinks',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#referenced',
  ],
  'apps/api/src/modules/qualification/config-service.ts#createCategoryClass': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#ownerOf',
    'apps/api/src/modules/qualification/store.ts#referenced',
    'apps/api/src/modules/qualification/store.ts#requireCodeAvailable',
  ],
  'apps/api/src/modules/qualification/config-service.ts#createLayer': [
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
  ],
  'apps/api/src/modules/qualification/config-service.ts#createLevel': [
    '#insertLevel',
    '#reload',
    '#replaceJobLinks',
    'apps/api/src/modules/qualification/store.ts#audit',
  ],
  'apps/api/src/modules/qualification/config-service.ts#createTargetType': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#autoCode',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#ownerOf',
    'apps/api/src/modules/qualification/store.ts#referenced',
    'apps/api/src/modules/qualification/store.ts#requireCodeAvailable',
  ],
  'apps/api/src/modules/qualification/config-service.ts#deleteCategory': [
    '#orgOf',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
  ],
  'apps/api/src/modules/qualification/config-service.ts#deleteCategoryClass': [
    '#orgOf',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
  ],
  'apps/api/src/modules/qualification/config-service.ts#deleteLayer': [
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
  ],
  'apps/api/src/modules/qualification/config-service.ts#deleteLevel': [
    '#orgOf',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
  ],
  'apps/api/src/modules/qualification/config-service.ts#deleteTargetType': [
    '#orgOf',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
  ],
  'apps/api/src/modules/qualification/config-service.ts#importCategories': [
    '#importLog',
    '#importedName',
    '#insertCategory',
    '#reload',
    '#replaceJobLinks',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#ownerOf',
    'apps/api/src/modules/qualification/store.ts#referenced',
  ],
  'apps/api/src/modules/qualification/config-service.ts#importLevels': [
    '#importLog',
    '#importedName',
    '#insertLevel',
    '#reload',
    '#replaceJobLinks',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#ownerOf',
  ],
  'apps/api/src/modules/qualification/config-service.ts#importLog': [
    'apps/api/src/audit/record.ts#recordImportLog',
    'apps/api/src/modules/qualification/access.ts#codeOf',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/qualification/config-service.ts#importedName': [
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    '#jobObject',
  ],
  'apps/api/src/modules/qualification/config-service.ts#insertCategory': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/store.ts#autoCode',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#ownerOf',
    'apps/api/src/modules/qualification/store.ts#requireCodeAvailable',
  ],
  'apps/api/src/modules/qualification/config-service.ts#insertLevel': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#levelOrder',
    'apps/api/src/modules/qualification/store.ts#autoCode',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#ownerOf',
    'apps/api/src/modules/qualification/store.ts#referenced',
    'apps/api/src/modules/qualification/store.ts#requireCodeAvailable',
  ],
  'apps/api/src/modules/qualification/config-service.ts#jobObject': [
    'apps/api/src/modules/permission/module-route-access.ts#visibleJob',
    '#JOB_KINDS',
    '#asOf',
  ],
  'apps/api/src/modules/qualification/config-service.ts#levelOrder': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#lockLevelOrder',
  ],
  'apps/api/src/modules/qualification/config-service.ts#listCodingRules': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#CODING_ITEMS',
    'apps/api/src/modules/qualification/read-model.ts#view',
  ],
  'apps/api/src/modules/qualification/config-service.ts#lockLevelOrder': [
    'apps/api/src/advisory-lock.ts#advisoryLock32',
    'apps/api/src/advisory-lock.ts#asUuid',
  ],
  'apps/api/src/modules/qualification/config-service.ts#patchJobLinks': ['#replaceJobLinks'],
  'apps/api/src/modules/qualification/config-service.ts#patchSimple': [
    '#reload',
    'apps/api/src/modules/qualification/store.ts#bumped',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#requireCodeAvailable',
    'apps/api/src/modules/qualification/store.ts#tableOf',
  ],
  'apps/api/src/modules/qualification/config-service.ts#reload': [
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#view',
    'apps/api/src/modules/qualification/read-model.ts#withJobLinks',
  ],
  'apps/api/src/modules/qualification/config-service.ts#replaceJobLinks': [
    'apps/api/src/modules/qualification/access.ts#ANCHOR',
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#jobObject',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
  ],
  'apps/api/src/modules/qualification/config-service.ts#updateCategory': [
    '#CATEGORY_COLUMNS',
    '#orgOf',
    '#patchJobLinks',
    '#patchSimple',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
  ],
  'apps/api/src/modules/qualification/config-service.ts#updateCategoryClass': [
    '#CLASS_COLUMNS',
    '#orgOf',
    '#patchSimple',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
  ],
  'apps/api/src/modules/qualification/config-service.ts#updateCodingRule': [
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#listCodingRules',
    'apps/api/src/modules/qualification/read-model.ts#view',
    'apps/api/src/modules/qualification/store.ts#audit',
  ],
  'apps/api/src/modules/qualification/config-service.ts#updateLayer': [
    '#patchSimple',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
  ],
  'apps/api/src/modules/qualification/config-service.ts#updateLevel': [
    '#LEVEL_COLUMNS',
    '#levelOrder',
    '#orgOf',
    '#patchJobLinks',
    '#patchSimple',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#referenced',
  ],
  'apps/api/src/modules/qualification/config-service.ts#updateTargetType': [
    '#CLASS_COLUMNS',
    '#orgOf',
    '#patchSimple',
    '#reload',
    'apps/api/src/modules/qualification/store.ts#audit',
  ],
  'apps/api/src/modules/qualification/current.ts#currentQualification': [
    '#assertIsoDate',
    '#normalizedUuid',
    '#rowsOf',
  ],
  'apps/api/src/modules/qualification/development-channel-data.ts#channelOverview': [
    'apps/api/src/modules/qualification/current.ts#currentQualification',
    '#displayOrders',
    '#standardOfCategory',
    'apps/api/src/modules/qualification/standard-service.ts#loadChannels',
  ],
  'apps/api/src/modules/qualification/development-channel-data.ts#displayOrders': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/development-channel-data.ts#standardOfCategory': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/development-channel.ts#SUBSET': [
    'packages/domain/src/personnel/fields.ts#SUBSETS',
  ],
  'apps/api/src/modules/qualification/development-channel.ts#registerDevelopmentChannel': [
    'apps/api/src/modules/qualification/access.ts#qualificationContext',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/current.ts#currentQualification',
    'apps/api/src/modules/qualification/development-channel-data.ts#channelOverview',
    'apps/api/src/modules/qualification/development-channel-data.ts#standardOfCategory',
    '#viewEmployeeQualification',
    'apps/api/src/modules/qualification/presenters.ts#presentChannels',
    'apps/api/src/modules/qualification/presenters.ts#presentChart',
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#withStandardParts',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/talent/http.ts#uuidParam',
    'apps/api/src/modules/talent/http.ts#uuidQuery',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/qualification/development-channel.ts#viewEmployeeQualification': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/personnel/access.ts#access',
    'apps/api/src/modules/personnel/access.ts#preflight',
    '#SUBSET',
  ],
  'apps/api/src/modules/qualification/extras.ts#categoryAnchors': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/extras.ts#importTask': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/qualification/access.ts#codeOf',
    '#categoryAnchors',
    '#operatingUnit',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/qualification/extras.ts#operatingUnit': [
    'apps/api/src/modules/permission/owner-units.ts#authorizedUnits',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_APP',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/qualification/extras.ts#registerChannels': [
    'apps/api/src/modules/qualification/access.ts#checkWriteFields',
    'apps/api/src/modules/qualification/access.ts#qualificationContext',
    'apps/api/src/modules/qualification/access.ts#qualificationScope',
    'apps/api/src/modules/qualification/access.ts#qualificationWriteContext',
    'apps/api/src/modules/qualification/access.ts#requireReadable',
    'apps/api/src/modules/qualification/input.ts#channelsPut',
    'apps/api/src/modules/qualification/presenters.ts#presentChannels',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/qualification/route-support.ts#requireAllVisible',
    'apps/api/src/modules/qualification/route-support.ts#runWrite',
    'apps/api/src/modules/qualification/route-support.ts#writeContext',
    'apps/api/src/modules/qualification/standard-service.ts#loadChannels',
    'apps/api/src/modules/qualification/standard-service.ts#putChannels',
    'apps/api/src/modules/qualification/store.ts#rowAccess',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/qualification/extras.ts#registerChart': [
    'apps/api/src/modules/qualification/access.ts#qualificationContext',
    'apps/api/src/modules/qualification/access.ts#qualificationScope',
    'apps/api/src/modules/qualification/access.ts#requireReadable',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/presenters.ts#presentChart',
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#withStandardParts',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/qualification/store.ts#rowAccess',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/qualification/extras.ts#registerCodingRules': [
    'apps/api/src/modules/qualification/access.ts#checkWriteFields',
    'apps/api/src/modules/qualification/access.ts#qualificationContext',
    'apps/api/src/modules/qualification/access.ts#qualificationWriteContext',
    'apps/api/src/modules/qualification/access.ts#trimQualification',
    'apps/api/src/modules/qualification/config-service.ts#CODING_ITEMS',
    'apps/api/src/modules/qualification/config-service.ts#listCodingRules',
    'apps/api/src/modules/qualification/config-service.ts#updateCodingRule',
    'apps/api/src/modules/qualification/input.ts#codingRulePatch',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/qualification/route-support.ts#runWrite',
    'apps/api/src/modules/qualification/route-support.ts#writeContext',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#revision',
  ],
  'apps/api/src/modules/qualification/extras.ts#registerExtras': [
    '#registerChannels',
    '#registerChart',
    '#registerCodingRules',
    '#registerGradeDescriptions',
    '#registerImports',
    '#registerStandardImport',
  ],
  'apps/api/src/modules/qualification/extras.ts#registerGradeDescriptions': [
    'apps/api/src/modules/qualification/access.ts#checkWriteFields',
    'apps/api/src/modules/qualification/access.ts#qualificationContext',
    'apps/api/src/modules/qualification/access.ts#qualificationScope',
    'apps/api/src/modules/qualification/access.ts#qualificationWriteContext',
    'apps/api/src/modules/qualification/access.ts#requireReadable',
    'apps/api/src/modules/qualification/input.ts#gradeDescriptionPut',
    'apps/api/src/modules/qualification/presenters.ts#presentGradeDescriptions',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/qualification/route-support.ts#requireAllVisible',
    'apps/api/src/modules/qualification/route-support.ts#runWrite',
    'apps/api/src/modules/qualification/route-support.ts#writeContext',
    'apps/api/src/modules/qualification/store.ts#rowAccess',
    'apps/api/src/modules/qualification/target-service.ts#gradeDescriptions',
    'apps/api/src/modules/qualification/target-service.ts#putGradeDescription',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/qualification/extras.ts#registerImports': [
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/modules/qualification/access.ts#checkWriteFields',
    'apps/api/src/modules/qualification/access.ts#qualificationWriteContext',
    'apps/api/src/modules/qualification/config-service.ts#importCategories',
    'apps/api/src/modules/qualification/config-service.ts#importLevels',
    '#CATEGORY_JOBS',
    '#LEVEL_JOBS',
    '#importTask',
    'apps/api/src/modules/qualification/input.ts#categoryImport',
    'apps/api/src/modules/qualification/input.ts#levelImport',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/qualification/route-support.ts#presenter',
    'apps/api/src/modules/qualification/route-support.ts#requireAllVisible',
    'apps/api/src/modules/qualification/route-support.ts#runWrite',
    'apps/api/src/modules/qualification/route-support.ts#writeContext',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
  ],
  'apps/api/src/modules/qualification/extras.ts#registerStandardImport': [
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/modules/qualification/access.ts#checkWriteFields',
    'apps/api/src/modules/qualification/access.ts#qualificationWriteContext',
    '#importTask',
    'apps/api/src/modules/qualification/input.ts#standardImport',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/qualification/route-support.ts#requireAllVisible',
    'apps/api/src/modules/qualification/route-support.ts#runWrite',
    'apps/api/src/modules/qualification/route-support.ts#writeContext',
    'apps/api/src/modules/qualification/standard-service.ts#importStandardDetails',
    'apps/api/src/modules/talent/http.ts#parseBody',
  ],
  'apps/api/src/modules/qualification/indicator-port.ts#deepFreeze': ['#deepFreeze'],
  'apps/api/src/modules/qualification/indicator-port.ts#indicators': [
    'apps/api/src/modules/qualification/current.ts#assertIsoDate',
    'apps/api/src/modules/qualification/current.ts#currentQualification',
    'apps/api/src/modules/qualification/current.ts#normalizedUuid',
    '#FAILURES',
    '#QUALIFICATION_PORT_LIMIT',
    '#deepFreeze',
    '#rowsOf',
    '#typeChains',
    '#typeScope',
    '#uuidArray',
  ],
  'apps/api/src/modules/qualification/indicator-port.ts#installQualificationIndicatorPort': [
    '#port',
    'packages/domain/src/qualification/indicator-port.ts#registerQualificationIndicatorPort',
  ],
  'apps/api/src/modules/qualification/indicator-port.ts#listTargetTypes': [
    'apps/api/src/modules/qualification/current.ts#normalizedUuid',
    '#deepFreeze',
    '#pageOf',
    '#rowsOf',
    '#scopePredicate',
  ],
  'apps/api/src/modules/qualification/indicator-port.ts#listTargets': [
    'apps/api/src/modules/qualification/current.ts#normalizedUuid',
    '#deepFreeze',
    '#pageOf',
    '#rowsOf',
    '#scopePredicate',
  ],
  'apps/api/src/modules/qualification/indicator-port.ts#pageOf': ['#QUALIFICATION_PORT_LIMIT'],
  'apps/api/src/modules/qualification/indicator-port.ts#port': ['#indicators', '#listTargetTypes', '#listTargets'],
  'apps/api/src/modules/qualification/indicator-port.ts#typeChains': ['#TYPE_DEPTH_LIMIT', '#rowsOf', '#uuidArray'],
  'apps/api/src/modules/qualification/indicator-port.ts#typeScope': ['#uuidArray'],
  'apps/api/src/modules/qualification/input.ts#ability': ['#percent', '#uuid'],
  'apps/api/src/modules/qualification/input.ts#categoryClassCreate': [
    '#code',
    '#common',
    '#name',
    '#order',
    '#ownerOrgId',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#categoryClassPatch': ['#categoryClassCreate'],
  'apps/api/src/modules/qualification/input.ts#categoryCreate': [
    '#CATEGORY_LINKS',
    '#code',
    '#common',
    '#jobLinks',
    '#name',
    '#ownerOrgId',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#categoryImport': [
    '#CATEGORY_LINKS',
    '#MAX_IMPORT_ITEMS',
    '#importItem',
    '#ownerOrgId',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#categoryPatch': ['#categoryCreate'],
  'apps/api/src/modules/qualification/input.ts#cell': ['#MAX_ABILITIES', '#ability', '#percent', '#uuid'],
  'apps/api/src/modules/qualification/input.ts#channel': ['#uuid'],
  'apps/api/src/modules/qualification/input.ts#channelsPut': ['#channel'],
  'apps/api/src/modules/qualification/input.ts#gradeDetail': ['#name', '#text', '#uuid'],
  'apps/api/src/modules/qualification/input.ts#gradeSchemeCreate': [
    '#MAX_GRADE_DETAILS',
    '#gradeDetail',
    '#name',
    '#text',
  ],
  'apps/api/src/modules/qualification/input.ts#gradeSchemePatch': ['#gradeSchemeCreate'],
  'apps/api/src/modules/qualification/input.ts#importItem': ['#code', '#name', '#uuid'],
  'apps/api/src/modules/qualification/input.ts#importRow': ['#percent'],
  'apps/api/src/modules/qualification/input.ts#jobLinks': ['#MAX_JOB_LINKS', '#uuid'],
  'apps/api/src/modules/qualification/input.ts#layerCreate': ['#name', '#order'],
  'apps/api/src/modules/qualification/input.ts#layerPatch': ['#layerCreate'],
  'apps/api/src/modules/qualification/input.ts#levelCreate': [
    '#LEVEL_LINKS',
    '#code',
    '#common',
    '#jobLinks',
    '#name',
    '#order',
    '#ownerOrgId',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#levelDescription': ['#uuid'],
  'apps/api/src/modules/qualification/input.ts#levelImport': [
    '#LEVEL_LINKS',
    '#MAX_IMPORT_ITEMS',
    '#importItem',
    '#ownerOrgId',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#levelPatch': ['#levelCreate'],
  'apps/api/src/modules/qualification/input.ts#ownerOrgId': ['#uuid'],
  'apps/api/src/modules/qualification/input.ts#standardCreate': [
    '#MAX_CELLS',
    '#MAX_LEVELS',
    '#cell',
    '#levelDescription',
    '#name',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#standardImport': ['#MAX_IMPORT_ROWS', '#expectedStandard', '#importRow'],
  'apps/api/src/modules/qualification/input.ts#standardPatch': ['#standardCreate'],
  'apps/api/src/modules/qualification/input.ts#targetCreate': [
    '#code',
    '#common',
    '#name',
    '#order',
    '#ownerOrgId',
    '#text',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#targetPatch': ['#targetCreate'],
  'apps/api/src/modules/qualification/input.ts#targetTypeCreate': [
    '#code',
    '#common',
    '#name',
    '#order',
    '#ownerOrgId',
    '#uuid',
  ],
  'apps/api/src/modules/qualification/input.ts#targetTypePatch': ['#targetTypeCreate'],
  'apps/api/src/modules/qualification/presenters.ts#levelOrderVisible': [
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    'apps/api/src/modules/qualification/access.ts#objectFields',
    'apps/api/src/modules/qualification/route-support.ts#readableIds',
  ],
  'apps/api/src/modules/qualification/presenters.ts#presentChannels': [
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    'apps/api/src/modules/qualification/access.ts#objectFields',
    '#levelOrderVisible',
    'apps/api/src/modules/qualification/route-support.ts#readableIds',
  ],
  'apps/api/src/modules/qualification/presenters.ts#presentChart': [
    '#levelOrderVisible',
    'apps/api/src/modules/qualification/route-support.ts#presenter',
  ],
  'apps/api/src/modules/qualification/presenters.ts#presentGradeDescriptions': [
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    'apps/api/src/modules/qualification/access.ts#objectFields',
    '#schemeDetailsVisible',
  ],
  'apps/api/src/modules/qualification/presenters.ts#schemeDetailsVisible': [
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    'apps/api/src/modules/qualification/access.ts#objectFields',
    'apps/api/src/modules/qualification/access.ts#qualificationScope',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/read-model.ts#gradeDetails': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#view',
  ],
  'apps/api/src/modules/qualification/read-model.ts#listRows': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#ORDER',
    'apps/api/src/modules/qualification/store.ts#tableOf',
  ],
  'apps/api/src/modules/qualification/read-model.ts#loadRow': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/store.ts#tableOf',
  ],
  'apps/api/src/modules/qualification/read-model.ts#view': ['#INTERNAL', '#NUMERIC', '#camel'],
  'apps/api/src/modules/qualification/read-model.ts#withGradeDetails': ['#gradeDetails', '#view'],
  'apps/api/src/modules/qualification/read-model.ts#withJobLinks': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#LINK_TABLES',
    '#view',
  ],
  'apps/api/src/modules/qualification/read-model.ts#withStandardParts': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#view',
  ],
  'apps/api/src/modules/qualification/route-support.ts#fieldEditable': [
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    'apps/api/src/modules/qualification/access.ts#codeOf',
  ],
  'apps/api/src/modules/qualification/route-support.ts#hideOverwritten': [
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
    'apps/api/src/modules/qualification/access.ts#objectFields',
    '#readableIds',
  ],
  'apps/api/src/modules/qualification/route-support.ts#objectOutcome': ['#presenter', '#requireStillVisible'],
  'apps/api/src/modules/qualification/route-support.ts#presenter': [
    'apps/api/src/modules/qualification/access.ts#trimQualification',
    '#hideOverwritten',
  ],
  'apps/api/src/modules/qualification/route-support.ts#readableIds': [
    'apps/api/src/modules/qualification/access.ts#codeOf',
    'apps/api/src/modules/qualification/access.ts#qlViewable',
    'apps/api/src/modules/qualification/access.ts#qualificationScope',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/route-support.ts#requireAllVisible': [
    'apps/api/src/modules/qualification/access.ts#requireReadable',
    'apps/api/src/modules/qualification/store.ts#rowAccess',
  ],
  'apps/api/src/modules/qualification/route-support.ts#requireStillVisible': [
    'apps/api/src/modules/permission/module-access.ts#scopeAllows',
    'apps/api/src/modules/qualification/access.ts#ANCHOR',
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    '#requireAllVisible',
  ],
  'apps/api/src/modules/qualification/route-support.ts#runWrite': ['#objectOutcome'],
  'apps/api/src/modules/qualification/route-support.ts#writeContext': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    'apps/api/src/modules/qualification/access.ts#codeOf',
    'apps/api/src/modules/qualification/access.ts#objectFields',
    'apps/api/src/modules/qualification/access.ts#qualificationScope',
  ],
  'apps/api/src/modules/qualification/routes.ts#SPECS': [
    'apps/api/src/modules/qualification/config-service.ts#createCategory',
    'apps/api/src/modules/qualification/config-service.ts#createCategoryClass',
    'apps/api/src/modules/qualification/config-service.ts#createLayer',
    'apps/api/src/modules/qualification/config-service.ts#createLevel',
    'apps/api/src/modules/qualification/config-service.ts#createTargetType',
    'apps/api/src/modules/qualification/config-service.ts#deleteCategory',
    'apps/api/src/modules/qualification/config-service.ts#deleteCategoryClass',
    'apps/api/src/modules/qualification/config-service.ts#deleteLayer',
    'apps/api/src/modules/qualification/config-service.ts#deleteLevel',
    'apps/api/src/modules/qualification/config-service.ts#deleteTargetType',
    'apps/api/src/modules/qualification/config-service.ts#updateCategory',
    'apps/api/src/modules/qualification/config-service.ts#updateCategoryClass',
    'apps/api/src/modules/qualification/config-service.ts#updateLayer',
    'apps/api/src/modules/qualification/config-service.ts#updateLevel',
    'apps/api/src/modules/qualification/config-service.ts#updateTargetType',
    'apps/api/src/modules/qualification/input.ts#categoryClassCreate',
    'apps/api/src/modules/qualification/input.ts#categoryClassPatch',
    'apps/api/src/modules/qualification/input.ts#categoryCreate',
    'apps/api/src/modules/qualification/input.ts#categoryPatch',
    'apps/api/src/modules/qualification/input.ts#gradeSchemeCreate',
    'apps/api/src/modules/qualification/input.ts#gradeSchemePatch',
    'apps/api/src/modules/qualification/input.ts#layerCreate',
    'apps/api/src/modules/qualification/input.ts#layerPatch',
    'apps/api/src/modules/qualification/input.ts#levelCreate',
    'apps/api/src/modules/qualification/input.ts#levelPatch',
    'apps/api/src/modules/qualification/input.ts#standardCreate',
    'apps/api/src/modules/qualification/input.ts#standardPatch',
    'apps/api/src/modules/qualification/input.ts#targetCreate',
    'apps/api/src/modules/qualification/input.ts#targetPatch',
    'apps/api/src/modules/qualification/input.ts#targetTypeCreate',
    'apps/api/src/modules/qualification/input.ts#targetTypePatch',
    'apps/api/src/modules/qualification/read-model.ts#withGradeDetails',
    'apps/api/src/modules/qualification/read-model.ts#withJobLinks',
    'apps/api/src/modules/qualification/read-model.ts#withStandardParts',
    '#CATEGORY_JOBS',
    '#LEVEL_JOBS',
    '#eq',
    'apps/api/src/modules/qualification/standard-service.ts#createStandard',
    'apps/api/src/modules/qualification/standard-service.ts#deleteStandard',
    'apps/api/src/modules/qualification/standard-service.ts#updateStandard',
    'apps/api/src/modules/qualification/target-service.ts#createGradeScheme',
    'apps/api/src/modules/qualification/target-service.ts#createTarget',
    'apps/api/src/modules/qualification/target-service.ts#deleteGradeScheme',
    'apps/api/src/modules/qualification/target-service.ts#deleteTarget',
    'apps/api/src/modules/qualification/target-service.ts#updateGradeScheme',
    'apps/api/src/modules/qualification/target-service.ts#updateTarget',
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#uuidQuery',
  ],
  'apps/api/src/modules/qualification/routes.ts#childDeleteRights': [
    'apps/api/src/modules/qualification/access.ts#codeOf',
  ],
  'apps/api/src/modules/qualification/routes.ts#registerObject': [
    'apps/api/src/modules/qualification/access.ts#ANCHOR',
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#checkWriteFields',
    'apps/api/src/modules/qualification/access.ts#listEnvelope',
    'apps/api/src/modules/qualification/access.ts#qualificationContext',
    'apps/api/src/modules/qualification/access.ts#qualificationScope',
    'apps/api/src/modules/qualification/access.ts#qualificationWriteContext',
    'apps/api/src/modules/qualification/access.ts#requireReadable',
    'apps/api/src/modules/qualification/read-model.ts#listRows',
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#view',
    'apps/api/src/modules/qualification/route-support.ts#QL_BASE',
    'apps/api/src/modules/qualification/route-support.ts#fieldEditable',
    'apps/api/src/modules/qualification/route-support.ts#presenter',
    'apps/api/src/modules/qualification/route-support.ts#runWrite',
    'apps/api/src/modules/qualification/route-support.ts#writeContext',
    '#childDeleteRights',
    'apps/api/src/modules/qualification/store.ts#rowAccess',
    'apps/api/src/modules/talent/http.ts#pageQuery',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/qualification/routes.ts#registerQualificationRoutes': [
    'apps/api/src/modules/qualification/candidates.ts#registerQualificationCandidates',
    'apps/api/src/modules/qualification/development-channel.ts#registerDevelopmentChannel',
    'apps/api/src/modules/qualification/extras.ts#registerExtras',
    'apps/api/src/modules/qualification/indicator-port.ts#installQualificationIndicatorPort',
    '#SPECS',
    '#registerObject',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#checkGrades': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#createStandard': [
    'apps/api/src/modules/qualification/access.ts#requireEditable',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#reloadStandard',
    '#standardExists',
    '#writeCells',
    '#writeLevelDescriptions',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#referenced',
    'apps/api/src/modules/qualification/store.ts#rowAccess',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#defaultAbilities': [
    'apps/api/src/modules/qualification/access.ts#fieldVisible',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#deleteStandard': [
    '#loadChannels',
    '#reloadStandard',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#deleteChildren',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#groupCells': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/input.ts#MAX_ABILITIES',
    '#key',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#importStandardDetails': [
    'apps/api/src/audit/record.ts#recordImportLog',
    'apps/api/src/modules/qualification/access.ts#codeOf',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#groupCells',
    '#importRejected',
    '#insertAbilities',
    '#lockImportTargets',
    '#reloadStandard',
    '#resolveRows',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#loadChannels': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#lockImportTargets': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#putChannels': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#channelKey',
    '#loadChannels',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#referenced',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#reloadStandard': [
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#withStandardParts',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#resolveRows': [
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#qlViewable',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#updateStandard': [
    '#reloadStandard',
    '#writeCells',
    '#writeLevelDescriptions',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#bumped',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
  ],
  'apps/api/src/modules/qualification/standard-service.ts#writeCells': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#checkGrades',
    '#defaultAbilities',
    '#insertAbilities',
    '#key',
    '#shape',
    'apps/api/src/modules/qualification/store.ts#referenced',
  ],
  'apps/api/src/modules/qualification/store.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/modules/qualification/access.ts#codeOf',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_AUDIT_ACTIONS',
  ],
  'apps/api/src/modules/qualification/store.ts#autoCode': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#CODE_PATTERN',
  ],
  'apps/api/src/modules/qualification/store.ts#deleteChildren': [
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    '#audit',
  ],
  'apps/api/src/modules/qualification/store.ts#guardUnique': ['#duplicate'],
  'apps/api/src/modules/qualification/store.ts#lockEditable': [
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    'apps/api/src/modules/qualification/access.ts#requireEditable',
    '#rowAccess',
  ],
  'apps/api/src/modules/qualification/store.ts#ownerOf': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/permission/owner-units.ts#chooseUnit',
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_APP',
  ],
  'apps/api/src/modules/qualification/store.ts#referenced': [
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    'apps/api/src/modules/qualification/access.ts#requireReadable',
    '#rowAccess',
  ],
  'apps/api/src/modules/qualification/store.ts#rejectInUse': ['apps/api/src/modules/qualification/access.ts#rowsOf'],
  'apps/api/src/modules/qualification/store.ts#requireCodeAvailable': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#duplicate',
    '#tableOf',
  ],
  'apps/api/src/modules/qualification/store.ts#rowAccess': [
    'apps/api/src/modules/qualification/access.ts#ANCHOR',
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    '#accessOf',
    '#tableOf',
  ],
  'apps/api/src/modules/qualification/store.ts#tableOf': [
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    '#TABLES',
  ],
  'apps/api/src/modules/qualification/subset-policy.ts#QUALIFICATION_POLICY': [
    '#qualificationBeforeRequest',
    '#qualificationBeforeSave',
  ],
  'apps/api/src/modules/qualification/subset-policy.ts#assertAutoSyncEditable': [
    'apps/api/src/modules/tenant-settings/service.ts#readEffectiveSetting',
  ],
  'apps/api/src/modules/qualification/subset-policy.ts#assertRefs': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/qualification/access.ts#assertQualificationRefs',
    'apps/api/src/modules/qualification/access.ts#codeOf',
  ],
  'apps/api/src/modules/qualification/subset-policy.ts#assertScorePrecision': ['#TWO_DECIMALS'],
  'apps/api/src/modules/qualification/subset-policy.ts#installQualificationSubsetPolicy': [
    'apps/api/src/modules/personnel/subset-policy.ts#registerSubsetPolicy',
    '#QUALIFICATION_POLICY',
  ],
  'apps/api/src/modules/qualification/subset-policy.ts#qualificationBeforeRequest': ['#SELF_SERVICE_CLOSED'],
  'apps/api/src/modules/qualification/subset-policy.ts#qualificationBeforeSave': [
    '#SELF_SERVICE_CLOSED',
    '#assertAutoSyncEditable',
    '#assertRefs',
    '#assertScorePrecision',
    '#canonicalRefs',
    '#isHuman',
    '#newRefs',
    '#requireText',
  ],
  'apps/api/src/modules/qualification/target-service.ts#cellsOf': [
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#withStandardParts',
  ],
  'apps/api/src/modules/qualification/target-service.ts#checkEvalMode': [
    'apps/api/src/modules/qualification/store.ts#referenced',
  ],
  'apps/api/src/modules/qualification/target-service.ts#createGradeScheme': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    'apps/api/src/modules/qualification/access.ts#QUALIFICATION_LABELS',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    '#insertDetail',
    '#reloadScheme',
    '#requireSchemeNameFree',
  ],
  'apps/api/src/modules/qualification/target-service.ts#createTarget': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#autoCode',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#ownerOf',
    'apps/api/src/modules/qualification/store.ts#referenced',
    'apps/api/src/modules/qualification/store.ts#requireCodeAvailable',
    '#checkEvalMode',
    '#reloadTarget',
  ],
  'apps/api/src/modules/qualification/target-service.ts#deleteGradeScheme': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/read-model.ts#view',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#deleteChildren',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
    '#manualDescriptions',
    '#reloadScheme',
    '#requireTargetsEditable',
  ],
  'apps/api/src/modules/qualification/target-service.ts#deleteTarget': [
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#deleteChildren',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
    '#manualDescriptions',
    '#reloadTarget',
  ],
  'apps/api/src/modules/qualification/target-service.ts#gradeDescriptions': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/read-model.ts#gradeDetails',
  ],
  'apps/api/src/modules/qualification/target-service.ts#manualDescriptions': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/target-service.ts#overwriteStandards': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/store.ts#audit',
    '#cellsOf',
  ],
  'apps/api/src/modules/qualification/target-service.ts#putGradeDescription': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    '#gradeDescriptions',
  ],
  'apps/api/src/modules/qualification/target-service.ts#referencingStandards': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/target-service.ts#reloadScheme': [
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#withGradeDetails',
  ],
  'apps/api/src/modules/qualification/target-service.ts#reloadTarget': [
    'apps/api/src/modules/qualification/read-model.ts#loadRow',
    'apps/api/src/modules/qualification/read-model.ts#view',
  ],
  'apps/api/src/modules/qualification/target-service.ts#requireSchemeNameFree': [
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/target-service.ts#requireTargetsEditable': [
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#rowsOf',
  ],
  'apps/api/src/modules/qualification/target-service.ts#updateGradeScheme': [
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#bumped',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
    '#insertDetail',
    '#reloadScheme',
    '#requireSchemeNameFree',
  ],
  'apps/api/src/modules/qualification/target-service.ts#updateTarget': [
    'apps/api/src/modules/qualification/access.ts#requireEditable',
    'apps/api/src/modules/qualification/store.ts#audit',
    'apps/api/src/modules/qualification/store.ts#bumped',
    'apps/api/src/modules/qualification/store.ts#guardUnique',
    'apps/api/src/modules/qualification/store.ts#lockEditable',
    'apps/api/src/modules/qualification/store.ts#rejectInUse',
    'apps/api/src/modules/qualification/store.ts#requireCodeAvailable',
    'apps/api/src/modules/qualification/store.ts#rowAccess',
    '#COMMON_OVERWRITE_MESSAGE',
    '#checkEvalMode',
    '#overwriteStandards',
    '#referencingStandards',
    '#reloadTarget',
  ],
};
