/**
 * 直接依赖图：区域 api-audit（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/audit/establishment-capacity.ts#capacityAuditChanges': ['#PART_FIELDS'],
  'apps/api/src/audit/establishment-capacity.ts#visibleCapacityParts': ['#PART_FIELDS'],
  'apps/api/src/audit/failures.ts#isDefiniteFailure': ['#CommandFailureError'],
  'apps/api/src/audit/nested-fields.ts#visibleItems': ['#IDENTITY'],
  'apps/api/src/audit/nested-fields.ts#visibleNested': ['#visibleItems'],
  'apps/api/src/audit/nested-fields.ts#visibleNestedChanges': ['#visibleItems'],
  'apps/api/src/audit/qualification-sources.ts#CHANNEL': [
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
  ],
  'apps/api/src/audit/qualification-sources.ts#GRADE_DESCRIPTION': [
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
  ],
  'apps/api/src/audit/qualification-sources.ts#STANDARD': [
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
  ],
  'apps/api/src/audit/qualification-sources.ts#collectRefs': ['#CHANNEL_REFS', '#isObject', '#isRef'],
  'apps/api/src/audit/qualification-sources.ts#collectTargets': ['#collectTargets', '#isObject', '#isOverwritten'],
  'apps/api/src/audit/qualification-sources.ts#hideOverwritten': ['#hideOverwritten', '#isObject', '#isOverwritten'],
  'apps/api/src/audit/qualification-sources.ts#isRef': ['#CHANNEL_REFS'],
  'apps/api/src/audit/qualification-sources.ts#projectedScheme': ['#isObject'],
  'apps/api/src/audit/qualification-sources.ts#qualificationSources': [
    '#CHANNEL',
    '#CHANNEL_REFS',
    '#GRADE_DESCRIPTION',
    '#STANDARD',
    '#collectRefs',
    '#collectTargets',
    '#projectedScheme',
    '#readable',
    '#redactProjection',
    '#redactRefs',
    '#redactStandard',
    '#sourceScope',
    'apps/api/src/modules/qualification/access.ts#accessSql',
    'apps/api/src/modules/qualification/access.ts#qlViewable',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
  ],
  'apps/api/src/audit/qualification-sources.ts#readable': ['#UUID'],
  'apps/api/src/audit/qualification-sources.ts#redactProjection': ['#projectedScheme'],
  'apps/api/src/audit/qualification-sources.ts#redactRefs': ['#isObject', '#isRef'],
  'apps/api/src/audit/qualification-sources.ts#redactStandard': ['#hideOverwritten'],
  'apps/api/src/audit/qualification-sources.ts#sourceScope': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
  ],
  'apps/api/src/audit/query.ts#pageLimit': ['#DEFAULT_LIMIT', '#MAX_LIMIT'],
  'apps/api/src/audit/query.ts#queryWindow': [
    '#windowMessage',
    'packages/domain/src/audit/retention.ts#auditQueryWindow',
    'packages/domain/src/audit/retention.ts#isIsoDate',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/audit/query.ts#tenantRetention': [
    '#RETENTION_KEY',
    'apps/api/src/modules/tenant-settings/service.ts#readEffectiveSetting',
    'packages/domain/src/audit/retention.ts#resolveAuditRetention',
  ],
  'apps/api/src/audit/record.ts#failedImportReport': ['#isIssue', '#reasonOf'],
  'apps/api/src/audit/record.ts#rawUuid': ['#UUID'],
  'apps/api/src/audit/record.ts#recordAudit': ['apps/api/src/audit/request-context.ts#currentAuditRequest'],
  'apps/api/src/audit/record.ts#recordFailedImport': [
    '#failedImportReport',
    '#recordOperationLog',
    'apps/api/src/audit/request-context.ts#currentAuditRequest',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/audit/record.ts#recordImportLog': ['#recordOperationLog'],
  'apps/api/src/audit/record.ts#recordOperationLog': ['apps/api/src/audit/request-context.ts#currentAuditRequest'],
  'apps/api/src/audit/record.ts#withFailedImportLog': [
    'apps/api/src/audit/failures.ts#CommandFailureError',
    '#recordFailedImport',
  ],
  'apps/api/src/audit/request-context.ts#currentAuditRequest': ['#storage'],
  'apps/api/src/audit/routes.ts#auditContext': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/audit/routes.ts#dataChangeFilters': [
    'apps/api/src/audit/query.ts#optionalQuery',
    'apps/api/src/audit/query.ts#optionalUuid',
    '#CODE',
    '#FIELD',
    '#normalizeObjectId',
    'packages/domain/src/audit/changes.ts#AUDIT_OPERATIONS',
  ],
  'apps/api/src/audit/routes.ts#dataChangeView': [
    '#WITHHELD_SOURCE',
    '#sourceView',
    'apps/api/src/audit/visibility.ts#visibleChanges',
    'packages/domain/src/audit/changes.ts#AUDIT_OPERATION_LABELS',
    'packages/domain/src/audit/changes.ts#auditContent',
    'packages/domain/src/audit/changes.ts#auditOperationOf',
    'packages/domain/src/audit/changes.ts#diffAuditFields',
    'packages/domain/src/audit/changes.ts#renderAuditChanges',
    'packages/domain/src/audit/labels.ts#auditObjectMeta',
  ],
  'apps/api/src/audit/routes.ts#eventColumns': ['apps/api/src/audit/transfer-linkage.ts#linkageSnapshot'],
  'apps/api/src/audit/routes.ts#failureFilters': [
    'apps/api/src/audit/query.ts#optionalQuery',
    'apps/api/src/audit/query.ts#optionalUuid',
    '#CODE',
    'packages/domain/src/audit/operations.ts#COMMAND_FAILURE_OUTCOMES',
  ],
  'apps/api/src/audit/routes.ts#failureView': [
    '#sourceView',
    'packages/domain/src/audit/operations.ts#COMMAND_FAILURE_LABELS',
  ],
  'apps/api/src/audit/routes.ts#operationFilters': [
    'apps/api/src/audit/query.ts#optionalQuery',
    'apps/api/src/audit/query.ts#optionalUuid',
    '#CODE',
    '#normalizeObjectId',
    'packages/domain/src/audit/operations.ts#AUDIT_BEHAVIORS',
  ],
  'apps/api/src/audit/routes.ts#operationView': [
    '#sourceView',
    '#visibleTask',
    'apps/api/src/audit/visibility.ts#visibleErrorReport',
    'packages/domain/src/audit/labels.ts#auditObjectMeta',
    'packages/domain/src/audit/operations.ts#AUDIT_BEHAVIOR_LABELS',
  ],
  'apps/api/src/audit/routes.ts#pageConditions': [
    'apps/api/src/audit/query.ts#afterCursor',
    'apps/api/src/audit/query.ts#cursorOf',
    'apps/api/src/audit/query.ts#occurredWithin',
  ],
  'apps/api/src/audit/routes.ts#recounted': ['packages/domain/src/audit/changes.ts#diffAuditFields'],
  'apps/api/src/audit/routes.ts#route:GET /api/tenant/audit/command-failures': [
    'apps/api/src/audit/query.ts#operatorNames',
    'apps/api/src/audit/query.ts#pageLimit',
    'apps/api/src/audit/query.ts#paginate',
    'apps/api/src/audit/query.ts#queryWindow',
    'apps/api/src/audit/query.ts#tenantRetention',
    '#BASE',
    '#auditContext',
    '#failureFilters',
    '#failureView',
    '#pageConditions',
    'apps/api/src/modules/survey360/access.ts#survey360FailureVisibility',
  ],
  'apps/api/src/audit/routes.ts#route:GET /api/tenant/audit/data-changes': [
    'apps/api/src/audit/query.ts#operatorNames',
    'apps/api/src/audit/query.ts#pageLimit',
    'apps/api/src/audit/query.ts#paginate',
    'apps/api/src/audit/query.ts#queryWindow',
    'apps/api/src/audit/query.ts#tenantRetention',
    '#BASE',
    '#auditContext',
    '#dataChangeFilters',
    '#dataChangeView',
    '#eventColumns',
    '#pageConditions',
    '#recounted',
    'apps/api/src/audit/visibility.ts#auditViewer',
  ],
  'apps/api/src/audit/routes.ts#route:GET /api/tenant/audit/data-changes/:id': [
    'apps/api/src/audit/query.ts#notBefore',
    'apps/api/src/audit/query.ts#operatorNames',
    'apps/api/src/audit/query.ts#queryWindow',
    'apps/api/src/audit/query.ts#tenantRetention',
    '#BASE',
    '#auditContext',
    '#dataChangeView',
    '#eventColumns',
    '#recounted',
    'apps/api/src/audit/visibility.ts#auditViewer',
    'apps/api/src/audit/visibility.ts#visibleValue',
  ],
  'apps/api/src/audit/routes.ts#route:GET /api/tenant/audit/operation-logs': [
    'apps/api/src/audit/query.ts#operatorNames',
    'apps/api/src/audit/query.ts#pageLimit',
    'apps/api/src/audit/query.ts#paginate',
    'apps/api/src/audit/query.ts#queryWindow',
    'apps/api/src/audit/query.ts#tenantRetention',
    '#BASE',
    '#auditContext',
    '#operationFilters',
    '#operationView',
    '#pageConditions',
    'apps/api/src/audit/visibility.ts#auditViewer',
  ],
  'apps/api/src/audit/routes.ts#visibleTask': ['packages/domain/src/audit/operations.ts#auditTaskSummary'],
  'apps/api/src/audit/survey360-person.ts#survey360PersonAuditFields': [
    'apps/api/src/audit/transfer-linkage.ts#ExactAuditFields',
    'packages/domain/src/survey360/catalog.ts#SURVEY360_OBJECTS',
  ],
  'apps/api/src/audit/transfer-linkage.ts#EMP': ['packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS'],
  'apps/api/src/audit/transfer-linkage.ts#ORG': ['packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS'],
  'apps/api/src/audit/transfer-linkage.ts#contractsVisible': [
    '#event',
    '#idOf',
    '#transferEmployee',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
  ],
  'apps/api/src/audit/transfer-linkage.ts#dutiesVisible': [
    '#array',
    '#event',
    '#idOf',
    '#organizationVisible',
    '#subordinateVisible',
  ],
  'apps/api/src/audit/transfer-linkage.ts#eventVisible': ['#can', '#event', '#idOf', '#itemVisible'],
  'apps/api/src/audit/transfer-linkage.ts#itemVisible': ['#can', '#organizationVisible', '#subordinateVisible'],
  'apps/api/src/audit/transfer-linkage.ts#leaves': ['#event', '#linkageSnapshot', '#object'],
  'apps/api/src/audit/transfer-linkage.ts#linkageSnapshot': ['#TRANSFER_LINKAGE', '#event', '#object'],
  'apps/api/src/audit/transfer-linkage.ts#mappedField': ['#can', '#textArray'],
  'apps/api/src/audit/transfer-linkage.ts#objectAccess': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
  ],
  'apps/api/src/audit/transfer-linkage.ts#organizationVisible': [
    '#mappedField',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
    'apps/api/src/modules/transfer/linkage/validation.ts#ROLE_FIELDS',
  ],
  'apps/api/src/audit/transfer-linkage.ts#pathVisible': [
    '#OWN_FIELDS',
    '#can',
    '#contractsVisible',
    '#dutiesVisible',
    '#event',
    '#textArray',
  ],
  'apps/api/src/audit/transfer-linkage.ts#resolveLinkageAudit': [
    '#EMP',
    '#ORG',
    '#different',
    '#eventVisible',
    '#fieldMatch',
    '#leaves',
    '#objectAccess',
    '#pathVisible',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/audit/transfer-linkage.ts#subordinateVisible': [
    '#mappedField',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
    'apps/api/src/modules/permission/scope-persons.ts#currentPersons',
    'apps/api/src/modules/transfer/linkage/validation.ts#RELATION_FIELDS',
  ],
  'apps/api/src/audit/transfer-linkage.ts#transferEmployee': ['#idOf'],
  'apps/api/src/audit/visibility.ts#CONFIG_FIELDS_BY_ACTION': [
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'apps/api/src/audit/visibility.ts#CONFIG_FIELDS_BY_TYPE': ['#EMPLOYMENT'],
  'apps/api/src/audit/visibility.ts#EMPLOYMENT': ['packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS'],
  'apps/api/src/audit/visibility.ts#ESTABLISHMENT': ['packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS'],
  'apps/api/src/audit/visibility.ts#OBJECT_FIELDS': ['#S360'],
  'apps/api/src/audit/visibility.ts#ORG': ['packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS'],
  'apps/api/src/audit/visibility.ts#RULES': [
    '#APPROVAL_FLOW_FIELDS',
    '#EMPLOYMENT',
    '#ESTABLISHMENT',
    '#GLOBAL_JOB_KINDS',
    '#ORG',
    '#anchored',
    '#appConfigRules',
    '#copyJobVisible',
    '#evaluationFlowRules',
    '#jobObject',
    '#movementVisible',
    '#notificationVisible',
    '#orderCodeChildren',
    '#orgAdjustmentChildren',
    '#orgRule',
    '#ownedBy',
    '#personRule',
    '#qualificationRules',
    '#seeAllOnly',
    '#successionRules',
    '#survey360Rules',
    '#transferLinkageRule',
    '#uuidOf',
    'apps/api/src/modules/approval/access.ts#adminScope',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
    'apps/api/src/modules/idp/access.ts#IDP_AUDIT_ACTIONS',
    'apps/api/src/modules/idp/access.ts#IDP_ORG_OBJECTS',
    'apps/api/src/modules/idp/access.ts#IDP_PERSON_OBJECTS',
    'apps/api/src/modules/idp/key-info-scope.ts#KEY_INFO',
    'apps/api/src/modules/idp/key-info-scope.ts#keyInfoScopeSql',
    'apps/api/src/modules/idp/key-info-scope.ts#keyInfoSnapshot',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/module-route-access.ts#JOB_OBJECT_CODES',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_AUDIT_ACTIONS',
    'apps/api/src/modules/talent/access.ts#TALENT_AUDIT_ACTIONS',
    'apps/api/src/modules/talent/access.ts#isDictionary',
    'apps/api/src/modules/talent/model-image-service.ts#MODEL_IMAGE_AUDIT_TYPE',
    'packages/domain/src/approval/catalog.ts#APPROVAL_INSTANCE_OBJECT',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
    'packages/domain/src/evaluation/catalog.ts#EVALUATION_AUDIT_ACTIONS',
    'packages/domain/src/evaluation/catalog.ts#EVALUATION_OBJECTS',
    'packages/domain/src/evaluation/catalog.ts#EVALUATION_ORG_OBJECTS',
    'packages/domain/src/idp/catalog.ts#IDP_OBJECTS',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_REQUEST_OBJECT',
    'packages/domain/src/personnel/fields.ts#SUBSETS',
    'packages/domain/src/platform/standard-presets.ts#ESTABLISHMENT_SCHEME_DATASOURCE',
    'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_CONFIG_OBJECTS',
    'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS',
    'packages/domain/src/talent/catalog.ts#TALENT_OBJECTS',
  ],
  'apps/api/src/audit/visibility.ts#RULE_BY_TYPE': ['#RULES'],
  'apps/api/src/audit/visibility.ts#S360': ['packages/domain/src/survey360/catalog.ts#SURVEY360_OBJECTS'],
  'apps/api/src/audit/visibility.ts#SOURCE_TYPES': [
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
  ],
  'apps/api/src/audit/visibility.ts#SURVEY360_SHEET_DESENSITIZE': [
    'apps/api/src/modules/survey360/access.ts#survey360AuditScope',
  ],
  'apps/api/src/audit/visibility.ts#anchored': ['apps/api/src/modules/permission/module-access.ts#scopeSql'],
  'apps/api/src/audit/visibility.ts#appConfigRules': [
    '#orgRule',
    '#ownedBy',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
  ],
  'apps/api/src/audit/visibility.ts#auditViewer': [
    'apps/api/src/audit/establishment-capacity.ts#CapacityAuditFields',
    'apps/api/src/audit/establishment-capacity.ts#capacityAuditChanges',
    'apps/api/src/audit/qualification-sources.ts#qualificationSources',
    'apps/api/src/audit/transfer-linkage.ts#ExactAuditFields',
    'apps/api/src/audit/transfer-linkage.ts#TRANSFER_LINKAGE',
    '#EVENT',
    '#RULE_BY_TYPE',
    '#SOURCE_TYPES',
    '#TASK',
    '#configKey',
    '#configPredicate',
    '#configTypes',
    '#entryFieldScope',
    '#eventTypes',
    '#hasItems',
    '#isConfigLog',
    '#itemRow',
    '#maskColumn',
    '#maskedFields',
    '#objectTypesIn',
    '#orderRunCount',
    '#orgAdjustmentCount',
    '#resolveConfigFields',
    '#resolveRule',
    '#rowOf',
    '#textArray',
  ],
  'apps/api/src/audit/visibility.ts#changedVisible': [
    'apps/api/src/audit/establishment-capacity.ts#CapacityAuditFields',
    'apps/api/src/audit/establishment-capacity.ts#capacityAuditChanges',
    'apps/api/src/audit/transfer-linkage.ts#ExactAuditFields',
    '#textArray',
  ],
  'apps/api/src/audit/visibility.ts#configKey': ['#CONFIG_FIELDS_BY_ACTION'],
  'apps/api/src/audit/visibility.ts#configPredicate': [
    '#EVENT',
    '#configTypes',
    '#fieldVisible',
    '#textArray',
    'packages/domain/src/audit/labels.ts#AUDIT_CONFIG_ACTIONS',
  ],
  'apps/api/src/audit/visibility.ts#configTypes': [
    '#textArray',
    'packages/domain/src/audit/labels.ts#AUDIT_CONFIG_OBJECT_TYPES',
  ],
  'apps/api/src/audit/visibility.ts#copyJobVisible': [
    '#uuidOf',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/audit/visibility.ts#desensitized': ['#EVENT', '#OBJECT_FIELDS'],
  'apps/api/src/audit/visibility.ts#entryFieldScope': ['#fieldScope', '#maskedFieldScope'],
  'apps/api/src/audit/visibility.ts#evaluationFlowRules': [
    '#evaluationFlowRule',
    'packages/domain/src/evaluation/flow-catalog.ts#EVALUATION_FLOW_OBJECTS',
  ],
  'apps/api/src/audit/visibility.ts#eventTypes': [
    '#EVENT',
    '#textArray',
    'packages/domain/src/audit/labels.ts#AUDIT_CONFIG_ACTIONS',
  ],
  'apps/api/src/audit/visibility.ts#fieldScope': [
    'apps/api/src/audit/establishment-capacity.ts#CapacityAuditFields',
    'apps/api/src/audit/establishment-capacity.ts#capacityAuditChanges',
    'apps/api/src/audit/transfer-linkage.ts#ExactAuditFields',
    '#EVENT',
    '#changedVisible',
    '#fieldVisible',
    '#textArray',
  ],
  'apps/api/src/audit/visibility.ts#fieldVisible': [
    'apps/api/src/audit/transfer-linkage.ts#ExactAuditFields',
    'packages/domain/src/audit/labels.ts#auditFieldCode',
  ],
  'apps/api/src/audit/visibility.ts#hasItems': ['#TASK'],
  'apps/api/src/audit/visibility.ts#idpGoalFields': [
    'apps/api/src/audit/nested-fields.ts#NestedAuditFields',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'packages/domain/src/idp/catalog.ts#IDP_OBJECTS',
  ],
  'apps/api/src/audit/visibility.ts#isConfigLog': [
    'packages/domain/src/audit/labels.ts#AUDIT_CONFIG_ACTIONS',
    'packages/domain/src/audit/labels.ts#AUDIT_CONFIG_OBJECT_TYPES',
  ],
  'apps/api/src/audit/visibility.ts#itemRow': ['#TASK'],
  'apps/api/src/audit/visibility.ts#maskColumn': ['#eventTypes'],
  'apps/api/src/audit/visibility.ts#maskedFieldScope': ['#EVENT', '#fieldScope', '#maskedFields'],
  'apps/api/src/audit/visibility.ts#movementVisible': [
    '#uuidOf',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/audit/visibility.ts#notificationVisible': ['#copyJobVisible', '#movementVisible', '#uuidOf'],
  'apps/api/src/audit/visibility.ts#objectTypesIn': ['#EVENT', '#TASK'],
  'apps/api/src/audit/visibility.ts#orderCodeChildren': [
    '#anchored',
    '#changedVisible',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/audit/visibility.ts#orderRunCount': ['#EVENT', '#orderCodeChildren', '#rowOf'],
  'apps/api/src/audit/visibility.ts#orgAdjustmentChildren': [
    '#changedVisible',
    '#uuidOf',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
  ],
  'apps/api/src/audit/visibility.ts#orgAdjustmentCount': ['#EVENT', '#orgAdjustmentChildren', '#rowOf'],
  'apps/api/src/audit/visibility.ts#orgRule': [
    '#anchored',
    '#ownedBy',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/audit/visibility.ts#personRule': [
    '#anchored',
    '#ownedBy',
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/audit/visibility.ts#qualificationRules': [
    '#appConfigRules',
    'apps/api/src/modules/qualification/access.ts#OPEN_READ',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_AUDIT_ACTIONS',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_OBJECTS',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_ORG_AUDITED',
  ],
  'apps/api/src/audit/visibility.ts#resolveConfigFields': [
    '#CONFIG_FIELDS_BY_ACTION',
    '#CONFIG_FIELDS_BY_TYPE',
    '#EVENT',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'packages/domain/src/audit/labels.ts#AUDIT_CONFIG_ACTIONS',
  ],
  'apps/api/src/audit/visibility.ts#resolveRule': [
    'apps/api/src/audit/establishment-capacity.ts#CapacityAuditFields',
    'apps/api/src/audit/survey360-person.ts#survey360PersonAuditFields',
    'apps/api/src/audit/transfer-linkage.ts#TRANSFER_LINKAGE',
    'apps/api/src/audit/transfer-linkage.ts#resolveLinkageAudit',
    '#desensitized',
    '#idpGoalFields',
    '#reviewGroupFields',
    '#withProtocol',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'packages/domain/src/evaluation/catalog.ts#EVALUATION_OBJECTS',
    'packages/domain/src/idp/catalog.ts#IDP_OBJECTS',
    'packages/domain/src/idp/catalog.ts#linkedViewable',
  ],
  'apps/api/src/audit/visibility.ts#reviewGroupFields': [
    'apps/api/src/audit/nested-fields.ts#NestedAuditFields',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'packages/domain/src/evaluation/catalog.ts#EVALUATION_OBJECTS',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
  ],
  'apps/api/src/audit/visibility.ts#rowOf': ['#EVENT', '#TASK'],
  'apps/api/src/audit/visibility.ts#successionRules': [
    '#orgRule',
    '#seeAllOnly',
    'apps/api/src/modules/permission/scope-audit.ts#creatorSql',
    'apps/api/src/modules/succession/access.ts#SUCCESSION_AUDIT_ACTIONS',
    'apps/api/src/modules/succession/audit-scope.ts#SUCCESSION_AUDIT',
    'packages/domain/src/succession/catalog.ts#SUCCESSION_OBJECTS',
  ],
  'apps/api/src/audit/visibility.ts#survey360Rules': [
    '#S360',
    '#SURVEY360_SHEET_DESENSITIZE',
    '#byConflictEmployee',
    '#byResolve',
    '#inVisibleActivity',
    'apps/api/src/modules/survey360/access.ts#survey360AuditScope',
  ],
  'apps/api/src/audit/visibility.ts#textArray': ['#quote'],
  'apps/api/src/audit/visibility.ts#transferLinkageRule': [
    'apps/api/src/audit/transfer-linkage.ts#TRANSFER_LINKAGE',
    'apps/api/src/audit/transfer-linkage.ts#transferEmployee',
    '#EMPLOYMENT',
    '#personRule',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
  ],
  'apps/api/src/audit/visibility.ts#visibleChanges': [
    'apps/api/src/audit/nested-fields.ts#NestedAuditFields',
    'apps/api/src/audit/nested-fields.ts#visibleNestedChanges',
    '#fieldVisible',
  ],
  'apps/api/src/audit/visibility.ts#visibleErrorReport': ['#fieldVisible'],
  'apps/api/src/audit/visibility.ts#visibleValue': [
    'apps/api/src/audit/establishment-capacity.ts#CapacityAuditFields',
    'apps/api/src/audit/establishment-capacity.ts#visibleCapacityParts',
    'apps/api/src/audit/nested-fields.ts#NestedAuditFields',
    'apps/api/src/audit/nested-fields.ts#visibleNested',
    'apps/api/src/audit/transfer-linkage.ts#ExactAuditFields',
    '#fieldVisible',
    '#visibleValue',
  ],
};
