/**
 * 直接依赖图：区域 api-modules-talent-review（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/talent-review/access.ts#checkWriteFields': [
    'apps/api/src/modules/permission/module-route-access.ts#writeFields',
    '#codeOf',
  ],
  'apps/api/src/modules/talent-review/access.ts#codeOf': [
    'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS',
  ],
  'apps/api/src/modules/talent-review/access.ts#configEnvelope': [
    'apps/api/src/modules/permission/scope-audit.ts#hasCreatorScope',
  ],
  'apps/api/src/modules/talent-review/access.ts#configScopeSql': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/talent-review/access.ts#notFound': [
    'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECT_LABELS',
  ],
  'apps/api/src/modules/talent-review/access.ts#notFoundMessage': ['#notFound'],
  'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    '#notFound',
  ],
  'apps/api/src/modules/talent-review/access.ts#requireConfigVisible': [
    'apps/api/src/modules/permission/module-route-access.ts#visible',
    '#notFound',
  ],
  'apps/api/src/modules/talent-review/access.ts#requireFilterVisible': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    '#codeOf',
  ],
  'apps/api/src/modules/talent-review/access.ts#reviewContext': [
    'apps/api/src/modules/permission/module-route-access.ts#objectContext',
    '#codeOf',
  ],
  'apps/api/src/modules/talent-review/access.ts#reviewScope': [
    'apps/api/src/modules/permission/module-route-access.ts#requestScope',
    '#codeOf',
  ],
  'apps/api/src/modules/talent-review/access.ts#reviewWriteContext': [
    'apps/api/src/modules/permission/module-route-access.ts#button',
    '#WRITE_BUTTONS',
    '#codeOf',
    '#reviewContext',
  ],
  'apps/api/src/modules/talent-review/access.ts#trimReview': [
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    '#codeOf',
  ],
  'apps/api/src/modules/talent-review/approval-adapter.ts#talentReviewAdapter': ['#unavailable'],
  'apps/api/src/modules/talent-review/calc-rule-input.ts#calcItem': ['#uuid'],
  'apps/api/src/modules/talent-review/calc-rule-input.ts#calcRuleCreate': [
    '#calcItem',
    '#name',
    'packages/domain/src/talent-review/calc-rule.ts#CALC_RULE_WINDOWS',
  ],
  'apps/api/src/modules/talent-review/calc-rule-input.ts#calcRulePatch': ['#calcRuleCreate'],
  'apps/api/src/modules/talent-review/calc-rule-routes.ts#CALC_RULES': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/calc-rule-routes.ts#optionalCatalogAccess': ['#requireCatalogAccess'],
  'apps/api/src/modules/talent-review/calc-rule-routes.ts#patchCatalogAccess': [
    '#optionalCatalogAccess',
    '#requireCatalogAccess',
  ],
  'apps/api/src/modules/talent-review/calc-rule-routes.ts#registerCalcRuleRoutes': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#configEnvelope',
    'apps/api/src/modules/talent-review/access.ts#configScopeSql',
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    'apps/api/src/modules/talent-review/access.ts#requireFilterVisible',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/calc-rule-input.ts#calcRuleCreate',
    'apps/api/src/modules/talent-review/calc-rule-input.ts#calcRulePatch',
    '#CALC_RULES',
    '#patchCatalogAccess',
    '#requireCatalogAccess',
    '#runWrite',
    'apps/api/src/modules/talent-review/calc-rule-service.ts#createCalcRule',
    'apps/api/src/modules/talent-review/calc-rule-service.ts#deleteCalcRule',
    'apps/api/src/modules/talent-review/calc-rule-service.ts#updateCalcRule',
    'apps/api/src/modules/talent-review/calc-rule-view.ts#CALC_RULE',
    'apps/api/src/modules/talent-review/calc-rule-view.ts#loadCalcRuleView',
    'apps/api/src/modules/talent-review/calc-rule-view.ts#withItems',
    'apps/api/src/modules/talent-review/config-kit.ts#listConfig',
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#pageQuery',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/calc-rule-routes.ts#requireCatalogAccess': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    '#REFERENCE_COLUMNS',
  ],
  'apps/api/src/modules/talent-review/calc-rule-routes.ts#runWrite': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/calc-rule-service.ts#presentHints',
    'apps/api/src/modules/talent-review/calc-rule-service.ts#requireItemsReferenceable',
    'apps/api/src/modules/talent-review/config-kit.ts#concurrentOr',
  ],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#analyzeOnce': [
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    '#failure',
    '#loadVisibleCatalog',
    '#reject',
    'packages/domain/src/talent-review/calc-rule.ts#analyzeCalcItems',
    'packages/domain/src/talent-review/calc-rule.ts#targetNotAllowed',
  ],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#createCalcRule': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable',
    '#itemRow',
    '#prepareItems',
    'apps/api/src/modules/talent-review/calc-rule-view.ts#CALC_RULE',
    'apps/api/src/modules/talent-review/config-kit.ts#createConfig',
  ],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#deleteCalcRule': [
    'apps/api/src/modules/talent-review/calc-rule-view.ts#CALC_RULE',
    'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig',
  ],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#failure': ['#reject'],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#loadVisibleCatalog': ['#loadFullCatalog', '#visibleOf'],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#prepareItems': ['#analyzeOnce', '#lockFields'],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#presentHints': [
    '#CYCLE_HIDDEN',
    '#CYCLE_KINDS',
    '#OTHER_HIDDEN',
    '#UNVERIFIABLE',
    '#loadFullCatalog',
    '#visibleOf',
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_CONTEXT_FIELDS',
    'packages/domain/src/talent-review/calc-rule.ts#analyzeCalcItems',
    'packages/domain/src/talent-review/calc-rule.ts#formulaPath',
  ],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#requireItemsReferenceable': [
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    '#loadVisibleCatalog',
    '#reject',
    'packages/domain/src/talent-review/calc-rule.ts#unreferenceableItem',
  ],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#syncItems': ['#itemRow'],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#updateCalcRule': [
    '#prepareItems',
    '#syncItems',
    'apps/api/src/modules/talent-review/calc-rule-view.ts#CALC_RULE',
    'apps/api/src/modules/talent-review/calc-rule-view.ts#loadCalcRuleView',
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    'apps/api/src/modules/talent-review/config-kit.ts#requireSeeAllToRename',
    'apps/api/src/modules/talent-review/config-kit.ts#uniqueOr',
  ],
  'apps/api/src/modules/talent-review/calc-rule-service.ts#visibleOf': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
  ],
  'apps/api/src/modules/talent-review/calc-rule-view.ts#CALC_RULE': ['#row', '#selectRows', '#withItems'],
  'apps/api/src/modules/talent-review/calc-rule-view.ts#loadCalcRuleView': ['#CALC_RULE'],
  'apps/api/src/modules/talent-review/calc-rule-view.ts#selectRows': ['#row'],
  'apps/api/src/modules/talent-review/config-input.ts#categoryCreate': ['#name', '#sortNo'],
  'apps/api/src/modules/talent-review/config-input.ts#categoryPatch': ['#categoryCreate'],
  'apps/api/src/modules/talent-review/config-input.ts#fieldCreate': [
    '#fieldOption',
    '#name',
    '#sortNo',
    '#uuid',
    'packages/domain/src/talent-review/fields.ts#FIELD_MAX_PRECISION',
    'packages/domain/src/talent-review/fields.ts#TALENT_REVIEW_FIELD_GROUPS',
    'packages/domain/src/talent-review/fields.ts#TALENT_REVIEW_FIELD_KINDS',
    'packages/domain/src/talent-review/fields.ts#TALENT_REVIEW_PAIR_ROLES',
  ],
  'apps/api/src/modules/talent-review/config-input.ts#fieldOption': ['#sortNo'],
  'apps/api/src/modules/talent-review/config-input.ts#fieldPatch': ['#fieldCreate', '#name', '#sortNo'],
  'apps/api/src/modules/talent-review/config-input.ts#gradeItem': ['#score'],
  'apps/api/src/modules/talent-review/config-input.ts#level': ['#score'],
  'apps/api/src/modules/talent-review/config-input.ts#moduleGradeCreate': ['#gradeItem', '#name'],
  'apps/api/src/modules/talent-review/config-input.ts#moduleGradePatch': ['#moduleGradeCreate'],
  'apps/api/src/modules/talent-review/config-input.ts#roleCreate': [
    '#name',
    '#sortNo',
    'packages/domain/src/talent-review/fields.ts#TALENT_REVIEW_ROLE_RESOLVERS',
  ],
  'apps/api/src/modules/talent-review/config-input.ts#rolePatch': ['#roleCreate'],
  'apps/api/src/modules/talent-review/config-input.ts#scoreRuleCreate': [
    '#level',
    '#name',
    '#score',
    'packages/domain/src/talent-review/scoring-config.ts#SCORE_DISPLAYS',
    'packages/domain/src/talent-review/scoring-config.ts#SCORE_RULE_KINDS',
  ],
  'apps/api/src/modules/talent-review/config-input.ts#scoreRulePatch': ['#scoreRuleCreate'],
  'apps/api/src/modules/talent-review/config-input.ts#settingsPatch': ['#uuid'],
  'apps/api/src/modules/talent-review/config-kit.ts#auditConfig': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_AUDIT_ACTIONS',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/talent-review/config-kit.ts#configReferrer': ['#guards'],
  'apps/api/src/modules/talent-review/config-kit.ts#createConfig': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable',
    '#auditConfig',
    '#loadConfig',
    '#uniqueOr',
  ],
  'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig': [
    '#auditConfig',
    '#configReferrer',
    '#loadConfig',
    '#lockConfigRow',
  ],
  'apps/api/src/modules/talent-review/config-kit.ts#listConfig': ['#visibleOrder'],
  'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow': [
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
  ],
  'apps/api/src/modules/talent-review/config-kit.ts#updateConfig': [
    '#auditConfig',
    '#loadConfig',
    '#lockConfigRow',
    '#requireSeeAllToRename',
    '#uniqueOr',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#CATEGORIES': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#FIELDS': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#ROLES': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#SETTINGS': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#detailResponse': [
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/config-kit.ts#loadConfig',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#listResponse': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#configEnvelope',
    'apps/api/src/modules/talent-review/access.ts#configScopeSql',
    'apps/api/src/modules/talent-review/access.ts#requireFilterVisible',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/config-kit.ts#listConfig',
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#pageQuery',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#registerCategories': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/config-input.ts#categoryCreate',
    'apps/api/src/modules/talent-review/config-input.ts#categoryPatch',
    'apps/api/src/modules/talent-review/config-kit.ts#createConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#updateConfig',
    '#CATEGORIES',
    '#detailResponse',
    '#listResponse',
    '#runWrite',
    '#visibleTo',
    'apps/api/src/modules/talent-review/config-service.ts#CATEGORY',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#registerConfigRoutes': [
    '#registerCategories',
    '#registerFields',
    '#registerRoles',
    '#registerSettings',
    'apps/api/src/modules/talent-review/scoring-routes.ts#registerScoringRoutes',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#registerFields': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/config-input.ts#fieldCreate',
    'apps/api/src/modules/talent-review/config-input.ts#fieldPatch',
    '#FIELDS',
    '#detailResponse',
    '#listResponse',
    '#requirePairUpdate',
    '#runWrite',
    '#visibleTo',
    'apps/api/src/modules/talent-review/field-service.ts#FIELD',
    'apps/api/src/modules/talent-review/field-service.ts#createField',
    'apps/api/src/modules/talent-review/field-service.ts#deleteField',
    'apps/api/src/modules/talent-review/field-service.ts#updateField',
    'apps/api/src/modules/talent-review/field-service.ts#withOptions',
    'apps/api/src/modules/talent-review/rename-disclosure.ts#resolveCalcDisclosure',
    'apps/api/src/modules/talent-review/rename-disclosure.ts#resolveFieldColumnsViewable',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#registerRoles': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/config-input.ts#roleCreate',
    'apps/api/src/modules/talent-review/config-input.ts#rolePatch',
    'apps/api/src/modules/talent-review/config-kit.ts#createConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#updateConfig',
    '#ROLES',
    '#detailResponse',
    '#listResponse',
    '#runWrite',
    '#visibleTo',
    'apps/api/src/modules/talent-review/config-service.ts#ROLE',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#registerSettings': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/config-input.ts#settingsPatch',
    '#SETTINGS',
    '#runWrite',
    'apps/api/src/modules/talent-review/settings-service.ts#loadSettings',
    'apps/api/src/modules/talent-review/settings-service.ts#updateSettings',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#revision',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#requirePairUpdate': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#runWrite': [
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/config-kit.ts#concurrentOr',
  ],
  'apps/api/src/modules/talent-review/config-routes.ts#visibleTo': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
  ],
  'apps/api/src/modules/talent-review/config-service.ts#CATEGORY': ['#audited'],
  'apps/api/src/modules/talent-review/config-service.ts#ROLE': ['#audited'],
  'apps/api/src/modules/talent-review/field-catalog.ts#bumpFieldCatalog': ['#BUMPED', '#ensureRow'],
  'apps/api/src/modules/talent-review/field-catalog.ts#lockFieldCatalog': ['#ensureRow'],
  'apps/api/src/modules/talent-review/field-rename-guard.ts#boundItemsReferencing': ['#rowsOf'],
  'apps/api/src/modules/talent-review/field-rename-guard.ts#guardFieldRename': [
    'apps/api/src/modules/talent-review/field-catalog.ts#lockFieldCatalog',
    '#boundItemsReferencing',
    '#breaksMessage',
    '#partitionBroken',
    '#solidifyCandidates',
    'apps/api/src/modules/talent-review/text-fallback.ts#textFallbackItems',
    'packages/domain/src/talent-review/formula-rename.ts#checkRenameRoundTrip',
  ],
  'apps/api/src/modules/talent-review/field-rename-guard.ts#partitionBroken': ['#visibleTo'],
  'apps/api/src/modules/talent-review/field-rename-guard.ts#solidifyCandidates': ['#rowsOf'],
  'apps/api/src/modules/talent-review/field-rename-guard.ts#visibleTo': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
  ],
  'apps/api/src/modules/talent-review/field-service.ts#FIELD': ['#row', '#selectRows', '#withOptions'],
  'apps/api/src/modules/talent-review/field-service.ts#checkOptions': ['#hasOptions', '#invalid'],
  'apps/api/src/modules/talent-review/field-service.ts#createField': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable',
    'apps/api/src/modules/talent-review/config-kit.ts#createConfig',
    'apps/api/src/modules/talent-review/field-catalog.ts#bumpFieldCatalog',
    '#FIELD',
    '#checkOptions',
    '#insertOptions',
    '#invalid',
    '#linkPartner',
    '#lockPartner',
    'packages/domain/src/talent-review/fields.ts#FIELD_DEFAULT_PRECISION',
  ],
  'apps/api/src/modules/talent-review/field-service.ts#deleteField': [
    'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig',
    'apps/api/src/modules/talent-review/field-catalog.ts#bumpFieldCatalog',
    '#FIELD',
  ],
  'apps/api/src/modules/talent-review/field-service.ts#linkPartner': [
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    '#loadFieldView',
  ],
  'apps/api/src/modules/talent-review/field-service.ts#loadFieldView': ['#FIELD'],
  'apps/api/src/modules/talent-review/field-service.ts#lockPartner': [
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    '#invalid',
  ],
  'apps/api/src/modules/talent-review/field-service.ts#selectRows': ['#row'],
  'apps/api/src/modules/talent-review/field-service.ts#syncOptions': ['#insertOptions', '#invalid'],
  'apps/api/src/modules/talent-review/field-service.ts#updateField': [
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    'apps/api/src/modules/talent-review/config-kit.ts#requireSeeAllToRename',
    'apps/api/src/modules/talent-review/config-kit.ts#uniqueOr',
    'apps/api/src/modules/talent-review/field-catalog.ts#bumpFieldCatalog',
    'apps/api/src/modules/talent-review/field-rename-guard.ts#guardFieldRename',
    '#FIELD',
    '#checkOptions',
    '#invalid',
    '#loadFieldView',
    '#syncOptions',
  ],
  'apps/api/src/modules/talent-review/health-port.ts#registerOrgHealthComputePort': ['#registered'],
  'apps/api/src/modules/talent-review/matrix-input.ts#axisLevel': [
    '#levelNo',
    '#name',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_AXES',
  ],
  'apps/api/src/modules/talent-review/matrix-input.ts#cell': [
    '#levelNo',
    '#name',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_MAX_LEVELS',
  ],
  'apps/api/src/modules/talent-review/matrix-input.ts#levelNo': [
    'packages/domain/src/talent-review/matrix.ts#MATRIX_MAX_LEVELS',
  ],
  'apps/api/src/modules/talent-review/matrix-input.ts#matrixCreate': [
    '#axisLevel',
    '#cell',
    '#name',
    '#positionField',
    '#sortNo',
    '#uuid',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_MAX_LEVELS',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_PLACEMENT_SOURCES',
  ],
  'apps/api/src/modules/talent-review/matrix-input.ts#matrixPatch': ['#matrixCreate'],
  'apps/api/src/modules/talent-review/matrix-input.ts#percent': ['#twoDecimals'],
  'apps/api/src/modules/talent-review/matrix-input.ts#positionField': [
    '#uuid',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_POSITION_ROLES',
  ],
  'apps/api/src/modules/talent-review/matrix-input.ts#ratioGroupCreate': [
    '#name',
    '#rule',
    'packages/domain/src/talent-review/matrix.ts#RATIO_CONTROL_MODES',
    'packages/domain/src/talent-review/matrix.ts#RATIO_CONTROL_SCOPES',
  ],
  'apps/api/src/modules/talent-review/matrix-input.ts#ratioGroupPatch': ['#ratioGroupCreate'],
  'apps/api/src/modules/talent-review/matrix-input.ts#rule': [
    '#percent',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_MAX_LEVELS',
    'packages/domain/src/talent-review/matrix.ts#RATIO_OPERATORS',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#GROUPS': ['#MATRICES'],
  'apps/api/src/modules/talent-review/matrix-routes.ts#MATRICES': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#recheck': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#recheckFields': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    '#recheck',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#registerMatrixRoutes': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#configEnvelope',
    'apps/api/src/modules/talent-review/access.ts#configScopeSql',
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    'apps/api/src/modules/talent-review/access.ts#requireFilterVisible',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/config-kit.ts#listConfig',
    'apps/api/src/modules/talent-review/matrix-input.ts#matrixCreate',
    'apps/api/src/modules/talent-review/matrix-input.ts#matrixPatch',
    '#MATRICES',
    '#referencedFields',
    '#registerRatioGroupRoutes',
    '#requireFieldReference',
    '#runDelete',
    '#runWrite',
    'apps/api/src/modules/talent-review/matrix-service.ts#createMatrix',
    'apps/api/src/modules/talent-review/matrix-service.ts#deleteMatrix',
    'apps/api/src/modules/talent-review/matrix-service.ts#updateMatrix',
    'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX',
    'apps/api/src/modules/talent-review/matrix-view.ts#loadMatrixView',
    'apps/api/src/modules/talent-review/matrix-view.ts#withChildren',
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#pageQuery',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#registerRatioGroupRoutes': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/matrix-input.ts#ratioGroupCreate',
    'apps/api/src/modules/talent-review/matrix-input.ts#ratioGroupPatch',
    '#GROUPS',
    '#runWrite',
    'apps/api/src/modules/talent-review/matrix-service.ts#createRatioGroup',
    'apps/api/src/modules/talent-review/matrix-service.ts#deleteRatioGroup',
    'apps/api/src/modules/talent-review/matrix-service.ts#updateRatioGroup',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#requireFieldReference': [
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#runDelete': ['#recheck', '#runGuarded'],
  'apps/api/src/modules/talent-review/matrix-routes.ts#runGuarded': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/matrix-service.ts#requireReferencesVisible',
  ],
  'apps/api/src/modules/talent-review/matrix-routes.ts#runWrite': ['#recheckFields', '#runGuarded'],
  'apps/api/src/modules/talent-review/matrix-service.ts#checkAgainstFields': [
    '#invalid',
    '#reject',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_AXES',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_AXIS_FIELD_KINDS',
    'packages/domain/src/talent-review/matrix.ts#MATRIX_POSITION_FIELD_GROUP',
    'packages/domain/src/talent-review/matrix.ts#checkAxisLevels',
    'packages/domain/src/talent-review/matrix.ts#checkCells',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#checkRules': [
    '#invalid',
    'packages/domain/src/talent-review/matrix.ts#checkRatioRule',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#checkStructure': ['#reject'],
  'apps/api/src/modules/talent-review/matrix-service.ts#createMatrix': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable',
    'apps/api/src/modules/talent-review/config-kit.ts#createConfig',
    '#cellRow',
    '#insertPositions',
    '#levelRows',
    '#lockPositionFields',
    '#validateShape',
    'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#createRatioGroup': [
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    '#checkRules',
    '#clearDefault',
    '#duplicateGroup',
    '#finishGroupWrite',
    '#insertRules',
    'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX',
    'apps/api/src/modules/talent-review/matrix-view.ts#loadMatrixView',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#deleteMatrix': [
    'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig',
    '#lockPositionFields',
    'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#deleteRatioGroup': [
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    '#finishGroupWrite',
    '#groupGuards',
    '#requireGroup',
    'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX',
    'apps/api/src/modules/talent-review/matrix-view.ts#loadMatrixView',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#finishGroupWrite': [
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    'apps/api/src/modules/talent-review/matrix-view.ts#loadMatrixView',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#lockPositionFields': ['#positionLockKey'],
  'apps/api/src/modules/talent-review/matrix-service.ts#positionLockKey': [
    'apps/api/src/advisory-lock.ts#asUuid',
    'apps/api/src/advisory-lock.ts#lockKey',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#reject': ['#invalid'],
  'apps/api/src/modules/talent-review/matrix-service.ts#requireReferencesVisible': [
    '#loadFieldFacts',
    '#requireVisibleRefs',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#requireVisibleRefs': [
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#syncLevelsAndCells': ['#cellRow', '#levelRows'],
  'apps/api/src/modules/talent-review/matrix-service.ts#updateMatrix': [
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    'apps/api/src/modules/talent-review/config-kit.ts#requireSeeAllToRename',
    'apps/api/src/modules/talent-review/config-kit.ts#uniqueOr',
    '#heldRefs',
    '#insertPositions',
    '#lockPositionFields',
    '#refIds',
    '#requireReferencesVisible',
    '#samePositions',
    '#syncLevelsAndCells',
    '#validateShape',
    'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX',
    'apps/api/src/modules/talent-review/matrix-view.ts#loadMatrixView',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#updateRatioGroup': [
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    '#checkRules',
    '#clearDefault',
    '#duplicateGroup',
    '#finishGroupWrite',
    '#insertRules',
    '#requireGroup',
    'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX',
    'apps/api/src/modules/talent-review/matrix-view.ts#loadMatrixView',
  ],
  'apps/api/src/modules/talent-review/matrix-service.ts#validateShape': [
    '#checkAgainstFields',
    '#checkStructure',
    '#loadFieldFacts',
    '#refIds',
    '#requireVisibleRefs',
  ],
  'apps/api/src/modules/talent-review/matrix-view.ts#MATRIX': ['#row', '#selectRows', '#withChildren'],
  'apps/api/src/modules/talent-review/matrix-view.ts#loadGroups': ['#number'],
  'apps/api/src/modules/talent-review/matrix-view.ts#loadMatrixView': ['#MATRIX'],
  'apps/api/src/modules/talent-review/matrix-view.ts#selectRows': ['#row'],
  'apps/api/src/modules/talent-review/matrix-view.ts#withChildren': ['#byMatrix', '#loadGroups', '#roleRank'],
  'apps/api/src/modules/talent-review/module-grade-service.ts#MODULE_GRADE': ['#row', '#withItems'],
  'apps/api/src/modules/talent-review/module-grade-service.ts#checkItems': [
    'packages/domain/src/talent-review/scoring-config.ts#gradeItemsProblem',
  ],
  'apps/api/src/modules/talent-review/module-grade-service.ts#createModuleGrade': [
    'apps/api/src/modules/talent-review/config-kit.ts#createConfig',
    '#MODULE_GRADE',
    '#checkItems',
    '#itemRows',
  ],
  'apps/api/src/modules/talent-review/module-grade-service.ts#updateModuleGrade': [
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    'apps/api/src/modules/talent-review/config-kit.ts#requireSeeAllToRename',
    'apps/api/src/modules/talent-review/config-kit.ts#uniqueOr',
    '#MODULE_GRADE',
    '#checkItems',
    '#itemRows',
  ],
  'apps/api/src/modules/talent-review/readiness-input.ts#readinessCreate': [
    'packages/domain/src/talent-review/catalog.ts#READINESS_COLOR_PATTERN',
  ],
  'apps/api/src/modules/talent-review/readiness-input.ts#readinessPatch': ['#readinessCreate'],
  'apps/api/src/modules/talent-review/readiness-port.ts#columns': ['#R'],
  'apps/api/src/modules/talent-review/readiness-port.ts#readinessPort': ['#R', '#columns'],
  'apps/api/src/modules/talent-review/readiness-port.ts#readinessReferrer': ['#guards'],
  'apps/api/src/modules/talent-review/readiness-service.ts#LIST_ORDER': ['#R'],
  'apps/api/src/modules/talent-review/readiness-service.ts#audit': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_AUDIT_ACTIONS',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/talent-review/readiness-service.ts#createReadiness': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable',
    '#R',
    '#audit',
    '#loadReadinessView',
    '#unique',
  ],
  'apps/api/src/modules/talent-review/readiness-service.ts#deleteReadiness': [
    'apps/api/src/modules/talent-review/readiness-port.ts#readinessReferrer',
    '#R',
    '#audit',
    '#loadReadinessView',
    '#lockForWrite',
  ],
  'apps/api/src/modules/talent-review/readiness-service.ts#listReadinessViews': [
    'apps/api/src/modules/talent-review/config-kit.ts#visibleOrder',
    '#LIST_ORDER',
    '#R',
    '#view',
  ],
  'apps/api/src/modules/talent-review/readiness-service.ts#loadReadinessView': ['#R', '#view'],
  'apps/api/src/modules/talent-review/readiness-service.ts#lockForWrite': [
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    '#R',
  ],
  'apps/api/src/modules/talent-review/readiness-service.ts#updateReadiness': [
    '#R',
    '#audit',
    '#loadReadinessView',
    '#lockForWrite',
    '#unique',
  ],
  'apps/api/src/modules/talent-review/readiness-service.ts#view': ['#R'],
  'apps/api/src/modules/talent-review/rename-disclosure.ts#resolveCalcDisclosure': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
  ],
  'apps/api/src/modules/talent-review/rename-disclosure.ts#resolveFieldColumnsViewable': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    '#REFERENCE_COLUMNS',
  ],
  'apps/api/src/modules/talent-review/routes.ts#PATH': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/routes.ts#registerTalentReviewRoutes': [
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#configEnvelope',
    'apps/api/src/modules/talent-review/access.ts#configScopeSql',
    'apps/api/src/modules/talent-review/access.ts#notFoundMessage',
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    'apps/api/src/modules/talent-review/access.ts#requireFilterVisible',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/calc-rule-routes.ts#registerCalcRuleRoutes',
    'apps/api/src/modules/talent-review/config-routes.ts#registerConfigRoutes',
    'apps/api/src/modules/talent-review/matrix-routes.ts#registerMatrixRoutes',
    'apps/api/src/modules/talent-review/readiness-input.ts#readinessCreate',
    'apps/api/src/modules/talent-review/readiness-input.ts#readinessPatch',
    'apps/api/src/modules/talent-review/readiness-service.ts#createReadiness',
    'apps/api/src/modules/talent-review/readiness-service.ts#deleteReadiness',
    'apps/api/src/modules/talent-review/readiness-service.ts#listReadinessViews',
    'apps/api/src/modules/talent-review/readiness-service.ts#loadReadinessView',
    'apps/api/src/modules/talent-review/readiness-service.ts#updateReadiness',
    '#PATH',
    '#runWrite',
    'apps/api/src/modules/talent/http.ts#booleanQuery',
    'apps/api/src/modules/talent/http.ts#pageQuery',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/routes.ts#runWrite': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigVisible',
    'apps/api/src/modules/talent-review/access.ts#reviewScope',
    'apps/api/src/modules/talent-review/access.ts#trimReview',
  ],
  'apps/api/src/modules/talent-review/score-rule-service.ts#SCORE_RULE': ['#row', '#withLevels'],
  'apps/api/src/modules/talent-review/score-rule-service.ts#checkShape': ['#invalid'],
  'apps/api/src/modules/talent-review/score-rule-service.ts#createScoreRule': [
    'apps/api/src/modules/talent-review/config-kit.ts#createConfig',
    '#SCORE_RULE',
    '#checkShape',
    '#levelRows',
  ],
  'apps/api/src/modules/talent-review/score-rule-service.ts#updateScoreRule': [
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    'apps/api/src/modules/talent-review/config-kit.ts#lockConfigRow',
    'apps/api/src/modules/talent-review/config-kit.ts#requireSeeAllToRename',
    'apps/api/src/modules/talent-review/config-kit.ts#uniqueOr',
    '#SCORE_RULE',
    '#checkShape',
    '#invalid',
    '#levelRows',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#MODULE_GRADES': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#SCORE_RULES': [
    'apps/api/src/modules/talent-review/access.ts#TALENT_REVIEW_BASE',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#recheck': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/talent-review/access.ts#codeOf',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#recheckFields': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    '#recheck',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#registerModuleGrades': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/config-input.ts#moduleGradeCreate',
    'apps/api/src/modules/talent-review/config-input.ts#moduleGradePatch',
    'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig',
    'apps/api/src/modules/talent-review/config-routes.ts#detailResponse',
    'apps/api/src/modules/talent-review/config-routes.ts#listResponse',
    'apps/api/src/modules/talent-review/module-grade-service.ts#MODULE_GRADE',
    'apps/api/src/modules/talent-review/module-grade-service.ts#createModuleGrade',
    'apps/api/src/modules/talent-review/module-grade-service.ts#updateModuleGrade',
    'apps/api/src/modules/talent-review/module-grade-service.ts#withItems',
    '#MODULE_GRADES',
    '#runScoringDelete',
    '#runScoringWrite',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#registerScoreRules': [
    'apps/api/src/modules/talent-review/access.ts#checkWriteFields',
    'apps/api/src/modules/talent-review/access.ts#reviewContext',
    'apps/api/src/modules/talent-review/access.ts#reviewWriteContext',
    'apps/api/src/modules/talent-review/config-input.ts#scoreRuleCreate',
    'apps/api/src/modules/talent-review/config-input.ts#scoreRulePatch',
    'apps/api/src/modules/talent-review/config-kit.ts#deleteConfig',
    'apps/api/src/modules/talent-review/config-routes.ts#detailResponse',
    'apps/api/src/modules/talent-review/config-routes.ts#listResponse',
    'apps/api/src/modules/talent-review/score-rule-service.ts#SCORE_RULE',
    'apps/api/src/modules/talent-review/score-rule-service.ts#createScoreRule',
    'apps/api/src/modules/talent-review/score-rule-service.ts#updateScoreRule',
    'apps/api/src/modules/talent-review/score-rule-service.ts#withLevels',
    '#SCORE_RULES',
    '#runScoringDelete',
    '#runScoringWrite',
    'apps/api/src/modules/talent/http.ts#parseBody',
    'apps/api/src/modules/talent/http.ts#requireNew',
    'apps/api/src/modules/talent/http.ts#revision',
    'apps/api/src/modules/talent/http.ts#uuidParam',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#registerScoringRoutes': [
    '#registerModuleGrades',
    '#registerScoreRules',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#runGuarded': [
    'apps/api/src/modules/talent-review/access.ts#trimReview',
    'apps/api/src/modules/talent-review/config-routes.ts#visibleTo',
  ],
  'apps/api/src/modules/talent-review/scoring-routes.ts#runScoringDelete': ['#recheck', '#runGuarded'],
  'apps/api/src/modules/talent-review/scoring-routes.ts#runScoringWrite': ['#recheckFields', '#runGuarded'],
  'apps/api/src/modules/talent-review/settings-service.ts#loadSettings': ['#DEFAULTS', '#columns'],
  'apps/api/src/modules/talent-review/settings-service.ts#updateSettings': [
    'apps/api/src/modules/talent-review/access.ts#requireConfigCreatable',
    'apps/api/src/modules/talent-review/config-kit.ts#auditConfig',
    '#columns',
    '#loadSettings',
    '#requireActiveMember',
  ],
  'apps/api/src/modules/talent-review/text-fallback.ts#textFallbackItems': [
    '#rowsOf',
    'packages/domain/src/talent-review/calc-rule.ts#fieldNameTerms',
    'packages/domain/src/talent-review/calc-rule.ts#textMentionsField',
  ],
};
