/**
 * 直接依赖图：区域 api-modules-employee-self-service（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/employee-self-service/access.ts#SELF_BUTTONS': [
    'packages/domain/src/platform/employee-self-service.ts#EMPLOYEE_SELF_SERVICE_BUTTONS',
  ],
  'apps/api/src/modules/employee-self-service/access.ts#boundEmployee': [
    'apps/api/src/modules/avatar/references.ts#employeeAvatars',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employee-self-service/access.ts#requireSelfServiceButtons': [
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/platform/employee-self-service.ts#EMPLOYEE_SELF_SERVICE_BUTTONS',
  ],
  'apps/api/src/modules/employee-self-service/access.ts#selfAccess': [
    '#COMMAND_FIELDS',
    '#boundEmployee',
    '#selfButtonGranted',
    'apps/api/src/modules/employee-self-service/policy.ts#PROTOCOL_FIELDS',
    'apps/api/src/modules/employee-self-service/policy.ts#employeeFieldPolicy',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFieldsInTransaction',
    'apps/api/src/modules/permission/module-access.ts#registerScopeProvider',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/permission/scope-types.ts#EMPTY_SCOPE',
    'apps/api/src/modules/transfer/employee-policy.ts#EMPLOYEE_READONLY_FIELDS',
    'apps/api/src/tenant-context.ts#tenantOf',
  ],
  'apps/api/src/modules/employee-self-service/access.ts#selfButtonGranted': [
    '#SELF_BUTTONS',
    'apps/api/src/modules/employee-self-service/policy.ts#employeeFieldPolicy',
  ],
  'apps/api/src/modules/employee-self-service/access.ts#transferFieldAccess': [
    'apps/api/src/modules/employee-self-service/policy.ts#employeeFieldPolicy',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFieldsInTransaction',
  ],
  'apps/api/src/modules/employee-self-service/development-channel.ts#names': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employee-self-service/development-channel.ts#ownDevelopmentChannel': [
    '#PAGE',
    '#names',
    'apps/api/src/modules/employee-self-service/page-permission.ts#employeePageGranted',
    'apps/api/src/modules/qualification/development-channel-data.ts#channelOverview',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_APP',
  ],
  'apps/api/src/modules/employee-self-service/disclosure.ts#discloseOwnRecord': [
    'apps/api/src/modules/employee-self-service/field-disclosure.ts#visibleFields',
    'apps/api/src/modules/employee-self-service/references.ts#referenceLabels',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
  ],
  'apps/api/src/modules/employee-self-service/page-permission.ts#employeePageGranted': [
    'apps/api/src/modules/employee-self-service/access.ts#boundEmployee',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/permission/subject.ts#loadGrantedObjectPermissions',
    'apps/api/src/modules/permission/subject.ts#loadObjectPermissions',
    'packages/domain/src/permission/decide.ts#buttonResource',
    'packages/domain/src/platform/employee-self-service.ts#EMPLOYEE_SELF_SERVICE_CODE',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_APP',
    'packages/domain/src/qualification/catalog.ts#QUALIFICATION_PAGES',
  ],
  'apps/api/src/modules/employee-self-service/policy.ts#DEFAULT_BUTTONS': [
    'packages/domain/src/platform/employee-self-service.ts#EMPLOYEE_SELF_SERVICE_BUTTONS',
  ],
  'apps/api/src/modules/employee-self-service/policy.ts#EMPLOYEE_PROFILE_CODE': [
    'packages/domain/src/platform/employee-self-service.ts#EMPLOYEE_SELF_SERVICE_CODE',
  ],
  'apps/api/src/modules/employee-self-service/policy.ts#employeeFieldPolicy': [
    '#DEFAULT_BUTTONS',
    '#EMPLOYEE_PROFILE_CODE',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    'apps/api/src/modules/permission/subject.ts#loadObjectPermissions',
    'apps/api/src/modules/transfer/employee-policy.ts#EMPLOYEE_READONLY_FIELDS',
    'packages/domain/src/platform/employee-self-service.ts#EMPLOYEE_DEFAULT_CREATE',
    'packages/domain/src/platform/employee-self-service.ts#EMPLOYEE_DEFAULT_EDIT_FIELDS',
  ],
  'apps/api/src/modules/employee-self-service/queries.ts#currentRecord': [
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employee-self-service/queries.ts#ownApplication': ['#ownApplications'],
  'apps/api/src/modules/employee-self-service/queries.ts#ownApplications': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employee-self-service/queries.ts#ownRecords': [
    '#employmentStatus',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employee-self-service/references.ts#referenceChoices': [
    'apps/api/src/modules/employee-self-service/access.ts#transferFieldAccess',
    '#JOB_FIELDS',
    '#PERSON_FIELDS',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/employment/employees.ts#listEmployees',
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'apps/api/src/modules/job/read-model.ts#listJobObjects',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScopeInTransaction',
    'apps/api/src/modules/transfer/configuration.ts#readTransferSettings',
    'apps/api/src/modules/transfer/employee-managers.ts#managerChoices',
    'apps/api/src/modules/transfer/employee-policy.ts#EMPLOYEE_READONLY_FIELDS',
  ],
  'apps/api/src/modules/employee-self-service/references.ts#referenceLabels': [
    '#JOB_FIELDS',
    '#PERSON_FIELDS',
    'apps/api/src/modules/employment/employees.ts#employeeName',
    'apps/api/src/modules/job/read-model.ts#loadJobObject',
    'apps/api/src/modules/org/read-model.ts#loadOrgSnapshot',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:GET /applications': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    'apps/api/src/modules/employee-self-service/access.ts#transferFieldAccess',
    'apps/api/src/modules/employee-self-service/field-disclosure.ts#visibleFields',
    'apps/api/src/modules/employee-self-service/queries.ts#applicationStatus',
    'apps/api/src/modules/employee-self-service/queries.ts#ownApplications',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/transfer/configuration.ts#readTransferCatalog',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:GET /applications/:id': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    'apps/api/src/modules/employee-self-service/disclosure.ts#discloseOwnRecord',
    'apps/api/src/modules/employee-self-service/queries.ts#applicationStatus',
    'apps/api/src/modules/employee-self-service/queries.ts#ownApplication',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:GET /development-channel': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:GET /employees/:id/development-channel': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:GET /employees/:id/records': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    'apps/api/src/modules/employee-self-service/disclosure.ts#discloseOwnRecord',
    'apps/api/src/modules/employee-self-service/queries.ts#ownRecords',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:GET /profile': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    'apps/api/src/modules/employee-self-service/disclosure.ts#discloseOwnRecord',
    'apps/api/src/modules/employee-self-service/queries.ts#currentRecord',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:GET /transfer/references/:code': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    'apps/api/src/modules/employee-self-service/references.ts#referenceChoices',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:POST /transfer': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    '#selfTransferGuard',
    'apps/api/src/modules/employee-self-service/transfer.ts#ownTransferInput',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/transfer/service.ts#createTransfer',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#route:POST /transfer/preview': [
    'apps/api/src/modules/employee-self-service/access.ts#selfAccess',
    'apps/api/src/modules/employee-self-service/transfer.ts#ownTransferPreview',
    'apps/api/src/modules/employment/context.ts#jsonBody',
  ],
  'apps/api/src/modules/employee-self-service/routes.ts#selfTransferGuard': [
    'apps/api/src/modules/employee-self-service/access.ts#requireSelfServiceButtons',
  ],
  'apps/api/src/modules/employee-self-service/transfer.ts#ownTransferInput': [
    'apps/api/src/modules/employee-self-service/access.ts#transferFieldAccess',
    '#inputSchema',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/service.ts#normalizeTransferInput',
    'apps/api/src/modules/transfer/service.ts#requireTransferWrite',
  ],
  'apps/api/src/modules/employee-self-service/transfer.ts#ownTransferPreview': [
    'apps/api/src/modules/employee-self-service/access.ts#requireSelfServiceButtons',
    'apps/api/src/modules/employee-self-service/access.ts#transferFieldAccess',
    'apps/api/src/modules/employee-self-service/field-disclosure.ts#visibleFields',
    '#ownTransferInput',
    '#previewLabels',
    'apps/api/src/modules/employment/context.ts#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/configuration.ts#readTransferCatalog',
    'apps/api/src/modules/transfer/preview.ts#previewTransfer',
  ],
  'apps/api/src/modules/employee-self-service/transfer.ts#previewLabels': [
    'apps/api/src/modules/employee-self-service/references.ts#referenceLabels',
  ],
};
