/**
 * 直接依赖图：区域 api-modules-employment（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'apps/api/src/modules/employment/activation-checks.ts#DEFAULT_ESTABLISHMENT_CHECKS': [
    'apps/api/src/modules/establishment/employment-check.ts#employmentEstablishmentExceeded',
  ],
  'apps/api/src/modules/employment/activation-checks.ts#activateMaterializedLinkage': [
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness',
    'apps/api/src/modules/employment/transfer-linkage.ts#applyTransferLinkage',
  ],
  'apps/api/src/modules/employment/activation-checks.ts#activateWithJudgement': [
    '#activateMaterializedLinkage',
    '#activationFailureOf',
    '#precheck',
    '#ruleRejection',
    'apps/api/src/modules/employment/late-transfer.ts#postponeLateTransfer',
    'apps/api/src/modules/employment/linkage-dependency.ts#assertPredecessorsSettled',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness',
    'apps/api/src/modules/employment/transitions.ts#transitionEmployment',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity': ['#establishmentExceeded'],
  'apps/api/src/modules/employment/activation-checks.ts#checks': ['#DEFAULT_ESTABLISHMENT_CHECKS'],
  'apps/api/src/modules/employment/activation-checks.ts#establishmentExceeded': ['#checks'],
  'apps/api/src/modules/employment/activation-checks.ts#precheck': [
    '#establishmentExceeded',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/establishment/org-reader.ts#createTxOrgHierarchyReader',
    'apps/api/src/modules/job/read-model.ts#loadJobObject',
    'apps/api/src/modules/org/employment-validity.ts#employmentDepartmentDisable',
    'packages/domain/src/employment/late-execution.ts#resolveLateExecution',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/activation-checks.ts#ruleRejection': [
    '#RULE_REJECTIONS',
    'apps/api/src/modules/employment/errors.ts#EmploymentError',
  ],
  'apps/api/src/modules/employment/activation-service.ts#activateDueBusinesses': [
    'apps/api/src/modules/employment/activation-checks.ts#activateWithJudgement',
    '#dueQueue',
    'apps/api/src/modules/employment/activation-store.ts#PREDECESSOR_FAILED',
    'apps/api/src/modules/employment/activation-store.ts#REBUILD_REQUIRED',
    'apps/api/src/modules/employment/activation-store.ts#failureBlockerIds',
    'apps/api/src/modules/employment/activation-store.ts#recordActivationAttempt',
    'apps/api/src/modules/employment/activation-store.ts#unresolvedPredecessor',
    'apps/api/src/modules/employment/linkage-dependency.ts#blockingPredecessors',
  ],
  'apps/api/src/modules/employment/activation-service.ts#dueQueue': [
    'apps/api/src/modules/employment/activation-store.ts#pendingActivations',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/activation-service.ts#retryActivation': [
    '#activateDueBusinesses',
    'apps/api/src/modules/employment/activation-store.ts#PREDECESSOR_FAILED',
    'apps/api/src/modules/employment/activation-store.ts#activationPredecessors',
    'apps/api/src/modules/employment/activation-store.ts#unresolvedPredecessor',
    'apps/api/src/modules/employment/linkage-dependency.ts#blockingPredecessors',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/activation-store.ts#activationPredecessors': ['#pendingActivations'],
  'apps/api/src/modules/employment/activation-store.ts#activationSummary': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/activation-store.ts#isRebuildBlocker': ['#REBUILD_REQUIRED'],
  'apps/api/src/modules/employment/activation-store.ts#listActivationTodos': [
    '#pendingActivationState',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/context.ts#employmentScopePredicate',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#operationKey',
  ],
  'apps/api/src/modules/employment/activation-store.ts#pendingActivations': [
    '#QUEUE_LIMIT',
    '#blockerIds',
    '#pendingActivationState',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#operationKey',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/activation-store.ts#recordActivationAttempt': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/system-actor.ts#auditActor',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/approval-hooks.ts#employmentApprovalHooks': ['#hooks'],
  'apps/api/src/modules/employment/approval-hooks.ts#hooks': ['#unavailable'],
  'apps/api/src/modules/employment/batch-edit.ts#batchEditEmploymentRecords': [
    'apps/api/src/audit/record.ts#recordOperationLog',
    '#departmentOf',
    '#recordOwners',
    'apps/api/src/modules/employment/record-edit.ts#editEmploymentRecord',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/employment/batch-edit.ts#batchSchema': ['#MAX_BATCH_EDIT'],
  'apps/api/src/modules/employment/batch-edit.ts#normalizeBatchEdit': [
    '#MAX_BATCH_EDIT',
    '#batchSchema',
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
  ],
  'apps/api/src/modules/employment/batch-edit.ts#recordOwners': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/configuration.ts#createCustomField': [
    '#fieldInput',
    '#lockSettings',
    'apps/api/src/modules/employment/context.ts#assertRevision',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/configuration.ts#getCustomFieldsForInheritance': [
    '#fieldSelect',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/configuration.ts#listCustomFields': [
    '#fieldSelect',
    'apps/api/src/modules/employment/read-model.ts#checkPage',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/configuration.ts#lockSettings': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/configuration.ts#readEmploymentSettings': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/configuration.ts#readSettings': ['#readEmploymentSettings'],
  'apps/api/src/modules/employment/configuration.ts#setCustomFieldInheritance': [
    '#fieldSelect',
    '#lockSettings',
    'apps/api/src/modules/employment/context.ts#assertRevision',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/configuration.ts#updateSettings': [
    '#lockSettings',
    '#readEmploymentSettings',
    'apps/api/src/modules/employment/context.ts#assertRevision',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/context.ts#auditEmployment': [
    'apps/api/src/audit/record.ts#recordAudit',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/employment/context.ts#employmentCreatorId': ['#employmentCreator'],
  'apps/api/src/modules/employment/context.ts#employmentRecordVisibleTo': [
    '#employmentCreatorId',
    'apps/api/src/modules/employment/visibility.ts#isEmploymentRecordVisible',
  ],
  'apps/api/src/modules/employment/context.ts#employmentScopePredicate': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/employment/context.ts#previousCreators': ['#employmentCreator'],
  'apps/api/src/modules/employment/context.ts#queryDate': [
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/context.ts#readContext': [
    'apps/api/src/authorization.ts#requirePermission',
    '#EMPLOYMENT_OBJECT',
    '#employmentCreatorId',
    'apps/api/src/modules/permission/module-access.ts#resolveModuleScope',
    'apps/api/src/modules/permission/module-access.ts#scopeAllowsInTransaction',
    'apps/api/src/tenant-context.ts#tenantOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/context.ts#readPageContext': ['#EMPLOYMENT_OBJECT', '#readContext'],
  'apps/api/src/modules/employment/context.ts#requireEmploymentScope': [
    'apps/api/src/modules/permission/module-access.ts#scopeAllows',
  ],
  'apps/api/src/modules/employment/context.ts#requireEmploymentWrite': [
    'apps/api/src/authorization.ts#requirePermission',
    '#EMPLOYMENT_OBJECT',
    'apps/api/src/modules/permission/object-write.ts#requireObjectWrite',
    'packages/domain/src/permission/decide.ts#buttonResource',
  ],
  'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord': ['#employmentRecordVisibleTo'],
  'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject': [
    '#employmentCreatorId',
    'apps/api/src/modules/permission/module-access.ts#scopeAllowsInTransaction',
  ],
  'apps/api/src/modules/employment/context.ts#runWrite': [
    '#trimEmploymentResponse',
    'apps/api/src/modules/permission/employment-replay.ts#authorizeEmploymentResult',
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
  ],
  'apps/api/src/modules/employment/context.ts#trimEmploymentResponse': [
    '#EMPLOYMENT_OBJECT',
    '#visiblePreviousRecords',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/permission/module-access.ts#trimModuleResponse',
    'apps/api/src/modules/transfer/response-disclosure.ts#trimEmploymentManagerReferences',
  ],
  'apps/api/src/modules/employment/context.ts#visiblePreviousRecords': [
    '#previousCreators',
    'apps/api/src/modules/employment/visibility.ts#visibleEmploymentRecords',
  ],
  'apps/api/src/modules/employment/cycles.ts#assertNotBeforeCurrentCycle': [
    '#DATE_LABELS',
    '#currentEmploymentCycle',
    'apps/api/src/modules/employment/errors.ts#EmploymentError',
  ],
  'apps/api/src/modules/employment/cycles.ts#currentEmploymentCycle': [
    '#cycleAtTimelinePoint',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/cycles.ts#cycleAtTimelinePoint': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#PendingApplicationError': ['#PENDING_MESSAGE'],
  'apps/api/src/modules/employment/deletion-guards.ts#assertNoLinkedChanges': ['#probes'],
  'apps/api/src/modules/employment/deletion-guards.ts#assertNoPendingApplication': [
    '#MAX_LISTED',
    '#PendingApplicationError',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#assertRestoredEstablishment': [
    'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity',
    'apps/api/src/modules/establishment/employment-check.ts#establishmentPeriodStartsWithin',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#assertRestoredPredecessor': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    '#assertRestoredEstablishment',
    '#validateRestoredReferences',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/org/employment-validity.ts#employmentDepartmentDisable',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#disclosePendingApplications': [
    'apps/api/src/modules/employment/context.ts#employmentRecordVisibleTo',
    '#PENDING_MESSAGE',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#organizationLinkage': [
    '#ROLE_LABELS',
    '#remainingOrgRoles',
    '#remainingSubordinates',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#probes': ['#organizationLinkage'],
  'apps/api/src/modules/employment/deletion-guards.ts#remainingOrgRoles': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#remainingSubordinates': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/deletion-guards.ts#validateRestoredReferences': [
    '#ReportingCycleDeletionError',
    'apps/api/src/modules/employment/references.ts#validateEmploymentReferences',
    'apps/api/src/modules/employment/reporting-cycle.ts#findReportingCycle',
  ],
  'apps/api/src/modules/employment/employee-status.ts#ENTRY_LIKE_KINDS': ['#ENTRY_KINDS'],
  'apps/api/src/modules/employment/employee-status.ts#STATUS_SETTING_KINDS': ['#ENTRY_LIKE_KINDS'],
  'apps/api/src/modules/employment/employee-status.ts#appendStatusSnapshot': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    '#appendStatusVersion',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness',
  ],
  'apps/api/src/modules/employment/employee-status.ts#appendStatusVersion': [
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
  ],
  'apps/api/src/modules/employment/employee-status.ts#assertRegularizationNotPropagated': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'packages/domain/src/employment/employee-status.ts#EMPLOYEE_STATUS',
  ],
  'apps/api/src/modules/employment/employee-status.ts#entryStatusFor': [
    '#ENTRY_KINDS',
    '#ENTRY_LIKE_KINDS',
    'packages/domain/src/employment/employee-status.ts#EMPLOYEE_STATUS',
    'packages/domain/src/employment/employee-status.ts#ENTRY_STATUS',
  ],
  'apps/api/src/modules/employment/employee-status.ts#inheritedStatus': ['#inheritsEmployeeStatus'],
  'apps/api/src/modules/employment/employee-status.ts#inheritsEmployeeStatus': ['#STATUS_SETTING_KINDS'],
  'apps/api/src/modules/employment/employee-status.ts#propagateEmployeeStatus': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    '#appendStatusVersion',
    '#propagationTargets',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
  ],
  'apps/api/src/modules/employment/employee-status.ts#propagationTargets': [
    'apps/api/src/modules/employment/record-store.ts#camelRow',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/record-store.ts#snapshotFields',
  ],
  'apps/api/src/modules/employment/employee-status.ts#rederiveRepositionedStatus': [
    '#appendStatusSnapshot',
    '#inheritedStatus',
    '#inheritsEmployeeStatus',
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/employees.ts#createEmployee': [
    'apps/api/src/modules/employment/context.ts#assertRevision',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    '#inputSchema',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/employees.ts#employeeName': [
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/employees.ts#employeeQuery': [
    'apps/api/src/modules/avatar/references.ts#employeeAvatarSql',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/context.ts#employmentScopePredicate',
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
  ],
  'apps/api/src/modules/employment/employees.ts#getEmployee': [
    '#employeeQuery',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/employees.ts#listEmployees': [
    '#employeeQuery',
    'apps/api/src/modules/employment/read-model.ts#checkPage',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    'packages/domain/src/employment/employee-status.ts#EMPLOYEE_STATUS_CODES',
    'packages/domain/src/employment/employee-status.ts#ENTRY_STATUS_CODES',
  ],
  'apps/api/src/modules/employment/errors.ts#EmploymentError': ['#EMPLOYMENT_STATUS'],
  'apps/api/src/modules/employment/field-derivations.ts#derivationFields': ['#rules'],
  'apps/api/src/modules/employment/field-derivations.ts#derivePresetFields': ['#resolveDerivation', '#rules'],
  'apps/api/src/modules/employment/field-derivations.ts#resolveDerivation': [
    '#sequenceForNewPost',
    '#soleOtherPositionManager',
    'apps/api/src/modules/employment/personnel-reader.ts#readPositionAssignments',
    'apps/api/src/modules/job/read-model.ts#loadJobObject',
    'apps/api/src/modules/transfer/preview-defaults.ts#managerForTransferDepartment',
  ],
  'apps/api/src/modules/employment/field-derivations.ts#sequenceForNewPost': [
    'apps/api/src/modules/job/read-model.ts#loadJobObject',
  ],
  'apps/api/src/modules/employment/fields.ts#INHERITED_FIELDS': ['#PRESET_FIELDS'],
  'apps/api/src/modules/employment/fields.ts#PRESET_FIELDS': [
    'apps/api/src/modules/employment/types.ts#PRESET_FIELD_NAMES',
  ],
  'apps/api/src/modules/employment/fields.ts#assertNoStatusFields': [
    'packages/domain/src/employment/employee-status.ts#EMPLOYMENT_STATUS_FIELDS',
  ],
  'apps/api/src/modules/employment/fields.ts#businessDate': ['apps/api/src/modules/org/read-model.ts#validIsoDate'],
  'apps/api/src/modules/employment/fields.ts#businessSchema': [
    '#customFields',
    '#date',
    '#formId',
    '#presetFieldsSchema',
    'apps/api/src/modules/employment/types.ts#BUSINESS_KINDS',
  ],
  'apps/api/src/modules/employment/fields.ts#date': ['apps/api/src/modules/org/read-model.ts#validIsoDate'],
  'apps/api/src/modules/employment/fields.ts#dayAfter': ['#businessDate'],
  'apps/api/src/modules/employment/fields.ts#emptyFields': [
    'apps/api/src/modules/employment/types.ts#emptyPresetFields',
  ],
  'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch': ['#assertNoStatusFields', '#patchSchema'],
  'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput': ['#parseEmploymentInput'],
  'apps/api/src/modules/employment/fields.ts#parseEmploymentInput': [
    '#assertNoStatusFields',
    '#businessSchema',
    '#dayAfter',
  ],
  'apps/api/src/modules/employment/fields.ts#patchSchema': ['#customFields', '#date', '#presetFieldsSchema'],
  'apps/api/src/modules/employment/fields.ts#presetFieldsSchema': ['#normalizedUuid', '#text', '#uuid'],
  'apps/api/src/modules/employment/fields.ts#uuid': ['#normalizedUuid'],
  'apps/api/src/modules/employment/fields.ts#validateCustomValue': ['#date'],
  'apps/api/src/modules/employment/forward-import.ts#assertDistinctSameDayTransitions': [
    'apps/api/src/modules/employment/fields.ts#parseEmploymentInput',
  ],
  'apps/api/src/modules/employment/forward-import.ts#importEmploymentRecords': [
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    '#importRecordRevision',
    '#lockImportParticipants',
    '#normalizeEmploymentImport',
    '#validateImportRevisions',
    'apps/api/src/modules/employment/record-edit.ts#editEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    'apps/api/src/modules/employment/write-service.ts#createEmploymentBusiness',
  ],
  'apps/api/src/modules/employment/forward-import.ts#importRecordRevision': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/forward-import.ts#lockImportParticipants': [
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
  ],
  'apps/api/src/modules/employment/forward-import.ts#normalizeEmploymentImport': [
    '#assertDistinctSameDayTransitions',
    '#schema',
  ],
  'apps/api/src/modules/employment/forward-import.ts#previewEmploymentImport': [
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    '#normalizeEmploymentImport',
    'apps/api/src/modules/employment/forward-preview.ts#previewEmploymentEditForwardUpdate',
    'apps/api/src/modules/employment/forward-preview.ts#previewEmploymentForwardUpdate',
  ],
  'apps/api/src/modules/employment/forward-import.ts#validateImportRevisions': [
    'apps/api/src/modules/employment/context.ts#assertRevision',
    '#importRecordRevision',
  ],
  'apps/api/src/modules/employment/forward-preview.ts#previewEmploymentEditForwardUpdate': [
    'apps/api/src/modules/employment/forward-rules.ts#isForwardEditSupported',
    'apps/api/src/modules/employment/forward-update.ts#forwardUpdateEmployment',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-edit.ts#editedRecordReporting',
    'apps/api/src/modules/employment/record-edit.ts#editedValues',
    'apps/api/src/modules/employment/references.ts#validateEmploymentReferences',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/forward-preview.ts#previewEmploymentForwardUpdate': [
    'apps/api/src/modules/employment/context.ts#requireEmploymentScope',
    'apps/api/src/modules/employment/cycles.ts#assertNotBeforeCurrentCycle',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/employment/forward-update.ts#forwardUpdateEmployment',
    'apps/api/src/modules/employment/inheritance.ts#prepareInheritance',
    'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance',
    'apps/api/src/modules/employment/record-store.ts#readEmploymentEmployee',
    'apps/api/src/modules/employment/references.ts#newRecordReporting',
    'apps/api/src/modules/employment/references.ts#validateEmploymentReferences',
    'apps/api/src/modules/employment/types.ts#emptyPresetFields',
    'apps/api/src/modules/employment/write-service.ts#NEW_CYCLE_KINDS',
    'apps/api/src/modules/employment/write-service.ts#selectEmploymentCycle',
  ],
  'apps/api/src/modules/employment/forward-references.ts#availableForwardChanges': [
    '#JOB_REFERENCES',
    '#enabled',
    '#formsCycle',
  ],
  'apps/api/src/modules/employment/forward-references.ts#enabled': [
    '#JOB_REFERENCES',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/establishment/org-reader.ts#createTxOrgHierarchyReader',
    'apps/api/src/modules/job/read-model.ts#loadJobObject',
  ],
  'apps/api/src/modules/employment/forward-references.ts#formsCycle': [
    'apps/api/src/modules/employment/reporting-cycle.ts#findReportingCycle',
    'apps/api/src/modules/employment/reporting-cycle.ts#insertedWindow',
    'apps/api/src/modules/employment/reporting-cycle.ts#recordWindow',
  ],
  'apps/api/src/modules/employment/forward-rules.ts#FORWARD_PRESET_FIELDS': [
    'apps/api/src/modules/employment/fields.ts#INHERITED_FIELDS',
  ],
  'apps/api/src/modules/employment/forward-rules.ts#matchingForwardChanges': [
    '#FORWARD_PRESET_FIELDS',
    '#skipsWholeRecord',
    '#valueMatches',
  ],
  'apps/api/src/modules/employment/forward-rules.ts#wholeRecordSkipReminder': [
    '#FORWARD_PRESET_FIELDS',
    '#PAIR_FIELDS',
    '#valueMatches',
  ],
  'apps/api/src/modules/employment/forward-store.ts#appendForwardPayload': [
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
  ],
  'apps/api/src/modules/employment/forward-store.ts#auditForwardTarget': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/forward-update.ts#candidates': [
    '#TARGET_LIMIT',
    '#pendingAfterSource',
    '#sourceOrder',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#camelRow',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/record-store.ts#snapshotFields',
  ],
  'apps/api/src/modules/employment/forward-update.ts#forwardUpdateEmployment': [
    'apps/api/src/modules/employment/configuration.ts#getCustomFieldsForInheritance',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    'apps/api/src/modules/employment/cycles.ts#currentEmploymentCycle',
    'apps/api/src/modules/employment/forward-references.ts#availableForwardChanges',
    'apps/api/src/modules/employment/forward-references.ts#referenceCheckDate',
    'apps/api/src/modules/employment/forward-rules.ts#applyForwardChanges',
    'apps/api/src/modules/employment/forward-rules.ts#matchingForwardChanges',
    'apps/api/src/modules/employment/forward-rules.ts#skipsWholeRecord',
    '#candidates',
    '#remindWholeRecordSkip',
    '#writeForwardTarget',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/forward-update.ts#pendingAfterSource': [
    'apps/api/src/modules/employment/timeline.ts#operationKey',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/forward-update.ts#remindWholeRecordSkip': [
    'apps/api/src/modules/employment/context.ts#employmentRecordVisibleTo',
    'apps/api/src/modules/employment/forward-references.ts#availableForwardChanges',
    'apps/api/src/modules/employment/forward-references.ts#referenceCheckDate',
    'apps/api/src/modules/employment/forward-rules.ts#wholeRecordSkipReminder',
  ],
  'apps/api/src/modules/employment/forward-update.ts#sourceOrder': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/forward-update.ts#writeForwardTarget': [
    'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity',
    'apps/api/src/modules/employment/forward-store.ts#appendForwardPayload',
    'apps/api/src/modules/employment/forward-store.ts#auditForwardTarget',
    'apps/api/src/modules/establishment/employment-check.ts#affectsEstablishmentOccupancy',
  ],
  'apps/api/src/modules/employment/import-audit.ts#failedImportAnchors': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#rawUuid',
    '#MAX_LOOKUP_ROWS',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/inheritance.ts#applyCustomInheritance': [
    'apps/api/src/modules/employment/fields.ts#validateCustomValue',
    '#owns',
  ],
  'apps/api/src/modules/employment/inheritance.ts#applyExplicitPresetFields': [
    'apps/api/src/modules/employment/field-derivations.ts#derivePresetFields',
    '#owns',
    '#setField',
  ],
  'apps/api/src/modules/employment/inheritance.ts#prepareEmploymentPatch': [
    'apps/api/src/modules/employment/fields.ts#INHERITED_FIELDS',
    '#owns',
    '#prepareInheritance',
    '#setField',
  ],
  'apps/api/src/modules/employment/inheritance.ts#prepareInheritance': [
    'apps/api/src/modules/employment/configuration.ts#getCustomFieldsForInheritance',
    'apps/api/src/modules/employment/field-derivations.ts#derivationFields',
    'apps/api/src/modules/employment/fields.ts#INHERITED_FIELDS',
    'apps/api/src/modules/employment/fields.ts#businessDate',
    'apps/api/src/modules/employment/fields.ts#emptyFields',
    'apps/api/src/modules/employment/fields.ts#presetFieldsSchema',
    '#NEW_CYCLES',
    '#applyCustomInheritance',
    '#applyExplicitPresetFields',
    '#resolveForm',
    '#selfServiceForm',
    '#setField',
    '#snapshotForm',
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    'apps/api/src/modules/transfer/form-configuration.ts#resolveTransferForm',
    'apps/api/src/modules/transfer/initiator-fields.ts#applyInitiatorFieldModes',
  ],
  'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance': [
    'apps/api/src/modules/employment/fields.ts#INHERITED_FIELDS',
    '#setField',
  ],
  'apps/api/src/modules/employment/inheritance.ts#selfServiceForm': [
    'apps/api/src/modules/permission/module-access.ts#authorizeInTransaction',
    'apps/api/src/modules/transfer/employee-policy.ts#EMPLOYEE_READONLY_FIELDS',
  ],
  'apps/api/src/modules/employment/inheritance.ts#snapshotForm': [
    'apps/api/src/modules/employment/fields.ts#PRESET_FIELDS',
  ],
  'apps/api/src/modules/employment/late-transfer.ts#assertNoRebuildRequired': [
    'apps/api/src/modules/employment/activation-store.ts#REBUILD_REQUIRED',
    '#lateWindowBlockers',
  ],
  'apps/api/src/modules/employment/late-transfer.ts#lateWindowBlockers': [
    '#LATE_WINDOW_LIMIT',
    '#lateWindowPoint',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#operationKey',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
  ],
  'apps/api/src/modules/employment/late-transfer.ts#lateWindowPoint': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#timelinePosition',
  ],
  'apps/api/src/modules/employment/late-transfer.ts#originalPlannedDate': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#plannedEffectiveDate',
  ],
  'apps/api/src/modules/employment/late-transfer.ts#postponeLateTransfer': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/employee-status.ts#rederiveRepositionedStatus',
    '#assertNoRebuildRequired',
    '#originalPlannedDate',
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#insertEmploymentTimeline',
    'apps/api/src/modules/employment/write-service.ts#validateTransferReposition',
    'packages/domain/src/employment/late-execution.ts#resolveLateExecution',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/linkage-dependency.ts#assertPredecessorsSettled': [
    'apps/api/src/modules/employment/activation-store.ts#activationPredecessors',
    '#blockingPredecessors',
  ],
  'apps/api/src/modules/employment/linkage-dependency.ts#blockingPredecessors': ['#exemptsBlocker'],
  'apps/api/src/modules/employment/linkage-dependency.ts#exemptsBlocker': [
    'apps/api/src/modules/employment/activation-store.ts#isRebuildBlocker',
    '#linkageDependent',
  ],
  'apps/api/src/modules/employment/linkage-dependency.ts#footprintFields': [
    '#uuidList',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/linkage-dependency.ts#linkageDependent': ['#linkageFootprint', '#matchesWildcard'],
  'apps/api/src/modules/employment/linkage-dependency.ts#linkageFootprint': [
    '#footprintFields',
    '#roleKey',
    'apps/api/src/modules/transfer/linkage/store.ts#latestLinkage',
  ],
  'apps/api/src/modules/employment/linkage-dependency.ts#matchesWildcard': ['#ROLE_WILDCARD'],
  'apps/api/src/modules/employment/org-adjustment-projection.ts#projectOrgAdjustmentRecords': [
    'apps/api/src/modules/employment/forward-references.ts#availableForwardChanges',
    'apps/api/src/modules/employment/forward-rules.ts#applyForwardChanges',
    'apps/api/src/modules/employment/forward-rules.ts#matchingForwardChanges',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
  ],
  'apps/api/src/modules/employment/org-adjustment.ts#appendOrgAdjustment': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    '#adjustmentSnapshot',
    '#auditAdjustmentInterval',
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentEmployee',
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
    'apps/api/src/modules/employment/timeline.ts#insertEmploymentTimeline',
    'apps/api/src/modules/employment/write-service.ts#appendEmploymentPayload',
    'apps/api/src/modules/employment/write-service.ts#appendEmploymentState',
  ],
  'apps/api/src/modules/employment/org-adjustment.ts#auditAdjustmentInterval': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'packages/domain/src/contracts/rules.ts#addDays',
  ],
  'apps/api/src/modules/employment/org-people.ts#activeEmployees': [
    '#currentDepartment',
    '#latestSnapshot',
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
  ],
  'apps/api/src/modules/employment/org-people.ts#countDepartmentStaff': [
    'apps/api/src/modules/employment/fields.ts#businessDate',
    '#currentDepartment',
    '#latestSnapshot',
    '#uuidArray',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/org-people.ts#ineligibleOrgPeople': [
    'apps/api/src/modules/employment/fields.ts#businessDate',
    '#activeEmployees',
    '#uuidArray',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/org-people.ts#listOrgPersonCandidates': [
    'apps/api/src/modules/employment/fields.ts#businessDate',
    '#activeEmployees',
    '#likePattern',
    'apps/api/src/modules/employment/read-model.ts#checkPage',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks': ['#hooks'],
  'apps/api/src/modules/employment/personnel-reader.ts#ASSIGNMENT_COLUMNS': ['#INCUMBENT_COLUMNS'],
  'apps/api/src/modules/employment/personnel-reader.ts#query': [
    'apps/api/src/modules/employment/fields.ts#businessDate',
    '#INCUMBENT_COLUMNS',
  ],
  'apps/api/src/modules/employment/personnel-reader.ts#readPositionAssignments': [
    '#ASSIGNMENT_COLUMNS',
    '#query',
    'apps/api/src/modules/employment/read-model.ts#checkPage',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/read-model.ts#findCurrentRecord': ['#record', '#recordsQuery', '#rowsOf'],
  'apps/api/src/modules/employment/read-model.ts#findPredecessor': ['#loadEmploymentRecord', '#rowsOf'],
  'apps/api/src/modules/employment/read-model.ts#listEmploymentRecords': [
    '#checkPage',
    '#record',
    '#recordsQuery',
    '#rowsOf',
  ],
  'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness': [
    'apps/api/src/modules/employment/activation-store.ts#activationSummary',
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/context.ts#employmentScopePredicate',
    '#loadEmploymentRecord',
    '#rowsOf',
    '#snapshotFields',
    '#statusCode',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
  ],
  'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord': ['#record', '#recordsQuery', '#rowsOf'],
  'apps/api/src/modules/employment/read-model.ts#record': ['#snapshotFields', '#statusCode'],
  'apps/api/src/modules/employment/read-model.ts#recordsQuery': [
    'apps/api/src/modules/employment/context.ts#employmentCreator',
    'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql',
  ],
  'apps/api/src/modules/employment/read-model.ts#snapshotFields': [
    '#columnName',
    'apps/api/src/modules/employment/types.ts#PRESET_FIELD_NAMES',
  ],
  'apps/api/src/modules/employment/record-edit.ts#editEmploymentRecord': [
    'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/forward-rules.ts#isForwardEditSupported',
    'apps/api/src/modules/employment/forward-store.ts#appendForwardPayload',
    'apps/api/src/modules/employment/forward-update.ts#forwardUpdateEmployment',
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    '#customAudit',
    '#editedRecordReporting',
    '#editedValues',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness',
    'apps/api/src/modules/employment/references.ts#validateEmploymentReferences',
    'apps/api/src/modules/employment/transfer-linkage.ts#queueTransferLinkage',
    'apps/api/src/modules/employment/transfer-linkage.ts#validateTransferSubordinates',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferBusiness',
    'apps/api/src/modules/employment/write-service.ts#requireSavedBusiness',
    'apps/api/src/modules/establishment/employment-check.ts#affectsEstablishmentOccupancy',
    'apps/api/src/modules/transfer/completion.ts#reconcileCompletion',
    'apps/api/src/modules/transfer/required-fields.ts#assertRequiredTransferFields',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/record-edit.ts#editedRecordReporting': [
    'apps/api/src/modules/employment/reporting-cycle.ts#recordWindow',
  ],
  'apps/api/src/modules/employment/record-edit.ts#editedValues': [
    'apps/api/src/modules/employment/configuration.ts#getCustomFieldsForInheritance',
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/field-derivations.ts#sequenceForNewPost',
    'apps/api/src/modules/employment/fields.ts#validateCustomValue',
  ],
  'apps/api/src/modules/employment/record-events.ts#eventColumns': ['#TIMELINE_ALIAS'],
  'apps/api/src/modules/employment/record-events.ts#recordEventDueSql': ['#RECORD_CREATE_EVENT', '#eventColumns'],
  'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness': ['#bumpEmploymentEmployee'],
  'apps/api/src/modules/employment/record-store.ts#camelRow': ['#camelCase'],
  'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow': [
    '#ARRAY_COLUMNS',
    '#JSON_COLUMNS',
    '#TABLES',
    '#VERSION_TABLES',
    '#versionValues',
  ],
  'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness': [
    'apps/api/src/modules/employment/context.ts#assertRevision',
    '#camelRow',
    '#lockEmploymentEmployee',
    '#rowsOf',
    '#snapshotFields',
  ],
  'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee': [
    'apps/api/src/modules/employment/context.ts#assertRevision',
    '#camelRow',
    '#rowsOf',
  ],
  'apps/api/src/modules/employment/record-store.ts#readEmploymentEmployee': ['#camelRow', '#rowsOf'],
  'apps/api/src/modules/employment/record-store.ts#snapshotFields': [
    'apps/api/src/modules/employment/types.ts#PRESET_FIELD_NAMES',
  ],
  'apps/api/src/modules/employment/references.ts#assertEmploymentDepartmentAvailable': [
    'apps/api/src/modules/establishment/org-reader.ts#assertOrg',
    'apps/api/src/modules/org/employment-validity.ts#employmentDepartmentDisable',
    'apps/api/src/modules/org/locks.ts#lockOrganizationSettings',
  ],
  'apps/api/src/modules/employment/references.ts#newRecordReporting': [
    '#setsDirectManager',
    'apps/api/src/modules/employment/reporting-cycle.ts#insertedWindow',
  ],
  'apps/api/src/modules/employment/references.ts#validateEmploymentReferences': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    '#validatePositionRanges',
    'apps/api/src/modules/employment/reporting-cycle.ts#assertNoReportingCycle',
    'apps/api/src/modules/establishment/org-reader.ts#assertOrg',
    'apps/api/src/modules/job/validation.ts#invalid',
    'apps/api/src/modules/job/validation.ts#requiredJob',
    'apps/api/src/modules/job/validation.ts#validateJobAssignment',
  ],
  'apps/api/src/modules/employment/references.ts#validateNewEmploymentReferences': [
    '#assertEmploymentDepartmentAvailable',
    '#validateEmploymentReferences',
  ],
  'apps/api/src/modules/employment/references.ts#validatePositionRanges': [
    '#validateRange',
    'apps/api/src/modules/job/validation.ts#invalid',
    'apps/api/src/modules/job/validation.ts#requiredJob',
  ],
  'apps/api/src/modules/employment/references.ts#validateRange': [
    'apps/api/src/modules/job/validation.ts#invalid',
    'apps/api/src/modules/job/validation.ts#requiredJob',
  ],
  'apps/api/src/modules/employment/reporting-cycle.ts#assertNoReportingCycle': [
    '#employeeNames',
    '#findReportingCycle',
  ],
  'apps/api/src/modules/employment/reporting-cycle.ts#employeeNames': [
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/reporting-cycle.ts#findReportingCycle': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
    '#MAX_CHAIN_DEPTH',
    '#currentManager',
  ],
  'apps/api/src/modules/employment/reporting-cycle.ts#insertedWindow': [
    '#windowBefore',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
  ],
  'apps/api/src/modules/employment/reporting-cycle.ts#recordWindow': [
    'apps/api/src/modules/employment/read-model.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/routes.ts#authorizeBusinessWrite': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/routes.ts#authorizeImport': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/context.ts#requireEmploymentScope',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    '#authorizeBusinessWrite',
    '#requireImportTransferAccess',
    'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferBusiness',
  ],
  'apps/api/src/modules/employment/routes.ts#discloseDeletionBlock': [
    'apps/api/src/modules/employment/deletion-guards.ts#PendingApplicationError',
    'apps/api/src/modules/employment/deletion-guards.ts#ReportingCycleDeletionError',
    'apps/api/src/modules/employment/deletion-guards.ts#disclosePendingApplications',
    'apps/api/src/modules/employment/visibility.ts#visibleEmploymentRecords',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
  ],
  'apps/api/src/modules/employment/routes.ts#emptySubmitBody': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    '#parse',
  ],
  'apps/api/src/modules/employment/routes.ts#ensureHiredAccount': [
    'apps/api/src/modules/employment/employees.ts#employeeName',
    'apps/api/src/modules/permission/user-provisioning.ts#provisionEmployeeUser',
  ],
  'apps/api/src/modules/employment/routes.ts#importEmployment': [
    'apps/api/src/audit/record.ts#rawImportRows',
    'apps/api/src/audit/record.ts#withFailedImportLog',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/employment/forward-import.ts#normalizeEmploymentImport',
    'apps/api/src/modules/employment/import-audit.ts#failedImportAnchors',
    '#authorizeImport',
    '#importWithTransferAuthorization',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#importWithTransferAuthorization': [
    'apps/api/src/audit/record.ts#recordOperationLog',
    'apps/api/src/modules/employment/forward-import.ts#importEmploymentRecords',
    'apps/api/src/modules/employment/forward-import.ts#lockImportParticipants',
    'apps/api/src/modules/employment/import-audit.ts#importedItems',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    '#requireImportTransferAccess',
    'apps/api/src/system-actor.ts#auditActor',
  ],
  'apps/api/src/modules/employment/routes.ts#registerBusinessTransitions': [
    'apps/api/src/modules/employment/approval-hooks.ts#employmentApprovalHooks',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    '#authorizeBusinessWrite',
    '#discloseDeletionBlock',
    '#emptySubmitBody',
    'apps/api/src/modules/employment/transitions.ts#transitionEmployment',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferBusiness',
    'apps/api/src/modules/transfer/service.ts#transferBusinessContext',
  ],
  'apps/api/src/modules/employment/routes.ts#requireImportTransferAccess': [
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
    'apps/api/src/modules/transfer/service.ts#requireDirectTransfer',
  ],
  'apps/api/src/modules/employment/routes.ts#requirePreviewButton': ['apps/api/src/authorization.ts#requirePermission'],
  'apps/api/src/modules/employment/routes.ts#requireViewableFilters': [
    'apps/api/src/modules/employment/context.ts#EMPLOYEE_OBJECT',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /activation-todos': [
    'apps/api/src/modules/employment/activation-store.ts#listActivationTodos',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /businesses/:id': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/context.ts#queryDate',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/transfer/service.ts#transferBusinessContext',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /completion-todos': [
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/permission/module-access.ts#getModuleViewableFields',
    'apps/api/src/modules/transfer/access.ts#requireTransferButton',
    'apps/api/src/modules/transfer/completion.ts#listCompletionTodos',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /custom-fields': [
    'apps/api/src/modules/employment/configuration.ts#listCustomFields',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    '#parse',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /employees': [
    'apps/api/src/modules/employment/context.ts#EMPLOYEE_OBJECT',
    'apps/api/src/modules/employment/context.ts#queryDate',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/employees.ts#listEmployees',
    '#parse',
    '#requireViewableFilters',
    'apps/api/src/modules/job/context.ts#pageQuery',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /employees/:id': [
    'apps/api/src/modules/employment/context.ts#EMPLOYEE_OBJECT',
    'apps/api/src/modules/employment/context.ts#queryDate',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/employees.ts#getEmployee',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /employees/:id/records': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/context.ts#queryDate',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/employees.ts#getEmployee',
    'apps/api/src/modules/employment/read-model.ts#listEmploymentRecords',
    'apps/api/src/modules/job/context.ts#pageQuery',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /records/:id': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/context.ts#queryDate',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:GET /settings': [
    'apps/api/src/modules/employment/configuration.ts#readSettings',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
  ],
  'apps/api/src/modules/employment/routes.ts#route:PATCH /businesses/:id': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    '#authorizeBusinessWrite',
    'apps/api/src/modules/employment/write-service.ts#updateEmploymentBusiness',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferBusiness',
    'apps/api/src/modules/transfer/service.ts#transferBusinessContext',
  ],
  'apps/api/src/modules/employment/routes.ts#route:PATCH /records/:id': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/record-edit.ts#editEmploymentRecord',
    '#authorizeBusinessWrite',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /businesses/:id/activation/retry': [
    'apps/api/src/modules/employment/activation-service.ts#retryActivation',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    '#authorizeBusinessWrite',
    '#emptySubmitBody',
    'apps/api/src/modules/employment/write-service.ts#requireSavedBusiness',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /custom-fields': [
    'apps/api/src/modules/employment/configuration.ts#createCustomField',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    '#parse',
    'apps/api/src/modules/job/context.ts#revision',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /employees': [
    'apps/api/src/modules/employment/context.ts#EMPLOYEE_OBJECT',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentScope',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/employment/employees.ts#createEmployee',
    '#loginEmail',
    '#parse',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/permission/user-provisioning.ts#provisionEmployeeUser',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /employees/:id/businesses': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentScope',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    '#ensureHiredAccount',
    '#splitLoginEmail',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    'apps/api/src/modules/employment/write-service.ts#NEW_CYCLE_KINDS',
    'apps/api/src/modules/employment/write-service.ts#createEmploymentBusiness',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
    'apps/api/src/modules/transfer/access.ts#requireTransferSource',
    'apps/api/src/modules/transfer/service.ts#requireDirectTransfer',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /employees/:id/forward-update-preview': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/employment/forward-preview.ts#previewEmploymentForwardUpdate',
    '#requirePreviewButton',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /employees/:id/import/forward-update-preview': [
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/forward-import.ts#normalizeEmploymentImport',
    'apps/api/src/modules/employment/forward-import.ts#previewEmploymentImport',
    '#authorizeImport',
    '#requirePreviewButton',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /employees/:id/preview': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#queryDate',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentScope',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/employees.ts#getEmployee',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/employment/inheritance.ts#inheritancePreview',
    'apps/api/src/modules/employment/inheritance.ts#prepareInheritance',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /records/:id/forward-update-preview': [
    'apps/api/src/authorization.ts#requirePermission',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#queryDate',
    'apps/api/src/modules/employment/context.ts#readPageContext',
    'apps/api/src/modules/employment/context.ts#trimEmploymentResponse',
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/forward-preview.ts#previewEmploymentEditForwardUpdate',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    '#requirePreviewButton',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:POST /records/batch-edit': [
    'apps/api/src/modules/employment/batch-edit.ts#batchEditEmploymentRecords',
    'apps/api/src/modules/employment/batch-edit.ts#normalizeBatchEdit',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/context.ts#runWrite',
    '#authorizeBusinessWrite',
  ],
  'apps/api/src/modules/employment/routes.ts#route:PUT /custom-fields/:id/inheritance': [
    'apps/api/src/modules/employment/configuration.ts#setCustomFieldInheritance',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    '#parse',
    'apps/api/src/modules/job/context.ts#revision',
    'apps/api/src/modules/job/context.ts#uuidParam',
  ],
  'apps/api/src/modules/employment/routes.ts#route:PUT /settings': [
    'apps/api/src/modules/employment/configuration.ts#updateSettings',
    'apps/api/src/modules/employment/context.ts#jsonBody',
    'apps/api/src/modules/employment/context.ts#readContext',
    'apps/api/src/modules/employment/context.ts#requireEmploymentWrite',
    'apps/api/src/modules/employment/context.ts#runWrite',
    '#parse',
    'apps/api/src/modules/job/context.ts#revision',
  ],
  'apps/api/src/modules/employment/routes.ts#splitLoginEmail': ['#loginEmail', '#parse'],
  'apps/api/src/modules/employment/status-hooks.ts#employeeStatusHooks': ['#hookContext', '#subscribers'],
  'apps/api/src/modules/employment/status-hooks.ts#subscribers': ['#registry'],
  'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors': ['#neighborsAt', '#timelinePosition'],
  'apps/api/src/modules/employment/timeline.ts#insertEmploymentTimeline': [
    '#neighborsAt',
    '#shiftSameDay',
    '#timelinePosition',
  ],
  'apps/api/src/modules/employment/timeline.ts#neighbor': ['apps/api/src/modules/employment/record-store.ts#rowsOf'],
  'apps/api/src/modules/employment/timeline.ts#neighbors': ['#neighbor'],
  'apps/api/src/modules/employment/timeline.ts#neighborsAt': ['#neighbor'],
  'apps/api/src/modules/employment/timeline.ts#removeEmploymentTimeline': [
    'apps/api/src/modules/employment/errors.ts#EmploymentError',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#neighbors',
  ],
  'apps/api/src/modules/employment/timeline.ts#shiftSameDay': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/timeline.ts#timelinePosition': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#operationKey',
    '#plannedEffectiveDate',
  ],
  'apps/api/src/modules/employment/transfer-linkage.ts#applyTransferLinkage': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-edit.ts#editEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#propagateDepartmentHead',
    '#validateTransferSubordinates',
    'apps/api/src/modules/org/write-service.ts#assignTransferOrganizationPeople',
    'apps/api/src/modules/transfer/linkage/execute.ts#applyTransferCrossLinkage',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/transfer-linkage.ts#propagateDepartmentHead': [
    'apps/api/src/modules/employment/context.ts#requireLinkedEmploymentRecord',
    'apps/api/src/modules/employment/forward-store.ts#appendForwardPayload',
    'apps/api/src/modules/employment/forward-store.ts#auditForwardTarget',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/transfer-linkage.ts#queueTransferLinkage': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#applyTransferLinkage',
    '#hasTransferLinkage',
    'apps/api/src/modules/transfer/linkage/store.ts#hasPendingCrossLinkage',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/transfer-linkage.ts#validateTransferSubordinates': [
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/org-people.ts#ineligibleOrgPeople',
    'apps/api/src/modules/employment/read-model.ts#findCurrentRecord',
    'apps/api/src/modules/org/write-service.ts#requireTransferOrganizationScope',
  ],
  'apps/api/src/modules/employment/transfer-locks.ts#lockTransferBusiness': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#lockTransferParticipants',
  ],
  'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#SETTING',
    '#array',
    '#participants',
  ],
  'apps/api/src/modules/employment/transfer-locks.ts#participants': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#array',
  ],
  'apps/api/src/modules/employment/transitions.ts#approveEmploymentBusiness': [
    'apps/api/src/modules/employment/activation-checks.ts#activationFailureOf',
    'apps/api/src/modules/employment/activation-store.ts#PREDECESSOR_FAILED',
    'apps/api/src/modules/employment/activation-store.ts#activationPredecessors',
    'apps/api/src/modules/employment/activation-store.ts#recordActivationAttempt',
    'apps/api/src/modules/employment/activation-store.ts#unresolvedPredecessor',
    'apps/api/src/modules/employment/late-transfer.ts#postponeLateTransfer',
    'apps/api/src/modules/employment/linkage-dependency.ts#blockingPredecessors',
    'apps/api/src/modules/employment/write-service.ts#appendEmploymentState',
    'apps/api/src/modules/employment/write-service.ts#materializeEmploymentRecord',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/transitions.ts#deleteEmploymentBusiness': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/deletion-guards.ts#assertNoLinkedChanges',
    'apps/api/src/modules/employment/deletion-guards.ts#assertNoPendingApplication',
    'apps/api/src/modules/employment/deletion-guards.ts#assertRestoredPredecessor',
    'apps/api/src/modules/employment/employee-status.ts#assertRegularizationNotPropagated',
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentRecord',
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    'apps/api/src/modules/employment/status-hooks.ts#employeeStatusHooks',
    'apps/api/src/modules/employment/timeline.ts#removeEmploymentTimeline',
    '#deletionSnapshot',
    'apps/api/src/modules/employment/write-service.ts#NEW_CYCLE_KINDS',
    'apps/api/src/modules/employment/write-service.ts#appendEmploymentState',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/transitions.ts#deletionSnapshot': [
    'apps/api/src/modules/employment/record-store.ts#camelRow',
  ],
  'apps/api/src/modules/employment/transitions.ts#transitionEmployment': [
    'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity',
    'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance',
    'apps/api/src/modules/employment/late-transfer.ts#postponeLateTransfer',
    'apps/api/src/modules/employment/linkage-dependency.ts#assertPredecessorsSettled',
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness',
    'apps/api/src/modules/employment/references.ts#assertEmploymentDepartmentAvailable',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferBusiness',
    '#ACTIONS',
    '#STATE_AFTER',
    '#approveEmploymentBusiness',
    '#assertTransition',
    '#deleteEmploymentBusiness',
    'apps/api/src/modules/employment/write-service.ts#appendEmploymentState',
    'apps/api/src/modules/employment/write-service.ts#materializeEmploymentRecord',
    'apps/api/src/modules/employment/write-service.ts#requireSavedBusiness',
    'apps/api/src/modules/establishment/carried-transfer.ts#assertReleasedEstablishment',
    'apps/api/src/modules/establishment/carried-transfer.ts#reverseCarriedEstablishment',
    'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferBusiness',
    'apps/api/src/modules/transfer/linkage/service.ts#assertTransferLinkageSubmittable',
    'apps/api/src/modules/transfer/required-fields.ts#assertRequiredTransferFields',
    'packages/domain/src/employment/late-execution.ts#resolveLateExecution',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/types.ts#emptyPresetFields': ['#PRESET_FIELD_NAMES'],
  'apps/api/src/modules/employment/visibility.ts#employmentVisibilitySql': [
    'apps/api/src/modules/permission/module-access.ts#scopeSql',
  ],
  'apps/api/src/modules/employment/visibility.ts#isEmploymentRecordVisible': ['#visibleEmploymentRecords'],
  'apps/api/src/modules/employment/visibility.ts#visibleEmploymentRecords': ['#employmentVisibilitySql'],
  'apps/api/src/modules/employment/write-service.ts#appendEmploymentPayload': [
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
    '#storedStatus',
  ],
  'apps/api/src/modules/employment/write-service.ts#appendEmploymentState': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
  ],
  'apps/api/src/modules/employment/write-service.ts#assertBusinessSequence': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#sequenceViolation',
  ],
  'apps/api/src/modules/employment/write-service.ts#assertDirectTransferAllowed': [
    'apps/api/src/modules/employment/configuration.ts#readEmploymentSettings',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/write-service.ts#assertEmployTypeUsage': ['#NEW_CYCLE_KINDS'],
  'apps/api/src/modules/employment/write-service.ts#assertSuccessorSequence': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
    '#sequenceViolation',
  ],
  'apps/api/src/modules/employment/write-service.ts#auditMaterialization': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    '#customAudit',
    'packages/domain/src/transfer/required.ts#clearedTransferFields',
  ],
  'apps/api/src/modules/employment/write-service.ts#checkMaterializedCapacity': [
    'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity',
  ],
  'apps/api/src/modules/employment/write-service.ts#createEmploymentBusiness': [
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/cycles.ts#assertNotBeforeCurrentCycle',
    'apps/api/src/modules/employment/employee-status.ts#entryStatusFor',
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
    'apps/api/src/modules/employment/inheritance.ts#prepareInheritance',
    'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentEmployee',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentEmployee',
    'apps/api/src/modules/employment/transfer-locks.ts#lockTransferParticipants',
    '#NEW_CYCLE_KINDS',
    '#appendEmploymentPayload',
    '#appendEmploymentState',
    '#assertBusinessSequence',
    '#assertDirectTransferAllowed',
    '#assertEmployTypeUsage',
    '#initializeEmploymentBusiness',
    '#materializeEmploymentRecord',
    '#payloadAudit',
    '#requireSavedBusiness',
    '#selectEmploymentCycle',
    '#validatePreparedEmployment',
  ],
  'apps/api/src/modules/employment/write-service.ts#cycleForMaterialization': ['#selectEmploymentCycle'],
  'apps/api/src/modules/employment/write-service.ts#effectiveEmployType': ['#NEW_CYCLE_KINDS'],
  'apps/api/src/modules/employment/write-service.ts#forwardMaterializedRecord': [
    'apps/api/src/modules/employment/forward-update.ts#forwardUpdateEmployment',
    'apps/api/src/modules/employment/types.ts#emptyPresetFields',
  ],
  'apps/api/src/modules/employment/write-service.ts#initializeEmploymentBusiness': [
    'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity',
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
    'apps/api/src/modules/establishment/carried-transfer.ts#carryEstablishment',
  ],
  'apps/api/src/modules/employment/write-service.ts#insertNewEmploymentCycle': [
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
  ],
  'apps/api/src/modules/employment/write-service.ts#materializeEmploymentRecord': [
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/cycles.ts#assertNotBeforeCurrentCycle',
    'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance',
    'apps/api/src/modules/employment/record-store.ts#insertEmploymentRow',
    'apps/api/src/modules/employment/references.ts#validateNewEmploymentReferences',
    'apps/api/src/modules/employment/reporting-cycle.ts#windowBefore',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
    'apps/api/src/modules/employment/timeline.ts#insertEmploymentTimeline',
    'apps/api/src/modules/employment/timeline.ts#timelinePosition',
    'apps/api/src/modules/employment/transfer-linkage.ts#queueTransferLinkage',
    '#NEW_CYCLE_KINDS',
    '#assertBusinessSequence',
    '#assertSuccessorSequence',
    '#auditMaterialization',
    '#checkMaterializedCapacity',
    '#cycleForMaterialization',
    '#effectiveEmployType',
    '#forwardMaterializedRecord',
    '#insertNewEmploymentCycle',
    '#notifyMaterialized',
    '#propagateMaterializedStatus',
    '#registerCompletion',
    'apps/api/src/modules/transfer/required-fields.ts#assertRequiredTransferFields',
  ],
  'apps/api/src/modules/employment/write-service.ts#normalizePatchedInput': [
    'apps/api/src/modules/employment/fields.ts#normalizeEmploymentInput',
  ],
  'apps/api/src/modules/employment/write-service.ts#notifyMaterialized': [
    'apps/api/src/modules/employment/personnel-hooks.ts#personnelHooks',
    'apps/api/src/modules/employment/status-hooks.ts#employeeStatusHooks',
  ],
  'apps/api/src/modules/employment/write-service.ts#payloadAudit': ['#customAudit'],
  'apps/api/src/modules/employment/write-service.ts#propagateMaterializedStatus': [
    'apps/api/src/modules/employment/employee-status.ts#propagateEmployeeStatus',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/write-service.ts#registerCompletion': [
    'apps/api/src/modules/transfer/completion.ts#openCompletion',
    'apps/api/src/modules/transfer/completion.ts#reconcileCompletion',
    'packages/domain/src/transfer/required.ts#clearedTransferFields',
  ],
  'apps/api/src/modules/employment/write-service.ts#requireSavedBusiness': [
    'apps/api/src/modules/employment/read-model.ts#loadEmploymentBusiness',
    'packages/domain/src/tenant-time.ts#tenantLocalDate',
  ],
  'apps/api/src/modules/employment/write-service.ts#selectEmploymentCycle': [
    'apps/api/src/modules/employment/read-model.ts#findPredecessor',
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/write-service.ts#sequenceViolation': ['#NEW_CYCLE_KINDS'],
  'apps/api/src/modules/employment/write-service.ts#storedStatus': [
    'apps/api/src/modules/employment/record-store.ts#rowsOf',
  ],
  'apps/api/src/modules/employment/write-service.ts#updateEmploymentBusiness': [
    'apps/api/src/modules/employment/activation-checks.ts#assertEstablishmentCapacity',
    'apps/api/src/modules/employment/context.ts#auditEmployment',
    'apps/api/src/modules/employment/cycles.ts#assertNotBeforeCurrentCycle',
    'apps/api/src/modules/employment/employee-status.ts#inheritedStatus',
    'apps/api/src/modules/employment/fields.ts#normalizeBusinessPatch',
    'apps/api/src/modules/employment/inheritance.ts#prepareEmploymentPatch',
    'apps/api/src/modules/employment/inheritance.ts#resolveEffectiveInheritance',
    'apps/api/src/modules/employment/record-store.ts#bumpEmploymentBusiness',
    'apps/api/src/modules/employment/record-store.ts#lockEmploymentBusiness',
    '#NEW_CYCLE_KINDS',
    '#appendEmploymentPayload',
    '#assertBusinessSequence',
    '#assertEmployTypeUsage',
    '#normalizePatchedInput',
    '#payloadAudit',
    '#requireSavedBusiness',
    '#selectEmploymentCycle',
    '#validatePreparedEmployment',
    'apps/api/src/modules/transfer/employee-policy.ts#requireEmployeeTransferBusiness',
  ],
  'apps/api/src/modules/employment/write-service.ts#validatePreparedEmployment': [
    'apps/api/src/modules/employment/context.ts#requireScopedEmploymentObject',
    'apps/api/src/modules/employment/references.ts#newRecordReporting',
    'apps/api/src/modules/employment/references.ts#validateNewEmploymentReferences',
    'apps/api/src/modules/employment/transfer-linkage.ts#validateTransferSubordinates',
    'apps/api/src/modules/transfer/required-fields.ts#assertRequiredTransferFields',
  ],
  'apps/api/src/modules/employment/write-service.ts#validateTransferReposition': [
    'apps/api/src/modules/employment/cycles.ts#assertNotBeforeCurrentCycle',
    'apps/api/src/modules/employment/references.ts#validateNewEmploymentReferences',
    'apps/api/src/modules/employment/reporting-cycle.ts#windowBefore',
    'apps/api/src/modules/employment/timeline.ts#employmentTimelineNeighbors',
    'apps/api/src/modules/employment/timeline.ts#timelinePosition',
    '#assertBusinessSequence',
    '#assertSuccessorSequence',
    '#selectEmploymentCycle',
  ],
};
