/**
 * 直接依赖图：区域 domain-expression（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'packages/domain/src/expression/ast.ts#walk': ['#childrenOf', '#walk'],
  'packages/domain/src/expression/dates.ts#addMinutes': ['#dateOrdinal', '#fromOrdinal'],
  'packages/domain/src/expression/dates.ts#dateAdd': ['#DAY_MS', '#dateOrdinal', '#fromOrdinal', '#utcMs'],
  'packages/domain/src/expression/dates.ts#dateDiff': ['#DAY_MS', '#dateOrdinal', '#utcMs'],
  'packages/domain/src/expression/dates.ts#dateOrdinal': ['#utcMs'],
  'packages/domain/src/expression/dates.ts#isValidDate': ['#utcMs'],
  'packages/domain/src/expression/dates.ts#parseDateText': [
    '#DATE_TIME',
    '#TIME_ONLY',
    '#YEAR_MONTH',
    '#isValidDate',
    '#makeDateParts',
  ],
  'packages/domain/src/expression/engine.ts#ReferenceCollector': [
    'packages/domain/src/expression/ast.ts#childrenOf',
    'packages/domain/src/expression/failures.ts#hyphenHint',
    'packages/domain/src/expression/registry.ts#arityOf',
    'packages/domain/src/expression/typing.ts#NO_RECORDS',
    'packages/domain/src/expression/typing.ts#TypeInference',
    'packages/domain/src/expression/typing.ts#verdictFor',
    'packages/domain/src/expression/typing.ts#withRecordObjects',
    'packages/domain/src/expression/values.ts#isMultiOptionField',
  ],
  'packages/domain/src/expression/engine.ts#cycleGroups': ['#cyclicComponents', '#representativeCycle'],
  'packages/domain/src/expression/engine.ts#describeGroup': ['#identityDisplay'],
  'packages/domain/src/expression/engine.ts#orderComputationItems': ['#orderItems'],
  'packages/domain/src/expression/engine.ts#orderItems': [
    '#MAX_REPORTED_CYCLES',
    '#cycleGroups',
    '#describeGroup',
    '#diagnostic',
    '#identityDisplay',
    '#parseItems',
    '#topologicalOrder',
    'packages/domain/src/expression/registry.ts#createDefaultRegistry',
  ],
  'packages/domain/src/expression/engine.ts#parseItems': [
    '#diagnostic',
    '#identityDisplay',
    '#resolveComputedField',
    '#validateFormula',
    'packages/domain/src/expression/values.ts#isMultiOptionField',
  ],
  'packages/domain/src/expression/engine.ts#resolveComputedField': ['#lastSegment'],
  'packages/domain/src/expression/engine.ts#topologicalOrder': ['#diagnostic'],
  'packages/domain/src/expression/engine.ts#validateFormula': [
    '#ReferenceCollector',
    '#byOffset',
    'packages/domain/src/expression/parser.ts#parseFormula',
    'packages/domain/src/expression/registry.ts#createDefaultRegistry',
  ],
  'packages/domain/src/expression/failures.ts#fail': ['#ComputationError', '#FAILURE_PREFIX'],
  'packages/domain/src/expression/failures.ts#hyphenHint': ['#HYPHEN_SUBTRACTION_HINT'],
  'packages/domain/src/expression/functions/assessment.ts#ASSESSMENT_FUNCTIONS': [
    '#ASSESSMENT_OBJECTS',
    '#latestAssessment',
  ],
  'packages/domain/src/expression/functions/assessment.ts#latestAssessment': [
    '#ASSESSMENT_OBJECTS',
    'packages/domain/src/expression/functions/shared.ts#latestBoundary',
    'packages/domain/src/expression/functions/shared.ts#matchesAll',
    'packages/domain/src/expression/functions/shared.ts#recordReader',
    'packages/domain/src/expression/functions/shared.ts#requireFieldOf',
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
    'packages/domain/src/expression/functions/shared.ts#withinBoundary',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/core.ts#CORE_FUNCTIONS': [
    '#aggregate',
    '#param',
    '#sum',
    '#toNumberFunction',
    'packages/domain/src/expression/functions/shared.ts#average',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/core.ts#aggregate': ['#aggregateNumbers', '#param'],
  'packages/domain/src/expression/functions/core.ts#aggregateNumbers': [
    'packages/domain/src/expression/operators.ts#operandNumber',
  ],
  'packages/domain/src/expression/functions/core.ts#sum': [
    '#aggregateNumbers',
    'packages/domain/src/expression/operators.ts#operandNumber',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/core.ts#toNumberFunction': [
    'packages/domain/src/expression/failures.ts#ComputationError',
    'packages/domain/src/expression/operators.ts#toNumberValue',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/datasets.ts#DATASET_FUNCTIONS': [
    '#TALENT_REVIEW_PREFIXES',
    '#latestTalentReview',
    '#parameterRuleData',
    '#personnelSubsetField',
  ],
  'packages/domain/src/expression/functions/datasets.ts#TALENT_REVIEW_PREFIXES': ['#TALENT_REVIEW_OBJECT'],
  'packages/domain/src/expression/functions/datasets.ts#latestTalentReview': [
    '#TALENT_REVIEW_PREFIXES',
    '#passedLatestFirst',
    'packages/domain/src/expression/functions/shared.ts#matchesAll',
    'packages/domain/src/expression/functions/shared.ts#recordReader',
    'packages/domain/src/expression/functions/shared.ts#requireFieldOf',
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/datasets.ts#parameterRuleData': [
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
  ],
  'packages/domain/src/expression/functions/datasets.ts#personnelSubsetField': [
    'packages/domain/src/expression/functions/shared.ts#matchesAll',
    'packages/domain/src/expression/functions/shared.ts#recordReader',
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/dates.ts#DATE_FUNCTIONS': [
    'packages/domain/src/expression/dates.ts#addMinutes',
    'packages/domain/src/expression/dates.ts#dateAdd',
    'packages/domain/src/expression/dates.ts#dateDiff',
    'packages/domain/src/expression/dates.ts#dateOrdinal',
    'packages/domain/src/expression/dates.ts#formatDate',
    'packages/domain/src/expression/dates.ts#makeDateParts',
    '#amountArg',
    '#byUnit',
    '#dateAddition',
    '#dateArg',
    '#datePart',
    '#dateTransform',
    '#dateValue',
    '#dayOfYear',
    '#difference',
    '#nextMonthFirstDay',
    '#now',
    '#num',
    '#param',
    '#timeOnly',
    '#today',
    '#unitArg',
    '#utcDay',
  ],
  'packages/domain/src/expression/functions/dates.ts#byUnit': ['packages/domain/src/expression/dates.ts#dateAdd'],
  'packages/domain/src/expression/functions/dates.ts#dateAddition': ['#amountArg', '#dateArg', '#dateValue', '#param'],
  'packages/domain/src/expression/functions/dates.ts#datePart': ['#dateArg', '#num', '#param'],
  'packages/domain/src/expression/functions/dates.ts#dateTransform': ['#dateArg', '#dateValue', '#param'],
  'packages/domain/src/expression/functions/dates.ts#dayOfYear': [
    'packages/domain/src/expression/dates.ts#utcMs',
    '#DAY_MS',
    '#utcDay',
  ],
  'packages/domain/src/expression/functions/dates.ts#difference': ['#dateArg', '#num', '#param'],
  'packages/domain/src/expression/functions/dates.ts#nextMonthFirstDay': [
    'packages/domain/src/expression/dates.ts#dateAdd',
    'packages/domain/src/expression/dates.ts#makeDateParts',
  ],
  'packages/domain/src/expression/functions/dates.ts#now': ['packages/domain/src/expression/dates.ts#instantToParts'],
  'packages/domain/src/expression/functions/dates.ts#today': ['packages/domain/src/expression/dates.ts#parseDateText'],
  'packages/domain/src/expression/functions/dates.ts#unitArg': [
    'packages/domain/src/expression/dates.ts#parseDateUnit',
  ],
  'packages/domain/src/expression/functions/dates.ts#utcDay': ['packages/domain/src/expression/dates.ts#utcMs'],
  'packages/domain/src/expression/functions/index.ts#BUILTIN_FUNCTIONS': [
    'packages/domain/src/expression/functions/assessment.ts#ASSESSMENT_FUNCTIONS',
    'packages/domain/src/expression/functions/core.ts#CORE_FUNCTIONS',
    'packages/domain/src/expression/functions/datasets.ts#DATASET_FUNCTIONS',
    'packages/domain/src/expression/functions/dates.ts#DATE_FUNCTIONS',
    'packages/domain/src/expression/functions/logic.ts#LOGIC_FUNCTIONS',
    'packages/domain/src/expression/functions/math.ts#MATH_FUNCTIONS',
    'packages/domain/src/expression/functions/performance.ts#PERFORMANCE_FUNCTIONS',
    'packages/domain/src/expression/functions/ranking.ts#RANKING_FUNCTIONS',
    'packages/domain/src/expression/functions/review.ts#REVIEW_FUNCTIONS',
    'packages/domain/src/expression/functions/survey360.ts#SURVEY360_FUNCTIONS',
  ],
  'packages/domain/src/expression/functions/logic.ts#LOGIC_FUNCTIONS': [
    '#bool',
    '#condition',
    '#emptyCheck',
    '#memberOf',
    '#param',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/logic.ts#emptyCheck': [
    '#bool',
    '#isBlank',
    '#param',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/logic.ts#memberOf': [
    'packages/domain/src/expression/operators.ts#valuesEqual',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/math.ts#MATH_FUNCTIONS': ['#mod', '#param', '#rounding', '#unary'],
  'packages/domain/src/expression/functions/math.ts#digitsArg': ['#MAX_DIGITS'],
  'packages/domain/src/expression/functions/math.ts#mod': ['#num'],
  'packages/domain/src/expression/functions/math.ts#rounding': ['#digitsArg', '#num', '#param', '#roundDecimal'],
  'packages/domain/src/expression/functions/math.ts#unary': ['#num', '#param'],
  'packages/domain/src/expression/functions/performance.ts#FILTER_PARAMS': ['#filterParam'],
  'packages/domain/src/expression/functions/performance.ts#PERFORMANCE_FUNCTIONS': [
    '#FILTER_PARAMS',
    '#PERFORMANCE_FIELDS',
    '#RECENT_OCCURRENCE_PARAMS',
    '#RECENT_YEAR_PARAMS',
    '#byFilters',
    '#byRecentOccurrence',
    '#byRecentYear',
    '#fetchSpec',
    '#recentOccurrenceCheck',
    '#recentYearCheck',
  ],
  'packages/domain/src/expression/functions/performance.ts#PREFIXES': ['#PERFORMANCE_FIELDS'],
  'packages/domain/src/expression/functions/performance.ts#RECENT_OCCURRENCE_PARAMS': ['#filterParam'],
  'packages/domain/src/expression/functions/performance.ts#RECENT_YEAR_PARAMS': ['#filterParam'],
  'packages/domain/src/expression/functions/performance.ts#byFilters': ['#filtered', '#newestFirst', '#resultField'],
  'packages/domain/src/expression/functions/performance.ts#byRecentOccurrence': [
    'packages/domain/src/expression/dates.ts#dateOrdinal',
    '#filtered',
    '#newestFirst',
    '#recencyArgs',
    '#resultField',
  ],
  'packages/domain/src/expression/functions/performance.ts#byRecentYear': [
    '#filtered',
    '#newestFirst',
    '#recencyArgs',
    '#referenceYear',
    '#resultField',
    '#yearOf',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/performance.ts#fetchSpec': ['#PERFORMANCE_FIELDS', '#PREFIXES'],
  'packages/domain/src/expression/functions/performance.ts#filtered': [
    '#PREFIXES',
    '#records',
    'packages/domain/src/expression/functions/shared.ts#matchesAll',
    'packages/domain/src/expression/functions/shared.ts#recordReader',
  ],
  'packages/domain/src/expression/functions/performance.ts#isRecordField': ['#PERFORMANCE_FIELDS'],
  'packages/domain/src/expression/functions/performance.ts#recencyArgs': ['#recencyRoles'],
  'packages/domain/src/expression/functions/performance.ts#recencyRoles': [
    '#isRecordField',
    '#nth',
    'packages/domain/src/expression/typing.ts#isDefinitely',
    'packages/domain/src/expression/typing.ts#mayBe',
  ],
  'packages/domain/src/expression/functions/performance.ts#recentOccurrenceCheck': ['#recencyRoles'],
  'packages/domain/src/expression/functions/performance.ts#recentYearCheck': ['#recencyRoles'],
  'packages/domain/src/expression/functions/performance.ts#records': [
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
  ],
  'packages/domain/src/expression/functions/performance.ts#referenceYear': [
    'packages/domain/src/expression/dates.ts#instantToParts',
  ],
  'packages/domain/src/expression/functions/performance.ts#resultField': [
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/performance.ts#yearOf': ['#PERFORMANCE_FIELDS'],
  'packages/domain/src/expression/functions/ranking.ts#RANKING_FUNCTIONS': ['#checkRankingArgs', '#ranking'],
  'packages/domain/src/expression/functions/ranking.ts#buildTable': [
    '#entryOf',
    '#rangeArgs',
    'packages/domain/src/expression/operators.ts#equalityStoreKeys',
  ],
  'packages/domain/src/expression/functions/ranking.ts#candidates': [
    'packages/domain/src/expression/operators.ts#equalityLookupKeys',
  ],
  'packages/domain/src/expression/functions/ranking.ts#checkMode': [
    '#modeOf',
    'packages/domain/src/expression/typing.ts#verdictFor',
  ],
  'packages/domain/src/expression/functions/ranking.ts#checkRange': [
    '#DATA_RANGE',
    '#NEW_RANGE',
    '#isReference',
    '#rangeRole',
    'packages/domain/src/expression/typing.ts#isDefinitely',
    'packages/domain/src/expression/typing.ts#verdictFor',
  ],
  'packages/domain/src/expression/functions/ranking.ts#checkRankingArgs': [
    '#DATA_RANGE',
    '#checkMode',
    '#checkRange',
    '#checkSortField',
  ],
  'packages/domain/src/expression/functions/ranking.ts#checkSortField': [
    '#isReference',
    'packages/domain/src/expression/typing.ts#isDefinitely',
  ],
  'packages/domain/src/expression/functions/ranking.ts#dateText': ['#numberText'],
  'packages/domain/src/expression/functions/ranking.ts#encodeValue': ['#dateText', '#numberText'],
  'packages/domain/src/expression/functions/ranking.ts#entryOf': ['#rangeValue', '#scoreOf', '#tryEvaluate'],
  'packages/domain/src/expression/functions/ranking.ts#modeOf': ['#MODES'],
  'packages/domain/src/expression/functions/ranking.ts#ownResult': [
    'packages/domain/src/expression/failures.ts#CONVERSION_MESSAGE',
    'packages/domain/src/expression/failures.ts#ComputationError',
    '#isBlank',
    '#rangeArgs',
    '#rangeValue',
    'packages/domain/src/expression/functions/shared.ts#isTypeConversion',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/ranking.ts#peerScores': [
    '#candidates',
    '#encodeValue',
    'packages/domain/src/expression/operators.ts#valuesEqual',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/ranking.ts#rangeArgs': ['#DATA_RANGE', '#rangeRole'],
  'packages/domain/src/expression/functions/ranking.ts#rangeRole': [
    '#DATA_RANGE',
    '#OLD_GROUP',
    'packages/domain/src/expression/typing.ts#isDefinitely',
    'packages/domain/src/expression/typing.ts#mayBe',
  ],
  'packages/domain/src/expression/functions/ranking.ts#rangeValue': ['packages/domain/src/expression/values.ts#EMPTY'],
  'packages/domain/src/expression/functions/ranking.ts#ranking': [
    '#countGreater',
    '#isReference',
    '#modeOf',
    '#ownResult',
    '#peerScores',
    '#percentile',
    '#tableFor',
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
  ],
  'packages/domain/src/expression/functions/ranking.ts#semanticKey': [
    'packages/domain/src/expression/ast.ts#walk',
    '#encodeValue',
  ],
  'packages/domain/src/expression/functions/ranking.ts#tableFor': [
    '#MAX_TABLES_PER_CALL',
    '#buildTable',
    '#semanticKey',
  ],
  'packages/domain/src/expression/functions/ranking.ts#tryEvaluate': [
    'packages/domain/src/expression/failures.ts#ComputationError',
  ],
  'packages/domain/src/expression/functions/review.ts#REVIEW_FUNCTIONS': [
    '#activeJudges',
    '#judgeMatches',
    '#moduleNamed',
    '#modules',
    '#param',
    '#scores',
    'packages/domain/src/expression/functions/shared.ts#average',
    'packages/domain/src/expression/operators.ts#valuesEqual',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/review.ts#judgeMatches': [
    'packages/domain/src/expression/operators.ts#valuesEqual',
  ],
  'packages/domain/src/expression/functions/review.ts#moduleNamed': ['#modules'],
  'packages/domain/src/expression/functions/review.ts#modules': [
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
  ],
  'packages/domain/src/expression/functions/shared.ts#average': ['packages/domain/src/expression/values.ts#EMPTY'],
  'packages/domain/src/expression/functions/shared.ts#isTypeConversion': [
    'packages/domain/src/expression/failures.ts#ComputationError',
  ],
  'packages/domain/src/expression/functions/shared.ts#matchesAll': ['#isTypeConversion'],
  'packages/domain/src/expression/functions/shared.ts#recordReader': [
    'packages/domain/src/expression/ast.ts#walk',
    '#prefixedFields',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/functions/shared.ts#unwrapPort': ['#PORT_LABELS'],
  'packages/domain/src/expression/functions/survey360.ts#PREFIXES': ['#SURVEY360_OBJECT'],
  'packages/domain/src/expression/functions/survey360.ts#SURVEY360_FUNCTIONS': ['#PREFIXES', '#latest360'],
  'packages/domain/src/expression/functions/survey360.ts#latest360': [
    'packages/domain/src/expression/functions/shared.ts#latestBoundary',
    'packages/domain/src/expression/functions/shared.ts#matchesAll',
    'packages/domain/src/expression/functions/shared.ts#recordReader',
    'packages/domain/src/expression/functions/shared.ts#requireFieldOf',
    'packages/domain/src/expression/functions/shared.ts#unwrapPort',
    'packages/domain/src/expression/functions/shared.ts#withinBoundary',
    '#PREFIXES',
    '#activityKey',
    '#isFinished',
    '#latestFirst',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/lexer.ts#HANDLE_AT': ['#UUID_SOURCE'],
  'packages/domain/src/expression/lexer.ts#Scanner': [
    '#CHINESE_QUOTES',
    '#HANDLE_AT',
    '#HIDDEN_FIELD_PLACEHOLDER',
    '#KEYWORDS',
    '#OPERATORS',
    '#PUNCTUATION',
    '#SLASH_FUNCTION_NAMES',
    '#SyntaxIssueError',
    '#isDigit',
    '#isIdentPart',
    '#isIdentStart',
    '#isSpace',
  ],
  'packages/domain/src/expression/lexer.ts#isIdentPart': ['#isDigit', '#isIdentStart'],
  'packages/domain/src/expression/lexer.ts#isIdentStart': ['#isCjk', '#isLetter'],
  'packages/domain/src/expression/lexer.ts#tokenize': ['#Scanner'],
  'packages/domain/src/expression/operators.ts#comparable': [
    'packages/domain/src/expression/dates.ts#dateOrdinal',
    'packages/domain/src/expression/dates.ts#parseDateText',
    '#numericText',
  ],
  'packages/domain/src/expression/operators.ts#equalityLookupKeys': [
    'packages/domain/src/expression/dates.ts#dateOrdinal',
    'packages/domain/src/expression/dates.ts#parseDateText',
    '#numericText',
    '#scalarKey',
    '#unwrapOption',
  ],
  'packages/domain/src/expression/operators.ts#equalityStoreKeys': [
    'packages/domain/src/expression/dates.ts#dateOrdinal',
    'packages/domain/src/expression/dates.ts#parseDateText',
    '#numericText',
    '#scalarKey',
    '#unwrapOption',
  ],
  'packages/domain/src/expression/operators.ts#numericText': ['#PERCENT'],
  'packages/domain/src/expression/operators.ts#operandNumber': [
    'packages/domain/src/expression/failures.ts#fail',
    '#numericText',
    '#toNumber',
    'packages/domain/src/expression/values.ts#describeValue',
  ],
  'packages/domain/src/expression/operators.ts#scalarKey': [
    'packages/domain/src/expression/dates.ts#dateOrdinal',
    '#toText',
  ],
  'packages/domain/src/expression/operators.ts#toNumber': [
    'packages/domain/src/expression/failures.ts#CONVERSION_MESSAGE',
    'packages/domain/src/expression/failures.ts#fail',
    '#numericText',
    'packages/domain/src/expression/values.ts#describeValue',
  ],
  'packages/domain/src/expression/operators.ts#toNumberValue': [
    '#toNumber',
    'packages/domain/src/expression/values.ts#EMPTY',
  ],
  'packages/domain/src/expression/operators.ts#toText': ['packages/domain/src/expression/values.ts#formatIsoLike'],
  'packages/domain/src/expression/operators.ts#valuesEqual': [
    'packages/domain/src/expression/failures.ts#fail',
    '#comparable',
    '#unwrapOption',
  ],
  'packages/domain/src/expression/parser.ts#Parser': [
    'packages/domain/src/expression/failures.ts#HYPHEN_SUBTRACTION_HINT',
    'packages/domain/src/expression/lexer.ts#HIDDEN_FIELD_OWNER',
    'packages/domain/src/expression/lexer.ts#HIDDEN_FIELD_PLACEHOLDER',
    'packages/domain/src/expression/lexer.ts#SyntaxIssueError',
    '#ASCII_WORD',
    '#COMPARISONS',
    '#DEF_NAMES',
    '#KEYWORD_FUNCTIONS',
    '#MAX_NESTING_DEPTH',
  ],
  'packages/domain/src/expression/parser.ts#limitIssue': ['#MAX_FORMULA_LENGTH', '#MAX_FORMULA_TOKENS', '#ORIGIN'],
  'packages/domain/src/expression/parser.ts#parseFormula': [
    'packages/domain/src/expression/lexer.ts#SyntaxIssueError',
    '#ORIGIN',
    '#Parser',
    '#scan',
  ],
  'packages/domain/src/expression/parser.ts#scan': [
    'packages/domain/src/expression/lexer.ts#SyntaxIssueError',
    'packages/domain/src/expression/lexer.ts#tokenize',
    '#MAX_FORMULA_LENGTH',
    '#MAX_FORMULA_TOKENS',
    '#ORIGIN',
    '#limitIssue',
  ],
  'packages/domain/src/expression/registry.ts#FunctionRegistry': ['#normalize'],
  'packages/domain/src/expression/registry.ts#createDefaultRegistry': [
    'packages/domain/src/expression/functions/index.ts#BUILTIN_FUNCTIONS',
    '#FunctionRegistry',
  ],
  'packages/domain/src/expression/typing.ts#TypeInference': [
    'packages/domain/src/expression/dates.ts#parseDateText',
    '#ARITHMETIC',
    '#DEFINITE',
    '#NO_RECORDS',
    '#UNCERTAIN',
    '#declaredType',
    '#mergeTypes',
    '#withRecordObjects',
  ],
  'packages/domain/src/expression/typing.ts#declaredType': ['#UNCERTAIN', '#fromKinds'],
  'packages/domain/src/expression/typing.ts#fromKinds': ['#DEFINITE', '#UNCERTAIN'],
  'packages/domain/src/expression/typing.ts#mayBe': ['#possibleKinds'],
  'packages/domain/src/expression/typing.ts#mergeTypes': ['#UNCERTAIN', '#fromKinds', '#possibleKinds'],
  'packages/domain/src/expression/typing.ts#verdictFor': ['#isDefinitely', '#mayBe'],
  'packages/domain/src/expression/typing.ts#withRecordObjects': ['#RECORD_SCOPES'],
  'packages/domain/src/expression/values.ts#describeValue': ['#KIND_LABELS', '#formatIsoLike'],
};
