/**
 * 直接依赖图：区域 domain-approval（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'packages/domain/src/approval/conditions.ts#conditionViolations': [
    '#MAX_CONDITION_ITEMS',
    '#defaultExpression',
    '#parse',
    '#tokenize',
    '#valueViolations',
    'packages/domain/src/approval/types.ts#CONDITION_OPERATORS',
  ],
  'packages/domain/src/approval/conditions.ts#evaluateCondition': [
    '#defaultExpression',
    '#itemResult',
    '#parse',
    '#tokenize',
  ],
  'packages/domain/src/approval/conditions.ts#itemResult': ['#empty'],
  'packages/domain/src/approval/countersign.ts#countersignOutcome': ['#EXIT_PRIORITY', '#exitThreshold'],
  'packages/domain/src/approval/countersign.ts#countersignVote': ['#VOTES'],
  'packages/domain/src/approval/countersign.ts#exitRuleViolation': [
    '#MAX_EXIT_COUNT',
    '#hasTwoDecimalsAtMost',
    'packages/domain/src/approval/types.ts#EXIT_LABELS',
    'packages/domain/src/approval/types.ts#EXIT_RULE_KINDS',
  ],
  'packages/domain/src/approval/countersign.ts#exitRulesOf': ['#EVERYONE', '#ONE_PERSON'],
  'packages/domain/src/approval/countersign.ts#transitionRuleViolations': [
    '#exitRuleViolation',
    '#exitRulesOf',
    '#sameRule',
    'packages/domain/src/approval/types.ts#EXIT_LABELS',
    'packages/domain/src/approval/types.ts#NODE_EXITS',
    'packages/domain/src/approval/types.ts#TRANSITION_RULE_TYPES',
    'packages/domain/src/approval/types.ts#nodeExits',
  ],
  'packages/domain/src/approval/definition.ts#avoidSubjectsViolations': [
    'packages/domain/src/approval/types.ts#ENABLED_AVOID_SUBJECTS_RESULTS',
    'packages/domain/src/approval/types.ts#avoidsSubjects',
    'packages/domain/src/approval/types.ts#hasExit',
    'packages/domain/src/approval/types.ts#isCountersign',
  ],
  'packages/domain/src/approval/definition.ts#definitionViolations': [
    'packages/domain/src/approval/conditions.ts#conditionViolations',
    '#CUSTOM_FIELD',
    '#MAX_NODES',
    '#NODE_KEY',
    '#nodeShapeViolations',
    'packages/domain/src/approval/types.ts#IDP_ONLY_APPROVERS',
    'packages/domain/src/approval/types.ts#approverExpressionsOf',
  ],
  'packages/domain/src/approval/definition.ts#nodeShapeViolations': [
    'packages/domain/src/approval/countersign.ts#transitionRuleViolations',
    'packages/domain/src/approval/types.ts#isCountersign',
    'packages/domain/src/approval/types.ts#nodeExits',
  ],
  'packages/domain/src/approval/definition.ts#publishViolations': [
    '#avoidSubjectsViolations',
    'packages/domain/src/approval/types.ts#hasExit',
  ],
  'packages/domain/src/approval/presets.ts#IDP_EMPLOYEE_ACTIONS': ['#IDP_ACTIONS'],
  'packages/domain/src/approval/presets.ts#IDP_TUTOR_ACTIONS': ['#IDP_ACTIONS'],
  'packages/domain/src/approval/presets.ts#PRESET_ACTIONS': ['#PRESET_RECUSAL'],
  'packages/domain/src/approval/presets.ts#PRESET_PROCESSES': [
    '#IDP_EMPLOYEE_ACTIONS',
    '#IDP_TUTOR_ACTIONS',
    '#LEAVE_FORM',
    '#PRESET_ACTIONS',
    '#draft',
    '#genericPreset',
    '#node',
    '#standardCondition',
  ],
  'packages/domain/src/approval/presets.ts#genericPreset': [
    '#GENERIC_FORM',
    '#draft',
    '#node',
    '#standardCondition',
    'packages/domain/src/approval/types.ts#APPROVAL_TYPES',
    'packages/domain/src/contracts/rules.ts#CONTRACT_FIELDS',
  ],
  'packages/domain/src/approval/presets.ts#node': [
    '#PRESET_ACTIONS',
    'packages/domain/src/approval/transfer-view.ts#TRANSFER_FORM_FIELDS',
  ],
  'packages/domain/src/approval/presets.ts#standardCondition': ['packages/domain/src/approval/types.ts#APPROVAL_TYPES'],
  'packages/domain/src/approval/recusal.ts#instanceRecusal': ['#isInitiator', '#isSubject'],
  'packages/domain/src/approval/recusal.ts#isInitiator': ['#lower'],
  'packages/domain/src/approval/recusal.ts#isPrimary': ['#lower'],
  'packages/domain/src/approval/recusal.ts#isSubject': ['#lower'],
  'packages/domain/src/approval/recusal.ts#nodeRecusal': [
    '#isInitiator',
    '#isPrimary',
    '#isSubject',
    'packages/domain/src/approval/types.ts#avoidsSelf',
    'packages/domain/src/approval/types.ts#avoidsSubjects',
  ],
  'packages/domain/src/approval/recusal.ts#recusalFacts': ['#lower'],
  'packages/domain/src/approval/routing.ts#adminRecused': [
    'packages/domain/src/approval/recusal.ts#instanceRecusal',
    '#whoOf',
  ],
  'packages/domain/src/approval/routing.ts#avoidSelfExceptionAdmin': [
    'packages/domain/src/approval/recusal.ts#instanceRecusal',
    '#adminRecused',
    '#whoOf',
  ],
  'packages/domain/src/approval/routing.ts#decideNode': [
    'packages/domain/src/approval/recusal.ts#nodeRecusal',
    '#auto',
    '#exceptionAdmin',
    '#whoOf',
  ],
  'packages/domain/src/approval/transfer-view.ts#TRANSFER_DETAIL_VIEW': ['#NO_MODEL', '#form', '#later'],
  'packages/domain/src/approval/transfer-view.ts#TRANSFER_FORM_FIELDS': ['#TRANSFER_DETAIL_VIEW'],
  'packages/domain/src/approval/types.ts#APPROVAL_TYPES': [
    '#EMPLOYEE_INFO_CONDITION_FIELDS',
    '#PERSONNEL_CONDITION_FIELDS',
    '#contractType',
    '#employeeInfoFormFields',
    '#employmentType',
    '#idpType',
    '#personnelFormFields',
    'packages/domain/src/personnel/catalog.ts#PERSONNEL_OBJECT',
    'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS',
  ],
  'packages/domain/src/approval/types.ts#EMPLOYEE_INFO_CONDITION_FIELDS': ['#PERSONNEL_CONDITION_FIELDS'],
  'packages/domain/src/approval/types.ts#IDP_PLAN_OBJECT': ['packages/domain/src/idp/catalog.ts#IDP_APP'],
  'packages/domain/src/approval/types.ts#approvalTypeOfBusiness': [
    '#APPROVAL_TYPES',
    '#ENTRY_KINDS',
    '#isApprovalType',
  ],
  'packages/domain/src/approval/types.ts#approverExpressionsOf': ['#isCountersign'],
  'packages/domain/src/approval/types.ts#contractType': [
    '#EMPLOYMENT_CONDITION_FIELDS',
    'packages/domain/src/contracts/rules.ts#CONTRACT_FIELDS',
    'packages/domain/src/contracts/rules.ts#CONTRACT_OBJECT',
  ],
  'packages/domain/src/approval/types.ts#employeeInfoFormFields': [
    'packages/domain/src/personnel/fields.ts#EMPLOYEE_EDITABLE_FIELDS',
  ],
  'packages/domain/src/approval/types.ts#employmentFormFields': [
    '#PROFILE_FORM_FIELDS',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'packages/domain/src/approval/types.ts#employmentType': [
    '#EMPLOYMENT_CONDITION_FIELDS',
    '#PROFILE_FORM_FIELDS',
    '#employmentFormFields',
    'packages/domain/src/permission/module-actions.ts#MODULE_OBJECTS',
  ],
  'packages/domain/src/approval/types.ts#hasExit': ['#nodeExits'],
  'packages/domain/src/approval/types.ts#idpType': ['#IDP_PLAN_OBJECT'],
  'packages/domain/src/approval/types.ts#isApprovalType': ['#APPROVAL_TYPES'],
  'packages/domain/src/approval/types.ts#nodeExits': ['#DEFAULT_EXITS'],
  'packages/domain/src/approval/types.ts#personnelFormFields': ['packages/domain/src/personnel/fields.ts#SUBSETS'],
  'packages/domain/src/approval/types.ts#subsetProcessCode': ['#SUBSET_PROCESS_CODES'],
};
