/**
 * 直接依赖图：区域 domain-talent-review（节点 → 直接依赖，字典序；同文件的依赖写作 #名字；没有依赖的叶子不登记）。
 * 生成文件（F-072）：改源码后用 `ROUTE_POLICY_UPDATE_DIGESTS=1` 重算，不要手改；冲突时取任一侧后重算。
 */
import type { Graph } from '../../../evidence-graph.js';

export const GRAPH: Graph = {
  'packages/domain/src/talent-review/calc-rule.ts#analyzeCalcItems': [
    'packages/domain/src/expression/engine.ts#orderComputationItems',
    'packages/domain/src/expression/engine.ts#validateFormula',
    'packages/domain/src/expression/registry.ts#createDefaultRegistry',
    '#FORMULA_CONTEXT_FIELDS',
    '#formulaFieldKind',
    '#formulaPath',
    '#formulaReferences',
    '#toIssue',
  ],
  'packages/domain/src/talent-review/calc-rule.ts#formulaPath': ['#FORMULA_OBJECT'],
  'packages/domain/src/talent-review/calc-rule.ts#formulaReferences': [
    'packages/domain/src/expression/engine.ts#validateFormula',
  ],
  'packages/domain/src/talent-review/calc-rule.ts#textMentionsField': [
    'packages/domain/src/expression/engine.ts#validateFormula',
    '#fieldNameTerms',
    '#formulaPath',
  ],
  'packages/domain/src/talent-review/calc-rule.ts#unreferenceableItem': [
    'packages/domain/src/expression/engine.ts#validateFormula',
    'packages/domain/src/expression/registry.ts#createDefaultRegistry',
    '#FORMULA_CONTEXT_FIELDS',
    '#formulaPath',
    '#toIssue',
  ],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS>calcRule': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS>category': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS>field': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS>matrix': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS>readiness': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS>role': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#TALENT_REVIEW_OBJECTS>settings': ['#object'],
  'packages/domain/src/talent-review/catalog.ts#object': ['#SYSTEM_FIELDS', '#TALENT_REVIEW_APP', '#crud'],
  'packages/domain/src/talent-review/formula-audit.ts#filterHints': ['#ids', '#isObject'],
  'packages/domain/src/talent-review/formula-audit.ts#filterRefs': ['#isObject'],
  'packages/domain/src/talent-review/formula-audit.ts#redactCalcRuleAuditValue': [
    '#filterHints',
    '#filterRefs',
    '#isChange',
    '#isItem',
    '#isObject',
    '#redactCalcRuleAuditValue',
    '#redactItem',
    '#withoutDerivedText',
  ],
  'packages/domain/src/talent-review/formula-audit.ts#redactItem': ['#renderOld', '#renderStored'],
  'packages/domain/src/talent-review/formula-audit.ts#renderOld': [
    'packages/domain/src/talent-review/formula-binding.ts#FORMULA_REPAIR_NOTICE',
    'packages/domain/src/talent-review/formula-binding.ts#renderFormula',
  ],
  'packages/domain/src/talent-review/formula-audit.ts#renderStored': [
    '#isObject',
    'packages/domain/src/talent-review/formula-binding.ts#FORMULA_REPAIR_NOTICE',
    'packages/domain/src/talent-review/formula-binding.ts#renderFormula',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#RESERVED_PATH': [
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_OBJECT',
    '#RESERVED_NAME',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#acceptedByEngine': [
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_CONTEXT_FIELDS',
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_OBJECT',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#bareWords': ['packages/domain/src/expression/ast.ts#walk'],
  'packages/domain/src/talent-review/formula-binding.ts#bindFormula': [
    'packages/domain/src/expression/engine.ts#validateFormula',
    'packages/domain/src/expression/parser.ts#parseFormula',
    '#PRECHECK_CODES',
    '#acceptedByEngine',
    '#at',
    '#fieldNodes',
    '#fromSyntax',
    '#invalid',
    '#isObjectReference',
    '#resolveReferences',
    '#semanticIssues',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#canonicalText': [
    'packages/domain/src/expression/lexer.ts#fieldHandle',
    '#CONTEXT_BINDING',
    '#RESERVED_PATH',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#fieldNodes': ['packages/domain/src/expression/ast.ts#walk'],
  'packages/domain/src/talent-review/formula-binding.ts#isObjectReference': [
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_OBJECT',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#renderBound': [
    'packages/domain/src/expression/lexer.ts#HIDDEN_FIELD_PLACEHOLDER',
    'packages/domain/src/expression/parser.ts#parseStoredFormula',
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_OBJECT',
    '#CONTEXT_BINDING',
    '#RESERVED_PATH',
    '#fieldNodes',
    '#startsWithObject',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#renderFormula': ['#renderBound', '#renderLegacy'],
  'packages/domain/src/talent-review/formula-binding.ts#renderLegacy': [
    'packages/domain/src/expression/lexer.ts#HIDDEN_FIELD_PLACEHOLDER',
    'packages/domain/src/expression/parser.ts#parseFormula',
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_OBJECT',
    '#FORMULA_REPAIR_NOTICE',
    '#fieldNodes',
    '#startsWithObject',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#resolveReferences': [
    '#CONTEXT_BINDING',
    '#RESERVED_NAME',
    '#at',
    '#canonicalText',
    '#invalid',
    '#normalizeId',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#semanticIssues': [
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_OBJECT',
    '#at',
    '#bareWords',
    '#fromSyntax',
  ],
  'packages/domain/src/talent-review/formula-binding.ts#startsWithObject': [
    'packages/domain/src/talent-review/calc-rule.ts#FORMULA_OBJECT',
  ],
  'packages/domain/src/talent-review/formula-rename.ts#checkRenameRoundTrip': [
    'packages/domain/src/expression/parser.ts#checkInputLimits',
    'packages/domain/src/talent-review/formula-binding.ts#bindFormula',
    'packages/domain/src/talent-review/formula-binding.ts#renderFormula',
  ],
  'packages/domain/src/talent-review/matrix.ts#checkAxisLevels': [
    '#MATRIX_MAX_LEVELS',
    '#MATRIX_MIN_LEVELS',
    '#checkOptionLevels',
    '#violation',
  ],
  'packages/domain/src/talent-review/matrix.ts#checkCells': ['#checkExportOrder', '#violation'],
  'packages/domain/src/talent-review/matrix.ts#checkExportOrder': ['#violation'],
  'packages/domain/src/talent-review/matrix.ts#checkOptionLevels': ['#violation'],
  'packages/domain/src/talent-review/matrix.ts#checkRatioRule': ['#violation'],
};
