'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {clientIntent,queryClientCommand} from '@/lib/hris/r1-client-command';
export default function ReportActions({catalog,dataset,fields,selected,data,definitionId,onChanged}:{catalog:any;dataset:string;fields:any[];selected:string[];data:any;definitionId:string;onChanged:()=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[unknown,setUnknown]=useState<string|null>(null),[jobs,setJobs]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]),[title,setTitle]=useState(''),[draftId,setDraftId]=useState(''),[draftRevision,setDraftRevision]=useState(0),[org,setOrg]=useState(''),[filterField,setFilterField]=useState(''),[filterValue,setFilterValue]=useState(''),[groupField,setGroupField]=useState(''),[metric,setMetric]=useState(''),[metricField,setMetricField]=useState(''),[recipientIds,setRecipientIds]=useState(''),[zone,setZone]=useState('Asia/Shanghai'),[localTime,setLocalTime]=useState('08:00'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[target,setTarget]=useState('');
 const live=useRef(true),urls=useRef<Set<string>>(new Set());useEffect(()=>{live.current=true;return()=>{live.current=false;for(const url of urls.current)URL.revokeObjectURL(url);};},[]);
 const refresh=async()=>{try{const r=await Promise.all(['/api/r1/reports/jobs','/api/r1/reports/subscriptions'].map(async url=>{const response=await fetch(url,{cache:'no-store'}),body=await response.json() as any;if(!response.ok)throw Error(body.error);return body;}));if(live.current){setJobs(r[0].jobs);setSubs(r[1].subscriptions);}}catch(e){setJobs([]);setSubs([]);setMessage((e as Error).message);}};
 useEffect(()=>{refresh();},[]);useEffect(()=>{setDraftId('');setDraftRevision(0);setFilterField('');setGroupField('');setMetricField('');},[dataset]);
 const send=async(path:string,payload:any,file=false)=>{if(busy||unknown)return;setBusy(true);setMessage('');let commandId:string|undefined;try{const response=await fetch('/api/r1/reports/catalog',{cache:'no-store'}),stamp=await response.json() as any;if(!response.ok)throw Error(stamp.error);const command=clientIntent(stamp,'report',payload);commandId=command.commandId;const {action,...body}=command,r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});if(r.status>=500){setUnknown(commandId);throw Error('结果待核对，请查询原命令。');}if(file&&r.ok&&r.headers.get('Content-Type')?.includes('text/csv')){const blob=await r.blob(),url=URL.createObjectURL(blob);urls.current.add(url);const a=document.createElement('a');a.href=url;a.download='report.csv';a.click();URL.revokeObjectURL(url);urls.current.delete(url);setMessage('报表已生成。');}else{const result=await r.json() as any;if(!r.ok)throw Error(result.error??'请求未提交');if(payload.operation==='save'&&path.endsWith('/definitions')){setDraftId(payload.id);setDraftRevision(payload.expectedRevision+1);}else if(path.endsWith('/definitions'))setDraftRevision(payload.expectedRevision+1);setMessage(result.queued?'超出同步导出预算，完整任务已保存。':path.endsWith('/subscriptions')?'订阅已保存，后台调度待启用。':'操作已保存。');}await refresh();onChanged();}catch(e){if(commandId&&(e as Error).name==='TypeError')setUnknown(commandId);setMessage((e as Error).message);}finally{setBusy(false);}};
 const query=()=>({dataset,...(data?.snapshotId?{snapshot:data.snapshotId}:{generation:data?.generation}),...(definitionId?{definitionId,definitionVersion:String(data?.reportDefinitionVersion??1)}:{columns:JSON.stringify(data?.columns?.map((f:any)=>f.fieldId)??selected)})});
 const saveDefinition=()=>{const columns=selected.length?selected:data?.columns?.map((f:any)=>f.fieldId)??[];if(!columns.length||!org||!title)return setMessage('请选择字段、保护组织并填写报表名称。');let value:any=filterValue;const f=fields.find(f=>f.fieldId===filterField);if(f?.type==='integer'||f?.type==='money_cents')value=Number(filterValue);if(f?.type==='boolean'){if(!['true','false'].includes(filterValue))return setMessage('布尔过滤值请输入 true 或 false。');value=filterValue==='true';}const definition={datasetId:dataset,schemaVersion:'r1-report-v1',columns,groupBy:groupField?[groupField]:[],metrics:metric?[{id:'指标',expression:{op:metric,...(metricField?{field:metricField}:{})}}]:[],...(filterField?{filter:{op:'eq',field:filterField,value}}:{})};send('/api/r1/reports/definitions',{operation:'save',id:draftId||crypto.randomUUID(),orgId:org,title,expectedRevision:draftRevision,definition});};
 const select=(value:string,set:(v:string)=>void,label:string)=><label>{label}<select className="block w-full rounded border p-2" value={value} onChange={e=>set(e.target.value)}><option value="">不使用</option>{fields.map(f=><option value={f.fieldId} key={f.fieldId}>{f.label}</option>)}</select></label>;
 return <section className="space-y-4 rounded border p-4"><h2 className="text-lg font-semibold">保存、导出与订阅</h2>{message&&<p role="status">{message}</p>}{unknown&&<div className="rounded border p-3">结果尚未确认：{unknown} <Button onClick={async()=>{try{const result=await queryClientCommand(unknown);if(result.state==='committed'){setUnknown(null);setMessage('原命令已提交，可刷新任务列表查看。');refresh();}else setMessage('回执尚未确认，请保留原编号。');}catch(e){setMessage((e as Error).message);}}}>查询原命令</Button></div>}
 <div className="flex gap-3"><Button disabled={busy||!!unknown||!data?.generation} onClick={()=>send('/api/r1/reports/export',{operation:'create',id:crypto.randomUUID(),query:query()},true)}>导出当前查询</Button><Button variant="outline" onClick={refresh}>刷新任务与订阅</Button></div>
 <details className="rounded border p-3"><summary>报表设计器</summary><p className="my-2 text-sm">使用上方所选列创建草稿，再发布固定版本；无权字段或不支持的计算会被拒绝。</p><div className="grid gap-3 md:grid-cols-3"><label>报表名称<Input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>保护组织<select className="block w-full rounded border p-2" value={org} onChange={e=>setOrg(e.target.value)}><option value="">请选择</option>{[...new Set([...(catalog?.definitionScopes?.[dataset]??[]),...(catalog?.subscriptionScopes??[])])].map((o:any)=><option key={o}>{o}</option>)}</select></label>{select(filterField,setFilterField,'等于过滤字段')}<label>过滤值<Input value={filterValue} onChange={e=>setFilterValue(e.target.value)}/></label>{select(groupField,setGroupField,'分组字段')}<label>指标<select className="block w-full rounded border p-2" value={metric} onChange={e=>setMetric(e.target.value)}><option value="">无指标</option><option value="count">计数</option><option value="countDistinct">去重计数</option><option value="sum">求和</option><option value="min">最小值</option><option value="max">最大值</option><option value="avg">平均值</option></select></label>{select(metricField,setMetricField,'指标字段（整行计数可留空）')}</div><div className="mt-3 flex gap-3"><Button disabled={busy||!!unknown} onClick={saveDefinition}>保存草稿</Button><Button disabled={busy||!!unknown||!draftId} onClick={()=>send('/api/r1/reports/definitions',{operation:'publish',id:draftId,expectedRevision:draftRevision})}>发布固定版本</Button><Button variant="outline" disabled={busy||!!unknown||!draftId} onClick={()=>send('/api/r1/reports/definitions',{operation:'retire',id:draftId,expectedRevision:draftRevision})}>停用</Button></div>{draftId&&<p className="mt-2">报表编号：{draftId}；编辑版本 {draftRevision}。可复制到上方“已发布报表编号”查询。</p>}</details>
 <details className="rounded border p-3"><summary>新建每日订阅</summary><p className="my-2 text-sm">仅发送需登录的报表链接。每个收件人按自己的当前权限查看；后台调度尚待启用。</p><div className="grid gap-3 md:grid-cols-3"><label>订阅名称<Input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>已有成员编号（逗号分隔）<Input value={recipientIds} onChange={e=>setRecipientIds(e.target.value)}/></label><label>保护组织<select className="block w-full rounded border p-2" value={org} onChange={e=>setOrg(e.target.value)}><option value="">请选择</option>{catalog?.subscriptionScopes?.map((o:string)=><option key={o}>{o}</option>)}</select></label><label>时区<Input value={zone} onChange={e=>setZone(e.target.value)}/></label><label>当地发送时间<Input type="time" value={localTime} onChange={e=>setLocalTime(e.target.value)}/></label><label>开始日期（UTC）<Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束日期（UTC）<Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><p className="mt-2 text-sm">夏令时缺失时刻跳过，重复时刻只取第一次。本表起止日期按 UTC 日界保存，请核对范围。</p><Button className="mt-3" disabled={busy||!!unknown||!start||!end||!org||!data?.generation||!!definitionId} onClick={()=>{const q:any=query();delete q.generation;send('/api/r1/reports/subscriptions',{operation:'save',id:crypto.randomUUID(),expectedRevision:0,orgId:org,title,query:q,recipientIds:recipientIds.split(',').map(x=>x.trim()).filter(Boolean),schedule:{timezone:zone,frequency:'daily',weekDays:[],localSendTime:localTime,gapPolicy:'skip',repeatPolicy:'earlier',startAt:start+'T00:00:00Z',endAt:end+'T23:59:59Z'},channel:'authenticated_link'});}}>保存订阅</Button></details>
 {jobs.length>0&&<div><h3>最近导出任务</h3>{jobs.map(j=><div className="my-2 flex flex-wrap items-center gap-3 rounded border p-2" key={j.id}><span>{j.id} · {j.status==='ready'?'可下载':j.runtimeState==='blocked_runtime'?'等待后台执行':j.status}</span>{j.status==='ready'&&<a className="underline" href={'/api/r1/reports/jobs/'+encodeURIComponent(j.id)+'/download'}>下载</a>}{j.status==='failed'&&<Button variant="outline" disabled={busy||!!unknown} onClick={()=>send('/api/r1/reports/jobs',{operation:'retry',id:j.id,expectedRevision:j.revision})}>重试已确认失败任务</Button>}{!['cancelled','expired'].includes(j.status)&&<Button variant="outline" disabled={busy||!!unknown} onClick={()=>send('/api/r1/reports/jobs',{operation:'cancel',id:j.id,expectedRevision:j.revision})}>取消</Button>}</div>)}</div>}
 {subs.length>0&&<div><h3>管理订阅</h3><label>转交给已有成员编号<Input value={target} onChange={e=>setTarget(e.target.value)}/></label>{subs.map(s=><div className="my-2 flex flex-wrap items-center gap-3 rounded border p-2" key={s.id}><span>{s.title} · {s.status} · {s.timezone} {s.localSendTime}</span><Button variant="outline" disabled={busy||!!unknown} onClick={()=>send('/api/r1/reports/subscriptions',{operation:s.status==='active'?'block':'activate',id:s.id,expectedRevision:s.revision})}>{s.status==='active'?'屏蔽':'启用'}</Button><Button variant="outline" disabled={busy||!!unknown||!target} onClick={()=>send('/api/r1/reports/subscriptions',{operation:'proposeTransfer',id:s.id,expectedRevision:s.revision,targetOwner:target})}>提出转交</Button>{s.proposedOwner&&<Button disabled={busy||!!unknown} onClick={()=>send('/api/r1/reports/subscriptions',{operation:'acceptTransfer',id:s.id,expectedRevision:s.revision})}>接受转交给 {s.proposedOwner}</Button>}</div>)}</div>}
 </section>;
}
