'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import ReportActions from './r1-actions';
import {reportLabels} from '@/lib/hris/r1-report-labels';
const reasons:Record<string,string>={PROJECTION_REQUIRED:'当前报表数据尚未准备就绪。',PRODUCER_NOT_CONFIGURED:'来源业务尚未配置。',GENERATION_NOT_FOUND:'所选数据版本尚不可用。',SNAPSHOT_NOT_FOUND:'未找到可核验的已保存快照。'};
export default function R1Reports(){
 const [catalog,setCatalog]=useState<any>(null),[dataset,setDataset]=useState('workforce'),[timeMode,setTimeMode]=useState('current'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[snapshot,setSnapshot]=useState(''),[definitionId,setDefinitionId]=useState(''),[columns,setColumns]=useState<string[]>([]),[sortField,setSortField]=useState(''),[direction,setDirection]=useState('asc'),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[applied,setApplied]=useState<URLSearchParams|null>(null);
 const generation=useRef(0),active=useRef<AbortController|null>(null),current=catalog?.datasets?.find((d:any)=>d.datasetId===dataset);
 const clear=()=>{generation.current++;active.current?.abort();setData(null);setBusy(false);};
 useEffect(()=>{const control=new AbortController();fetch('/api/r1/reports/catalog',{cache:'no-store',signal:control.signal}).then(async r=>{const b=await r.json() as any;if(!r.ok)throw Error(b.error??'报表目录暂不可用');setCatalog(b);}).catch(e=>{if(e.name!=='AbortError'){setCatalog(null);setError(e.message);}});return()=>{control.abort();active.current?.abort();};},[]);
 useEffect(()=>{clear();setApplied(null);setColumns([]);setSortField('');setSnapshot('');setFrom('');setTo('');setTimeMode(['attendance','instructorSchedule','contractOperations'].includes(dataset)?'event_range':'current');},[dataset]);
 const read=async(cursor?:string)=>{if(busy)return;setError('');const old=data;clear();setBusy(true);const seq=generation.current,controller=new AbortController();active.current=controller;try{let p:URLSearchParams;if(cursor&&applied)p=new URLSearchParams(applied);else{p=new URLSearchParams({dataset,mode:timeMode});if(timeMode==='event_range'){if(from)p.set('from',from);if(to)p.set('to',to);}if(timeMode==='snapshot')p.set('snapshot',snapshot);if(!definitionId){if(columns.length)p.set('columns',JSON.stringify(columns));if(sortField)p.set('sort',JSON.stringify([{field:sortField,direction}]));}}if(cursor){p.set('cursor',cursor);if(old?.generation)p.set('generation',old.generation);}const url=definitionId?'/api/r1/reports/definitions/'+encodeURIComponent(definitionId)+'/run':'/api/r1/reports';const r=await fetch(url+'?'+p,{cache:'no-store',signal:controller.signal}),b=await r.json() as any;if(seq!==generation.current)return;if(!r.ok)throw Error(b.error??'报表暂不可用');if(cursor&&(b.generation!==old?.generation||b.securityStamp?.authorizationRevision!==old?.securityStamp?.authorizationRevision||b.revision!==old?.revision))throw Error('权限或数据版本变化，请从第一页重新查询。');setData(cursor?{...b,rows:[...(old?.rows??[]),...(b.rows??[])]}:b);p.delete('cursor');setApplied(p);}catch(e){if(seq===generation.current){setData(null);if((e as Error).name!=='AbortError')setError((e as Error).message);}}finally{if(seq===generation.current)setBusy(false);}};
 return <main className="mx-auto max-w-7xl space-y-5 p-6"><Link href="/">返回导航台</Link><h1 className="text-2xl font-semibold">人事报表</h1><p>按当前授权查看明细与汇总。已保存快照保留原数值，每次读取仍重新核对访问权限。</p>{error&&<p role="alert" className="rounded border border-red-300 p-3 text-red-700">{error}</p>}
 <section className="grid gap-3 rounded border p-4 md:grid-cols-3"><label>数据集<select className="mt-1 block w-full rounded border p-2" value={dataset} onChange={e=>setDataset(e.target.value)}>{Object.entries(reportLabels).map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></label><label>时间方式<select className="mt-1 block w-full rounded border p-2" value={timeMode} onChange={e=>{clear();setTimeMode(e.target.value);}}><option value={current?.timeMode??'current'}>{current?.timeMode==='event_range'?'业务日期范围':'当前数据'}</option><option value="snapshot">已保存快照</option></select></label><label>已发布报表编号（可选）<Input value={definitionId} onChange={e=>{clear();setDefinitionId(e.target.value);}} placeholder="留空查询数据集"/></label>{timeMode==='event_range'&&<><label>开始业务日<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>结束业务日<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}{timeMode==='snapshot'&&<label>已保存快照编号<Input value={snapshot} onChange={e=>setSnapshot(e.target.value)} placeholder="请输入已有快照编号"/></label>}<div className="flex items-end"><Button disabled={busy||!catalog||timeMode==='snapshot'&&!snapshot} onClick={()=>read()}>{busy?'正在读取…':'查询'}</Button></div></section>
 {!definitionId&&current&&<details className="rounded border p-4"><summary>选择列与排序</summary><div className="my-3 grid grid-cols-2 gap-2 md:grid-cols-4">{current.fields.map((f:any)=><label key={f.fieldId}><input type="checkbox" checked={columns.includes(f.fieldId)} onChange={e=>{clear();setColumns(old=>e.target.checked?[...old,f.fieldId]:old.filter(id=>id!==f.fieldId));}}/> {f.label}</label>)}</div><p className="text-sm">未选列时，仅返回当前开放字段；无权字段不能用于排序。</p><select aria-label="排序字段" className="mr-3 mt-2 rounded border p-2" value={sortField} onChange={e=>{clear();setSortField(e.target.value);}}><option value="">默认顺序</option>{current.fields.map((f:any)=><option key={f.fieldId} value={f.fieldId}>{f.label}</option>)}</select><select aria-label="排序方向" className="rounded border p-2" value={direction} onChange={e=>{clear();setDirection(e.target.value);}}><option value="asc">升序</option><option value="desc">降序</option></select></details>}
 {data&&<section className="space-y-3 rounded border p-4"><h2 className="text-lg font-semibold">{reportLabels[dataset]}</h2>{data.reasonCode&&<p>{reasons[data.reasonCode]??'当前结果暂不可用，请核对来源或权限。'}</p>}{data.generatedAt&&<p className="text-sm text-slate-500">生成时间：{new Date(data.generatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}；{timeMode==='snapshot'?'已保存快照':'固定数据版本'}，当前权限下可见。</p>}{data.rows&&<><p>已加载 {data.rows.length} 条；总数{data.totalState==='known'?data.total:'待核'}。{current?.grain}</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{data.columns?.map((f:any)=><th className="whitespace-nowrap border-b p-2 text-left" key={f.fieldId}>{f.label}</th>)}</tr></thead><tbody>{data.rows.map((row:any)=><tr key={row.rowKey}>{data.columns?.map((f:any)=>{const cell=row.cells[f.fieldId];return <td className="border-b p-2" key={f.fieldId}>{!cell?'无权查看':cell.state==='value'?String(cell.value):cell.state==='not_configured'?'未配置':cell.state==='unavailable'?'暂不可用':'待核对'}</td>;})}</tr>)}</tbody></table></div></>}{data.groups?.map((group:any,i:number)=><div key={i} className="rounded border p-3">{Object.entries(group.cells).map(([id,cell]:[string,any])=><span className="mr-4" key={id}>{current?.fields?.find((f:any)=>f.fieldId===id)?.label??id}：{cell.value??'待核对'}</span>)}<dl className="mt-2 flex flex-wrap gap-4">{Object.entries(group.metrics).map(([id,cell]:[string,any])=><div key={id}><dt>{id}</dt><dd>{cell.state==='value'?String(cell.value):cell.reasonCode==='zero_denominator'?'无适用分母':'待核对'}</dd></div>)}</dl></div>)}{data.nextCursor&&<Button variant="outline" disabled={busy} onClick={()=>read(data.nextCursor)}>加载下一页</Button>}</section>}
 <ReportActions catalog={catalog} dataset={dataset} fields={current?.fields??[]} selected={columns} data={data} definitionId={definitionId} onChanged={()=>clear()}/>
 </main>;
}
