import {requireAttachmentIntegrity,byteDigest} from '@/lib/hris/r1-migration-attachments';
import {attachmentIntent,reserveUpload,replayAttachment,commitAttachment} from '@/lib/hris/r1-attachment-commands';
import {authorizeTuple} from '@/lib/hris/r1-authorization';
import {digest} from '@/lib/hris/r1-command';
import {readConsistent} from '@/lib/hris/context';
import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {developmentContext,commitExtension,type DevelopmentContext} from '@/lib/hris/development-repository';
import {canReadRecord} from '@/lib/hris/development';
import {permittedEmployeeIds} from '@/lib/hris/authorization';
import {json,failure,HttpError,readBody} from '@/lib/hris/http';
type FileRow={visibility:'hr'|'employee';id:string;employeeId:string|null;recordId:string|null;objectKey:string;name:string;mime:string;size:number;createdAt:string;createdBy:string};
const select='SELECT id,employee_id AS employeeId,record_id AS recordId,object_key AS objectKey,visibility,name,mime,size,created_at AS createdAt,created_by AS createdBy FROM hris_attachments WHERE tenant_id=? AND deleted_at IS NULL';
function bucket(){const b=(env as unknown as {BUCKET?:R2Bucket}).BUCKET;if(!b)throw new HttpError(503,'附件存储暂不可用');return b;}
async function authorize(ctx:DevelopmentContext,employeeId:string|null,recordId:string|null,write=false){
 if(ctx.member.securityStamp?.featuresEnabled){const orgId=employeeId?ctx.state.employees.find(e=>e.id===employeeId)?.orgId:ctx.records.find(r=>r.id===recordId)?.payload.orgId;if(!orgId)throw new HttpError(404,'附件归属不存在或不可见','NOT_FOUND_OR_NOT_VISIBLE');await authorizeTuple(ctx.db,ctx.member,{objectType:'BASE',action:write?'attachment.write':'attachment.read',orgId,personId:employeeId??'',field:'record',historyMode:'current'});}
 if(!!employeeId===!!recordId)throw new HttpError(400,'须指定一个附件归属');
 if(employeeId){if(!permittedEmployeeIds(ctx.state,ctx.member).has(employeeId)||(write&&!['admin','hr'].includes(ctx.member.role)))throw new HttpError(403,'没有此员工附件权限');}
 else {const r=ctx.records.find(r=>r.id===recordId&&r.kind==='course');if(!r||!canReadRecord(r,ctx.state,ctx.member)||(write&&(!['admin','hr'].includes(ctx.member.role)||r.status!=='draft')))throw new HttpError(403,'没有课程附件权限；已发布版本不可更改');}
}
function visibleFile(ctx:DevelopmentContext,f:FileRow){return !!f.recordId||['admin','hr'].includes(ctx.member.role)||(f.visibility==='employee'&&f.employeeId===ctx.member.employeeId);}
export async function GET(request:Request){try{
 const ctx=await developmentContext(['course']),url=new URL(request.url),id=url.searchParams.get('id');
 if(id){const [metadata]=await readConsistent(ctx,[ctx.db.prepare(select+' AND id=?').bind(ctx.member.tenantId,id)]);const file=(metadata.results as FileRow[])[0];if(!file)throw new HttpError(404,'附件不存在');await authorize(ctx,file.employeeId,file.recordId);if(!visibleFile(ctx,file))throw new HttpError(403,'附件未向当前成员开放');const integrity=await requireAttachmentIntegrity(ctx.db,ctx.member.tenantId,file.id);const object=await bucket().get(file.objectKey);if(!object)throw new HttpError(404,'附件文件不存在');const verifiedBytes=integrity?new Uint8Array(await object.arrayBuffer()):null;if(verifiedBytes&&(verifiedBytes.byteLength!==file.size||await byteDigest(verifiedBytes)!==integrity!.digest))throw new HttpError(409,'附件内容与核验摘要不符','ATTACHMENT_HASH_MISMATCH');await readConsistent(ctx,[]);await authorize(ctx,file.employeeId,file.recordId);return new Response(verifiedBytes??object.body,{headers:{'Content-Type':file.mime,'Content-Length':String(file.size),'Content-Disposition':`attachment; filename="download"; filename*=UTF-8''${encodeURIComponent(file.name)}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}});}
 const employeeId=url.searchParams.get('employeeId'),recordId=url.searchParams.get('recordId');await authorize(ctx,employeeId,recordId);const audience=employeeId&&!['admin','hr'].includes(ctx.member.role)?" AND visibility='employee' AND employee_id=?":'';const [rows]=await readConsistent(ctx,[ctx.db.prepare(select+` AND ${employeeId?'employee_id':'record_id'}=?`+audience+' ORDER BY created_at DESC LIMIT 201').bind(ctx.member.tenantId,employeeId??recordId,...(audience?[ctx.member.employeeId??'']:[]))]);return json({items:(rows.results as FileRow[]).slice(0,200).map(({objectKey,...r})=>r),hasMore:rows.results.length>200,revision:ctx.row.revision});
 }catch(e){return failure(e);}}
export async function POST(request:Request){try{
 if(request.headers.get('origin')!==new URL(request.url).origin)throw new HttpError(403,'请求来源无效');
 const ctx=await developmentContext(['course']),url=new URL(request.url),employeeId=url.searchParams.get('employeeId'),recordId=url.searchParams.get('recordId');await authorize(ctx,employeeId,recordId,true);
 const revision=z.coerce.number().int().nonnegative().parse(url.searchParams.get('revision'));
 attachmentIntent(request,ctx,revision,'BASE.attachment.upload',{});
 const visibility=z.enum(['hr','employee']).parse(url.searchParams.get('visibility')??'hr');
 const name=z.string().trim().min(1).max(160).parse(url.searchParams.get('name'));if(/[\x00-\x1f\x7f/\\]/.test(name))throw new HttpError(400,'文件名无效');
 const mime=request.headers.get('content-type')?.split(';')[0]??'';const allowed:Record<string,string[]>={'application/pdf':['pdf'],'image/png':['png'],'image/jpeg':['jpg','jpeg'],'text/plain':['txt'],'text/csv':['csv'],'application/vnd.openxmlformats-officedocument.wordprocessingml.document':['docx'],'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['xlsx']};if(!allowed[mime]?.includes(name.split('.').pop()!.toLowerCase()))throw new HttpError(415,'支持 PDF、图片、文本及 DOCX/XLSX 文件，扩展名须与类型一致');
 const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'文件为空');const chunks:Uint8Array[]=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.byteLength;if(size>10*1024*1024){await reader.cancel();throw new HttpError(413,'文件不能超过 10 MB');}chunks.push(r.value);}if(!size)throw new HttpError(400,'文件为空');const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}
 const signature=Array.from(bytes.slice(0,8));if((mime==='application/pdf'&&new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')||(mime==='image/png'&&signature.join(',')!=='137,80,78,71,13,10,26,10')||(mime==='image/jpeg'&&!(signature[0]===255&&signature[1]===216&&signature[2]===255))||(mime.includes('openxmlformats')&&!(signature[0]===80&&signature[1]===75&&signature[2]===3&&signature[3]===4)))throw new HttpError(415,'文件内容与声明类型不符');
 const byteHash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join(''),command=attachmentIntent(request,ctx,revision,'BASE.attachment.upload',{employeeId,recordId,visibility,name,mime,size,byteHash}),replayed=await replayAttachment(ctx,command);if(replayed)return json({...replayed.result,revision:replayed.workspaceRevision,commandId:replayed.commandId,replayed:true});
 if(revision!==ctx.row.revision)throw new HttpError(409,'数据已变化，请刷新','REVISION_CONFLICT');
 const id=command?.commandId??crypto.randomUUID(),key=`${ctx.member.tenantId}/${id}`,at=new Date().toISOString();await reserveUpload(ctx,id,key,await digest({employeeId,recordId,visibility,name,mime,size,byteHash}),employeeId?ctx.state.employees.find(e=>e.id===employeeId)!.orgId:ctx.records.find(r=>r.id===recordId)?.payload.orgId??'');await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});
 const plan=(token:string)=>[ctx.db.prepare('INSERT INTO hris_attachments(tenant_id,id,employee_id,record_id,object_key,visibility,name,mime,size,created_by,created_at) SELECT owner,?,?,?,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(id,employeeId,recordId,key,visibility,name,mime,size,ctx.member.userId,at,ctx.member.tenantId,token)];if(command)await commitAttachment(ctx,command,plan,{id});else await commitExtension(ctx,revision,'上传附件',name,plan);return json({id,revision:revision+1,...(command?{commandId:command.commandId}:{})});
 }catch(e){/* A lost D1 response may have committed the reference. Preserve immutable bytes; reconcile the reference before any physical cleanup. */return failure(e);}}
export async function DELETE(request:Request){try{
 const body=z.object({id:z.string().min(1),revision:z.number().int().nonnegative()}).parse(await readBody(request)),ctx=await developmentContext(['course']);const preliminary=attachmentIntent(request,ctx,body.revision,'BASE.attachment.delete',{id:body.id}),replayed=await replayAttachment(ctx,preliminary);if(replayed)return json({...replayed.result,commandId:replayed.commandId,replayed:true});const file=await ctx.db.prepare(select+' AND id=?').bind(ctx.member.tenantId,body.id).first<FileRow>();if(!file)throw new HttpError(404,'附件不存在');await authorize(ctx,file.employeeId,file.recordId,true);
 const command=attachmentIntent(request,ctx,body.revision,'BASE.attachment.delete',{id:file.id}),plan=(token:string)=>[ctx.db.prepare('UPDATE hris_attachments SET deleted_at=? WHERE tenant_id=? AND id=? AND EXISTS (SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(new Date().toISOString(),ctx.member.tenantId,file.id,ctx.member.tenantId,token),ctx.db.prepare("INSERT INTO r1_object_cleanup(tenant_id,id,object_key,reason) SELECT owner,?,?,'tombstone' FROM hris_workspaces WHERE owner=? AND last_mutation=?").bind(file.id,file.objectKey,ctx.member.tenantId,token)];if(command)await commitAttachment(ctx,command,plan,{deleted:true,cleanupPending:true});else await commitExtension(ctx,body.revision,'删除附件',file.name,plan);
 // Keep a tombstone even if physical removal fails; authorization never returns it.
 return json({deleted:true,cleanupPending:true});
 }catch(e){return failure(e);}}
