'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;role:string;employeeId:string|null;userId:string};
type Field={key:string;label:string;type?:string};
const fields:Record<string,Field[]>={session:[{key:'trainingId',label:'培训项目',type:'training'},{key:'courseId',label:'对应课程',type:'course'},{key:'title',label:'场次名称'},{key:'startAt',label:'开始时间（北京时间）',type:'stamp'},{key:'endAt',label:'结束时间（北京时间）',type:'stamp'},{key:'location',label:'场地'},{key:'instructorCertificationId',label:'讲师认证（可选）',type:'certification'},{key:'instructor',label:'讲师（未引用认证时填写）'},{key:'mandatory',label:'必须核验出席才能完成课程',type:'boolean'}],declare:[{key:'evidence',label:'本人出席与参与依据',type:'long'}],recordAttendance:[{key:'employeeId',label:'已报名员工',type:'employee'},{key:'present',label:'登记为出席',type:'boolean'},{key:'evidence',label:'出勤登记依据',type:'long'}],verifyAttendance:[{key:'evidence',label:'独立核验意见',type:'long'}],cancelSession:[{key:'evidence',label:'取消原因',type:'long'}],closeSession:[{key:'evidence',label:'场次结项依据',type:'long'}]};
const statuses:Record<string,string>={active:'已安排',closed:'已结项',cancelled:'已取消',submitted:'待核验',returned:'待补充',verified:'已核验'};
export default function TrainingSessions(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[tab,setTab]=useState('trainingSession'),[form,setForm]=useState<Record<string,string>|null>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/training-sessions',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),manager=hr||data?.role==='manager',find=(id:string|null)=>data?.records.find(r=>r.id===id),record=find(selected),emp=(id:string|null)=>core?.employees.find(e=>e.id===id)?.name??'—',local=(v?:string)=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
 function open(action:string,r?:R,extra:Record<string,string>={}){setError('');setForm({action,id:r?.id??'',sessionId:r?.kind==='trainingSession'?r.id:r?.referenceId??'',trainingId:'none',courseId:'none',employeeId:'none',instructorCertificationId:'none',instructor:'',mandatory:'true',present:'true',...extra});}
 async function send(command:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/training-sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('培训场次记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;const c:Record<string,unknown>={...form};if(!c.id)delete c.id;if(c.instructorCertificationId==='none')delete c.instructorCertificationId;else if(form.action==='session')c.instructor=find(String(c.instructorCertificationId))?.payload.name??'';for(const f of fields[form.action]){if(f.type==='boolean')c[f.key]=form[f.key]==='true';if(f.type==='stamp')c[f.key]=form[f.key]+':00+08:00';}if(form.accepted)c.accepted=form.accepted==='true';send(c);}
 function options(f:Field){if(f.type==='certification')return (data?.records??[]).filter(r=>r.kind==='instructorCertification'&&r.status==='approved'&&r.referenceId===form?.courseId).map(r=>[r.id,`${r.payload.name} · ${r.payload.start} 至 ${r.payload.end}`]);if(f.type==='training')return (data?.records??[]).filter(r=>r.kind==='training'&&r.status==='active').map(r=>[r.id,r.payload.name??'']);if(f.type==='course'){const t=find(form?.trainingId??null);return (data?.records??[]).filter(r=>r.kind==='course'&&t?.payload.courseIds?.includes(r.id)).map(r=>[r.id,r.payload.title??'']);}const s=find(form?.sessionId??null);return (core?.employees??[]).filter(e=>data?.records.some(r=>r.kind==='enrollment'&&r.employeeId===e.id&&r.referenceId===s?.payload.sessionCourseId&&r.payload.trainingId===s?.referenceId&&r.status!=='cancelled')).map(e=>[e.id,e.name]);}
 function actions(r:R){const isSession=r.kind==='trainingSession',s=isSession?r:find(r.referenceId),selfEnrolled=isSession&&data?.records.some(x=>x.kind==='enrollment'&&x.employeeId===data?.employeeId&&x.payload.trainingId===r.referenceId&&x.referenceId===r.payload.sessionCourseId&&x.status!=='cancelled');return <div className="flex flex-wrap gap-2"><Button variant="ghost" size="sm" onClick={()=>setSelected(r.id)}>详情</Button>{isSession&&r.status==='active'&&<>{selfEnrolled&&<Button size="sm" onClick={()=>open('declare',r)}>提交出席依据</Button>}{hr&&<><Button size="sm" variant="outline" onClick={()=>open('recordAttendance',r)}>登记出勤</Button><Button size="sm" variant="outline" onClick={()=>open('closeSession',r)}>结项</Button><Button size="sm" variant="ghost" onClick={()=>open('cancelSession',r)}>取消</Button></>}</>}{!isSession&&s?.status==='active'&&r.status==='submitted'&&manager&&r.employeeId!==data?.employeeId&&r.payload.submittedBy!==data?.userId&&<><Button size="sm" onClick={()=>open('verifyAttendance',r,{accepted:'true'})}>核验通过</Button><Button size="sm" variant="outline" onClick={()=>open('verifyAttendance',r,{accepted:'false'})}>退回补充</Button></>}</div>;}
 const rows=(data?.records??[]).filter(r=>r.kind===tab&&(r.payload.title+' '+r.payload.location+' '+r.payload.instructor+' '+emp(r.employeeId)+' '+find(r.referenceId)?.payload.title).includes(search)).reverse();
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/reports?dataset=trainingRoster" className="text-link">班级学员名册</Link><Link href="/reports?dataset=trainingProgress" className="text-link">培训项目进度</Link><Link href="/" className="text-link">导航台</Link><Link href="/learning" className="text-link">培训项目与学习</Link><Link href="/instructors" className="text-link">讲师认证</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">TRAINING SESSIONS</div><h1>培训场次与出勤</h1><p className="text-sm text-slate-500 mt-2">时间使用北京时间。场次结束后提交出席依据，经独立核验后计入必修场次完成情况。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}<section className="panel"><div className="section-head gap-4"><Tabs value={tab} onValueChange={v=>{setTab(v);setPage(1);}}><TabsList><TabsTrigger value="trainingSession">培训场次</TabsTrigger><TabsTrigger value="trainingAttendance">出勤核验</TabsTrigger></TabsList></Tabs>{hr&&tab==='trainingSession'&&<Button onClick={()=>open('session')}>安排场次</Button>}</div><div className="filters"><Input aria-label="搜索培训场次" className="max-w-md" placeholder="搜索场次、讲师、场地或员工" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><Table><TableHeader><TableRow>{['场次 / 员工','时间 / 场地','状态 / 要求','操作'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*15,page*15).map(r=>{const s=r.kind==='trainingSession'?r:find(r.referenceId);return <TableRow key={r.id}><TableCell>{s?.payload.title}{r.employeeId&&<p>{emp(r.employeeId)}</p>}<p className="text-sm text-slate-500">{s?.payload.instructor} · {s?.payload.instructorCertificationId?'已引用认证':'未引用认证'}</p>{s?.status==='active'&&s.payload.instructorCertificationId&&find(s.payload.instructorCertificationId)?.status==='revoked'&&<p className="text-sm text-amber-700">原讲师认证已撤销，请复核排期</p>}</TableCell><TableCell>{local(s?.payload.startAt)}<br/>{local(s?.payload.endAt)}<p className="text-sm text-slate-500">{s?.payload.location}</p></TableCell><TableCell><Badge variant="outline">{statuses[r.status]}</Badge><p className="text-sm text-slate-500">{r.kind==='trainingSession'?r.payload.mandatory?'必修场次':'选修场次':r.payload.present?'登记出席':'登记未出席'}</p></TableCell><TableCell>{actions(r)}</TableCell></TableRow>;})}</TableBody></Table>{!rows.length&&<p className="empty">暂无可见场次或出勤记录</p>}<div className="flex justify-end items-center gap-3 mt-4"><span className="text-sm">{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>培训场次办理</DialogTitle><DialogDescription>场次须属于培训项目中的课程；出勤以提供的材料核验，不使用定位或人脸识别。</DialogDescription></DialogHeader>{error&&<p className="text-red-700" role="alert">{error}</p>}{form&&<form onSubmit={submit} className="edit-form">{fields[form.action].map(f=><label className="field" key={f.key}><span>{f.label}</span>{['training','course','employee','certification'].includes(f.type??'')?<Select value={form[f.key]||'none'} onValueChange={v=>setForm({...form,[f.key]:v,...(f.key==='trainingId'?{courseId:'none',instructorCertificationId:'none'}:f.key==='courseId'?{instructorCertificationId:'none'}:{})})}><SelectTrigger aria-label={f.label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{options(f).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>:f.type==='boolean'?<Checkbox checked={form[f.key]==='true'} onCheckedChange={v=>setForm({...form,[f.key]:v===true?'true':'false'})}/>:f.type==='long'?<textarea required minLength={5} maxLength={3000} rows={4} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<Input type={f.type==='stamp'?'datetime-local':'text'} required={f.key!=='instructor'||form.instructorCertificationId==='none'} disabled={f.key==='instructor'&&form.instructorCertificationId!=='none'} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{record?.payload.title??emp(record?.employeeId??null)}</DialogTitle><DialogDescription>{record?statuses[record.status]:''}</DialogDescription></DialogHeader>{record&&<div className="space-y-4">{Object.entries({依据:record.payload.evidence,核验意见:record.payload.verification,关闭原因:record.payload.closedReason,场地:record.payload.location,讲师:record.payload.instructor,认证编号:record.payload.instructorCertificationId,认证期间:record.payload.instructorCertifiedStart?`${record.payload.instructorCertifiedStart} 至 ${record.payload.instructorCertifiedEnd}`:undefined}).filter(([,v])=>v).map(([k,v])=><div key={k}><p className="text-sm text-slate-500">{k}</p><p className="whitespace-pre-wrap">{v}</p></div>)}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></div>}</DialogContent></Dialog>
 </main>;
}
