'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {AttendancePeriodSnapshot} from '@/lib/hris/attendance-periods';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;role:string};
type Form={id?:string;employeeId:string;start:string;end:string;evidence:string};
type Preview={rows:AttendancePeriodSnapshot['rows'];totals:AttendancePeriodSnapshot['totals'];blockers:string[];revision:number;signature:string};
const selectClass='w-full rounded border p-2 bg-white',status:Record<string,string>={frozen:'已冻结',open:'已重新开放',void:'已作废'},signature=(f:Form)=>JSON.stringify([f.employeeId,f.start,f.end]);
function Summary({rows,totals}:{rows:AttendancePeriodSnapshot['rows'];totals:AttendancePeriodSnapshot['totals']}){return <div className="space-y-3"><p>计划 {totals.plannedMinutes} 分钟 · 批准请假 {totals.approvedLeaveMinutes} 分钟 · 未覆盖 {totals.uncoveredMinutes??'待核验'} 分钟</p><div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['业务日期','班次','计划分钟','请假分钟','未覆盖分钟','核验状态'].map(l=><th key={l} className="text-left p-2">{l}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.shiftId} className="border-t">{[r.date,r.name,r.plannedMinutes,r.approvedLeaveMinutes,r.uncoveredMinutes??'待核验',r.status].map((v,n)=><td key={n} className="p-2">{v}</td>)}</tr>)}</tbody></table></div></div>;}
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<Form|null>(null),[preview,setPreview]=useState<Preview|null>(null),[action,setAction]=useState<{id:string;action:'reopen'|'void'}|null>(null),[reason,setReason]=useState(''),[detailId,setDetail]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all');
 async function load(){try{const [r,h]=await Promise.all([fetch('/api/attendance-periods',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),d=await r.json() as Data&{error?:string},c=await h.json() as {state:State;error?:string};if(!r.ok||!h.ok)throw Error(d.error??c.error??'加载失败');setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);const manage=['admin','hr'].includes(data?.role??''),detail=data?.records.find(r=>r.id===detailId);
 function open(r?:R){setError('');setPreview(null);setForm({id:r?.id,employeeId:r?.employeeId??'',start:r?.payload.start??'',end:r?.payload.end??'',evidence:''});}
 async function send(command:unknown,isPreview=false){if(!data||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/attendance-periods',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as Preview&{error?:string};if(!r.ok)throw Error(d.error??'请求失败');if(isPreview&&form)setPreview({...d,signature:signature(form)});else{setForm(null);setAction(null);setNotice('期间处理已保存，原始来源与历史记录已保留。');}}catch(e){setError((e as Error).message);setPreview(null);if(isPreview)await load();}finally{if(!isPreview)await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-7xl space-y-6"><Link href="/attendance" className="text-link">返回假勤管理</Link><div className="page-head"><div><h1>考勤期间汇总与冻结</h1><p className="text-sm text-slate-500 mt-2">按单人1至31个已结束业务日核验固定班次。冻结后更改须先重新开放，当前不发布员工月报或计算工资。</p></div>{manage&&<Button disabled={busy} onClick={()=>open()}>核验并冻结期间</Button>}</div>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel space-y-4"><label>状态<select className={selectClass} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部</option>{Object.entries(status).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{data?.records.filter(r=>filter==='all'||r.status===filter).slice().reverse().map(r=><article key={r.id} className="rounded border p-4 space-y-2"><h2>{r.payload.employeeSnapshot?.name} · {r.payload.start}—{r.payload.end}</h2><p>{status[r.status]} · 第{r.payload.version}次冻结 · 记录时组织：{r.payload.employeeSnapshot?.orgName}</p><p>计划 {r.payload.attendanceSnapshot?.totals.plannedMinutes} 分钟；批准请假 {r.payload.attendanceSnapshot?.totals.approvedLeaveMinutes} 分钟</p><div className="flex gap-2"><Button variant="ghost" onClick={()=>setDetail(r.id)}>明细与历史</Button>{manage&&r.status==='frozen'&&<Button variant="outline" disabled={busy} onClick={()=>{setReason('');setAction({id:r.id,action:'reopen'});}}>重新开放</Button>}{manage&&r.status==='open'&&<><Button disabled={busy} onClick={()=>open(r)}>重新核验并冻结</Button><Button variant="ghost" disabled={busy} onClick={()=>{setReason('');setAction({id:r.id,action:'void'});}}>作废错误期间</Button></>}</div></article>)}{data&&!data.records.length&&<p>尚无可见期间记录，原有假勤流程继续可用。</p>}</section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>期间核验与冻结</DialogTitle><DialogDescription>先预览来源结果；缺卡、待审批和未覆盖时段必须先处理。跨日班次按起始业务日完整归属。</DialogDescription></DialogHeader>{form&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void send(form.id?{action:'refreeze',id:form.id,evidence:form.evidence}:{action:'freeze',employeeId:form.employeeId,start:form.start,end:form.end,evidence:form.evidence});}}><fieldset disabled={busy} className="space-y-4">{error&&<p role="alert">{error}</p>}<label className="field"><span>员工</span><select required disabled={!!form.id} className={selectClass} value={form.employeeId} onChange={e=>{setPreview(null);setForm({...form,employeeId:e.target.value});}}><option value="">请选择员工</option>{core?.employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.code} · {e.status}</option>)}</select></label><div className="grid grid-cols-2 gap-3">{[['start','开始业务日'],['end','结束业务日']].map(([k,l])=><label className="field" key={k}><span>{l}</span><Input required disabled={!!form.id} type="date" value={form[k as 'start'|'end']} onChange={e=>{setPreview(null);setForm({...form,[k]:e.target.value});}}/></label>)}</div><Button type="button" variant="outline" disabled={!form.employeeId||!form.start||!form.end} onClick={()=>send({action:'preview',employeeId:form.employeeId,start:form.start,end:form.end},true)}>预览核验结果</Button>{preview&&preview.signature===signature(form)&&<section className="rounded border p-3 space-y-3">{preview.blockers.length>0?<ul className="text-amber-700">{preview.blockers.map(b=><li key={b}>{b}</li>)}</ul>:<p>当前来源满足本批冻结条件。</p>}<Summary rows={preview.rows} totals={preview.totals}/><p className="text-sm text-slate-500">预览后如来源或权限变化，保存会拒绝并要求重新核验。</p></section>}<label className="field"><span>核验依据</span><textarea required minLength={5} maxLength={1500} className={selectClass} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><div className="flex gap-3"><Button type="button" variant="outline" onClick={()=>setForm(null)}>取消</Button><Button disabled={!preview||preview.signature!==signature(form)||preview.blockers.length>0||preview.revision!==data?.revision}>冻结本期间</Button></div></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!action} onOpenChange={v=>!v&&!busy&&setAction(null)}><DialogContent><DialogHeader><DialogTitle>{action?.action==='reopen'?'重新开放期间':'作废错误期间'}</DialogTitle><DialogDescription>保留旧冻结快照和所有处理历史，需记录具体依据。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();if(action)void send({...action,reason});}}><label>处理原因<textarea className={selectClass} required minLength={5} maxLength={1500} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy}>保存处理</Button></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail('')}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>期间明细 · {detail?.payload.employeeSnapshot?.name}</DialogTitle><DialogDescription>{detail?.payload.start}—{detail?.payload.end}；显示最近一次冻结快照，重新开放不使旧快照随当前数据变化。</DialogDescription></DialogHeader>{detail?.payload.attendanceSnapshot&&<div className="space-y-4"><Summary rows={detail.payload.attendanceSnapshot.rows} totals={detail.payload.attendanceSnapshot.totals}/><p>冻结来源修订号 {detail.payload.attendanceSnapshot.sourceRevision}；来源记录 {detail.payload.attendanceSnapshot.sources.length} 条</p><p className="whitespace-pre-wrap">核验：{detail.payload.evidence}</p>{detail.payload.reopenReason&&<p>重新开放：{detail.payload.reopenReason}</p>}<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/></div>}</DialogContent></Dialog></main>;
}
