'use client';
import {businessDate} from '@/lib/hris/business-time';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
type Item={id:string;name:string;size:number;createdAt:string};
export default function Attachments({employeeId,recordId,canWrite=false}:{employeeId?:string;recordId?:string;canWrite?:boolean}){
 const [shared,setShared]=useState(false);
 const [items,setItems]=useState<Item[]>([]),[revision,setRevision]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const query=new URLSearchParams(employeeId?{employeeId}:{recordId:recordId??''}).toString();
 async function load(){try{const r=await fetch('/api/attachments?'+query,{cache:'no-store'}),d=await r.json() as {error?:string;items:Item[];revision:number;hasMore?:boolean};if(!r.ok)throw Error(d.error);setItems(d.items);setRevision(d.revision);if(d.hasMore)setNotice('仅显示最新 200 个附件');}catch(e){setError((e as Error).message);}}
 useEffect(()=>{setItems([]);setError('');load();},[query]);
 async function upload(file:File){setBusy(true);setError('');setNotice('');try{if(file.size>10*1024*1024)throw Error('文件不能超过 10 MB');const ext=file.name.split('.').pop()?.toLowerCase();const fallback:Record<string,string>={csv:'text/csv',txt:'text/plain',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};const r=await fetch('/api/attachments?'+query+'&'+new URLSearchParams({revision:String(revision),name:file.name,visibility:shared?'employee':'hr'}),{method:'POST',headers:{'Content-Type':file.type||fallback[ext??'']||'application/octet-stream'},body:file});const d=await r.json() as {error?:string;items:Item[];revision:number;hasMore?:boolean};if(!r.ok)throw Error(d.error);setNotice('附件已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 async function remove(id:string){setBusy(true);setError('');try{const r=await fetch('/api/attachments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,revision})});const d=await r.json() as {error?:string;items:Item[];revision:number;hasMore?:boolean};if(!r.ok)throw Error(d.error);setNotice('附件已移除');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <section className="my-6 space-y-3"><h3 className="font-semibold">附件资料</h3>{error&&<p className="text-red-700" role="alert">{error}</p>}{notice&&<p className="text-sm text-slate-500" role="status">{notice}</p>}{canWrite&&<div>{employeeId&&<label className="mb-3 flex items-center gap-2 text-sm"><Checkbox checked={shared} onCheckedChange={v=>setShared(v===true)}/>允许员工本人查看本次上传附件</label>}<label className="block text-sm">上传文件（单个不超过 10 MB）<Input className="mt-2" type="file" aria-label="上传附件" accept=".pdf,.png,.jpg,.jpeg,.txt,.csv,.docx,.xlsx" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.target.value='';}}/></label></div>}{!items.length&&<p className="text-sm text-slate-500">暂无附件</p>}{items.map(f=><div className="flex items-center justify-between gap-3 border-b py-2 text-sm" key={f.id}><a className="text-link break-all" href={'/api/attachments?id='+encodeURIComponent(f.id)}>{f.name}<span className="block text-xs text-slate-500">{Math.ceil(f.size/1024)} KB · {businessDate(f.createdAt)}</span></a>{canWrite&&<Button variant="ghost" size="sm" disabled={busy} onClick={()=>remove(f.id)}>删除</Button>}</div>)}</section>;
}
