'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {clientIntent,sendClientCommand,queryClientCommand,type ClientStamp} from '@/lib/hris/r1-client-command';
import type {CommandIntent} from '@/lib/hris/r1-command';
import {personnelKinds,personnelOperations,formFields,personnelPayload,type FormEntity} from '@/lib/hris/r1-form-model';
import {businessDate} from '@/lib/hris/business-time';
const labels:Record<string,string>={effectiveOn:'调动计划生效日',intent:'事项性质',previousApprovalId:'更正原单编号',reviewerOutId:'调出审批人账号编号',reviewerInId:'调入审批人账号编号',signedOn:'签署登记日期',endedOn:'终止日期',evidence:'人工核验依据',orgId:'组织',code:'编码',name:'名称',entryType:'入口模板类型',templateId:'模板',personId:'人员',identifierType:'核对标识类型',identifierValue:'核对标识',reason:'办理原因',evidenceRef:'核验依据编号',identityReviewId:'已确认身份记录',predecessorId:'前一雇佣段',startOn:'开始日期',employmentType:'雇佣类型',employmentId:'雇佣段',positionId:'职位',gradeId:'职级',type:'任职类型',homePrimaryId:'派出主职',validFrom:'生效日期',validTo:'结束日期（可空）',reviewerId:'独立审核人账号编号',lastWorkingOn:'最后工作日',legalEntityId:'法人',number:'合同编号',agreementCategory:'协议类型',contractType:'合同期限类型',start:'合同开始',end:'合同结束',renewalOf:'续签原合同',inheritPrevious:'省略时继承原值',status:'状态',kind:'类别',batchId:'导入批次',rowNo:'行号',attemptVersion:'修正尝试版本',mode:'导入模式',recordId:'更新的记录',id:'待修订目录',closePreviousVersion:'要关闭的原版本号',parentId:'上级目录',city:'城市',sequence:'职级序号',establishedOn:'职位设立日期',familyId:'职类',gradeMinId:'最低职级',gradeMaxId:'最高职级',responsibilities:'职责',newType:'新增方式',scopeOrgId:'法人适用组织',endAssignmentId:'要结束的任职',replacesAssignmentId:'要变更的非主职任职'};
const enums:Record<string,string[]>={intent:['independent','correction'],entryType:['employee_create','prehire','onboard','subset'],identifierType:['code','document','phone','email'],employmentType:['employee','internship','retired_rehire'],type:['primary','part_time','secondment','expatriate'],agreementCategory:['labor','service','internship'],contractType:['fixed','open','project'],inheritPrevious:['true','false'],status:['active','inactive','archived'],mode:['create','update'],newType:['New','Backfill']};
const enumNames:Record<string,string>={independent:'独立新事项',correction:'更正原事项',employee_create:'新增人员',prehire:'待入职',onboard:'办理入职',subset:'子集记录',code:'工号',document:'证件',phone:'手机号',email:'邮箱',employee:'员工',internship:'实习',retired_rehire:'退休返聘',primary:'主职',part_time:'兼职',secondment:'借调',expatriate:'外派',labor:'劳动协议',service:'服务协议',fixed:'固定期限',open:'无固定期限',project:'项目期限',true:'是',false:'否',active:'启用',inactive:'停用',archived:'归档',create:'新增',update:'更新',New:'新增职位',Backfill:'补位',education:'教育',employment:'工作',family:'家庭',appraisal:'考核',training:'培训',reward:'奖励',certificate:'证书',skill:'技能',language:'语言',custom:'自定义'};
const sources:Record<string,string>={personId:'person',orgId:'org',scopeOrgId:'org',templateId:'template',identityReviewId:'identity_review',predecessorId:'employment',employmentId:'employment',positionId:'position',gradeId:'grade',homePrimaryId:'assignment',legalEntityId:'legal_entity',renewalOf:'contract',recordId:'subset',familyId:'job_family',gradeMinId:'grade',gradeMaxId:'grade',endAssignmentId:'assignment',replacesAssignmentId:'assignment'};
function Picker({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(s:string)=>void}){return <Select value={value||'_empty'} onValueChange={s=>onChange(s==='_empty'?'':s)}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="_empty">请选择／留空</SelectItem>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export default function PersonnelWorkspace({user,initialKind='person'}:{user:string;initialKind?:string}){
 const [kind,setKind]=useState(initialKind),[data,setData]=useState<(ClientStamp&{enabled:boolean;items:FormEntity[];nextCursor:string|null;userId:string})|null>(null),[lists,setLists]=useState<Record<string,FormEntity[]>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[operation,setOperation]=useState('person'),[open,setOpen]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[values,setValues]=useState<Record<string,unknown>>({}),[fields,setFields]=useState<any[]>([]),[history,setHistory]=useState<any[]|null>(null),[historyCursor,setHistoryCursor]=useState<any>(null),[optionCursors,setOptionCursors]=useState<Record<string,string|null>>({}),[historyLabel,setHistoryLabel]=useState(''),[notice,setNotice]=useState(''),[unknown,setUnknown]=useState<string|null>(null);
 const dirtyFields=useRef(new Set<string>());
 const pending=useRef<CommandIntent|null>(null),generation=useRef(0);
 const fetchPage=async(k:string,cursor?:string)=>{const r=await fetch('/api/r1/m01?'+new URLSearchParams({kind:k,...(cursor?{cursor}:{})}),{cache:'no-store'}),body=await r.json() as any;if(!r.ok){if([401,403,409].includes(r.status)){generation.current++;setData(null);setLists({});setValues({});setForm({});setHistory(null);dirtyFields.current.clear();}throw Error(body.error??'读取失败');}return body;};
 const load=async(cursor?:string)=>{const own=++generation.current;setError('');try{const page=await fetchPage(kind,cursor);if(own!==generation.current)return;setData((old:any)=>cursor&&old?{...page,items:[...old.items,...page.items]}:page);}catch(e){setError((e as Error).message);}};
 useEffect(()=>{setData(null);void load();return()=>{generation.current++;};},[kind]);
 const refreshOptions=async()=>{const own=generation.current;const entries=await Promise.all(Object.keys(personnelKinds).map(async k=>[k,await fetchPage(k)] as const));if(own===generation.current){setLists(Object.fromEntries(entries.map(([k,d])=>[k,d.items])));setOptionCursors(Object.fromEntries(entries.map(([k,d])=>[k,d.nextCursor])));}};
 const begin=async()=>{setError('');setForm({effectiveOn:businessDate(),intent:'independent',validFrom:businessDate(),startOn:businessDate(),start:businessDate(),entryType:'employee_create',status:'active',inheritPrevious:'true',mode:'create',rowNo:'1',attemptVersion:'1',batchId:crypto.randomUUID(),identifierType:'code',employmentType:'employee',type:'primary',agreementCategory:'labor',contractType:'fixed',kind:operation==='catalog'?'org':'custom'});setValues({});dirtyFields.current.clear();setFields([]);try{await refreshOptions();setOpen(true);}catch(e){setError((e as Error).message);}};
 const loadOption=async(key:string)=>{const source=['id','parentId'].includes(key)?form.kind:sources[key],cursor=optionCursors[source];if(!cursor)return;try{const page=await fetchPage(source,cursor);setLists(old=>({...old,[source]:[...(old[source]??[]),...page.items]}));setOptionCursors(old=>({...old,[source]:page.nextCursor}));}catch(e){setError((e as Error).message);}};
 const showHistory=async(row:{id:string;payload:Record<string,any>;code?:string|null},more=false)=>{const own=generation.current;setError('');try{const r=await fetch('/api/r1/m01/'+encodeURIComponent(row.id)+'/history'+(more?'?'+new URLSearchParams({after:String(historyCursor.nextAfter),revision:String(historyCursor.revision),authorizationRevision:String(historyCursor.authorizationRevision),recoveryEpoch:String(historyCursor.recoveryEpoch)}):''),{cache:'no-store'}),d=await r.json() as any;if(!r.ok)throw Error(d.error);if(own!==generation.current)return;setHistory((old:any)=>more?[...(old??[]),...d.items]:d.items);setHistoryCursor({...d,id:row.id});setHistoryLabel(row.payload.name??row.payload.number??row.code??row.id);}catch(e){setHistory(null);setError((e as Error).message);}};
 const editRow=async(row:FormEntity,op:string)=>{try{await refreshOptions();dirtyFields.current.clear();setOperation(op);setForm({...Object.fromEntries(Object.entries({...row.payload,...row.payload.attributes}).filter(([,v])=>v!==null&&typeof v!=='object').map(([k,v])=>[k,String(v)])),id:row.id,kind:row.kind,personId:row.personId??'',orgId:row.orgId??'',code:row.code??'',status:row.status,inheritPrevious:String(row.payload.inheritPrevious??true),signedOn:businessDate(),endedOn:businessDate(),closePreviousVersion:String(row.revision)});setValues(Object.fromEntries((row.payload.fieldSnapshots??[]).map((f:any)=>[f.rootId,f.value])));setFields(row.payload.fields??[]);setOpen(true);}catch(e){setError((e as Error).message);}};
 const execute=async(payload:any)=>{if(!data||busy||pending.current)return;setBusy(true);setError('');const intent=clientIntent(data,payload.operation,payload);pending.current=intent;
  try{const result=await sendClientCommand(intent);if(result.state==='unknown'){setUnknown(intent.commandId);setNotice(result.message);return;}pending.current=null;if(result.state==='rejected'){setError(result.message);if([401,403,409].includes(result.status)){setLists({});setValues({});setForm({});await load();}return;}
   const receipt=result.receipt as any;setNotice(receipt.result?.effectStatus==='failed'?'办理尝试已记录，尚未生效；请查看原单原因': '办理记录已保存');setOpen(false);await load();
  }finally{setBusy(false);}
 };
 const query=async()=>{if(!unknown)return;setBusy(true);try{const r=await queryClientCommand(unknown);if(r.state==='committed'){pending.current=null;setUnknown(null);setOpen(false);setNotice('已核实原办理记录提交，请查看实际业务状态');await load();}else setNotice('原办理结果仍未确认，可稍后再次查询');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const submit=(e:FormEvent)=>{e.preventDefault();try{void execute(personnelPayload(operation,form,lists,operation==='contract'?Object.fromEntries(Object.entries(values).filter(([key])=>dirtyFields.current.has(key))):values,fields));}catch(e){setError((e as Error).message);}};
 const selectedTemplate=lists.template?.find(t=>t.id===form.templateId),dynamicFields=operation==='contract'?(lists.contract_field??[]).filter(f=>f.status==='active').map(f=>({code:f.id,name:f.payload.name,type:'text',required:false})):selectedTemplate?.payload.fields??[];
 const optionsFor=(key:string)=>{if(key==='kind')return (operation==='catalog'?['org','position','job','job_family','grade','legal_entity']:['education','employment','family','appraisal','training','reward','certificate','project','skill','language','custom']).map(value=>({value,label:personnelKinds[value as keyof typeof personnelKinds]??enumNames[value]??value}));
  if(enums[key])return enums[key].map(value=>({value,label:enumNames[value]??value}));
  const source=key==='id'||key==='parentId'?form.kind:sources[key];return (lists[source]??[]).filter(e=>!form.personId||!e.personId||e.personId===form.personId).map(e=>({value:e.id,label:[e.code,e.payload.name??e.payload.number??e.payload.kind??personnelKinds[e.kind as keyof typeof personnelKinds],e.revision?'v'+e.revision:''].filter(Boolean).join(' · ')}));};
 return <main className="mx-auto max-w-7xl p-6 text-base"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><Link href="/" className="text-blue-700">人才管理</Link><h1 className="mt-2 text-2xl font-semibold">组织与人员</h1></div><span>{user}</span><Link href="/approvals">人事审批</Link><Link href="/settings">成员与授权</Link></header>
 <div className="mb-4 flex flex-wrap gap-3"><div className="w-48"><Picker label="记录类别" value={kind} onChange={setKind} options={Object.entries(personnelKinds).map(([value,label])=>({value,label}))}/></div><Button variant="outline" onClick={()=>load()} disabled={busy}>刷新</Button><div className="w-56"><Picker label="办理事项" value={operation} onChange={setOperation} options={Object.entries(personnelOperations).map(([value,label])=>({value,label}))}/></div><Button disabled={busy||!!unknown||!data?.enabled} onClick={begin}>发起办理</Button></div>
 {error&&<p role="alert" className="my-4 rounded border border-red-300 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="my-4">{notice}</p>}{unknown&&<div className="my-4 rounded border p-4"><p>结果尚未确认，暂不重复发起办理。</p><Button onClick={query} disabled={busy}>查询原办理结果</Button></div>}
 {data&&!data.enabled?<p>人员新功能尚未开放。</p>:<section className="rounded-xl border bg-white"><Table><TableHeader><TableRow><TableHead>名称／编号</TableHead><TableHead>状态</TableHead><TableHead>版本</TableHead><TableHead>业务状态</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{data?.items.map(row=><TableRow key={row.id}><TableCell>{row.payload.name??row.payload.number??row.code??row.id}</TableCell><TableCell>{({active:'有效',ended:'已结束',pending:'待审核',approved:'已批准',applied:'已生效',failed:'执行失败',draft:'草稿',confirmed:'已确认',published:'已发布',cancelled:'已取消',archived:'已归档'} as any)[row.status]??row.status}</TableCell><TableCell>{row.revision}</TableCell><TableCell>{row.payload.failure??row.payload.cleanupStatus??row.payload.effectStatus??'—'}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Button size='sm' variant='outline' onClick={()=>showHistory(row)}>版本历史</Button>{(['org','position','job','job_family','grade','legal_entity','contract_field','template'].includes(row.kind)||row.kind==='contract'&&row.status==='draft')&&<Button size='sm' variant='outline' disabled={busy||!!unknown} onClick={()=>editRow(row,row.kind==='contract_field'?'contractField':['contract','template'].includes(row.kind)?row.kind:'catalog')}>修订</Button>}{row.kind==='contract'&&['draft','signed'].includes(row.status)&&<Button size='sm' disabled={busy||!!unknown} onClick={()=>editRow(row,row.status==='draft'?'contractSign':'contractEnd')}>{row.status==='draft'?'登记签署':'终止合同'}</Button>}{(['assignment_request','exit_request'].includes(row.kind)&&row.status==='pending'&&row.payload.reviewerId===data.userId)&&<Button size="sm" disabled={busy||!!unknown} onClick={()=>execute({operation:row.kind==='assignment_request'?'assignmentApprove':'exitApprove',id:row.id})}>审核通过</Button>}{(['assignment_request','exit_request'].includes(row.kind)&&['approved','failed'].includes(row.status))&&<Button size="sm" disabled={busy||!!unknown} onClick={()=>execute({operation:row.kind==='assignment_request'?'assignmentExecute':'exitExecute',id:row.id})}>到期执行</Button>}{['assignment_request','exit_request'].includes(row.kind)&&['pending','approved','failed'].includes(row.status)&&<Button size='sm' variant='outline' disabled={busy||!!unknown} onClick={()=>editRow(row,row.kind==='assignment_request'?'assignmentCancel':'exitCancel')}>取消原单</Button>}{row.kind==='person'&&row.status==='ended'&&<Button size="sm" disabled={busy||!!unknown} onClick={()=>execute({operation:'exitCleanup',personId:row.id,orgId:row.orgId,limit:20})}>继续清理关联事项</Button>}</div></TableCell></TableRow>)}</TableBody></Table>{!data?.items.length&&<p className="p-8 text-center">暂无可见记录</p>}{data?.nextCursor&&<Button className="m-4" variant="outline" onClick={()=>load(data.nextCursor!)}>加载下一页</Button>}</section>}
 <Dialog open={history!==null} onOpenChange={v=>!v&&setHistory(null)}><DialogContent className='max-h-[90vh] overflow-y-auto'><DialogHeader><DialogTitle>{historyLabel} · 版本历史</DialogTitle><DialogDescription>仅显示当前权限可见的历史字段。按记录时刻保留旧版本。</DialogDescription></DialogHeader>{history?.map(h=><article key={h.version} className='rounded border p-3'><h3>版本 {h.version} · {h.recordedAt}</h3><p>{h.payload.status} · {h.historyQuality==='unknown'?'历史待核':'已知历史'}</p><dl>{Object.entries(h.payload.payload).filter(([k,v])=>typeof v==='string'&&['name','number','validFrom','validTo','startOn','lastWorkingOn','effectStatus','reason'].includes(k)).map(([k,v])=><div key={k} className='flex gap-3'><dt>{labels[k]??k}</dt><dd>{String(v)}</dd></div>)}</dl></article>)}{historyCursor?.nextAfter&&<Button onClick={()=>showHistory({id:historyCursor.id,payload:{name:historyLabel}},true)}>加载更早记录</Button>}</DialogContent></Dialog>
 <Dialog open={open} onOpenChange={v=>!busy&&!unknown&&setOpen(v)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{personnelOperations[operation as keyof typeof personnelOperations]}</DialogTitle><DialogDescription>按当前权限办理。任职和退出需独立审核，批准后由授权 HR 到期执行。</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2">{(formFields[operation]??[]).map(key=><label key={key} className="grid gap-2 text-sm"><span>{labels[key]??key}</span>{enums[key]||sources[key]||['kind','id','parentId'].includes(key)?<Picker label={labels[key]??key} value={form[key]??''} options={optionsFor(key)} onChange={v=>setForm({...form,[key]:v})}/>:<Input aria-label={labels[key]} type={/On$|From$|To$|^start$|^end$/.test(key)?'date':['rowNo','attemptVersion','sequence','closePreviousVersion'].includes(key)?'number':'text'} value={form[key]??''} maxLength={key==='responsibilities'?4000:200} onChange={e=>setForm({...form,[key]:e.target.value})}/>} {optionCursors[['id','parentId'].includes(key)?form.kind:sources[key]]&&<Button type='button' size='sm' variant='outline' onClick={()=>loadOption(key)}>加载更多选项</Button>}</label>)}</div>
 {['person','subsetImport','contract'].includes(operation)&&<fieldset className="grid gap-3 rounded border p-4"><legend>模板字段</legend>{dynamicFields.map((f:any)=><label key={f.code} className="grid gap-2 text-sm"><span>{f.name??f.code}{f.required?'（必填）':''}{f.unit?' · '+f.unit:''}</span><Input aria-label={f.name??f.code} required={f.required} type={f.type==='date'?'date':'text'} maxLength={1000} value={String(values[f.code]??'')} onChange={e=>{dirtyFields.current.add(f.code);setValues({...values,[f.code]:e.target.value||null});}}/></label>)}{!dynamicFields.length&&<p className="text-sm">未配置或未选择模板字段。</p>}</fieldset>}
 {operation==='template'&&<fieldset className="grid gap-3 rounded border p-4"><legend>字段定义</legend>{fields.map((f,i)=><div key={i} className="grid gap-2 rounded border p-3"><Input aria-label={'字段编码'+(i+1)} placeholder="字段编码" value={f.code} onChange={e=>setFields(fields.map((v,j)=>j===i?{...v,code:e.target.value}:v))}/><Picker label="字段类型" value={f.type} options={['text','number','date','enum','attachment'].map(value=>({value,label:({text:'文本',number:'数值',date:'日期',enum:'枚举',attachment:'附件'} as any)[value]}))} onChange={type=>setFields(fields.map((v,j)=>j===i?{...v,type,...(type==='number'?{unit:'',precision:0}:{}),...(type==='enum'?{options:[]}: {})}:v))}/>{f.type==='number'&&<><Input aria-label="单位" placeholder="单位" value={f.unit} onChange={e=>setFields(fields.map((v,j)=>j===i?{...v,unit:e.target.value}:v))}/><Input aria-label="小数位数" type="number" min={0} max={6} value={f.precision} onChange={e=>setFields(fields.map((v,j)=>j===i?{...v,precision:Number(e.target.value)}:v))}/></>}{f.type==='enum'&&<Input aria-label="枚举项" placeholder="选项，以逗号分隔" value={f.options?.join(',')??''} onChange={e=>setFields(fields.map((v,j)=>j===i?{...v,options:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}:v))}/>}<label className="flex gap-2"><Checkbox checked={f.required} onCheckedChange={required=>setFields(fields.map((v,j)=>j===i?{...v,required:!!required}:v))}/>必填</label><label className="flex gap-2"><Checkbox checked={f.uniqueKey} onCheckedChange={uniqueKey=>setFields(fields.map((v,j)=>j===i?{...v,uniqueKey:!!uniqueKey}:v))}/>唯一键</label><p className="text-sm">默认值：空；允许读取和更新，仍须具备对应字段授权。</p><Button type="button" variant="outline" onClick={()=>setFields(fields.filter((_,j)=>j!==i))}>移除此字段</Button></div>)}<Button type="button" variant="outline" disabled={fields.length>=20} onClick={()=>setFields([...fields,{code:'',type:'text',required:false,default:null,uniqueKey:false,readActions:['read'],writeActions:['update']}])}>添加字段</Button></fieldset>}
 <Button type="submit" disabled={busy||!!unknown}>{busy?'办理中…':'提交办理'}</Button></form></DialogContent></Dialog></main>;
}
