'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {PortalCache} from '@/lib/hris/r1-portal-cache';
import {portalEntries,entryLabels,type PortalEntry} from '@/lib/hris/r1-portal-contract';
import {queryClientCommand} from '@/lib/hris/r1-client-command';
const labels:Record<string,string>={name:'姓名',code:'工号',orgName:'组织',positionName:'职位',email:'邮箱',grade:'职级',title:'事项',due:'截止时间',metricName:'指标',unit:'单位',baseline:'基线',target:'目标值',current:'当前值',direction:'方向',balance:'余额',score:'成绩',date:'业务日期',approvalStatus:'审批状态',effectStatus:'生效状态',objectiveId:'目标编号',keyResultId:'关键结果编号',alignmentTargetId:'对齐目标',cycleId:'周期',planId:'计划编号',stageId:'阶段',taskId:'任务编号',assignmentId:'学习安排',feedbackId:'反馈记录'};
const reasonNames:Record<string,string>={binding_missing:'需要核对员工绑定',PRODUCER_NOT_CONFIGURED:'业务来源尚未接入',PRODUCER_COMMAND_UPGRADE_REQUIRED:'原业务办理接口尚待升级',RELATIONSHIP_NOT_CONFIGURED:'团队关系尚未配置',STATUS_MAPPING_REQUIRED:'来源状态暂不可解释',ADJUSTMENT_PENDING:'目标调整待审核',BALANCE_UNKNOWN:'余额待核对',STAGE_NOT_OPEN:'阶段尚未开放',TEMPLATE_RETIRED:'原模板已失效'};
export default function Portal(){
 const [entry,setEntry]=useState<PortalEntry>('approvals'),[partition,setPartition]=useState('all'),[q,setQ]=useState(''),[summary,setSummary]=useState<any>(null),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState<string|null>(null),[notice,setNotice]=useState(''),[selected,setSelected]=useState<any>(null),[reason,setReason]=useState('');
 const cache=useRef(new PortalCache<any>()),unknownIntent=useRef<any>(null);
 const clear=()=>{cache.current.clear();setData(null);setSummary(null);setSelected(null);setReason('');};
 const load=async(cursor?:string)=>{setError('');if(!cursor)clear();const request=cache.current.begin();try{const [r,s]=await Promise.all([fetch('/api/r1/self-service/'+entry+'?'+new URLSearchParams({partition,q,...(cursor?{cursor}:{})}),{cache:'no-store',signal:request.controller.signal}),fetch('/api/self-service',{cache:'no-store',signal:request.controller.signal})]),b=await r.json() as any,head=await s.json() as any;if(!r.ok||!s.ok)throw Error(b.error??head.error??'暂时不可用');if(b.securityStamp.authorizationRevision!==head.securityStamp.authorizationRevision||b.revision!==head.revision)throw Error('读取版本变化，请刷新');if(!cache.current.accept(request,b,b.securityStamp.authorizationRevision)){setData(null);setSummary(null);return;}setData((old:any)=>cursor&&old?{...b,items:[...old.items,...b.items]}:b);setSummary(head);}catch(e){if(request.generation!==cache.current.generation)return;cache.current.failed();setData(null);setSummary(null);setSelected(null);if((e as Error).name!=='AbortError')setError((e as Error).message);}};
 useEffect(()=>{void load();return()=>cache.current.clear();},[entry,partition,q]);
 const perform=async()=>{if(!selected||!data||busy||unknown)return;setBusy(true);try{const commandId=crypto.randomUUID(),body={entry,businessId:selected.item.businessId,sourceVersion:selected.item.sourceVersion,sourceRevision:selected.item.sourceRevision,action:selected.action,intent:{commandId,idempotencyKey:commandId,expectedWorkspaceRevision:data.revision,expectedAuthorizationRevision:data.securityStamp.authorizationRevision,expectedWriterEpoch:data.securityStamp.writerEpoch,expectedRecoveryEpoch:data.securityStamp.recoveryEpoch,payload:{reason,...(selected.action==='decide'?{decision:selected.decision,nodeRevision:selected.item.fields.nodeRevision,generation:selected.item.fields.generation}:selected.action==='withdraw'?{generation:selected.item.fields.generation}:{})}}};unknownIntent.current=body;let r;try{r=await fetch('/api/r1/self-service/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}catch{setUnknown(commandId);setNotice('结果尚未确认，请查询原办理记录');return;}let result:any;try{result=await r.json();}catch{setUnknown(commandId);setNotice('结果尚未确认，请查询原办理记录');return;}if(r.status>=500){setUnknown(commandId);setNotice('结果尚未确认，请查询原办理记录');return;}if(!r.ok){clear();setError(result.error??'原业务拒绝办理，请重新读取后确认');return;}unknownIntent.current=null;setNotice('已取得原业务办理回执');setSelected(null);await load();}finally{setBusy(false);}};
 return <main className="mx-auto max-w-6xl space-y-5 p-6"><Link href="/">返回工作台</Link><div className="flex items-center justify-between"><h1 className="text-2xl font-semibold">员工自助</h1><Button variant="outline" onClick={()=>load()}>刷新</Button></div><p>查看本人事项、获授权的他人任务和团队资料。业务办理仍由原系统核验。</p>{error&&<p role="alert" className="rounded border border-red-300 p-3 text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}{unknown&&<Button onClick={async()=>{try{const r=await queryClientCommand(unknown);if(r.state==='committed'){setUnknown(null);unknownIntent.current=null;setNotice('已查到原办理回执');await load();}else setNotice('仍无可信结果，保留原办理编号继续核对');}catch(e){clear();setError((e as Error).message);}}}>查询原办理结果</Button>}
 <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{portalEntries.map(key=>{const card=summary?.entries?.find((c:any)=>c.entry===key);return <button key={key} className={'rounded border p-4 text-left '+(key===entry?'border-blue-700 bg-blue-50':'')} onClick={()=>{setEntry(key);setPartition('all');}}><strong>{entryLabels[key]}</strong><p className="mt-2 text-sm">{card?.availability==='not_configured'?'尚未配置':card?.visibleTotal===null||card?.visibleTotal===undefined?'待核对':card.visibleTotal+' 项可见记录'}</p></button>;})}<Link href="/payroll" className="rounded border p-4"><strong>已发布工资条</strong><p className="mt-2">{summary?.payslipCount===null||summary?.payslipCount===undefined?'待核对':summary.payslipCount+' 条'}</p></Link></div>
 <div className="flex flex-wrap gap-3"><select className="rounded border p-2" aria-label="任务分区" value={partition} onChange={e=>setPartition(e.target.value)}><option value="all">全部可见</option><option value="self_tasks">本人任务</option><option value="self_requests">本人申请</option><option value="authorized_others">获授权的他人任务</option><option value="team">团队</option></select><Input placeholder="搜索已开放字段" aria-label="搜索已开放字段" value={q} onChange={e=>setQ(e.target.value)}/></div>
 {data?.reasonCode&&<p>{reasonNames[data.reasonCode]??'该入口当前不可用，请核对原业务配置。'}</p>}{data&&<p className="text-sm">本次可见：{data.visibleTotal??'总数待核'}；待审核 {data.statusCounts?.pending??'—'}；更正待发布 {data.statusCounts?.awaiting_publish??'—'}；待生效 {data.statusCounts?.waiting??'—'}</p>}
 <section className="space-y-3">{data?.items?.map((item:any)=><article key={item.taskKey} className="rounded border p-4"><div className="flex justify-between gap-3"><h2 className="font-semibold">{item.fields.title??item.fields.name??entryLabels[entry]}</h2><span>{item.displayStatus}</span></div><p className="text-xs text-slate-500">{item.partition==='authorized_others'?'获授权的他人事项':item.partition==='self_requests'?'本人申请':item.partition==='team'?'团队记录':'本人事项'}</p><dl className="mt-3 grid gap-2 md:grid-cols-2">{Object.entries(item.fields).filter(([key])=>labels[key]&&!['title','name'].includes(key)).map(([key,value])=><div key={key} className="flex gap-3"><dt className="text-slate-500">{labels[key]}</dt><dd>{value===null?'待核对':String(value)}</dd></div>)}</dl>{item.reasonCode&&<p className="mt-2 text-sm">{reasonNames[item.reasonCode]??'原业务当前有办理限制，请查看原单。'}</p>}<div className="mt-3 flex gap-3"><Link href={item.href}>查看原单</Link>{item.allowedActions.map((action:string)=>action==='decide'?['approved','rejected'].map(decision=><Button key={decision} disabled={busy||!!unknown} onClick={()=>{setSelected({item,action,decision});setReason('');}}>{decision==='approved'?'批准':'拒绝'}</Button>):<Button key={action} disabled={busy||!!unknown} onClick={()=>{setSelected({item,action});setReason('');}}>{action==='withdraw'?'撤回':'办理'}</Button>)}</div></article>)}</section>{data?.nextCursor&&<Button onClick={()=>load(data.nextCursor)}>加载下一页</Button>}
 {!!summary?.supplementaryTasks?.length&&<section className="rounded border p-4"><h2 className="font-semibold">其他原业务任务</h2>{summary.supplementaryTasks.map((task:any)=><div key={task.businessType+task.businessId} className="my-3 flex justify-between"><span>{task.title}</span><Link href={task.href}>查看原业务</Link></div>)}</section>}
 {selected&&<section className="space-y-3 rounded border-2 p-4"><h2>确认办理 · {selected.item.fields.title??selected.item.businessId}</h2><Input aria-label="办理说明" placeholder="填写办理说明" value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={!reason||busy||!!unknown} onClick={perform}>提交</Button><Button variant="outline" onClick={()=>setSelected(null)}>关闭</Button></section>}
 </main>;
}
