'use client';
import {useState,type FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {objectiveQuestions,type ObjectiveQuestion} from '@/lib/hris/learning-objective-exams';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
const names={single:'单选题',multiple:'多选题',trueFalse:'判断题'};
type Send=(c:Record<string,unknown>)=>Promise<void>;
const blank=():ObjectiveQuestion=>({type:'single',prompt:'',options:['',''],correct:[0],points:1});
export function ObjectiveEditor({initial,busy,send}:{initial?:R;busy:boolean;send:Send}){
 const [questions,setQuestions]=useState<ObjectiveQuestion[]>(initial?objectiveQuestions(initial):[blank()]),[passingScore,setPassingScore]=useState(initial?.payload.passingScore??60),[maxAttempts,setMaxAttempts]=useState(initial?.payload.maxAttempts??3);
 const update=(i:number,q:Partial<ObjectiveQuestion>)=>setQuestions(questions.map((x,j)=>j===i?{...x,...q}:x));
 function submit(e:FormEvent){e.preventDefault();void send({objectiveQuestions:questions,passingScore,maxAttempts});}
 return <form onSubmit={submit} className="space-y-4 border rounded p-4"><fieldset disabled={busy} className="space-y-4"><legend>客观题配置</legend><p className="text-sm text-slate-500">每题分值和多选漏选分须明确配置。漏选分仅用于未选错且未选全，选错得0分。及格按未舍入的原始得分比例判断，整数百分制用于显示及计划聚合；人工题和题库抽题尚未支持。</p><div className="grid grid-cols-2 gap-3"><label>及格线（百分制）<Input type="number" min={1} max={100} required value={passingScore} onChange={e=>setPassingScore(Number(e.target.value))}/></label><label>最多作答次数<Input type="number" min={1} max={10} required value={maxAttempts} onChange={e=>setMaxAttempts(Number(e.target.value))}/></label></div>
 {questions.map((q,i)=><fieldset key={i} className="border-t pt-3 space-y-3"><legend>第 {i+1} 题</legend><label className="block">题型<select className="block border rounded p-2" value={q.type} onChange={e=>{const type=e.target.value;if(type==='single'||type==='multiple'||type==='trueFalse')update(i,{type,options:type==='trueFalse'?['正确','错误']:['',''],correct:type==='multiple'?[0,1]:[0],partialPoints:type==='multiple'?0:undefined});}}>{Object.entries(names).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="block">题目<textarea required minLength={5} maxLength={4000} className="block w-full border rounded p-2" value={q.prompt} onChange={e=>update(i,{prompt:e.target.value})}/></label>{q.type!=='trueFalse'&&<label className="block">选项（每行一项，2至6项）<textarea required className="block w-full border rounded p-2" value={q.options.join('\n')} onChange={e=>update(i,{options:e.target.value.split('\n'),correct:[]})}/></label>}<fieldset><legend>正确答案{q.type==='multiple'?'（至少两项）':''}</legend>{q.options.map((o,k)=><label className="flex gap-2" key={k}><input type={q.type==='multiple'?'checkbox':'radio'} name={`correct-${i}`} checked={q.correct?.includes(k)??false} onChange={e=>update(i,{correct:q.type==='multiple'?e.target.checked?[...(q.correct??[]),k]:(q.correct??[]).filter(v=>v!==k):[k]})}/>{k+1}. {o||'未填写选项'}</label>)}</fieldset><label className="block">本题分值<Input type="number" min={1} max={100} required value={q.points} onChange={e=>update(i,{points:Number(e.target.value)})}/></label>{q.type==='multiple'&&<label className="block">漏选分（未选错且未选全）<Input type="number" min={0} max={q.points-1} required value={q.partialPoints??0} onChange={e=>update(i,{partialPoints:Number(e.target.value)})}/></label>}<Button type="button" variant="ghost" disabled={questions.length===1} onClick={()=>setQuestions(questions.filter((_,j)=>j!==i))}>删除此题</Button></fieldset>)}<p>共 {questions.length} 题，原始总分 {questions.reduce((n,q)=>n+q.points,0)}</p><div className="flex gap-3"><Button type="button" variant="outline" disabled={questions.length>=20} onClick={()=>setQuestions([...questions,blank()])}>增加题目</Button><Button type="submit">保存试卷草稿</Button></div></fieldset></form>;
}
export function ObjectiveAttempt({exam,task,attempts,busy,own,send}:{exam:R;task:R;attempts:R[];busy:boolean;own:boolean;send:Send}){
 const questions=objectiveQuestions(exam),[answers,setAnswers]=useState<Record<number,number[]>>({}),passed=attempts.some(a=>a.payload.passed),remaining=Math.max(0,(task.payload.maxAttempts??0)-attempts.length);
 return <section className="space-y-3 border rounded p-4"><h3>独立考试</h3><p>及格线 {task.payload.passingScore}（按未舍入得分比例判断） · 剩余 {remaining} 次</p><p className="text-sm text-slate-500">百分制显示取整；临界分以原始得分比例判断，显示舍入不会改变通过结果。</p>{attempts.map(a=><p key={a.id}>{a.createdAt} · {a.payload.score}分{a.payload.maxPoints!==undefined?`（原始 ${a.payload.earnedPoints}/${a.payload.maxPoints}）`:''} · {a.payload.passed?'通过':'未通过'}</p>)}{own&&!passed&&remaining>0&&task.status==='active'&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void send({answers:questions.map((_,i)=>answers[i]??[])});}}><fieldset disabled={busy} className="space-y-4">{questions.map((q,i)=><fieldset key={i}><legend>{i+1}. {q.prompt}（{names[q.type]}，{q.points}分）</legend>{q.type==='multiple'&&<p className="text-sm">漏选且未选错：{q.partialPoints??0}分；选错：0分。</p>}{q.options.map((o,k)=><label className="flex gap-2" key={k}><input type={q.type==='multiple'?'checkbox':'radio'} name={`${task.id}-answer-${i}`} checked={answers[i]?.includes(k)??false} onChange={e=>setAnswers({...answers,[i]:q.type==='multiple'?e.target.checked?[...(answers[i]??[]),k]:(answers[i]??[]).filter(n=>n!==k):[k]})}/>{o}</label>)}</fieldset>)}<Button type="submit" disabled={questions.some((_,i)=>!answers[i]?.length)}>提交试卷</Button></fieldset></form>}{passed&&<p className="text-green-700">考试已通过；计划结项与学分登记仍须分别满足条件。</p>}</section>;
}
