import {z} from 'zod';
import {attendanceReport} from './attendance';
import {visibleRecord,type DevelopmentRecord as R} from './development';
import {scopedOrgs,type Member} from './authorization';
import {businessDate} from './business-time';
import type {State} from './model';
import {HttpError} from './http';
const id=z.string().min(1).max(100),evidence=z.string().trim().min(5).max(1500),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const n=new Date(v+'T00:00:00Z');return Number.isFinite(n.getTime())&&n.toISOString().slice(0,10)===v;});
export type AttendancePeriodSnapshot={policy:'fixed-shift-coverage-v1';sourceRevision:number;capturedAt:string;rows:ReturnType<typeof attendanceReport>;sources:{id:string;kind:string;status:string;updatedAt:string;referenceId:string|null}[];totals:{plannedMinutes:number;approvedLeaveMinutes:number;uncoveredMinutes:number|null}};
export const attendancePeriodPreviewInput=z.object({action:z.literal('preview'),employeeId:id,start:date,end:date}).strict();
const command=z.discriminatedUnion('action',[z.object({action:z.literal('freeze'),employeeId:id,start:date,end:date,evidence}).strict(),z.object({action:z.literal('refreeze'),id,evidence}).strict(),z.object({action:z.literal('reopen'),id,reason:evidence}).strict(),z.object({action:z.literal('void'),id,reason:evidence}).strict()]);
export function attendancePeriodPreview(records:R[],state:State,employeeId:string,start:string,end:string,at=new Date().toISOString()){
 const shifts=records.filter(r=>r.kind==='shift'&&r.employeeId===employeeId&&r.status==='active'&&r.payload.date!>=start&&r.payload.date!<=end),ids=new Set(shifts.map(r=>r.id)),source=records.filter(r=>ids.has(r.id)||!!r.referenceId&&ids.has(r.referenceId)&&['clock','correction','leave'].includes(r.kind)),rows=attendanceReport(source,at),blockers:string[]=[];
 if(end<start||(Date.parse(end+'T00:00:00Z')-Date.parse(start+'T00:00:00Z'))/86400000>=31)blockers.push('首批期间须为连续1至31个业务日');if(end>=businessDate(at))blockers.push('只能冻结已经结束的业务日期期间');if(!shifts.length)blockers.push('期间没有有效班次，不能以空汇总完成冻结');if(shifts.some(r=>Date.parse(r.payload.endAt!)>Date.parse(at)))blockers.push('存在尚未结束的跨日班次');if(source.some(r=>['correction','leave'].includes(r.kind)&&r.status==='pending'))blockers.push('存在尚未审批完成的补卡或请假');if(rows.some(r=>r.correctionConflict||r.uncoveredMinutes!==0||!['记录完整','请假覆盖'].includes(r.status)))blockers.push('存在缺卡、补卡冲突或未覆盖时段，请先核验');if(source.length>1000)blockers.push('首批单次最多1000条来源，请缩短期间后核对');
 return {rows,source,blockers,totals:{plannedMinutes:rows.reduce((s,r)=>s+r.plannedMinutes,0),approvedLeaveMinutes:rows.reduce((s,r)=>s+r.approvedLeaveMinutes,0),uncoveredMinutes:rows.some(r=>r.uncoveredMinutes===null)?null:rows.reduce((s,r)=>s+r.uncoveredMinutes!,0)}};
}
export function applyAttendancePeriod(records:R[],state:State,m:Member,input:unknown,revision:number,at=new Date().toISOString()):R{
 const c=command.parse(input),deny=():never=>{throw new HttpError(403,'没有此员工考勤期间的管理权限');},fail=(message:string):never=>{throw new HttpError(400,message);};if(!['admin','hr'].includes(m.role))deny();const old=c.action==='freeze'?undefined:records.find(r=>r.kind==='attendancePeriod'&&r.id===c.id);if(c.action!=='freeze'&&(!old||!visibleRecord(old,records,state,m)))deny();const employee=state.employees.find(e=>e.id===(c.action==='freeze'?c.employeeId:old!.employeeId));if(!employee||!scopedOrgs(state,m).has(employee.orgId))deny();
 if(c.action==='reopen'){if(old!.status!=='frozen')fail('只有已冻结期间可重新开放');return {...old!,status:'open',updatedAt:at,payload:{...old!.payload,reopenedBy:m.userId,reopenedAt:at,reopenReason:c.reason}};}
 if(c.action==='void'){if(old!.status!=='open')fail('须先重新开放才能作废错误期间');return {...old!,status:'void',updatedAt:at,payload:{...old!.payload,closedReason:c.reason}};}
 if(old&&old.status!=='open')fail('只有重新开放的期间可以再次冻结');const start=c.action==='freeze'?c.start:old!.payload.start!,end=c.action==='freeze'?c.end:old!.payload.end!;
 if(records.some(r=>r.kind==='attendancePeriod'&&r.employeeId===employee!.id&&r.id!==old?.id&&r.status!=='void'&&r.payload.start!<=end&&r.payload.end!>=start))fail('同员工已有重叠期间，请使用原期间重新冻结或先核对后作废');const preview=attendancePeriodPreview(records,state,employee!.id,start,end,at);if(preview.blockers.length)fail(preview.blockers.join('；'));
 const snapshot:AttendancePeriodSnapshot={policy:'fixed-shift-coverage-v1',sourceRevision:revision,capturedAt:at,rows:preview.rows,sources:preview.source.map(r=>({id:r.id,kind:r.kind,status:r.status,updatedAt:r.updatedAt,referenceId:r.referenceId})),totals:preview.totals};return {id:old?.id??crypto.randomUUID(),kind:'attendancePeriod',employeeId:employee!.id,positionId:null,referenceId:null,status:'frozen',createdBy:old?.createdBy??m.userId,createdAt:old?.createdAt??at,updatedAt:at,payload:{...old?.payload,start,end,version:(old?.payload.version??0)+1,employeeSnapshot:{code:employee!.code,name:employee!.name,orgName:state.orgs.find(o=>o.id===employee!.orgId)?.name??''},orgId:employee!.orgId,attendanceSnapshot:snapshot,evidence:c.evidence,verifiedBy:m.userId,verifiedAt:at}};
}
