/** Pure adapter contract preflight. No network, persistence, account grants or personnel mutations. */
import {z} from 'zod';
const key=z.string().trim().min(1).max(100),label=z.string().trim().min(1).max(100);
export const externalProfileEvent=z.object({eventId:key,sourceId:key,externalEmployeeId:key,sequence:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),occurredAt:z.string().datetime({offset:true}),mappingVersion:z.number().int().positive(),profile:z.object({code:label,name:label,externalOrgId:key,job:z.string().trim().max(200),email:z.union([z.literal(''),z.string().email().max(254)])}).strict()}).strict();
export type ProfileEvent=z.infer<typeof externalProfileEvent>;
export type IntegrationMapping={tenantId:string;sourceId:string;version:number;employees:Readonly<Record<string,string>>;organizations:Readonly<Record<string,string>>};
export type IntegrationReceipt={tenantId:string;sourceId:string;eventId:string;externalEmployeeId:string;sequence:number;digest:string;committedRevision:number};
export type IntegrationCursor={tenantId:string;sourceId:string;externalEmployeeId:string;lastSequence:number};
export type IntegrationPreflight={decision:'ready'|'duplicate'|'conflict'|'gap'|'stale'|'mapping_required'|'rejected';code:string;digest?:string;eventId?:string;expectedSequence?:number;committedRevision?:number;candidate?:{employeeId:string;orgId:string;code:string;name:string;job:string;email:string};};
function canonical(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical((value as Record<string,unknown>)[k])).join(',')+'}';}
export async function inspectProfileEvent(input:unknown,mapping:IntegrationMapping,receipts:readonly IntegrationReceipt[],cursors:readonly IntegrationCursor[]):Promise<IntegrationPreflight>{
 const parsed=externalProfileEvent.safeParse(input);if(!parsed.success)return {decision:'rejected',code:'INVALID_EVENT_SCHEMA'};const event=parsed.data;if(event.sourceId!==mapping.sourceId)return {decision:'rejected',code:'SOURCE_MISMATCH'};if(event.mappingVersion!==mapping.version)return {decision:'mapping_required',code:'MAPPING_VERSION_MISMATCH',eventId:event.eventId};
 const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical({...event,occurredAt:new Date(event.occurredAt).toISOString()}))))).map(b=>b.toString(16).padStart(2,'0')).join(''),base={eventId:event.eventId,digest},sameNamespace=(r:{tenantId:string;sourceId:string})=>r.tenantId===mapping.tenantId&&r.sourceId===mapping.sourceId;
 const matches=receipts.filter(r=>sameNamespace(r)&&r.eventId===event.eventId);if(matches.length>1)return {...base,decision:'conflict',code:'DUPLICATE_RECEIPT_INVARIANT'};const receipt=matches[0];if(receipt)return receipt.digest===digest&&receipt.externalEmployeeId===event.externalEmployeeId&&receipt.sequence===event.sequence?{...base,decision:'duplicate',code:'ALREADY_COMMITTED',committedRevision:receipt.committedRevision}:{...base,decision:'conflict',code:'EVENT_ID_REUSED_WITH_DIFFERENT_CONTENT'};
 const matchingCursors=cursors.filter(r=>sameNamespace(r)&&r.externalEmployeeId===event.externalEmployeeId);if(matchingCursors.length>1||matchingCursors.some(r=>!Number.isSafeInteger(r.lastSequence)||r.lastSequence<0))return {...base,decision:'conflict',code:'INVALID_CURSOR_INVARIANT'};const last=matchingCursors[0]?.lastSequence??0;if(event.sequence<=last)return {...base,decision:'stale',code:'OLDER_EVENT_WITHOUT_RECEIPT'};if(event.sequence!==last+1)return {...base,decision:'gap',code:'MISSING_PREDECESSOR',expectedSequence:last+1};
 const employeeId=Object.hasOwn(mapping.employees,event.externalEmployeeId)?mapping.employees[event.externalEmployeeId]:undefined,orgId=Object.hasOwn(mapping.organizations,event.profile.externalOrgId)?mapping.organizations[event.profile.externalOrgId]:undefined;if(!employeeId||!orgId)return {...base,decision:'mapping_required',code:!employeeId?'EMPLOYEE_MAPPING_REQUIRED':'ORGANIZATION_MAPPING_REQUIRED'};
 if(Object.values(mapping.employees).filter(id=>id===employeeId).length!==1||Object.values(mapping.organizations).filter(id=>id===orgId).length!==1)return {...base,decision:'mapping_required',code:'AMBIGUOUS_MAPPING'};
 return {...base,decision:'ready',code:'DRY_RUN_ONLY',candidate:{employeeId,orgId,code:event.profile.code,name:event.profile.name,job:event.profile.job,email:event.profile.email}};
}
export function integrationRetryDecision(attempt:number,httpStatus:number|undefined,retryAfterSeconds?:number){
 if(!Number.isInteger(attempt)||attempt<1||attempt>6)return {retry:false,reason:'attempt_limit',delaySeconds:0} as const;
 if(httpStatus!==undefined&&httpStatus!==408&&httpStatus!==429&&!(httpStatus>=500&&httpStatus<=599))return {retry:false,reason:'requires_diagnosis',delaySeconds:0} as const;
 const retryAfter=Number.isFinite(retryAfterSeconds)&&retryAfterSeconds!>=0?Math.min(3600,Math.ceil(retryAfterSeconds!)):0;
 return {retry:true,reason:'transient_failure',delaySeconds:Math.max(retryAfter,Math.min(300,2**attempt))} as const;
}
