import {z} from 'zod';
import {visibleRecord,type DevelopmentRecord as R} from './development';
import {interviewCriteria,type InterviewCriteria} from './recruitment-evaluations';
import type {State} from './model';
import type {Member} from './authorization';
import {HttpError} from './http';
const id=z.string().min(1).max(100),text=z.string().trim().min(1).max(200),instant=z.string().datetime({offset:true});
export type ScheduledInterviewDefinition={id:string;rootId:string;version:number;title:string;orgId:string;criteria:InterviewCriteria};
export type InterviewSchedule={title:string;method:'onsite'|'video'|'phone';startAt:string;endAt:string;timeZone:'Asia/Shanghai';location:string;interviewerEmployeeId:string;definition:ScheduledInterviewDefinition};
const fields={title:text,method:z.enum(['onsite','video','phone']),startAt:instant,endAt:instant,timeZone:z.literal('Asia/Shanghai'),location:z.string().trim().min(1).max(1000),interviewerEmployeeId:id,definitionId:id};
const command=z.discriminatedUnion('action',[z.object({action:z.literal('schedule'),candidateId:id,...fields}).strict(),z.object({action:z.literal('reschedule'),id,...fields}).strict(),z.object({action:z.literal('cancel'),id,reason:z.string().trim().min(5).max(1500)}).strict()]);
export function appointmentLive(r:R,records:R[],state:State){const c=records.find(x=>x.id===r.referenceId&&x.kind==='candidate'),q=records.find(x=>x.id===c?.referenceId&&x.kind==='requisition'),p=state.positions?.find(x=>x.id===r.positionId),e=state.employees.find(x=>x.id===r.payload.interviewSchedule?.interviewerEmployeeId);return r.status==='scheduled'&&!!c&&['screening','interviewed'].includes(c.status)&&q?.status==='active'&&p?.status==='启用'&&!!e&&e.status!=='离职'&&e.orgId===p.orgId;}
export function canEvaluateAppointment(r:R,records:R[],state:State,m:Member,at=new Date().toISOString()){return ['admin','hr','manager'].includes(m.role)&&m.employeeId===r.payload.interviewSchedule?.interviewerEmployeeId&&visibleRecord(r,records,state,m)&&appointmentLive(r,records,state)&&Date.parse(r.payload.interviewSchedule!.endAt)<=Date.parse(at);}
export function applyInterviewSchedule(records:R[],state:State,m:Member,input:unknown,eligibleInterviewerIds:readonly string[],at=new Date().toISOString()):R{
 const c=command.parse(input),deny=():never=>{throw new HttpError(403,'没有此面试排期的管理权限');},fail=(message:string):never=>{throw new HttpError(400,message);};
 if(!['admin','hr'].includes(m.role))deny();const old=c.action==='schedule'?undefined:records.find(r=>r.kind==='interviewAppointment'&&r.id===c.id);if(c.action!=='schedule'&&(!old||!visibleRecord(old,records,state,m)))deny();if(old&&old.status!=='scheduled')fail('已取消或完成的排期不可覆盖');
 if(c.action==='cancel')return {...old!,status:'cancelled',updatedAt:at,payload:{...old!.payload,closedReason:c.reason}};
 const candidate=records.find(r=>r.kind==='candidate'&&r.id===(c.action==='schedule'?c.candidateId:old!.referenceId));if(!candidate||!visibleRecord(candidate,records,state,m))deny();const q=records.find(r=>r.id===candidate!.referenceId&&r.kind==='requisition'),position=state.positions?.find(p=>p.id===candidate!.positionId);if(!['screening','interviewed'].includes(candidate!.status)||q?.status!=='active'||position?.status!=='启用')fail('候选、需求或岗位已不允许面试安排');
 const interviewer=state.employees.find(e=>e.id===c.interviewerEmployeeId);if(!interviewer||!eligibleInterviewerIds.includes(interviewer.id)||interviewer.status==='离职'||interviewer.orgId!==position!.orgId)fail('首批须指定岗位同组织、具备有效管理评价账号的在职人员');
 const start=Date.parse(c.startAt),end=Date.parse(c.endAt);if(end<=start||end-start>86400000)fail('结束须晚于开始，首批单次面试最多24小时');
 let definition=old?.payload.interviewSchedule?.definition;if(!definition||definition.id!==c.definitionId){const d=records.find(r=>r.kind==='interviewDefinition'&&r.id===c.definitionId);if(!d||!visibleRecord(d,records,state,m))deny();if(d!.status!=='sealed'||d!.payload.orgId!==position!.orgId)fail('请选择岗位同组织已定版评价表');definition={id:d!.id,rootId:d!.payload.definitionRootId!,version:d!.payload.version!,title:d!.payload.title!,orgId:position!.orgId,criteria:interviewCriteria.parse(d!.payload.interviewCriteria)};}
 if(records.some(r=>r.kind==='interviewAppointment'&&r.id!==old?.id&&r.status==='scheduled'&&r.payload.interviewSchedule&&(r.referenceId===candidate!.id||r.payload.interviewSchedule.interviewerEmployeeId===interviewer!.id)&&Date.parse(r.payload.interviewSchedule.startAt)<end&&Date.parse(r.payload.interviewSchedule.endAt)>start))fail('候选人或指定面试官已有重叠排期，请先调整或取消原安排');
 const key=old?.id??crypto.randomUUID();return {id:key,kind:'interviewAppointment',employeeId:null,positionId:candidate!.positionId,referenceId:candidate!.id,status:'scheduled',createdBy:old?.createdBy??m.userId,createdAt:old?.createdAt??at,updatedAt:at,payload:{interviewSchedule:{title:c.title,method:c.method,startAt:new Date(start).toISOString(),endAt:new Date(end).toISOString(),timeZone:c.timeZone,location:c.location,interviewerEmployeeId:c.interviewerEmployeeId,definition:structuredClone(definition)}}};
}
