import {goalInput,resolvePerformanceGoals} from './performance-indicators';
import {performanceTemplateSnapshot,validatePerformanceResponses,validatePerformanceGoalRules} from './performance-templates';
import {performanceInputScore,performanceRatingAt,ratingSchemeSchema,validatePerformanceScores} from './performance-ratings';
import {z} from 'zod';
import {HttpError} from './http';
import {scopedOrgs,type Member} from './authorization';
import {isTalentManager,orgWithin,visibleRecord,type DevelopmentRecord} from './development';
import type {State} from './model';
const id=z.string().min(1).max(100),text=z.string().trim().min(1).max(200),evidence=z.string().trim().min(5).max(4000),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return !isNaN(d.getTime())&&d.toISOString().slice(0,10)===v;});
const goal=goalInput,score=z.number().min(0).max(100).multipleOf(0.01);
const cycleFields={templateId:id.nullable().optional(),ratingDefinitionId:id.nullable().optional(),metadata:z.object({year:z.number().int().min(1900).max(2200).optional(),cycleLabel:text.optional(),category:text.optional(),businessDate:date.optional()}).strict().optional(),name:text,orgId:id,period:text,start:date,end:date,lowCut:score,highCut:score,lowLabel:text,midLabel:text,highLabel:text};
export const performanceCommand=z.discriminatedUnion('action',[
 z.object({action:z.literal('cycle'),...cycleFields}),z.object({action:z.literal('editCycle'),id,...cycleFields}),
 z.object({action:z.literal('startCycle'),id}),z.object({action:z.literal('closeCycle'),id}),
 z.object({action:z.literal('goals'),id:id.optional(),employeeId:id,cycleId:id,goals:z.array(goal).min(1).max(20)}),
 z.object({action:z.literal('confirmGoals'),id}),
 z.object({action:z.literal('selfReview'),id,responses:z.unknown().optional(),evidence}),
 z.object({action:z.literal('evaluate'),id,responses:z.unknown().optional(),scores:z.array(performanceInputScore).min(1).max(20),evidence}),
 z.object({action:z.literal('returnPerformance'),id,evidence}),
 z.object({action:z.literal('cancelPerformance'),id,evidence}),
 z.object({action:z.literal('publishPerformance'),id,evidence,supersedes:id.optional()}),
 z.object({action:z.literal('appeal'),resultId:id,evidence}),
 z.object({action:z.literal('withdrawAppeal'),id,evidence}),
 z.object({action:z.literal('reviewAppeal'),id,accepted:z.boolean(),scores:z.array(performanceInputScore).min(1).max(20).optional(),evidence}),
 z.object({action:z.literal('publishCorrection'),id,evidence}),
]);
export function applyPerformance(records:DevelopmentRecord[],state:State,member:Member,input:unknown,at=new Date().toISOString()){
 const c=performanceCommand.parse(input),scope=scopedOrgs(state,member);
 const invalid=(message:string):never=>{throw new HttpError(400,message);},deny=(message:string):never=>{throw new HttpError(403,message);};
 const manager=()=>{if(!isTalentManager(member))deny('没有绩效管理权限');};
 const hr=()=>{if(!['admin','hr'].includes(member.role))deny('仅管理员和HR可配置周期及发布结果');};
 const employee=(id:string)=>{const e=state.employees.find(e=>e.id===id);if(!e||!(isTalentManager(member)?scope.has(e.orgId):e.id===member.employeeId))deny('没有此员工的数据权限');return e!;};
 const get=(id:string,kind:DevelopmentRecord['kind'])=>{const r=records.find(r=>r.id===id&&r.kind===kind);if(!r||!visibleRecord(r,records,state,member))deny('记录不存在或没有访问权限');return r!;};
 const independent=(r:DevelopmentRecord)=>{manager();employee(r.employeeId!);if(r.employeeId===member.employeeId)deny('不能确认、评价或发布本人的绩效');};
 const cycle=(r:DevelopmentRecord)=>{const p=get(r.referenceId!,'performanceCycle');if(p.status!=='active')invalid('绩效周期未启动或已结束');const e=employee(r.employeeId!);if(e.status==='离职'||!orgWithin(state,e.orgId,p.payload.orgId!))invalid('员工已离职或已调出本绩效周期的组织范围，不能继续推进计划');return p;};
 const published=(r:DevelopmentRecord)=>records.some(x=>x.kind==='performance'&&x.payload.sourcePlanId===r.id);
 const make=(kind:DevelopmentRecord['kind'],payload:DevelopmentRecord['payload'],extra:Partial<DevelopmentRecord>={})=>({id:crypto.randomUUID(),kind,payload,employeeId:null,positionId:null,referenceId:null,status:'draft',createdBy:member.userId,createdAt:at,updatedAt:at,...extra} as DevelopmentRecord);
 const change=(r:DevelopmentRecord,status:string,payload:DevelopmentRecord['payload']={})=>({...r,status,payload:{...r.payload,...payload},updatedAt:at});
 const latest=(r:DevelopmentRecord)=>{if(records.some(x=>x.kind==='performance'&&x.payload.supersedes===r.id))invalid('该结果已被更正，请使用最新版本');};
 const frozen=(r:DevelopmentRecord)=>{const p=r.payload.performanceSnapshot;if(!p||!r.payload.sourcePlanId||r.status!=='published')invalid('仅可对具备完整评分快照的正式结果办理申诉');const plan=z.object({goals:z.array(goal).min(1).max(20),evaluatedBy:z.string().optional()}).passthrough().parse(p!.plan),cy=z.object({lowCut:score,highCut:score,lowLabel:text,midLabel:text,highLabel:text,ratingScheme:ratingSchemeSchema.optional()}).passthrough().parse(p!.cycle);return {plan,cy};};
 switch(c.action){
 case 'appeal':{const r=get(c.resultId,'performance');if(r.employeeId!==member.employeeId)deny('仅员工本人可对自己的正式结果申诉');latest(r);frozen(r);if(records.some(x=>x.kind==='performanceAppeal'&&x.referenceId===r.id&&x.status!=='withdrawn'))invalid('本结果版本已有申诉记录，请查看办理进度');return make('performanceAppeal',{period:r.payload.period,evidence:c.evidence,performanceSnapshot:{...r.payload},submittedBy:member.userId,submittedAt:at},{employeeId:r.employeeId,referenceId:r.id,status:'submitted'});}
 case 'withdrawAppeal':{const r=get(c.id,'performanceAppeal');if(r.employeeId!==member.employeeId||r.createdBy!==member.userId)deny('仅申诉人本人可撤回');if(r.status!=='submitted')invalid('只有待复核申诉可撤回');return change(r,'withdrawn',{closedReason:c.evidence});}
 case 'reviewAppeal':{hr();const r=get(c.id,'performanceAppeal');independent(r);if(r.status!=='submitted')invalid('申诉尚未提交或已经处理');const old=get(r.referenceId!,'performance');latest(old);const {plan,cy}=frozen(old);if(member.userId===r.createdBy||member.userId===old.createdBy||member.userId===plan.evaluatedBy)deny('原评价人、原发布人和申诉人不能复核此次申诉');if(!c.accepted){if(c.scores)invalid('维持原结果时不应提交新评分');return change(r,'upheld',{verification:c.evidence,verifiedBy:member.userId,verifiedAt:at});}if(!c.scores||c.scores.length!==plan.goals.length)invalid('更正须对原快照中的每项目标重新评分');validatePerformanceScores(cy,c.scores!);const total=Math.round(c.scores!.reduce((sum,v,i)=>sum+v*plan.goals[i].weight,0))/100,{band,label}=performanceRatingAt(cy,total);if(total===old.payload.score&&JSON.stringify(c.scores)===JSON.stringify((old.payload.performanceSnapshot?.plan as {scores?:number[]})?.scores))invalid('评分未改变，可选择维持原结果');return change(r,'approved',{scores:c.scores,score:total,band,originalRating:label,verification:c.evidence,verifiedBy:member.userId,verifiedAt:at});}
 case 'publishCorrection':{hr();const r=get(c.id,'performanceAppeal');independent(r);if(r.status!=='approved')invalid('申诉尚未获准更正');if(r.payload.verifiedBy===member.userId)deny('须由另一位有权限HR核对并发布更正');if(records.some(x=>x.kind==='performance'&&x.payload.appealId===r.id))invalid('本次更正已经发布');const old=get(r.referenceId!,'performance');latest(old);const {plan,cy}=frozen(old);return make('performance',{period:old.payload.period,source:old.payload.source,originalRating:r.payload.originalRating,band:r.payload.band,score:r.payload.score,reason:c.evidence,sourcePlanId:old.payload.sourcePlanId,supersedes:old.id,appealId:r.id,performanceSnapshot:{cycle:{...cy},plan:{...plan,scores:r.payload.scores,score:r.payload.score,evaluation:r.payload.verification,evaluatedBy:r.payload.verifiedBy,evaluatedAt:r.payload.verifiedAt},appeal:{id:r.id}}},{employeeId:r.employeeId,referenceId:r.id,status:'published'});}

 case 'cycle':case 'editCycle':{hr();const old=c.action==='editCycle'?get(c.id,'performanceCycle'):undefined;if(old&&(old.status!=='draft'||records.some(r=>r.kind==='performancePlan'&&r.referenceId===old.id)))invalid('只有未启动且未生成计划的周期草稿可编辑');if(old&&old.payload.orgId!==c.orgId)invalid('周期所属组织不能修改，请另建周期');const org=state.orgs.find(o=>o.id===c.orgId);if(!org||!scope.has(c.orgId))deny('没有此组织的管理权限');if(org!.status!=='启用'||c.end<c.start||c.lowCut>=c.highCut)invalid('请检查组织状态、日期及评级阈值');if(new Set([c.lowLabel,c.midLabel,c.highLabel]).size!==3)invalid('评级名称不能重复');const definition=c.ratingDefinitionId?get(c.ratingDefinitionId,'performanceRatingDefinition'):undefined;if(definition&&(definition.status!=='sealed'||definition.payload.orgId!==c.orgId))invalid('请选择同组织已定版的绩效等级方案');const template=c.templateId?get(c.templateId,'performanceTemplate'):undefined;if(template&&(template.status!=='sealed'||template.payload.orgId!==c.orgId))invalid('请选择同组织已定版绩效模板');const templateSnapshot=old&&c.templateId===undefined?old.payload.performanceTemplate:template?performanceTemplateSnapshot.parse({id:template.id,rootId:template.payload.definitionRootId,version:template.payload.version,title:template.payload.title,description:template.payload.description,orgId:template.payload.orgId,workflow:'single-weighted-goals-v1',prompts:template.payload.performancePrompts,goalRules:template.payload.performanceGoalRules}):undefined;const ratingScheme=old&&c.ratingDefinitionId===undefined?old.payload.ratingScheme:definition?ratingSchemeSchema.parse({id:definition.id,rootId:definition.payload.definitionRootId,version:definition.payload.version,title:definition.payload.title,levels:definition.payload.ratingLevels}):undefined;return make('performanceCycle',{performanceTemplate:templateSnapshot,performanceMetadata:c.metadata??old?.payload.performanceMetadata,ratingScheme,name:c.name,orgId:c.orgId,period:c.period,start:c.start,end:c.end,lowCut:c.lowCut,highCut:c.highCut,lowLabel:c.lowLabel,midLabel:c.midLabel,highLabel:c.highLabel},old?{id:old.id,createdBy:old.createdBy,createdAt:old.createdAt}:{});}
 case 'startCycle':{hr();const r=get(c.id,'performanceCycle');if(r.status!=='draft')invalid('周期已经启动');return change(r,'active');}
 case 'closeCycle':{hr();const r=get(c.id,'performanceCycle');if(r.status!=='active')invalid('周期尚未启动或已结束');if(records.some(x=>x.kind==='performancePlan'&&x.referenceId===r.id&&x.status!=='cancelled'&&!published(x)))invalid('仍有未发布或未取消的绩效计划');return change(r,'closed');}
 case 'goals':{const e=employee(c.employeeId),cy=get(c.cycleId,'performanceCycle');if(e.status==='离职'||cy.status!=='active'||!orgWithin(state,e.orgId,cy.payload.orgId!))invalid('员工状态或周期范围不符合要求');validatePerformanceGoalRules(cy.payload.performanceTemplate,c.goals);if(c.goals.reduce((sum,g)=>sum+g.weight,0)!==100)invalid('目标权重合计必须等于100%');const old=c.id?get(c.id,'performancePlan'):undefined;if(old&&(old.status!=='draft'||old.employeeId!==e.id||old.referenceId!==cy.id))invalid('仅可修改本人或管理范围内同一周期的草稿');if(records.some(r=>r.kind==='performancePlan'&&r.employeeId===e.id&&r.referenceId===cy.id&&r.id!==c.id))invalid('此员工已建立本周期计划');return make('performancePlan',{period:cy.payload.period,goals:resolvePerformanceGoals(c.goals,old?.payload.goals,records,state,member,e.orgId)},{employeeId:e.id,referenceId:cy.id,...(old?{id:old.id,createdBy:old.createdBy,createdAt:old.createdAt}:{})});}
 case 'confirmGoals':{const r=get(c.id,'performancePlan');independent(r);cycle(r);if(r.status!=='draft')invalid('仅草稿目标可以确认');return change(r,'confirmed',{confirmedBy:member.userId,confirmedAt:at});}
 case 'selfReview':{const r=get(c.id,'performancePlan');if(records.some(c=>c.kind==='performanceGoalChange'&&c.referenceId===r.id&&c.status==='submitted'))invalid('目标调整待复核，请先处理或撤回调整再提交自评');if(r.employeeId!==member.employeeId)deny('仅员工本人可提交自评');const cy=cycle(r);if(r.status!=='confirmed')invalid('目标未确认或已提交自评');return change(r,'submitted',{selfResponses:validatePerformanceResponses(cy.payload.performanceTemplate,'selfReview',c.responses),selfEvidence:c.evidence,selfReviewedAt:at});}
 case 'returnPerformance':{const r=get(c.id,'performancePlan');independent(r);cycle(r);if(published(r)||!['submitted','evaluated'].includes(r.status))invalid('当前阶段不能退回');return change(r,'confirmed',{verification:c.evidence,scores:undefined,score:undefined,evaluation:undefined,evaluationResponses:undefined,evaluatedBy:undefined,evaluatedAt:undefined});}
 case 'evaluate':{const r=get(c.id,'performancePlan');independent(r);const cy=cycle(r);if(r.status!=='submitted')invalid('须先由员工提交自评');if(c.scores.length!==r.payload.goals!.length)invalid('请对每项目标评分');validatePerformanceScores(cy.payload,c.scores);const weighted=Math.round(c.scores.reduce((sum,v,i)=>sum+v*r.payload.goals![i].weight,0))/100;return change(r,'evaluated',{evaluationResponses:validatePerformanceResponses(cy.payload.performanceTemplate,'evaluation',c.responses),scores:c.scores,score:weighted,evaluation:c.evidence,evaluatedBy:member.userId,evaluatedAt:at});}
 case 'cancelPerformance':{const r=get(c.id,'performancePlan');if(records.some(c=>c.kind==='performanceGoalChange'&&c.referenceId===r.id&&c.status==='submitted'))invalid('请先处理或撤回目标调整再取消计划');independent(r);if(published(r)||r.status==='cancelled')invalid('已发布或取消的绩效计划不能取消');return change(r,'cancelled',{closedReason:c.evidence});}
 case 'publishPerformance':{hr();const r=get(c.id,'performancePlan');independent(r);const cy=cycle(r);if(r.status!=='evaluated'||published(r))invalid('尚未完成评价或已发布');const previous=records.filter(x=>x.kind==='performance'&&x.employeeId===r.employeeId&&x.payload.period===r.payload.period);if(previous.length&&!c.supersedes)invalid('此员工本期已有绩效，需明确选择被替代的历史记录');if(c.supersedes){const old=get(c.supersedes,'performance');if(old.payload.sourcePlanId)invalid('正式结果须通过申诉更正流程处理，不能用另一周期直接替代');if(old.employeeId!==r.employeeId||old.payload.period!==r.payload.period||records.some(x=>x.payload.supersedes===old.id))invalid('仅可替代同员工同期间的最新历史记录');}const total=r.payload.score!,{band,label:rating}=performanceRatingAt(cy.payload,total);return make('performance',{period:r.payload.period,source:'正式绩效周期：'+cy.payload.name,originalRating:rating,band,score:total,reason:c.evidence,sourcePlanId:r.id,supersedes:c.supersedes,performanceSnapshot:{cycle:{...cy.payload},plan:{...r.payload}}},{employeeId:r.employeeId,referenceId:r.id,status:'published'});}
 }
}
