import {z} from 'zod';
import {HttpError} from './http';
import {authorizeTuple} from './r1-authorization';
import {commitCommand,digest,securityStamp,type CommandIntent} from './r1-command';
import type {Member} from './authorization';
const id=z.string().min(1).max(100),version=z.number().int().positive();
/** Contract shapes only; none constructs a provider connection or implements deferred business algorithms. */
export const externalPayloads={
 master_data:z.object({externalPersonId:id,externalOrgId:id,mappingVersion:version,sequence:version,profile:z.object({code:id,name:id,job:z.string().max(200),email:z.string().email().or(z.literal(''))}).strict()}).strict(),
 electronic_signing:z.object({contractId:id,contractVersion:version,legalEntityId:id,templateVersion:version,signerReference:id,externalEnvelopeId:id.nullable()}).strict(),
 assessment:z.object({templateId:id,templateVersion:version,assessmentInvitationId:id,externalAttemptId:id.nullable(),consentReference:id,visibilityReference:id,resultVersion:version.nullable()}).strict(),
 budget:z.object({requestId:id,period:id,orgId:id,legalEntityId:id,currency:z.string().regex(/^[A-Z]{3}$/),amountCents:z.number().int().safe().nonnegative(),holdId:id.nullable(),expiry:z.string().datetime().nullable(),revision:version}).strict(),
 payment:z.object({payrollBatchId:id,adjustmentId:id.nullable(),sourceVersion:version,period:id,currency:z.string().regex(/^[A-Z]{3}$/),voucherRef:id.nullable(),paymentOrderRef:id.nullable()}).strict(),
 notification:z.object({eventId:id,templateVersion:version,recipientId:id,channel:z.enum(['in_app','simulated']),secureLink:z.string().regex(/^\/r1-[a-z/-]+(?:\?[A-Za-z0-9%&=._-]+)?$/),providerRequestId:id}).strict(),
};
export const stableReference=z.object({source:id,objectType:z.enum(['label','assessment_template','assessment_result']),externalId:id,version,internalId:id,orgId:id,label:z.string().trim().min(1).max(100),rawStatus:id,mappingVersion:version,attributes:z.object({relationId:id.optional(),personId:id.optional(),effectiveFrom:z.string().datetime().optional(),effectiveTo:z.string().datetime().nullable().optional(),revokeRef:id.nullable().optional(),anonymityPolicyRef:id.optional(),visibilityPolicyRef:id.optional()}).strict()}).strict();
export type ReferenceContract={source:string;mappingVersion:number;statusMap:Readonly<Record<string,'available'|'retired'|'blocked'>>;mode:'internal'|'simulated';version:string};
export async function registerReference(ctx:{db:D1Database;member:Member;row:{revision:number}},intent:CommandIntent,contract:ReferenceContract){
 const c=stableReference.parse(intent.payload),{db,member:m}=ctx,t=m.tenantId,s=await securityStamp(db,t);if(c.source!==contract.source||c.mappingVersion!==contract.mappingVersion)throw new HttpError(409,'来源映射版本不匹配','MAPPING_REQUIRED');if(!Object.hasOwn(contract.statusMap,c.rawStatus))throw new HttpError(409,'生产者状态未登记','STATUS_MAPPING_REQUIRED');
 await authorizeTuple(db,m,{objectType:'BASE',action:'reference.register',orgId:c.orgId,personId:c.attributes.personId??'',field:'record',historyMode:'current'});const hash=await digest(c),old=await db.prepare('SELECT digest FROM r1_stable_references WHERE tenant_id=? AND source=? AND object_type=? AND external_id=? AND version=?').bind(t,c.source,c.objectType,c.externalId,c.version).first<{digest:string}>();if(old&&old.digest!==hash)throw new HttpError(409,'同引用版本内容冲突','REFERENCE_CONFLICT');
 const mapping=await db.prepare('SELECT internal_id FROM r1_stable_references WHERE tenant_id=? AND source=? AND object_type=? AND external_id=? LIMIT 1').bind(t,c.source,c.objectType,c.externalId).first<{internal_id:string}>();if(mapping&&mapping.internal_id!==c.internalId)throw new HttpError(409,'稳定引用不能改绑对象','REFERENCE_REBIND_FORBIDDEN');
 const alias=await db.prepare('SELECT external_id FROM r1_stable_references WHERE tenant_id=? AND source=? AND object_type=? AND internal_id=? AND external_id<>? LIMIT 1').bind(t,c.source,c.objectType,c.internalId,c.externalId).first();if(alias)throw new HttpError(409,'同来源多个身份不能自动合并','AMBIGUOUS_MAPPING');
 return commitCommand(db,m,s,intent,token=>[db.prepare('INSERT OR IGNORE INTO r1_stable_references SELECT owner,?,?,?,?,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(c.source,c.objectType,c.externalId,c.version,c.internalId,c.orgId,c.label,c.rawStatus,c.mappingVersion,JSON.stringify(c.attributes),hash,t,token)],{referenceId:c.internalId,version:c.version,mode:contract.mode});
}
export async function readReference(ctx:{db:D1Database;member:Member},key:{source:string;objectType:string;externalId:string;version:number},contract:ReferenceContract){
 const {db,member:m}=ctx;if(key.source!==contract.source)throw new HttpError(409,'来源未登记','MAPPING_REQUIRED');const r=await db.prepare('SELECT * FROM r1_stable_references WHERE tenant_id=? AND source=? AND object_type=? AND external_id=? AND version=?').bind(m.tenantId,key.source,key.objectType,key.externalId,key.version).first<any>();if(!r)throw new HttpError(404,'引用不存在或不可见','NOT_FOUND_OR_NOT_VISIBLE');const attrs=JSON.parse(r.payload);await authorizeTuple(db,m,{objectType:'BASE',action:'reference.read',orgId:r.org_id,personId:attrs.personId??'',field:'record',historyMode:'current'});
 if(r.mapping_version!==contract.mappingVersion||!Object.hasOwn(contract.statusMap,r.raw_status))return {availability:'not_configured',reasonCode:'STATUS_MAPPING_REQUIRED',internalId:r.internal_id,version:r.version};const assessment=r.object_type.startsWith('assessment_');return {internalId:r.internal_id,externalId:r.external_id,source:r.source,version:r.version,label:r.label,availability:contract.statusMap[r.raw_status],mappingVersion:r.mapping_version,mode:contract.mode,fieldStates:assessment?{aggregate:attrs.anonymityPolicyRef&&attrs.visibilityPolicyRef?'producer_policy_required':'not_configured'}:{},attributes:attrs,engineActivated:false};
}
