import {z} from 'zod';
import {HttpError} from './http';
import {authorizeTuple} from './r1-authorization';
import {commitCommand,digest,securityStamp,replayCommand,type CommandIntent} from './r1-command';
import {externalPayloads} from './r1-adapter-contracts';
import {integrationRetryDecision} from './integration-preflight';
import type {memberContext} from './context';
type Context=Awaited<ReturnType<typeof memberContext>>;
const id=z.string().min(1).max(100);
const input=z.object({sourceId:id,sourceRevision:z.number().int().positive(),recipientId:id,orgId:id,payload:z.unknown()}).strict();
export type DeliveryContract={namespace:string;kind:keyof typeof externalPayloads;mode:'simulated';version:string};
export type DeliveryTransport={mode:'simulated';send:(id:string,payload:unknown)=>Promise<{state:'sent'|'unknown'|'failed';receiptId:string|null;payloadDigest?:string;httpStatus?:number;confirmedNoEffect?:boolean;retryAfterSeconds?:number}>;query:(id:string)=>Promise<{state:'sent'|'unknown'|'failed';receiptId:string|null;payloadDigest?:string;confirmedNoEffect?:boolean}>};
export async function prepareDelivery(ctx:Context,intent:CommandIntent,contract:DeliveryContract){
 const c=input.parse(intent.payload),{db,member:m}=ctx,s=await securityStamp(db,m.tenantId);if(contract.mode!=='simulated')throw new HttpError(403,'仅允许隔离模拟适配器','EXTERNAL_MODE_FORBIDDEN');await authorizeTuple(db,m,{objectType:'BASE',action:'integration.deliver',orgId:c.orgId,personId:'',field:'record',historyMode:'current'});const payload=externalPayloads[contract.kind].parse(c.payload),hash=await digest({namespace:contract.namespace,version:contract.version,payload});const replay=await replayCommand(db,m,s,intent);if(replay)return replay;
 const prior=await db.prepare('SELECT id,payload_digest,source_namespace FROM r1_provider_deliveries WHERE tenant_id=? AND source_namespace=? AND source_id=? AND source_revision=? AND recipient_id=?').bind(m.tenantId,contract.namespace,c.sourceId,c.sourceRevision,c.recipientId).first<any>();if(prior&&(prior.payload_digest!==hash||prior.source_namespace!==contract.namespace))throw new HttpError(409,'投递业务键内容冲突','DELIVERY_CONFLICT');const deliveryId=prior?.id??crypto.randomUUID();
 return commitCommand(db,m,s,intent,token=>[db.prepare('INSERT OR IGNORE INTO r1_provider_deliveries(tenant_id,id,source_id,source_revision,recipient_id,state,external_mode,source_namespace,payload,payload_digest,owner_id,org_id) SELECT owner,?,?,?,?,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(deliveryId,c.sourceId,c.sourceRevision,c.recipientId,'pending','simulated',contract.namespace,JSON.stringify(payload),hash,m.userId,c.orgId,m.tenantId,token)],{deliveryId,mode:'simulated',state:'pending'});
}
export async function dispatchDelivery(context:()=>Promise<Context>,deliveryId:string,transport?:DeliveryTransport){
 const ctx=await context(),{db,member:m}=ctx,t=m.tenantId,d=await db.prepare('SELECT * FROM r1_provider_deliveries WHERE tenant_id=? AND id=?').bind(t,deliveryId).first<any>();if(!d)throw new HttpError(404,'投递不存在','NOT_FOUND');await authorizeTuple(db,m,{objectType:'BASE',action:'integration.deliver',orgId:d.org_id,personId:'',field:'record',historyMode:'current'});
 if(!transport)return {state:d.state==='unknown'?'unknown':'not_configured',mode:'disabled'};if(d.external_mode!=='simulated'||transport.mode!=='simulated')throw new HttpError(403,'禁止真实外发','EXTERNAL_MODE_FORBIDDEN');if(d.state==='sent'||d.state==='dead_letter')return {state:d.state,mode:'simulated'};
 const update=async(state:string,expected:string,receiptId:string|null,attempt=0,next:number|null=null,reason:string|null=null)=>{const current=await context(),s=await securityStamp(db,t),key=crypto.randomUUID();await authorizeTuple(db,current.member,{objectType:'BASE',action:'integration.deliver',orgId:d.org_id,personId:'',field:'record',historyMode:'current'});return commitCommand(db,current.member,s,{commandId:key,idempotencyKey:key,action:'BASE.deliveryState',payload:{deliveryId,state,receiptId},expectedWorkspaceRevision:current.row.revision,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch},token=>[
 db.prepare('INSERT INTO r1_adapter_guard SELECT owner,?,CASE WHEN EXISTS(SELECT 1 FROM r1_provider_deliveries WHERE tenant_id=? AND id=? AND state=? AND attempt=?) THEN 1 ELSE 0 END FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(key,t,deliveryId,expected,d.attempt,t,token),
 db.prepare('UPDATE r1_provider_deliveries SET state=?,receipt_id=?,attempt=attempt+?,next_attempt_at=?,reason_code=? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(state,receiptId,attempt,next,reason,t,deliveryId,t,token)],{deliveryId,state});};
 if(d.state==='unknown'){const r=await transport.query(deliveryId);if(r.state==='unknown')return {...r,action:'query_receipt',mode:'simulated'};if(!r.receiptId||r.payloadDigest!==d.payload_digest)throw new HttpError(409,'缺少原回执或摘要不匹配','RECEIPT_REQUIRED');if(r.state==='failed'&&!r.confirmedNoEffect)return {state:'unknown',action:'query_receipt',mode:'simulated'};await update(r.state,'unknown',r.receiptId,0,r.state==='failed'?Date.now():null,r.state==='failed'?'CONFIRMED_NO_EFFECT':null);return {...r,action:'query_receipt',mode:'simulated'};}
 if(d.state==='failed'&&d.reason_code!=='CONFIRMED_NO_EFFECT')throw new HttpError(409,'先核对供应商是否已执行','RECEIPT_REQUIRED');if(d.next_attempt_at&&d.next_attempt_at>Date.now())return {state:d.state,nextAttemptAt:d.next_attempt_at,mode:'simulated'};
 if(d.attempt>=6){await update('dead_letter',d.state,d.receipt_id,0,null,'ATTEMPT_LIMIT');return {state:'dead_letter',ownerId:d.owner_id,nextAction:'reconcile_original_receipt',closeGate:'external_chain_acceptance',mode:'simulated'};}
 const claim=await update('unknown',d.state,d.receipt_id,1),current=await context();if(current.row.revision!==claim.workspaceRevision)throw new HttpError(409,'领取后数据变化，查询原投递','REVISION_CONFLICT');await authorizeTuple(db,current.member,{objectType:'BASE',action:'integration.deliver',orgId:d.org_id,personId:'',field:'record',historyMode:'current'});d.attempt++;let r;try{r=await transport.send(deliveryId,JSON.parse(d.payload));}catch{return {state:'unknown',action:'query_receipt',mode:'simulated'};}
 if(r.state!=='unknown'&&r.payloadDigest!==d.payload_digest)throw new HttpError(409,'回执摘要不匹配','RECEIPT_CONFLICT');if(r.state==='sent'){if(!r.receiptId)throw new HttpError(409,'缺少投递回执','RECEIPT_REQUIRED');await update('sent','unknown',r.receiptId);}
 else if(r.state==='failed'&&r.confirmedNoEffect){const retry=integrationRetryDecision(d.attempt,r.httpStatus,r.retryAfterSeconds);await update(retry.retry?'failed':'dead_letter','unknown',r.receiptId,0,retry.retry?Date.now()+retry.delaySeconds*1000:null,retry.retry?'CONFIRMED_NO_EFFECT':'REQUIRES_DIAGNOSIS');}
 const stored=await db.prepare('SELECT state,next_attempt_at FROM r1_provider_deliveries WHERE tenant_id=? AND id=?').bind(t,deliveryId).first<any>();return {...r,state:stored.state,nextAttemptAt:stored.next_attempt_at,mode:'simulated'};
}
