import {makeEnvelope,type EventEnvelope} from './r1-integration';
import type {CommandIntent} from './r1-command';
import type {Entity} from './r1-m01';
type DomainInput={source:string;eventType:string;internalId:string;entityRevision:number;definitionVersion:string;payload:EventEnvelope['payload']};
async function envelope(tenant:string,intent:CommandIntent,input:DomainInput){const at=new Date().toISOString();return makeEnvelope({tenantId:tenant,schemaVersion:1,eventId:crypto.randomUUID(),eventType:input.eventType,source:input.source,internalId:input.internalId,externalId:null,entityRevision:input.entityRevision,workspaceRevision:intent.expectedWorkspaceRevision+1,definitionVersion:input.definitionVersion,sourceRevision:intent.expectedWorkspaceRevision,sequence:input.entityRevision,mappingVersion:1,occurredAt:at,effectiveAt:at,correlationId:intent.correlationId??intent.commandId,causationId:intent.causationId??intent.commandId,digestAlgorithm:'sha256-canonical-json-v1',payload:input.payload});}
function insert(db:D1Database,tenant:string,intent:CommandIntent,events:EventEnvelope[]){return(token:string)=>events.length?[db.prepare("INSERT INTO r1_outbox(tenant_id,event_id,command_id,event_type,workspace_revision,payload) SELECT w.owner,json_extract(e.value,'$.eventId'),?,json_extract(e.value,'$.eventType'),w.revision,e.value FROM hris_workspaces w,json_each(?) e WHERE w.owner=? AND w.last_mutation=?").bind(intent.commandId,JSON.stringify(events),tenant,token)]:[];}
export async function domainEventPlan(db:D1Database,tenant:string,intent:CommandIntent,input:DomainInput){return insert(db,tenant,intent,[await envelope(tenant,intent,input)]);}
/** One bounded SQL statement keeps the existing 20-row cleanup transaction below its statement budget. */
export async function m01DomainEvents(db:D1Database,tenant:string,intent:CommandIntent,changes:Entity[]){const events=await Promise.all(changes.map(e=>envelope(tenant,intent,{source:'M01',eventType:['org','position','job','job_family','grade','legal_entity'].includes(e.kind)?'catalog.version_published':e.kind==='assignment'?'assignment.applied':e.kind==='employment'&&e.status==='ended'?'employment.ended':'record.changed',internalId:e.id,entityRevision:e.revision,definitionVersion:e.kind+'-r1-v1',payload:{...(e.personId?{personId:e.personId}:{}),...(e.kind==='assignment'?{assignmentVersionId:e.id+':'+e.revision}:{})}})));return insert(db,tenant,intent,events);}
