export const personnelKinds={regularize_request:'转正原单',person:'人员',employment:'雇佣段',assignment:'任职',assignment_request:'任职申请',exit_request:'退出申请',contract:'合同',org:'组织',position:'职位',job:'职务',job_family:'职类',grade:'职级',legal_entity:'法人',contract_field:'合同字段',template:'人员模板',subset:'人员子集',identity_review:'身份核对'};
export const personnelOperations={regularizeRequest:'转正申请',assignmentCancel:'取消任职原单',exitCancel:'取消退出原单',transfer:'发起两级调动',transferWorkflow:'配置两级调动审核人',person:'新增人员草稿',identityReview:'核对历史身份',identityBind:'登记身份线索',employment:'新建雇佣段',assignmentRequest:'申请任职',exitRequest:'申请退出',contract:'登记合同',contractField:'配置合同字段',template:'发布人员模板',subsetImport:'导入一条子集记录',catalog:'发布目录版本',contractSign:'登记人工签署凭据',contractEnd:'独立办理合同终止'};
export const formFields:Record<string,string[]>={regularizeRequest:['personId','orgId','reason'],
 assignmentCancel:['reason'],exitCancel:['reason'],transfer:['personId','orgId','positionId','gradeId','effectiveOn','intent','previousApprovalId','reason'],transferWorkflow:['reviewerOutId','reviewerInId'],contractSign:['signedOn','evidence'],contractEnd:['endedOn','evidence'],person:['orgId','code','name','entryType','templateId'],identityReview:['personId','identifierType','identifierValue','reason','evidenceRef'],identityBind:['personId','identifierType','identifierValue','evidenceRef'],employment:['personId','identityReviewId','predecessorId','startOn','employmentType'],assignmentRequest:['personId','employmentId','orgId','positionId','gradeId','type','homePrimaryId','validFrom','validTo','reviewerId','reason','endAssignmentId','replacesAssignmentId'],exitRequest:['personId','lastWorkingOn','reviewerId','reason'],contract:['personId','legalEntityId','number','agreementCategory','contractType','start','end','renewalOf'],contractField:['orgId','code','name','inheritPrevious','status'],template:['orgId','kind','entryType'],subsetImport:['personId','templateId','batchId','rowNo','attemptVersion','mode','recordId'],catalog:['kind','id','closePreviousVersion','code','name','orgId','parentId','status','validFrom','validTo','city','sequence','establishedOn','familyId','gradeMinId','gradeMaxId','responsibilities','newType','scopeOrgId']};
export type FormEntity={id:string;kind:string;orgId:string|null;personId:string|null;code:string|null;revision:number;status:string;payload:Record<string,any>;allowedActions?:string[]};
export function personnelPayload(operation:string,form:Record<string,string>,lists:Record<string,FormEntity[]>,values:Record<string,unknown>,templateFields:unknown[]){
 const nullable=(k:string)=>form[k]||null,person=lists.person?.find(e=>e.id===form.personId),orgId=form.orgId||person?.orgId||'';
 const base={operation};
 switch(operation){
 case 'regularizeRequest':return {...base,personId:form.personId,orgId,reason:form.reason};
 case 'assignmentCancel':case 'exitCancel':return {...base,id:form.id,reason:form.reason};
 case 'transfer':return {operation:'transfer',command:{action:'request',kind:'transfer',employeeId:form.personId,orgId,positionId:nullable('positionId'),gradeId:nullable('gradeId'),effectiveOn:form.effectiveOn,intent:form.intent||'independent',...(form.previousApprovalId?{previousApprovalId:form.previousApprovalId}:{}),reason:form.reason}};
 case 'transferWorkflow':return {operation:'transfer',command:{action:'workflow',kind:'transfer',steps:[{userId:form.reviewerOutId,name:'调出审批人'},{userId:form.reviewerInId,name:'调入审批人'}]}};
 case 'contractSign':return {...base,id:form.id,signedOn:form.signedOn,evidence:form.evidence};
 case 'contractEnd':return {...base,id:form.id,endedOn:form.endedOn,evidence:form.evidence};
 case 'person':return {...base,orgId,code:form.code,name:form.name,entryType:form.entryType,templateId:form.templateId,fields:values};
 case 'identityReview':return {...base,personId:form.personId,candidateIds:[form.personId],identifiers:[{type:form.identifierType,value:form.identifierValue}],reason:form.reason,evidenceRef:form.evidenceRef};
 case 'identityBind':return {...base,personId:form.personId,orgId,identifiers:[{type:form.identifierType,value:form.identifierValue}],evidenceRef:form.evidenceRef};
 case 'employment':return {...base,personId:form.personId,orgId,identityReviewId:form.identityReviewId,predecessorId:nullable('predecessorId'),startOn:form.startOn,employmentType:form.employmentType};
 case 'assignmentRequest':return {...base,personId:form.personId,orgId,employmentId:form.employmentId,positionId:form.positionId,gradeId:nullable('gradeId'),type:form.type,homePrimaryId:nullable('homePrimaryId'),validFrom:form.validFrom,validTo:nullable('validTo'),reviewerId:form.reviewerId,reason:form.reason,...(form.endAssignmentId?{endAssignmentId:form.endAssignmentId}:{}),...(form.replacesAssignmentId?{replacesAssignmentId:form.replacesAssignmentId}:{})};
 case 'exitRequest':return {...base,personId:form.personId,orgId,lastWorkingOn:form.lastWorkingOn,reviewerId:form.reviewerId,reason:form.reason};
 case 'contract':return {...base,...(form.id?{id:form.id}:{}),personId:form.personId,orgId,legalEntityId:form.legalEntityId,number:form.number,agreementCategory:form.agreementCategory,contractType:form.contractType,start:form.start,end:nullable('end'),renewalOf:nullable('renewalOf'),fields:values};
 case 'contractField':return {...base,...(form.id?{id:form.id}:{}),orgId,code:form.code,name:form.name,inheritPrevious:form.inheritPrevious==='true',status:form.status};
 case 'template':return {...base,...(form.id?{id:form.id}:{}),orgId,kind:form.kind,entryType:form.entryType,fields:templateFields};
 case 'subsetImport':return {...base,personId:form.personId,orgId,templateId:form.templateId,templateVersion:lists.template?.find(t=>t.id===form.templateId)?.revision??0,batchId:form.batchId,rowNo:Number(form.rowNo),attemptVersion:Number(form.attemptVersion),mode:form.mode,recordId:nullable('recordId'),fields:values};
 case 'catalog':return {...base,...(form.id?{id:form.id}:{}),...(form.closePreviousVersion?{closePreviousVersion:Number(form.closePreviousVersion)}:{}),kind:form.kind,code:form.code,name:form.name,orgId,parentId:form.parentId??'',status:form.status,validFrom:form.validFrom,validTo:nullable('validTo'),attributes:{...(form.city?{city:form.city}:{}),...(form.sequence?{sequence:Number(form.sequence)}:{}),...(form.establishedOn?{establishedOn:form.establishedOn}:{}),...(form.familyId?{familyId:form.familyId}:{}),...(form.gradeMinId?{gradeMinId:form.gradeMinId}:{}),...(form.gradeMaxId?{gradeMaxId:form.gradeMaxId}:{}),...(form.responsibilities?{responsibilities:form.responsibilities}:{}),...(form.newType?{newType:form.newType}:{}),...(form.scopeOrgId?{orgIds:[form.scopeOrgId]}:{})}};
 default:throw Error('请选择办理事项');
 }
}
