import {homeworkTaskOpen,canReviewHomework} from '@/lib/hris/learning-homework';
import {examTaskOpen} from '@/lib/hris/learning-exam-tasks';
import {learningTaskDisplayDue,learningStageSubmissionOpen,learningStageOpen} from '@/lib/hris/learning-requirements';
import {learningTaskOpen} from '@/lib/hris/learning-plan-model';
import {performancePlanLive} from '@/lib/hris/performance-availability';
import {businessDate} from '@/lib/hris/workforce';
import {developmentContext,visibleDevelopment,type DevelopmentContext} from '@/lib/hris/development-repository';
import {visibleState} from '@/lib/hris/authorization';
export function legacySelfService(ctx:DevelopmentContext){
 const state=visibleState(ctx.state,ctx.member),all=visibleDevelopment(ctx),records=all.filter(r=>r.employeeId===ctx.member.employeeId),employee=state.employees.find(e=>e.id===ctx.member.employeeId)??null;
 const livePerformance=(r:typeof records[number])=>performancePlanLive(ctx.state,ctx.records,r)&&r.status==='confirmed'&&all.some(c=>c.kind==='performanceCycle'&&c.id===r.referenceId&&c.status==='active')&&!all.some(c=>c.kind==='performance'&&c.payload.sourcePlanId===r.id);
 const pendingChange=(id:string)=>records.some(c=>c.kind==='performanceGoalChange'&&c.referenceId===id&&c.status==='submitted');
 const tasks=records.filter(r=>(['cadreObservation','plan','enrollment'].includes(r.kind)&&['active','returned'].includes(r.status)&&(r.kind==='cadreObservation'||employee?.status!=='离职')&&learningTaskOpen(r,employee)&&learningStageSubmissionOpen(r,all)&&learningStageOpen(r,all,undefined,state))||(r.kind==='performancePlan'&&livePerformance(r)&&!pendingChange(r.id))).map(r=>({id:r.id,title:r.payload.title??(r.kind==='performancePlan'?`${r.payload.period} 绩效自评`:r.kind==='cadreObservation'?'任职考察述职':'发展行动'),due:learningTaskDisplayDue(r,all),kind:r.kind,href:r.kind==='cadreObservation'?'/cadres':r.kind==='enrollment'?'/learning':r.kind==='performancePlan'?'/performance?'+new URLSearchParams({recordId:r.id}):'/development'}));
 for(const r of all.filter(r=>r.kind==='homeworkTask'&&(r.employeeId===ctx.member.employeeId&&homeworkTaskOpen(r,ctx.state,undefined,ctx.records)||canReviewHomework(r,ctx.state,ctx.member,ctx.records))))tasks.push({id:r.id,title:(r.payload.title??'独立作业')+(r.status==='submitted'?' · 待批阅':''),due:learningTaskDisplayDue(r,all),kind:r.kind,href:'/learning-homework'});
 for(const r of records.filter(r=>r.kind==='learningExamTask'&&examTaskOpen(r,state)&&learningStageSubmissionOpen(r,all)&&learningStageOpen(r,all,undefined,state)))tasks.push({id:r.id,title:r.payload.title??'独立考试',due:learningTaskDisplayDue(r,all),kind:r.kind,href:'/learning-exam-tasks'});
 for(const r of records.filter(r=>r.kind==='performanceCheckin'&&r.status==='returned'&&r.createdBy===ctx.member.userId)){const p=all.find(p=>p.id===r.referenceId&&p.kind==='performancePlan');if(p&&livePerformance(p)&&employee?.status!=='离职'&&(p.payload.version??1)===r.payload.basePlanVersion&&!pendingChange(p.id))tasks.push({id:r.id,title:(r.payload.period??'')+' 补充目标跟进',due:'',kind:r.kind,href:'/performance-checkins'});}
 for(const r of all.filter(r=>r.kind==='surveyRound'&&!!employee&&employee.status!=='离职'&&r.status==='open'&&r.payload.start!<=businessDate()&&r.payload.end!>=businessDate()&&ctx.records.find(x=>x.id===r.id)?.payload.participantIds?.includes(ctx.member.employeeId??'')&&!records.some(x=>x.kind==='surveyResponse'&&x.referenceId===r.id&&x.status==='submitted')))tasks.push({id:r.id,title:r.payload.name??'实名问卷',due:r.payload.end??'',kind:r.kind,href:'/surveys'});
 for(const r of records.filter(r=>r.kind==='feedbackInvite'&&!!employee&&employee.status!=='离职'&&r.status==='assigned')){const p=all.find(x=>x.id===r.referenceId&&x.kind==='feedbackProject');if(p?.status==='open'&&p.payload.start!<=businessDate()&&p.payload.end!>=businessDate()&&!records.some(x=>x.kind==='feedbackReply'&&x.referenceId===r.id))tasks.push({id:r.id,title:(r.payload.subjectName??'同事')+' · 360反馈',due:p.payload.end??'',kind:r.kind,href:'/feedback'});}
 for(const r of records.filter(r=>r.kind==='onboardingPlan'&&r.status==='active'&&r.payload.onboardingItems?.some(x=>['pending','returned'].includes(x.status))))tasks.push({id:r.id,title:r.payload.title??'入职融入计划',due:learningTaskDisplayDue(r,all),kind:r.kind,href:'/onboarding'});
 const requests=records.filter(r=>['performanceGoalChange','trainingRequest','leave','correction','performanceAppeal','payQuery'].includes(r.kind)||r.kind==='employeeFieldValue'&&r.payload.submittedBy===ctx.member.userId).map(r=>({id:r.id,kind:r.kind,title:r.kind==='performanceGoalChange'?r.payload.period+' 目标调整':r.kind==='trainingRequest'?(r.payload.title+' 培训申请'):r.kind==='leave'?'请假申请':r.kind==='correction'?'补卡申请':r.kind==='performanceAppeal'?r.payload.period+' 绩效申诉':r.kind==='payQuery'?r.payload.period+' 工资条异议':r.payload.name+' 字段变更',status:r.kind==='performanceAppeal'?(records.some(x=>x.kind==='performance'&&x.payload.appealId===r.id)?'corrected':r.status==='approved'?'awaiting_publish':r.status):r.kind==='employeeFieldValue'?(r.status==='pending'?'pending':'processed'):r.status,at:r.updatedAt,href:r.kind==='performanceGoalChange'?'/performance-changes':r.kind==='trainingRequest'?'/training-requests':r.kind==='payQuery'?'/payroll-adjustments':r.kind==='performanceAppeal'?'/performance':r.kind==='employeeFieldValue'?'/employee-fields':'/attendance'}));
 return {employee,tasks,requests,payslipCount:records.filter(r=>r.kind==='paySlip'&&r.status!=='cancelled'&&ctx.records.some(b=>b.id===r.referenceId&&b.status==='published')).length,revision:ctx.row.revision};
}

