import {z} from 'zod';
import {HttpError} from './http';
import {commitMigrationTransaction,replayCommand,type CommandIntent} from './r1-command';
import {rowDigest} from './r1-migration-map';
import type {MigrationContext} from './r1-migration-context';
export type MigrationObjectReader={get(key:string):Promise<Uint8Array|null>};
export async function byteDigest(bytes:Uint8Array){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as Uint8Array<ArrayBuffer>))].map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function verifyMigrationAttachments(ctx:MigrationContext,intent:CommandIntent,objects:MigrationObjectReader){const c=z.object({operation:z.literal('verifyAttachments'),ids:z.array(z.string().min(1).max(100)).min(1).max(100)}).strict().parse(intent.payload),prior=await replayCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent);if(prior)return prior;const rows:any[]=[],t=ctx.member.tenantId,at=new Date().toISOString();for(const id of new Set(c.ids)){const row=await ctx.db.prepare('SELECT * FROM hris_attachments WHERE tenant_id=? AND id=?').bind(t,id).first<any>();if(!row)throw new HttpError(404,'附件引用不存在','ATTACHMENT_NOT_FOUND');const prior=await ctx.db.prepare('SELECT digest FROM r1_attachment_integrity WHERE tenant_id=? AND attachment_id=?').bind(t,id).first<{digest:string}>();let bytes:Uint8Array|null=null,reason:string|null=null;try{if(row.size>10*1024*1024)reason='ATTACHMENT_SIZE_BUDGET';else bytes=await objects.get(row.object_key);}catch{reason='OBJECT_UNAVAILABLE';}if(!bytes&&!reason)reason='OBJECT_MISSING';if(bytes&&bytes.byteLength!==row.size)reason='OBJECT_SIZE_MISMATCH';const hash=bytes?await byteDigest(bytes):null;if(prior?.digest&&hash&&prior.digest!==hash)reason='OBJECT_HASH_MISMATCH';rows.push({id,key:row.object_key,hash:reason?prior?.digest??hash:hash,bytes:bytes?.byteLength??null,status:reason?'quarantined':'verified',reason,sourceDigest:await rowDigest('hris_attachments',{...row})});}
 return commitMigrationTransaction(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>[ctx.db.prepare("INSERT INTO r1_attachment_integrity SELECT w.owner,json_extract(j.value,'$.id'),json_extract(j.value,'$.key'),json_extract(j.value,'$.hash'),json_extract(j.value,'$.bytes'),json_extract(j.value,'$.status'),json_extract(j.value,'$.reason'),?,json_extract(j.value,'$.sourceDigest') FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=? ON CONFLICT(tenant_id,attachment_id) DO UPDATE SET object_key=excluded.object_key,digest=excluded.digest,byte_count=excluded.byte_count,status=excluded.status,reason_code=excluded.reason_code,observed_at=excluded.observed_at,source_digest=excluded.source_digest").bind(at,JSON.stringify(rows),t,token)],{verified:rows.filter(r=>r.status==='verified').length,quarantined:rows.filter(r=>r.status==='quarantined').length},{storageVersion:1});
}
export async function requireAttachmentIntegrity(db:D1Database,tenant:string,id:string){const r=await db.prepare('SELECT status,digest FROM r1_attachment_integrity WHERE tenant_id=? AND attachment_id=?').bind(tenant,id).first<{status:string;digest:string}>();if(r&&r.status!=='verified')throw new HttpError(409,'附件完整性未确认，已隔离','ATTACHMENT_QUARANTINED');return r;}
