import {z} from 'zod';
import {HttpError} from './http';
import {commitMigrationTransaction,digest,canonical,replayCommand,type CommandIntent} from './r1-command';
import {checkMigrationSchema,migrationSource,sourceKeySql} from './r1-schema-check';
import {normalizeJsonRows,normalizationOrder,deterministicMigrationId} from './r1-normalize-json';
import type {MigrationContext} from './r1-migration-context';
const id=z.string().min(1).max(100),input=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('begin'),id,sourceSha:z.string().regex(/^[0-9a-f]{40}$/),worker:id}).strict(),
 z.object({operation:z.literal('claim'),id,worker:id,expectedRevision:z.number().int().positive()}).strict(),
 z.object({operation:z.literal('normalize'),id,worker:id,fencingToken:z.number().int().positive(),expectedRevision:z.number().int().positive()}).strict()
]);
export const migrationPlanVersion='r1-migration-v1';
export async function migrationRun(ctx:MigrationContext,id:string){const r=await ctx.db.prepare('SELECT * FROM r1_migration_runs WHERE tenant_id=? AND id=?').bind(ctx.member.tenantId,id).first<any>();if(!r)throw new HttpError(404,'迁移运行不存在','MIGRATION_NOT_FOUND');return r;}
export function assertMigrationLease(run:any,worker:string,fence:number,revision:number){if(run.lease_owner!==worker||run.fencing_token!==fence||run.revision!==revision||run.lease_until<=Date.now())throw new HttpError(409,'迁移租约或检查点版本已变化','MIGRATION_FENCE_STALE');}
export const guardedMigrationStatement=(ctx:MigrationContext,sql:string,args:unknown[])=>(token:string)=>ctx.db.prepare(sql).bind(...args,ctx.member.tenantId,token);
export function migrationFenceStatement(ctx:MigrationContext,run:any,token:string){return ctx.db.prepare("INSERT INTO r1_adapter_guard SELECT owner,?,CASE WHEN EXISTS(SELECT 1 FROM r1_migration_runs WHERE tenant_id=? AND id=? AND revision=? AND fencing_token=? AND lease_until>CAST((julianday('now')-2440587.5)*86400000 AS INTEGER)) THEN 1 ELSE 0 END FROM hris_workspaces WHERE owner=? AND last_mutation=?").bind(token,ctx.member.tenantId,run.id,run.revision,run.fencing_token,ctx.member.tenantId,token);}
export async function migrationCommand(ctx:MigrationContext,intent:CommandIntent){const c=input.parse(intent.payload),t=ctx.member.tenantId,db=ctx.db;
 if(c.operation==='begin'){
  const schema=await checkMigrationSchema(db),old=await db.prepare('SELECT * FROM r1_migration_runs WHERE tenant_id=? AND id=?').bind(t,c.id).first<any>();if(old){if(old.source_sha!==c.sourceSha||old.ddl_digest!==schema.ddlDigest)throw new HttpError(409,'迁移运行键冲突','IDEMPOTENCY_CONFLICT');return {runId:old.id,phase:old.phase,revision:old.revision,replayed:true};}if(ctx.member.securityStamp!.featuresEnabled)throw new HttpError(409,'新能力已启用，需前向核验不能重新回填','MIGRATION_ALREADY_SWITCHED');if(ctx.row.legacyBytes>4*1024*1024&&ctx.row.storageVersion===0)throw new HttpError(413,'旧JSON超过单租户安全解析预算，需分区提取器','LEGACY_JSON_BUDGET');const phase=ctx.row.storageVersion===0?'normalizing':'backfilling',epoch=ctx.member.securityStamp!.writerEpoch+1;let hash:string|null=null;
  if(ctx.row.storageVersion===0){const row=await db.prepare('SELECT data FROM hris_workspaces WHERE owner=?').bind(t).first<{data:string}>();let parsed;try{parsed=JSON.parse(row!.data);}catch{throw new HttpError(409,'旧JSON无法解析','LEGACY_JSON_INVALID');}normalizeJsonRows(parsed,t);hash=await digest(parsed);}
  return commitMigrationTransaction(db,ctx.member,ctx.member.securityStamp!,intent,token=>[
   db.prepare("INSERT INTO r1_migration_runs(tenant_id,id,plan_version,source_sha,ddl_digest,phase,revision,writer_epoch,lease_owner,lease_until,fencing_token,source_table,cursor,rows_observed,manifest_digest,reason_code,created_at) SELECT owner,?,?,?,?,?,1,?,?,?,1,?,'',0,NULL,NULL,? FROM hris_workspaces WHERE owner=? AND last_mutation=?").bind(c.id,migrationPlanVersion,c.sourceSha,schema.ddlDigest,phase,epoch,c.worker,Date.now()+60000,phase==='normalizing'?normalizationOrder[0]:'hris_orgs',new Date().toISOString(),t,token),
   ...(hash?[db.prepare('INSERT INTO r1_migration_archives SELECT owner,?,revision-1,?,data,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(c.id,hash,new Date().toISOString(),t,token)]:[])
  ],{runId:c.id,phase,revision:1,fencingToken:1,writerEpoch:epoch},{storageVersion:ctx.row.storageVersion as 0|1,control:{phase:phase==='normalizing'?'writers_guarded':'backfilling',featuresEnabled:0,bumpWriterEpoch:true}});
 }
 const run=await migrationRun(ctx,c.id),prior=await replayCommand(db,ctx.member,ctx.member.securityStamp!,intent);if(prior)return prior;
 if(c.operation==='claim'){
  if(run.revision!==c.expectedRevision||run.lease_until>Date.now()||!['normalizing','backfilling','reconciling','paused'].includes(run.phase))throw new HttpError(409,'迁移已被领取或状态不允许接管','MIGRATION_LEASE_CONFLICT');return commitMigrationTransaction(db,ctx.member,ctx.member.securityStamp!,intent,token=>[db.prepare('UPDATE r1_migration_runs SET lease_owner=?,lease_until=?,fencing_token=fencing_token+1,revision=revision+1 WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(c.worker,Date.now()+60000,t,c.id,t,token)],{runId:c.id,fencingToken:run.fencing_token+1,revision:run.revision+1},{storageVersion:ctx.row.storageVersion as 0|1});
 }
 assertMigrationLease(run,c.worker,c.fencingToken,c.expectedRevision);if(run.phase!=='normalizing'||ctx.row.storageVersion!==0)throw new HttpError(409,'此运行不处于旧JSON规范化阶段','MIGRATION_PHASE_CONFLICT');const archive=await db.prepare('SELECT * FROM r1_migration_archives WHERE tenant_id=? AND id=?').bind(t,c.id).first<any>(),source=await db.prepare('SELECT data FROM hris_workspaces WHERE owner=?').bind(t).first<{data:string}>();if(!archive||await digest(JSON.parse(source!.data))!==archive.source_digest)throw new HttpError(409,'归档后旧JSON发生变化','MIGRATION_SOURCE_CONFLICT');const normalized=normalizeJsonRows(JSON.parse(archive.source_json),t),table=run.source_table,index=normalizationOrder.indexOf(table),offset=run.cursor?Number(run.cursor):0;if(index<0||!Number.isSafeInteger(offset)||offset<0)throw new HttpError(409,'规范化游标无效','MIGRATION_CURSOR_INVALID');const rows=normalized.tables[table].slice(offset,offset+100),schema=migrationSource(table),key=(r:any)=>JSON.stringify(schema.keys.map(k=>r[k])),keys=rows.map(key),existing=(await db.prepare('SELECT * FROM "'+table+'" s WHERE s."'+schema.tenantColumn+'"=? AND '+sourceKeySql(schema.keys)+' IN (SELECT value FROM json_each(?))').bind(t,JSON.stringify(keys)).all<any>()).results;
 for(const row of existing){const expected=rows.find(r=>key(r)===key(row));if(expected&&canonical({...row})!==canonical(expected))throw new HttpError(409,'已存在规范化记录与归档不一致','LEGACY_NORMALIZATION_CONFLICT');}
 const nextOffset=offset+rows.length,tableDone=nextOffset===normalized.tables[table].length,complete=tableDone&&index===normalizationOrder.length-1,nextTable=tableDone?normalizationOrder[index+1]??'hris_orgs':table,batchId=await deterministicMigrationId('normalize',c.id+':'+table+':'+offset),hash=await digest(rows),plans:((token:string)=>D1PreparedStatement)[]=[];
 plans.push(token=>migrationFenceStatement(ctx,run,token));if(rows.length)plans.push(token=>db.prepare('INSERT OR IGNORE INTO "'+table+'"('+schema.columns.map(c=>'"'+c+'"').join(',')+') SELECT '+schema.columns.map(c=>"json_extract(j.value,'$."+c+"')").join(',')+' FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=?').bind(JSON.stringify(rows),t,token));
 plans.push(token=>db.prepare('INSERT INTO r1_migration_batches SELECT owner,?,?,?,?,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(batchId,c.id,'normalize:'+table,String(offset),String(offset),String(nextOffset),rows.length,hash,hash,c.fencingToken,intent.commandId,t,token));
 const rowIds=new Set(rows.map((r:any)=>r.employee_id??r.approval_id));const batchIssues=await Promise.all(normalized.issues.filter(issue=>issue.table===table&&rowIds.has(JSON.parse(issue.key)[0])).map(async issue=>({id:await deterministicMigrationId('issue',issue.table+issue.key+issue.reason),table:issue.table,key:issue.key,reason:issue.reason,detail:JSON.stringify({source:'archived_json',rule:'do_not_guess_missing_ids'})})));
 if(batchIssues.length)plans.push(token=>db.prepare("INSERT OR IGNORE INTO r1_migration_issues SELECT w.owner,json_extract(j.value,'$.id'),json_extract(j.value,'$.table'),json_extract(j.value,'$.key'),NULL,json_extract(j.value,'$.reason'),'open',1,NULL,NULL,json_extract(j.value,'$.detail') FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=?").bind(JSON.stringify(batchIssues),t,token));
 plans.push(token=>db.prepare('UPDATE r1_migration_runs SET source_table=?,cursor=?,rows_observed=rows_observed+?,revision=revision+1,lease_until=?,phase=? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(nextTable,tableDone?'':String(nextOffset),rows.length,Date.now()+60000,complete?'backfilling':'normalizing',t,c.id,t,token));
 return commitMigrationTransaction(db,ctx.member,ctx.member.securityStamp!,intent,token=>plans.map(p=>p(token)),{runId:c.id,phase:complete?'backfilling':'normalizing',revision:run.revision+1,batchId,rows:rows.length},{storageVersion:0,normalizeComplete:complete,...(complete?{control:{phase:'backfilling',featuresEnabled:0,bumpWriterEpoch:false}}:{})});
}
