import {z} from 'zod';
import {HttpError} from './http';
import {commitMigrationTransaction,digest,replayCommand,type CommandIntent} from './r1-command';
import {migrationRun,assertMigrationLease,migrationFenceStatement,migrationPlanVersion} from './r1-migration';
import {backfillOrder} from './r1-migration-backfill';
import {migrationSource,sourceKeySql,checkMigrationSchema} from './r1-schema-check';
import {mapLegacySource,rowDigest} from './r1-migration-map';
import type {MigrationContext} from './r1-migration-context';
const id=z.string().min(1).max(100),base={id,worker:id,fencingToken:z.number().int().positive(),expectedRevision:z.number().int().positive()};
const input=z.discriminatedUnion('operation',[
 z.object({...base,operation:z.literal('reconcile'),table:z.enum(backfillOrder as [string,...string[]])}).strict(),
 z.object({...base,operation:z.literal('rescan')}).strict(),
 z.object({...base,operation:z.literal('switchRead')}).strict(),
 z.object({...base,operation:z.literal('rollback'),reason:z.string().min(1).max(500)}).strict()
]);
export async function sourceWatermark(ctx:MigrationContext){return (await ctx.db.prepare('SELECT migration_source_revision n FROM r1_schema_state WHERE tenant_id=?').bind(ctx.member.tenantId).first<{n:number}>())!.n;}
/** Every page compares source keys and complete mapped object payloads, never just counts. */
export async function reconcileMigration(ctx:MigrationContext,intent:CommandIntent){const c=input.parse(intent.payload),run=await migrationRun(ctx,c.id),db=ctx.db,t=ctx.member.tenantId,replay=await replayCommand(db,ctx.member,ctx.member.securityStamp!,intent);if(replay)return replay;assertMigrationLease(run,c.worker,c.fencingToken,c.expectedRevision);const plans:((token:string)=>D1PreparedStatement)[]=[token=>migrationFenceStatement(ctx,run,token)];let result:Record<string,unknown>={runId:c.id,revision:run.revision+1},phase=run.phase,features=ctx.member.securityStamp!.featuresEnabled as 0|1,bump=false;
 if(c.operation==='rollback'){if(!['backfilling','reconciling','read_switched'].includes(run.phase))throw new HttpError(409,'阶段不允许回滚','MIGRATION_PHASE_CONFLICT');phase='rolled_back';features=0;bump=true;result={...result,phase,compatibility:'read_only',reason:c.reason};
 }else if(c.operation==='rescan'){if(run.phase!=='reconciling')throw new HttpError(409,'只允许对账阶段重新扫描','MIGRATION_PHASE_CONFLICT');phase='backfilling';plans.push(token=>db.prepare('DELETE FROM r1_migration_reconciliation WHERE tenant_id=? AND run_id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(t,c.id,t,token));plans.push(token=>db.prepare("UPDATE r1_migration_runs SET scan_generation=scan_generation+1,source_table='hris_orgs',cursor='' WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(t,c.id,t,token));result={...result,phase,scanGeneration:run.scan_generation+1};
 }else if(c.operation==='switchRead'){
  if(run.phase!=='reconciling')throw new HttpError(409,'尚未完成回填与对账','MIGRATION_PHASE_CONFLICT');await checkMigrationSchema(db);const watermark=await sourceWatermark(ctx),checks=(await db.prepare('SELECT * FROM r1_migration_reconciliation WHERE tenant_id=? AND run_id=?').bind(t,c.id).all<any>()).results;if(backfillOrder.some(table=>!checks.some(r=>r.source_table===table&&r.completed===1&&r.difference_count===0&&r.source_revision===watermark)))throw new HttpError(409,'逐表逐键对账不完整或源已变化','MIGRATION_RECONCILIATION_REQUIRED');
  const attachments=await db.prepare("SELECT count(*) n FROM hris_attachments a LEFT JOIN r1_attachment_integrity i ON i.tenant_id=a.tenant_id AND i.attachment_id=a.id WHERE a.tenant_id=? AND (i.attachment_id IS NULL OR i.status NOT IN ('verified','quarantined') OR i.source_digest='')").bind(t).first<{n:number}>();if(attachments!.n)throw new HttpError(409,'附件未检查或隔离','ATTACHMENT_VERIFICATION_REQUIRED');
  const conflicts=await db.prepare("SELECT count(*) n FROM r1_migration_issues WHERE tenant_id=? AND status='open' AND reason_code IN ('TARGET_HAS_NEW_FACTS','PERSON_REFERENCE_MISSING','IDENTITY_CONFLICT','LEGACY_NAME_COLLISION')").bind(t).first<{n:number}>();if(conflicts!.n)throw new HttpError(409,'存在未核实结构或身份冲突','MIGRATION_ISSUES_BLOCK_SWITCH');phase='read_switched';features=1;bump=true;const manifest=await digest(checks.map(r=>({...r})));plans.push(token=>db.prepare('UPDATE r1_migration_runs SET manifest_digest=? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(manifest,t,c.id,t,token));result={...result,phase,manifestDigest:manifest,sourceWatermark:watermark};
 }else{
  if(run.phase!=='reconciling')throw new HttpError(409,'运行不处于对账阶段','MIGRATION_PHASE_CONFLICT');const table=c.table,schema=migrationSource(table),key=sourceKeySql(schema.keys),watermark=await sourceWatermark(ctx),prior=await db.prepare('SELECT * FROM r1_migration_reconciliation WHERE tenant_id=? AND run_id=? AND source_table=?').bind(t,c.id,table).first<any>();if(prior&&prior.source_revision!==watermark)throw new HttpError(409,'源变化，须重扫重新对账','MIGRATION_RECONCILIATION_STALE');if(prior?.completed)return {runId:c.id,table,completed:true,replayed:true};const cursor=prior?.cursor??'',rows=(await db.prepare('SELECT s.*,'+key+' AS _key FROM "'+table+'" s WHERE s."'+schema.tenantColumn+'"=? AND '+key+'>?'+(table==='hris_audit_events'?" AND action NOT LIKE 'BASE.migration.%'":'')+' ORDER BY '+key+' LIMIT 101').bind(t,cursor).all<any>()).results,source=rows.slice(0,100),proof:any[]=[];let differences=0;
  for(const raw of source){const {_key,...row}=raw,hash=await rowDigest(table,row),maps=(await db.prepare('SELECT * FROM r1_migration_map WHERE tenant_id=? AND source_table=? AND source_key=? AND mapping_version=? ORDER BY ordinal').bind(t,table,_key,migrationPlanVersion).all<any>()).results,mapped=await mapLegacySource(ctx,table,_key,row);let mismatch=maps.length!==Math.max(1,mapped.entities.length)||maps.some(m=>m.source_digest!==hash||m.confidence==='conflict');
   for(const e of mapped.entities){const target=await db.prepare('SELECT kind,person_id,org_id,code,revision,status,payload FROM r1_m01_entities WHERE tenant_id=? AND id=?').bind(t,e.id).first<any>();if(!target||target.kind!==e.kind||target.person_id!==e.personId||target.org_id!==e.orgId||target.code!==e.code||target.status!==e.status||await digest(JSON.parse(target.payload))!==await digest(e.payload))mismatch=true;const version=target?await db.prepare('SELECT payload FROM r1_m01_versions WHERE tenant_id=? AND entity_id=? AND version=?').bind(t,e.id,target.revision).first<{payload:string}>():null;if(!version||JSON.parse(version.payload).payload&&await digest(JSON.parse(version.payload).payload)!==await digest(JSON.parse(target.payload)))mismatch=true;}
   if(table==='hris_attachments'){const i=await db.prepare('SELECT source_digest,status FROM r1_attachment_integrity WHERE tenant_id=? AND attachment_id=?').bind(t,row.id).first<any>();if(!i||i.source_digest!==hash||!['verified','quarantined'].includes(i.status))mismatch=true;}
   const observed=await db.prepare('SELECT source_image FROM r1_migration_observations WHERE tenant_id=? AND source_table=? AND source_key=? AND source_digest=?').bind(t,table,_key,hash).first<{source_image:string}>();if(!observed||await rowDigest(table,JSON.parse(observed.source_image))!==hash)mismatch=true;if(mismatch)differences++;proof.push({key:_key,digest:hash,mismatch});
  }
  const complete=rows.length<=100;if(complete){const orphan=await db.prepare('SELECT count(DISTINCT m.source_key) n FROM r1_migration_map m WHERE m.tenant_id=? AND m.source_table=? AND NOT EXISTS(SELECT 1 FROM "'+table+'" s WHERE s."'+schema.tenantColumn+'"=m.tenant_id AND '+key+'=m.source_key)').bind(t,table).first<{n:number}>();differences+=orphan!.n;}
  const hash=await digest({prior:prior?.digest??null,proof}),next=source.at(-1)?._key??cursor;plans.push(token=>db.prepare('INSERT INTO r1_migration_reconciliation SELECT owner,?,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=? ON CONFLICT(tenant_id,run_id,source_table) DO UPDATE SET cursor=excluded.cursor,row_count=excluded.row_count,digest=excluded.digest,difference_count=excluded.difference_count,source_revision=excluded.source_revision,completed=excluded.completed').bind(c.id,table,next,(prior?.row_count??0)+source.length,hash,(prior?.difference_count??0)+differences,watermark,Number(complete),t,token));result={...result,table,rows:source.length,differences,completed:complete,digest:hash};
 }
 plans.push(token=>db.prepare('UPDATE r1_migration_runs SET revision=revision+1,lease_until=?,phase=? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(Date.now()+60000,phase,t,c.id,t,token));return commitMigrationTransaction(db,ctx.member,ctx.member.securityStamp!,intent,token=>plans.map(p=>p(token)),result,{storageVersion:1,control:{phase:phase==='rolled_back'?'read_switched':phase,featuresEnabled:features,bumpWriterEpoch:bump}});
}
