import {z} from 'zod';
import {HttpError} from './http';
import {commitMigrationTransaction,digest,replayCommand,type CommandIntent} from './r1-command';
import {migrationSource,sourceKeySql} from './r1-schema-check';
import {migrationRun,assertMigrationLease,migrationFenceStatement,migrationPlanVersion} from './r1-migration';
import {mapLegacySource,rowDigest} from './r1-migration-map';
import {deterministicMigrationId} from './r1-normalize-json';
import type {MigrationContext} from './r1-migration-context';
// Dependency order; all original tables are retained and observed, including immutable history and attachments.
export const backfillOrder=['hris_orgs','hris_grades','hris_positions','hris_employees','hris_employee_positions','hris_workflows','hris_workflow_steps','hris_approvals','hris_assignment_requests','hris_approval_steps','hris_employment_history','hris_development_records','hris_development_events','hris_attachments','hris_memberships','hris_access_grants','hris_installation','hris_audit_events','hris_workspaces'];
const input=z.object({operation:z.literal('backfill'),id:z.string().min(1).max(100),worker:z.string().min(1).max(100),fencingToken:z.number().int().positive(),expectedRevision:z.number().int().positive()}).strict();
export async function backfillMigration(ctx:MigrationContext,intent:CommandIntent){const c=input.parse(intent.payload),run=await migrationRun(ctx,c.id),t=ctx.member.tenantId,db=ctx.db,replay=await replayCommand(db,ctx.member,ctx.member.securityStamp!,intent);if(replay)return replay;assertMigrationLease(run,c.worker,c.fencingToken,c.expectedRevision);if(ctx.row.storageVersion!==1||run.phase!=='backfilling')throw new HttpError(409,'运行不处于回填阶段','MIGRATION_PHASE_CONFLICT');const table=run.source_table,schema=migrationSource(table),key=sourceKeySql(schema.keys),source=(await db.prepare('SELECT s.*,'+key+' AS _source_key FROM "'+table+'" s WHERE s."'+schema.tenantColumn+'"=? AND '+key+'>?'+(table==='hris_audit_events'?" AND action NOT LIKE 'BASE.migration.%'":'')+' ORDER BY '+key+' LIMIT 101').bind(t,run.cursor).all<any>()).results,rows=source.slice(0,100),observations:any[]=[],maps:any[]=[],entities:any[]=[],versions:any[]=[],issues:any[]=[],at=new Date().toISOString();
 for(const raw of rows){const {_source_key:sourceKey,...row}=raw,hash=await rowDigest(table,row),existing=(await db.prepare('SELECT * FROM r1_migration_map WHERE tenant_id=? AND source_table=? AND source_key=? AND mapping_version=? ORDER BY ordinal').bind(t,table,sourceKey,migrationPlanVersion).all<any>()).results;if(existing.length&&existing.every(m=>m.source_digest===hash))continue;
  const mapped=await mapLegacySource(ctx,table,sourceKey,row),observationId=await deterministicMigrationId('observation',table+sourceKey+hash);observations.push({id:observationId,runId:c.id,table,key:sourceKey,sourceRevision:ctx.row.revision,sourceDigest:hash,image:JSON.stringify(row),at});issues.push(...mapped.issues);
  for(const e of mapped.entities){const current=await db.prepare('SELECT revision,payload FROM r1_m01_entities WHERE tenant_id=? AND id=?').bind(t,e.id).first<any>();if(current){const p=JSON.parse(current.payload);if(!p.migrationObservation||p.migrationSource?.table!==table||p.migrationSource?.key!==sourceKey){mapped.confidence='conflict';issues.push({id:await deterministicMigrationId('issue',table+sourceKey+'TARGET_HAS_NEW_FACTS'),sourceTable:table,sourceKey,targetId:e.id,reasonCode:'TARGET_HAS_NEW_FACTS',detail:'{}'});continue;}e.revision=current.revision+1;}
   entities.push({...e,payload:JSON.stringify(e.payload)});versions.push({entityId:e.id,version:e.revision,payload:JSON.stringify(e),validFrom:e.payload.validFrom??e.payload.startOn??null,validTo:e.payload.validTo??null});}
  const targets=mapped.entities.length?mapped.entities.map(e=>({kind:e.kind,id:e.id})):[{kind:'legacy_observation',id:observationId}];targets.forEach((target,ordinal)=>maps.push({table,key:sourceKey,ordinal,sourceRevision:ctx.row.revision,sourceDigest:hash,targetKind:target.kind,targetId:target.id,confidence:mapped.confidence,issueId:mapped.issues[0]?.id??null}));
 }
 const payloads=[observations,maps,entities,versions,issues];if(payloads.some(x=>new TextEncoder().encode(JSON.stringify(x)).byteLength>4*1024*1024))throw new HttpError(413,'回填块超过安全字节预算','MIGRATION_CHUNK_TOO_LARGE');const done=source.length<=100,index=backfillOrder.indexOf(table),complete=done&&index===backfillOrder.length-1,nextTable=done?backfillOrder[index+1]??table:table,nextCursor=done?'':rows.at(-1)!._source_key,batchId=await deterministicMigrationId('batch',c.id+':'+run.scan_generation+':'+table+run.cursor),inputHash=await digest(await Promise.all(rows.map(async({_source_key,...r})=>({key:_source_key,digest:await rowDigest(table,r)})))),outputHash=await digest(payloads),plans:((token:string)=>D1PreparedStatement)[]=[token=>migrationFenceStatement(ctx,run,token)];
 const bulk=(sql:string,payload:unknown[])=>{if(payload.length)plans.push(token=>db.prepare(sql+' FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=?').bind(JSON.stringify(payload),t,token));};
 bulk("INSERT OR IGNORE INTO r1_migration_observations SELECT w.owner,json_extract(j.value,'$.id'),json_extract(j.value,'$.runId'),json_extract(j.value,'$.table'),json_extract(j.value,'$.key'),json_extract(j.value,'$.sourceRevision'),json_extract(j.value,'$.sourceDigest'),json_extract(j.value,'$.image'),json_extract(j.value,'$.at'),'unknown_before_observation'",observations);
 if(entities.length)plans.push(token=>db.prepare("INSERT INTO r1_m01_entities SELECT w.owner,json_extract(j.value,'$.id'),json_extract(j.value,'$.kind'),json_extract(j.value,'$.personId'),json_extract(j.value,'$.orgId'),json_extract(j.value,'$.code'),json_extract(j.value,'$.revision'),json_extract(j.value,'$.status'),json_extract(j.value,'$.payload') FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=? ON CONFLICT(tenant_id,id) DO UPDATE SET org_id=excluded.org_id,code=excluded.code,revision=excluded.revision,status=excluded.status,payload=excluded.payload").bind(JSON.stringify(entities),t,token));
 if(versions.length)plans.push(token=>db.prepare("INSERT INTO r1_m01_versions SELECT w.owner,json_extract(j.value,'$.entityId'),json_extract(j.value,'$.version'),w.revision,?,?,json_extract(j.value,'$.validFrom'),json_extract(j.value,'$.validTo'),'unknown_before_observation',json_extract(j.value,'$.payload') FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=?").bind(intent.commandId,at,JSON.stringify(versions),t,token));
 if(maps.length)plans.push(token=>db.prepare("INSERT INTO r1_migration_map SELECT w.owner,json_extract(j.value,'$.table'),json_extract(j.value,'$.key'),?,json_extract(j.value,'$.ordinal'),json_extract(j.value,'$.sourceRevision'),json_extract(j.value,'$.sourceDigest'),json_extract(j.value,'$.targetKind'),json_extract(j.value,'$.targetId'),json_extract(j.value,'$.confidence'),json_extract(j.value,'$.issueId') FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=? ON CONFLICT(tenant_id,source_table,source_key,mapping_version,ordinal) DO UPDATE SET source_revision=excluded.source_revision,source_digest=excluded.source_digest,confidence=excluded.confidence,issue_id=excluded.issue_id").bind(migrationPlanVersion,JSON.stringify(maps),t,token));
 bulk("INSERT OR IGNORE INTO r1_migration_issues SELECT w.owner,json_extract(j.value,'$.id'),json_extract(j.value,'$.sourceTable'),json_extract(j.value,'$.sourceKey'),json_extract(j.value,'$.targetId'),json_extract(j.value,'$.reasonCode'),'open',1,NULL,NULL,json_extract(j.value,'$.detail')",issues);
 if(table==='hris_memberships'){
  const legacyGrants:any[]=[];for(const row of rows){if(!row.active)continue;const rawScope=JSON.parse(row.org_scope),orgs=(await db.prepare('SELECT id,parent_id FROM hris_orgs WHERE tenant_id=?').bind(t).all<any>()).results,scope=new Set<string>(row.role==='admin'?orgs.map(o=>o.id):rawScope);let more=true;while(more){more=false;for(const o of orgs)if(scope.has(o.parent_id)&&!scope.has(o.id)){scope.add(o.id);more=true;}}
   if(['employee','payroll_editor','payroll_reviewer'].includes(row.role)){const e=await db.prepare('SELECT org_id FROM hris_employees WHERE tenant_id=? AND id=?').bind(t,row.employee_id).first<any>();scope.clear();if(e)scope.add(e.org_id);}
   legacyGrants.push({id:await deterministicMigrationId('legacygrant',row.user_id),user:row.user_id,relation:['employee','payroll_editor','payroll_reviewer'].includes(row.role)?'self':'scope',scope:JSON.stringify([...scope]),fields:JSON.stringify(['record',...(row.role==='admin'||row.view_email?['email']:[]),...(row.role==='admin'||row.view_level?['level']:[])])});
  }if(legacyGrants.length)plans.push(token=>db.prepare("INSERT INTO r1_permission_grants SELECT w.owner,json_extract(j.value,'$.id'),json_extract(j.value,'$.user'),'LEGACY','current.read',json_extract(j.value,'$.relation'),json_extract(j.value,'$.scope'),json_extract(j.value,'$.fields'),'current',?,NULL FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=? ON CONFLICT(tenant_id,id) DO UPDATE SET relation_type=excluded.relation_type,scope=excluded.scope,fields=excluded.fields").bind(at,JSON.stringify(legacyGrants),t,token));
 }
 plans.push(token=>db.prepare('INSERT INTO r1_migration_batches SELECT owner,?,?,?,?,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(batchId,c.id,table,run.scan_generation+':'+run.cursor,run.cursor,rows.at(-1)?._source_key??run.cursor,rows.length,inputHash,outputHash,run.fencing_token,intent.commandId,t,token));plans.push(token=>db.prepare('UPDATE r1_migration_runs SET source_table=?,cursor=?,rows_observed=rows_observed+?,revision=revision+1,lease_until=?,phase=? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(nextTable,nextCursor,rows.length,Date.now()+60000,complete?'reconciling':'backfilling',t,c.id,t,token));
 return commitMigrationTransaction(db,ctx.member,ctx.member.securityStamp!,intent,token=>plans.map(p=>p(token)),{runId:c.id,batchId,rows:rows.length,observations:observations.length,issues:issues.length,phase:complete?'reconciling':'backfilling',revision:run.revision+1},{storageVersion:1,...(complete?{control:{phase:'reconciling',featuresEnabled:0 as const,bumpWriterEpoch:false}}:{})});
}
