import {digest} from './r1-command';
import {deterministicMigrationId} from './r1-normalize-json';
import type {Entity} from './r1-m01';
import type {MigrationContext} from './r1-migration-context';
export type MigrationIssue={id:string;sourceTable:string;sourceKey:string;targetId:string|null;reasonCode:string;detail:string};
export type MappedSource={entities:Entity[];issues:MigrationIssue[];confidence:string;protectedSource:Record<string,unknown>};
const date=(x:unknown)=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x+'T00:00:00Z'))&&new Date(x+'T00:00:00Z').toISOString().slice(0,10)===x?x:null;
/** Observations preserve known IDs and current facts; they do not reconstruct unknown history. */
export async function mapLegacySource(ctx:MigrationContext,table:string,key:string,row:Record<string,any>):Promise<MappedSource>{const entities:Entity[]=[],issues:MigrationIssue[]=[],t=ctx.member.tenantId,issue=async(reasonCode:string,targetId:string|null=null,detail:Record<string,unknown>={})=>issues.push({id:await deterministicMigrationId('issue',table+key+reasonCode),sourceTable:table,sourceKey:key,targetId,reasonCode,detail:JSON.stringify(detail)}),entity=(kind:string,id:string,orgId:string|null,personId:string|null,payload:Record<string,any>,status='active',code:string|null=null)=>{const e={kind,id,orgId,personId,payload:{...payload,historyQuality:'unknown_before_observation',migrationSource:{table,key},migrationObservation:true},status,code,revision:1};entities.push(e);return e;};
 if(['hris_orgs','hris_positions','hris_grades'].includes(table)){
  const kind=table==='hris_orgs'?'org':table==='hris_positions'?'position':'grade',org=kind==='org'?row.id:row.org_id??null,attributes=kind==='org'?{city:row.city,legacyLeader:row.leader}:kind==='position'?{legacyFamilyLabel:row.family,responsibilities:row.responsibilities}:{sequence:row.sequence};entity(kind,row.id,org,null,{name:row.name,parentId:row.parent_id??'',validFrom:null,validTo:null,attributes},row.status==='启用'?'active':'inactive',row.code??null);await issue('CATALOG_VALID_FROM_UNVERIFIED',row.id);
  const nameCount=await ctx.db.prepare('SELECT count(*) n FROM "'+table+'" WHERE tenant_id=? AND name=?'+(kind==='position'?' AND org_id=?':kind==='org'?' AND parent_id IS ?':'')).bind(t,row.name,...(kind==='position'?[row.org_id]:kind==='org'?[row.parent_id]:[])).first<{n:number}>();if(nameCount!.n>1)await issue('LEGACY_NAME_COLLISION',row.id);
 }else if(table==='hris_employees'){
  entity('person',row.id,row.org_id,null,{name:row.name,legacyStatus:row.status,fields:{email:row.email||null,level:row.level||null},identityState:'unverified',historyIncomplete:true},row.status==='离职'?'ended':'active',row.code);
  const employmentId=await deterministicMigrationId('employment',row.id);entity('employment',employmentId,row.org_id,row.id,{startOn:date(row.joined),employmentType:'employee',lastWorkingOn:null,predecessorId:null,historyIncomplete:true,legacyJoined:row.joined},row.status==='离职'?'ended':'active');await issue('EMPLOYMENT_HISTORY_INCOMPLETE',employmentId);if(!date(row.joined))await issue('EMPLOYMENT_START_UNVERIFIED',employmentId);
  if(row.email){const matches=await ctx.db.prepare('SELECT count(*) n FROM hris_employees WHERE tenant_id=? AND lower(email)=lower(?)').bind(t,row.email).first<{n:number}>();if(matches!.n>1)await issue('IDENTITY_CONFLICT',row.id,{kind:'duplicate_contact_not_identity_evidence'});}
 }else if(table==='hris_employee_positions'){
  const person=await ctx.db.prepare('SELECT * FROM hris_employees WHERE tenant_id=? AND id=?').bind(t,row.employee_id).first<any>();if(!person){await issue('PERSON_REFERENCE_MISSING');return {entities,issues,confidence:'conflict',protectedSource:row};}const assignmentId=await deterministicMigrationId('assignment',row.employee_id),employmentId=await deterministicMigrationId('employment',row.employee_id);entity('assignment',assignmentId,person.org_id,row.employee_id,{employmentId,positionId:row.position_id,gradeId:row.grade_id,type:'primary',homePrimaryId:null,validFrom:null,validTo:null,occupancy:person.status==='离职'?0:1,legacyJobLabel:person.job,legacyLevelLabel:person.level},person.status==='离职'?'ended':'active');await issue('ASSIGNMENT_VALID_FROM_UNVERIFIED',assignmentId);if(!row.position_id)await issue('POSITION_REFERENCE_UNVERIFIED',assignmentId);
 }else if(table==='hris_development_records'&&row.kind==='employmentContract'){
  const p=JSON.parse(row.payload),person=await ctx.db.prepare('SELECT org_id FROM hris_employees WHERE tenant_id=? AND id=?').bind(t,row.employee_id).first<{org_id:string}>(),legal=p.legalEntityId?await ctx.db.prepare("SELECT id FROM r1_m01_entities WHERE tenant_id=? AND id=? AND kind='legal_entity'").bind(t,p.legalEntityId).first():null;entity('contract',row.id,person?.org_id??p.orgId??null,row.employee_id,{number:p.contractNumber??null,legalEntityId:legal?p.legalEntityId:null,legacyEmployerLabel:p.employerName??null,agreementCategory:p.agreementCategory??null,contractType:p.contractType??null,start:date(p.start),end:date(p.end),endedOn:date(p.endedOn),renewalOf:row.reference_id,fields:{},legacyPayload:p},row.status);if(!legal)await issue('LEGAL_ENTITY_UNVERIFIED',row.id);if(!p.agreementCategory)await issue('AGREEMENT_CATEGORY_UNVERIFIED',row.id);if(!date(p.start))await issue('CONTRACT_START_UNVERIFIED',row.id);
 }else if(table==='hris_approvals'){
  // Original steps/details remain immutable observations. Unsupported legacy adapters cannot replay terminal effects.
  await issue('LEGACY_APPROVAL_EFFECT_UNVERIFIED',row.id,{approvalStatus:row.status,executionState:'unknown',notificationState:'unknown',rule:'do_not_reexecute_terminal'});
 }else if(table==='hris_memberships'||table==='hris_access_grants'){
  await issue('LEGACY_GRANT_REQUIRES_EXPLICIT_NEW_CAPABILITY',row.user_id??row.claimed_by??null,{rule:'preserve_old_binding_no_export_subscribe_manage_or_relationship_grants'});
 }
 for(const e of entities)e.payload.migrationIssueIds=issues.filter(i=>i.targetId===e.id).map(i=>i.id);
 return {entities,issues,confidence:issues.length?'legacy_partial':'observed',protectedSource:row};
}
export function migrationRowImage(table:string,row:Record<string,unknown>){const copy={...row};if(table==='hris_workspaces'){delete copy.revision;delete copy.last_mutation;}return copy;}
export async function rowDigest(table:string,row:Record<string,unknown>){return digest(migrationRowImage(table,row));}
