import {HttpError} from './http';
import {migrationSource} from './r1-schema-check';
import {digest} from './r1-command';
export const normalizationOrder=['hris_orgs','hris_grades','hris_positions','hris_employees','hris_employee_positions','hris_workflows','hris_workflow_steps','hris_approvals','hris_assignment_requests','hris_approval_steps','hris_audit_events'];
export function normalizeJsonRows(value:unknown,tenant:string){const s=value as any;if(!s||typeof s!=='object'||!['orgs','employees','approvals','audit'].every(k=>Array.isArray(s[k])))throw new HttpError(409,'旧JSON结构无法核验','LEGACY_JSON_INVALID');const out:Record<string,Record<string,unknown>[]>=Object.fromEntries(normalizationOrder.map(t=>[t,[]])),issues:{table:string;key:string;reason:string}[]=[];const push=(table:string,row:Record<string,unknown>)=>out[table].push({tenant_id:tenant,...row});
 for(const key of ['orgs','grades','positions','employees','approvals','audit']){const rows=s[key]??[];if(!Array.isArray(rows)||rows.length>10000||rows.some((r:any)=>!r||typeof r.id!=='string'||!r.id||r.id.length>100)||new Set(rows.map((r:any)=>r.id)).size!==rows.length)throw new HttpError(409,'旧JSON键重复或来源超界','LEGACY_JSON_INVALID');}
 const ordered:any[]=[],seen=new Set<string>(),visiting=new Set<string>(),byId=new Map<string,any>(s.orgs.map((o:any)=>[o.id,o]));const visit=(o:any,depth=0)=>{if(depth>100||visiting.has(o.id))throw new HttpError(409,'旧组织存在循环','LEGACY_ORG_CYCLE');if(seen.has(o.id))return;visiting.add(o.id);if(o.parentId){const parent=byId.get(o.parentId);if(!parent)throw new HttpError(409,'旧组织父引用缺失','LEGACY_PARENT_MISSING');visit(parent,depth+1);}visiting.delete(o.id);seen.add(o.id);ordered.push(o);};s.orgs.forEach((o:any)=>visit(o));
 for(const o of ordered)push('hris_orgs',{id:o.id,name:o.name,parent_id:o.parentId||null,city:o.city??'',leader:o.leader??'',status:o.status});for(const g of s.grades??[])push('hris_grades',{id:g.id,code:g.code,name:g.name,sequence:g.sequence,status:g.status});for(const p of s.positions??[])push('hris_positions',{id:p.id,code:p.code,name:p.name,org_id:p.orgId,family:p.family??'',responsibilities:p.responsibilities??'',status:p.status});
 const link=(r:any,table:string,key:string)=>{const position=r.positionId&&(s.positions??[]).some((p:any)=>p.id===r.positionId)?r.positionId:null,grade=r.gradeId&&(s.grades??[]).some((g:any)=>g.id===r.gradeId)?r.gradeId:null;if(r.positionId&&!position||r.gradeId&&!grade)issues.push({table,key:JSON.stringify([r.id]),reason:'LEGACY_ASSIGNMENT_REFERENCE_UNKNOWN'});return {position_id:position,grade_id:grade};};
 for(const e of s.employees){push('hris_employees',{id:e.id,code:e.code,name:e.name,org_id:e.orgId,job:e.job??'',level:e.level??'',joined:e.joined??'',status:e.status,email:e.email??''});push('hris_employee_positions',{employee_id:e.id,...link(e,'hris_employee_positions',e.id)});}
 for(const [kind,w] of Object.entries(s.workflows??{}) as [string,any][]){if(!Number.isSafeInteger(w.version)||!Array.isArray(w.steps)||w.steps.length>100)throw new HttpError(409,'旧模板无法核验','LEGACY_WORKFLOW_INVALID');push('hris_workflows',{kind,version:w.version});w.steps.forEach((step:any,position:number)=>push('hris_workflow_steps',{kind,version:w.version,position,user_id:step.userId,name:step.name}));}
 for(const a of s.approvals){push('hris_approvals',{id:a.id,employee_id:a.employeeId,kind:a.kind,org_id:a.orgId,reason:a.reason??'',status:a.status,created:a.created,created_by:a.createdBy??null,decided:a.decided??null,decided_by:a.decidedBy??null,current_step:a.currentStep??null,workflow_version:a.workflowVersion??null,details:a.details?JSON.stringify(a.details):null});push('hris_assignment_requests',{approval_id:a.id,...link(a,'hris_assignment_requests',a.id)});(a.steps??[]).forEach((step:any,position:number)=>push('hris_approval_steps',{approval_id:a.id,position,user_id:step.userId,name:step.name,decision:step.decision??null,at:step.at??null}));}
 for(const a of s.audit)push('hris_audit_events',{id:a.id,actor_id:a.actorId??'legacy-unattributed',action:a.action,subject:a.subject,at:a.at,revision:0});
 for(const [table,rows] of Object.entries(out)){const schema=migrationSource(table);for(const row of rows)for(const column of schema.columns)if(!Object.hasOwn(row,column))throw new HttpError(409,'旧JSON不能提供规范化列：'+column,'LEGACY_MAPPING_INCOMPLETE');}
 return {tables:out,issues};
}
export async function deterministicMigrationId(kind:string,key:string){return 'migr-'+kind+'-'+(await digest({kind,key})).slice(0,32);}
