import {z} from 'zod';
import {HttpError} from './http';
import {securityStamp,sameStamp,digest,type CommandIntent} from './r1-command';
import {authorizeTuple,tupleAllowed,type Relationship} from './r1-authorization';
import {memberGrants} from './r1-grants';
import {consumerRecord,portalEntries,fieldRegistry,type PortalEntry,type ConsumerRecord,type ConsumerAdapter} from './r1-portal-contract';
import {portalAdapters} from './r1-portal-adapters';
import type {memberContext} from './context';
export type PortalContext=Awaited<ReturnType<typeof memberContext>>&{personId:string;personOrgId:string};
type Context=Awaited<ReturnType<typeof memberContext>>;
type Registry=Record<PortalEntry,ConsumerAdapter>;
export async function portalContext(ctx:Context):Promise<PortalContext|null>{
 const m=ctx.member;if(!m.securityStamp?.featuresEnabled)throw new HttpError(409,'自助新能力尚未开放','FEATURE_NOT_READY');if(!m.employeeId)return null;
 const binding=await ctx.db.prepare('SELECT count(*) AS n FROM hris_memberships WHERE tenant_id=? AND employee_id=? AND active=1').bind(m.tenantId,m.employeeId).first<{n:number}>();if(binding?.n!==1)throw new HttpError(409,'成员绑定需要核对','BINDING_CONFLICT');const row=await ctx.db.prepare("SELECT org_id,status FROM r1_m01_entities WHERE tenant_id=? AND id=? AND kind='person'").bind(m.tenantId,m.employeeId).first<{org_id:string;status:string}>(),legacy=JSON.parse(ctx.row.data).employees.find((e:any)=>e.id===m.employeeId);if(row?.status==='ended'||!row&&(!legacy||legacy.status==='离职'))return null;return {...ctx,personId:m.employeeId,personOrgId:row?.org_id??legacy.orgId};
}
const parameters=z.object({entry:z.enum(portalEntries),partition:z.enum(['self_tasks','self_requests','authorized_others','team','all']).default('all'),q:z.string().max(100).default(''),subjectPersonId:z.string().max(100).optional(),history:z.enum(['true','false']).default('false'),cursor:z.string().uuid().optional(),limit:z.coerce.number().int().min(1).max(100).default(20)}).strict();
function classify(r:ConsumerRecord,ctx:PortalContext){if(r.subjectPersonId===ctx.personId){if(r.kind==='request'&&r.initiatorId===ctx.member.userId)return 'self_requests';return 'self_tasks';}return r.assigneeIds.includes(ctx.member.userId)?'authorized_others':'team';}
export async function readPortal(context:Context,params:URLSearchParams,registry:Registry=portalAdapters()){
 const p=parameters.parse(Object.fromEntries(params)),ctx=await portalContext(context),adapter=registry[p.entry],stamp=context.member.securityStamp!;
 if(!ctx)return {availability:'unavailable',reasonCode:'binding_missing',entry:p.entry,items:[],visibleTotal:null,totalState:'unknown',counts:{},allowedActions:[],revision:context.row.revision,securityStamp:stamp};
 if(p.entry!=='team'&&p.subjectPersonId&&p.subjectPersonId!==ctx.personId)throw new HttpError(403,'不能通过参数更换本人','SUBJECT_FORBIDDEN');
 const available={entry:p.entry,producerId:adapter.producerId,contractVersion:adapter.contractVersion,mode:adapter.mode,realIntegration:adapter.integrationEvidenceRef?'evidence_requires_review':'not_executed',observedAt:new Date().toISOString(),revision:ctx.row.revision,securityStamp:stamp};
 if(adapter.configurationState!=='configured')return {...available,availability:adapter.configurationState,reasonCode:'PRODUCER_NOT_CONFIGURED',owner:adapter.producerId+' implementation owner',recoveryCondition:'register compatible producer contract and integration evidence',items:[],visibleTotal:null,totalState:'unknown',counts:{},allowedActions:[]};
 const source=await adapter.load(ctx);if(source.records.length>500)throw new HttpError(503,'来源返回超过受控窗口','PRODUCER_LIMIT_EXCEEDED');const records=source.records.map(r=>consumerRecord.parse(r)),grants=await memberGrants(ctx.db,ctx.member.tenantId,ctx.member.userId,'M48'),relations=(await ctx.db.prepare('SELECT subject_person_id AS subjectPersonId,relation_type AS relationType,valid_from AS validFrom,valid_to AS validTo FROM r1_relationships WHERE tenant_id=? AND manager_person_id=? LIMIT 1001').bind(ctx.member.tenantId,ctx.personId).all<Relationship>()).results;if(relations.length>1000)throw new HttpError(503,'关系需要分页读取','BOUNDED_QUERY_REQUIRED');
 const teamConfigured=grants.some(g=>g.action==='team.read')&&relations.some(r=>r.validFrom<=new Date().toISOString()&&(!r.validTo||r.validTo>new Date().toISOString()));
 if(p.entry==='team'&&!teamConfigured)return {...available,availability:'not_configured',reasonCode:'RELATIONSHIP_NOT_CONFIGURED',items:[],visibleTotal:null,totalState:'unknown',counts:{},statusCounts:{},nextCursor:null,hasMore:false};
 const allowed=(r:ConsumerRecord,field:string,action='read',historyMode:'current'|'history'=p.history==='true'?'history':'current')=>tupleAllowed(ctx.member,grants,relations,{objectType:'M48',action:p.entry+'.'+action,orgId:r.orgId,personId:r.subjectPersonId,field,historyMode});
 const items:any[]=[];
 for(const r of records){if(p.subjectPersonId&&r.subjectPersonId!==p.subjectPersonId)continue;if(!allowed(r,'record'))continue;const fields:Record<string,unknown>={},fieldStates:Record<string,string>={};for(const name of fieldRegistry[p.entry]){if(!allowed(r,name)){fieldStates[name]='forbidden';continue;}if(['score'].includes(name)&&r.publicationStatus==='unpublished'){fieldStates[name]='unpublished';continue;}const value=r.fields[name];fields[name]=value??null;fieldStates[name]=value===null||value===undefined?'unknown':'known';}
  const mapping=Object.hasOwn(adapter.statusMap,r.rawStatus)?adapter.statusMap[r.rawStatus]:null,actions=mapping?.actionable&&adapter.act?r.allowedActions.filter(action=>allowed(r,'record',action)&&Object.keys(r.fields).filter(f=>fieldRegistry[p.entry].includes(f)).every(f=>allowed(r,f,action))):[],partition=p.entry==='team'?'team':classify(r,ctx);
  // Public client receives only projected fields; raw producer payloads and assignee lists stay server-side.
  items.push({taskKey:[r.businessType,r.businessId,actions[0]??'read',r.fields.nodeRevision??r.sourceRevision].join(':'),actionKeys:Object.fromEntries(actions.map(action=>[action,[r.businessType,r.businessId,action,r.fields.nodeRevision??r.sourceRevision].join(':')])),businessId:r.businessId,businessType:r.businessType,sourceIdentity:r.sourceIdentity??{businessId:r.businessId},stableEmployeeId:r.subjectPersonId,partition,rawStatus:r.rawStatus,displayStatus:mapping?.displayStatus??'状态暂不可解释',statusCategory:mapping?.category??'unknown',mappingVersion:adapter.contractVersion,approvalStatus:r.approvalStatus,effectStatus:r.effectStatus,publicationStatus:r.publicationStatus,sourceRevision:r.sourceRevision,sourceVersion:r.sourceVersion,definitionVersion:r.definitionVersion,period:r.period,effectiveAt:r.effectiveAt,fields,fieldStates,allowedActions:actions,reasonCode:mapping?r.reasonCode:'STATUS_MAPPING_REQUIRED',href:r.href,mode:adapter.mode});
 }
 if(p.subjectPersonId&&!items.length)throw new HttpError(403,'对象不可读取','SUBJECT_FORBIDDEN');
 const queryDigest=await digest({entry:p.entry,partition:p.partition,q:p.q,subject:p.subjectPersonId??null,history:p.history,limit:p.limit}),manifest={...source.sourceManifest,contractVersion:adapter.contractVersion,workspaceRevision:ctx.row.revision},sourceDigest=await digest(manifest);let after='';
 if(p.cursor){const cursor=await ctx.db.prepare('SELECT * FROM r1_portal_cursors WHERE tenant_id=? AND id=? AND actor_id=?').bind(ctx.member.tenantId,p.cursor,ctx.member.userId).first<any>();if(!cursor||cursor.query_digest!==queryDigest||cursor.source_digest!==sourceDigest||cursor.authorization_revision!==stamp.authorizationRevision||cursor.writer_epoch!==stamp.writerEpoch||cursor.recovery_epoch!==stamp.recoveryEpoch||cursor.expires_at<=Date.now())throw new HttpError(409,'分页或授权版本变化','CURSOR_STALE');after=cursor.last_key;}
 const filtered=items.filter(i=>(p.partition==='all'||i.partition===p.partition)&&Object.values(i.fields).some(v=>typeof v==='string'&&v.toLowerCase().includes(p.q.toLowerCase()))||p.q===''&&(p.partition==='all'||i.partition===p.partition));filtered.sort((a,b)=>a.taskKey<b.taskKey?-1:a.taskKey>b.taskKey?1:0);const counts=items.reduce<Record<string,number>>((a,i)=>({...a,[i.partition]:(a[i.partition]??0)+1}),{}),statusCounts=filtered.reduce<Record<string,number>>((a,i)=>({...a,[i.statusCategory]:(a[i.statusCategory]??0)+1}),{}),page=filtered.filter(i=>i.taskKey>after).slice(0,p.limit+1),selected=page.slice(0,p.limit),next=page.length>p.limit?crypto.randomUUID():null;
 // Re-evaluate all represented tuples at the final time boundary, in addition to the revision fence.
 for(const i of items){const r=records.find(r=>r.businessId===i.businessId&&r.businessType===i.businessType)!;if(!allowed(r,'record')||Object.keys(i.fields).some(f=>!allowed(r,f)))throw new HttpError(409,'权限有效期已变化','REVISION_CONFLICT');}
 const final=await securityStamp(ctx.db,ctx.member.tenantId),latest=await ctx.db.prepare('SELECT revision FROM hris_workspaces WHERE owner=?').bind(ctx.member.tenantId).first<{revision:number}>();if(!sameStamp(stamp,final)||latest?.revision!==ctx.row.revision)throw new HttpError(409,'读取中授权或数据变化','REVISION_CONFLICT');
 if(next)await ctx.db.prepare('INSERT INTO r1_portal_cursors VALUES (?,?,?,?,?,?,?,?,?,?)').bind(ctx.member.tenantId,next,ctx.member.userId,queryDigest,sourceDigest,stamp.authorizationRevision,stamp.writerEpoch,stamp.recoveryEpoch,selected.at(-1)!.taskKey,Date.now()+300000).run();
 return {...available,availability:p.entry==='team'&&!teamConfigured?'not_configured':selected.length?'available':'no_data',reasonCode:p.entry==='team'&&!teamConfigured?'RELATIONSHIP_NOT_CONFIGURED':null,items:selected,visibleTotal:source.complete?filtered.length:null,totalState:source.complete?'known':'unknown',counts:source.complete?counts:{},statusCounts:source.complete?statusCounts:{},loadedCounts:counts,nextCursor:next,hasMore:!!next||!source.complete,sourceManifest:manifest,sourceManifestDigest:sourceDigest};
}
export async function portalAction(context:Context,input:unknown,registry:Registry=portalAdapters()){
 const b=z.object({entry:z.enum(portalEntries),businessId:z.string().min(1).max(100),sourceVersion:z.string().min(1).max(100),sourceRevision:z.number().int().nonnegative(),action:z.string().min(1).max(100),intent:z.object({correlationId:z.string().regex(/^[A-Za-z0-9:_-]{1,100}$/).optional(),causationId:z.string().regex(/^[A-Za-z0-9:_-]{1,100}$/).optional(),commandId:z.string().uuid(),idempotencyKey:z.string().min(1).max(100),expectedWorkspaceRevision:z.number().int(),expectedAuthorizationRevision:z.number().int(),expectedWriterEpoch:z.number().int(),expectedRecoveryEpoch:z.number().int(),payload:z.unknown()}).strict()}).strict().parse(input),ctx=await portalContext(context);if(!ctx)throw new HttpError(403,'当前未绑定员工','BINDING_MISSING');const adapter=registry[b.entry];if(adapter.configurationState!=='configured'||!adapter.act)throw new HttpError(409,'生产者尚未开放此办理契约','PRODUCER_NOT_CONFIGURED');
 const stamp=ctx.member.securityStamp!;if(b.intent.expectedWorkspaceRevision!==ctx.row.revision||b.intent.expectedAuthorizationRevision!==stamp.authorizationRevision||b.intent.expectedWriterEpoch!==stamp.writerEpoch||b.intent.expectedRecoveryEpoch!==stamp.recoveryEpoch)throw new HttpError(409,'办理版本已变化','REVISION_CONFLICT');
 const source=await adapter.load(ctx),record=source.records.map(r=>consumerRecord.parse(r)).find(r=>r.businessId===b.businessId);if(!record)throw new HttpError(404,'原单不存在或不可见','NOT_FOUND_OR_NOT_VISIBLE');if(!Object.hasOwn(adapter.statusMap,record.rawStatus)||!adapter.statusMap[record.rawStatus].actionable||!record.allowedActions.includes(b.action))throw new HttpError(403,'原业务当前不允许此动作','ACTION_NOT_ALLOWED');if(record.sourceVersion!==b.sourceVersion||record.sourceRevision!==b.sourceRevision)throw new HttpError(409,'原单版本变化，请重新确认','SOURCE_VERSION_CONFLICT');
 for(const field of ['record',...Object.keys(record.fields).filter(f=>fieldRegistry[b.entry].includes(f))])await authorizeTuple(ctx.db,ctx.member,{objectType:'M48',action:b.entry+'.'+b.action,orgId:record.orgId,personId:record.subjectPersonId,field,historyMode:'current'});
 const final=await securityStamp(ctx.db,ctx.member.tenantId),latest=await ctx.db.prepare('SELECT revision FROM hris_workspaces WHERE owner=?').bind(ctx.member.tenantId).first<{revision:number}>();if(!sameStamp(stamp,final)||latest?.revision!==ctx.row.revision)throw new HttpError(409,'办理中权限或原数据变化','REVISION_CONFLICT');
 return adapter.act(ctx,record,b.action,{...b.intent,payload:b.intent.payload,action:'M48.'+b.entry+'.'+b.action});
}
