import type {PortalContext} from './r1-portal';
import {commonStatusMap,type ConsumerAdapter,type ConsumerRecord,type PortalEntry} from './r1-portal-contract';
import {effectiveVersions} from './r1-temporal';
import {businessDate} from './business-time';
import {HttpError} from './http';
import {authorizeTuple} from './r1-authorization';
import {executeWorkflow} from './r1-workflow';
import {visibleDevelopment,type DevelopmentContext} from './development-repository';
import {legacySelfService} from './r1-legacy-self-service';
const base=(id:string,type:string,subject:string,org:string,revision:number):ConsumerRecord=>({businessId:id,businessType:type,subjectPersonId:subject,orgId:org,kind:'record',initiatorId:null,assigneeIds:[],rawStatus:'active',sourceRevision:revision,sourceVersion:String(revision),definitionVersion:'r1-v1',period:null,publicationStatus:'not_applicable',approvalStatus:null,effectStatus:null,effectiveAt:null,fields:{},allowedActions:[],reasonCode:null,href:'/self-service'});
async function bounded(ctx:PortalContext,sql:string,args:unknown[]=[]){const r=await ctx.db.prepare(sql+' LIMIT 501').bind(ctx.member.tenantId,...args).all<any>();if(r.results.length>500||new TextEncoder().encode(JSON.stringify(r.results)).byteLength>4*1024*1024)throw new HttpError(503,'来源超过当前有界查询预算','BOUNDED_QUERY_REQUIRED');return r.results;}
export async function portalLegacyContext(ctx:PortalContext):Promise<DevelopmentContext>{const rows=await bounded(ctx,'SELECT id,kind,employee_id AS employeeId,position_id AS positionId,reference_id AS referenceId,status,payload,created_by AS createdBy,created_at AS createdAt,updated_at AS updatedAt FROM hris_development_records WHERE tenant_id=? ORDER BY id');return {...ctx,state:JSON.parse(ctx.row.data),records:rows.map(r=>({...r,payload:JSON.parse(r.payload)}))} as DevelopmentContext;}
const page=(ctx:PortalContext,records:ConsumerRecord[],version:string)=>({records,sourceManifest:{workspaceRevision:ctx.row.revision,contractVersion:version},totalState:'known' as const,complete:true});
export function portalAdapters():Record<PortalEntry,ConsumerAdapter>{
 const internal=(producerId:string,load:ConsumerAdapter['load']):ConsumerAdapter=>({producerId,contractVersion:'r1-v1',configurationState:'configured',mode:'internal',integrationEvidenceRef:null,statusMap:commonStatusMap,load});
 const team=internal('M01',async ctx=>{const persons=await bounded(ctx,"SELECT id,org_id AS orgId,code,status,payload,revision FROM r1_m01_entities WHERE tenant_id=? AND kind='person' ORDER BY id"),assignments=await bounded(ctx,"SELECT id,person_id,revision,payload FROM r1_m01_entities WHERE tenant_id=? AND kind='assignment' AND status='active' AND json_extract(payload,'$.type')='primary' ORDER BY id"),state=JSON.parse(ctx.row.data),day=businessDate(),versions=await bounded(ctx,"SELECT v.payload FROM r1_m01_versions v JOIN r1_m01_entities e ON e.tenant_id=v.tenant_id AND e.id=v.entity_id WHERE v.tenant_id=? AND e.kind IN ('org','position','grade') ORDER BY e.id,v.version"),catalog=effectiveVersions(versions.map(v=>JSON.parse(v.payload))),catalogName=(id:string|undefined)=>{const entries=catalog.filter((e:any)=>e.id===id&&(e.payload.validFrom?e.payload.validFrom<=day:e.payload.migrationObservation===true)&&(!e.payload.validTo||e.payload.validTo>=day));if(entries.length>1)throw new HttpError(409,'目录有效版本冲突','TEMPORAL_CONFLICT');return entries[0]?.payload.name??null;};return page(ctx,persons.map(p=>{const value=JSON.parse(p.payload),employee=state.employees.find((e:any)=>e.id===p.id),r=base(p.id,'M01.person',p.id,p.orgId,p.revision),current=assignments.filter(a=>{const v=JSON.parse(a.payload);return a.person_id===p.id&&(v.validFrom?v.validFrom<=day:v.migrationObservation===true)&&(!v.validTo||v.validTo>=day);});if(current.length>1)throw new HttpError(409,'当前主职冲突','PRIMARY_CONFLICT');r.sourceIdentity={businessId:p.id,personId:p.id,assignmentId:current[0]?.id??null,relationshipRevision:ctx.member.securityStamp!.authorizationRevision};r.sourceVersion=[ctx.row.revision,p.revision,current[0]?.revision??0,ctx.member.securityStamp!.authorizationRevision].join(':');r.rawStatus=p.status==='ended'?'cancelled':'active';r.fields={name:value.name??employee?.name??'',code:p.code??'',orgName:catalogName(p.orgId),positionName:catalogName(current[0]?JSON.parse(current[0].payload).positionId:undefined),email:value.fields?.email??employee?.email??null,grade:catalogName(current[0]?JSON.parse(current[0].payload).gradeId:undefined)};r.href='/r1-personnel';return r;}),'M01.person-v1');});team.contractVersion='r1-m01-team-v1';team.integrationEvidenceRef='docs/delivery/r1-p3/R1_P3_Producer_Case_Evidence.json#P3-LINK-M48-team';
 const approvals=internal('M19',async ctx=>{const rows=await bounded(ctx,'SELECT * FROM r1_workflow_instances WHERE tenant_id=? ORDER BY id'),records:ConsumerRecord[]=[];for(const i of rows){try{await authorizeTuple(ctx.db,ctx.member,{objectType:'M19',action:'read',orgId:i.org_id,personId:i.person_id,field:'record',historyMode:'current'});}catch(e){if(e instanceof HttpError&&e.status===403)continue;throw e;}const n=i.current_node_id?await ctx.db.prepare('SELECT revision,assignees,status FROM r1_workflow_nodes WHERE tenant_id=? AND id=?').bind(ctx.member.tenantId,i.current_node_id).first<any>():null,r=base(i.id,i.business_type,i.person_id,i.org_id,i.revision);r.sourceIdentity={businessId:i.business_id,instanceId:i.id,personId:i.person_id};r.kind='request';r.initiatorId=i.initiator_id;r.assigneeIds=n?JSON.parse(n.assignees):[];r.rawStatus=i.approval_status==='approved'&&['waiting','failed'].includes(i.effect_status)?i.effect_status:i.approval_status;r.approvalStatus=i.approval_status;r.effectStatus=i.effect_status;r.fields={title:i.title,approvalStatus:i.approval_status,effectStatus:i.effect_status,nodeRevision:n?.revision??null,generation:i.generation};r.href='/r1-approvals';if(i.approval_status==='pending'&&r.assigneeIds.includes(ctx.member.userId)&&i.initiator_id!==ctx.member.userId&&i.person_id!==ctx.personId)r.allowedActions=['decide'];if(i.approval_status==='pending'&&i.initiator_id===ctx.member.userId)r.allowedActions.push('withdraw');const frozen=JSON.parse(i.template_payload),qualified:string[]=[];for(const action of r.allowedActions){try{for(const field of frozen.requiredFields)await authorizeTuple(ctx.db,ctx.member,{objectType:'M19',action,orgId:i.org_id,personId:i.person_id,field,historyMode:'current'});qualified.push(action);}catch(e){if(!(e instanceof HttpError&&e.status===403))throw e;}}r.allowedActions=qualified;r.definitionVersion='workflow:'+frozen.templateVersion;records.push(r);}return page(ctx,records,'M19.workflow-v1');});
 approvals.contractVersion='r1-m19-portal-v1';approvals.integrationEvidenceRef='docs/delivery/r1-p3/R1_P3_Producer_Case_Evidence.json#P3-LINK-M48-approval';
 approvals.act=async(ctx,r,action,intent)=>{const payload=intent.payload as any;if(!['decide','withdraw'].includes(action))throw new HttpError(403,'未允许的原单动作','FORBIDDEN');return executeWorkflow(ctx,{...intent,action:'M19.'+action,payload:{operation:action,id:r.businessId,expectedRevision:r.sourceRevision,generation:payload.generation,...(action==='decide'?{nodeRevision:payload.nodeRevision,decision:payload.decision}:{}),reason:payload.reason}});};
 const kinds:Record<string,string[]>={goals:['performancePlan','performanceGoalChange','performanceCheckin','performanceAppeal','performance'],attendance:['leave','correction'],learning:['enrollment','homeworkTask','learningExamTask','learningAssignment','trainingRequest'],development:['plan']};
 const compatibility=(entry:'goals'|'attendance'|'learning'|'development',producerId:string):ConsumerAdapter=>({...internal(producerId,async ctx=>{const legacy=await portalLegacyContext(ctx),summary=legacySelfService(legacy),visible=visibleDevelopment(legacy),records:ConsumerRecord[]=[];
 for(const source of visible.filter(r=>kinds[entry].includes(r.kind))){const employee=legacy.state.employees.find(e=>e.id===source.employeeId);if(!employee)continue;const task=summary.tasks.find(t=>t.id===source.id),request=summary.requests.find(t=>t.id===source.id),r=base(source.id,source.kind,employee.id,employee.orgId,ctx.row.revision);r.kind=task?'task':request?'request':'record';r.initiatorId=source.createdBy;r.assigneeIds=task?[ctx.member.userId]:[];r.rawStatus=request?.status??source.status;r.sourceVersion=source.updatedAt;r.definitionVersion='legacy-'+source.kind+'-v1';r.period=source.payload.period??null;r.publicationStatus=source.kind==='performance'?(source.status==='published'?'published':'unpublished'):'not_applicable';r.fields={title:task?.title??request?.title??source.payload.title??source.payload.name??source.kind,due:task?.due??source.payload.due??null};if(entry==='goals'){r.fields.planId=source.kind==='performancePlan'?source.id:source.referenceId;r.fields.cycleId=source.payload.period??null;if(source.kind==='performanceAppeal'&&source.status==='approved')r.approvalStatus='approved';}if(entry==='attendance'){r.fields.balance=null;r.fields.unit=null;}if(entry==='learning'){r.fields.taskId=source.id;r.fields.assignmentId=source.payload.learningAssignmentId??null;r.fields.score=source.payload.score??null;}if(entry==='development'){r.fields.planId=source.id;r.fields.stageId=null;r.fields.actionId=null;}r.href=task?.href??request?.href??(entry==='goals'?'/performance':entry==='attendance'?'/attendance':entry==='learning'?'/learning':'/development');r.reasonCode='PRODUCER_COMMAND_UPGRADE_REQUIRED';r.allowedActions=[];records.push(r);}return page(ctx,records,'legacy-'+entry+'-read-v1');}),contractVersion:'legacy-'+entry+'-read-v1',mode:'compatibility'});
 return {team,approvals,okr:{producerId:'M16',contractVersion:'okr-v1',configurationState:'not_configured',mode:'internal',integrationEvidenceRef:null,statusMap:{},load:async ctx=>page(ctx,[],'okr-v1')},goals:compatibility('goals','M16'),attendance:compatibility('attendance','M11'),learning:compatibility('learning','M27'),development:compatibility('development','M17')};
}
