import {identity} from './context';
import {requireMember,type Member} from './authorization';
import {securityStamp,sameStamp} from './r1-command';
import {HttpError} from './http';
/** Report queries never load the unbounded legacy workspace or development record arrays. */
export async function reportContext(){const {user,db}=await identity(),sql='SELECT user_id AS userId,tenant_id AS tenantId,role,employee_id AS employeeId,org_scope AS orgScope,view_email AS viewEmail,view_level AS viewLevel,active FROM hris_memberships WHERE user_id=?',member=await db.prepare(sql).bind(user.id).first<Member>();requireMember(member);const stamp=await securityStamp(db,member.tenantId);if(!stamp.featuresEnabled)throw new HttpError(409,'报表新能力尚未开放','FEATURE_NOT_READY');const row=await db.prepare('SELECT revision,storage_version AS storageVersion FROM hris_workspaces WHERE owner=?').bind(member.tenantId).first<{revision:number;storageVersion:number}>();if(!row||row.storageVersion!==1)throw new HttpError(409,'报表源尚未迁移','SOURCE_NOT_MIGRATED');const current=await db.prepare(sql).bind(user.id).first<Member>();requireMember(current);if(current.tenantId!==member.tenantId||!sameStamp(stamp,await securityStamp(db,current.tenantId)))throw new HttpError(409,'报表授权已变化','REVISION_CONFLICT');current.securityStamp=stamp;return {user,db,member:current,row};}
export type ReportContext=Awaited<ReturnType<typeof reportContext>>;
export async function reportFence(ctx:ReportContext){const row=await ctx.db.prepare('SELECT revision FROM hris_workspaces WHERE owner=?').bind(ctx.member.tenantId).first<{revision:number}>();if(row?.revision!==ctx.row.revision||!sameStamp(ctx.member.securityStamp!,await securityStamp(ctx.db,ctx.member.tenantId))||Date.now()>=(ctx.member.permissionValidUntil??Number.MAX_SAFE_INTEGER))throw new HttpError(409,'报表当前权限已变化','REVISION_CONFLICT');}

/** Internal worker lookup of an existing member only; never accepts a caller-supplied identity in an HTTP read route. */
export async function reportActorContext(db:D1Database,tenant:string,actor:string):Promise<ReportContext>{
 const member=await db.prepare('SELECT user_id AS userId,tenant_id AS tenantId,role,employee_id AS employeeId,org_scope AS orgScope,view_email AS viewEmail,view_level AS viewLevel,active FROM hris_memberships WHERE tenant_id=? AND user_id=?').bind(tenant,actor).first<Member>();requireMember(member);const stamp=await securityStamp(db,tenant);if(!stamp.featuresEnabled)throw new HttpError(409,'报表新能力尚未开放','FEATURE_NOT_READY');const row=await db.prepare('SELECT revision,storage_version AS storageVersion FROM hris_workspaces WHERE owner=?').bind(tenant).first<{revision:number;storageVersion:number}>();if(!row||row.storageVersion!==1)throw new HttpError(409,'来源尚未迁移','SOURCE_NOT_MIGRATED');member.securityStamp=stamp;return {db,member,row,user:{id:actor} as ReportContext['user']};
}
