import {HttpError} from './http';
import {digest,canonical} from './r1-command';
import {verifyRecoveryManifest,type SignedRecoveryManifest,type RecoveryVaultAccess,type ImmutableBackupStore} from './r1-recovery-crypto';
import {restoreRecoveryDatabase,type IsolatedRecoveryTarget} from './r1-recovery-restore';
import {restoreRecoveryObjects,type IsolatedObjectTarget} from './r1-recovery-objects';
import {SqlSecurityLedger,type SecurityLedgerState} from './r1-security-ledger';
import type {SqlRecoveryReceiptStore,RecoveryExternalReceipt} from './r1-recovery-receipts';
export const recoveryControlSchema=`CREATE TABLE recovery_control_runs(id TEXT PRIMARY KEY,request_digest TEXT NOT NULL,checkpoint_id TEXT NOT NULL,target_id TEXT NOT NULL,object_target_id TEXT NOT NULL,phase TEXT NOT NULL,last_verified TEXT NOT NULL,revision INTEGER NOT NULL,incident_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,blocked_reason TEXT);
CREATE TABLE recovery_control_events(run_id TEXT NOT NULL,revision INTEGER NOT NULL,phase TEXT NOT NULL,at INTEGER NOT NULL,evidence TEXT NOT NULL,digest TEXT NOT NULL,PRIMARY KEY(run_id,revision));
CREATE TABLE recovery_control_guard(id TEXT PRIMARY KEY,valid INTEGER NOT NULL CHECK(valid=1));`;
const phases=['incident_confirmed','isolated','source_verified','database_restored','objects_verified','authorization_reconciled','business_checked'];
export interface AuthorityRecoveryTarget extends IsolatedRecoveryTarget {applyCurrentAuthority(tenant:string,state:SecurityLedgerState,receipt:{id:string;digest:string}):Promise<{members:number;disabled:number;restoredBusinessObjectsCreated:0}>;verifyBusiness():Promise<Record<string,unknown>>;reconcileOutboundReceipts(lookup:(tenant:string,channel:RecoveryExternalReceipt['channel'],id:string)=>Promise<RecoveryExternalReceipt|null>):Promise<Record<string,number>>;}
/** The control DB survives replacement of the business target. This service never approves or opens it. */
export class RecoveryController {
 constructor(private db:D1Database,readonly storageId:string,businessStorageId:string){if(storageId===businessStorageId)throw new HttpError(409,'恢复控制面必须独立','RECOVERY_CONTROL_NOT_INDEPENDENT');}
 async read(id:string){return this.db.prepare('SELECT * FROM recovery_control_runs WHERE id=?').bind(id).first<any>();}
 async start(id:string,checkpoint:string,target:string,objects:string){const requestDigest=await digest({id,checkpoint,target,objects}),old=await this.read(id);if(old){if(old.request_digest!==requestDigest)throw new HttpError(409,'恢复运行键冲突','RECOVERY_RUN_CONFLICT');return old;}const now=Date.now();await this.db.batch([this.db.prepare("INSERT INTO recovery_control_runs VALUES (?,?,?,?,?,'incident_confirmed','incident_confirmed',1,?,?,NULL)").bind(id,requestDigest,checkpoint,target,objects,now,now),this.db.prepare("INSERT INTO recovery_control_events VALUES (?,1,'incident_confirmed',?,?,?)").bind(id,now,'{}',await digest({phase:'incident_confirmed',at:now}))]);return this.read(id);}
 private async record(id:string,phase:string,evidence:Record<string,unknown>){const old=await this.read(id);if(!old)throw new HttpError(404,'恢复运行不存在','RECOVERY_RUN_NOT_FOUND');if(phase!=='blocked'){const current=phases.indexOf(old.last_verified),next=phases.indexOf(phase);if(next<=current)return;if(next!==current+1)throw new HttpError(409,'恢复步骤不能跳过','RECOVERY_STAGE_CONFLICT');}const at=Date.now(),revision=old.revision+1,body=canonical(evidence),hash=await digest({id,revision,phase,at,evidence});await this.db.batch([this.db.prepare('INSERT INTO recovery_control_guard VALUES (?,CASE WHEN (SELECT revision FROM recovery_control_runs WHERE id=?)=? THEN 1 ELSE 0 END)').bind(id,id,old.revision),this.db.prepare('INSERT INTO recovery_control_events VALUES (?,?,?,?,?,?)').bind(id,revision,phase,at,body,hash),this.db.prepare('UPDATE recovery_control_runs SET phase=?,last_verified=?,revision=?,updated_at=?,blocked_reason=? WHERE id=?').bind(phase,phase==='blocked'?old.last_verified:phase,revision,at,phase==='blocked'?String(evidence.reasonCode):null,id),this.db.prepare('DELETE FROM recovery_control_guard WHERE id=?').bind(id)]);}
 async run(id:string,packages:SignedRecoveryManifest[],vault:RecoveryVaultAccess,backup:ImmutableBackupStore,target:AuthorityRecoveryTarget,objects:IsolatedObjectTarget,ledger:SqlSecurityLedger,platformAccess:(tenant:string)=>Promise<boolean>,receipts?:SqlRecoveryReceiptStore){if(!packages.length)throw new HttpError(400,'恢复清单为空','RECOVERY_MANIFEST_INVALID');const checkpoint=packages.at(-1)!.manifest.checkpointId,run=await this.start(id,checkpoint,target.targetId,objects.targetId);if(run.phase==='business_checked')return this.status(id);try{await target.assertIsolated();await objects.assertIsolated();await this.record(id,'isolated',{targetId:target.targetId,objectTargetId:objects.targetId,externalSending:false});for(const p of packages)await verifyRecoveryManifest(p,vault,backup);await this.record(id,'source_verified',{checkpointId:checkpoint,correlationId:packages.at(-1)!.manifest.correlationId??null,manifestDigest:packages.at(-1)!.digest});
  const reconciled:{tenant:string;revision:number;digest:string}[]=[];const result=await restoreRecoveryDatabase(packages,vault,backup,target,async()=>{await this.record(id,'database_restored',{checkpointId:checkpoint,openGate:0});if(receipts)await target.reconcileOutboundReceipts((tenant,channel,key)=>receipts.lookup(tenant,channel,key));const restoredObjects=await restoreRecoveryObjects(packages,vault,backup,objects);await this.record(id,'objects_verified',{objectCount:restoredObjects.objectCount,byteCount:restoredObjects.byteCount});const manifest=packages.at(-1)!.manifest,tenants=Object.keys(manifest.tenantRevisions);if(!tenants.length)throw new HttpError(503,'缺少租户安全检查点','SECURITY_RECONCILIATION_REQUIRED');for(const tenant of tenants){const head=await ledger.verifyChain(tenant),reference=manifest.securityLedgers?.[tenant]??(tenants.length===1?manifest.securityLedger:null);if(!reference||head.revision<reference.revision||head.state.denied||head.state.pendingId||!head.state.platformAccessVerified||!await platformAccess(tenant))throw new HttpError(503,'可信当前授权不足或未确认','SECURITY_RECONCILIATION_REQUIRED');if(!await ledger.verifyReference(tenant,reference.revision,reference.digest))throw new HttpError(503,'备份安全水位不是此可信链的一部分','SECURITY_LEDGER_BROKEN');await target.applyCurrentAuthority(tenant,head.state,{id:checkpoint+':authority:'+tenant+':'+head.revision,digest:head.digest});reconciled.push({tenant,revision:head.revision,digest:head.digest});}await this.record(id,'authorization_reconciled',{tenants:reconciled,scopeProjection:'conservative_current_intersection',restoredBusinessObjectsCreated:0});});
  if(!reconciled.length)throw new HttpError(503,'缺少当前授权回执','SECURITY_RECONCILIATION_REQUIRED');for(const confirmed of reconciled){const fresh=await ledger.verifyChain(confirmed.tenant);if(fresh.revision!==confirmed.revision||fresh.digest!==confirmed.digest||!await platformAccess(confirmed.tenant))throw new HttpError(503,'对账后授权发生变化，保持隔离','SECURITY_SOURCE_CHANGED');}const business=await target.verifyBusiness();await this.record(id,'business_checked',{...business,integrity:result.integrity,foreignKeyErrors:result.foreignKeyErrors,openGate:0,externalSending:false});return this.status(id);
 }catch(e){await this.record(id,'blocked',{reasonCode:e instanceof HttpError?e.machineCode??'RECOVERY_BLOCKED':'RECOVERY_STEP_FAILED'});throw e;}}
 async status(id:string){const r=await this.read(id);if(!r)throw new HttpError(404,'恢复运行不存在','RECOVERY_RUN_NOT_FOUND');const events=(await this.db.prepare('SELECT revision,phase,at,evidence,digest FROM recovery_control_events WHERE run_id=? ORDER BY revision LIMIT 1001').bind(id).all<any>()).results;if(events.length>1000)throw new HttpError(503,'恢复步骤记录超过查询预算','RECOVERY_HISTORY_BUDGET');return {runId:id,phase:r.phase,lastVerified:r.last_verified,blockedReason:r.blocked_reason,incidentAt:r.incident_at,elapsedIncludingApprovalWaitMs:Date.now()-r.incident_at,steps:events.map(e=>({...e,evidence:JSON.parse(e.evidence)})),ownerApproval:'required_not_provided',opened:false,rtoPassed:false};}
 async open(){throw new HttpError(403,'需独立所有者开放批准与平台执行能力，本窗口不能代批','OWNER_RECOVERY_APPROVAL_REQUIRED');}
}
