import {createHash} from 'node:crypto';
import {HttpError} from './http';
import {digest} from './r1-command';
import {migrationFiles} from './r1-schema-manifest';
import {recoveryCut,assertRecoveryCut,baselineRows,committedTransactions,encodeRecoveryRecords,recoverySchemaDigest,recoveryExcludedTables} from './r1-recovery-data';
import {RECOVERY_CHUNK_BYTES,writeRecoveryChunks,sealRecoveryManifest,verifyRecoveryManifest,type RecoveryManifest,type SignedRecoveryManifest,type RecoveryKeyVault,type ImmutableBackupStore} from './r1-recovery-crypto';
import {SqlSecurityLedger} from './r1-security-ledger';
export interface ImmutableBusinessObjectReader {head(key:string):Promise<{versionId:string;byteCount:number;immutable:true}|null>;readRange(key:string,versionId:string,offset:number,length:number):Promise<Uint8Array|null>;}
type Reference={object_key:string;tenant_id:string;byte_count:number;mime:string;tombstone:number;expected_digest:string|null;quarantined:number};
/** Pages include tombstones and committed report chunks; unreferenced upload intents are deliberately excluded. */
async function* references(db:D1Database){const duplicate=await db.prepare("SELECT object_key FROM (SELECT object_key FROM hris_attachments UNION ALL SELECT object_key FROM r1_report_job_chunks) GROUP BY object_key HAVING count(*)>1 LIMIT 1").first();if(duplicate)throw new HttpError(409,'业务对象键重复','RECOVERY_OBJECT_MANIFEST_INVALID');let after='';while(true){const page=(await db.prepare(`SELECT * FROM (SELECT a.object_key,a.tenant_id,a.size byte_count,a.mime,CASE WHEN a.deleted_at IS NULL THEN 0 ELSE 1 END tombstone,i.digest expected_digest,CASE WHEN i.status='quarantined' THEN 1 ELSE 0 END quarantined FROM hris_attachments a LEFT JOIN r1_attachment_integrity i ON i.tenant_id=a.tenant_id AND i.attachment_id=a.id UNION ALL SELECT c.object_key,c.tenant_id,c.byte_count,'text/csv',CASE WHEN f.status IN ('tombstone','deleted') THEN 1 ELSE 0 END,c.digest,0 FROM r1_report_job_chunks c LEFT JOIN r1_report_file_intents f ON f.tenant_id=c.tenant_id AND f.object_key=c.object_key) WHERE object_key>? ORDER BY object_key LIMIT 100`).bind(after).all<Reference>()).results;for(const row of page){if(row.object_key<=after)throw new HttpError(409,'业务对象键重复','RECOVERY_OBJECT_MANIFEST_INVALID');after=row.object_key;yield row;}if(page.length<100)break;}}
/** No scheduler or cloud credentials are implied. The caller is the independently authorized backup service. */
export async function createRecoveryCheckpoint(db:D1Database,options:{correlationId?:string;checkpointId:string;sourceSha:string;lockDigest:string;parent?:SignedRecoveryManifest;keyHistory?:ReadonlyMap<string,RecoveryKeyVault>},vault:RecoveryKeyVault,backup:ImmutableBackupStore,objects:ImmutableBusinessObjectReader,ledger:SqlSecurityLedger,platformAccess:(tenant:string)=>Promise<boolean>){const existing=await backup.get(options.checkpointId+'/manifest');if(existing){const signed=await verifyRecoveryManifest(JSON.parse(new TextDecoder().decode(existing)),vault,backup);if(signed.manifest.correlationId!==options.correlationId||signed.manifest.sourceSha!==options.sourceSha||signed.manifest.lockDigest!==options.lockDigest||signed.manifest.parentDigest!==(options.parent?.digest??null))throw new HttpError(409,'恢复检查点键冲突','RECOVERY_IDEMPOTENCY_CONFLICT');return signed;}
 if(options.parent)await verifyRecoveryManifest(options.parent,options.keyHistory??vault,backup);const cut=await recoveryCut(db),takenAt=new Date().toISOString(),tenants=Object.keys(cut.tenantRevisions);if(!tenants.length)throw new HttpError(409,'恢复源无租户','RECOVERY_MANIFEST_INVALID');const securityLedgers:NonNullable<RecoveryManifest['securityLedgers']>={},tenantEpochs:NonNullable<RecoveryManifest['tenantEpochs']>={};for(const tenant of tenants){const head=await ledger.verifyChain(tenant),epoch=await db.prepare('SELECT schema_version schemaVersion,writer_epoch writerEpoch,recovery_epoch recoveryEpoch,authorization_revision authorizationRevision FROM r1_schema_state WHERE tenant_id=?').bind(tenant).first<any>();if(!epoch||head.state.workspaceRevision!==cut.tenantRevisions[tenant]||head.state.authorizationRevision!==epoch.authorizationRevision||head.state.recoveryEpoch!==epoch.recoveryEpoch||head.state.denied||head.state.pendingId||!head.state.platformAccessVerified||!await platformAccess(tenant))throw new HttpError(503,'备份缺少当前可信安全水位','SECURITY_RECONCILIATION_REQUIRED');securityLedgers[tenant]={revision:head.revision,digest:head.digest,verifiedAt:takenAt};tenantEpochs[tenant]={...epoch};}
 if(options.parent&&options.parent.manifest.toSeq>cut.seq)throw new HttpError(409,'备份源日志水位回退','RECOVERY_LOG_GAP');const key=await vault.createDataKey(),counts:Record<string,number>={},catalog:RecoveryManifest['objects']=[],kind=options.parent?'incremental':'baseline',records=options.parent?committedTransactions(db,options.parent.manifest.toSeq,cut.seq):baselineRows(db,cut,counts);
 const chunks=await writeRecoveryChunks(options.checkpointId,key.key,(async function*(){yield* encodeRecoveryRecords(records,options.parent?'increment':'baseline','database');for await(const ref of references(db)){await assertRecoveryCut(db,cut);const head=await objects.head(ref.object_key);if(ref.quarantined||!head||head.immutable!==true||!Number.isSafeInteger(head.byteCount)||head.byteCount<0||head.byteCount!==ref.byte_count||!head.versionId)throw new HttpError(409,'可达对象缺失或不可变版本未确认','RECOVERY_OBJECT_MISSING');let offset=0;const hash=createHash('sha256');do{const length=Math.min(RECOVERY_CHUNK_BYTES,head.byteCount-offset),bytes=await objects.readRange(ref.object_key,head.versionId,offset,length);if(!bytes||bytes.byteLength!==length)throw new HttpError(409,'对象范围缺失或长度变化','RECOVERY_OBJECT_MISSING');hash.update(bytes);yield {kind:'object' as const,sourceId:ref.object_key,bytes};offset+=length;}while(offset<head.byteCount);const hashValue=hash.digest('hex');if(ref.expected_digest&&hashValue!==ref.expected_digest)throw new HttpError(409,'业务对象摘要改变','RECOVERY_OBJECT_HASH_MISMATCH');const recheck=await objects.head(ref.object_key);if(!recheck||recheck.versionId!==head.versionId||recheck.byteCount!==head.byteCount||!recheck.immutable)throw new HttpError(409,'复制期间对象版本变化','RECOVERY_SOURCE_CHANGED');catalog.push({key:ref.object_key,versionId:head.versionId,byteCount:head.byteCount,digest:hashValue,mime:ref.mime,owner:ref.tenant_id,tombstone:!!ref.tombstone,chunks:[]});if(catalog.length>2000)throw new HttpError(413,'恢复清单需分区，不能截断成功','RECOVERY_MANIFEST_BUDGET');}})(),backup);
 for(const object of catalog)object.chunks=chunks.filter(c=>c.kind==='object'&&c.sourceId===object.key).map(c=>c.sequence);await assertRecoveryCut(db,cut);for(const tenant of tenants){const head=await ledger.verifyChain(tenant);if(head.digest!==securityLedgers[tenant].digest||!await platformAccess(tenant))throw new HttpError(409,'备份期间当前授权改变','SECURITY_SOURCE_CHANGED');}
 const m:RecoveryManifest={manifestVersion:1,...(options.correlationId?{correlationId:options.correlationId}:{}),checkpointId:options.checkpointId,sourceSha:options.sourceSha,lockDigest:options.lockDigest,schemaDigest:await recoverySchemaDigest(),ddlFiles:migrationFiles,kind,parentCheckpoint:options.parent?.manifest.checkpointId??null,parentDigest:options.parent?.digest??null,fromSeq:options.parent?.manifest.toSeq??cut.seq,toSeq:cut.seq,takenAt,tenantRevisions:cut.tenantRevisions,tenantEpochs,securityLedger:securityLedgers[tenants[0]],securityLedgers,keyId:vault.keyId,wrappedKey:key.wrappedKey,chunks,tableCounts:counts,objects:catalog,excludedTables:recoveryExcludedTables,retainedUntil:new Date(Date.parse(takenAt)+31*86400000).toISOString()};return sealRecoveryManifest(m,vault,backup);
}
