import {createHash} from 'node:crypto';
import {z} from 'zod';
import {HttpError} from './http';
import {canonical,digest} from './r1-command';
import {byteDigest} from './r1-migration-attachments';
export const RECOVERY_CHUNK_BYTES=4*1024*1024;
const hex=z.string().regex(/^[0-9a-f]{64}$/),id=z.string().min(1).max(150),integer=z.number().int().nonnegative().safe();
const chunkSchema=z.object({sequence:integer,key:id,kind:z.enum(['baseline','increment','object']),sourceId:id,plaintextBytes:integer,ciphertextBytes:integer,plaintextDigest:hex,ciphertextDigest:hex,previousDigest:hex.nullable(),nonce:z.string().regex(/^[0-9a-f]{24}$/)}).strict();
export type RecoveryChunk=z.infer<typeof chunkSchema>;
export const recoveryManifestSchema=z.object({manifestVersion:z.literal(1),correlationId:id.optional(),checkpointId:id,sourceSha:z.string().regex(/^[0-9a-f]{40}$/),lockDigest:hex,schemaDigest:hex,ddlFiles:z.array(z.object({file:id,sha256:hex}).strict()).min(1),kind:z.enum(['baseline','incremental']),parentCheckpoint:id.nullable(),parentDigest:hex.nullable(),fromSeq:integer,toSeq:integer,takenAt:z.string().datetime(),tenantRevisions:z.record(z.string(),integer),securityLedger:z.object({revision:integer,digest:hex,verifiedAt:z.string().datetime()}).strict(),securityLedgers:z.record(z.string(),z.object({revision:integer,digest:hex,verifiedAt:z.string().datetime()}).strict()).optional(),tenantEpochs:z.record(z.string(),z.object({schemaVersion:integer,writerEpoch:integer,recoveryEpoch:integer,authorizationRevision:integer}).strict()).optional(),keyId:id,wrappedKey:z.string().regex(/^[0-9a-f]+$/),chunks:z.array(chunkSchema).max(100000),tableCounts:z.record(z.string(),integer),objects:z.array(z.object({key:id,versionId:id,byteCount:integer,digest:hex,mime:z.string().max(200),owner:id,tombstone:z.boolean(),chunks:z.array(integer)}).strict()).max(100000),excludedTables:z.array(id),retainedUntil:z.string().datetime()}).strict();
export type RecoveryManifest=z.infer<typeof recoveryManifestSchema>;
export type SignedRecoveryManifest={manifest:RecoveryManifest;digest:string;signature:string};
export interface RecoveryKeyVault {readonly keyId:string;createDataKey():Promise<{key:CryptoKey;wrappedKey:string}>;unwrapDataKey(wrapped:string):Promise<CryptoKey>;sign(message:Uint8Array):Promise<string>;verify(message:Uint8Array,signature:string):Promise<boolean>;}
export type RecoveryVaultAccess=RecoveryKeyVault|ReadonlyMap<string,RecoveryKeyVault>;
export function recoveryVaultFor(access:RecoveryVaultAccess,keyId:string):RecoveryKeyVault {const vault='keyId' in access?access:access.get(keyId);if(!vault||vault.keyId!==keyId)throw new HttpError(409,'恢复依赖密钥不可用','RECOVERY_KEY_UNAVAILABLE');return vault;}
export interface ImmutableBackupStore {putIfAbsent(key:string,bytes:Uint8Array):Promise<void>;get(key:string):Promise<Uint8Array|null>;}
const hexBytes=(bytes:ArrayBuffer|Uint8Array)=>[...new Uint8Array(bytes as ArrayBuffer)].map(x=>x.toString(16).padStart(2,'0')).join('');
function fromHex(hex:string){if(!/^(?:[0-9a-f]{2})+$/.test(hex))throw new HttpError(409,'加密材料格式无效','RECOVERY_CRYPTO_INVALID');return Uint8Array.from(hex.match(/../g)!,s=>parseInt(s,16));}
const buffer=(v:Uint8Array)=>v as Uint8Array<ArrayBuffer>;
/** The wrapping key and signing private key live in a separate vault, never in a manifest. */
export class WebCryptoRecoveryVault implements RecoveryKeyVault {
 constructor(readonly keyId:string,private wrappingKey:CryptoKey,private signingKey:CryptoKey,private verificationKey:CryptoKey){}
 async createDataKey(){const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt','decrypt']);return {key,wrappedKey:hexBytes(await crypto.subtle.wrapKey('raw',key,this.wrappingKey,'AES-KW'))};}
 async unwrapDataKey(wrapped:string){try{return await crypto.subtle.unwrapKey('raw',fromHex(wrapped),this.wrappingKey,'AES-KW',{name:'AES-GCM',length:256},false,['decrypt']);}catch{throw new HttpError(409,'独立解封密钥不可用','RECOVERY_KEY_UNAVAILABLE');}}
 async sign(message:Uint8Array){return hexBytes(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},this.signingKey,buffer(message)));}
 async verify(message:Uint8Array,signature:string){try{return await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},this.verificationKey,fromHex(signature),buffer(message));}catch{return false;}}
}
function aad(checkpointId:string,c:Pick<RecoveryChunk,'sequence'|'kind'|'sourceId'|'plaintextBytes'|'plaintextDigest'|'previousDigest'>){return new TextEncoder().encode(canonical({checkpointId,sequence:c.sequence,kind:c.kind,sourceId:c.sourceId,plaintextBytes:c.plaintextBytes,plaintextDigest:c.plaintextDigest,previousDigest:c.previousDigest}));}
export async function encryptRecoveryChunk(checkpointId:string,key:CryptoKey,sequence:number,kind:RecoveryChunk['kind'],sourceId:string,bytes:Uint8Array,previousDigest:string|null){if(bytes.byteLength>RECOVERY_CHUNK_BYTES)throw new HttpError(413,'恢复分块超过4MiB','RECOVERY_CHUNK_BUDGET');const nonce=crypto.getRandomValues(new Uint8Array(12)),base={sequence,kind,sourceId,plaintextBytes:bytes.byteLength,plaintextDigest:await byteDigest(bytes),previousDigest};const encrypted=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv:nonce,additionalData:aad(checkpointId,base)},key,buffer(bytes)));return {bytes:encrypted,chunk:chunkSchema.parse({...base,key:checkpointId+'/'+sequence,ciphertextBytes:encrypted.byteLength,ciphertextDigest:await byteDigest(encrypted),nonce:hexBytes(nonce)})};}
export async function decryptRecoveryChunk(checkpointId:string,key:CryptoKey,chunk:RecoveryChunk,encrypted:Uint8Array){const c=chunkSchema.parse(chunk);if(c.plaintextBytes>RECOVERY_CHUNK_BYTES||encrypted.byteLength!==c.ciphertextBytes||await byteDigest(encrypted)!==c.ciphertextDigest)throw new HttpError(409,'恢复密文摘要或字节数不一致','RECOVERY_CHUNK_CORRUPT');let plain:Uint8Array;try{plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:fromHex(c.nonce),additionalData:aad(checkpointId,c)},key,buffer(encrypted)));}catch{throw new HttpError(409,'恢复分块认证失败','RECOVERY_AUTHENTICATION_FAILED');}if(plain.byteLength!==c.plaintextBytes||await byteDigest(plain)!==c.plaintextDigest)throw new HttpError(409,'恢复明文摘要不符','RECOVERY_CHUNK_CORRUPT');return plain;}
export async function sealRecoveryManifest(value:RecoveryManifest,vault:RecoveryKeyVault,store:ImmutableBackupStore){const manifest=recoveryManifestSchema.parse(value);await validateRecoveryManifest(manifest,vault,store);const hash=await digest(manifest),signature=await vault.sign(new TextEncoder().encode(hash));const signed={manifest,digest:hash,signature};await store.putIfAbsent(manifest.checkpointId+'/manifest',new TextEncoder().encode(canonical(signed)));return signed;}
export async function verifyRecoveryManifestSignature(value:unknown,access:RecoveryVaultAccess){const signed=z.object({manifest:recoveryManifestSchema,digest:hex,signature:z.string().min(1).max(1000)}).strict().parse(value);const vault=recoveryVaultFor(access,signed.manifest.keyId);if(signed.manifest.keyId!==vault.keyId||await digest(signed.manifest)!==signed.digest||!await vault.verify(new TextEncoder().encode(signed.digest),signed.signature))throw new HttpError(409,'恢复清单签名或信任密钥不符','RECOVERY_MANIFEST_UNTRUSTED');return signed;}
export async function verifyRecoveryManifest(value:unknown,access:RecoveryVaultAccess,store:ImmutableBackupStore){const signed=await verifyRecoveryManifestSignature(value,access);await validateRecoveryManifest(signed.manifest,recoveryVaultFor(access,signed.manifest.keyId),store);return signed;}
async function validateRecoveryManifest(m:RecoveryManifest,vault:RecoveryKeyVault,store:ImmutableBackupStore){if(m.keyId!==vault.keyId||m.fromSeq>m.toSeq||Date.parse(m.retainedUntil)<=Date.parse(m.takenAt)||m.kind==='baseline'&&(m.parentCheckpoint!==null||m.parentDigest!==null)||m.kind==='incremental'&&(!m.parentCheckpoint||!m.parentDigest))throw new HttpError(409,'恢复清单边界无效','RECOVERY_MANIFEST_INVALID');const key=await vault.unwrapDataKey(m.wrappedKey),nonces=new Set<string>();let previous:string|null=null;for(let sequence=0;sequence<m.chunks.length;sequence++){const c=m.chunks[sequence];if(c.sequence!==sequence||c.previousDigest!==previous||c.key!==m.checkpointId+'/'+sequence||nonces.has(c.nonce))throw new HttpError(409,'恢复块断链、重复nonce或乱序','RECOVERY_CHAIN_INVALID');nonces.add(c.nonce);const bytes=await store.get(c.key);if(!bytes)throw new HttpError(409,'恢复块缺失','RECOVERY_OBJECT_MISSING');await decryptRecoveryChunk(m.checkpointId,key,c,bytes);previous=c.ciphertextDigest;}
 const objectKeys=new Set<string>(),claimed=new Set<number>();for(const object of m.objects){if(objectKeys.has(object.key)||!object.chunks.length||object.chunks.some(n=>m.chunks[n]?.kind!=='object'||m.chunks[n].sourceId!==object.key)||object.chunks.reduce((n,i)=>n+m.chunks[i].plaintextBytes,0)!==object.byteCount)throw new HttpError(409,'对象引用清单不完整','RECOVERY_OBJECT_MANIFEST_INVALID');objectKeys.add(object.key);const hash=createHash('sha256');for(const sequence of object.chunks){if(claimed.has(sequence))throw new HttpError(409,'对象块重复引用','RECOVERY_OBJECT_MANIFEST_INVALID');claimed.add(sequence);const c=m.chunks[sequence],bytes=await store.get(c.key);if(!bytes)throw new HttpError(409,'对象分块缺失','RECOVERY_OBJECT_MISSING');hash.update(await decryptRecoveryChunk(m.checkpointId,key,c,bytes));}if(hash.digest('hex')!==object.digest)throw new HttpError(409,'整个对象的摘要不一致','RECOVERY_OBJECT_HASH_MISMATCH');}if(m.chunks.some(c=>c.kind==='object'&&!claimed.has(c.sequence)))throw new HttpError(409,'对象块未被完整清单引用','RECOVERY_OBJECT_MANIFEST_INVALID');
}
/** One chunk is live at a time. The caller streams DB rows or object ranges into this writer. */
export async function writeRecoveryChunks(checkpointId:string,key:CryptoKey,source:AsyncIterable<{kind:RecoveryChunk['kind'];sourceId:string;bytes:Uint8Array}>,store:ImmutableBackupStore){const chunks:RecoveryChunk[]=[],nonces=new Set<string>();for await(const item of source){const encrypted=await encryptRecoveryChunk(checkpointId,key,chunks.length,item.kind,item.sourceId,item.bytes,chunks.at(-1)?.ciphertextDigest??null);if(nonces.has(encrypted.chunk.nonce))throw new HttpError(409,'恢复nonce重复','RECOVERY_NONCE_REUSED');nonces.add(encrypted.chunk.nonce);await store.putIfAbsent(encrypted.chunk.key,encrypted.bytes);const verify=await store.get(encrypted.chunk.key);if(!verify||await byteDigest(verify)!==encrypted.chunk.ciphertextDigest)throw new HttpError(409,'上传后未确认恢复块','RECOVERY_UPLOAD_UNVERIFIED');chunks.push(encrypted.chunk);}return chunks;}
