import {HttpError} from './http';
import {canonical,digest} from './r1-command';
import {schemaTables,schemaObjects} from './r1-schema-manifest';
import {checkMigrationSchema,sourceKeySql} from './r1-schema-check';
import {RECOVERY_CHUNK_BYTES,type RecoveryChunk} from './r1-recovery-crypto';
export const recoveryExcludedTables=['r1_recovery_changes','r1_report_query_cursors','r1_portal_cursors','r1_workflow_commit_guard','r1_adapter_guard'];
export const recoveryTables=schemaTables.filter(t=>!recoveryExcludedTables.includes(t.name));
export type RecoveryRow={table:string;row:Record<string,unknown>};
export type RecoveryChange={seq:number;tenant_id:string;tx_id:string;table_name:string;row_key:string;operation:string;after_image:string|null;schema_version:number;workspace_revision:number};
export type RecoveryTransaction={txId:string;fromSeq:number;toSeq:number;changes:RecoveryChange[]};
export async function recoveryCut(db:D1Database){const [tenants,seq]=await db.batch([db.prepare('SELECT owner,revision FROM hris_workspaces ORDER BY owner LIMIT 101'),db.prepare('SELECT coalesce(max(seq),0) seq FROM r1_recovery_changes')]);if(tenants.results.length>100)throw new HttpError(413,'单恢复分区租户数超过预算','RECOVERY_TENANT_BUDGET');return {seq:(seq.results[0] as any).seq as number,tenantRevisions:Object.fromEntries(tenants.results.map((r:any)=>[r.owner,r.revision])) as Record<string,number>};}
export async function assertRecoveryCut(db:D1Database,cut:Awaited<ReturnType<typeof recoveryCut>>){if(await digest(await recoveryCut(db))!==await digest(cut))throw new HttpError(409,'导出期间源已变化，不能发布一致基线','RECOVERY_SOURCE_CHANGED');}
/** A page is accepted only while the full journal and tenant revision cut stays unchanged. */
export async function* baselineRows(db:D1Database,cut:Awaited<ReturnType<typeof recoveryCut>>,counts:Record<string,number>):AsyncGenerator<RecoveryRow>{await checkMigrationSchema(db);for(const table of recoveryTables){counts[table.name]=0;let after='';while(true){await assertRecoveryCut(db,cut);const key=sourceKeySql(table.keys),page=(await db.prepare('SELECT s.*,'+key+' AS _recovery_key FROM "'+table.name+'" s WHERE '+key+'>? ORDER BY '+key+' LIMIT 100').bind(after).all<Record<string,unknown>>()).results;await assertRecoveryCut(db,cut);for(const raw of page){const {_recovery_key,...row}=raw;after=_recovery_key as string;counts[table.name]++;yield {table:table.name,row};}if(page.length<100)break;}}await assertRecoveryCut(db,cut);}
function tableSchema(name:string){const table=schemaTables.find(t=>t.name===name);if(!table||recoveryExcludedTables.includes(name))throw new HttpError(409,'恢复表未注册或为临时缓存','RECOVERY_SCHEMA_UNSUPPORTED');return table;}
export function validateRecoveryRow(value:RecoveryRow){const table=tableSchema(value.table),names=Object.keys(value.row).sort();if(canonical(names)!==canonical([...table.columns].sort())||table.keys.some(k=>value.row[k]===null||value.row[k]===undefined))throw new HttpError(409,'恢复行未覆盖全部列或键缺失','RECOVERY_ROW_INVALID');canonical(value.row);return table;}
export function validateRecoveryTransaction(tx:RecoveryTransaction,expectedNextSeq:number){if(tx.fromSeq!==expectedNextSeq||!tx.changes.length||tx.toSeq!==tx.changes.at(-1)!.seq||tx.changes[0].seq!==tx.fromSeq)throw new HttpError(409,'增量日志断序','RECOVERY_LOG_GAP');for(let i=0;i<tx.changes.length;i++){const c=tx.changes[i];if(c.tx_id!==tx.txId||c.seq!==tx.fromSeq+i)throw new HttpError(409,'事务被拆开或日志断序','RECOVERY_TRANSACTION_INCOMPLETE');const table=tableSchema(c.table_name);if(!['insert','update','delete'].includes(c.operation))throw new HttpError(409,'日志操作无效','RECOVERY_ROW_INVALID');let row:any;if(c.operation!=='delete'){if(!c.after_image)throw new HttpError(409,'完整行镜像缺失','RECOVERY_ROW_INVALID');row=JSON.parse(c.after_image);validateRecoveryRow({table:c.table_name,row});if(row[table.tenantColumn!]!==c.tenant_id)throw new HttpError(409,'日志行租户不符','RECOVERY_TENANT_MISMATCH');}const rawKey=JSON.parse(c.row_key),key=Array.isArray(rawKey)?Object.fromEntries(table.keys.map((k,i)=>[k,rawKey[i]])):rawKey;if(canonical(Object.keys(key).sort())!==canonical([...table.keys].sort())||row&&table.keys.some(k=>key[k]!==row[k]))throw new HttpError(409,'日志主键不匹配','RECOVERY_ROW_INVALID');}
 if(tx.txId.startsWith('unfenced:'))throw new HttpError(409,'存在无法证明提交边界的写入','RECOVERY_UNFENCED_WRITE');if(tx.txId.startsWith('aux:')){if(tx.changes.length!==1||!['r1_report_file_intents','r1_upload_intents','r1_workflow_denials'].includes(tx.changes[0].table_name))throw new HttpError(409,'辅助日志不属于已批准单行写入','RECOVERY_UNFENCED_WRITE');return;}
 const seal=tx.changes.at(-1)!;if(seal.table_name!=='r1_commands'||seal.operation!=='update'||!seal.after_image||JSON.parse(seal.after_image).status!=='committed'||JSON.parse(seal.after_image).token!==tx.txId)throw new HttpError(409,'增量事务缺少提交封印','RECOVERY_TRANSACTION_INCOMPLETE');if(tx.changes.some(c=>c.workspace_revision!==seal.workspace_revision||c.tenant_id!==seal.tenant_id||c.schema_version!==seal.schema_version))throw new HttpError(409,'事务租户、schema或revision不一致','RECOVERY_TRANSACTION_INCOMPLETE');}
export async function* committedTransactions(db:D1Database,fromSeq:number,toSeq:number):AsyncGenerator<RecoveryTransaction>{let cursor=fromSeq,current:RecoveryChange[]=[],bytes=0;while(cursor<toSeq){const page=(await db.prepare('SELECT * FROM r1_recovery_changes WHERE seq>? AND seq<=? ORDER BY seq LIMIT 100').bind(cursor,toSeq).all<RecoveryChange>()).results;if(!page.length)throw new HttpError(409,'增量尾部缺失','RECOVERY_LOG_GAP');for(const raw of page){const c={...raw};if(c.seq!==cursor+1)throw new HttpError(409,'增量日志断序','RECOVERY_LOG_GAP');if(current.length&&current[0].tx_id!==c.tx_id){const tx={txId:current[0].tx_id,fromSeq:current[0].seq,toSeq:current.at(-1)!.seq,changes:current};validateRecoveryTransaction(tx,tx.fromSeq);yield tx;current=[];bytes=0;}bytes+=new TextEncoder().encode(canonical(c)).byteLength;if(bytes>16*1024*1024)throw new HttpError(413,'单事务恢复记录超过有界解析预算','RECOVERY_TRANSACTION_BUDGET');current.push(c);cursor=c.seq;}}
 if(current.length){const tx={txId:current[0].tx_id,fromSeq:current[0].seq,toSeq:current.at(-1)!.seq,changes:current};validateRecoveryTransaction(tx,tx.fromSeq);yield tx;}}
/** UTF-8 NDJSON may span 4MiB blocks; the parser retains at most one bounded record. */
export async function* encodeRecoveryRecords(records:AsyncIterable<unknown>,kind:RecoveryChunk['kind'],sourceId:string){let pending=new Uint8Array(RECOVERY_CHUNK_BYTES),used=0;for await(const row of records){const bytes=new TextEncoder().encode(canonical(row)+'\n');if(bytes.byteLength>16*1024*1024)throw new HttpError(413,'单条恢复记录超过预算','RECOVERY_RECORD_BUDGET');let offset=0;while(offset<bytes.length){const n=Math.min(bytes.length-offset,RECOVERY_CHUNK_BYTES-used);pending.set(bytes.subarray(offset,offset+n),used);used+=n;offset+=n;if(used===RECOVERY_CHUNK_BYTES){yield {kind,sourceId,bytes:pending};pending=new Uint8Array(RECOVERY_CHUNK_BYTES);used=0;}}}if(used)yield {kind,sourceId,bytes:pending.slice(0,used)};}
export async function* decodeRecoveryRecords(chunks:AsyncIterable<Uint8Array>):AsyncGenerator<any>{const decoder=new TextDecoder('utf-8',{fatal:true});let pending='';for await(const bytes of chunks){pending+=decoder.decode(bytes,{stream:true});let end;while((end=pending.indexOf('\n'))>=0){const record=pending.slice(0,end);pending=pending.slice(end+1);if(new TextEncoder().encode(record).byteLength>16*1024*1024)throw new HttpError(413,'恢复记录超过预算','RECOVERY_RECORD_BUDGET');try{yield JSON.parse(record);}catch{throw new HttpError(409,'恢复记录损坏','RECOVERY_ROW_INVALID');}}if(new TextEncoder().encode(pending).byteLength>16*1024*1024)throw new HttpError(413,'恢复记录超过预算','RECOVERY_RECORD_BUDGET');}pending+=decoder.decode();if(pending)throw new HttpError(409,'恢复记录尾部被截断','RECOVERY_TRANSACTION_INCOMPLETE');}
export const recoverySchemaDigest=()=>digest(schemaObjects);
