import {HttpError} from './http';
import {datasetDefinition} from './r1-report-catalog';
import {reportCell} from './r1-report-values';
import type {ReportProducer,ProjectionRow} from './r1-report-projection';
import type {ReportContext} from './r1-report-context';
import {effectiveVersions} from './r1-temporal';
import {businessDate} from './business-time';
async function latest(ctx:ReportContext,cutoff:number,kind:string,personId?:string){const results=(await ctx.db.prepare("SELECT v.payload FROM r1_m01_entities e JOIN r1_m01_versions v ON v.tenant_id=e.tenant_id AND v.entity_id=e.id WHERE e.tenant_id=? AND e.kind=?"+(personId?' AND e.person_id=?':'')+" AND v.version=(SELECT max(v2.version) FROM r1_m01_versions v2 WHERE v2.tenant_id=v.tenant_id AND v2.entity_id=v.entity_id AND v2.workspace_revision<=?) ORDER BY e.id LIMIT 201").bind(ctx.member.tenantId,kind,...(personId?[personId]:[]),cutoff).all<{payload:string}>()).results;if(results.length>200)throw new HttpError(503,'单对象关联超过构建预算','SOURCE_ASSOCIATION_BUDGET');return results.map(r=>JSON.parse(r.payload));}
async function catalog(ctx:ReportContext,cutoff:number,id:string|undefined,day:string){if(!id)return null;const r=(await ctx.db.prepare('SELECT payload FROM r1_m01_versions WHERE tenant_id=? AND entity_id=? AND workspace_revision<=? ORDER BY version LIMIT 201').bind(ctx.member.tenantId,id,cutoff).all<{payload:string}>()).results;if(r.length>200)throw new HttpError(503,'目录历史超过查询预算','SOURCE_ASSOCIATION_BUDGET');const active=effectiveVersions(r.map(r=>JSON.parse(r.payload))).filter(e=>(e.payload.validFrom?e.payload.validFrom<=day:e.payload.migrationObservation===true)&&(!e.payload.validTo||day<=e.payload.validTo));if(active.length>1)throw new HttpError(409,'目录有效版本冲突','TEMPORAL_CONFLICT');return active[0]??null;}
export const m01ReportProducer:ReportProducer={producerId:'M01',version:'r1-m01-v1',mode:'internal',async readPage(ctx,datasetId,cutoff,orgId,after,limit,generatedAt){const d=datasetDefinition(datasetId)!;if(!['workforce','contractCoverage','contractOperations'].includes(datasetId))throw new HttpError(409,'人事生产者不支持该数据集','DATASET_VERSION_UNSUPPORTED');const day=businessDate(generatedAt),kind=datasetId==='contractOperations'?'contract':'person',pageSize=Math.min(limit,20),afterId=after?JSON.parse(after)[0]:'',source=(await ctx.db.prepare("SELECT v.payload FROM r1_m01_entities e JOIN r1_m01_versions v ON v.tenant_id=e.tenant_id AND v.entity_id=e.id WHERE e.tenant_id=? AND e.kind=? AND e.id>? AND v.version=(SELECT max(v2.version) FROM r1_m01_versions v2 WHERE v2.tenant_id=v.tenant_id AND v2.entity_id=v.entity_id AND v2.workspace_revision<=?) AND json_extract(v.payload,'$.orgId')=? ORDER BY e.id LIMIT ?").bind(ctx.member.tenantId,kind,afterId,cutoff,orgId,pageSize+1).all<{payload:string}>()).results,entries=source.slice(0,pageSize).map(r=>JSON.parse(r.payload)),rows:ProjectionRow[]=[];
 for(const e of entries){let person=e;if(kind==='contract'){const row=await ctx.db.prepare('SELECT payload FROM r1_m01_versions WHERE tenant_id=? AND entity_id=? AND workspace_revision<=? ORDER BY version DESC LIMIT 1').bind(ctx.member.tenantId,e.personId,cutoff).first<{payload:string}>();if(!row)throw new HttpError(409,'合同缺少稳定人员版本','SOURCE_REFERENCE_MISSING');person=JSON.parse(row.payload);}const org=await catalog(ctx,cutoff,person.orgId,day),employment=(await latest(ctx,cutoff,'employment',person.id)).filter(x=>x.status==='active').sort((a,b)=>(b.payload.startOn??'').localeCompare(a.payload.startOn??''))[0],status=person.status==='ended'?'离职':person.payload.probationStatus==='formal'?'正式':person.payload.probationStatus==='trial'?'试用':person.payload.legacyStatus??'在职',joined=employment?.payload.startOn??person.payload.joined??null;let values:unknown[]=[],eventDate:string|null=null;
  if(datasetId==='workforce'){const assignments=(await latest(ctx,cutoff,'assignment',person.id)).filter(x=>x.status==='active'&&x.payload.type==='primary'&&(x.payload.validFrom?x.payload.validFrom<=day:x.payload.migrationObservation===true)&&(!x.payload.validTo||day<=x.payload.validTo));if(assignments.length>1)throw new HttpError(409,'主职版本冲突','PRIMARY_CONFLICT');const position=await catalog(ctx,cutoff,assignments[0]?.payload.positionId,day),grade=await catalog(ctx,cutoff,assignments[0]?.payload.gradeId,day);values=[person.code,person.payload.name,org?.payload.name??null,position?.payload.name??null,status,joined,person.payload.fields?.email??null,grade?.payload.name??null];}
  else if(datasetId==='contractCoverage'){if(person.status==='ended')continue;const contracts=(await latest(ctx,cutoff,'contract',person.id)).filter(c=>c.status!=='cancelled'),signed=contracts.filter(c=>c.status==='signed'),unknown=signed.some(c=>!c.payload.start||!c.payload.legalEntityId),covers=signed.filter(c=>c.payload.start&&c.payload.start<=day&&(!c.payload.end||c.payload.end>=day));values=[day,person.code,person.payload.name,org?.payload.name??null,status,joined,unknown?null:covers.length?'存在覆盖当日的签署登记':'未找到覆盖当日的签署登记',unknown?null:covers.length,covers.map(c=>c.payload.number).filter(Boolean).join('；'),signed.filter(c=>c.payload.start>day).length,signed.filter(c=>c.payload.end&&c.payload.end<day).length,contracts.filter(c=>c.status==='ended').length,contracts.filter(c=>c.status==='draft').length];}
  else {const legal=await catalog(ctx,cutoff,e.payload.legalEntityId,day),renewals=(await latest(ctx,cutoff,'contract',person.id)).filter(c=>c.status!=='cancelled'&&c.payload.renewalOf===e.id);eventDate=e.payload.endedOn??e.payload.end??null;values=[e.payload.number,person.code,person.payload.name,org?.payload.name??null,status,legal?.payload.name??null,({fixed:'固定期限',open:'无固定期限',project:'项目期限'} as any)[e.payload.contractType]??null,({draft:'草稿待登记签署',signed:'已登记签署',ended:'已登记终止',cancelled:'草稿已作废'} as any)[e.status]??e.status,e.payload.start,e.payload.end??null,e.payload.endedOn??null,e.payload.signedOn??null,e.status==='signed'&&e.payload.end?Math.round((Date.parse(e.payload.end+'T00:00:00Z')-Date.parse(day+'T00:00:00Z'))/86400000):null,renewals.map(c=>c.payload.number).join('；'),renewals.map(c=>c.status).join('；'),({labor:'劳动合同',service:'劳务合同',internship:'实习协议'} as any)[e.payload.agreementCategory]??null];}
  rows.push({rowKey:JSON.stringify([e.id]),keyParts:[e.id],orgId,personId:person.id,policyKind:'person',policyKey:person.id,eventDate,currency:null,cells:Object.fromEntries(d.fields.map((f,i)=>[f.fieldId,reportCell(f,values[i])])),sourceVersion:String(e.revision)});
 }
 const complete=source.length<=pageSize;return {rows,nextCursor:complete?null:JSON.stringify([entries.at(-1)!.id]),complete,sourceManifest:{producerId:'M01',producerVersion:'r1-m01-v1',cutoff,scopeOrg:orgId,mode:'internal'}};
}};
export const reportProducers=()=>Object.fromEntries(['workforce','contractCoverage','contractOperations'].map(id=>[id,m01ReportProducer]));
