import {z} from 'zod';
import {HttpError} from './http';
import {commitCommand,replayCommand,commandTrace,digest,type CommandIntent} from './r1-command';
import {exportReportPage} from './r1-report-export-plan';
import {reportActorContext,reportFence,type ReportContext} from './r1-report-context';
import {reportCsvChunk,byteDigest,type ReportObjectStore} from './r1-report-csv';
import {datasetDefinition} from './r1-report-catalog';
const id=z.string().min(1).max(100),input=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('create'),id,query:z.record(z.string().max(12000))}).strict(),
 z.object({operation:z.enum(['cancel','expire','retry']),id,expectedRevision:z.number().int().positive()}).strict()
]);
export async function reportScopeRevision(ctx:ReportContext){return (await ctx.db.prepare('SELECT report_scope_revision AS revision FROM r1_schema_state WHERE tenant_id=?').bind(ctx.member.tenantId).first<{revision:number}>())!.revision;}
export async function loadReportJob(ctx:ReportContext,id:string){const job=await ctx.db.prepare('SELECT * FROM r1_report_jobs WHERE tenant_id=? AND id=? AND requester_id=?').bind(ctx.member.tenantId,id,ctx.member.userId).first<any>();if(!job)throw new HttpError(404,'报表任务不存在','JOB_NOT_FOUND');return job;}
async function jobPolicy(ctx:ReportContext,job:any){if(job.expires_at<=Date.now()||['cancelled','expired'].includes(job.status))throw new HttpError(410,'报表任务已取消或过期','JOB_UNAVAILABLE');if(Date.now()>=job.permission_valid_until)throw new HttpError(409,'任务授权有效期已结束','JOB_AUTHORIZATION_CHANGED');if(job.authorization_revision!==ctx.member.securityStamp!.authorizationRevision||job.scope_revision!==await reportScopeRevision(ctx))throw new HttpError(409,'任务生成以来权限范围已变化，请重新请求','JOB_AUTHORIZATION_CHANGED');if(job.definition_id){const definition=await ctx.db.prepare('SELECT status FROM r1_report_definitions WHERE tenant_id=? AND id=?').bind(ctx.member.tenantId,job.definition_id).first<any>();if(definition?.status==='retired')throw new HttpError(409,'报表定义已停用','DEFINITION_RETIRED');}await reportFence(ctx);}
const exportPage=exportReportPage;
export async function manageReportJob(ctx:ReportContext,intent:CommandIntent){const c=input.parse(intent.payload),t=ctx.member.tenantId,now=Date.now();let plans:((token:string)=>D1PreparedStatement)[]=[],result:Record<string,unknown>={jobId:c.id};
 if(c.operation==='create'){
  const prior=await ctx.db.prepare('SELECT id,request_digest,status FROM r1_report_jobs WHERE tenant_id=? AND requester_id=? AND idempotency_key=?').bind(t,ctx.member.userId,intent.idempotencyKey).first<any>();if(prior){if(prior.request_digest!==await digest(Object.keys(commandTrace(intent)).length?{query:c.query,trace:commandTrace(intent)}:c.query))throw new HttpError(409,'同一导出键内容不同','IDEMPOTENCY_CONFLICT');await reportFence(ctx);return {jobId:prior.id,status:prior.status,replayed:true};}
  if(c.query.cursor)throw new HttpError(400,'导出必须从固定版本起点开始','EXPORT_CURSOR_FORBIDDEN');const replay=await replayCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent);if(replay)return replay;
  const page=await exportPage(ctx,c.query);if(!page.generation)throw new HttpError(503,'来源版本尚不可用','PROJECTION_REQUIRED');
  const columns=page.columns.map((f:any)=>f.fieldId),query:Record<string,string>={...c.query,dataset:page.dataset,...(page.definitionId?{definitionVersion:String(page.reportDefinitionVersion)}:{columns:JSON.stringify(columns)}),limit:'200',...(c.query.snapshot?{}:{generation:page.generation})};delete query.cursor;
  const scope=await reportScopeRevision(ctx),hash=await digest(Object.keys(commandTrace(intent)).length?{query:c.query,trace:commandTrace(intent)}:c.query);plans=[token=>ctx.db.prepare("INSERT INTO r1_report_jobs(tenant_id,id,requester_id,idempotency_key,request_digest,dataset_id,generation_id,query,columns_json,status,runtime_state,created_at,expires_at,authorization_revision,scope_revision,permission_valid_until,definition_id,definition_version) SELECT owner,?,?,?,?,?,?,?,?,'queued','blocked_runtime',?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?").bind(c.id,ctx.member.userId,intent.idempotencyKey,hash,page.dataset,page.generation,JSON.stringify(query),JSON.stringify(columns),now,now+86400000,ctx.member.securityStamp!.authorizationRevision,scope,ctx.member.permissionValidUntil??Number.MAX_SAFE_INTEGER,page.definitionId??null,page.reportDefinitionVersion??null,t,token)];result={...result,status:'queued',runtimeState:'blocked_runtime',reasonCode:'DEP-PLATFORM-01',generation:page.generation};
 }else{const job=await loadReportJob(ctx,c.id),replay=await replayCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent);if(replay)return replay;if(job.revision!==c.expectedRevision)throw new HttpError(409,'任务版本已变化','JOB_CONFLICT');if(c.operation==='retry'){await jobPolicy(ctx,job);if(job.status!=='failed'||job.attempt>=6||!['STORAGE_UNAVAILABLE','EXPORT_OBJECT_UNVERIFIED'].includes(job.reason_code))throw new HttpError(409,'此任务需新请求或人工核对','JOB_RETRY_FORBIDDEN');const p=(token:string)=>ctx.db.prepare("UPDATE r1_report_jobs SET status='queued',reason_code=NULL,revision=revision+1,fencing_token=fencing_token+1,lease_until=0 WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(t,c.id,t,token);return commitCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>[p(token)],{jobId:c.id,status:'queued'});}if(c.operation==='expire'&&job.expires_at>now)throw new HttpError(409,'任务尚未到期','JOB_NOT_EXPIRED');plans=[token=>ctx.db.prepare('UPDATE r1_report_jobs SET status=?,revision=revision+1,fencing_token=fencing_token+1,result_manifest=NULL,lease_until=0 WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(c.operation==='expire'?'expired':'cancelled',t,c.id,t,token),token=>ctx.db.prepare("UPDATE r1_report_file_intents SET status='tombstone' WHERE tenant_id=? AND job_id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(t,c.id,t,token)];result.status=c.operation==='expire'?'expired':'cancelled';}
 await reportFence(ctx);return commitCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>plans.map(p=>p(token)),result);
}
async function workerIntent(ctx:ReportContext,action:string,payload:{jobId:string;[key:string]:unknown}):Promise<CommandIntent>{const id=crypto.randomUUID(),s=ctx.member.securityStamp!,trace=await ctx.db.prepare("SELECT c.command_id,json_extract(o.payload,'$.correlationId') correlation_id FROM r1_report_jobs j JOIN r1_commands c ON c.tenant_id=j.tenant_id AND c.actor_id=j.requester_id AND c.action='M32.export' AND c.idempotency_key=j.idempotency_key JOIN r1_outbox o ON o.tenant_id=c.tenant_id AND o.event_id=c.token WHERE j.tenant_id=? AND j.id=? LIMIT 1").bind(ctx.member.tenantId,payload.jobId).first<{command_id:string;correlation_id:string}>();return {...(trace?{correlationId:trace.correlation_id,causationId:trace.command_id}:{}),commandId:id,idempotencyKey:id,action,payload,expectedWorkspaceRevision:ctx.row.revision,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch};}
export async function claimReportJob(ctx:ReportContext,jobId:string,worker:string){if(!worker||worker.length>100)throw new HttpError(400,'worker标识无效','INVALID_WORKER');const j=await loadReportJob(ctx,jobId),now=Date.now();await jobPolicy(ctx,j);if(!['queued','running'].includes(j.status)||j.lease_until>now)throw new HttpError(409,'任务已被领取或结束','JOB_LEASE_CONFLICT');if(j.attempt>=6)throw new HttpError(409,'任务重试预算耗尽','JOB_RETRY_EXHAUSTED');const active=await ctx.db.prepare("SELECT id FROM r1_report_jobs WHERE tenant_id=? AND status='running' AND lease_until>? AND id<>? LIMIT 1").bind(ctx.member.tenantId,now,jobId).first();if(active)throw new HttpError(409,'租户已有活动导出','TENANT_WORKER_BUSY');
 const intent=await workerIntent(ctx,'M32.export.claim',{jobId,worker,revision:j.revision});await commitCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>[ctx.db.prepare("UPDATE r1_report_jobs SET status='running',runtime_state='manual_isolated_execution',revision=revision+1,lease_owner=?,lease_until=?,fencing_token=fencing_token+1,attempt=attempt+1 WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(worker,now+60000,ctx.member.tenantId,jobId,ctx.member.tenantId,token)],{jobId,fencingToken:j.fencing_token+1});return {jobId,worker,fencingToken:j.fencing_token+1};
}
export async function advanceReportJob(ctx:ReportContext,lease:{jobId:string;worker:string;fencingToken:number},store:ReportObjectStore){const j=await loadReportJob(ctx,lease.jobId),t=ctx.member.tenantId;await jobPolicy(ctx,j);if(j.status!=='running'||j.lease_owner!==lease.worker||j.fencing_token!==lease.fencingToken||j.lease_until<=Date.now())throw new HttpError(409,'导出worker租约已失效','JOB_FENCE_STALE');const page=await exportPage(ctx,JSON.parse(j.query),j.next_cursor),fields=page.columns as NonNullable<ReturnType<typeof datasetDefinition>>['fields'];
 if(page.generation!==j.generation_id)throw new HttpError(409,'导出来源版本发生变化','GENERATION_CONFLICT');
 const bytes=new TextEncoder().encode(reportCsvChunk(fields,page.rows,j.sequence===0));if(bytes.byteLength>4*1024*1024)throw new HttpError(413,'单个CSV块超过4MiB','EXPORT_CHUNK_TOO_LARGE');const hash=await byteDigest(bytes),key=t+'/r1-report/'+j.id+'/'+j.fencing_token+'/'+j.sequence+'/'+crypto.randomUUID();
 // Reserve before put: interrupted puts remain explicit orphans and cannot be downloaded.
 await ctx.db.prepare("INSERT INTO r1_report_file_intents VALUES (?,?,?,?,?,'orphan',?,?)").bind(t,key,j.id,j.fencing_token,Date.now(),hash,bytes.byteLength).run();await store.put(key,bytes);await jobPolicy(ctx,j);
 const stored=await store.get(key);if(!stored||await byteDigest(stored)!==hash)throw new HttpError(503,'暂存文件校验失败','EXPORT_OBJECT_UNVERIFIED');
 const current=await loadReportJob(ctx,j.id);if(current.revision!==j.revision||current.fencing_token!==lease.fencingToken||current.lease_until<=Date.now()||current.status!=='running')throw new HttpError(409,'旧worker不能提交文件','JOB_FENCE_STALE');
 const prior=(await ctx.db.prepare('SELECT sequence,object_key,digest,row_count,byte_count,first_key,last_key FROM r1_report_job_chunks WHERE tenant_id=? AND job_id=? ORDER BY sequence LIMIT 10001').bind(t,j.id).all<any>()).results.map(r=>({...r}));if(prior.length>=10000)throw new HttpError(413,'导出超过块清单预算','EXPORT_MANIFEST_BUDGET');const chunk={sequence:j.sequence+1,object_key:key,digest:hash,row_count:page.rows.length,byte_count:bytes.byteLength,first_key:page.rows[0]?.rowKey??'',last_key:page.rows.at(-1)?.rowKey??''},chunks=[...prior,chunk],ready=!page.hasMore;
 const manifest=ready?JSON.stringify({schemaVersion:'r1-export-v1',generationId:j.generation_id,sourceManifest:page.sourceManifest,query:JSON.parse(j.query),columns:fields.map(f=>({fieldId:f.fieldId,type:f.type,unit:f.unit,nullPolicy:f.nullPolicy})),chunks,digest:await digest(chunks),rows:j.row_count+page.rows.length,bytes:j.byte_count+bytes.byteLength,authorizationRevision:j.authorization_revision,scopeRevision:j.scope_revision}):null;
 const intent=await workerIntent(ctx,ready?'M32.export.ready':'M32.export.chunk',{jobId:j.id,fence:lease.fencingToken,sequence:chunk.sequence,digest:hash});await commitCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>[
 ctx.db.prepare("INSERT INTO r1_adapter_guard SELECT owner,?,CASE WHEN EXISTS(SELECT 1 FROM r1_report_jobs j JOIN r1_schema_state s ON s.tenant_id=j.tenant_id WHERE j.tenant_id=? AND j.id=? AND j.status='running' AND j.fencing_token=? AND j.revision=? AND j.lease_until>CAST((julianday('now')-2440587.5)*86400000 AS INTEGER) AND j.expires_at>CAST((julianday('now')-2440587.5)*86400000 AS INTEGER) AND j.permission_valid_until>CAST((julianday('now')-2440587.5)*86400000 AS INTEGER) AND s.report_scope_revision=j.scope_revision) THEN 1 ELSE 0 END FROM hris_workspaces WHERE owner=? AND last_mutation=?").bind(token,t,j.id,lease.fencingToken,j.revision,t,token),
 ctx.db.prepare('INSERT INTO r1_report_job_chunks SELECT owner,?,?,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(j.id,chunk.sequence,key,hash,chunk.row_count,chunk.byte_count,chunk.first_key,chunk.last_key,lease.fencingToken,t,token),
 ctx.db.prepare("UPDATE r1_report_file_intents SET status='referenced' WHERE tenant_id=? AND object_key=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(t,key,t,token),
 ctx.db.prepare('UPDATE r1_report_jobs SET status=?,revision=revision+1,sequence=sequence+1,next_cursor=?,row_count=row_count+?,byte_count=byte_count+?,lease_until=?,result_manifest=?,reason_code=NULL WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?) AND lease_until>CAST((julianday(\'now\')-2440587.5)*86400000 AS INTEGER)').bind(ready?'ready':'running',page.nextCursor,chunk.row_count,chunk.byte_count,ready?0:Date.now()+60000,manifest,t,j.id,t,token)
 ],{jobId:j.id,status:ready?'ready':'running',sequence:chunk.sequence});return {jobId:j.id,status:ready?'ready':'running',rows:j.row_count+page.rows.length};
}
export async function readReportJob(ctx:ReportContext,id:string){const j=await loadReportJob(ctx,id);let available=true;try{await jobPolicy(ctx,j);}catch{available=false;}await reportFence(ctx);return {jobId:j.id,status:j.status,runtimeState:j.runtime_state,revision:j.revision,reasonCode:j.reason_code??(j.runtime_state==='blocked_runtime'?'DEP-PLATFORM-01':null),rows:available?j.row_count:null,bytes:available?j.byte_count:null,expiresAt:j.expires_at,generation:j.generation_id,downloadable:available&&j.status==='ready'&&j.expires_at>Date.now()};}
export async function downloadReportChunk(ctx:ReportContext,id:string,sequence:number,store:ReportObjectStore){const j=await loadReportJob(ctx,id);await jobPolicy(ctx,j);if(j.status!=='ready'||!j.result_manifest)throw new HttpError(409,'导出尚未可用','JOB_NOT_READY');await exportPage(ctx,JSON.parse(j.query));const m=JSON.parse(j.result_manifest);if(await digest(m.chunks)!==m.digest)throw new HttpError(409,'导出清单校验失败','MANIFEST_DIGEST_CONFLICT');const part=m.chunks.find((p:any)=>p.sequence===sequence);if(!part)throw new HttpError(404,'导出块不存在','CHUNK_NOT_FOUND');const bytes=await store.get(part.object_key);if(!bytes||await byteDigest(bytes)!==part.digest)throw new HttpError(503,'导出文件不可核验','EXPORT_OBJECT_UNVERIFIED');await jobPolicy(ctx,j);return {bytes,manifest:{...m,chunks:m.chunks.map(({object_key,...rest}:any)=>rest)}};}
export async function reportWorkerContext(db:D1Database,tenant:string,actor:string){return reportActorContext(db,tenant,actor);}

/** Executor boundary persists a diagnosable local failure without hiding the original exception. */
export async function runReportJobStep(ctx:ReportContext,lease:{jobId:string;worker:string;fencingToken:number},store:ReportObjectStore){try{return await advanceReportJob(ctx,lease,store);}catch(error){const current=await reportActorContext(ctx.db,ctx.member.tenantId,ctx.member.userId),job=await loadReportJob(current,lease.jobId);if(job.status==='running'&&job.fencing_token===lease.fencingToken&&job.lease_owner===lease.worker){const intent=await workerIntent(current,'M32.export.failed',{jobId:job.id,fence:lease.fencingToken,reasonCode:error instanceof HttpError?error.machineCode??'STORAGE_UNAVAILABLE':'STORAGE_UNAVAILABLE'});await commitCommand(current.db,current.member,current.member.securityStamp!,intent,token=>[current.db.prepare("UPDATE r1_report_jobs SET status='failed',revision=revision+1,lease_until=0,reason_code=? WHERE tenant_id=? AND id=? AND fencing_token=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(error instanceof HttpError?error.machineCode??'STORAGE_UNAVAILABLE':'STORAGE_UNAVAILABLE',current.member.tenantId,job.id,lease.fencingToken,current.member.tenantId,token)],{jobId:job.id,status:'failed'});}throw error;}}
