import {z} from 'zod';
import {HttpError} from './http';
import {authorizeTuple} from './r1-authorization';
import {commitCommand,replayCommand,digest,type CommandIntent} from './r1-command';
import {validateReportDefinition} from './r1-report-definition';
import type {ReportContext} from './r1-report-context';
const id=z.string().min(1).max(100),command=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('save'),id,orgId:id,title:z.string().min(1).max(100),expectedRevision:z.number().int().nonnegative(),definition:z.unknown()}).strict(),
 z.object({operation:z.enum(['publish','retire']),id,expectedRevision:z.number().int().positive()}).strict(),
]);
export async function manageReportDefinition(ctx:ReportContext,intent:CommandIntent){const c=command.parse(intent.payload),db=ctx.db,t=ctx.member.tenantId,root=await db.prepare('SELECT * FROM r1_report_definitions WHERE tenant_id=? AND id=?').bind(t,c.id).first<any>();if(c.operation!=='save'&&!root)throw new HttpError(404,'报表定义不存在','NOT_FOUND');const orgId=root?.org_id??(c.operation==='save'?c.orgId:''),source=c.operation==='save'?c.definition:JSON.parse(root.draft),v=validateReportDefinition(source),access=async(action:string,field='record')=>authorizeTuple(db,ctx.member,{objectType:'M32',action:v.dataset.datasetId+'.'+action,orgId,personId:ctx.member.employeeId??'',field,historyMode:'current'});await access('manage');for(const f of v.usedFields){await access('read',f);await access('manage',f);}const replay=await replayCommand(db,ctx.member,ctx.member.securityStamp!,intent);if(replay)return replay;if((root?.revision??0)!==c.expectedRevision)throw new HttpError(409,'报表草稿版本已变化','REVISION_CONFLICT');if(root&&root.dataset_id!==v.dataset.datasetId||c.operation==='save'&&root&&c.orgId!==orgId)throw new HttpError(409,'稳定定义不能换数据集或组织','DEFINITION_IDENTITY_CONFLICT');
 const plans:((token:string)=>D1PreparedStatement)[]=[],guard=(sql:string,args:unknown[])=>(token:string)=>db.prepare(sql).bind(...args,t,token);let result:Record<string,unknown>={definitionId:c.id};
 if(c.operation==='save'){if(root?.status==='retired')throw new HttpError(409,'停用定义不得直接恢复','DEFINITION_RETIRED');plans.push(guard("INSERT INTO r1_report_definitions SELECT owner,?,?,?,?,?,1,'draft',0 FROM hris_workspaces WHERE owner=? AND last_mutation=? ON CONFLICT(tenant_id,id) DO UPDATE SET title=excluded.title,draft=excluded.draft,revision=r1_report_definitions.revision+1",[c.id,v.dataset.datasetId,orgId,c.title,JSON.stringify(v.definition)]));result.revision=c.expectedRevision+1;}
 else if(c.operation==='publish'){if(root.status==='retired')throw new HttpError(409,'已停用定义不可发布','DEFINITION_RETIRED');const version=root.published_version+1,hash=await digest(v.definition),prior=await db.prepare('SELECT digest FROM r1_report_definition_versions WHERE tenant_id=? AND definition_id=? AND version=?').bind(t,c.id,root.published_version).first<{digest:string}>();if(prior?.digest===hash)throw new HttpError(409,'该内容已发布','DEFINITION_ALREADY_PUBLISHED');plans.push(guard('INSERT INTO r1_report_definition_versions SELECT owner,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?',[c.id,version,hash,JSON.stringify(v.definition),ctx.member.userId,new Date().toISOString()]));plans.push(guard("UPDATE r1_report_definitions SET published_version=?,status='published',revision=revision+1 WHERE id=? AND tenant_id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)",[version,c.id,t]));result={...result,version,digest:hash};}
 else {plans.push(guard("UPDATE r1_report_definitions SET status='retired',revision=revision+1 WHERE id=? AND tenant_id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)",[c.id,t]));result.status='retired';}
 return commitCommand(db,ctx.member,ctx.member.securityStamp!,intent,token=>plans.map(p=>p(token)),result);
}
