import {HttpError} from './http';
import type {ReportField} from './r1-report-catalog';
export type ReportCell={value:string|number|boolean|null;state:'value'|'null'|'not_configured'|'unavailable';reasonCode:string|null};
export function decimalParts(v:string|number){const s=String(v);if(!/^-?\d{1,16}(\.\d{1,6})?$/.test(s))throw new HttpError(400,'小数超出明确精度范围','DECIMAL_INVALID');const [whole,fraction='']=s.replace('-','').split('.');return {n:BigInt(whole+fraction)*(s.startsWith('-')?-BigInt(1):BigInt(1)),scale:fraction.length};}
export function decimalString(n:bigint,scale:number){const sign=n<BigInt(0)?'-':'',raw=(n<BigInt(0)?-n:n).toString().padStart(scale+1,'0');if(!scale)return sign+raw;return (sign+raw.slice(0,-scale)+'.'+raw.slice(-scale)).replace(/\.?0+$/,'');}
export function reportCell(field:ReportField,value:unknown,state?:ReportCell['state'],reasonCode:string|null=null):ReportCell{
 if(value===null||value===undefined||value==='')return {value:null,state:state??'null',reasonCode:reasonCode??'missing_source'};
 if(state&&state!=='value')throw new HttpError(400,'缺值状态不得带数值','CELL_STATE_CONFLICT');
 if(['integer','money_cents'].includes(field.type)){if(!Number.isSafeInteger(value))throw new HttpError(400,'整数或金额超出安全范围','UNSAFE_INTEGER');}
 else if(field.type==='decimal'){if(typeof value==='number'&&(!Number.isFinite(value)||Math.abs(value)>Number.MAX_SAFE_INTEGER))throw new HttpError(400,'小数数值超出安全范围，请使用明确十进制文本','DECIMAL_INVALID');const parts=decimalParts(value as string|number);value=decimalString(parts.n,parts.scale);}
 else if(field.type==='boolean'){if(typeof value!=='boolean')throw new HttpError(400,'布尔值无效','CELL_TYPE_INVALID');}
 else {if(typeof value!=='string'||value.length>65536)throw new HttpError(400,'字段文本无效或过大','CELL_TYPE_INVALID');if(field.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T00:00:00Z'))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value))throw new HttpError(400,'业务日期无效','CELL_TYPE_INVALID');if(field.type==='timestamp'&&(!Number.isFinite(Date.parse(value))||!Number.isFinite(Date.parse(value.slice(0,10)+'T00:00:00Z'))||new Date(value.slice(0,10)+'T00:00:00Z').toISOString().slice(0,10)!==value.slice(0,10)||!/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(value)))throw new HttpError(400,'时间需明确时区','CELL_TYPE_INVALID');}
 if(field.type==='timestamp')value=new Date(value as string).toISOString();
 return {value:value as ReportCell['value'],state:'value',reasonCode:null};
}
export function sumCells(cells:ReportCell[],unit:string,currencies:string[]=[]){if(['money_cents','currency_cents'].includes(unit)&&new Set(currencies).size>1)throw new HttpError(400,'不同币种不可相加','CURRENCY_MISMATCH');const known=cells.filter(c=>c.state==='value'),missingCount=cells.length-known.length;if(!known.length)return {value:null,state:'null',reasonCode:'unknown_values',knownCount:0,missingCount};const parts=known.map(c=>decimalParts(c.value as string|number)),scale=Math.max(...parts.map(p=>p.scale)),n=parts.reduce((n,p)=>n+p.n*BigInt(10)**BigInt(scale-p.scale),BigInt(0));if(['money_cents','currency_cents','integer'].includes(unit)&&(n>BigInt(Number.MAX_SAFE_INTEGER)||n<BigInt(Number.MIN_SAFE_INTEGER)))throw new HttpError(400,'汇总整数溢出','UNSAFE_INTEGER');return {value:scale||n>BigInt(Number.MAX_SAFE_INTEGER)||n<BigInt(Number.MIN_SAFE_INTEGER)?decimalString(n,scale):Number(n),state:'value',reasonCode:null,knownCount:known.length,missingCount};}
export function ratio(numerator:ReportCell,denominator:ReportCell,percent=false):ReportCell{if(numerator.state!=='value'||denominator.state!=='value')return {value:null,state:'null',reasonCode:'unknown_denominator'};const n=decimalParts(numerator.value as string|number),d=decimalParts(denominator.value as string|number);if(d.n===BigInt(0))return {value:null,state:'null',reasonCode:'zero_denominator'};const top=n.n*BigInt(10)**BigInt(d.scale)*(percent?BigInt(10000):BigInt(100)),bottom=d.n*BigInt(10)**BigInt(n.scale),sign=(top<BigInt(0))!==(bottom<BigInt(0))?-BigInt(1):BigInt(1),a=top<BigInt(0)?-top:top,b=bottom<BigInt(0)?-bottom:bottom;return {value:decimalString(sign*((a+b/BigInt(2))/b),2),state:'value',reasonCode:null};}
export function legacyCells(dataset:{fields:ReportField[]},columns:string[],row:unknown[]){if(new Set(columns).size!==columns.length||columns.length!==row.length)throw new HttpError(409,'旧列标签重复或宽度不符','LEGACY_MAPPING_INVALID');return Object.fromEntries(columns.map((label,i)=>{const f=dataset.fields.find(f=>f.label===label);if(!f)throw new HttpError(409,'未知旧列，不能推断字段','LEGACY_MAPPING_INVALID');let value=row[i];if(f.type==='boolean'&&typeof value==='string')value=value==='是'||value==='通过'?true:value==='否'||value==='未通过'?false:null;if(f.type==='timestamp'&&typeof value==='string'&&/^\d{4}-\d{2}-\d{2} /.test(value))value=value.replace(' ','T')+'+08:00';return [f.fieldId,reportCell(f,value)];}));}
