import {HttpError} from './http';
import {readReport} from './r1-report-query';
import {aggregateDefinition} from './r1-report-aggregate';
import {validateReportDefinition} from './r1-report-definition';
import {digest,canonical} from './r1-command';
import type {ReportContext} from './r1-report-context';
/** Resolve and pin immutable published definitions before exporting; never export an editable draft. */
export async function exportReportPage(ctx:ReportContext,raw:Record<string,string>,cursor?:string|null){const query={...raw},definitionId=query.definitionId,version=query.definitionVersion;delete query.definitionId;delete query.definitionVersion;if(!definitionId&&version)throw new HttpError(400,'版本需关联报表定义','DEFINITION_REQUIRED');let definition:any,root:any,definitionVersion:number|undefined;
 if(definitionId){if(['columns','filter','sort'].some(k=>k in query))throw new HttpError(400,'已发布定义不能覆盖','DEFINITION_OVERRIDE_FORBIDDEN');root=await ctx.db.prepare('SELECT * FROM r1_report_definitions WHERE tenant_id=? AND id=?').bind(ctx.member.tenantId,definitionId).first<any>();if(!root?.published_version||root.status==='retired')throw new HttpError(409,'报表定义未发布或已停用','DEFINITION_NOT_PUBLISHED');definitionVersion=version?Number(version):root.published_version;if(!Number.isSafeInteger(definitionVersion)||definitionVersion!<1)throw new HttpError(400,'定义版本无效','DEFINITION_VERSION_INVALID');const saved=await ctx.db.prepare('SELECT payload,digest FROM r1_report_definition_versions WHERE tenant_id=? AND definition_id=? AND version=?').bind(ctx.member.tenantId,definitionId,definitionVersion).first<any>();if(!saved)throw new HttpError(404,'定义版本不存在','DEFINITION_VERSION_NOT_FOUND');definition=validateReportDefinition(JSON.parse(saved.payload));if(await digest(definition.definition)!==saved.digest)throw new HttpError(409,'定义摘要不一致','DEFINITION_DIGEST_CONFLICT');if(query.dataset&&query.dataset!==root.dataset_id)throw new HttpError(400,'数据集不一致','DATASET_MISMATCH');query.dataset=root.dataset_id;}
 if(definition?.definition.metrics.length){if(cursor)throw new HttpError(400,'同步汇总无明细游标','AGGREGATE_CURSOR_FORBIDDEN');const result:any=await aggregateDefinition(ctx,new URLSearchParams(query),definition.definition,root.org_id,['read','export']);const fields=definition.definition.groupBy.map((id:string)=>definition.dataset.fields.find((f:any)=>f.fieldId===id)),columns=[...fields,...definition.definition.metrics.map((m:any)=>({fieldId:m.id,label:m.id,type:definition.metricTypes[m.id].type,unit:definition.metricTypes[m.id].unit,nullPolicy:'state_and_reason'}))];return {...result,definitionId,reportDefinitionVersion:definitionVersion,columns,rows:(result.groups??[]).map((g:any)=>({rowKey:canonical(g.cells),cells:{...g.cells,...g.metrics}})),hasMore:false,nextCursor:null};}
 const result:any=await readReport(ctx,new URLSearchParams({...query,limit:'200',...(cursor?{cursor}:{})}),{additionalActions:['export'],cursorTtlMs:86400000,definition:definition?.definition,scopeOrg:root?.org_id});return {...result,definitionId,reportDefinitionVersion:definitionVersion};
}
