import {z} from 'zod';
import {HttpError} from './http';
import {authorizeTuple} from './r1-authorization';
import {commitCommand,replayCommand,digest,type CommandIntent} from './r1-command';
import {reportActorContext,reportFence,type ReportContext} from './r1-report-context';
import {readReport} from './r1-report-query';
import {reportPolicy} from './r1-report-permissions';
import {reportScopeRevision} from './r1-report-jobs';
import {scheduleSchema,scheduleOccurrence} from './r1-report-schedule';
import {datasetDefinition} from './r1-report-catalog';
const id=z.string().min(1).max(100),base={id,expectedRevision:z.number().int().nonnegative()},input=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('save'),...base,orgId:id,title:z.string().min(1).max(100),query:z.record(z.string().max(12000)),recipientIds:z.array(id).min(1).max(20),schedule:scheduleSchema,channel:z.literal('authenticated_link')}).strict(),
 z.object({operation:z.enum(['block','activate','expire','acceptTransfer']),...base}).strict(),
 z.object({operation:z.literal('proposeTransfer'),...base,targetOwner:id}).strict()
]);
const scheduleOf=(s:any)=>({timezone:s.timezone,frequency:s.frequency,weekDays:JSON.parse(s.week_days),localSendTime:s.local_send_time,gapPolicy:s.gap_policy,repeatPolicy:s.repeat_policy,startAt:s.start_at,endAt:s.end_at});
async function subscription(ctx:ReportContext,id:string){const s=await ctx.db.prepare('SELECT * FROM r1_report_subscriptions WHERE tenant_id=? AND id=?').bind(ctx.member.tenantId,id).first<any>();if(!s)throw new HttpError(404,'订阅不存在','SUBSCRIPTION_NOT_FOUND');return s;}
async function manage(ctx:ReportContext,s:{org_id:string}){return authorizeTuple(ctx.db,ctx.member,{objectType:'M32',action:'subscription.manage',orgId:s.org_id,personId:'',field:'record',historyMode:'current'});}
async function recipientQuery(owner:ReportContext,recipient:ReportContext,raw:Record<string,string>,orgId:string):Promise<Record<string,string>>{const history=!!raw.snapshot,policies=await Promise.all([reportPolicy(owner,raw.dataset,'read',history),reportPolicy(owner,raw.dataset,'subscribe',history),reportPolicy(recipient,raw.dataset,'read',history)]),dataset=datasetDefinition(raw.dataset)!;if(policies.some(p=>!p.scopeOrgs.includes(orgId)))throw new HttpError(403,'订阅双方无该范围权限','SUBSCRIPTION_SCOPE_FORBIDDEN');const requested:string[]=raw.columns?JSON.parse(raw.columns):dataset.fields.map(f=>f.fieldId),fields=requested.filter(id=>policies.every(p=>p.fields.has(id)));if(!fields.length)throw new HttpError(403,'订阅双方没有共同字段','SUBSCRIPTION_FIELD_FORBIDDEN');owner.member.permissionValidUntil=Math.min(owner.member.permissionValidUntil??Number.MAX_SAFE_INTEGER,recipient.member.permissionValidUntil??Number.MAX_SAFE_INTEGER);return {...raw,columns:JSON.stringify(fields)};}
async function intersectRead(owner:ReportContext,recipient:ReportContext,query:Record<string,string>){return readReport(owner,new URLSearchParams(query),{additionalActions:['subscribe'],policyActors:[{ctx:recipient,actions:['read']}]}) as Promise<any>;}
export async function manageReportSubscription(ctx:ReportContext,intent:CommandIntent){const c=input.parse(intent.payload),t=ctx.member.tenantId,old=await ctx.db.prepare('SELECT * FROM r1_report_subscriptions WHERE tenant_id=? AND id=?').bind(t,c.id).first<any>();if(c.operation!=='save'&&!old)throw new HttpError(404,'订阅不存在','SUBSCRIPTION_NOT_FOUND');if(old&&ctx.member.userId!==(c.operation==='acceptTransfer'?old.proposed_owner:old.owner_id))throw new HttpError(403,'仅订阅所有者或指定接受者可操作','SUBSCRIPTION_OWNER_REQUIRED');const org=c.operation==='save'?c.orgId:old.org_id;await manage(ctx,{org_id:org});const replay=await replayCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent);if(replay)return replay;if((old?.revision??0)!==c.expectedRevision)throw new HttpError(409,'订阅版本已变化','SUBSCRIPTION_CONFLICT');if(old&&old.org_id!==org)throw new HttpError(409,'订阅保护组织不可变','SUBSCRIPTION_SCOPE_IMMUTABLE');const revision=c.expectedRevision+1,plans:((token:string)=>D1PreparedStatement)[]=[],at=new Date().toISOString();
 if(c.operation==='save'){
  if(new Set(c.recipientIds).size!==c.recipientIds.length||c.query.cursor||c.query.limit)throw new HttpError(400,'收件人重复或订阅含分页截点','SUBSCRIPTION_INPUT_INVALID');
  for(const actor of c.recipientIds){const recipient=await reportActorContext(ctx.db,t,actor),query=await recipientQuery(ctx,recipient,c.query,org);await intersectRead(ctx,recipient,{...query,limit:'1'});}
  plans.push(token=>ctx.db.prepare("INSERT INTO r1_report_subscriptions SELECT owner,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'active',?,NULL,? FROM hris_workspaces WHERE owner=? AND last_mutation=? ON CONFLICT(tenant_id,id) DO UPDATE SET title=excluded.title,query_json=excluded.query_json,recipient_ids=excluded.recipient_ids,timezone=excluded.timezone,frequency=excluded.frequency,week_days=excluded.week_days,local_send_time=excluded.local_send_time,gap_policy=excluded.gap_policy,repeat_policy=excluded.repeat_policy,start_at=excluded.start_at,end_at=excluded.end_at,channel=excluded.channel,status='active',revision=excluded.revision,proposed_owner=NULL").bind(c.id,ctx.member.userId,org,c.title,JSON.stringify(c.query),JSON.stringify(c.recipientIds),c.schedule.timezone,c.schedule.frequency,JSON.stringify(c.schedule.weekDays),c.schedule.localSendTime,c.schedule.gapPolicy,c.schedule.repeatPolicy,c.schedule.startAt,c.schedule.endAt,c.channel,revision,at,t,token));
 }else if(c.operation==='proposeTransfer'){
  if(c.targetOwner===old.owner_id)throw new HttpError(400,'目标已是所有者','TRANSFER_SAME_OWNER');const target=await reportActorContext(ctx.db,t,c.targetOwner);await manage(target,old);ctx.member.permissionValidUntil=Math.min(ctx.member.permissionValidUntil??Number.MAX_SAFE_INTEGER,target.member.permissionValidUntil??Number.MAX_SAFE_INTEGER);plans.push(token=>ctx.db.prepare('UPDATE r1_report_subscriptions SET proposed_owner=?,revision=? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(c.targetOwner,revision,t,c.id,t,token));
 }else{
  if(c.operation==='expire'&&Date.parse(old.end_at)>Date.now())throw new HttpError(409,'订阅尚未到期','SUBSCRIPTION_NOT_EXPIRED');if(c.operation==='activate'&&Date.parse(old.end_at)<=Date.now())throw new HttpError(409,'已过期订阅需重新配置','SUBSCRIPTION_EXPIRED');plans.push(token=>ctx.db.prepare('UPDATE r1_report_subscriptions SET owner_id=?,status=?,revision=?,proposed_owner=NULL WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(c.operation==='acceptTransfer'?ctx.member.userId:old.owner_id,c.operation==='block'?'blocked':c.operation==='expire'?'expired':old.status==='expired'?'expired':c.operation==='activate'?'active':old.status,revision,t,c.id,t,token));
 }
 plans.push(token=>ctx.db.prepare("UPDATE r1_report_subscription_results SET delivery_state='suppressed',reason_code='SUBSCRIPTION_REVISION_CHANGED' WHERE tenant_id=? AND subscription_id=? AND delivery_state IN ('pending','failed') AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(t,c.id,t,token));
 plans.push(token=>ctx.db.prepare('INSERT INTO r1_report_subscription_events SELECT owner,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(intent.commandId,c.id,revision,ctx.member.userId,c.operation,JSON.stringify({previousOwner:old?.owner_id??null,nextOwner:c.operation==='acceptTransfer'?ctx.member.userId:old?.owner_id??ctx.member.userId}),at,t,token));await reportFence(ctx);return commitCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>plans.map(p=>p(token)),{subscriptionId:c.id,revision,runtimeState:'blocked_runtime'});
}
function internalIntent(ctx:ReportContext,action:string,payload:unknown):CommandIntent{const commandId=crypto.randomUUID(),s=ctx.member.securityStamp!;return {commandId,idempotencyKey:commandId,action,payload,expectedWorkspaceRevision:ctx.row.revision,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch};}
function active(s:any){if(s.status!=='active'||Date.parse(s.end_at)<=Date.now())throw new HttpError(409,'订阅已屏蔽或过期','SUBSCRIPTION_INACTIVE');}
/** One local occurrence and one existing recipient per transaction; scheduler adapter is deliberately absent. */
export async function generateSubscriptionResult(ctx:ReportContext,id:string,localDay:string,recipientId:string){const s=await subscription(ctx,id);if(s.owner_id!==ctx.member.userId)throw new HttpError(403,'须由当前订阅所有者生成','SUBSCRIPTION_OWNER_REQUIRED');active(s);if(!JSON.parse(s.recipient_ids).includes(recipientId))throw new HttpError(403,'收件人不在订阅中','RECIPIENT_NOT_REGISTERED');const occurrence=scheduleOccurrence(scheduleOf(s),localDay);if(occurrence.state!=='scheduled')return occurrence;if(Date.parse(occurrence.occurrenceAt)>Date.now())throw new HttpError(409,'订阅周期尚未到达','OCCURRENCE_NOT_DUE');const prior=await ctx.db.prepare('SELECT id,delivery_state FROM r1_report_subscription_results WHERE tenant_id=? AND subscription_id=? AND subscription_revision=? AND occurrence_at=? AND recipient_id=? AND channel=?').bind(ctx.member.tenantId,id,s.revision,occurrence.occurrenceAt,recipientId,s.channel).first<any>();if(prior)return {resultId:prior.id,state:prior.delivery_state,replayed:true};
 const recipient=await reportActorContext(ctx.db,ctx.member.tenantId,recipientId),query=await recipientQuery(ctx,recipient,JSON.parse(s.query_json),s.org_id),page=await intersectRead(ctx,recipient,{...query,limit:'1'});if(!page.generation)throw new HttpError(503,'订阅来源尚不可用','PROJECTION_REQUIRED');if(!query.snapshot)query.generation=page.generation;const resultId=crypto.randomUUID(),scope=await reportScopeRevision(ctx),manifest={generationId:page.generation,sourceManifest:page.sourceManifest,query,ownerId:s.owner_id,recipientId,subscriptionId:id,subscriptionRevision:s.revision,occurrence,scopeRevision:scope,authorizationRevision:ctx.member.securityStamp!.authorizationRevision,kind:'recipient_fixed_source_current_policy_result',rowTotal:null},hash=await digest(manifest),intent=internalIntent(ctx,'M32.subscription.generate',{subscriptionId:id,resultId,recipientId,occurrenceAt:occurrence.occurrenceAt,manifestDigest:hash});
 await reportFence(ctx);await commitCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>[ctx.db.prepare("INSERT INTO r1_report_subscription_results(tenant_id,id,subscription_id,subscription_revision,owner_id,recipient_id,occurrence_at,local_day,local_send_time,utc_offset_minutes,channel,query_json,generation_id,manifest,manifest_digest,authorization_revision,scope_revision,delivery_state) SELECT owner,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'pending' FROM hris_workspaces WHERE owner=? AND last_mutation=?").bind(resultId,id,s.revision,s.owner_id,recipientId,occurrence.occurrenceAt,occurrence.localDay,occurrence.localSendTime,occurrence.utcOffsetMinutes,s.channel,JSON.stringify(query),page.generation,JSON.stringify(manifest),hash,ctx.member.securityStamp!.authorizationRevision,scope,ctx.member.tenantId,token)],{resultId,state:'pending',mode:'local_manual'});return {resultId,state:'pending'};
}
export async function readSubscriptionResult(ctx:ReportContext,id:string,cursor?:string){const r=await ctx.db.prepare('SELECT * FROM r1_report_subscription_results WHERE tenant_id=? AND id=? AND recipient_id=?').bind(ctx.member.tenantId,id,ctx.member.userId).first<any>();if(!r)throw new HttpError(404,'订阅结果不存在','SUBSCRIPTION_RESULT_NOT_FOUND');const s=await subscription(ctx,r.subscription_id);active(s);if(!JSON.parse(s.recipient_ids).includes(ctx.member.userId))throw new HttpError(403,'已不在订阅收件人中','RECIPIENT_NOT_REGISTERED');if(await digest(JSON.parse(r.manifest))!==r.manifest_digest)throw new HttpError(409,'订阅结果清单不一致','MANIFEST_DIGEST_CONFLICT');const owner=await reportActorContext(ctx.db,ctx.member.tenantId,s.owner_id),query=await recipientQuery(owner,ctx,JSON.parse(r.query_json),s.org_id);return {...await intersectRead(owner,ctx,{...query,...(cursor?{cursor}:{})}),subscriptionResultId:r.id,subscriptionRevision:r.subscription_revision,deliveryState:r.delivery_state};}
export type SubscriptionTransport={mode:'simulated';send:(id:string,payload:{recipientId:string;path:string;manifestDigest:string})=>Promise<{state:'sent'|'unknown'|'failed';receiptId:string|null;manifestDigest?:string;confirmedNoEffect?:boolean}>;query:(id:string)=>Promise<{state:'sent'|'unknown'|'failed';receiptId:string|null;manifestDigest?:string;confirmedNoEffect?:boolean}>};
export async function dispatchSubscriptionResult(context:()=>Promise<ReportContext>,resultId:string,transport?:SubscriptionTransport){let ctx=await context();const t=ctx.member.tenantId,r=await ctx.db.prepare('SELECT * FROM r1_report_subscription_results WHERE tenant_id=? AND id=?').bind(t,resultId).first<any>();if(!r)throw new HttpError(404,'订阅结果不存在','SUBSCRIPTION_RESULT_NOT_FOUND');const s=await subscription(ctx,r.subscription_id);if(ctx.member.userId!==s.owner_id)throw new HttpError(403,'须由当前所有者核对投递','SUBSCRIPTION_OWNER_REQUIRED');await manage(ctx,s);if(!transport)return {state:'not_configured',reasonCode:'DEP-PLATFORM-01',mode:'disabled'};if(transport.mode!=='simulated')throw new HttpError(403,'本轮禁止真实通知','EXTERNAL_MODE_FORBIDDEN');if(['sent','suppressed'].includes(r.delivery_state))return {state:r.delivery_state};
 const update=async(state:string,receipt:string|null,reason:string|null,increment=0)=>{ctx=await context();await manage(ctx,s);const intent=internalIntent(ctx,'M32.subscription.delivery',{resultId,state,receipt}),expected=r.delivery_state;await commitCommand(ctx.db,ctx.member,ctx.member.securityStamp!,intent,token=>[ctx.db.prepare('INSERT INTO r1_adapter_guard SELECT owner,?,CASE WHEN EXISTS(SELECT 1 FROM r1_report_subscription_results WHERE tenant_id=? AND id=? AND delivery_state=? AND attempt=?) THEN 1 ELSE 0 END FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(token,t,resultId,expected,r.attempt,t,token),ctx.db.prepare('UPDATE r1_report_subscription_results SET delivery_state=?,receipt_id=?,reason_code=?,attempt=attempt+? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(state,receipt,reason,increment,t,resultId,t,token)],{resultId,state});r.delivery_state=state;r.attempt+=increment;};
 const reconcile=async(receipt:Awaited<ReturnType<SubscriptionTransport['query']>>)=>{if(receipt.state==='unknown')return {state:'unknown',action:'query_receipt'};if(!receipt.receiptId||receipt.manifestDigest!==r.manifest_digest)throw new HttpError(409,'回执与原订阅清单不匹配','RECEIPT_CONFLICT');if(receipt.state==='failed'&&!receipt.confirmedNoEffect)return {state:'unknown',action:'query_receipt'};await update(receipt.state,receipt.receiptId,receipt.state==='failed'?'CONFIRMED_NO_EFFECT':null);return {state:receipt.state,action:'query_receipt'};};
 if(r.delivery_state==='unknown')return reconcile(await transport.query(resultId));
 active(s);if(s.revision!==r.subscription_revision)throw new HttpError(409,'订阅版本变化阻止投递','SUBSCRIPTION_CONFLICT');if(r.delivery_state==='failed'&&r.reason_code!=='CONFIRMED_NO_EFFECT')throw new HttpError(409,'未知副作用先核回执','RECEIPT_REQUIRED');if(r.attempt>=6)throw new HttpError(409,'重试预算耗尽','DELIVERY_RETRY_EXHAUSTED');
 const recipient=await reportActorContext(ctx.db,t,r.recipient_id),q=await recipientQuery(ctx,recipient,JSON.parse(r.query_json),s.org_id);await intersectRead(ctx,recipient,{...q,limit:'1'});await update('unknown',null,null,1);
 ctx=await context();const current=await subscription(ctx,r.subscription_id);active(current);if(current.revision!==r.subscription_revision)throw new HttpError(409,'领取后订阅变化，先查原回执','SUBSCRIPTION_CONFLICT');const nowRecipient=await reportActorContext(ctx.db,t,r.recipient_id);await intersectRead(ctx,nowRecipient,{...await recipientQuery(ctx,nowRecipient,JSON.parse(r.query_json),s.org_id),limit:'1'});
 let receipt;try{receipt=await transport.send(resultId,{recipientId:r.recipient_id,path:'/reports/subscriptions/results/'+encodeURIComponent(resultId),manifestDigest:r.manifest_digest});}catch{return {state:'unknown',action:'query_receipt'};}return reconcile(receipt);
}
