import {z} from 'zod';
import {HttpError} from './http';
import {datasetDefinition,reportSchemaVersion,registeredMeasureInputs,type ReportField} from './r1-report-catalog';
import {reportCell} from './r1-report-values';
const name=z.string().min(1).max(100),atom=z.union([z.string().max(2000),z.number().int().safe(),z.boolean(),z.null()]);
const filter:z.ZodType<any>=z.lazy(()=>z.union([z.object({op:z.enum(['and','or']),args:z.array(filter).min(1).max(50)}).strict(),z.object({op:z.enum(['eq','ne','lt','lte','gt','gte','in','isNull']),field:name,value:z.union([atom,z.array(atom).max(100)]).optional()}).strict()]));
const expression:z.ZodType<any>=z.lazy(()=>z.union([z.object({op:z.literal('field'),field:name}).strict(),z.object({op:z.enum(['sum','count','countDistinct','min','max','avg']),field:name.optional(),where:filter.optional()}).strict(),z.object({op:z.enum(['add','subtract','ratio']),left:expression,right:expression,percent:z.boolean().optional()}).strict()]));
export const definitionSchema=z.object({datasetId:name,schemaVersion:z.literal(reportSchemaVersion),columns:z.array(name).min(1).max(100),filter:filter.optional(),groupBy:z.array(name).max(20).default([]),sort:z.array(z.object({field:name,direction:z.enum(['asc','desc'])}).strict()).max(5).default([]),metrics:z.array(z.object({id:name,expression}).strict()).max(50).default([]),joins:z.array(z.object({id:name,generationId:name.optional(),strategy:z.enum(['distinct_root','preaggregate']),fields:z.array(name).max(20).default([])}).strict()).max(5).default([])}).strict();
export function validateReportDefinition(input:unknown,allowedFields?:ReadonlySet<string>){
 const stack=[{v:input,depth:0}],seen=new Set<unknown>();let size=0;while(stack.length){const {v,depth}=stack.pop()!;if(++size>2000||depth>24)throw new HttpError(400,'表达式复杂度超限','EXPRESSION_BUDGET_EXCEEDED');if(v&&typeof v==='object'){if(seen.has(v))throw new HttpError(400,'表达式循环引用','EXPRESSION_BUDGET_EXCEEDED');seen.add(v);for(const child of Object.values(v))stack.push({v:child,depth:depth+1});}}
 if(input&&typeof input==='object'&&'schemaVersion'in input&&input.schemaVersion!==reportSchemaVersion)throw new HttpError(409,'数据集版本不兼容','DATASET_VERSION_UNSUPPORTED');
 const d=definitionSchema.parse(input),dataset=datasetDefinition(d.datasetId);if(!dataset)throw new HttpError(400,'未注册数据集','DATASET_NOT_FOUND');const used=new Set<string>();let complexity=0;
 const field=(id:string)=>{const f=dataset.fields.find(f=>f.fieldId===id);if(!f)throw new HttpError(400,'字段未注册','FIELD_NOT_REGISTERED');if(allowedFields&&!allowedFields.has(id))throw new HttpError(403,'字段不可用于此查询','FIELD_NOT_ALLOWED');used.add(id);return f;};
 const visit=(depth:number)=>{if(++complexity>50||depth>8)throw new HttpError(400,'表达式复杂度超限','EXPRESSION_BUDGET_EXCEEDED');};
 const checkFilter=(n:any,depth=1)=>{visit(depth);if(n.args){n.args.forEach((x:any)=>checkFilter(x,depth+1));return;}const f=field(n.field);if(!f.allowedFilterOps.includes(n.op))throw new HttpError(400,'字段不支持该过滤','FILTER_TYPE_INVALID');if(n.op==='isNull'){if(n.value!==undefined)throw new HttpError(400,'空值判断无需参数','FILTER_TYPE_INVALID');return;}if(n.value===undefined||n.value===null)throw new HttpError(400,'缺值需使用空值判断','FILTER_TYPE_INVALID');for(const value of n.op==='in'?(Array.isArray(n.value)?n.value:(()=>{throw new HttpError(400,'in需要数组','FILTER_TYPE_INVALID');})()):[n.value])reportCell(f,value);};
 const type=(n:any,depth=1):{type:string;unit:string}=>{visit(depth);if(n.where){if(n.op!=='count')throw new HttpError(400,'条件仅支持已声明计数','INVALID_EXPRESSION');checkFilter(n.where,depth+1);}if(n.op==='field'){const f=field(n.field);return f;}if(['add','subtract','ratio'].includes(n.op)){const a=type(n.left,depth+1),b=type(n.right,depth+1);if(!['integer','decimal','money_cents'].includes(a.type)||!['integer','decimal','money_cents'].includes(b.type)||a.unit!==b.unit)throw new HttpError(400,'公式单位或类型不兼容','UNIT_MISMATCH');if(n.op!=='ratio'&&n.percent!==undefined)throw new HttpError(400,'倍率仅用于比率','INVALID_EXPRESSION');return n.op==='ratio'?{type:'decimal',unit:n.percent?'percent_0_100':'ratio'}:a;}if(n.op==='count'&&!n.field)return {type:'integer',unit:'count'};if(!n.field)throw new HttpError(400,'聚合需要字段','FIELD_REQUIRED');const f=field(n.field);if(['count','countDistinct'].includes(n.op))return {type:'integer',unit:'count'};if(!f.allowedAggregations.includes(n.op)&&!registeredMeasureInputs[f.fieldId]?.includes(n.op))throw new HttpError(400,'该字段未批准此聚合','AGGREGATION_NOT_REGISTERED');return f;};
 if(d.metrics.some(m=>dataset.fields.some(f=>f.fieldId===m.id)))throw new HttpError(400,'指标编号不能覆盖原字段','METRIC_FIELD_COLLISION');if(new Set(d.columns).size!==d.columns.length||new Set(d.metrics.map(m=>m.id)).size!==d.metrics.length)throw new HttpError(400,'列或指标重复','DUPLICATE_FIELD');d.columns.forEach(field);d.groupBy.forEach(field);d.sort.forEach(s=>field(s.field));if(d.filter)checkFilter(d.filter);const metricTypes=Object.fromEntries(d.metrics.map(m=>[m.id,type(m.expression)]));if(new Set(d.joins.map(j=>j.id)).size!==d.joins.length)throw new HttpError(400,'关联重复','DUPLICATE_JOIN');for(const j of d.joins){const registered=dataset.allowedJoins.find(r=>r.id===j.id);if(!registered||!registered.strategies.includes(j.strategy))throw new HttpError(400,'关联未注册或缺少去重策略','JOIN_NOT_REGISTERED');if(j.fields.length)throw new HttpError(400,'一对多关联只允许根去重或预聚合，不开放任意明细扩行','JOIN_FANOUT_FORBIDDEN');}
 return {definition:d,dataset,usedFields:[...used],metricTypes,complexity};
}
/** Identifiers are generated from the registry; user values are exclusively bindings. */
export function cellSql(field:ReportField,property:'value'|'state'='value',alias='r'){return `json_extract(${alias}.cells, '$."${field.fieldId}".${property}')`;}
export function compileReportFilter(input:unknown,allowedFields?:ReadonlySet<string>){
 const v=validateReportDefinition(input,allowedFields),args:unknown[]=[];
 const compile=(n:any):string=>{if(n.args)return '('+n.args.map(compile).join(n.op==='and'?' AND ':' OR ')+')';const f=v.dataset.fields.find(f=>f.fieldId===n.field)!,column=cellSql(f);if(n.op==='isNull')return '('+cellSql(f,'state')+"='null')";const op={eq:'=',ne:'<>',lt:'<',lte:'<=',gt:'>',gte:'>='}[n.op as 'eq'];
  const compare=(value:unknown,operator:string)=>{const normalized=reportCell(f,value).value;if(f.type==='decimal'){const text=String(normalized),[whole,fraction='']=text.split('.');args.push(whole,(text.startsWith('-')?-1:1)*Number((fraction+'000000').slice(0,6)));const fractional=`CASE WHEN instr(${column},'.')>0 THEN CAST(substr(${column}||'000000',instr(${column},'.')+1,6) AS INTEGER)*CASE WHEN substr(${column},1,1)='-' THEN -1 ELSE 1 END ELSE 0 END`;return `(CAST(${column} AS INTEGER),${fractional}) ${operator} (CAST(? AS INTEGER),?)`;}args.push(typeof normalized==='boolean'?Number(normalized):normalized);return column+' '+operator+' ?';};
  if(n.op==='in')return n.value.length?'('+n.value.map((value:unknown)=>compare(value,'=')).join(' OR ')+')':'0';return compare(n.value,op);
 };
 const sql=v.definition.filter?compile(v.definition.filter):'1';if(args.length>70)throw new HttpError(413,'过滤参数超出预算','QUERY_BINDING_BUDGET');return {...v,sql,args};
}
