import {z} from 'zod';
import {HttpError} from './http';
import {authorizeTuple} from './r1-authorization';
import {commitCommand,replayCommand,digest,canonical,type CommandIntent} from './r1-command';
import {datasetDefinition,reportSchemaVersion} from './r1-report-catalog';
import {reportCell,type ReportCell} from './r1-report-values';
import {reportFence,type ReportContext} from './r1-report-context';
export type ProjectionRow={rowKey:string;keyParts:string[];orgId:string;personId:string|null;policyKind:'person'|'batch'|'source';policyKey:string;eventDate:string|null;currency:string|null;cells:Record<string,ReportCell>;sourceVersion:string};
export type ReportProducer={producerId:string;version:string;mode:'internal'|'simulated';readPage:(ctx:ReportContext,datasetId:string,cutoff:number,orgId:string,after:string,limit:number,generatedAt:string)=>Promise<{rows:ProjectionRow[];nextCursor:string|null;complete:boolean;sourceManifest:Record<string,string|number>}>};
export type ProducerRegistry=Record<string,ReportProducer>;
const projectedRow=z.object({rowKey:z.string().min(1).max(1000),keyParts:z.array(z.string().min(1).max(100)).min(1).max(8),orgId:z.string().min(1).max(100),personId:z.string().min(1).max(100).nullable(),policyKind:z.enum(['person','batch','source']),policyKey:z.string().min(1).max(100),eventDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(),currency:z.string().regex(/^[A-Z]{3}$/).nullable(),cells:z.record(z.object({value:z.union([z.string().max(65536),z.number().int().safe(),z.boolean(),z.null()]),state:z.enum(['value','null','not_configured','unavailable']),reasonCode:z.string().max(100).nullable()}).strict()),sourceVersion:z.string().min(1).max(100)}).strict();
const common={id:z.string().min(1).max(100),orgId:z.string().min(1).max(100)},command=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('begin'),...common,datasetId:z.string().min(1).max(100)}).strict(),
 z.object({operation:z.literal('advance'),id:common.id,expectedRevision:z.number().int().positive()}).strict(),
 z.object({operation:z.literal('snapshot'),id:common.id,snapshotId:common.id,purpose:z.string().min(1).max(500)}).strict(),
]);
export async function projectReport(ctx:ReportContext,intent:CommandIntent,registry:ProducerRegistry){const c=command.parse(intent.payload),t=ctx.member.tenantId,db=ctx.db,existing=c.operation==='begin'?null:await db.prepare('SELECT * FROM r1_report_generations WHERE tenant_id=? AND id=?').bind(t,c.id).first<any>(),orgId=c.operation==='begin'?c.orgId:existing?.scope_org;if(!orgId)throw new HttpError(404,'未找到报表版本','GENERATION_NOT_FOUND');await authorizeTuple(db,ctx.member,{objectType:'M32',action:'projection.manage',orgId,personId:'',field:'record',historyMode:'current'});const replay=await replayCommand(db,ctx.member,ctx.member.securityStamp!,intent);if(replay)return replay;
 const datasetId=c.operation==='begin'?c.datasetId:existing.dataset_id,definition=datasetDefinition(datasetId);if(!definition)throw new HttpError(400,'未注册数据集','DATASET_NOT_FOUND');const producer=registry[datasetId];if(!producer)throw new HttpError(503,'生产者版本化读取契约尚未配置','PRODUCER_NOT_CONFIGURED');
 const guarded=(sql:string,args:unknown[])=> (token:string)=>db.prepare(sql).bind(...args,t,token),plans:((token:string)=>D1PreparedStatement)[]=[];let result:Record<string,unknown>={generationId:c.id,mode:producer.mode,realIntegration:'not_executed'};
 if(c.operation==='begin'){
  const manifest={producerId:producer.producerId,producerVersion:producer.version,cutoff:ctx.row.revision,scopeOrg:orgId,mode:producer.mode};plans.push(guarded("INSERT INTO r1_report_generations SELECT owner,?,?,?,?,?,?,?,'building','',1,0,NULL,?,?,NULL FROM hris_workspaces WHERE owner=? AND last_mutation=?",[c.id,datasetId,reportSchemaVersion,producer.version,JSON.stringify(manifest),ctx.row.revision,orgId,ctx.member.userId,new Date().toISOString()]));result.status='building';
 }else if(c.operation==='advance'){
  if(existing.status!=='building'||existing.revision!==c.expectedRevision)throw new HttpError(409,'报表构建状态或版本已变化','GENERATION_CONFLICT');if(existing.producer_version!==producer.version)throw new HttpError(409,'生产者版本已变化','DATASET_VERSION_UNSUPPORTED');
  const page=await producer.readPage(ctx,datasetId,existing.source_cutoff,orgId,existing.build_cursor,200,existing.generated_at);if(canonical(page.sourceManifest)!==canonical(JSON.parse(existing.source_manifest)))throw new HttpError(409,'来源清单发生变化','SOURCE_MANIFEST_CHANGED');if(page.rows.length>200||page.complete&&page.nextCursor!==null||!page.complete&&(!page.nextCursor||page.nextCursor<=existing.build_cursor))throw new HttpError(409,'生产者分页不一致','PRODUCER_PAGE_INVALID');const keys=page.rows.map(r=>r.rowKey);if(new Set(keys).size!==keys.length||keys.some((k,i)=>!k||k<=existing.build_cursor||i>0&&k<=keys[i-1]))throw new HttpError(409,'行键重复或次序无效','ROW_KEY_INVALID');
  const rows=page.rows.map(raw=>{const r=projectedRow.parse(raw);if(['workforce','contractCoverage','contractOperations'].includes(datasetId)&&r.policyKind!=='person'||['workforce','contractCoverage'].includes(datasetId)&&r.keyParts[0]!==r.personId)throw new HttpError(409,'数据集粒度或保护对象不符','PRODUCER_ROW_INVALID');if(r.orgId!==orgId||r.keyParts.length!==definition.rowKeySchema.length||r.keyParts.some(k=>!k)||r.rowKey!==JSON.stringify(r.keyParts))throw new HttpError(409,'来源行键或组织范围不符','PRODUCER_ROW_INVALID');for(const id of Object.keys(r.cells))if(!definition.fields.some(f=>f.fieldId===id))throw new HttpError(409,'未注册来源字段','FIELD_NOT_REGISTERED');const cells=Object.fromEntries(definition.fields.map(f=>{const cell=r.cells[f.fieldId];return [f.fieldId,reportCell(f,cell?.value,cell?.state,cell?.reasonCode)];}));return {...r,cells};});
  const bytes=new TextEncoder().encode(canonical(rows)).byteLength;if(bytes>4*1024*1024)throw new HttpError(413,'报表块超过4MiB','REPORT_CHUNK_TOO_LARGE');const hash=await digest(rows),seq=existing.revision;
  plans.push(guarded('INSERT INTO r1_report_rows SELECT w.owner,?, ?,json_extract(j.value,\'$.rowKey\'),json_extract(j.value,\'$.orgId\'),json_extract(j.value,\'$.personId\'),json_extract(j.value,\'$.policyKind\'),json_extract(j.value,\'$.policyKey\'),json_extract(j.value,\'$.eventDate\'),json_extract(j.value,\'$.currency\'),json_extract(j.value,\'$.cells\'),json_extract(j.value,\'$.sourceVersion\'),json_extract(j.value,\'$.keyParts\') FROM json_each(?) j JOIN hris_workspaces w WHERE w.owner=? AND w.last_mutation=?',[datasetId,c.id,JSON.stringify(rows)]));
  plans.push(guarded('INSERT INTO r1_report_chunks SELECT owner,?,?,?,?,?,?,? FROM hris_workspaces WHERE owner=? AND last_mutation=?',[c.id,seq,keys[0]??'',keys.at(-1)??'',rows.length,bytes,hash]));
  const prior=(await db.prepare('SELECT sequence,digest,row_count FROM r1_report_chunks WHERE tenant_id=? AND generation_id=? ORDER BY sequence LIMIT 10001').bind(t,c.id).all<any>()).results.map(r=>({sequence:r.sequence,digest:r.digest,row_count:r.row_count}));if(prior.length>=10000)throw new HttpError(413,'构建块预算超限','GENERATION_BUDGET_EXCEEDED');const rootHash=page.complete?await digest([...prior,{sequence:seq,digest:hash,row_count:rows.length}]):null;
  plans.push(guarded('UPDATE r1_report_generations SET status=?,build_cursor=?,revision=revision+1,row_count=row_count+?,content_digest=?,completed_at=? WHERE id=? AND tenant_id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)',[page.complete?'ready':'building',page.nextCursor??keys.at(-1)??existing.build_cursor,rows.length,rootHash,page.complete?new Date().toISOString():null,c.id,t]));result={...result,status:page.complete?'ready':'building',rowsWritten:rows.length,nextCursor:page.nextCursor};
 }else{
  if(existing.status!=='ready'||!existing.content_digest)throw new HttpError(409,'报表版本尚未完整构建','GENERATION_NOT_READY');const chunks=(await db.prepare('SELECT sequence,digest,row_count FROM r1_report_chunks WHERE tenant_id=? AND generation_id=? ORDER BY sequence LIMIT 10001').bind(t,c.id).all<any>()).results.map(r=>({sequence:r.sequence,digest:r.digest,row_count:r.row_count}));if(chunks.length>10000||await digest(chunks)!==existing.content_digest||chunks.reduce((n,c)=>n+c.row_count,0)!==existing.row_count)throw new HttpError(409,'报表快照校验失败','SNAPSHOT_DIGEST_CONFLICT');
  plans.push(guarded("INSERT INTO r1_report_snapshots SELECT owner,?,?,?,?,?,?,?,?,?,?,?,?,?,'ready' FROM hris_workspaces WHERE owner=? AND last_mutation=?",[c.snapshotId,datasetId,c.id,existing.definition_version,String(existing.source_cutoff),existing.generated_at,existing.source_manifest,JSON.stringify(definition.rowKeySchema),existing.row_count,JSON.stringify(chunks),existing.content_digest,ctx.member.userId,c.purpose]));result={...result,snapshotId:c.snapshotId,status:'ready'};
 }
 await reportFence(ctx);return commitCommand(db,ctx.member,ctx.member.securityStamp!,intent,token=>plans.map(p=>p(token)),result);
}
