import {HttpError} from './http';
import {digest} from './r1-command';
import {verifyRecoveryManifest,verifyRecoveryManifestSignature,type SignedRecoveryManifest,type RecoveryVaultAccess,type RecoveryKeyVault,type ImmutableBackupStore} from './r1-recovery-crypto';
const DAY=86400000;
export const recoveryMaintenanceSchema=`CREATE TABLE backup_checkpoints(id TEXT PRIMARY KEY,digest TEXT NOT NULL,manifest TEXT NOT NULL,verified_at INTEGER NOT NULL);CREATE TABLE recovery_gc_receipts(id TEXT PRIMARY KEY,object_key TEXT NOT NULL,version_id TEXT NOT NULL,state TEXT NOT NULL,updated_at INTEGER NOT NULL);`;
export type CatalogEntry={signed:SignedRecoveryManifest;verifiedAt:number};
export class RecoveryCatalog {
 private vaults=new Map<string,RecoveryKeyVault>();private backup:ImmutableBackupStore|null=null;
 constructor(private db:D1Database,readonly storageId:string,businessStorageId:string,verification?:{vaults:RecoveryVaultAccess;store:ImmutableBackupStore}){if(verification)this.configureVerification(verification.vaults,verification.store);if(storageId===businessStorageId)throw new HttpError(409,'备份目录必须独立','RECOVERY_CONTROL_NOT_INDEPENDENT');}
 configureVerification(vaults:RecoveryVaultAccess,store:ImmutableBackupStore){if('keyId' in vaults)this.vaults.set(vaults.keyId,vaults);else for(const [id,v] of vaults)this.vaults.set(id,v);this.backup=store;}
 async verifyArchive(entry:CatalogEntry){if(!this.backup)throw new HttpError(503,'归档验证源不可用','RECOVERY_CATALOG_TRUST_UNAVAILABLE');await verifyRecoveryManifest(entry.signed,this.vaults,this.backup);}
 async register(signed:SignedRecoveryManifest,vault:RecoveryVaultAccess,store:ImmutableBackupStore){await verifyRecoveryManifest(signed,vault,store);this.configureVerification(vault,store);const old=await this.db.prepare('SELECT digest FROM backup_checkpoints WHERE id=?').bind(signed.manifest.checkpointId).first<{digest:string}>();if(old){if(old.digest!==signed.digest)throw new HttpError(409,'备份目录键冲突','RECOVERY_IDEMPOTENCY_CONFLICT');return;}await this.db.prepare('INSERT INTO backup_checkpoints VALUES (?,?,?,?)').bind(signed.manifest.checkpointId,signed.digest,JSON.stringify(signed),Date.now()).run();}
 async entries(){const rows=(await this.db.prepare('SELECT manifest,digest,verified_at FROM backup_checkpoints ORDER BY verified_at,id LIMIT 10001').all<{manifest:string;digest:string;verified_at:number}>()).results;if(rows.length>10000)throw new HttpError(413,'目录需要分区读取','RECOVERY_CATALOG_BUDGET');const entries:CatalogEntry[]=[];for(const r of rows){const signed=JSON.parse(r.manifest) as SignedRecoveryManifest;if(signed.digest!==r.digest||await digest(signed.manifest)!==r.digest)throw new HttpError(409,'独立备份目录摘要损坏','RECOVERY_CATALOG_INVALID');await verifyRecoveryManifestSignature(signed,this.vaults);entries.push({signed,verifiedAt:r.verified_at});}return entries;}
}
/** Pure planning over an independently verified catalog; this function grants no delete authority. */
export function recoveryRetentionPlan(entries:CatalogEntry[],now=Date.now()) {const byId=new Map(entries.map(e=>[e.signed.manifest.checkpointId,e]));if(byId.size!==entries.length)throw new HttpError(409,'目录重复检查点','RECOVERY_CATALOG_INVALID');const roots=new Set<string>(),daily=new Set<string>();for(const e of [...entries].sort((a,b)=>Date.parse(b.signed.manifest.takenAt)-Date.parse(a.signed.manifest.takenAt))){const m=e.signed.manifest,t=Date.parse(m.takenAt);if(!Number.isFinite(t)||t>now||e.verifiedAt>now)throw new HttpError(409,'目录时间无效','RECOVERY_CATALOG_INVALID');if(Date.parse(m.retainedUntil)>now||t>=now-30*DAY)roots.add(m.checkpointId);if(m.kind==='baseline'){const day=m.takenAt.slice(0,10);if(!daily.has(day)&&daily.size<31){daily.add(day);roots.add(m.checkpointId);}}}
 const keep=new Set<string>();for(const root of roots){let id:string|null=root;const chain=new Set<string>();while(id){if(chain.has(id))throw new HttpError(409,'恢复依赖循环','RECOVERY_DEPENDENCY_MISSING');chain.add(id);const entry=byId.get(id);if(!entry)throw new HttpError(409,'存续恢复点缺少依赖','RECOVERY_DEPENDENCY_MISSING');const m=entry.signed.manifest;keep.add(id);if(m.parentCheckpoint){const parent=byId.get(m.parentCheckpoint);if(!parent||parent.signed.digest!==m.parentDigest||parent.signed.manifest.toSeq!==m.fromSeq)throw new HttpError(409,'恢复父摘要或水位不连续','RECOVERY_DEPENDENCY_MISSING');}else if(m.kind!=='baseline')throw new HttpError(409,'增量缺少基线','RECOVERY_DEPENDENCY_MISSING');id=m.parentCheckpoint;}}
 const objects=new Set<string>(),keys=new Set<string>(),chunks=new Set<string>();for(const id of keep){const m=byId.get(id)!.signed.manifest;keys.add(m.keyId);for(const o of m.objects)objects.add(JSON.stringify([o.key,o.versionId]));for(const c of m.chunks)chunks.add(c.key);chunks.add(m.checkpointId+'/manifest');}return {retainedCheckpoints:[...keep].sort(),expiredCheckpoints:[...byId.keys()].filter(id=>!keep.has(id)).sort(),retainedObjects:[...objects].sort(),retainedKeys:[...keys].sort(),retainedBackupKeys:[...chunks].sort(),oldestRestorableAt:keep.size?Math.min(...[...keep].map(id=>Date.parse(byId.get(id)!.signed.manifest.takenAt))):null};}
/** Actual platform adapter must fence backup publication, business reference creation and physical deletion together. */
export interface RecoveryMaintenanceGuard {runExclusive<T>(operation:()=>Promise<T>):Promise<T>;assertHeld():Promise<void>;}
export interface RecoveryGcObjects {isReferenced(key:string):Promise<boolean>;headVersion(key:string):Promise<string|null>;deleteVersion(key:string,version:string):Promise<void>;}
export async function collectRecoveryObject(control:D1Database,catalog:RecoveryCatalog,guard:RecoveryMaintenanceGuard,objects:RecoveryGcObjects,key:string,version:string){return guard.runExclusive(async()=>{await guard.assertHeld();const entries=await catalog.entries(),plan=recoveryRetentionPlan(entries),id=await digest({key,version}),old=await control.prepare('SELECT state FROM recovery_gc_receipts WHERE id=?').bind(id).first<{state:string}>();if(old?.state==='deleted')return {state:'deleted',replayed:true};if(plan.retainedObjects.includes(JSON.stringify([key,version]))||await objects.isReferenced(key))return {state:'retained',replayed:false};const current=await objects.headVersion(key);if(current&&current!==version)throw new HttpError(409,'待清理对象版本改变','RECOVERY_SOURCE_CHANGED');await control.prepare("INSERT INTO recovery_gc_receipts VALUES (?,?,?,'pending',?) ON CONFLICT(id) DO UPDATE SET state='pending',updated_at=excluded.updated_at").bind(id,key,version,Date.now()).run();await guard.assertHeld();try{if(current)await objects.deleteVersion(key,version);}catch{return {state:'unknown',replayed:false};}if(await objects.headVersion(key)!==null)return {state:'unknown',replayed:false};await control.prepare("UPDATE recovery_gc_receipts SET state='deleted',updated_at=? WHERE id=?").bind(Date.now(),id).run();return {state:'deleted',replayed:false};});}
/** Archive verification time is a conservative lower bound: retain at least 48 hours after verified archival. */
export async function pruneArchivedHotJournal(db:D1Database,catalog:RecoveryCatalog,guard:RecoveryMaintenanceGuard,now=Date.now()){return guard.runExclusive(async()=>{await guard.assertHeld();const entries=await catalog.entries(),plan=recoveryRetentionPlan(entries,now),eligible=entries.filter(e=>plan.retainedCheckpoints.includes(e.signed.manifest.checkpointId)&&e.verifiedAt<=now-2*DAY&&e.signed.manifest.kind==='baseline'),through=Math.max(0,...eligible.map(e=>e.signed.manifest.toSeq));if(!through)return {deleted:0,through:0};await catalog.verifyArchive(eligible.find(e=>e.signed.manifest.toSeq===through)!);const before=await db.prepare('SELECT count(*) n FROM r1_recovery_changes').first<{n:number}>();await guard.assertHeld();const result=await db.prepare('DELETE FROM r1_recovery_changes WHERE seq<=? AND tx_id<>(SELECT tx_id FROM r1_recovery_changes ORDER BY seq DESC LIMIT 1) AND tx_id NOT IN (SELECT tx_id FROM r1_recovery_changes WHERE seq>?)').bind(through,through).run();return {deleted:result.meta.changes,through,originalRows:before?.n,scope:'recovery_journal_only',businessHistoryDeleted:false};});}
export function recoveryHealth(entries:CatalogEntry[],incidentAt:number|null=null,openedAt:number|null=null,now=Date.now()){const plan=recoveryRetentionPlan(entries,now),verified=entries.filter(e=>plan.retainedCheckpoints.includes(e.signed.manifest.checkpointId)),watermark=verified.length?Math.max(...verified.map(e=>Date.parse(e.signed.manifest.takenAt))):null,age=watermark===null?null:now-watermark,level=age===null?'unavailable':age>60*60000?'breach':age>=55*60000?'critical':age>=45*60000?'warning':age>40*60000?'budget_exceeded':'healthy';if(incidentAt!==null&&(incidentAt>now||openedAt!==null&&(openedAt<incidentAt||openedAt>now)))throw new HttpError(400,'恢复计时无效','RECOVERY_TIME_INVALID');const rto=incidentAt===null?null:(openedAt??now)-incidentAt;return {commonRestorableAt:watermark,ageMs:age,level,rtoIncludingApprovalWaitMs:rto,rtoComplete:openedAt!==null,rtoPassed:openedAt!==null&&rto!==null&&rto<=240*60000,coverage30DayStartAvailable:plan.oldestRestorableAt!==null&&plan.oldestRestorableAt<=now-30*DAY,continuous30DayMonitoringVerified:false};}
