import {z} from 'zod';
import {HttpError} from './http';
const iso=z.string().datetime({offset:true});
export const scheduleSchema=z.object({timezone:z.string().min(1).max(80),frequency:z.enum(['daily','weekly']),weekDays:z.array(z.number().int().min(0).max(6)).max(7),localSendTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),gapPolicy:z.enum(['skip','reject']),repeatPolicy:z.literal('earlier'),startAt:iso,endAt:iso}).strict().superRefine((s,ctx)=>{try{new Intl.DateTimeFormat('en',{timeZone:s.timezone});}catch{ctx.addIssue({code:'custom',message:'无效时区'});}if(Date.parse(s.startAt)>=Date.parse(s.endAt)||s.frequency==='weekly'&&!s.weekDays.length||s.frequency==='daily'&&s.weekDays.length||new Set(s.weekDays).size!==s.weekDays.length)ctx.addIssue({code:'custom',message:'周期与起止范围不一致'});});
export function scheduleOccurrence(input:unknown,localDay:string){const s=scheduleSchema.parse(input);if(!/^\d{4}-\d{2}-\d{2}$/.test(localDay)||!Number.isFinite(Date.parse(localDay+'T00:00:00Z'))||new Date(localDay+'T00:00:00Z').toISOString().slice(0,10)!==localDay)throw new HttpError(400,'本地业务日无效','INVALID_LOCAL_DAY');if(s.frequency==='weekly'&&!s.weekDays.includes(new Date(localDay+'T00:00:00Z').getUTCDay()))return {state:'not_scheduled' as const};
 const target=localDay+'T'+s.localSendTime,center=Date.parse(target+':00Z'),format=new Intl.DateTimeFormat('en-CA',{timeZone:s.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}),matches:number[]=[];
 // Bounded civil-time conversion: 36 hours handles all IANA UTC offsets, including non-hour offsets.
 for(let at=center-18*3600000;at<=center+18*3600000;at+=60000){const p=Object.fromEntries(format.formatToParts(at).map(p=>[p.type,p.value]));if(p.year+'-'+p.month+'-'+p.day+'T'+p.hour+':'+p.minute===target)matches.push(at);}
 if(!matches.length){if(s.gapPolicy==='reject')throw new HttpError(409,'夏令时缺失时刻按显式策略拒绝','DST_GAP');return {state:'skipped_gap' as const};}const utc=matches[0],occurrenceAt=new Date(utc).toISOString();if(utc<Date.parse(s.startAt)||utc>Date.parse(s.endAt))return {state:'outside_range' as const};return {state:'scheduled' as const,occurrenceAt,localDay,localSendTime:s.localSendTime,utcOffsetMinutes:(center-utc)/60000,repeatedLocalTime:matches.length>1};
}
