import {z} from 'zod';
import {HttpError} from './http';
import {digest,canonical} from './r1-command';
export const securityLedgerSchema=`CREATE TABLE security_ledger_events(tenant_id TEXT NOT NULL,revision INTEGER NOT NULL,event_id TEXT NOT NULL,request_digest TEXT NOT NULL,previous_digest TEXT,digest TEXT NOT NULL,payload TEXT NOT NULL,signature TEXT NOT NULL,PRIMARY KEY(tenant_id,revision),UNIQUE(tenant_id,event_id));
CREATE TABLE security_ledger_heads(tenant_id TEXT PRIMARY KEY,revision INTEGER NOT NULL,digest TEXT NOT NULL,payload TEXT NOT NULL);
CREATE TABLE security_ledger_guard(tenant_id TEXT PRIMARY KEY,valid INTEGER NOT NULL CHECK(valid=1));`;
const hash=z.string().regex(/^[0-9a-f]{64}$/),number=z.number().int().nonnegative().safe();
export const securityStateSchema=z.object({epoch:number,authorizationRevision:number,workspaceRevision:number,denied:z.boolean(),pendingId:z.string().nullable(),authorityImage:z.record(z.string(),z.unknown()),authorityDigest:hash,platformAccessVerified:z.boolean(),recoveryEpoch:number}).strict();
export type SecurityLedgerState=z.infer<typeof securityStateSchema>;
export interface SecuritySigner {sign(message:Uint8Array):Promise<string>;verify(message:Uint8Array,signature:string):Promise<boolean>;}
export class SqlSecurityLedger {
 constructor(private db:D1Database,private signer:SecuritySigner,readonly storageId:string,businessStorageId:string){if(storageId===businessStorageId)throw new HttpError(409,'安全ledger必须独立于业务存储','SECURITY_STORAGE_NOT_INDEPENDENT');}
 async read(tenant:string){const r=await this.db.prepare('SELECT * FROM security_ledger_heads WHERE tenant_id=?').bind(tenant).first<any>();return r?{revision:r.revision,digest:r.digest,state:securityStateSchema.parse(JSON.parse(r.payload))}:null;}
 async append(tenant:string,eventId:string,expectedRevision:number,state:SecurityLedgerState){const parsed=securityStateSchema.parse(state);if(await digest(parsed.authorityImage)!==parsed.authorityDigest)throw new HttpError(409,'安全授权映像摘要不一致','SECURITY_IMAGE_INVALID');const requestDigest=await digest({tenant,eventId,state:parsed}),old=await this.db.prepare('SELECT request_digest FROM security_ledger_events WHERE tenant_id=? AND event_id=?').bind(tenant,eventId).first<{request_digest:string}>();if(old){if(old.request_digest!==requestDigest)throw new HttpError(409,'安全事件幂等键冲突','SECURITY_IDEMPOTENCY_CONFLICT');return this.read(tenant);}const head=await this.read(tenant);if((head?.revision??0)!==expectedRevision||head&&(parsed.epoch<head.state.epoch||parsed.authorizationRevision<head.state.authorizationRevision||parsed.recoveryEpoch<head.state.recoveryEpoch||parsed.workspaceRevision<head.state.workspaceRevision&&parsed.recoveryEpoch===head.state.recoveryEpoch))throw new HttpError(409,'安全ledger版本变化','SECURITY_LEDGER_CONFLICT');const revision=expectedRevision+1,envelope={purpose:'r1-security-ledger-v1',tenant,revision,eventId,previousDigest:head?.digest??null,state:parsed},hash=await digest(envelope),signature=await this.signer.sign(new TextEncoder().encode(hash));
 await this.db.batch([this.db.prepare('INSERT INTO security_ledger_guard VALUES (?,CASE WHEN coalesce((SELECT revision FROM security_ledger_heads WHERE tenant_id=?),0)=? THEN 1 ELSE 0 END)').bind(tenant,tenant,expectedRevision),this.db.prepare('INSERT INTO security_ledger_events VALUES (?,?,?,?,?,?,?,?)').bind(tenant,revision,eventId,requestDigest,head?.digest??null,hash,canonical(parsed),signature),this.db.prepare('INSERT INTO security_ledger_heads VALUES (?,?,?,?) ON CONFLICT(tenant_id) DO UPDATE SET revision=excluded.revision,digest=excluded.digest,payload=excluded.payload').bind(tenant,revision,hash,canonical(parsed)),this.db.prepare('DELETE FROM security_ledger_guard WHERE tenant_id=?').bind(tenant)]);return this.read(tenant);}
 async verifyReference(tenant:string,revision:number,hash:string){const r=await this.db.prepare('SELECT digest FROM security_ledger_events WHERE tenant_id=? AND revision=?').bind(tenant,revision).first<{digest:string}>();return r?.digest===hash;}
 async verifyChain(tenant:string){const head=await this.read(tenant);if(!head)throw new HttpError(503,'独立安全记录不可用','SECURITY_LEDGER_UNAVAILABLE');let after=0,previous:string|null=null,lastState:SecurityLedgerState|null=null;while(after<head.revision){const rows=(await this.db.prepare('SELECT * FROM security_ledger_events WHERE tenant_id=? AND revision>? ORDER BY revision LIMIT 100').bind(tenant,after).all<any>()).results;if(!rows.length)throw new HttpError(503,'安全链尾部缺失','SECURITY_LEDGER_BROKEN');for(const r of rows){if(r.revision!==after+1||r.previous_digest!==previous)throw new HttpError(503,'安全链断序','SECURITY_LEDGER_BROKEN');const state=securityStateSchema.parse(JSON.parse(r.payload)),hash=await digest({purpose:'r1-security-ledger-v1',tenant,revision:r.revision,eventId:r.event_id,previousDigest:r.previous_digest,state});if(hash!==r.digest||await digest(state.authorityImage)!==state.authorityDigest||!await this.signer.verify(new TextEncoder().encode(hash),r.signature)||lastState&&(state.epoch<lastState.epoch||state.authorizationRevision<lastState.authorizationRevision||state.recoveryEpoch<lastState.recoveryEpoch||state.workspaceRevision<lastState.workspaceRevision&&state.recoveryEpoch===lastState.recoveryEpoch))throw new HttpError(503,'安全链认证失败','SECURITY_LEDGER_BROKEN');previous=hash;after=r.revision;lastState=state;}}
 const now=await this.read(tenant);if(after!==head.revision||previous!==head.digest||now?.digest!==head.digest||await digest(lastState)!==await digest(head.state))throw new HttpError(503,'安全水位在核验期间变化','SECURITY_LEDGER_CHANGED');return head;}
}
/** Cross-store changes deliberately fail closed; the business adapter must be a privileged fenced control writer. */
export async function coordinateSecurityChange(ledger:SqlSecurityLedger,tenant:string,eventId:string,desired:{authorityImage:Record<string,unknown>;platformAccessVerified:boolean},applyBusiness:()=>Promise<{authorizationRevision:number;workspaceRevision:number;recoveryEpoch:number;authorityImage:Record<string,unknown>}>){const head=await ledger.verifyChain(tenant);if(head.state.denied||head.state.pendingId)throw new HttpError(503,'前一安全变更未对账','SECURITY_RECONCILIATION_REQUIRED');const pending={...head.state,epoch:head.state.epoch+1,denied:true,pendingId:eventId};await ledger.append(tenant,eventId+':deny',head.revision,pending);const committed=await applyBusiness();if(await digest(committed.authorityImage)!==await digest(desired.authorityImage))throw new HttpError(503,'业务授权映像与独立确认不一致','SECURITY_IMAGE_MISMATCH');const next=await ledger.read(tenant);if(!next||next.state.pendingId!==eventId)throw new HttpError(503,'安全变更控制权变化','SECURITY_RECONCILIATION_REQUIRED');return ledger.append(tenant,eventId+':ack',next.revision,{...pending,...committed,...desired,authorityDigest:await digest(desired.authorityImage),denied:!desired.platformAccessVerified,pendingId:null});}
export type CurrentSecurityProof={purpose:'r1-current-security-v1';tenant:string;challenge:string;revision:number;digest:string;epoch:number;authorizationRevision:number;workspaceRevision:number;recoveryEpoch:number;denied:boolean;platformAccessVerified:boolean;expiresAt:number};
export async function issueSecurityProof(ledger:SqlSecurityLedger,signer:SecuritySigner,tenant:string,challenge:string){const head=await ledger.verifyChain(tenant),s=head.state,proof:CurrentSecurityProof={purpose:'r1-current-security-v1',tenant,challenge,revision:head.revision,digest:head.digest,epoch:s.epoch,authorizationRevision:s.authorizationRevision,workspaceRevision:s.workspaceRevision,recoveryEpoch:s.recoveryEpoch,denied:s.denied||!!s.pendingId,platformAccessVerified:s.platformAccessVerified,expiresAt:Date.now()+30000};return {proof,signature:await signer.sign(new TextEncoder().encode(await digest(proof)))};}
export async function verifyCurrentSecurityProof(signed:{proof:CurrentSecurityProof;signature:string},signer:SecuritySigner,expected:{tenant:string;challenge:string;authorizationRevision:number;workspaceRevision:number;recoveryEpoch:number}){const p=signed.proof;if(!p||p.purpose!=='r1-current-security-v1'||p.tenant!==expected.tenant||p.challenge!==expected.challenge||p.expiresAt<=Date.now()||p.expiresAt>Date.now()+60000||p.denied||!p.platformAccessVerified||p.authorizationRevision!==expected.authorizationRevision||p.workspaceRevision!==expected.workspaceRevision||p.recoveryEpoch!==expected.recoveryEpoch||!await signer.verify(new TextEncoder().encode(await digest(p)),signed.signature))throw new HttpError(503,'当前独立安全授权未核实','SECURITY_RECONCILIATION_REQUIRED');return p;}
