import {env} from 'cloudflare:workers';
import {HttpError} from './http';
import {digest,type SecurityStamp} from './r1-command';
import {SqlSecurityLedger,issueSecurityProof,verifyCurrentSecurityProof,type SecuritySigner,type SecurityLedgerState} from './r1-security-ledger';
import {currentAuthoritySource} from './r1-security-source';
export type SecurityWriteRequest={tenant:string;commandId:string;requestDigest:string;authorizationRevision:number;workspaceRevision:number;recoveryEpoch:number;challenge:string};
type WritePermit=SecurityWriteRequest&{purpose:'r1-security-write-permit-v1';epoch:number;expiresAt:number};
export interface CurrentSecurityRuntime {current(tenant:string,challenge:string):Promise<Awaited<ReturnType<typeof issueSecurityProof>>>;prepare(request:SecurityWriteRequest):Promise<{permit:WritePermit;signature:string}>;finalize(tenant:string,commandId:string,requestDigest:string):Promise<void>;}
/** This provider belongs to the independent security plane; the app receives only its public verification key. */
export class LedgerSecurityRuntime implements CurrentSecurityRuntime {
 constructor(private ledger:SqlSecurityLedger,private signer:SecuritySigner,private source:(tenant:string,commandId?:string)=>ReturnType<typeof currentAuthoritySource>,private platformAccess:(tenant:string)=>Promise<boolean>){}
 async current(tenant:string,challenge:string){const signed=await issueSecurityProof(this.ledger,this.signer,tenant,challenge);if(!await this.platformAccess(tenant))throw new HttpError(503,'当前平台访问未核实','SECURITY_PLATFORM_ACCESS_DENIED');return signed;}
 async prepare(request:SecurityWriteRequest){const head=await this.ledger.verifyChain(request.tenant),source=await this.source(request.tenant);if(head.state.denied||head.state.pendingId||!await this.platformAccess(request.tenant)||request.authorizationRevision!==source.authorizationRevision||request.workspaceRevision!==source.workspaceRevision||request.recoveryEpoch!==source.recoveryEpoch||head.state.workspaceRevision!==source.workspaceRevision||head.state.authorizationRevision!==source.authorizationRevision||head.state.recoveryEpoch!==source.recoveryEpoch||await digest(source.authorityImage)!==head.state.authorityDigest)throw new HttpError(503,'安全写入条件未对账','SECURITY_RECONCILIATION_REQUIRED');const pending:SecurityLedgerState={...head.state,epoch:head.state.epoch+1,denied:true,pendingId:request.commandId+':'+request.requestDigest};await this.ledger.append(request.tenant,request.commandId+':prepare',head.revision,pending);const permit:WritePermit={...request,purpose:'r1-security-write-permit-v1',epoch:pending.epoch,expiresAt:Date.now()+30000};return {permit,signature:await this.signer.sign(new TextEncoder().encode(await digest(permit)))};}
 async finalize(tenant:string,commandId:string,requestDigest:string){const head=await this.ledger.verifyChain(tenant),source=await this.source(tenant,commandId);if(!head.state.denied&&head.state.pendingId===null&&source.command?.status==='committed'&&source.command.requestDigest===requestDigest&&source.command.workspaceRevision===source.workspaceRevision&&head.state.workspaceRevision===source.workspaceRevision&&await digest(source.authorityImage)===head.state.authorityDigest)return;if(!head.state.denied||head.state.pendingId!==commandId+':'+requestDigest||source.command?.status!=='committed'||source.command.requestDigest!==requestDigest||source.command.workspaceRevision!==source.workspaceRevision)throw new HttpError(503,'业务命令未确认，安全闸门保持关闭','SECURITY_RECONCILIATION_REQUIRED');const state={...head.state,authorizationRevision:source.authorizationRevision,workspaceRevision:source.workspaceRevision,recoveryEpoch:source.recoveryEpoch,authorityImage:source.authorityImage,authorityDigest:await digest(source.authorityImage),denied:!await this.platformAccess(tenant),pendingId:null};await this.ledger.append(tenant,commandId+':finalize',head.revision,state);}
}
function configuration(){const e=env as unknown as {R1_REQUIRE_SECURITY_LEDGER?:string;R1_SECURITY_RUNTIME?:CurrentSecurityRuntime;R1_SECURITY_PUBLIC_KEY?:string};if(e.R1_REQUIRE_SECURITY_LEDGER!=='1')return null;if(!e.R1_SECURITY_RUNTIME||!e.R1_SECURITY_PUBLIC_KEY)throw new HttpError(503,'独立安全服务未配置，受保护访问拒绝','SECURITY_LEDGER_UNAVAILABLE');return {runtime:e.R1_SECURITY_RUNTIME,publicKey:e.R1_SECURITY_PUBLIC_KEY};}
async function verifier(publicKey:string):Promise<SecuritySigner>{let key:CryptoKey;try{key=await crypto.subtle.importKey('jwk',JSON.parse(publicKey),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);}catch{throw new HttpError(503,'独立安全验签公钥无效','SECURITY_KEY_UNAVAILABLE');}return {sign:async()=>{throw Error('NO_PRIVATE_KEY_IN_APPLICATION');},verify:async(message,signature)=>{try{if(!/^(?:[0-9a-f]{2})+$/.test(signature))return false;return await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,Uint8Array.from(signature.match(/../g)!,x=>parseInt(x,16)),message as Uint8Array<ArrayBuffer>);}catch{return false;}}};}
export async function assertRuntimeSecurity(db:D1Database,tenant:string,stamp:SecurityStamp){const c=configuration();if(!c)return;const revision=await db.prepare('SELECT revision FROM hris_workspaces WHERE owner=?').bind(tenant).first<{revision:number}>(),challenge=crypto.randomUUID();if(!revision)throw new HttpError(503,'当前安全源不可用','SECURITY_SOURCE_UNAVAILABLE');let signed;try{signed=await c.runtime.current(tenant,challenge);}catch{throw new HttpError(503,'独立安全服务不可用或拒绝当前访问','SECURITY_LEDGER_UNAVAILABLE');}const proof=await verifyCurrentSecurityProof(signed,await verifier(c.publicKey),{tenant,challenge,authorizationRevision:stamp.authorizationRevision,workspaceRevision:revision.revision,recoveryEpoch:stamp.recoveryEpoch});stamp.externalSecurityEpoch=proof.epoch;}
export async function prepareRuntimeSecurityWrite(request:Omit<SecurityWriteRequest,'challenge'>){const c=configuration();if(!c)return null;const expected={...request,challenge:crypto.randomUUID()},signed=await c.runtime.prepare(expected),p=signed.permit;if(!p||p.purpose!=='r1-security-write-permit-v1'||Object.entries(expected).some(([key,value])=>(p as any)[key]!==value)||p.expiresAt<=Date.now()||p.expiresAt>Date.now()+60000||!await (await verifier(c.publicKey)).verify(new TextEncoder().encode(await digest(p)),signed.signature))throw new HttpError(503,'独立安全写入许可未核实','SECURITY_WRITE_PERMIT_INVALID');return {expiresAt:p.expiresAt,finalize:()=>c.runtime.finalize(request.tenant,request.commandId,request.requestDigest)};}
