import type {Member} from './authorization';
import {HttpError} from './http';
import {m01Entity,m01Write} from './r1-m01';
export type BusinessSnapshot={businessType:string;businessId:string;applicationVersion:number;revision:number;orgId:string;personId:string;initiatorId:string;title:string;values:Record<string,unknown>;requiredFields:string[];status:string};
export type EffectPlan={status:'applied'|'waiting'|'waiting_external'|'failed'|'blocked';statements:(token:string)=>D1PreparedStatement[]};
export type WorkflowAdapter={version:string;loadBusinessSnapshot:(id:string)=>Promise<BusinessSnapshot>;validateStart:(s:BusinessSnapshot,m:Member)=>Promise<void>;validateDecision:(s:BusinessSnapshot,m:Member)=>Promise<void>;planLocalEffect:(s:BusinessSnapshot,commandId:string)=>Promise<EffectPlan>;projectRejection:(s:BusinessSnapshot,commandId:string)=>Promise<(token:string)=>D1PreparedStatement[]>;canCancel:(s:BusinessSnapshot)=>Promise<boolean>;planLocalCancel:(s:BusinessSnapshot,commandId:string)=>Promise<(token:string)=>D1PreparedStatement[]>};
/** Explicit registry: no client supplied adapter IDs, no network and no R2/R3 producer impersonation. */
export function workflowAdapters(db:D1Database,tenant:string):Record<string,WorkflowAdapter>{
 const load=async(id:string)=>{const e=await m01Entity(db,tenant,id);if(e.kind!=='regularize_request')throw new HttpError(400,'原单类型不支持此流程','SOURCE_TYPE_MISMATCH');return e;};
 const eligible=async(s:BusinessSnapshot)=>{const p=await m01Entity(db,tenant,s.personId),employee=await db.prepare('SELECT status FROM hris_employees WHERE tenant_id=? AND id=?').bind(tenant,s.personId).first<{status:string}>();if(p.status==='ended'||employee?.status!=='试用')throw new HttpError(409,'仅当前试用人员可以转正','SOURCE_STATE_CHANGED');const request=await load(s.businessId),employment=await m01Entity(db,tenant,request.payload.employmentId);if(employment.status!=='active')throw new HttpError(409,'雇佣段已变化','SOURCE_STATE_CHANGED');const f=await db.prepare('SELECT command_id FROM r1_exit_fences WHERE tenant_id=? AND person_id=?').bind(tenant,s.personId).first<{command_id:string}>();if(f&&f.command_id!==request.payload.exitFenceObserved)throw new HttpError(409,'退出代次阻断','BLOCKED_BY_EXIT');};
 return {'personnel.regularize':{version:'r1-regularize-v1',async loadBusinessSnapshot(id){const e=await load(id);return {businessType:'personnel.regularize',businessId:e.id,applicationVersion:e.payload.applicationVersion,revision:e.revision,orgId:e.orgId!,personId:e.personId!,initiatorId:e.payload.initiatorId,title:'转正申请',values:{},requiredFields:['record'],status:e.status};},async validateStart(s,m){await eligible(s);if(s.status!=='pending'||s.initiatorId!==m.userId)throw new HttpError(409,'原单不能发起审批','SOURCE_STATE_CHANGED');},async validateDecision(s){await eligible(s);if(s.status!=='pending')throw new HttpError(409,'原单状态变化','SOURCE_STATE_CHANGED');},async planLocalEffect(s,commandId){await eligible(s);const e=await load(s.businessId),p=await m01Entity(db,tenant,s.personId),at=new Date().toISOString();return {status:'applied',statements:token=>[...m01Write(db,tenant,token,{...e,revision:e.revision+1,status:'applied'},commandId,at),...m01Write(db,tenant,token,{...p,revision:p.revision+1,payload:{...p.payload,probationStatus:'formal',regularizedAt:at}},commandId,at),db.prepare("UPDATE hris_employees SET status='正式' WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(tenant,s.personId,tenant,token)]};},async projectRejection(s,commandId){const e=await load(s.businessId);return token=>m01Write(db,tenant,token,{...e,revision:e.revision+1,status:'rejected'},commandId,new Date().toISOString());},async canCancel(s){return s.status==='pending';},async planLocalCancel(s,commandId){const e=await load(s.businessId);return token=>m01Write(db,tenant,token,{...e,revision:e.revision+1,status:'cancelled'},commandId,new Date().toISOString());}}};
}
