import {domainEventPlan} from './r1-domain-events';
import {z} from 'zod';
import type {Member} from './authorization';
import {HttpError} from './http';
import {authorizeTuple} from './r1-authorization';
import {securityStamp,commitCommand,replayCommand,digest,type CommandIntent,type SecurityStamp} from './r1-command';
import {validateDefinition,resolveNode,resolveDecisions,type WorkflowDefinition,type ReviewNode} from './r1-workflow-model';
import {workflowAdapters,type WorkflowAdapter,type BusinessSnapshot} from './r1-workflow-adapters';
const id=z.string().min(1).max(100),reason=z.string().trim().min(1).max(1000),revision=z.number().int().positive();
const target={id,expectedRevision:revision,generation:revision,delegationId:id.optional()};
export const workflowInput=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('publish'),id,orgId:id,definition:z.unknown()}).strict(),
 z.object({operation:z.literal('retire'),id,orgId:id}).strict(),
 z.object({operation:z.literal('start'),templateId:id,businessType:id,businessId:id,applicationVersion:revision}).strict(),
 z.object({operation:z.literal('decide'),...target,nodeRevision:revision,decision:z.enum(['approved','rejected']),reason}).strict(),
 z.object({operation:z.literal('transferNode'),...target,nodeRevision:revision,assignees:z.array(id).min(1).max(20),reason}).strict(),
 z.object({operation:z.literal('intervene'),...target,targetNode:id,reason}).strict(),
 z.object({operation:z.enum(['revokeFlow','withdraw','remind']),...target,reason}).strict(),
 z.object({operation:z.literal('createDelegation'),delegateId:id,actions:z.array(z.enum(['read','manage.transfer','manage.intervene','manage.revoke','remind'])).min(1).max(5),businessTypes:z.array(id).min(1).max(20),scope:z.array(id).min(1).max(20),fields:z.array(id).min(1).max(20),startAt:z.number().int().safe().nonnegative(),endAt:z.number().int().safe().nonnegative()}).strict(),
 z.object({operation:z.literal('acceptDelegation'),id,expectedRevision:revision,reason}).strict(),
 z.object({operation:z.literal('revokeDelegation'),id,expectedRevision:revision,reason}).strict(),
]);
type Context={db:D1Database;member:Member;row:{revision:number;data:string}};
type Instance={id:string;business_type:string;business_id:string;application_version:number;request_digest:string;org_id:string;person_id:string;title:string;initiator_id:string;revision:number;generation:number;approval_status:string;effect_status:string;current_node_id:string|null;source_revision:number;template_payload:string;created_at:string;updated_at:string};
type NodeRow={id:string;node_key:string;revision:number;generation:number;status:string;assignees:string;policy:string};
function fail(message:string,code:string,status=409):never{throw new HttpError(status,message,code);}
export async function workflowMember(db:D1Database,tenant:string,userId:string,stamp:SecurityStamp){const m=await db.prepare('SELECT user_id AS userId,tenant_id AS tenantId,role,employee_id AS employeeId,org_scope AS orgScope,view_email AS viewEmail,view_level AS viewLevel,active FROM hris_memberships WHERE tenant_id=? AND user_id=? AND active=1').bind(tenant,userId).first<Member>();if(!m)fail('成员不再有效','FORBIDDEN',403);return {...m,securityStamp:stamp};}
async function executeWorkflowInternal(ctx:Context,intent:CommandIntent,registry?:Record<string,WorkflowAdapter>,batchItem?:{batchId:string;itemId:string;requestDigest:string}){
 const c=workflowInput.parse(intent.payload),{db,member:m}=ctx,t=m.tenantId,stamp=await securityStamp(db,t),at=new Date().toISOString();
 const actorName=(await db.prepare('SELECT name FROM hris_access_grants WHERE tenant_id=? AND claimed_by=?').bind(t,m.userId).first<{name:string}>())?.name??m.userId;
 if(!stamp.featuresEnabled)fail('新能力未开放','FEATURE_NOT_READY');
 if(intent.action!=='M19.'+c.operation)fail('动作与载荷不匹配','UNKNOWN_COMMAND',400);
 const plans:((token:string)=>D1PreparedStatement[])[]=[],result:Record<string,unknown>={},adapters=registry??workflowAdapters(db,t);
 const guarded=(sql:string,args:unknown[])=> (token:string)=>[db.prepare(sql+' FROM hris_workspaces WHERE owner=? AND last_mutation=?').bind(...args,t,token)];
 const access=(member:Member,action:string,orgId:string,personId='',field='record')=>authorizeTuple(db,member,{objectType:'M19',action,orgId,personId,field,historyMode:'current'});
 const event=(instanceId:string|null,action:string,payload:unknown,principal:string|null=null,delegation:string|null=null)=>plans.push(guarded('INSERT INTO r1_workflow_events(tenant_id,id,instance_id,action,actor_id,principal_id,delegation_id,payload,at,command_id) SELECT owner,?,?,?,?,?,?,?,?,?',[crypto.randomUUID(),instanceId,action,m.userId,principal,delegation,JSON.stringify({details:payload,actorName,beforeWorkspaceRevision:intent.expectedWorkspaceRevision,afterWorkspaceRevision:intent.expectedWorkspaceRevision+1}),at,intent.commandId]));
 const replay=await replayCommand(db,m,stamp,intent);if(replay)return replay;
 const source=async(type:string,businessId:string)=>{if(type==='personnel.transfer')fail('D7禁止通用流程动作','D7_PROTECTED',400);const adapter=adapters[type];if(!adapter)fail('原单适配器未配置','ADAPTER_NOT_CONFIGURED');const s=await adapter.loadBusinessSnapshot(businessId);if(s.businessType==='personnel.transfer'||s.businessType!==type||s.businessId!==businessId)fail('原单类型与路由不符','D7_PROTECTED',400);return {adapter,s};};
 const qualify=async(assignees:string[],s:BusinessSnapshot)=>{if(!assignees.length||new Set(assignees).size!==assignees.length)fail('审批人为空或重复','INVALID_ASSIGNEES',400);for(const who of assignees){const member=await workflowMember(db,t,who,stamp);if(who===s.initiatorId||member.employeeId===s.personId)fail('不能审批本人事项','SELF_APPROVAL',403);for(const field of s.requiredFields)await access(member,'decide',s.orgId,s.personId,field);}};
 const notifications=(instanceId:string,node:NodeRow,d:WorkflowDefinition)=>{if(!d.notificationTemplateVersion)return;for(const recipient of JSON.parse(node.assignees) as string[])plans.push(guarded('INSERT OR IGNORE INTO r1_workflow_notifications(tenant_id,id,instance_id,node_id,node_revision,recipient_id,template_version,status,digest) SELECT owner,?,?,?,?,?,?,?,?',[crypto.randomUUID(),instanceId,node.id,node.revision,recipient,d.notificationTemplateVersion,'not_configured',`${node.id}:${node.revision}:${recipient}:${d.notificationTemplateVersion}`]));};
 const invalidate=(instanceId:string)=>plans.push(token=>[db.prepare("UPDATE r1_workflow_notifications SET status='invalidated' WHERE tenant_id=? AND instance_id=? AND status IN ('pending','failed','not_configured') AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(t,instanceId,t,token)]);
 const activate=async(instanceId:string,key:string,d:WorkflowDefinition,s:BusinessSnapshot,generation:number)=>{const n=resolveNode(d,key,s.values);if(n.type==='end')return null;await qualify(n.assignees,s);const row:NodeRow={id:crypto.randomUUID(),node_key:n.id,revision:1,generation,status:'pending',assignees:JSON.stringify(n.assignees),policy:JSON.stringify({...n,activationAuthorizationRevision:stamp.authorizationRevision,activatedAt:at,resolvedAssigneeIds:n.assignees})};plans.push(guarded('INSERT INTO r1_workflow_nodes(tenant_id,id,instance_id,node_key,revision,generation,status,assignees,policy) SELECT owner,?,?,?,?,?,?,?,?',[row.id,instanceId,row.node_key,row.revision,row.generation,row.status,row.assignees,row.policy]));notifications(instanceId,row,d);return row;};
 if(c.operation==='publish'||c.operation==='retire'){
  await access(m,'configure',c.orgId);const root=await db.prepare('SELECT current_version,business_type,org_id FROM r1_workflow_roots WHERE tenant_id=? AND id=?').bind(t,c.id).first<{current_version:number;business_type:string;org_id:string}>();
  if(root&&root.org_id!==c.orgId)fail('模板组织范围不匹配','FORBIDDEN',403);
  if(c.operation==='retire'){if(!root)fail('模板不存在','NOT_FOUND',404);plans.push(token=>[db.prepare('UPDATE r1_workflow_roots SET disabled=1 WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(t,c.id,t,token)]);}
  else {const d=validateDefinition(c.definition);if(root&&root.business_type!==d.businessType)fail('模板业务类型不能改写','TEMPLATE_TYPE_CONFLICT');if(!adapters[d.businessType]||adapters[d.businessType].version!==d.adapterVersion)fail('没有匹配版本的原单适配器','ADAPTER_NOT_CONFIGURED');for(const n of d.nodes)if(n.type==='review')for(const who of n.assignees)await workflowMember(db,t,who,stamp);const v=(root?.current_version??0)+1,hash=await digest(d);plans.push(guarded('INSERT INTO r1_workflow_templates(tenant_id,id,version,digest,payload,published_at) SELECT owner,?,?,?,?,?',[c.id,v,hash,JSON.stringify(d),at]));plans.push(token=>[db.prepare('INSERT INTO r1_workflow_roots(tenant_id,id,business_type,current_version,disabled,org_id) SELECT owner,?,?,?,0,? FROM hris_workspaces WHERE owner=? AND last_mutation=? ON CONFLICT(tenant_id,id) DO UPDATE SET current_version=excluded.current_version,disabled=0').bind(c.id,d.businessType,v,c.orgId,t,token)]);Object.assign(result,{templateId:c.id,version:v,digest:hash});}event(null,c.operation,{templateId:c.id});
 }else if(c.operation==='createDelegation'){
  if(c.delegateId===m.userId||c.endAt<c.startAt)fail('不能自委托或设置反向有效期','INVALID_DELEGATION',400);await workflowMember(db,t,c.delegateId,stamp);
  for(const org of c.scope)for(const action of c.actions)for(const field of c.fields)await access(m,action,org,'',field);
  const overlaps=await db.prepare("SELECT actions,scope,business_types FROM r1_admin_delegations WHERE tenant_id=? AND principal_id=? AND delegate_id=? AND status IN ('pending_acceptance','accepted') AND start_at<? AND end_at>?").bind(t,m.userId,c.delegateId,c.endAt,c.startAt).all<{actions:string;scope:string;business_types:string}>();
  if(overlaps.results.some(d=>c.actions.some(a=>JSON.parse(d.actions).includes(a))&&c.scope.some(o=>JSON.parse(d.scope).includes(o))&&c.businessTypes.some(b=>JSON.parse(d.business_types).includes(b))))fail('委托管理范围重叠','DELEGATION_OVERLAP');
  const id=crypto.randomUUID();plans.push(guarded('INSERT INTO r1_admin_delegations(tenant_id,id,principal_id,delegate_id,actions,business_types,scope,fields,start_at,end_at,revision,status) SELECT owner,?,?,?,?,?,?,?,?,?,1,?',[id,m.userId,c.delegateId,JSON.stringify(c.actions),JSON.stringify(c.businessTypes),JSON.stringify(c.scope),JSON.stringify(c.fields),c.startAt,c.endAt,'pending_acceptance']));result.delegationId=id;event(null,c.operation,{id},m.userId,id);
 }else if(c.operation==='acceptDelegation'||c.operation==='revokeDelegation'){
  const d=await db.prepare('SELECT * FROM r1_admin_delegations WHERE tenant_id=? AND id=?').bind(t,c.id).first<any>();if(!d||d.revision!==c.expectedRevision)fail('委托版本已变化','REVISION_CONFLICT');
  if(c.operation==='acceptDelegation'){if(d.delegate_id!==m.userId||d.status!=='pending_acceptance'||d.end_at<=Date.now())fail('不能接受此委托','FORBIDDEN',403);await workflowMember(db,t,d.principal_id,stamp);}
  else if(![d.principal_id,d.delegate_id].includes(m.userId)||!['pending_acceptance','accepted'].includes(d.status))fail('不能撤销此委托','FORBIDDEN',403);
  plans.push(token=>[db.prepare('UPDATE r1_admin_delegations SET status=?,accepted_at=?,revision=revision+1,revoke_reason=? WHERE tenant_id=? AND id=? AND revision=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(c.operation==='acceptDelegation'?'accepted':'revoked',c.operation==='acceptDelegation'?at:d.accepted_at,c.reason,t,c.id,c.expectedRevision,t,token)]);event(null,c.operation,{id:c.id,reason:c.reason},d.principal_id,c.id);
 }else if(c.operation==='start'){
  const {adapter,s}=await source(c.businessType,c.businessId);await access(m,'start',s.orgId,s.personId);if(s.applicationVersion!==c.applicationVersion)fail('原单申请版本变化','SOURCE_VERSION_CONFLICT');await adapter.validateStart(s,m);
  const published=await db.prepare('SELECT t.payload,t.version,t.digest FROM r1_workflow_roots r JOIN r1_workflow_templates t ON t.tenant_id=r.tenant_id AND t.id=r.id AND t.version=r.current_version WHERE r.tenant_id=? AND r.id=? AND r.disabled=0 AND r.business_type=? AND r.org_id=?').bind(t,c.templateId,c.businessType,s.orgId).first<any>();if(!published)fail('没有可用审批模板','TEMPLATE_UNAVAILABLE');const d=validateDefinition(JSON.parse(published.payload));if(adapter.version!==d.adapterVersion)fail('适配器版本变化','ADAPTER_VERSION_CONFLICT');
  const hash=await digest({s,templateId:c.templateId,templateVersion:published.version,templateDigest:published.digest});const prior=await db.prepare('SELECT id,request_digest FROM r1_workflow_instances WHERE tenant_id=? AND business_type=? AND business_id=? AND application_version=?').bind(t,c.businessType,c.businessId,c.applicationVersion).first<any>();
  if(prior){if(prior.request_digest!==hash)fail('原单申请键内容冲突','APPLICATION_CONFLICT');result.instanceId=prior.id;result.applicationReplayed=true;}
  else {const id=crypto.randomUUID(),n=await activate(id,d.entry,d,s,1);if(!n)fail('发起不能自动通过','AUTO_PASS_FORBIDDEN');plans.unshift(guarded('INSERT INTO r1_workflow_instances(tenant_id,id,business_type,business_id,application_version,request_digest,org_id,person_id,title,initiator_id,revision,generation,approval_status,effect_status,current_node_id,source_revision,template_payload,created_at,updated_at) SELECT owner,?,?,?,?,?,?,?,?,?,1,1,?,?,?,?,?,?,?',[id,s.businessType,s.businessId,s.applicationVersion,hash,s.orgId,s.personId,s.title,s.initiatorId,'pending','not_requested',n.id,s.revision,JSON.stringify({definition:d,templateId:c.templateId,templateVersion:published.version,templateDigest:published.digest,values:s.values,requiredFields:s.requiredFields}),at,at]));result.instanceId=id;event(id,'start',{templateId:c.templateId,version:published.version,sourceRevision:s.revision});}
 }else {
  const i=await db.prepare('SELECT * FROM r1_workflow_instances WHERE tenant_id=? AND id=?').bind(t,c.id).first<Instance>();if(!i)fail('申请不存在或不可见','NOT_FOUND_OR_NOT_VISIBLE',404);
  const {adapter,s}=await source(i.business_type,i.business_id),frozen=JSON.parse(i.template_payload),d=validateDefinition(frozen.definition);if(adapter.version!==d.adapterVersion)fail('原单适配器版本变化','ADAPTER_VERSION_CONFLICT');
  const action=c.operation==='transferNode'?'manage.transfer':c.operation==='intervene'?'manage.intervene':c.operation==='revokeFlow'?'manage.revoke':c.operation;
  for(const field of frozen.requiredFields)await access(m,action,i.org_id,i.person_id,field);
  let principal:string|null=null;
  if(c.delegationId){if(!['manage.transfer','manage.intervene','manage.revoke','remind'].includes(action))fail('委托不授予审批权','DELEGATION_ACTION_FORBIDDEN',403);const delegate=await db.prepare('SELECT * FROM r1_admin_delegations WHERE tenant_id=? AND id=?').bind(t,c.delegationId).first<any>();
   if(!delegate||delegate.delegate_id!==m.userId||delegate.status!=='accepted'||!delegate.accepted_at||delegate.start_at>Date.now()||delegate.end_at<=Date.now()||!JSON.parse(delegate.actions).includes(action)||!JSON.parse(delegate.business_types).includes(i.business_type)||!JSON.parse(delegate.scope).includes(i.org_id)||frozen.requiredFields.some((f:string)=>!JSON.parse(delegate.fields).includes(f)))fail('委托当前无效或范围不足','DELEGATION_INVALID',403);
   principal=delegate.principal_id;const p=await workflowMember(db,t,principal!,stamp);for(const field of frozen.requiredFields)await access(p,action,i.org_id,i.person_id,field);
   plans.push(token=>[db.prepare(`INSERT INTO r1_workflow_commit_guard(tenant_id,command_id,valid) SELECT owner,?,CASE WHEN EXISTS(SELECT 1 FROM r1_admin_delegations d JOIN hris_memberships p ON p.tenant_id=d.tenant_id AND p.user_id=d.principal_id JOIN hris_memberships a ON a.tenant_id=d.tenant_id AND a.user_id=d.delegate_id WHERE d.tenant_id=? AND d.id=? AND d.revision=? AND d.status='accepted' AND d.accepted_at IS NOT NULL AND p.active=1 AND a.active=1 AND d.start_at<=(julianday('now')-2440587.5)*86400000 AND d.end_at>(julianday('now')-2440587.5)*86400000) THEN 1 ELSE 0 END FROM hris_workspaces WHERE owner=? AND last_mutation=?`).bind(intent.commandId,t,c.delegationId,delegate.revision,t,token)]);
  }
  if(i.revision!==c.expectedRevision||i.generation!==c.generation)fail('申请版本或节点代次变化','REVISION_CONFLICT');if(i.approval_status!=='pending')fail('审批已关闭','NODE_CLOSED');
  if(s.revision!==i.source_revision||s.applicationVersion!==i.application_version)fail('原单版本变化','SOURCE_VERSION_CONFLICT');
  const n=await db.prepare('SELECT * FROM r1_workflow_nodes WHERE tenant_id=? AND id=?').bind(t,i.current_node_id).first<NodeRow>();if(!n||n.status!=='pending'||n.generation!==i.generation)fail('当前节点已关闭','NODE_CLOSED');
  let status=i.approval_status,effect=i.effect_status,nodeId=i.current_node_id,generation=i.generation;
  const closeNode=(status:string)=>plans.push(token=>[db.prepare('UPDATE r1_workflow_nodes SET status=? WHERE tenant_id=? AND id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(status,t,n.id,t,token)]);
  if(c.operation==='decide'){
   if(c.nodeRevision!==n.revision||!JSON.parse(n.assignees).includes(m.userId))fail('旧节点或不属于当前审批人','NODE_CLOSED');if(m.userId===i.initiator_id||m.employeeId===i.person_id)fail('不能审批本人事项','SELF_APPROVAL',403);await adapter.validateDecision(s,m);
   const old=await db.prepare('SELECT actor_id AS actorId,decision FROM r1_workflow_decisions WHERE tenant_id=? AND node_id=? AND node_revision=?').bind(t,n.id,n.revision).all<{actorId:string;decision:string}>();if(old.results.some(r=>r.actorId===m.userId))fail('此审批人已提交决定','ALREADY_DECIDED');const decisions=[...old.results,{actorId:m.userId,decision:c.decision}],policy={...JSON.parse(n.policy),assignees:JSON.parse(n.assignees)} as ReviewNode,resolved=resolveDecisions(policy,decisions);
   plans.push(guarded('INSERT INTO r1_workflow_decisions(tenant_id,id,node_id,node_revision,actor_id,decision,reason,at,command_id,digest,actor_name) SELECT owner,?,?,?,?,?,?,?,?,?,?',[crypto.randomUUID(),n.id,n.revision,m.userId,c.decision,c.reason,at,intent.commandId,await digest({nodeId:n.id,nodeRevision:n.revision,actorId:m.userId,decision:c.decision,reason:c.reason,at,commandId:intent.commandId}),actorName]));
   if(resolved==='rejected'){plans.push(await adapter.projectRejection(s,intent.commandId));status='rejected';closeNode('rejected');invalidate(i.id);}
   else if(resolved==='blocked'){effect='blocked';}
   else if(resolved==='approved'){closeNode('approved');invalidate(i.id);const next=await activate(i.id,policy.next,d,{...s,values:frozen.values},generation);nodeId=next?.id??null;if(!next){status='approved';const plan=await adapter.planLocalEffect(s,intent.commandId);effect=plan.status;plans.push(plan.statements);}}
   event(i.id,'decide',{nodeId:n.id,nodeRevision:n.revision,decision:c.decision,reason:c.reason,resolution:resolved,cancelledByResolution:resolved==='pending'||resolved==='blocked'?[]:policy.assignees.filter(w=>!decisions.some(d=>d.actorId===w))});
  }else if(c.operation==='transferNode'){
   if(c.nodeRevision!==n.revision)fail('节点版本变化','NODE_CLOSED');await qualify(c.assignees,s);closeNode('transferred');invalidate(i.id);
   const next={...n,id:crypto.randomUUID(),revision:n.revision+1,assignees:JSON.stringify(c.assignees)};plans.push(guarded('INSERT INTO r1_workflow_nodes(tenant_id,id,instance_id,node_key,revision,generation,status,assignees,policy) SELECT owner,?,?,?,?,?,?,?,?',[next.id,i.id,next.node_key,next.revision,next.generation,'pending',next.assignees,next.policy]));nodeId=next.id;notifications(i.id,next,d);
   event(i.id,c.operation,{oldNode:n.id,nodeId:next.id,assignees:c.assignees,reason:c.reason},principal,c.delegationId??null);
  }else if(c.operation==='intervene'){
   if(!d.interventionTargets.includes(c.targetNode))fail('干预目标未获模板许可','INVALID_INTERVENTION');generation++;closeNode('skipped_by_intervention');invalidate(i.id);const next=await activate(i.id,c.targetNode,d,{...s,values:frozen.values},generation);nodeId=next!.id;effect='not_requested';event(i.id,c.operation,{from:n.node_key,to:c.targetNode,generation,reason:c.reason},principal,c.delegationId??null);
  }else if(c.operation==='withdraw'||c.operation==='revokeFlow'){
   if(c.operation==='withdraw'&&i.initiator_id!==m.userId)fail('仅原申请人撤回','FORBIDDEN',403);if(effect==='applied'||!await adapter.canCancel(s))fail('原单不允许撤销','CANNOT_CANCEL');plans.push(await adapter.planLocalCancel(s,intent.commandId));status=c.operation==='withdraw'?'withdrawn':'cancelled';effect='cancelled';closeNode('cancelled');invalidate(i.id);event(i.id,c.operation,{reason:c.reason},principal,c.delegationId??null);
  }else if(c.operation==='remind'){notifications(i.id,n,d);event(i.id,c.operation,{reason:c.reason},principal,c.delegationId??null);}
  plans.push(token=>[db.prepare('UPDATE r1_workflow_instances SET revision=revision+1,generation=?,approval_status=?,effect_status=?,current_node_id=?,updated_at=? WHERE tenant_id=? AND id=? AND revision=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(generation,status,effect,nodeId,at,t,i.id,i.revision,t,token)]);Object.assign(result,{instanceId:i.id,revision:i.revision+1,generation,approvalStatus:status,effectStatus:effect});
 }
 if(result.instanceId&&!result.applicationReplayed)plans.push(await domainEventPlan(db,t,intent,{source:'M19',eventType:c.operation==='start'?'node.activated':c.operation==='decide'?'approval.decided':c.operation==='remind'?'notification.requested':'node.changed',internalId:String(result.instanceId),entityRevision:Number(result.revision??1),definitionVersion:'workflow-r1-v1',payload:{...(result.approvalStatus?{approvalStatus:result.approvalStatus as any}:{}),...(result.effectStatus?{effectStatus:result.effectStatus as any}:{})}}));
 if(batchItem)plans.push(guarded('INSERT INTO r1_workflow_batch_items(tenant_id,batch_id,item_id,actor_id,request_digest,command_id,result) SELECT owner,?,?,?,?,?,?',[batchItem.batchId,batchItem.itemId,m.userId,batchItem.requestDigest,intent.commandId,JSON.stringify({status:'committed',commandId:intent.commandId,beforeRevision:'expectedRevision' in c?c.expectedRevision:null,afterRevision:result.revision??null,reasonCode:null,queryRef:'/api/r1/commands/'+intent.commandId})]));
 try{return await commitCommand(db,m,stamp,intent,token=>plans.flatMap(p=>p(token)),result);}catch(e){if(e instanceof Error&&e.message.includes('r1_delegation_commit_guard'))fail('委托在提交时已过期','DELEGATION_EXPIRED');throw e;}
}

export async function executeWorkflow(...args:Parameters<typeof executeWorkflowInternal>){
 try{return await executeWorkflowInternal(...args);}catch(e){
  if(e instanceof HttpError&&[400,403,404,409].includes(e.status)){const [ctx,intent]=args;try{const r=await ctx.db.prepare('INSERT INTO r1_workflow_denials SELECT m.tenant_id,?,?,?,?,?,s.authorization_revision,? FROM hris_memberships m JOIN r1_schema_state s ON s.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.user_id=? AND m.active=1 AND s.open_gate=1').bind(crypto.randomUUID(),ctx.member.userId,intent.commandId,intent.action,e.machineCode??'REJECTED',new Date().toISOString(),ctx.member.tenantId,ctx.member.userId).run();Object.assign(e,{denialAuditRecorded:!!r.meta.changes});}catch{Object.assign(e,{denialAuditRecorded:false});}}throw e;
 }
}
