import {z} from 'zod';
import {HttpError} from './http';
import {securityStamp,sameStamp} from './r1-command';
import {authorizeTuple} from './r1-authorization';
import {workflowMember} from './r1-workflow';
import {projectR1CoreState} from './r1-core-read';
import {visibleState} from './authorization';
import type {memberContext} from './context';
type Context=Awaited<ReturnType<typeof memberContext>>;
export async function readWorkflows(ctx:Context,params:URLSearchParams){
 const {db,member:m}=ctx,t=m.tenantId,stamp=await securityStamp(db,t);if(!stamp.featuresEnabled)throw new HttpError(409,'新能力未开放','FEATURE_NOT_READY');
 const limit=z.coerce.number().int().min(1).max(100).parse(params.get('limit')??20),q=z.string().max(100).parse(params.get('q')??'').trim().toLowerCase(),type=z.string().max(100).parse(params.get('businessType')??''),partition=z.enum(['all','approval','execution','closed']).parse(params.get('partition')??'all'),cursor=params.get('cursor'),detail=params.get('id'),delegationId=params.get('delegationId');
 const approval=z.enum(['','pending','approved','rejected','withdrawn','cancelled']).parse(params.get('approvalStatus')??''),effect=z.enum(['','not_requested','waiting','waiting_external','applied','failed','cancelled','blocked']).parse(params.get('effectStatus')??''),ownership=z.enum(['all','initiated','assigned','managed']).parse(params.get('ownership')??'all');
 const guard={approval,effect,ownership,actor:m.userId,tenant:t,revision:ctx.row.revision,auth:stamp.authorizationRevision,writer:stamp.writerEpoch,recovery:stamp.recoveryEpoch,q,type,partition,delegationId};let after='';if(cursor){let c:any;try{c=JSON.parse(atob(cursor));}catch{throw new HttpError(400,'游标无效','INVALID_CURSOR');}for(const [k,v] of Object.entries(guard))if(c[k]!==v)throw new HttpError(409,'列表权限或数据已变化','CURSOR_STALE');after=z.string().max(200).parse(c.after);}
 const can=async(org:string,person:string,action='read',field='record',history=false)=>{try{await authorizeTuple(db,m,{objectType:'M19',action,orgId:org,personId:person,field,historyMode:history?'history':'current'});return true;}catch(e){if(e instanceof HttpError&&e.status===403)return false;throw e;}};
 let delegation:any=null,principal:Awaited<ReturnType<typeof workflowMember>>|null=null;
 if(delegationId){delegation=await db.prepare('SELECT * FROM r1_admin_delegations WHERE tenant_id=? AND id=? AND delegate_id=?').bind(t,delegationId,m.userId).first();if(!delegation||delegation.status!=='accepted'||!delegation.accepted_at||delegation.start_at>Date.now()||delegation.end_at<=Date.now()||!JSON.parse(delegation.actions).includes('read'))throw new HttpError(403,'委托查询无效','DELEGATION_INVALID');principal=await workflowMember(db,t,delegation.principal_id,stamp);}
 const permitted=async(i:any)=>{if(!await can(i.org_id,i.person_id))return false;if(principal){if(!JSON.parse(delegation.scope).includes(i.org_id)||!JSON.parse(delegation.business_types).includes(i.business_type)||!JSON.parse(delegation.fields).includes('record'))return false;try{await authorizeTuple(db,principal,{objectType:'M19',action:'read',orgId:i.org_id,personId:i.person_id,field:'record',historyMode:'current'});}catch(e){if(e instanceof HttpError&&e.status===403)return false;throw e;}}return true;};
 const records=await db.prepare('SELECT * FROM r1_workflow_instances WHERE tenant_id=?'+(detail?' AND id=?':'')+' ORDER BY id LIMIT 501').bind(t,...(detail?[detail]:[])).all<any>();if(records.results.length>500)throw new HttpError(503,'此查询需要持久权限投影分页','BOUNDED_QUERY_REQUIRED');
 const visible:any[]=[];
 for(const i of records.results){if(!await permitted(i))continue;const n=i.current_node_id?await db.prepare('SELECT id,revision,generation,status,assignees FROM r1_workflow_nodes WHERE tenant_id=? AND id=?').bind(t,i.current_node_id).first<any>():null,required=JSON.parse(i.template_payload).requiredFields as string[];
  const actions:string[]=[];if(i.approval_status==='pending'){
   if(n?.status==='pending'&&JSON.parse(n.assignees).includes(m.userId)&&i.initiator_id!==m.userId&&i.person_id!==m.employeeId){let allowed=true;for(const field of required)if(!await can(i.org_id,i.person_id,'decide',field))allowed=false;if(allowed)actions.push('decide');}
   for(const [op,action] of [['transferNode','manage.transfer'],['intervene','manage.intervene'],['revokeFlow','manage.revoke'],['remind','remind'],['withdraw','withdraw']]){let allowed=true;for(const field of required)if(!await can(i.org_id,i.person_id,action,field))allowed=false;if(allowed&&(op!=='withdraw'||i.initiator_id===m.userId))actions.push(op);}
  }
  visible.push({id:i.id,businessType:i.business_type,businessId:i.business_id,title:i.title,revision:i.revision,generation:i.generation,nodeRevision:n?.revision??null,approvalStatus:i.approval_status,effectStatus:i.effect_status,initiated:i.initiator_id===m.userId,assigned:!!n&&JSON.parse(n.assignees).includes(m.userId),managed:actions.some(a=>['transferNode','intervene','revokeFlow'].includes(a)),partition:i.approval_status==='pending'?'approval':['waiting','waiting_external','failed','blocked'].includes(i.effect_status)?'execution':'closed',actions,href:'/r1-approvals',templateVersion:JSON.parse(i.template_payload).templateVersion});
 }
 if(!detail&&!delegationId){const state=await projectR1CoreState(db,m,visibleState(JSON.parse(ctx.row.data),m));for(const a of state.approvals){const transfer=a.details?.transfer;if(!transfer)continue;const org=transfer.source.orgId;if(!await can(org,a.employeeId))continue;const execution=(transfer as any).execution;visible.push({id:'D7:'+a.id,businessType:'personnel.transfer',businessId:a.id,title:'调动申请',revision:ctx.row.revision,generation:null,nodeRevision:null,approvalStatus:a.status,effectStatus:execution??'not_requested',partition:a.status==='pending'?'approval':['waiting','failed'].includes(execution)?'execution':'closed',actions:[],href:'/approvals',protectedPath:'D7'});}}
 visible.sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);const counts=visible.reduce<Record<string,number>>((a,i)=>({...a,[i.businessType]:(a[i.businessType]??0)+1}),{}),partitionCounts=visible.reduce<Record<string,number>>((a,i)=>({...a,[i.partition]:(a[i.partition]??0)+1}),{}),filtered=visible.filter(i=>(!approval||i.approvalStatus===approval)&&(!effect||i.effectStatus===effect)&&(ownership==='all'||i[ownership])&&(!type||i.businessType===type)&&(partition==='all'||partition===i.partition)&&i.title.toLowerCase().includes(q));
 let history:unknown=null;if(detail){const i=records.results.find(i=>i.id===detail);if(!i||!visible.length)throw new HttpError(404,'申请不存在或不可见','NOT_FOUND_OR_NOT_VISIBLE');if(await can(i.org_id,i.person_id,'read','record',true)){const events=await db.prepare('SELECT id,action,actor_id AS actorId,principal_id AS principalId,delegation_id AS delegationId,at,payload FROM r1_workflow_events WHERE tenant_id=? AND instance_id=? AND id>? ORDER BY id LIMIT 51').bind(t,detail,params.get('historyAfter')??'').all();const showReason=await can(i.org_id,i.person_id,'read','reason',true);history={items:events.results.slice(0,50).map((e:any)=>{const p=JSON.parse(e.payload);return {id:e.id,action:e.action,actorId:e.actorId,actorName:p.actorName??e.actorId,principalId:e.principalId,delegationId:e.delegationId,at:e.at,...(showReason?{reason:p.details?.reason??null}:{})};}),next:events.results.length>50?(events.results[49] as any).id:null};}}
 const latest=await db.prepare('SELECT revision FROM hris_workspaces WHERE owner=?').bind(t).first<{revision:number}>();if(latest?.revision!==ctx.row.revision||!sameStamp(stamp,await securityStamp(db,t))||delegation&&delegation.end_at<=Date.now())throw new HttpError(409,'读取中权限或版本变化','REVISION_CONFLICT');
 const page=filtered.filter(i=>i.id>after).slice(0,limit+1),items=page.slice(0,limit);return {items,total:filtered.length,counts,partitionCounts,history,revision:ctx.row.revision,securityStamp:stamp,nextCursor:page.length>limit?btoa(JSON.stringify({...guard,after:items.at(-1)!.id})):null};
}
