import {canEvaluateAppointment} from './interview-schedule';
import {structuredInterviewFields,freezeInterviewEvaluation} from './recruitment-evaluations';
import {recruitmentJobSnapshot} from './recruitment-jobs';
import {requisitionAwaitingApproval} from './recruitment-status';
import {z} from 'zod';
import {businessDate} from './workforce';
import type {State} from './model';
import {scopedOrgs,type Member} from './authorization';
import {HttpError} from './http';
import {visibleRecord,type DevelopmentRecord as R} from './development';
const id=z.string().min(1).max(100),text=z.string().trim().min(1).max(200),evidence=z.string().trim().min(5).max(4000),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return !isNaN(d.getTime())&&d.toISOString().slice(0,10)===v;});
const details=z.object({type:z.enum(['new','replacement','reserve']).optional(),urgency:z.enum(['high','medium','low']).optional(),requestedOn:date.optional(),expectedOn:date.optional(),duties:z.string().trim().max(2000).optional(),qualifications:z.string().trim().max(2000).optional()}).strict();
export const recruitmentCommand=z.discriminatedUnion('action',[
 z.object({action:z.literal('requisition'),submit:z.boolean().optional(),details:details.optional(),positionId:id,title:text,headcount:z.number().int().min(1).max(10000),reason:evidence}),
 z.object({action:z.literal('reviseRequisition'),id,submit:z.boolean().optional(),details:details.optional(),title:text,headcount:z.number().int().min(1).max(10000),reason:evidence}),z.object({action:z.literal('returnRequisition'),id,reason:evidence}),
 z.object({action:z.literal('submitRequisition'),id}),z.object({action:z.literal('approveRequisition'),id}),z.object({action:z.literal('closeRequisition'),id,reason:evidence}),
 z.object({action:z.literal('candidate'),jobId:id.optional(),requisitionId:id,name:text,email:z.string().trim().email().max(200).or(z.literal('')),source:evidence}),
 z.object({action:z.literal('structuredInterview'),candidateId:id,appointmentId:id.optional(),...structuredInterviewFields,recommendation:z.enum(['advance','reject']),evidence:z.string().trim().min(5).max(1500)}).strict(),
 z.object({action:z.literal('interview'),candidateId:id,rating:z.number().int().min(1).max(5),recommendation:z.enum(['advance','reject']),evidence}),
 z.object({action:z.literal('offer'),id,joined:date,gradeId:id.optional(),evidence}),
 z.object({action:z.literal('approveOffer'),id}),z.object({action:z.literal('returnOffer'),id,reason:evidence}),
 z.object({action:z.literal('acceptOffer'),id,evidence}),
 z.object({action:z.literal('rejectCandidate'),id,reason:evidence}),
 z.object({action:z.literal('hire'),id,code:text}),
]);
export function applyRecruitment(records:R[],state:State,member:Member,input:unknown,at=new Date().toISOString()){
 const c=recruitmentCommand.parse(input),scope=scopedOrgs(state,member);
 const invalid=(message:string):never=>{throw new HttpError(400,message);},deny=(message:string):never=>{throw new HttpError(403,message);};
 const hr=()=>{if(!['admin','hr'].includes(member.role))deny('仅管理员或HR可维护招聘业务');};
 const approver=(createdBy:string)=>{if(!['admin','manager'].includes(member.role)||createdBy===member.userId)deny('招聘审批须由其他有权限的管理人员完成');};
 const position=(id:string)=>{const p=state.positions?.find(p=>p.id===id);if(!p||!scope.has(p.orgId))deny('没有此岗位的数据权限');if(p!.status!=='启用')invalid('岗位已停用');return p!;};
 const get=(id:string,kind:R['kind'])=>{const r=records.find(r=>r.id===id&&r.kind===kind);if(!r||!visibleRecord(r,records,state,member))deny('记录不存在或没有访问权限');return r!;};
 const req=(r:R)=>{const q=get(r.referenceId!,'requisition');if(q.status!=='active')invalid('招聘需求未批准或已关闭');return q;};
 const offerTargets=(r:R)=>{position(r.positionId!);if(r.payload.gradeId&&!state.grades?.some(g=>g.id===r.payload.gradeId&&g.status==='启用'))invalid('录用目标职级已停用，请退回重新核对或结束候选流程');};
 const make=(kind:R['kind'],payload:R['payload'],extra:Partial<R>={})=>({id:crypto.randomUUID(),kind,payload,employeeId:null,positionId:null,referenceId:null,status:'draft',createdBy:member.userId,createdAt:at,updatedAt:at,...extra} as R);
 const change=(r:R,status:string,payload:R['payload']={})=>({...r,status,payload:{...r.payload,...payload},updatedAt:at});
 let record:R,completedAppointment:R|undefined,employeeInput:Record<string,unknown>|undefined;
 switch(c.action){
 case 'requisition':{hr();position(c.positionId);record=make('requisition',{requisitionSubmissionRequired:true,recruitmentDetails:c.details,...(c.submit?{submittedBy:member.userId,submittedAt:at}:{}),version:1,contributors:[member.userId],title:c.title,headcount:c.headcount,reason:c.reason},{positionId:c.positionId,status:c.submit?'submitted':'draft'});break;}
 case 'submitRequisition':{hr();const r=get(c.id,'requisition');position(r.positionId!);if(r.status!=='draft'||!r.payload.requisitionSubmissionRequired)invalid('只有待提交的新制草稿可以发起审批');record=change(r,'submitted',{submittedBy:member.userId,submittedAt:at,contributors:Array.from(new Set([r.createdBy,...(r.payload.contributors??[]),member.userId]))});break;}
 case 'approveRequisition':{const r=get(c.id,'requisition');approver(r.createdBy);if(r.payload.contributors?.includes(member.userId))deny('参与编写或修改需求的人不能审批该需求');position(r.positionId!);if(!requisitionAwaitingApproval(r))invalid('需求尚未提交或已经处理');record=change(r,'active',{approvedBy:member.userId,approvedAt:at});break;}
 case 'reviseRequisition':{hr();const r=get(c.id,'requisition');position(r.positionId!);if(!['draft','returned'].includes(r.status))invalid('仅未批准或已退回需求可修订');record=change(r,c.submit?'submitted':'draft',{requisitionSubmissionRequired:true,recruitmentDetails:c.details??r.payload.recruitmentDetails,version:(r.payload.version??1)+1,contributors:Array.from(new Set([r.createdBy,...(r.payload.contributors??[]),member.userId])),title:c.title,headcount:c.headcount,reason:c.reason,verification:undefined,verifiedBy:undefined,verifiedAt:undefined,submittedBy:c.submit?member.userId:undefined,submittedAt:c.submit?at:undefined});break;}
 case 'returnRequisition':{const r=get(c.id,'requisition');approver(r.createdBy);if(r.payload.contributors?.includes(member.userId))deny('参与编写或修改需求的人不能审批该需求');if(!requisitionAwaitingApproval(r))invalid('仅待审批需求可退回');record=change(r,'returned',{verification:c.reason,verifiedBy:member.userId,verifiedAt:at});break;}
 case 'closeRequisition':{hr();const r=get(c.id,'requisition');if(!['draft','submitted','returned','active'].includes(r.status))invalid('需求已经关闭');if(records.some(x=>x.kind==='candidate'&&x.referenceId===r.id&&!['hired','rejected'].includes(x.status)))invalid('仍有在途候选人，请先完成或结束招聘流程');record=change(r,'closed',{closedReason:c.reason});break;}
 case 'candidate':{hr();const q=get(c.requisitionId,'requisition');position(q.positionId!);if(q.status!=='active')invalid('需求须先通过审批');if(member.role!=='admin'&&!member.viewEmail&&c.email)deny('没有联系邮箱维护权限');if(c.email&&records.some(r=>r.kind==='candidate'&&r.referenceId===q.id&&r.payload.email?.toLowerCase()===c.email.toLowerCase()&&r.status!=='rejected'))invalid('此需求已有相同邮箱的候选人');const job=c.jobId?get(c.jobId,'recruitmentJob'):undefined;if(job&&(job.status!=='active'||job.referenceId!==q.id))invalid('请选择同一需求下启用的招聘职位版本');const frozenJob=job?recruitmentJobSnapshot.parse({id:job.id,rootId:job.payload.definitionRootId,version:job.payload.version,title:job.payload.title,details:job.payload.jobDetails,workflow:job.payload.jobWorkflow}):undefined;record=make('candidate',{recruitmentJob:frozenJob,name:c.name,email:c.email,source:c.source},{positionId:q.positionId,referenceId:q.id,status:'screening'});break;}
 case 'structuredInterview':
 case 'interview':{if(!['admin','hr','manager'].includes(member.role))deny('没有面试评价权限');const r=get(c.candidateId,'candidate');req(r);position(r.positionId!);if(!['screening','interviewed'].includes(r.status))invalid('当前阶段不能记录面试');let evaluation;if(c.action==='structuredInterview'){let d:R;const p=position(r.positionId!);if(c.appointmentId){const appointment=get(c.appointmentId,'interviewAppointment'),snapshot=appointment.payload.interviewSchedule?.definition;if(appointment.referenceId!==r.id||snapshot?.id!==c.definitionId)invalid('排期与候选或评价表不匹配');if(!canEvaluateAppointment(appointment,records,state,member,at))deny('仅面试结束后，仍有当前管理权限的指定人员可评价有效排期');d={...appointment,id:snapshot!.id,status:'sealed',payload:{orgId:snapshot!.orgId,title:snapshot!.title,definitionRootId:snapshot!.rootId,version:snapshot!.version,interviewCriteria:snapshot!.criteria}};completedAppointment={...appointment,status:'completed',updatedAt:at};}else d=get(c.definitionId,'interviewDefinition');if(d.payload.orgId!==p.orgId)invalid('评价表须属于候选岗位同一组织');evaluation=freezeInterviewEvaluation(d,c.scores,c.comments,c.recommendation);}const prior=records.filter(x=>x.kind==='interview'&&x.referenceId===r.id);record=make('interview',{version:prior.reduce((v,x)=>Math.max(v,x.payload.version??0),prior.length)+1,rating:c.action==='interview'?c.rating:undefined,interviewEvaluation:evaluation,interviewAppointmentId:c.action==='structuredInterview'?c.appointmentId:undefined,recommendation:c.recommendation,evidence:c.evidence},{positionId:r.positionId,referenceId:r.id,status:'recorded'});break;}
 case 'offer':{hr();const r=get(c.id,'candidate');req(r);position(r.positionId!);if(records.some(x=>x.kind==='interviewAppointment'&&x.referenceId===r.id&&x.status==='scheduled'))invalid('仍有未完成面试排期，请由指定人员评价或明确取消');if(!['screening','interviewed'].includes(r.status))invalid('当前阶段不能发起录用');const interviews=records.filter(x=>x.kind==='interview'&&x.referenceId===r.id).sort((a,b)=>(b.payload.version??0)-(a.payload.version??0)||b.createdAt.localeCompare(a.createdAt)),latest=interviews[0];if(latest&&!latest.payload.version&&interviews.some(x=>x.id!==latest.id&&x.createdAt===latest.createdAt&&x.payload.recommendation!==latest.payload.recommendation))invalid('旧面试记录时间相同且意见不同，请新增明确的面试评价');if(!latest||latest.payload.recommendation!=='advance')invalid('须有最近一次建议推进的面试评价');if(c.gradeId){if(member.role!=='admin'&&!member.viewLevel)deny('没有职级字段维护权限');if(!state.grades?.some(g=>g.id===c.gradeId&&g.status==='启用'))invalid('目标职级不存在或已停用');}record=change(r,'offered',{version:(r.payload.version??0)+1,offerInterviewId:latest.id,offerInterviewVersion:latest.payload.version,offerReturnReason:undefined,verifiedBy:undefined,verifiedAt:undefined,joined:c.joined,gradeId:c.gradeId,evidence:c.evidence,offeredBy:member.userId,offeredAt:at,approvedBy:undefined,approvedAt:undefined});break;}
 case 'approveOffer':{const r=get(c.id,'candidate');approver(r.payload.offeredBy??r.createdBy);req(r);offerTargets(r);if(r.status!=='offered')invalid('当前阶段不能审批录用');record=change(r,'approved',{approvedBy:member.userId,approvedAt:at});break;}
 case 'returnOffer':{const r=get(c.id,'candidate');approver(r.payload.offeredBy??r.createdBy);req(r);if(r.status!=='offered')invalid('仅待审批录用可退回修改');record=change(r,'screening',{offerReturnReason:c.reason,verifiedBy:member.userId,verifiedAt:at,joined:undefined,gradeId:undefined,evidence:undefined,offeredBy:undefined,offeredAt:undefined,approvedBy:undefined,approvedAt:undefined,offerInterviewId:undefined,offerInterviewVersion:undefined});break;}
 case 'acceptOffer':{hr();const r=get(c.id,'candidate');req(r);offerTargets(r);if(r.status!=='approved')invalid('须先完成录用审批');record=change(r,'accepted',{acceptanceEvidence:c.evidence,acceptanceRecordedBy:member.userId,acceptanceRecordedAt:at});break;}
 case 'rejectCandidate':{hr();const r=get(c.id,'candidate');if(['hired','rejected'].includes(r.status))invalid('候选流程已经结束');record=change(r,'rejected',{closedReason:c.reason});break;}
 case 'hire':{hr();const r=get(c.id,'candidate'),q=req(r),p=position(r.positionId!);if(r.status!=='accepted')invalid('须先登记候选人接受录用的依据');if(records.filter(x=>x.kind==='candidate'&&x.referenceId===q.id&&x.status==='hired').length>=q.payload.headcount!)invalid('招聘需求人数已满');if(r.payload.joined!>businessDate(at))invalid('尚未到计划入职日期');employeeInput={action:'employee',code:c.code,name:r.payload.name!,email:r.payload.email??'',orgId:p.orgId,positionId:p.id,gradeId:r.payload.gradeId??null,job:p.name,level:'',joined:r.payload.joined!};record=change(r,'hired',{hiredBy:member.userId,hiredAt:at});break;}
 }
 if(completedAppointment)completedAppointment.payload={...completedAppointment.payload,interviewResultId:record.id};
 return {record,employeeInput,completedAppointment};
}
