import {z} from 'zod';
import {applyAttendance} from './attendance';
import {visibleRecord,type DevelopmentRecord as R} from './development';
import {scopedOrgs,type Member} from './authorization';
import type {State} from './model';
import {HttpError} from './http';
const id=z.string().min(1).max(100),name=z.string().trim().min(1).max(100),minute=z.number().int().min(0).max(2880);
export const fixedShift=z.object({startMinute:minute.max(1439),endMinute:minute,breakStartMinute:minute.optional(),breakEndMinute:minute.optional()}).strict().superRefine((v,c)=>{const bad=(message:string)=>c.addIssue({code:'custom',message});if(v.endMinute<=v.startMinute||v.endMinute-v.startMinute>1440)bad('班次须大于0且不超过24小时');if((v.breakStartMinute===undefined)!==(v.breakEndMinute===undefined))bad('休息起止须同时填写');if(v.breakStartMinute!==undefined&&(v.breakStartMinute<v.startMinute||v.breakEndMinute!>v.endMinute||v.breakEndMinute!<=v.breakStartMinute||v.breakEndMinute!-v.breakStartMinute>=v.endMinute-v.startMinute))bad('休息须位于班次内并保留有效工作时间');});
export type FixedShift=z.infer<typeof fixedShift>;
export type ShiftDefinitionSnapshot={id:string;rootId:string;version:number;name:string;orgId:string;timeZone:'Asia/Shanghai';times:FixedShift};
const fields={name,orgId:id,times:fixedShift},date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const n=new Date(v+'T00:00:00Z');return Number.isFinite(n.getTime())&&n.toISOString().slice(0,10)===v;});
const command=z.discriminatedUnion('action',[z.object({action:z.literal('create'),...fields}).strict(),z.object({action:z.literal('edit'),id,...fields}).strict(),z.object({action:z.literal('seal'),id}).strict(),z.object({action:z.literal('revise'),id}).strict(),z.object({action:z.literal('archive'),id,reason:z.string().trim().min(5).max(1500)}).strict(),z.object({action:z.literal('assign'),id,assignments:z.array(z.object({employeeId:id,date}).strict()).min(1).max(20)}).strict()]);
export function applyShiftDefinition(records:R[],state:State,m:Member,input:unknown,at=new Date().toISOString()):R[]{
 const c=command.parse(input),fail=(message:string):never=>{throw new HttpError(400,message);},deny=():never=>{throw new HttpError(403,'没有此班次定义或员工的管理权限');};if(!['admin','hr',...(c.action==='assign'?['manager']:[])].includes(m.role))deny();
 const old=c.action==='create'?undefined:records.find(r=>r.kind==='shiftDefinition'&&r.id===c.id);if(c.action!=='create'&&(!old||!visibleRecord(old,records,state,m)))deny();
 if(c.action==='assign'){if(old!.status!=='sealed')fail('只能使用已定版班次派班');const times=fixedShift.parse(old!.payload.fixedShift),snapshot:ShiftDefinitionSnapshot={id:old!.id,rootId:old!.payload.definitionRootId!,version:old!.payload.version!,name:old!.payload.name!,orgId:old!.payload.orgId!,timeZone:'Asia/Shanghai',times},created:R[]=[];for(const a of c.assignments){const e=state.employees.find(e=>e.id===a.employeeId);if(!e||!scopedOrgs(state,m).has(e.orgId))deny();if(e!.orgId!==snapshot.orgId)fail('首批班次仅适用于定义所属组织');const stamp=(offset:number)=>new Date(Date.parse(a.date+'T00:00:00+08:00')+offset*60000).toISOString();const shift=applyAttendance([...records,...created],state,m,{action:'shift',employeeId:a.employeeId,date:a.date,name:snapshot.name,startAt:stamp(times.startMinute),endAt:stamp(times.endMinute),...(times.breakStartMinute!==undefined?{breakStart:stamp(times.breakStartMinute),breakEnd:stamp(times.breakEndMinute!)}:{})},at);created.push({...shift,payload:{...shift.payload,shiftDefinition:snapshot}});}return created;}
 if(c.action==='archive'){if(old!.status==='archived')fail('此版本已经归档');return [{...old!,status:'archived',updatedAt:at,payload:{...old!.payload,closedReason:c.reason}}];}
 if(c.action==='seal'){if(old!.status!=='draft')fail('只有草稿可定版');fixedShift.parse(old!.payload.fixedShift);if(!state.orgs.some(o=>o.id===old!.payload.orgId&&o.status==='启用'))fail('组织已停用');return [{...old!,status:'sealed',updatedAt:at}];}
 if(c.action==='revise'){const family=records.filter(r=>r.kind==='shiftDefinition'&&r.payload.definitionRootId===old!.payload.definitionRootId);if(old!.status!=='sealed'||family.some(r=>r.status==='draft'||r.status==='sealed'&&(r.payload.version??0)>(old!.payload.version??0)))fail('请从没有后续草稿的最新定版修订');return [{...old!,id:crypto.randomUUID(),referenceId:old!.id,status:'draft',createdAt:at,updatedAt:at,createdBy:m.userId,payload:{...old!.payload,version:Math.max(...family.map(r=>r.payload.version??1))+1}}];}
 if(old&&old.status!=='draft')fail('只有草稿可以编辑');if(!scopedOrgs(state,m).has(c.orgId))deny();if(!state.orgs.some(o=>o.id===c.orgId&&o.status==='启用'))fail('组织不存在或已停用');if(old&&old.payload.orgId!==c.orgId)fail('修订不能更换所属组织');const key=old?.id??crypto.randomUUID();return [{id:key,kind:'shiftDefinition',employeeId:null,positionId:null,referenceId:old?.referenceId??null,status:'draft',createdBy:old?.createdBy??m.userId,createdAt:old?.createdAt??at,updatedAt:at,payload:{name:c.name,orgId:c.orgId,fixedShift:c.times,definitionRootId:old?.payload.definitionRootId??key,version:old?.payload.version??1}}];
}
