import {z} from 'zod';
import {HttpError} from './http';
import {scopedOrgs,type Member} from './authorization';
import {visibleRecord,type DevelopmentRecord as R} from './development';
import {businessDate} from './workforce';
import type {State} from './model';
const id=z.string().min(1).max(100),text=z.string().trim().min(1).max(200),evidence=z.string().trim().min(5).max(3000),stamp=z.string().datetime({offset:true});
export const sessionCommand=z.discriminatedUnion('action',[
 z.object({action:z.literal('session'),trainingId:id,courseId:id,title:text,startAt:stamp,endAt:stamp,location:text,instructor:text,instructorCertificationId:id.optional(),mandatory:z.boolean()}),
 z.object({action:z.literal('cancelSession'),id,evidence}),z.object({action:z.literal('closeSession'),id,evidence}),
 z.object({action:z.literal('declare'),sessionId:id,evidence}),
 z.object({action:z.literal('recordAttendance'),sessionId:id,employeeId:id,present:z.boolean(),evidence}),
 z.object({action:z.literal('verifyAttendance'),id,accepted:z.boolean(),evidence}),
]);
export function applyTrainingSession(records:R[],state:State,member:Member,input:unknown,at=new Date().toISOString()):R{
 const c=sessionCommand.parse(input),scope=scopedOrgs(state,member),hr=['admin','hr'].includes(member.role),manager=hr||member.role==='manager';
 const deny=(s:string):never=>{throw new HttpError(403,s);},invalid=(s:string):never=>{throw new HttpError(400,s);};
 const get=(id:string,kind:R['kind'])=>{const r=records.find(r=>r.id===id&&r.kind===kind);if(!r||!visibleRecord(r,records,state,member))deny('记录不存在或没有访问权限');return r!;};
 const make=(kind:R['kind'],payload:R['payload'],extra:Partial<R>={}):R=>({id:crypto.randomUUID(),kind,payload,employeeId:null,positionId:null,referenceId:null,status:'active',createdBy:member.userId,createdAt:at,updatedAt:at,...extra});
 const change=(r:R,status:string,payload:R['payload']={}):R=>({...r,status,payload:{...r.payload,...payload},updatedAt:at});
 const training=(s:R)=>{const t=get(s.referenceId!,'training');if(t.status!=='active')invalid('培训项目未启动或已结束');return t;};
 const enrolled=(s:R,employeeId:string)=>{const e=records.find(r=>r.kind==='enrollment'&&r.employeeId===employeeId&&r.referenceId===s.payload.sessionCourseId&&r.payload.trainingId===s.referenceId&&r.status!=='cancelled');if(!e)invalid('员工没有此场次课程的有效培训报名');return e!;};
 switch(c.action){
 case 'session':{if(!hr)deny('仅HR或管理员可安排培训场次');const t=get(c.trainingId,'training');if(t.status!=='active'||!t.payload.courseIds?.includes(c.courseId))invalid('培训项目状态或课程不匹配');if(Date.parse(c.endAt)<=Date.parse(c.startAt)||businessDate(c.startAt)<t.payload.start!||businessDate(c.endAt)>t.payload.end!)invalid('场次时间须在项目期间内且结束晚于开始');if(c.mandatory&&records.some(r=>r.kind==='enrollment'&&r.payload.trainingId===t.id&&r.referenceId===c.courseId&&r.status==='completed'))invalid('已有完成该课程的学员，不能追加必修场次');let instructor=c.instructor;let certification:R|undefined;if(c.instructorCertificationId){certification=get(c.instructorCertificationId,'instructorCertification');const lecturer=state.employees.find(e=>e.id===certification!.employeeId);if(certification.status!=='approved'||certification.referenceId!==c.courseId||certification.payload.start!>businessDate(c.startAt)||certification.payload.end!<businessDate(c.endAt)||!lecturer||lecturer.status==='离职')invalid('讲师认证须覆盖此课程版本和整个场次期间，且员工仍在职');instructor=certification.payload.name!;}if(records.some(r=>r.kind==='trainingSession'&&r.status!=='cancelled'&&(r.payload.location?.toLowerCase()===c.location.toLowerCase()||r.payload.instructor?.toLowerCase()===instructor.toLowerCase()||!!certification&&r.payload.instructorEmployeeId===certification.employeeId)&&Date.parse(r.payload.startAt!)<Date.parse(c.endAt)&&Date.parse(r.payload.endAt!)>Date.parse(c.startAt)))invalid('同时间的场地或讲师已有其他场次安排');return make('trainingSession',{title:c.title,sessionCourseId:c.courseId,startAt:c.startAt,endAt:c.endAt,location:c.location,instructor,mandatory:c.mandatory,...(certification?{instructorCertificationId:certification.id,instructorEmployeeId:certification.employeeId!,instructorCertifiedStart:certification.payload.start,instructorCertifiedEnd:certification.payload.end}:{})},{referenceId:t.id});}
 case 'cancelSession':case 'closeSession':{if(!hr)deny('仅HR或管理员可结束场次');const r=get(c.id,'trainingSession');training(r);if(r.status!=='active')invalid('场次已经结束或取消');if(c.action==='cancelSession'){if(records.some(x=>x.kind==='trainingAttendance'&&x.referenceId===r.id&&['submitted','returned'].includes(x.status)))invalid('仍有待处理出勤，请完成独立核验后再取消场次');if(records.some(x=>x.kind==='trainingAttendance'&&x.referenceId===r.id&&x.status==='verified'&&x.payload.present))invalid('已有核验出席记录，不能取消场次');return change(r,'cancelled',{closedReason:c.evidence});}if(Date.parse(r.payload.endAt!)>Date.parse(at)||records.some(x=>x.kind==='trainingAttendance'&&x.referenceId===r.id&&['submitted','returned'].includes(x.status)))invalid('场次尚未结束或仍有待处理出勤');return change(r,'closed',{closedReason:c.evidence});}
 case 'declare':case 'recordAttendance':{const s=get(c.sessionId,'trainingSession');training(s);if(s.status!=='active'||Date.parse(s.payload.endAt!)>Date.parse(at))invalid('场次未结束或已结项，不能提交出勤记录');const employeeId=c.action==='declare'?member.employeeId:c.employeeId;if(!employeeId)deny('请先关联员工档案');if(c.action==='recordAttendance'&&(!hr||!state.employees.some(e=>e.id===employeeId&&scope.has(e.orgId))))deny('没有此员工的出勤登记权限');const e=enrolled(s,employeeId!);if(e.status==='completed')invalid('学习成果已完成核验，出勤记录不能重写');const old=records.find(r=>r.kind==='trainingAttendance'&&r.referenceId===s.id&&r.employeeId===employeeId);return make('trainingAttendance',{present:c.action==='declare'?true:c.present,evidence:c.evidence,submittedBy:member.userId,submittedAt:at},{referenceId:s.id,employeeId:employeeId!,status:'submitted',...(old?{id:old.id,createdBy:old.createdBy,createdAt:old.createdAt}:{})});}
 case 'verifyAttendance':{const r=get(c.id,'trainingAttendance'),s=get(r.referenceId!,'trainingSession');training(s);enrolled(s,r.employeeId!);if(!manager||r.employeeId===member.employeeId||r.payload.submittedBy===member.userId)deny('出勤须由其他管理者核验，不能自审或核验本人');if(r.status!=='submitted'||s.status!=='active')invalid('当前出勤或场次状态不能核验');return change(r,c.accepted?'verified':'returned',{verification:c.evidence,verifiedBy:member.userId,verifiedAt:at});}
 }
}
