'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {InterviewCriteria} from '@/lib/hris/recruitment-evaluations';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;role:string};
type Draft={id?:string;title:string;orgId:string;criteria:InterviewCriteria};
const selectClass='w-full rounded border p-2 bg-white',states:Record<string,string>={draft:'草稿',sealed:'已定版',archived:'已归档'};
const metric=():InterviewCriteria[number]=>({id:crypto.randomUUID(),dimension:'',title:'',description:'',labels:['欠缺','具备','掌握','卓越']});
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[draft,setDraft]=useState<Draft|null>(null),[candidateId,setCandidate]=useState(''),[definitionId,setDefinition]=useState(''),[scores,setScores]=useState<Record<string,number>>({}),[comments,setComments]=useState<Record<string,string>>({}),[recommendation,setRecommendation]=useState<'advance'|'reject'>('advance'),[evidence,setEvidence]=useState(''),[detailId,setDetail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[requestKey,setRequestKey]=useState(''),[appointmentId,setAppointmentId]=useState('');
 async function load(){try{const [r,h]=await Promise.all([fetch('/api/recruitment',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]);const d=await r.json() as Data&{error?:string},c=await h.json() as {state:State;error?:string};if(!r.ok||!h.ok)throw Error(d.error??c.error??'加载失败');setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{setAppointmentId(new URLSearchParams(window.location.search).get('appointmentId')??'');setRequestKey(crypto.randomUUID());void load();},[]);const manage=['admin','hr'].includes(data?.role??''),canEvaluate=['admin','hr','manager'].includes(data?.role??''),records=data?.records??[],definitions=records.filter(r=>r.kind==='interviewDefinition'),appointment=records.find(r=>r.kind==='interviewAppointment'&&r.id===appointmentId),selectedCandidateId=appointment?.referenceId??candidateId,candidate=records.find(r=>r.id===selectedCandidateId),frozen=appointment?.payload.interviewSchedule?.definition,definition=frozen?{...appointment!,id:frozen.id,payload:{title:frozen.title,interviewCriteria:frozen.criteria}}:definitions.find(r=>r.id===definitionId),detail=records.find(r=>r.id===detailId),position=core?.positions?.find(p=>p.id===candidate?.positionId),dimensions=[...new Set(definition?.payload.interviewCriteria?.map(i=>i.dimension)??[])];
 async function send(endpoint:string,command:unknown){if(!data||busy)return;setBusy(true);setError('');setNotice('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(endpoint==='/api/recruitment'&&requestKey?{'Idempotency-Key':requestKey}:{})},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error??'保存失败');setDraft(null);if(endpoint==='/api/recruitment'){setRequestKey(crypto.randomUUID());setScores({});setComments({});setEvidence('');}setNotice('记录已保存，历史证据已保留。');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function evaluate(e:FormEvent){e.preventDefault();void send('/api/recruitment',{action:'structuredInterview',candidateId:selectedCandidateId,definitionId:frozen?.id??definitionId,...(appointmentId?{appointmentId}:{}),scores,comments,recommendation,evidence});}
 function updateMetric(index:number,patch:Partial<InterviewCriteria[number]>){if(draft)setDraft({...draft,criteria:draft.criteria.map((i,n)=>n===index?{...i,...patch}:i)});}
 return <main className="main-content mx-auto max-w-7xl space-y-6"><Link className="text-link" href="/recruitment">返回招聘与入职</Link><div className="page-head"><div><h1>结构化面试评价</h1><p className="mt-2 text-sm text-slate-500">按组织评价表逐项评分，明确通过或不通过。每次评价保留当时版本；当前不计算总分。</p></div>{manage&&<Button disabled={busy} onClick={()=>setDraft({title:'',orgId:'',criteria:[metric()]})}>新建评价表</Button>}</div>{appointmentId&&data&&!appointment&&<p role="alert">排期不存在或不在当前可见范围，请返回排期列表核对。</p>}{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <section className="panel space-y-3"><h2>评价表版本</h2>{definitions.length===0&&<p>暂无可见评价表，由本组织HR建立并定版后使用。</p>}{definitions.slice().reverse().map(r=><article className="rounded border p-3" key={r.id}><b>{r.payload.title} · v{r.payload.version}</b><p>{core?.orgs.find(o=>o.id===r.payload.orgId)?.name} · {states[r.status]} · {r.payload.interviewCriteria?.length}项指标</p><div className="flex flex-wrap gap-2 mt-2"><Button variant="ghost" onClick={()=>setDetail(r.id)}>详情与历史</Button>{manage&&r.status==='draft'&&<><Button disabled={busy} variant="outline" onClick={()=>setDraft({id:r.id,title:r.payload.title!,orgId:r.payload.orgId!,criteria:structuredClone(r.payload.interviewCriteria!)})}>编辑</Button><Button disabled={busy} onClick={()=>send('/api/interview-definitions',{action:'seal',id:r.id})}>定版</Button></>}{manage&&r.status==='sealed'&&!definitions.some(x=>x.payload.definitionRootId===r.payload.definitionRootId&&(x.status==='draft'||x.status==='sealed'&&(x.payload.version??0)>(r.payload.version??0)))&&<Button variant="outline" disabled={busy} onClick={()=>send('/api/interview-definitions',{action:'revise',id:r.id})}>后续版本</Button>}{manage&&r.status!=='archived'&&<Button variant="ghost" disabled={busy} onClick={()=>send('/api/interview-definitions',{action:'archive',id:r.id})}>归档</Button>}</div></article>)}</section>
 {canEvaluate&&<form className="panel space-y-4" onSubmit={evaluate}><h2>{appointment?'完成指定排期评价':'记录一次面试评价'}</h2>{appointment&&<p>排期：{appointment.payload.interviewSchedule?.title}；由指定人员在结束后完成评价。</p>}<p className="text-sm text-slate-500">以当前账号登记评价。此处不安排面试、不发送邀约或代他人签署。</p><fieldset disabled={busy} className="space-y-4"><label className="field"><span>候选人</span><select required className={selectClass} disabled={!!appointmentId} value={selectedCandidateId} onChange={e=>{setRequestKey(crypto.randomUUID());setCandidate(e.target.value);setDefinition('');setScores({});setComments({});setEvidence('');}}><option value="">请选择候选人</option>{records.filter(r=>r.kind==='candidate'&&['screening','interviewed'].includes(r.status)&&records.some(q=>q.id===r.referenceId&&q.status==='active')).map(r=><option key={r.id} value={r.id}>{r.payload.name} · {records.find(q=>q.id===r.referenceId)?.payload.title}</option>)}</select></label><label className="field"><span>同组织定版评价表</span><select required className={selectClass} disabled={!!appointmentId} value={frozen?.id??definitionId} onChange={e=>{setDefinition(e.target.value);setScores({});setComments({});}}><option value="">请选择评价表</option>{frozen&&<option value={frozen.id}>{frozen.title} · 冻结v{frozen.version}</option>}{!frozen&&definitions.filter(r=>r.status==='sealed'&&r.payload.orgId===position?.orgId).map(r=><option key={r.id} value={r.id}>{r.payload.title} · v{r.payload.version}</option>)}</select></label><label className="field"><span>面试结论</span><select className={selectClass} value={recommendation} onChange={e=>setRecommendation(e.target.value as 'advance'|'reject')}><option value="advance">通过，建议推进</option><option value="reject">不通过，不建议推进</option></select></label>{dimensions.map(d=><section className="rounded border p-3 space-y-3" key={d}><h3>{d}</h3>{definition?.payload.interviewCriteria?.filter(i=>i.dimension===d).map(i=><label key={i.id} className="field"><span>{i.title}</span><p className="text-sm text-slate-500">{i.description}</p><select required={recommendation==='advance'} className={selectClass} value={scores[i.id]??''} onChange={e=>setScores(previous=>{const next={...previous};if(e.target.value)next[i.id]=Number(e.target.value);else delete next[i.id];return next;})}><option value="">未评分</option>{i.labels.map((l,n)=><option key={n} value={n+1}>{n+1} · {l}</option>)}</select></label>)}<label className="field"><span>{d}评语（可选）</span><textarea maxLength={1500} className={selectClass} value={comments[d]??''} onChange={e=>setComments({...comments,[d]:e.target.value})}/></label></section>)}<label className="field"><span>综合评价与结论依据</span><textarea required minLength={5} maxLength={1500} className={selectClass} rows={4} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><p className="text-sm text-slate-500">通过须完成全部指标；不通过可只填写结论依据，未评分不会补零。总分尚未配置。</p><Button disabled={!definition||!candidate||busy||!!appointmentId&&appointment?.status!=='scheduled'}>保存评价</Button></fieldset></form>}
 <section className="panel space-y-3"><h2>结构化评价记录</h2>{records.filter(r=>r.kind==='interview'&&r.payload.interviewEvaluation).slice().reverse().map(r=><article className="rounded border p-3" key={r.id}><p>{records.find(c=>c.id===r.referenceId)?.payload.name} · 第{r.payload.version}次 · {r.payload.recommendation==='advance'?'建议推进':'不建议推进'}</p><p>{r.payload.interviewEvaluation?.title} · v{r.payload.interviewEvaluation?.version}</p><Button variant="ghost" onClick={()=>setDetail(r.id)}>查看评分与依据</Button></article>)}</section>
 <Dialog open={!!draft} onOpenChange={v=>!v&&!busy&&setDraft(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>面试评价表草稿</DialogTitle><DialogDescription>配置四档逐项评价；定版后保留内容，后续修改须新建版本。</DialogDescription></DialogHeader>{draft&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void send('/api/interview-definitions',{action:draft.id?'edit':'create',...draft});}}><fieldset disabled={busy} className="space-y-4">{error&&<p role="alert">{error}</p>}<label className="field"><span>名称</span><Input required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field"><span>所属组织</span><select required disabled={!!draft.id} className={selectClass} value={draft.orgId} onChange={e=>setDraft({...draft,orgId:e.target.value})}><option value="">请选择组织</option>{core?.orgs.filter(o=>o.status==='启用').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{draft.criteria.map((i,n)=><section key={i.id} className="rounded border p-3 space-y-3"><h3>指标{n+1}</h3><label className="field"><span>维度</span><Input required maxLength={200} value={i.dimension} onChange={e=>updateMetric(n,{dimension:e.target.value})}/></label><label className="field"><span>指标名称</span><Input required maxLength={200} value={i.title} onChange={e=>updateMetric(n,{title:e.target.value})}/></label><label className="field"><span>评价说明</span><textarea maxLength={1500} className={selectClass} value={i.description} onChange={e=>updateMetric(n,{description:e.target.value})}/></label><div className="grid grid-cols-2 gap-2">{i.labels.map((l,k)=><label key={k} className="field"><span>{k+1}分标签</span><Input required maxLength={200} value={l} onChange={e=>{const labels=[...i.labels] as typeof i.labels;labels[k]=e.target.value;updateMetric(n,{labels});}}/></label>)}</div><Button type="button" variant="ghost" disabled={draft.criteria.length===1} onClick={()=>setDraft({...draft,criteria:draft.criteria.filter((_,k)=>k!==n)})}>移除此指标</Button></section>)}<Button type="button" variant="outline" disabled={draft.criteria.length>=20} onClick={()=>setDraft({...draft,criteria:[...draft.criteria,metric()]})}>添加指标</Button><div className="flex gap-2"><Button type="button" variant="outline" onClick={()=>setDraft(null)}>取消</Button><Button>保存草稿</Button></div></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail('')}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{detail?.payload.interviewEvaluation?.title??detail?.payload.title}</DialogTitle><DialogDescription>逐项四档评分，未生成总分。</DialogDescription></DialogHeader>{detail&&<div className="space-y-3">{(detail.payload.interviewCriteria??detail.payload.interviewEvaluation?.criteria??[]).map(i=><section className="rounded border p-3" key={i.id}><b>{i.dimension} · {i.title}</b><p>{i.description}</p><p>{i.labels.map((l,n)=>`${n+1} ${l}`).join(' / ')}</p>{detail.payload.interviewEvaluation&&<p>评分：{detail.payload.interviewEvaluation.scores[i.id]??'未评分'}；维度评语：{detail.payload.interviewEvaluation.comments[i.dimension]??'—'}</p>}</section>)}{detail.payload.interviewEvaluation&&<><p>结论：{detail.payload.recommendation==='advance'?'通过，建议推进':'不通过，不建议推进'}</p><p className="whitespace-pre-wrap">{detail.payload.evidence}</p></>}<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/></div>}</DialogContent></Dialog></main>;
}
