'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={records:R[];judgeEligible:string[];employees:{id:string;name:string;status:string}[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={active:'评分中',published:'已冻结',cancelled:'已取消'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[judges,setJudges]=useState<string[]>([]),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const response=await fetch('/api/instructor-trials',{cache:'no-store'}),d=await response.json() as Data&{error?:string};if(!response.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 const hr=['admin','hr'].includes(data?.role??''),records=data?.records??[],trials=records.filter(r=>r.kind==='instructorTrial'),rows=trials.filter(r=>[r.payload.name,r.payload.title,labels[r.status]].join(' ').includes(search)).reverse(),record=trials.find(r=>r.id===detail),judge=(r:R)=>!!data?.employeeId&&!!r.payload.participantIds?.includes(data.employeeId),manage=(r:R)=>hr&&r.employeeId!==data?.employeeId&&!!data?.employees.some(e=>e.id===r.employeeId),history=(r:R)=>manage(r)&&!judge(r);
 function open(action:string,r?:R){setError('');setJudges([]);const own=r?.payload.trialScores?.find(s=>s.employeeId===data?.employeeId);setForm({action,id:r?.id??'',profileId:'',title:'',criteria:'',passingScore:'',due:'',score:own?String(own.score):'',evidence:action==='score'?own?.evidence??'':''});}
 async function submit(e:FormEvent){e.preventDefault();if(!data||!form||busy)return;setBusy(true);setError('');try{const command={...form,...(form.action==='arrange'?{passingScore:Number(form.passingScore),participantIds:judges}:{}),...(form.action==='score'?{score:Number(form.score)}:{})},response=await fetch('/api/instructor-trials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await response.json() as {error?:string};if(!response.ok)throw Error(d.error);setForm(null);setNotice('试讲记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/instructor-development" className="text-link">培养任务</Link><Link href="/instructor-directory" className="text-link">内部讲师名册</Link><Link href="/instructors" className="text-link">课程讲师认证</Link><Link href="/work-inbox" className="text-link">待办工作台</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">TEACHING TRIALS</div><h1>内部讲师试讲</h1><p className="mt-2 text-sm text-slate-500">为待复核提名安排试讲，冻结评委、标准和通过分数。指定评委本人评分后，由非安排人、非评委的其他HR冻结结果。</p></div><Button variant="outline" onClick={load}>刷新</Button></div><p className="mb-5 text-sm text-slate-500">采用100分制、2至10名评委、全部评委等权平均；通过分数由HR按活动依据填写。评委只看自己的原始评分。已安排试讲的提名须以最新冻结通过的结果办理入册，取消不能绕过此门槛。</p>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}
 <div className="flex justify-between gap-4 mb-5"><Input aria-label="搜索试讲" className="max-w-md" placeholder="搜索讲师、试讲名称或状态" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{hr&&<Button onClick={()=>open('arrange')}>安排试讲</Button>}</div><div className="grid gap-4">{rows.slice((page-1)*12,page*12).map(r=><section className="panel" key={r.id}><div className="section-head"><div><h2>{r.payload.title}</h2><p className="text-sm text-slate-500">{r.payload.name} · V{r.payload.version} · {labels[r.status]} · 截止 {r.payload.due}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setDetail(r.id)}>详情</Button>{r.status==='active'&&judge(r)&&<Button size="sm" onClick={()=>open('score',r)}>本人评分</Button>}{r.status==='active'&&manage(r)&&<>{!judge(r)&&r.createdBy!==data?.userId&&<Button size="sm" onClick={()=>open('freeze',r)}>冻结结果</Button>}<Button size="sm" variant="outline" onClick={()=>open('cancel',r)}>取消试讲</Button></>}</div></div><p className="text-sm whitespace-pre-wrap">{r.payload.criteria}</p><p className="mt-3 text-sm">通过标准：{r.payload.passingScore} / 100；{r.status==='published'?`冻结平均分 ${r.payload.score} · ${r.payload.passed?'通过':'未通过'}`:history(r)?`已提交 ${r.payload.trialScores?.length??0} / ${r.payload.participantIds?.length??0}`:'尚无冻结结果'}</p></section>)}</div>{!rows.length&&<p className="panel empty">暂无可见的试讲</p>}<div className="flex justify-end items-center gap-3 mt-4"><span>{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*12>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{form?.action==='arrange'?'安排试讲':form?.action==='score'?'本人试讲评分':form?.action==='freeze'?'冻结试讲结果':'取消试讲'}</DialogTitle><DialogDescription>安排后不可更换评委或通过标准，变更需取消并重新安排。评分截止前、结果冻结前可修改本人的评分，修改过程保留。冻结后不再改分，不自动办理入册。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='arrange'&&<><label className="field"><span>待复核讲师提名</span><select required className="rounded border p-2" value={form.profileId} onChange={e=>{setForm({...form,profileId:e.target.value});setJudges([]);}}><option value="">请选择</option>{records.filter(r=>r.kind==='instructorProfile'&&r.status==='submitted'&&r.employeeId!==data?.employeeId&&!trials.some(t=>t.referenceId===r.id&&t.status==='active')).map(r=><option key={r.id} value={r.id}>{r.payload.name} · {r.payload.title} · V{r.payload.version}</option>)}</select></label><label className="field"><span>试讲名称</span><Input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field"><span>评价标准及活动依据</span><textarea required minLength={10} maxLength={3000} rows={3} value={form.criteria} onChange={e=>setForm({...form,criteria:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="field"><span>通过分数</span><Input required type="number" min={0} max={100} step={1} value={form.passingScore} onChange={e=>setForm({...form,passingScore:e.target.value})}/></label><label className="field"><span>评分截止日（北京时间）</span><Input required type="date" value={form.due} onChange={e=>setForm({...form,due:e.target.value})}/></label></div><fieldset className="rounded border p-3"><legend>指定评委（2至10名，须有登录账号）</legend><div className="max-h-40 overflow-auto space-y-2">{data?.employees.filter(e=>e.status!=='离职'&&data.judgeEligible.includes(e.id)&&e.id!==records.find(r=>r.id===form.profileId)?.employeeId).map(e=><label key={e.id} className="flex gap-2 items-center"><input type="checkbox" checked={judges.includes(e.id)} onChange={v=>setJudges(v.target.checked?[...judges,e.id]:judges.filter(id=>id!==e.id))}/>{e.name}</label>)}</div></fieldset></>}{form.action==='score'&&<label className="field"><span>本人评分（0至100整数）</span><Input required type="number" min={0} max={100} step={1} value={form.score} onChange={e=>setForm({...form,score:e.target.value})}/></label>}<label className="field"><span>安排依据 / 评分依据 / 办理意见</span><textarea required minLength={5} maxLength={2000} rows={3} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button type="submit" disabled={busy}>{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{record?.payload.title}</DialogTitle><DialogDescription>这里只显示当前权限允许的评分与办理信息。</DialogDescription></DialogHeader>{record&&<><p className="whitespace-pre-wrap">{record.payload.criteria}</p>{record.payload.trialScores?.map(s=><div className="rounded border p-3" key={s.employeeId}><p>{data?.employees.find(e=>e.id===s.employeeId)?.name??'指定评委'} · {s.score} / 100</p><p className="text-sm whitespace-pre-wrap">{s.evidence}</p></div>)}{record.payload.verification&&<p>{record.payload.verification}</p>}{record.payload.closedReason&&<p>{record.payload.closedReason}</p>}{history(record)&&<ProcessHistory id={record.id} updatedAt={record.updatedAt}/>}</>}</DialogContent></Dialog></main>;
}
