'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={draft:'草稿',published:'已发布',archived:'已停用',active:'进行中',closed:'已结项',cancelled:'已取消',pending:'待办理',submitted:'待核验',verified:'已核验',returned:'待补充'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/onboarding',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),manager=hr||data?.role==='manager',records=data?.records??[],selected=records.find(r=>r.id===detail),name=(id:string|null)=>core?.employees.find(e=>e.id===id)?.name??'—';
 function open(action:string,r?:R,extra:Record<string,string>={}){setError('');setForm({action,id:r?.id??'',employeeId:'none',templateId:r?.kind==='onboardingTemplate'?r.id:'none',evidence:'',...extra});}
 async function send(command:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('融入计划记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;send({...form,...(form.action==='template'?{items:form.items.split('\n').map(s=>s.trim()).filter(Boolean)}:{}),...(form.action==='verify'?{accepted:form.accepted==='true'}:{})});}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/self-service" className="text-link">员工自助</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">ONBOARDING</div><h1>新员工融入计划</h1><p className="mt-2 text-sm text-slate-500">员工提交办理依据，管理者逐项独立核验，全部通过后由HR结项。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}
 <section className="panel"><div className="section-head"><h2>融入计划</h2>{hr&&<Button onClick={()=>open('assign')}>指派计划</Button>}</div><Table><TableHeader><TableRow>{['员工 / 计划','截止日期','办理进度','状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{records.filter(r=>r.kind==='onboardingPlan').reverse().map(r=><TableRow key={r.id}><TableCell>{name(r.employeeId)}<p>{r.payload.title} · V{r.payload.version}</p></TableCell><TableCell>{r.payload.due}</TableCell><TableCell>{r.payload.onboardingItems?.filter(x=>x.status==='verified').length} / {r.payload.onboardingItems?.length}</TableCell><TableCell>{labels[r.status]}</TableCell><TableCell><div className="flex gap-2"><Button variant="ghost" onClick={()=>setDetail(r.id)}>办理与详情</Button>{hr&&r.status==='active'&&r.employeeId!==data?.employeeId&&<><Button variant="outline" disabled={!r.payload.onboardingItems?.every(x=>x.status==='verified')} onClick={()=>open('close',r)}>结项</Button><Button variant="ghost" onClick={()=>open('cancel',r)}>取消</Button></>}</div></TableCell></TableRow>)}</TableBody></Table>{!records.some(r=>r.kind==='onboardingPlan')&&<p className="empty">暂无可见融入计划</p>}</section>
 {hr&&<section className="panel"><div className="section-head"><h2>办理模板</h2><Button onClick={()=>open('template')}>新建模板版本</Button></div><Table><TableHeader><TableRow>{['模板 / 编码','版本 / 事项数','状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{records.filter(r=>r.kind==='onboardingTemplate').map(r=><TableRow key={r.id}><TableCell>{r.payload.title}<p>{r.payload.code}</p></TableCell><TableCell>V{r.payload.version} · {r.payload.onboardingItems?.length} 项</TableCell><TableCell>{labels[r.status]}</TableCell><TableCell><div className="flex gap-2"><Button variant="ghost" onClick={()=>setDetail(r.id)}>详情</Button>{r.status==='draft'&&<Button disabled={busy} onClick={()=>send({action:'publish',id:r.id})}>发布</Button>}{r.status==='published'&&<><Button onClick={()=>open('assign',r)}>指派</Button><Button variant="outline" onClick={()=>open('archive',r)}>停用</Button></>}</div></TableCell></TableRow>)}</TableBody></Table></section>}
 <Dialog open={!!selected&&!form} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{selected?.payload.title}</DialogTitle><DialogDescription>模板版本 V{selected?.payload.version} · {selected&&labels[selected.status]}</DialogDescription></DialogHeader>{selected&&<><p>{selected.payload.evidence??selected.payload.closedReason}</p>{selected.payload.onboardingItems?.map(x=><div key={x.id} className="border-b py-4 space-y-2"><div className="flex justify-between gap-4"><strong>{x.title}</strong><span>{labels[x.status]}</span></div>{x.evidence&&<p className="whitespace-pre-wrap">办理依据：{x.evidence}</p>}{x.verification&&<p className="whitespace-pre-wrap">核验意见：{x.verification}</p>}{selected.kind==='onboardingPlan'&&selected.status==='active'&&<div className="flex gap-2">{selected.employeeId===data?.employeeId&&['pending','returned'].includes(x.status)&&<Button onClick={()=>open('submit',selected,{itemId:x.id})}>提交依据</Button>}{manager&&selected.employeeId!==data?.employeeId&&x.status==='submitted'&&x.submittedBy!==data?.userId&&<><Button onClick={()=>open('verify',selected,{itemId:x.id,accepted:'true'})}>核验通过</Button><Button variant="outline" onClick={()=>open('verify',selected,{itemId:x.id,accepted:'false'})}>退回补充</Button></>}</div>}</div>)}{selected.payload.closedReason&&<p>结项 / 取消依据：{selected.payload.closedReason}</p>}<ProcessHistory id={selected.id} updatedAt={selected.updatedAt}/></>}</DialogContent></Dialog>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{form?.action==='template'?'新建模板版本':form?.action==='assign'?'指派融入计划':form?.action==='archive'?'停用模板':'办理融入事项'}</DialogTitle><DialogDescription>模板升级与停用不改写既有计划；计划结项或取消后锁定办理记录。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form onSubmit={submit} className="edit-form">{form.action==='template'&&<>{[['code','模板编码（同编码创建新版）'],['title','模板名称']].map(([k,l])=><label className="field" key={k}><span>{l}</span><Input required maxLength={200} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="field"><span>必办事项（每行一项，最多30项）</span><textarea required rows={6} value={form.items??''} onChange={e=>setForm({...form,items:e.target.value})}/></label></>}{form.action==='assign'&&<>{[{key:'templateId',label:'已发布模板',options:records.filter(r=>r.kind==='onboardingTemplate'&&r.status==='published').map(r=>[r.id,`${r.payload.title} · V${r.payload.version}`])},{key:'employeeId',label:'员工',options:(core?.employees??[]).filter(e=>e.status!=='离职').map(e=>[e.id,e.name])}].map(f=><label className="field" key={f.key}><span>{f.label}</span><Select value={form[f.key]} onValueChange={v=>setForm({...form,[f.key]:v})}><SelectTrigger aria-label={f.label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{f.options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>)}<label className="field"><span>截止日期</span><Input required type="date" value={form.due??''} onChange={e=>setForm({...form,due:e.target.value})}/></label></>}{!['template','archive'].includes(form.action)&&<label className="field"><span>办理依据 / 意见</span><textarea required minLength={5} maxLength={2000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label>}<Button disabled={busy} type="submit">{busy?'保存中…':'确认保存'}</Button></form>}</DialogContent></Dialog></main>;
}
