import {test} from 'node:test';
import assert from 'node:assert/strict';
import {inspectProfileEvent,integrationRetryDecision} from '../lib/hris/integration-preflight.ts';
const mapping={tenantId:'synthetic-tenant',sourceId:'synthetic-source',version:1,employees:{'EXT-1':'employee-1'},organizations:{'ORG-1':'org-1'}},event={eventId:'EVENT-1',sourceId:'synthetic-source',externalEmployeeId:'EXT-1',sequence:1,occurredAt:'2026-01-01T09:00:00+08:00',mappingVersion:1,profile:{code:'SYN-1',name:'合成对账人员',externalOrgId:'ORG-1',job:'合成岗位',email:'synthetic@example.com'}};
const inspect=(e=event,m=mapping,r=[],c=[])=>inspectProfileEvent(e,m,r,c);
test('preflight returns mapped candidate only, requires committed receipt for replay and does not mutate inputs',async()=>{const input=structuredClone(event),before=JSON.stringify([input,mapping]),ready=await inspect(input);assert.equal(ready.decision,'ready');assert.equal(ready.code,'DRY_RUN_ONLY');assert.equal(ready.candidate.employeeId,'employee-1');assert.equal(JSON.stringify([input,mapping]),before);const receipt={tenantId:mapping.tenantId,sourceId:mapping.sourceId,eventId:event.eventId,externalEmployeeId:event.externalEmployeeId,sequence:1,digest:ready.digest,committedRevision:17};const replay=await inspect({...event,occurredAt:'2026-01-01T01:00:00Z',profile:{...event.profile,name:' 合成对账人员 '}},mapping,[receipt]);assert.equal(replay.decision,'duplicate');assert.equal(replay.committedRevision,17);assert.equal((await inspect({...event,profile:{...event.profile,job:'不同内容'}},mapping,[receipt])).decision,'conflict');assert.equal((await inspect(event,mapping,[{...receipt,tenantId:'other-tenant'}])).decision,'ready');});
test('missing order, stale events, unmapped IDs and ambiguous identity never become write candidates',async()=>{assert.equal((await inspect({...event,sequence:3})).expectedSequence,1);const cursor={tenantId:mapping.tenantId,sourceId:mapping.sourceId,externalEmployeeId:event.externalEmployeeId,lastSequence:1};assert.equal((await inspect(event,mapping,[],[cursor])).decision,'stale');assert.equal((await inspect({...event,eventId:'EVENT-2',sequence:2},mapping,[],[cursor])).decision,'ready');for(const m of [{...mapping,employees:{}},{...mapping,organizations:{}},{...mapping,employees:{'EXT-1':'employee-1','EXT-2':'employee-1'}}]){const r=await inspect(event,m);assert.equal(r.decision,'mapping_required');assert.equal(r.candidate,undefined);}assert.equal((await inspect({...event,externalEmployeeId:'toString'})).code,'EMPLOYEE_MAPPING_REQUIRED');assert.equal((await inspect({...event,mappingVersion:2})).code,'MAPPING_VERSION_MISMATCH');assert.equal((await inspect(event,mapping,[],[cursor,cursor])).code,'INVALID_CURSOR_INVARIANT');});
test('contract rejects lifecycle, roles, salary and extra fields rather than silently accepting an unauthorized mutation',async()=>{for(const patch of [{status:'离职'},{role:'admin'},{salary:100},{password:'synthetic-not-a-credential'}]){const result=await inspect({...event,profile:{...event.profile,...patch}});assert.equal(result.decision,'rejected');assert.equal(result.candidate,undefined);}assert.equal((await inspect({...event,tenantId:'untrusted'})).decision,'rejected');assert.equal((await inspect({...event,sourceId:'foreign-source'})).code,'SOURCE_MISMATCH');assert.equal((await inspect({...event,sequence:0})).decision,'rejected');});
test('retry guidance bounds transient retries and does not retry authentication, business conflict or malformed requests',()=>{for(const code of [400,401,403,404,409,422,200,302])assert.equal(integrationRetryDecision(1,code).retry,false);for(const code of [undefined,408,429,500,503])assert.equal(integrationRetryDecision(1,code).retry,true);assert.equal(integrationRetryDecision(2,429,120).delaySeconds,120);assert.equal(integrationRetryDecision(2,429,99999).delaySeconds,3600);assert.equal(integrationRetryDecision(7,503).retry,false);assert.equal(integrationRetryDecision(0,503).retry,false);});
