import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,dev} from './support/foundation-scenario.mjs';
import {perf,performance,cycleInput,goals,change} from './support/performance-scenario.mjs';
const api=await import('../app/api/performance-indicators/route.ts');
const fields=f=>({orgId:f.org.id,indicator:{type:'qualitative',code:'SYN-QUALITY',title:'合成交付质量',category:'合成质量',description:'合成指标定义原文',metric:'根据合成验收记录核对全部交付'}});
const indicator=async(command,status=200)=>expect(await api.POST(request('/api/performance-indicators',{revision:(await get()).revision,command})),status);
async function fixture(){const f=await setup(),d=await indicator({action:'create',...fields(f)});await indicator({action:'seal',id:d.id});const cy=await perf(cycleInput(f.org.id));await perf({action:'startCycle',id:cy.id});return {...f,d,cy};}
test('indicator source is resolved server-side and stays frozen after archive and revision, including published result',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());act('employee');const p=await perf({action:'goals',employeeId:f.e.id,cycleId:f.cy.id,goals:goals.map((g,i)=>i?g:{...g,indicatorId:f.d.id,indicatorSource:{title:'伪造源文本',version:99}})});
 let source=(await get()).records.find(r=>r.id===p.id).payload.goals[0].indicatorSource;assert.equal(source.title,fields(f).indicator.title);assert.equal(source.version,1);
 act('owner');const v2=await indicator({action:'revise',id:f.d.id});await indicator({action:'edit',id:v2.id,...fields(f),indicator:{...fields(f).indicator,title:'合成新版指标'}});await indicator({action:'seal',id:v2.id});await indicator({action:'archive',id:f.d.id,reason:'原指标归档但保留已有目标引用'});
 act('employee');assert.ok(!(await expect(await api.GET())).records.some(r=>r.id===f.d.id));await perf({action:'goals',id:p.id,employeeId:f.e.id,cycleId:f.cy.id,goals:goals.map((g,i)=>i?g:{...g,indicatorId:f.d.id})});
 act('manager');await perf({action:'confirmGoals',id:p.id});act('employee');await perf({action:'selfReview',id:p.id,evidence:'按原指标来源完成合成成果'});act('manager');await perf({action:'evaluate',id:p.id,scores:[70,80],evidence:'按原目标快照核对合成评价'});act('owner');const result=await perf({action:'publishPerformance',id:p.id,evidence:'合成发布保留原指标来源版本'});const r=(await get()).records.find(r=>r.id===result.id);assert.equal(r.payload.performanceSnapshot.plan.goals[0].indicatorSource.id,f.d.id);assert.equal(r.payload.score,74);
});
test('indicator catalog scopes draft and sealed records, rejects new archived and foreign employee references',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const d=await indicator({action:'create',...fields(f)});act('employee');assert.equal((await expect(await api.GET())).records.length,0);act('manager');await indicator({action:'create',...fields(f)},403);act('hr');await indicator({action:'create',...fields(f),orgId:f.otherOrg.id},403);act('owner');await indicator({action:'seal',id:d.id});const foreign=await indicator({action:'create',...fields(f),orgId:f.otherOrg.id});await indicator({action:'seal',id:foreign.id});const cy=await perf(cycleInput(f.org.id));await perf({action:'startCycle',id:cy.id});act('employee');assert.ok(!(await expect(await api.GET())).records.some(r=>r.id===foreign.id));await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:[{...goals[0],weight:100,indicatorId:foreign.id}]},403);act('owner');await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:[{...goals[0],weight:100,indicatorId:foreign.id}]},400);await indicator({action:'archive',id:d.id,reason:'停用合成指标不再允许新引用'});await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:[{...goals[0],weight:100,indicatorId:d.id}]},400);
});
test('goal adjustment freezes explicit replacement source and audit failure rolls back both plan and request',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());act('employee');const p=await perf({action:'goals',employeeId:f.e.id,cycleId:f.cy.id,goals});act('manager');await perf({action:'confirmGoals',id:p.id});act('employee');const pending=await change({action:'request',planId:p.id,goals:goals.map((g,i)=>i?g:{...g,indicatorId:f.d.id}),evidence:'明确将合成指标作为新的参考来源'});act('owner');await indicator({action:'archive',id:f.d.id,reason:'待审申请已经保存原指标快照'});act('manager');const rev=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_indicator_change BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit failure'); END");await change({action:'review',id:pending.id,accepted:true,evidence:'合成审计失败必须原子回滚'},503);f.sqlite.exec('DROP TRIGGER reject_indicator_change');assert.equal((await get()).revision,rev);assert.equal((await get()).records.find(r=>r.id===p.id).payload.goals[0].indicatorSource,undefined);await change({action:'review',id:pending.id,accepted:true,evidence:'原子保存合成指标来源与计划'});assert.equal((await get()).records.find(r=>r.id===p.id).payload.goals[0].indicatorSource.id,f.d.id);
});
test('indicator codes and revisions preserve lineage, and accepted maximum goal text fits the bounded API',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());await indicator({action:'create',...fields(f),indicator:{...fields(f).indicator,code:'syn-quality'}},400);await indicator({action:'edit',id:f.d.id,...fields(f)},400);const draft=await indicator({action:'revise',id:f.d.id});await indicator({action:'archive',id:draft.id,reason:'合成修订草稿丢弃保留版本号'});const next=await indicator({action:'revise',id:f.d.id});assert.equal((await get()).records.find(r=>r.id===next.id).payload.version,3);
 act('employee');const p=await perf({action:'goals',employeeId:f.e.id,cycleId:f.cy.id,goals:Array.from({length:20},(_,i)=>({title:'合成目标'+i,metric:'文'.repeat(4000),weight:5}))});assert.equal((await get()).records.find(r=>r.id===p.id).payload.goals.length,20);
});
