import {reportFixture} from './support/r1-report-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
const {projectReport}=await import('../lib/hris/r1-report-projection.ts'),{datasetDefinition}=await import('../lib/hris/r1-report-catalog.ts'),{reportCell}=await import('../lib/hris/r1-report-values.ts');
test('P3-M32-06: 10001 synthetic versioned rows build in bounded chunks; SQL indexed pagination covers every key exactly once',async()=>{
 const f=await reportFixture(),count=10001,d=datasetDefinition('workforce');for(let n=0;n<count;n++)f.seed('person-'+String(n).padStart(5,'0'),'person','A',null,{name:'合成规模人员'+n});const producer={producerId:'M01',version:'synthetic-scale-v1',mode:'simulated',async readPage(ctx,dataset,cutoff,orgId,after,limit){const start=after?JSON.parse(after)[0]:'',source=(await ctx.db.prepare("SELECT e.id,v.payload FROM r1_m01_entities e JOIN r1_m01_versions v ON v.tenant_id=e.tenant_id AND v.entity_id=e.id WHERE e.tenant_id=? AND e.kind='person' AND e.id>? AND v.version=(SELECT max(x.version) FROM r1_m01_versions x WHERE x.tenant_id=e.tenant_id AND x.entity_id=e.id AND x.workspace_revision<=?) ORDER BY e.id LIMIT ?").bind(f.t,start,cutoff,limit+1).all()).results,rows=source.slice(0,limit).map(r=>({rowKey:JSON.stringify([r.id]),keyParts:[r.id],orgId,personId:r.id,policyKind:'person',policyKey:r.id,eventDate:null,currency:null,sourceVersion:'1',cells:Object.fromEntries(d.fields.map(field=>[field.fieldId,reportCell(field,field.fieldId==='workforce.c01'?r.id:field.fieldId==='workforce.c02'?JSON.parse(r.payload).payload.name:null)]))}));return {rows,nextCursor:source.length>limit?rows.at(-1).rowKey:null,complete:source.length<=limit,sourceManifest:{producerId:'M01',producerVersion:'synthetic-scale-v1',cutoff,scopeOrg:orgId,mode:'simulated'}};}};
 const registry={workforce:producer},send=async payload=>{const c=await f.intent(payload);return projectReport(c.ctx,c.command,registry);};await send({operation:'begin',id:'scale',datasetId:'workforce',orgId:'A'});let chunks=0;while(true){const g=f.sqlite.prepare("SELECT * FROM r1_report_generations WHERE id='scale'").get();if(g.status==='ready')break;await send({operation:'advance',id:'scale',expectedRevision:g.revision});chunks++;assert.ok(chunks<=51);}assert.equal(chunks,51);const measures=f.sqlite.prepare('SELECT max(row_count) rows,max(byte_count) bytes,sum(row_count) total FROM r1_report_chunks').get();assert.equal(measures.rows,200);assert.equal(measures.total,count);assert.ok(measures.bytes<=4*1024*1024);
 const prepare=f.db.prepare;let captured;f.db.prepare=sql=>{const statement=prepare(sql);if(sql.startsWith('SELECT r.row_key')){const all=statement.all.bind(statement);statement.all=async()=>{captured={sql,args:statement.args};return all();};}return statement;};let cursor,keys=[];do{const page=await f.read('workforce',{generation:'scale',limit:'200',...(cursor?{cursor}:{})});assert.equal(page.totalState,'unknown');keys.push(...page.rows.map(r=>r.rowKey));cursor=page.nextCursor;}while(cursor);assert.equal(keys.length,count);assert.equal(new Set(keys).size,count);assert.equal(keys[0],'["person-00000"]');assert.equal(keys.at(-1),'["person-10000"]');const plan=f.sqlite.prepare('EXPLAIN QUERY PLAN '+captured.sql).all(...captured.args).map(r=>r.detail);assert.ok(plan.some(s=>/SEARCH r USING INDEX/.test(s)));assert.ok(!plan.some(s=>/^SCAN r\b/.test(s)));console.log(JSON.stringify({proof:'synthetic 10001-row local SQLite query, not cloud load acceptance',chunks,maxRows:measures.rows,maxBytes:measures.bytes,queryPlan:plan.filter(s=>/SEARCH r |SCAN r /.test(s))}));f.db.prepare=prepare;
 const {manageReportJob,claimReportJob,advanceReportJob,downloadReportChunk}=await import('../lib/hris/r1-report-jobs.ts'),{synchronousOrQueuedExport}=await import('../lib/hris/r1-report-export.ts'),{reportContext}=await import('../lib/hris/r1-report-context.ts');f.grant('M32','workforce.export',['record','workforce.c01','workforce.c02']);const cmd=await f.intent({operation:'create',id:'scale-export',query:{dataset:'workforce',generation:'scale',columns:JSON.stringify(['workforce.c01','workforce.c02'])}},'M32.export'),queued=await synchronousOrQueuedExport(cmd.ctx,cmd.command);assert.equal(queued.queued,true);const objectBytes=new Map(),store={async put(k,b){objectBytes.set(k,new Uint8Array(b));},async get(k){return objectBytes.get(k)??null;}},lease=await claimReportJob(await reportContext(),'scale-export','synthetic-scale-worker');let exportChunks=0;while(true){const step=await advanceReportJob(await reportContext(),lease,store);exportChunks++;if(step.status==='ready'){assert.equal(step.rows,10001);break;}assert.ok(exportChunks<=51);}assert.equal(exportChunks,51);let exportedRows=0;for(let part=1;part<=51;part++){const result=await downloadReportChunk(await reportContext(),'scale-export',part,store),lines=new TextDecoder().decode(result.bytes).trim().split('\r\n');exportedRows+=lines.length-(part===1?1:0);}assert.equal(exportedRows,10001);console.log(JSON.stringify({proof:'local SQL + simulated object store export; no cloud worker',exportChunks,exportedRows,maxConcurrentLease:1}));f.sqlite.close();
});
