import {database,act,request} from './support/runtime.mjs';
import {readdirSync,readFileSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
const {memberContext}=await import('../lib/hris/context.ts'),{readPortal,portalAction}=await import('../lib/hris/r1-portal.ts'),{portalAdapters}=await import('../lib/hris/r1-portal-adapters.ts'),{portalEntries,fieldRegistry,commonStatusMap}=await import('../lib/hris/r1-portal-contract.ts'),{commitCommand}=await import('../lib/hris/r1-command.ts'),access=await import('../app/api/access/route.ts');
async function fixture(){const {sqlite,db}=database();for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));globalThis.p2env.DB=db;act('owner');assert.equal((await access.POST(request('/api/access',{action:'setup',name:'门户隔离合成'}))).status,200);const t=(await memberContext()).member.tenantId;sqlite.exec('DROP TRIGGER r1_guard_hris_memberships_update; DROP TRIGGER r1_guard_hris_memberships_insert');sqlite.prepare("UPDATE hris_memberships SET employee_id='self' WHERE user_id='owner'").run();sqlite.prepare("INSERT INTO r1_m01_entities VALUES (?,'self','person',NULL,'A','SELF',1,'active',?)").run(t,JSON.stringify({name:'当前绑定人员'}));sqlite.exec('UPDATE r1_schema_state SET features_enabled=1; CREATE TABLE portal_fixture_records(entry TEXT NOT NULL,id TEXT PRIMARY KEY,payload TEXT NOT NULL)');
 function grant(entry,action='read',scope=['A'],fields=['record',...fieldRegistry[entry]],relation='self',member='owner'){sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(t,crypto.randomUUID(),member,'M48',entry+'.'+action,relation,JSON.stringify(scope),JSON.stringify(fields),'current','2020-01-01',null);}
 const record=(id,extra={})=>({businessId:id,businessType:'synthetic.learning',subjectPersonId:'self',orgId:'A',kind:'task',initiatorId:'owner',assigneeIds:['owner'],rawStatus:'active',sourceRevision:1,sourceVersion:'v1',definitionVersion:'fixture-v1',period:null,publicationStatus:'not_applicable',approvalStatus:null,effectStatus:null,effectiveAt:null,fields:{title:'合成任务'+id,score:null},allowedActions:['submit'],reasonCode:null,href:'/learning',...extra});
 const seed=(entry,r)=>sqlite.prepare('INSERT INTO portal_fixture_records VALUES (?,?,?)').run(entry,r.businessId,JSON.stringify(r)),registry=portalAdapters(),calls=[];
 for(const entry of portalEntries)registry[entry]={producerId:'synthetic-'+entry,contractVersion:'fixture-v1',configurationState:'configured',mode:'simulated',integrationEvidenceRef:null,statusMap:commonStatusMap,async load(){return {records:sqlite.prepare('SELECT payload FROM portal_fixture_records WHERE entry=? ORDER BY id').all(entry).map(r=>JSON.parse(r.payload)),sourceManifest:{fixture:1},totalState:'known',complete:true};},async act(ctx,r,action,intent){calls.push({id:r.businessId,action,sourceVersion:r.sourceVersion});if(r.reasonCode)throw Object.assign(Error('原生产者拒绝'),{machineCode:r.reasonCode});const next={...r,sourceRevision:r.sourceRevision+1,sourceVersion:'v2',rawStatus:'completed'};return commitCommand(db,ctx.member,ctx.member.securityStamp,intent,token=>[db.prepare('UPDATE portal_fixture_records SET payload=? WHERE id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)').bind(JSON.stringify(next),r.businessId,t,token)],{businessId:r.businessId});}};
 const read=async(entry,params={})=>readPortal(await memberContext(),new URLSearchParams({entry,...params}),registry);
 const action=async(entry,id,payload={})=>{const ctx=await memberContext(),s=ctx.member.securityStamp;return portalAction(ctx,{entry,businessId:id,sourceVersion:'v1',sourceRevision:1,action:'submit',intent:{commandId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),expectedWorkspaceRevision:ctx.row.revision,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch,payload}},registry);};
 return {sqlite,db,t,record,grant,seed,registry,read,action,calls};}
test('P3-M48-01: session binding controls subject; forged subject, missing binding, duplicate binding and inactive member fail closed',async()=>{const f=await fixture();f.grant('learning');f.seed('learning',f.record('self-task'));assert.equal((await f.read('learning')).items[0].stableEmployeeId,'self');await assert.rejects(f.read('learning',{subjectPersonId:'other'}),/更换本人/);f.sqlite.exec("UPDATE hris_memberships SET employee_id=NULL WHERE user_id='owner'");const missing=await f.read('learning');assert.equal(missing.reasonCode,'binding_missing');assert.equal(missing.items.length,0);f.sqlite.exec("UPDATE hris_memberships SET employee_id='self' WHERE user_id='owner'");f.sqlite.prepare("INSERT INTO hris_memberships(user_id,tenant_id,role,employee_id,active) VALUES ('duplicate',?,'employee','self',1)").run(f.t);await assert.rejects(f.read('learning'),/绑定/);f.sqlite.exec("UPDATE hris_memberships SET active=0 WHERE user_id='owner'");await assert.rejects(memberContext(),/成员权限/);f.sqlite.close();});
test('P3-M48-02: multi-role grants preserve direct/dotted/department field tuples; no cross product or sensitive leakage',async()=>{const f=await fixture();for(const [id,org] of [['direct','A'],['dotted','B'],['department','C'],['child','C-child'],['indirect','D']]){f.seed('team',f.record(id,{businessType:'M01.person',subjectPersonId:id,orgId:org,kind:'record',fields:{name:id,email:id+'@example.test',grade:'G1',salary:999999,document:'secret',answers:'secret'},assigneeIds:[],allowedActions:[]}));f.sqlite.prepare('INSERT INTO r1_relationships VALUES (?,?,?,?,?,?,?,?)').run(f.t,id,'self',id,id==='department'||id==='child'?'department_head':id,'2020-01-01',null,'fixture-v1');}
 for(const [role,scope,fields,relation] of [['line',['A'],['record','name','email'],'direct'],['dotted',['B'],['record','name'],'dotted'],['dept',['C'],['record','name'],'department_head']]){f.sqlite.prepare('INSERT INTO r1_member_roles VALUES (?,?,?,?,?,?)').run(f.t,'owner',role,'2020-01-01',null,1);f.sqlite.prepare('INSERT INTO r1_role_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(f.t,role,role,'M48','team.read',relation,JSON.stringify(scope),JSON.stringify(fields),'current','2020-01-01',null);}
 const result=await f.read('team');assert.deepEqual(result.items.map(i=>i.businessId).sort(),['department','direct','dotted']);assert.equal(result.items.find(i=>i.businessId==='direct').fields.email,'direct@example.test');assert.equal(result.items.find(i=>i.businessId==='dotted').fieldStates.email,'forbidden');assert.ok(!JSON.stringify(result).includes('999999'));assert.ok(!JSON.stringify(result).includes('secret'));await assert.rejects(f.read('team',{subjectPersonId:'indirect'}),/不可读取/);await assert.rejects(f.read('team',{salary:'999999'}));f.sqlite.close();});
test('P3-M48-03: 25 self tasks and two delegated reviews separate with stable cursors; awaiting publication is not pending approval',async()=>{const f=await fixture();f.grant('learning');f.grant('learning','read',['B'],['record','title','score'],'direct');for(let i=0;i<25;i++)f.seed('learning',f.record('self-'+String(i).padStart(2,'0')));for(let i=0;i<2;i++){const person='other'+i;f.sqlite.prepare('INSERT INTO r1_relationships VALUES (?,?,?,?,?,?,?,?)').run(f.t,person,'self',person,'direct','2020-01-01',null,'fixture-v1');f.seed('learning',f.record('review-'+i,{subjectPersonId:person,orgId:'B',initiatorId:'other-member'}));}f.seed('learning',f.record('appeal',{kind:'request',rawStatus:'awaiting_publish',approvalStatus:'approved'}));
 const a=await f.read('learning',{partition:'self_tasks'});assert.equal(a.items.length,20);assert.equal(a.visibleTotal,25);assert.equal(a.counts.authorized_others,2);assert.equal(a.counts.self_requests,1);const b=await f.read('learning',{partition:'self_tasks',cursor:a.nextCursor});assert.equal(b.items.length,5);assert.equal(new Set([...a.items,...b.items].map(i=>i.taskKey)).size,25);const requests=await f.read('learning',{partition:'self_requests'});assert.equal(requests.statusCounts.awaiting_publish,1);assert.equal(requests.statusCounts.pending,undefined);await assert.rejects(f.read('learning',{partition:'self_tasks',cursor:crypto.randomUUID()}),/分页/);f.sqlite.close();});
test('P3-M48-04/07: seven entries keep availability and source identity; OKR never invents scoring or unknown status actions',async()=>{const f=await fixture();f.sqlite.prepare('INSERT INTO r1_relationships VALUES (?,?,?,?,?,?,?,?)').run(f.t,'team-config','self','self','direct','2020-01-01',null,'fixture-v1');for(const entry of portalEntries){f.grant(entry);f.grant(entry,'submit');f.seed(entry,f.record(entry,{businessType:'synthetic.'+entry,fields:entry==='okr'?{objectiveId:'o',keyResultId:'kr',metricName:'合成指标',unit:'项',baseline:0,target:10,current:3,direction:'increase'}:{title:'合成来源',name:'本人'}}));const r=await f.read(entry);assert.equal(r.items.length,1);assert.equal(r.realIntegration,'not_executed');assert.equal(r.mode,'simulated');assert.equal(r.items[0].sourceVersion,'v1');if(entry==='okr'){assert.equal(r.items[0].fields.current,3);assert.equal(r.items[0].fields.score,undefined);}}
 f.registry.okr.configurationState='not_configured';assert.equal((await f.read('okr')).availability,'not_configured');await assert.rejects(f.action('okr','okr'),/未开放/);f.sqlite.prepare('UPDATE portal_fixture_records SET payload=? WHERE id=?').run(JSON.stringify(f.record('learning',{rawStatus:'new_unknown_status'})),'learning');const unknown=await f.read('learning');assert.equal(unknown.items[0].displayStatus,'状态暂不可解释');assert.deepEqual(unknown.items[0].allowedActions,[]);await assert.rejects(f.action('learning','learning'),/不允许/);f.sqlite.close();});
test('P3-M48-05: producer rejection preserves original rows; unknown balances/scores are not zero, changed sources reject before dispatch',async()=>{const f=await fixture();for(const [entry,reason] of [['goals','ADJUSTMENT_PENDING'],['attendance','BALANCE_UNKNOWN'],['learning','STAGE_NOT_OPEN'],['development','TEMPLATE_RETIRED']]){f.grant(entry);f.grant(entry,'submit');const r=f.record(entry,{reasonCode:reason,fields:entry==='attendance'?{balance:null,unit:null}:entry==='learning'?{score:null,title:'未开放阶段'}:{title:'原域限制'}});f.seed(entry,r);const before=f.sqlite.prepare('SELECT payload FROM portal_fixture_records WHERE id=?').get(entry).payload;await assert.rejects(f.action(entry,entry),e=>e.machineCode===reason);assert.equal(f.sqlite.prepare('SELECT payload FROM portal_fixture_records WHERE id=?').get(entry).payload,before);const read=await f.read(entry);if(entry==='attendance')assert.equal(read.items[0].fieldStates.balance,'unknown');}
 f.sqlite.prepare('UPDATE portal_fixture_records SET payload=? WHERE id=?').run(JSON.stringify(f.record('learning',{sourceVersion:'v2',sourceRevision:2})),'learning');const before=f.calls.length;await assert.rejects(f.action('learning','learning'),/版本变化/);assert.equal(f.calls.length,before);f.sqlite.close();});
test('P3-M48-06: cache revocation aborts old requests and object URLs; late data, 503 and auth version mixing cannot revive sensitive data',async()=>{const {PortalCache}=await import('../lib/hris/r1-portal-cache.ts'),c=new PortalCache(),a=c.begin();assert.equal(c.accept(a,{secret:'private'},1),true);const old=c.begin(),revoked=[];c.addObjectUrl('blob:synthetic');c.clear(url=>revoked.push(url));assert.equal(old.controller.signal.aborted,true);assert.deepEqual(revoked,['blob:synthetic']);assert.equal(c.accept(old,{secret:'late'},1),false);assert.equal(c.data,null);const next=c.begin();assert.equal(c.accept(next,{secret:'new'},2),true);c.failed(503);assert.equal(c.data,null);const fresh=c.begin();c.accept(fresh,{secret:'v3'},3);assert.equal(c.accept(c.begin(),{secret:'stale'},2),false);assert.equal(c.data,null);});
test('P3-M48-05/07: all seven synthetic producer actions preserve IDs and versions; lost committed reply queries actor-bound original receipt',async()=>{
 const {commandReceipt}=await import('../lib/hris/r1-command.ts');const f=await fixture();for(const entry of portalEntries){f.grant(entry,'submit');f.seed(entry,f.record(entry,{businessType:'synthetic.'+entry,fields:{}}));const result=await f.action(entry,entry);assert.equal(result.status,'committed');assert.equal(result.result.businessId,entry);assert.equal(f.calls.at(-1).sourceVersion,'v1');assert.equal(JSON.parse(f.sqlite.prepare('SELECT payload FROM portal_fixture_records WHERE id=?').get(entry).payload).sourceRevision,2);}
 f.seed('learning',f.record('lost'));f.grant('learning','submit');const batch=f.db.batch;let commandId;f.db.batch=async statements=>{const result=await batch(statements);if(statements.some(s=>s.sql.includes('UPDATE portal_fixture_records'))){commandId=f.sqlite.prepare('SELECT command_id FROM r1_commands ORDER BY rowid DESC LIMIT 1').get().command_id;throw Error('synthetic response lost after COMMIT');}return result;};const before=f.calls.length;await assert.rejects(f.action('learning','lost'),/response lost/);f.db.batch=batch;const ctx=await memberContext(),receipt=await commandReceipt(f.db,ctx.member,commandId);assert.equal(receipt.status,'committed');assert.equal(JSON.parse(receipt.result).businessId,'lost');assert.equal(f.calls.length,before+1);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM r1_commands WHERE command_id=?").get(commandId).n,1);f.sqlite.close();
});
test('P3-M48-02/03: history never inherits current grants, revoked roles invalidate cursor, missing team and incomplete sources expose no global count',async()=>{
 const f=await fixture();f.grant('learning');for(let n=0;n<21;n++)f.seed('learning',f.record('h'+n));const first=await f.read('learning');assert.ok(first.nextCursor);assert.equal((await f.read('learning',{history:'true'})).items.length,0);f.sqlite.exec("UPDATE r1_permission_grants SET fields='[\"record\"]'");await assert.rejects(f.read('learning',{cursor:first.nextCursor}),/分页/);const original=f.registry.learning.load;f.registry.learning.load=async ctx=>({...await original(ctx),complete:false,totalState:'unknown'});const partial=await f.read('learning');assert.equal(partial.visibleTotal,null);assert.deepEqual(partial.counts,{});assert.deepEqual(partial.statusCounts,{});assert.equal(partial.loadedCounts.self_tasks,21);f.grant('team');f.seed('team',f.record('team',{fields:{name:'合成'}}));const missing=await f.read('team');assert.equal(missing.reasonCode,'RELATIONSHIP_NOT_CONFIGURED');assert.deepEqual(missing.items,[]);assert.equal(missing.visibleTotal,null);f.sqlite.close();
});
test('P3-M48-02/07: authorization race or stale client versions prevent producer dispatch; malformed records fail closed',async()=>{
 const f=await fixture();f.grant('learning','submit');f.seed('learning',f.record('race'));const ctx=await memberContext(),s=ctx.member.securityStamp,intent={commandId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),expectedWorkspaceRevision:ctx.row.revision-1,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch,payload:{}};await assert.rejects(portalAction(ctx,{entry:'learning',businessId:'race',sourceVersion:'v1',sourceRevision:1,action:'submit',intent},f.registry),/版本/);assert.equal(f.calls.length,0);const original=f.registry.learning.load;f.registry.learning.load=async ctx=>{const p=await original(ctx);f.sqlite.exec("DELETE FROM r1_permission_grants WHERE action='learning.submit'");return p;};await assert.rejects(f.action('learning','race'),e=>['FORBIDDEN','REVISION_CONFLICT'].includes(e.machineCode));assert.equal(f.calls.length,0);f.registry.learning.load=async()=>({records:[{businessId:'bad',fields:{salary:100}}],sourceManifest:{fixture:1},complete:true,totalState:'known'});await assert.rejects(f.read('learning'));f.sqlite.close();
});
test('P3-M48-03/06: consumer invalidation and inbox share rollback, duplicate event cannot invalidate twice; route rejects forged parameters',async()=>{
 const f=await fixture(),{invalidatePortal}=await import('../lib/hris/r1-portal-events.ts'),{makeEnvelope}=await import('../lib/hris/r1-integration.ts'),route=await import('../app/api/r1/self-service/[entry]/route.ts');f.grant('learning');for(let n=0;n<21;n++)f.seed('learning',f.record('i'+n));const first=await f.read('learning');assert.ok(first.nextCursor);f.sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(f.t,'consume','owner','BASE','integration.consume','scope','["A"]','["record"]','current','2020-01-01',null);
 const at=new Date().toISOString(),event=await makeEnvelope({tenantId:f.t,schemaVersion:1,eventId:'evt',eventType:'assignment.applied',source:'M01',internalId:'assignment',externalId:null,entityRevision:1,workspaceRevision:1,definitionVersion:'r1-v1',sourceRevision:0,sequence:1,mappingVersion:1,occurredAt:at,effectiveAt:at,correlationId:'cause',causationId:'cause',digestAlgorithm:'sha256-canonical-json-v1',payload:{personId:'self'}}),contract={source:'M01',mappingVersion:1,schemaVersion:1,mode:'internal',version:'r1-v1'};
 const consume=async()=>{const ctx=await memberContext(),s=ctx.member.securityStamp,id=crypto.randomUUID();return invalidatePortal(ctx,{commandId:id,idempotencyKey:id,action:'BASE.portal.invalidate',payload:event,expectedWorkspaceRevision:ctx.row.revision,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch},event,contract,'A');};
 f.sqlite.exec("CREATE TRIGGER portal_inbox_fault BEFORE INSERT ON r1_consumer_inbox BEGIN SELECT RAISE(ABORT,'synthetic_inbox_fault'); END");await assert.rejects(consume(),/synthetic_inbox_fault/);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_portal_invalidations').get().n,0);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_portal_cursors').get().n,1);f.sqlite.exec('DROP TRIGGER portal_inbox_fault');assert.equal((await consume()).status,'committed');assert.equal((await consume()).status,'duplicate');assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_portal_invalidations').get().n,1);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_portal_cursors').get().n,0);
 const response=await route.GET(new Request('https://example.test/api/r1/self-service/learning?employeeId=forged'),{params:Promise.resolve({entry:'learning'})});assert.equal(response.status,400);assert.equal(response.headers.get('Cache-Control'),'no-store');f.sqlite.close();
});
test('BP-I-REQ-01: real compatibility projection counts only own published payslips, tracks appeal publication and retains original M26 identity',async()=>{
 const f=await fixture(),{portalSummary}=await import('../lib/hris/r1-portal-summary.ts');f.sqlite.exec('DROP TRIGGER r1_guard_hris_employees_insert; DROP TRIGGER r1_guard_hris_development_records_insert; DROP TRIGGER r1_guard_hris_orgs_insert');f.sqlite.prepare("INSERT INTO hris_orgs(tenant_id,id,name,city,leader,status) VALUES (?,'A','合成A','','','启用')").run(f.t);
 f.sqlite.prepare("INSERT INTO hris_employees(tenant_id,id,code,name,org_id,job,level,joined,status,email) VALUES (?,'self','S','合成本人','A','','','2020-01-01','正式','')").run(f.t);
 f.sqlite.prepare("INSERT INTO hris_employees(tenant_id,id,code,name,org_id,job,level,joined,status,email) VALUES (?,'other','OTHER','合成他人','A','','','2020-01-01','正式','')").run(f.t);
 const put=(id,kind,employee,reference,status,payload={})=>f.sqlite.prepare('INSERT INTO hris_development_records(tenant_id,id,kind,employee_id,position_id,reference_id,status,payload,created_by,created_at,updated_at) VALUES (?,?,?,?,NULL,?,?,?,?,?,?)').run(f.t,id,kind,employee,reference,status,JSON.stringify(payload),'owner','2026-01-01T00:00:00.000Z','2026-01-01T00:00:00.000Z');
 put('batch','payBatch',null,null,'published',{orgId:'A'});put('draft-batch','payBatch',null,null,'approved',{orgId:'A'});for(const [id,person,batch,status] of [['own','self','batch','active'],['cancel','self','batch','cancelled'],['draft','self','draft-batch','active'],['other','other','batch','active']])put(id,'paySlip',person,batch,status,{grossCents:987654321});
 put('appeal','performanceAppeal','self',null,'approved',{period:'2026'});put('feedback','feedbackProject',null,null,'open',{orgId:'A',start:'2020-01-01',end:'2099-12-31'});put('invite','feedbackInvite','self','feedback','assigned',{subjectName:'合成受评人'});put('review-unstarted','review','self',null,'draft',{name:'初始未启动采集'});
 for(const [action,fields] of [['summary.read',['payslipCount']],['auxiliary.read',['record']]])f.sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(f.t,action,'owner','M48',action,'self','["A"]',JSON.stringify(fields),'current','2020-01-01',null);f.grant('goals');
 let head=await portalSummary(await memberContext());assert.equal(head.payslipCount,1);assert.ok(!JSON.stringify(head).includes('987654321'));assert.equal(head.supplementaryTasks.length,1);assert.equal(head.supplementaryTasks[0].businessType,'feedbackInvite');assert.equal(head.supplementaryTasks[0].producerId,'M26');assert.deepEqual(head.supplementaryTasks[0].allowedActions,[]);assert.ok(!JSON.stringify(head).includes('review-unstarted'));
 let goals=await readPortal(await memberContext(),new URLSearchParams({entry:'goals'}));assert.equal(goals.items.find(r=>r.businessId==='appeal').rawStatus,'awaiting_publish');put('correction','performance','self',null,'published',{appealId:'appeal',period:'2026'});goals=await readPortal(await memberContext(),new URLSearchParams({entry:'goals'}));assert.equal(goals.items.find(r=>r.businessId==='appeal').rawStatus,'corrected');put('reply','feedbackReply','self','invite','submitted',{});head=await portalSummary(await memberContext());assert.equal(head.supplementaryTasks.length,0);assert.equal(f.sqlite.prepare("SELECT status FROM hris_development_records WHERE id='feedback'").get().status,'open');f.sqlite.close();
});
