import './support/runtime.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
const {makeReport}=await import('../lib/hris/reports.ts'),{datasetDefinition}=await import('../lib/hris/r1-report-catalog.ts'),{legacyCells}=await import('../lib/hris/r1-report-values.ts');
// Fixed synthetic inputs and hand-computed expectations for preserved source semantics.
// This calls the actual compatibility calculator; it is NOT an R2/R3 integration test.
function fixture(){const ctx={member:{userId:'owner',tenantId:'synthetic',role:'admin',employeeId:null,active:1,orgScope:'[]',viewEmail:true,viewLevel:true},row:{revision:1},state:{employees:['p1','p2'].map(id=>({id,code:id,name:'合成'+id,orgId:'A',positionId:'position',job:'合成岗位',email:id+'@example.test',level:'G1',joined:'2020-01-01',status:'正式'})),orgs:[{id:'A',name:'合成组织',status:'启用'}],positions:[{id:'position',code:'S1',orgId:'A',name:'合成岗位',status:'启用'}],approvals:[],audit:[]},records:[]};const add=(id,kind,status,payload={},referenceId=null,employeeId='p1',positionId=null)=>{const r={id,kind,status,payload,referenceId,employeeId,positionId,createdBy:'owner',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};ctx.records.push(r);return r;};const report=(dataset,opts={})=>{const r=makeReport(ctx,{dataset,...opts});for(const row of r.rows)legacyCells(datasetDefinition(dataset),r.columns,row);return r.rows.map(row=>Object.fromEntries(r.columns.map((c,i)=>[c,row[i]])));};return {ctx,add,report};}
const cases={
 workforce(f){const r=f.report('workforce');assert.equal(r.length,2);assert.deepEqual(r.map(r=>r['工号']),['p1','p2']);},
 contractCoverage(f){for(const id of ['c1','c2'])f.add(id,'employmentContract','signed',{start:'2020-01-01',end:'2099-12-31',contractNumber:id});const r=f.report('contractCoverage');assert.equal(r.length,2);assert.deepEqual(r.map(r=>r['覆盖当日的签署记录数']),[2,0]);},
 contractOperations(f){f.add('c1','employmentContract','signed',{contractNumber:'c1',start:'2020-01-01',end:'2026-09-10'});f.add('c2','employmentContract','ended',{contractNumber:'c2',end:'2026-12-31',endedOn:'2026-09-10'});f.add('c3','employmentContract','draft',{});assert.equal(f.report('contractOperations',{from:'2026-09-10',to:'2026-09-10'}).length,2);assert.equal(f.report('contractOperations').length,3);},
 recruitmentOperations(f){f.add('q','requisition','active',{title:'合成需求',headcount:3},null,null,'position');for(const [id,status]of[['a','hired'],['b','offered'],['c','offered'],['d','accepted']])f.add(id,'candidate',status,{candidatePersonId:'same-natural-person'},'q',null);const r=f.report('recruitmentOperations')[0];assert.deepEqual([r['需求人数'],r['累计已入职'],r['剩余可入职'],r['待审录用'],r['已接受待入职']],[3,1,2,2,1]);assert.equal(new Set(f.ctx.records.filter(x=>x.kind==='candidate').map(x=>x.payload.candidatePersonId)).size,1);f.ctx.records[0].payload.headcount=undefined;assert.equal(f.report('recruitmentOperations')[0]['剩余可入职'],null);},
 attendance(f){f.add('s','shift','active',{date:'2026-09-10',name:'合成班',startAt:'2026-09-10T01:00:00Z',endAt:'2026-09-10T02:00:00Z'});const r=f.report('attendance',{from:'2026-09-10',to:'2026-09-10'});assert.equal(r.length,1);assert.equal(r[0]['计划分钟'],60);assert.equal(r[0]['未覆盖分钟'],null);assert.equal(f.report('attendance',{from:'2026-09-11'}).length,0);},
 payrollOperations(f){pay(f);const r=f.report('payrollOperations');assert.equal(r.length,1);assert.deepEqual([r[0]['有效明细数'],r[0]['明细应发（分）'],r[0]['明细净额（分）']],[1,10000,9800]);f.ctx.member.role='hr';assert.throws(()=>f.report('payrollOperations'),/薪酬/);},
 payrollReconciliation(f){pay(f);f.add('delta','payAdjustment','published',{payItems:[{category:'earning',amountCents:50}]},'slip');f.add('pending','payAdjustment','draft',{payItems:[{category:'earning',amountCents:9999}]},'slip');const r=f.report('payrollReconciliation')[0];assert.deepEqual([r['原净额（分）'],r['已发布补差数'],r['补差净额（分）'],r['对账净额（分）']],[9800,1,50,9850]);assert.equal(r['支付成功'],undefined);},
 payrollAttendanceReferences(f){pay(f);const r=f.report('payrollAttendanceReferences');assert.equal(r.length,2);assert.equal(new Set(r.map(x=>x['工资条编号'])).size,1);assert.deepEqual(r.map(x=>x['引用冻结版本']),[1,2]);assert.deepEqual(r.map(x=>x['当前冻结版本']),[null,null]);},
 performanceOperations(f){f.add('plan','performancePlan','confirmed',{version:2});f.add('a','performanceCheckin','submitted',{basePlanVersion:1},'plan');f.add('b','performanceCheckin','submitted',{basePlanVersion:2},'plan');f.add('c','performanceGoalChange','submitted',{},'plan');const r=f.report('performanceOperations');assert.equal(r.length,1);assert.deepEqual([r[0]['待审目标调整'],r[0]['待反馈记录（所有版本）'],r[0]['其中旧目标版本记录']],[1,2,1]);},
 performance(f){f.add('old','performance','published',{sourcePlanId:'plan',score:80});const next=f.add('new','performance','draft',{sourcePlanId:'plan',supersedes:'old',score:90});assert.equal(f.report('performance')[0]['分数'],80);next.status='published';assert.equal(f.report('performance').length,1);assert.equal(f.report('performance')[0]['分数'],90);},
 talentReview(f){f.add('old','review','published',{});const next=f.add('new','review','draft',{supersedes:'old',potential:3});assert.equal(f.report('talentReview')[0]['潜力档位'],null);next.status='published';assert.equal(f.report('talentReview').length,1);assert.equal(f.report('talentReview')[0]['潜力档位'],3);},
 successionCoverage(f){for(const id of ['s1','s2'])f.add(id,'succession','active',{readiness:'ready'},null,'p1','position');const r=f.report('successionCoverage');assert.equal(r.length,1);assert.deepEqual([r[0]['现任人数'],r[0]['有效后备人数'],r[0]['现在可就任']],[2,1,1]);},
 learning(f){f.add('e1','enrollment','completed',{title:'合成课程',sourceEnrollmentId:'historical',sourceVerifiedAt:'2020-01-01T00:00:00Z'});f.add('e2','enrollment','cancelled',{title:'合成课程'});const r=f.report('learning');assert.equal(r.length,2);assert.deepEqual(r.map(x=>x['状态']),['已完成','已取消']);assert.equal(r[0]['来源学习任务'],'historical');},
 learningPlanProgress(f){f.add('a','learningAssignment','active',{title:'空计划',courseIds:[]});const r=f.report('learningPlanProgress')[0];assert.deepEqual([r['已完成要求'],r['要求总数'],r['计划成绩']],[0,0,null]);},
 learningExams(f){f.add('e','learningExamTask','active',{title:'合成试卷'});let r=f.report('learningExams')[0];assert.deepEqual([r['作答次数'],r['最后得分（百分制取整）'],r['原始得分']],[0,null,null]);f.add('a1','learningExamAttempt','submitted',{},'e');f.add('a2','learningExamAttempt','submitted',{},'e');r=f.report('learningExams')[0];assert.equal(r['作答次数'],2);},
 homework(f){f.add('h','homeworkTask','submitted',{title:'合成作业',submissionId:'submission2',submissionVersion:2});const r=f.report('homework')[0];assert.deepEqual([r['提交次数'],r['当前提交ID'],r['当前评分'],r['批阅人']],[2,'submission2',null,'未留姓名快照']);},
 trainingStageProgress(f){training(f);const r=f.report('trainingStageProgress');assert.equal(r.length,1);assert.deepEqual([r[0]['课程总数'],r[0]['已核验课程数'],r[0]['该阶段已派发未完成'],r[0]['该阶段无有效项目任务']],[3,1,1,1]);},
 trainingProgress(f){training(f);f.add('empty','training','active',{name:'空项目',orgId:'A'});const r=f.report('trainingProgress');assert.deepEqual([r[0]['可见报名人数'],r[0]['有效学习任务数'],r[0]['已完成任务'],r[0]['已取消任务'],r[0]['任务完成率（%）']],[1,2,1,1,50]);assert.equal(r[1]['任务完成率（%）'],null);},
 trainingRoster(f){training(f);f.add('s1','trainingSession','active',{mandatory:true,sessionCourseId:'course1'},'t');f.add('s2','trainingSession','active',{mandatory:true,sessionCourseId:'course1'},'t');f.add('cancel','trainingSession','cancelled',{mandatory:true,sessionCourseId:'course1'},'t');f.add('a','trainingAttendance','verified',{present:true},'s1');const r=f.report('trainingRoster');assert.equal(r.length,2);assert.deepEqual([r[0]['必修场次数'],r[0]['已核验出席'],r[0]['已核验未出席'],r[0]['待核验或未登记']],[2,1,0,1]);},
 instructorSchedule(f){f.add('t','training','active',{name:'合成培训',orgId:'A'});f.add('s','trainingSession','cancelled',{title:'合成场次',instructor:'合成外部标记',startAt:'2026-09-09T16:00:00Z',endAt:'2026-09-09T17:00:00Z'},'t');const r=f.report('instructorSchedule',{from:'2026-09-10',to:'2026-09-10'});assert.equal(r.length,1);assert.deepEqual([r[0]['原排期分钟'],r[0]['有效计划分钟'],r[0]['身份关联']],[60,0,'未关联内部员工']);},
 instructorCampaignProgress(f){f.add('c','instructorCampaign','published',{title:'合成认证',orgId:'A'});f.add('a','instructorApplication','withdrawn',{},'c');f.add('b','instructorApplication','submitted',{},'c');const r=f.report('instructorCampaignProgress');assert.equal(r.length,1);assert.deepEqual([r[0]['报名记录数'],r[0]['待资格复核'],r[0]['已撤回']],[2,1,1]);assert.equal(new Set(f.ctx.records.filter(x=>x.kind==='instructorApplication').map(x=>x.employeeId)).size,1);}
};
function pay(f){f.add('batch','payBatch','published',{name:'合成批次',orgId:'A',period:'2026-09',currency:'CNY'},null,null);f.add('slip','paySlip','published',{employeeSnapshot:{code:'p1',name:'合成p1',orgName:'合成组织'},period:'2026-09',payItems:[{category:'earning',amountCents:10000},{category:'deduction',amountCents:200}],payrollAttendance:[1,2].map(v=>({id:'period'+v,start:'2026-09-01',end:'2026-09-10',version:v,plannedMinutes:60,approvedLeaveMinutes:0,uncoveredMinutes:0}))},'batch');}
function training(f){f.add('t','training','active',{name:'合成培训',orgId:'A',trainingStages:[{title:'阶段一',courseIds:['course1','course2','course3']}]});for(const [id,status,course] of [['e1','completed','course1'],['e2','active','course2'],['e3','cancelled','course3']])f.add(id,'enrollment',status,{title:course,trainingId:'t'},course);}
for(const [dataset,verify]of Object.entries(cases))test('P3-M32-01/02 source compatibility oracle (not real producer integration): '+dataset,()=>verify(fixture()));
