import {database,act,request} from './support/runtime.mjs';
import {readdirSync,readFileSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
const {memberContext}=await import('../lib/hris/context.ts');
const {makeEnvelope,receiveEvent,adapterCatalog,requireExternalResult,SimulatedAdapter,deliveryAction,verifyCallback}=await import('../lib/hris/r1-integration.ts');
const {canonical}=await import('../lib/hris/r1-command.ts');
const access=await import('../app/api/access/route.ts');
const commands=await import('../app/api/r1/commands/route.ts');
const hris=await import('../app/api/hris/route.ts');
const attachments=await import('../app/api/attachments/route.ts');
async function fixture(){const x=database();for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())x.sqlite.exec(readFileSync('drizzle/'+f,'utf8'));globalThis.p2env.DB=x.db;act('owner');assert.equal((await access.POST(request('/api/access',{action:'setup',name:'接口隔离合成'}))).status,200);return {...x,ctx:await memberContext()};}
const source={source:'M01',mappingVersion:1,schemaVersion:1,mode:'internal',version:'r1-20260910'};
const base={schemaVersion:1,eventId:'event-1',eventType:'assignment.applied',source:'M01',internalId:'assignment',externalId:null,entityRevision:1,workspaceRevision:1,definitionVersion:'v1',sourceRevision:0,sequence:1,mappingVersion:1,occurredAt:'2026-09-10T00:00:00Z',effectiveAt:'2026-09-10T00:00:00Z',correlationId:'command',causationId:'approval',digestAlgorithm:'sha256-canonical-json-v1',payload:{personId:'synthetic-person'}};
function intent(c,payload){const s=c.member.securityStamp,id=crypto.randomUUID();return {commandId:id,idempotencyKey:id,action:'inbox.consume',payload,expectedWorkspaceRevision:c.row.revision,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch};}
test('P3-INT-01: normalized envelope, durable duplicate, digest conflict and sequence gap',async()=>{
 const f=await fixture(),e=await makeEnvelope(base);let c=f.ctx;
 assert.equal((await receiveEvent(f.db,c.member,intent(c,e),e,source,()=>[])).status,'committed');
 c=await memberContext();assert.equal((await receiveEvent(f.db,c.member,intent(c,e),e,source,()=>[])).status,'duplicate');
 const changed=await makeEnvelope({...base,payload:{personId:'other'}});await assert.rejects(receiveEvent(f.db,c.member,intent(c,changed),changed,source,()=>[]),/不同内容/);
 c=await memberContext();const gap=await makeEnvelope({...base,eventId:'gap',sequence:3});assert.equal((await receiveEvent(f.db,c.member,intent(c,gap),gap,source,()=>[])).status,'gap');
 await assert.rejects(receiveEvent(f.db,c.member,intent(c,e),e,{...source,mappingVersion:2},()=>[]),/映射/);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_consumer_inbox').get().n,1);f.sqlite.close();
});
test('P3-INT-02: inbox projection and receipt roll back together under injected audit failure',async()=>{
 const f=await fixture(),e=await makeEnvelope(base),c=f.ctx;f.sqlite.exec("CREATE TRIGGER inject_integration_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'injected failure'); END");
 await assert.rejects(receiveEvent(f.db,c.member,intent(c,e),e,source,()=>[]),/injected failure/);
 assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_consumer_inbox').get().n,0);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_consumer_cursors').get().n,0);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_commands').get().n,0);f.sqlite.close();
});
test('P3-INT-03: explicitly simulated unknown delivery is queried and not blindly resent',async()=>{
 let intercepted=0;const adapter=new SimulatedAdapter(async()=>{intercepted++;return 'unknown';});
 assert.equal((await adapter.send('notification',{nodeId:'node'})).state,'unknown');assert.equal(deliveryAction('unknown',false,false),'query_receipt');
 await adapter.send('notification',{nodeId:'node'});assert.equal(intercepted,1);assert.equal(adapter.query('notification').mode,'simulated');
 await adapter.receipt('notification',{nodeId:'node'},'sent');await adapter.receipt('notification',{nodeId:'node'},'sent');await assert.rejects(adapter.receipt('notification',{nodeId:'other'},'sent'),/冲突/);
 assert.equal(deliveryAction('pending',true,false),'invalidate');assert.equal(adapter.attempts.length,1);
 const key=await crypto.subtle.importKey('raw',new Uint8Array(32).fill(7),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);const body={receiptId:'r1',state:'sent'};
 const signature=[...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(canonical(body))))].map(x=>x.toString(16).padStart(2,'0')).join('');await verifyCallback(body,signature,key);await assert.rejects(verifyCallback({...body,state:'failed'},signature,key),/签名/);
});
test('P3-INT-04: six external adapters stay unconfigured; internal signed/published does not imply external success',()=>{
 assert.equal(adapterCatalog().length,6);for(const a of adapterCatalog()){assert.equal(a.realIntegration,'not_executed');assert.throws(()=>requireExternalResult(a.id,'signed'),e=>e.machineCode==='ADAPTER_NOT_CONFIGURED');}
});
test('P3-INT-05: unknown command and forged tenant cannot choose an unregistered producer',async()=>{
 const f=await fixture(),c=f.ctx,b=intent(c,{operation:'activateFutureProducer'});
 let r=await commands.POST(request('/api/r1/commands',{...b,tenantId:'forged'}));assert.equal(r.status,400);
 r=await commands.POST(request('/api/r1/commands',b));assert.equal(r.status,400);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_commands').get().n,0);f.sqlite.close();
});
test('P3-INT-06: unknown DB commit preserves uploaded bytes; tombstone refuses download and queues cleanup',async()=>{
 const f=await fixture();let c=await memberContext();let response=await hris.POST(request('/api/hris',{revision:c.row.revision,command:{action:'org',name:'文件合成组织',parentId:'',city:'上海',leader:'',status:'启用'}}));assert.equal(response.status,200);
 c=await memberContext();const org=JSON.parse(c.row.data).orgs[0].id;response=await hris.POST(request('/api/hris',{revision:c.row.revision,command:{action:'employee',code:'FILE1',name:'文件合成员工',orgId:org,job:'测试岗位',level:'',joined:'2026-01-01',email:''}}));assert.equal(response.status,200);
 c=await memberContext();const employeeId=JSON.parse(c.row.data).employees[0].id,objects=new Map();let deletes=0;
 globalThis.p2env.BUCKET={put:async(k,b)=>objects.set(k,b),get:async k=>objects.has(k)?{body:objects.get(k)}:null,delete:async()=>{deletes++;throw Error('synthetic object service unavailable');}};
 let lost=false;globalThis.p2env.DB={prepare:q=>f.db.prepare(q),batch:async statements=>{const r=await f.db.batch(statements);if(!lost&&statements.some(s=>s.sql.includes('INSERT INTO hris_attachments'))){lost=true;throw Error('response lost after SQLite commit');}return r;}};
 const upload=new Request('https://hris.example/api/attachments?'+new URLSearchParams({employeeId,revision:String(c.row.revision),name:'synthetic.txt'}),{method:'POST',headers:{Origin:'https://hris.example','Content-Type':'text/plain'},body:'synthetic attachment'});
 response=await attachments.POST(upload);assert.equal(response.status,503);assert.equal(objects.size,1);assert.equal(deletes,0);
 const file=f.sqlite.prepare('SELECT id FROM hris_attachments').get();assert.ok(file);globalThis.p2env.DB=f.db;
 response=await attachments.GET(request('/api/attachments?id='+file.id));assert.equal(response.status,200);assert.equal(await response.text(),'synthetic attachment');
 c=await memberContext();response=await attachments.DELETE(request('/api/attachments',{id:file.id,revision:c.row.revision}));assert.equal(response.status,200);assert.equal((await response.json()).cleanupPending,true);
 assert.equal((await attachments.GET(request('/api/attachments?id='+file.id))).status,404);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_object_cleanup').get().n,1);assert.equal(objects.size,1);assert.equal(deletes,0);f.sqlite.close();
});
async function grantIntegration(f){const t=f.ctx.member.tenantId;for(const action of ['integration.deliver','integration.callback','reference.register','reference.read'])f.sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(t,action,'owner','BASE',action,'scope','["integration-org"]','["record"]','current','2020-01-01',null);return t;}
test('P3-INT-01: two consumers process once independently, quarantine gaps with owner and preserve old receipts',async()=>{
 const f=await fixture(),e=await makeEnvelope(base);for(const consumer of ['M48','M32']){const c=await memberContext();await receiveEvent(f.db,c.member,intent(c,e),e,source,()=>[],consumer);}assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_consumer_inbox').get().n,2);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_consumer_cursors').get().n,2);
 const c=await memberContext(),stale=await makeEnvelope({...base,eventId:'stale-new-id'});assert.equal((await receiveEvent(f.db,c.member,intent(c,stale),stale,source,()=>[],'M48')).status,'stale');const q=f.sqlite.prepare('SELECT * FROM r1_integration_quarantine').get();assert.equal(q.reason,'STALE_WITHOUT_RECEIPT');assert.equal(q.owner_id,'owner');assert.ok(q.next_action.includes('M48'));assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_consumer_inbox').get().n,2);f.sqlite.close();
});
test('P3-INT-03: durable delivery loss, signed duplicate callback, nonce conflict, expiry and bad signature quarantine',async()=>{
 const {prepareDelivery,dispatchDelivery}=await import('../lib/hris/r1-delivery.ts'),{acceptCallback}=await import('../lib/hris/r1-callbacks.ts');const f=await fixture();await grantIntegration(f);let c=await memberContext();const payload={sourceId:'workflow-node',sourceRevision:1,recipientId:'owner',orgId:'integration-org',payload:{eventId:'event',templateVersion:1,recipientId:'owner',channel:'simulated',secureLink:'/r1-approvals',providerRequestId:'provider-request'}},contract={namespace:'synthetic-notification',kind:'notification',mode:'simulated',version:'v1'};const r=await prepareDelivery(c,intent(c,payload),contract),id=r.result.deliveryId;let sends=0,queries=0;
 const adapter={mode:'simulated',async send(){sends++;throw Error('simulated provider accepted response lost');},async query(){queries++;return {state:'unknown',receiptId:null};}};
 assert.equal((await dispatchDelivery(memberContext,id)).state,'not_configured');assert.equal((await dispatchDelivery(memberContext,id,adapter)).state,'unknown');assert.equal((await dispatchDelivery(memberContext,id,adapter)).action,'query_receipt');assert.equal(sends,1);assert.equal(queries,1);
 const key=await crypto.subtle.importKey('raw',new Uint8Array(32).fill(19),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']),config={source:contract.namespace,orgId:'integration-org',protocol:'r1-proxy-hmac-sha256-v1',mode:'simulated',keys:new Map([['test-key',key]]),windowMs:300000,kind:'notification'};
 const body={receiptId:'receipt-1',deliveryId:id,payloadDigest:f.sqlite.prepare('SELECT payload_digest FROM r1_provider_deliveries WHERE id=?').get(id).payload_digest,state:'sent',externalState:'sent',nonce:'nonce-1',timestamp:Date.now(),keyId:'test-key'},sign=async b=>[...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(canonical(b))))].map(x=>x.toString(16).padStart(2,'0')).join(''),callback=async b=>{const c=await memberContext();return acceptCallback(c,intent(c,b),b,await sign(b),config);};
 await callback(body);assert.equal((await callback(body)).status,'duplicate');assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_external_receipts').get().n,1);await assert.rejects(callback({...body,state:'failed',externalState:'failed'}),e=>e.machineCode==='NONCE_REPLAY');await assert.rejects(callback({...body,nonce:'new-nonce',state:'failed',externalState:'failed'}),e=>e.machineCode==='RECEIPT_CONFLICT');await assert.rejects(callback({...body,nonce:'expired',timestamp:Date.now()-300001}),e=>e.machineCode==='CALLBACK_EXPIRED');c=await memberContext();await assert.rejects(acceptCallback(c,intent(c,body),body,'0'.repeat(64),config),e=>e.machineCode==='INVALID_SIGNATURE');assert.equal(f.sqlite.prepare('SELECT state FROM r1_provider_deliveries WHERE id=?').get(id).state,'sent');assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_integration_quarantine').get().n,4);assert.equal(sends,1);f.sqlite.close();
});
test('P3-INT-03: callback audit failure rolls nonce/receipt/state back together; no trusted completion survives',async()=>{
 const {acceptCallback}=await import('../lib/hris/r1-callbacks.ts'),{prepareDelivery}=await import('../lib/hris/r1-delivery.ts');const f=await fixture();await grantIntegration(f);const c=await memberContext(),payload={sourceId:'payment-fixture',sourceRevision:1,recipientId:'owner',orgId:'integration-org',payload:{payrollBatchId:'synthetic-batch',adjustmentId:null,sourceVersion:1,period:'2026-09',currency:'CNY',voucherRef:null,paymentOrderRef:null}},r=await prepareDelivery(c,intent(c,payload),{namespace:'synthetic-payment',kind:'payment',mode:'simulated',version:'v1'});
 const key=await crypto.subtle.importKey('raw',new Uint8Array(32).fill(23),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']),body={receiptId:'r',deliveryId:r.result.deliveryId,payloadDigest:f.sqlite.prepare('SELECT payload_digest FROM r1_provider_deliveries').get().payload_digest,state:'sent',externalState:'paid',nonce:'n',timestamp:Date.now(),keyId:'key'},sig=[...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(canonical(body))))].map(x=>x.toString(16).padStart(2,'0')).join('');
 f.sqlite.exec("CREATE TRIGGER synthetic_callback_audit_fault BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'callback_audit_fault'); END");const current=await memberContext();await assert.rejects(acceptCallback(current,intent(current,body),body,sig,{source:'synthetic-payment',orgId:'integration-org',protocol:'r1-proxy-hmac-sha256-v1',mode:'simulated',keys:new Map([['key',key]]),windowMs:300000,kind:'payment'}),/callback_audit_fault/);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_callback_nonces').get().n,0);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_external_receipts').get().n,0);assert.equal(f.sqlite.prepare('SELECT state FROM r1_provider_deliveries').get().state,'pending');f.sqlite.close();
});
test('P3-INT-05: equal labels retain independent stable IDs/versions; unknown statuses and revoked grants fail closed',async()=>{
 const {registerReference,readReference}=await import('../lib/hris/r1-adapter-contracts.ts');const f=await fixture();await grantIntegration(f);const contract={source:'synthetic-assessment',version:'v1',mappingVersion:1,mode:'simulated',statusMap:{published:'available',retired:'retired'}},base={source:contract.source,objectType:'assessment_template',externalId:'ext1',version:1,internalId:'int1',orgId:'integration-org',label:'同名模板',rawStatus:'published',mappingVersion:1,attributes:{}},register=async p=>{const c=await memberContext();return registerReference(c,intent(c,p),contract);};await register(base);await register({...base,externalId:'ext2',internalId:'int2'});await register({...base,version:2,label:'已改名模板'});await assert.rejects(register({...base,version:3,internalId:'int2'}),/改绑/);await assert.rejects(register({...base,version:3,rawStatus:'unregistered'}),/未登记/);const c=await memberContext(),key={source:base.source,objectType:base.objectType,externalId:base.externalId,version:1},old=await readReference(c,key,contract);assert.equal(old.label,'同名模板');assert.equal(old.internalId,'int1');assert.equal(old.fieldStates.aggregate,'not_configured');assert.equal(old.engineActivated,false);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_stable_references').get().n,3);
 f.sqlite.prepare("UPDATE r1_permission_grants SET fields='[]' WHERE action='reference.read'").run();await assert.rejects(readReference(await memberContext(),key,contract),/权限/);f.sqlite.close();
});
async function attachmentFixture(){const f=await fixture();let c=await memberContext();assert.equal((await hris.POST(request('/api/hris',{revision:c.row.revision,command:{action:'org',name:'附件隔离组织',parentId:'',city:'上海',leader:'',status:'启用'}}))).status,200);c=await memberContext();const orgId=JSON.parse(c.row.data).orgs[0].id;assert.equal((await hris.POST(request('/api/hris',{revision:c.row.revision,command:{action:'employee',code:'AT1',name:'附件合成人员',orgId,job:'合成岗位',level:'',joined:'2020-01-01',email:''}}))).status,200);c=await memberContext();const employeeId=JSON.parse(c.row.data).employees[0].id,objects=new Map();let deletes=0;const bucket={put:async(k,b)=>objects.set(k,b),get:async k=>objects.has(k)?{body:objects.get(k)}:null,delete:async()=>{deletes++;throw Error('synthetic delete unavailable');}};globalThis.p2env.BUCKET=bucket;
 const t=c.member.tenantId;for(const action of ['attachment.read','attachment.write'])f.sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(t,action,'owner','BASE',action,'scope',JSON.stringify([orgId]),'["record"]','current','2020-01-01',null);f.sqlite.exec('UPDATE r1_schema_state SET features_enabled=1');
 const header=async()=>{const c=await memberContext(),s=c.member.securityStamp;return {revision:c.row.revision,header:{commandId:crypto.randomUUID(),idempotencyKey:crypto.randomUUID(),expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch}};};const upload=h=>new Request('https://hris.example/api/attachments?'+new URLSearchParams({employeeId,revision:String(h.revision),name:'isolated.txt'}),{method:'POST',headers:{Origin:'https://hris.example','Content-Type':'text/plain',...(h.header?{'x-r1-command':JSON.stringify(h.header)}:{})},body:'isolated attachment bytes'});
 return {...f,t,orgId,employeeId,objects,bucket,header,upload,deletes:()=>deletes};}
test('P3-INT-06: put then real metadata rollback leaves inaccessible orphan; compensation failure stays pending',async()=>{
 const {developmentContext}=await import('../lib/hris/development-repository.ts'),{reconcileOrphan}=await import('../lib/hris/r1-attachment-commands.ts');const f=await attachmentFixture(),h=await f.header();f.sqlite.exec("CREATE TRIGGER synthetic_attachment_fault BEFORE INSERT ON hris_attachments BEGIN SELECT RAISE(ABORT,'metadata_rollback'); END");let r=await attachments.POST(f.upload(h));assert.equal(r.status,503);assert.equal(f.objects.size,1);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM hris_attachments').get().n,0);assert.equal((await attachments.GET(request('/api/attachments?id='+h.header.commandId))).status,404);assert.equal((await (await attachments.GET(request('/api/attachments?employeeId='+f.employeeId))).json()).items.length,0);
 f.sqlite.exec('DROP TRIGGER synthetic_attachment_fault');let c=await developmentContext(['course']),ci=intent(c,{orphanId:h.header.commandId});ci.action='BASE.attachment.reconcile';const result=await reconcileOrphan(c,h.header.commandId,ci,f.bucket);assert.equal(result.physicalDelete,'failed');assert.equal(result.cleanupPending,true);assert.equal(f.deletes(),1);assert.equal(f.objects.size,1);assert.equal(f.sqlite.prepare('SELECT state FROM r1_object_upload_intents').get().state,'frozen_orphan');assert.equal((await attachments.POST(f.upload(h))).status,409);assert.equal((await attachments.GET(request('/api/attachments?id='+h.header.commandId))).status,404);f.sqlite.close();
});
test('P3-INT-06: upgraded attachment commands replay once, old writes block before put, current field revocation denies bytes',async()=>{
 const f=await attachmentFixture(),h=await f.header();assert.equal((await attachments.POST(f.upload({revision:h.revision}))).status,409);assert.equal(f.objects.size,0);assert.equal((await attachments.POST(f.upload(h))).status,200);assert.equal((await attachments.POST(f.upload(h))).status,200);assert.equal(f.objects.size,1);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM hris_attachments').get().n,1);
 f.sqlite.prepare("UPDATE r1_permission_grants SET fields='[]' WHERE action='attachment.read'").run();assert.equal((await attachments.GET(request('/api/attachments?id='+h.header.commandId))).status,403);f.sqlite.prepare("UPDATE r1_permission_grants SET fields='[\"record\"]' WHERE action='attachment.read'").run();const del=await f.header(),deletion=()=>new Request('https://hris.example/api/attachments',{method:'DELETE',headers:{Origin:'https://hris.example','Content-Type':'application/json','x-r1-command':JSON.stringify(del.header)},body:JSON.stringify({id:h.header.commandId,revision:del.revision})});let r=await attachments.DELETE(deletion());assert.equal(r.status,200);assert.equal((await r.json()).cleanupPending,true);assert.equal((await attachments.DELETE(deletion())).status,200);assert.equal((await attachments.GET(request('/api/attachments?id='+h.header.commandId))).status,404);assert.equal(f.deletes(),0);f.sqlite.close();
});
test('P3-INT-02: grant expires after application validation; final command SQL rejects without partial changes',async()=>{
 const {authorizeTuple}=await import('../lib/hris/r1-authorization.ts'),{commitCommand}=await import('../lib/hris/r1-command.ts');const f=await fixture();await grantIntegration(f);f.sqlite.prepare("UPDATE r1_permission_grants SET valid_to=? WHERE action='integration.deliver'").run(new Date(Date.now()+100).toISOString());const c=await memberContext();await authorizeTuple(f.db,c.member,{objectType:'BASE',action:'integration.deliver',orgId:'integration-org',personId:'',field:'record',historyMode:'current'});assert.ok(c.member.permissionValidUntil<Date.now()+101);await new Promise(r=>setTimeout(r,130));await assert.rejects(commitCommand(f.db,c.member,c.member.securityStamp,intent(c,{}),()=>[]),e=>e.machineCode==='REVISION_CONFLICT');assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_commands').get().n,0);f.sqlite.close();
});
test('P3-INT-03/04: confirmed-no-effect retries obey due time and diagnostics, namespaces never collide',async()=>{
 const {prepareDelivery,dispatchDelivery}=await import('../lib/hris/r1-delivery.ts');const f=await fixture();await grantIntegration(f);const payload={sourceId:'same-event',sourceRevision:1,recipientId:'owner',orgId:'integration-org',payload:{eventId:'event',templateVersion:1,recipientId:'owner',channel:'simulated',secureLink:'/r1-approvals',providerRequestId:'p'}};const prepare=async namespace=>{const c=await memberContext();return (await prepareDelivery(c,intent(c,payload),{namespace,kind:'notification',mode:'simulated',version:'v1'})).result.deliveryId;};const a=await prepare('provider-a'),b=await prepare('provider-b');assert.notEqual(a,b);let sends=0;const adapter={mode:'simulated',async send(id){sends++;return {state:'failed',confirmedNoEffect:true,receiptId:'failure-receipt',httpStatus:429,retryAfterSeconds:120,payloadDigest:f.sqlite.prepare('SELECT payload_digest FROM r1_provider_deliveries WHERE id=?').get(id).payload_digest};},async query(){return {state:'unknown',receiptId:null};}};
 const r=await dispatchDelivery(memberContext,a,adapter);assert.equal(r.state,'failed');assert.ok(r.nextAttemptAt>Date.now()+110000);await dispatchDelivery(memberContext,a,adapter);assert.equal(sends,1);f.sqlite.prepare('UPDATE r1_provider_deliveries SET attempt=6,next_attempt_at=0 WHERE id=?').run(a);assert.equal((await dispatchDelivery(memberContext,a,adapter)).state,'dead_letter');assert.equal(sends,1);
 const denial={...adapter,async send(id){return {...await adapter.send(id),httpStatus:403};}};assert.equal((await dispatchDelivery(memberContext,b,denial)).state,'dead_letter');assert.equal(sends,2);f.sqlite.close();
});
test('P3-INT-04: HTTP preflight validates retained contracts without invoking any network sender',async()=>{
 const preflight=await import('../app/api/r1/adapters/[source]/preflight/route.ts'),f=await fixture(),t=await grantIntegration(f);f.sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(t,'preflight','owner','BASE','integration.preflight','scope','["integration-org"]','["record"]','current','2020-01-01',null);let network=0;const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{network++;throw Error('network prohibited in test');};try{const body={orgId:'integration-org',payload:{contractId:'contract',contractVersion:1,legalEntityId:'legal',templateVersion:1,signerReference:'synthetic-member-ref',externalEnvelopeId:null}},r=await preflight.POST(request('/api/r1/adapters/electronic_signing/preflight',body),{params:Promise.resolve({source:'electronic_signing'})});assert.equal(r.status,200);const b=await r.json();assert.equal(b.schemaValid,true);assert.equal(b.availability,'not_configured');assert.equal(b.businessEffect,'none');assert.equal(network,0);}finally{globalThis.fetch=oldFetch;f.sqlite.close();}
});
test('P3-INT-01: actual M01 domain outbox has canonical versioned envelopes and rolls back with its command',async()=>{
 const {verifyEnvelope}=await import('../lib/hris/r1-integration.ts'),{executeM01}=await import('../lib/hris/r1-m01.ts');const f=await fixture(),t=f.ctx.member.tenantId;f.sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(t,'catalog','owner','M01','catalog','scope','["A"]','["record"]','current','2020-01-01',null);f.sqlite.exec('UPDATE r1_schema_state SET features_enabled=1; DROP TRIGGER r1_guard_hris_orgs_insert');f.sqlite.prepare("INSERT INTO hris_orgs(tenant_id,id,name,city,leader,status) VALUES (?,'A','合成A','','','启用')").run(t);const payload={operation:'catalog',kind:'job_family',code:'JF',name:'职类',orgId:'A',parentId:'',status:'active',validFrom:(await import('../lib/hris/business-time.ts')).businessDate(),validTo:null,attributes:{}},c=await memberContext(),command={...intent(c,payload),action:'M01.catalog'};await executeM01(c,command);const rows=f.sqlite.prepare("SELECT payload FROM r1_outbox WHERE event_type='catalog.version_published'").all();assert.equal(rows.length,1);const e=JSON.parse(rows[0].payload);assert.equal((await verifyEnvelope(e,source)).digest,e.digest);assert.equal(e.tenantId,t);assert.equal(e.correlationId,command.commandId);assert.equal(e.sequence,e.entityRevision);f.sqlite.exec("CREATE TRIGGER synthetic_domain_audit_fail BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'domain_audit_failure'); END");const next=await memberContext(),p2={...payload,code:'JF2',name:'第二职类'},second={...intent(next,p2),action:'M01.catalog'};await assert.rejects(executeM01(next,second),/domain_audit_failure/);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM r1_outbox WHERE event_type='catalog.version_published'").get().n,1);f.sqlite.close();
});
