import {reportFixture} from './support/r1-report-fixture.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
const {projectReport}=await import('../lib/hris/r1-report-projection.ts'),{reportProducers}=await import('../lib/hris/r1-report-m01-producer.ts');
test('P3-M32-01/03: M01 projection keeps one row per stable person, left coverage rows and real dated contract records',async()=>{const f=await reportFixture();for(const id of ['p1','p2'])f.seed(id,'person','A',null,{name:'合成'+id});f.seed('employment','employment','A','p1',{startOn:'2020-01-01'});f.seed('legal','legal_entity','A',null,{name:'合成法人',validFrom:'2020-01-01',validTo:null});for(const id of ['c1','c2'])f.seed(id,'contract','A','p1',{number:id,start:'2020-01-01',end:'2099-12-31',legalEntityId:'legal',agreementCategory:'labor',contractType:'fixed'},'signed');
 await f.build();const workforce=await f.read();assert.equal(workforce.rows.length,2);assert.equal(new Set(workforce.rows.map(r=>r.personId)).size,2);await f.build('contractCoverage');const coverage=await f.read('contractCoverage');assert.equal(coverage.rows.length,2);assert.equal(coverage.rows.find(r=>r.personId==='p1').cells['contractCoverage.c08'].value,2);assert.equal(coverage.rows.find(r=>r.personId==='p2').cells['contractCoverage.c08'].value,0);await f.build('contractOperations');const contracts=await f.read('contractOperations',{from:'2099-12-31',to:'2099-12-31'});assert.equal(contracts.rows.length,2);await assert.rejects(f.read('workforce',{from:'2026-01-01'}),e=>e.machineCode==='TIME_MODE_INVALID');await assert.rejects(f.read('workforce',{snapshot:'invented'}),e=>e.machineCode==='SNAPSHOT_NOT_FOUND');await assert.rejects(f.read('workforce',{asAt:'2020-01-01'}));f.sqlite.close();});
test('P3-M32-03/05: snapshot retains fixed values while current person scope/field revocation strips access; source changes cannot splice pages',async()=>{const f=await reportFixture();for(let i=0;i<25;i++)f.seed('p'+String(i).padStart(2,'0'),'person','A',null,{name:'合成旧名'+i,fields:{email:'p'+i+'@example.test'}});const g=await f.build();await f.send({operation:'snapshot',id:g,snapshotId:'saved',purpose:'本轮隔离历史核验'});const first=await f.read('workforce',{generation:g,limit:'20'});assert.equal(first.rows.length,20);await f.change('p24',{payload:{name:'新姓名'}});const second=await f.read('workforce',{generation:g,limit:'20',cursor:first.nextCursor});assert.equal(second.rows.length,5);assert.equal(second.rows.find(r=>r.personId==='p24').cells['workforce.c02'].value,'合成旧名24');const historical=await f.read('workforce',{snapshot:'saved'});assert.equal(historical.rows.length,25);await f.change('p24',{orgId:'B'});const restricted=await f.read('workforce',{snapshot:'saved'});assert.equal(restricted.rows.length,24);assert.equal(restricted.total,null);f.sqlite.exec("UPDATE r1_permission_grants SET fields='[\"record\",\"workforce.c02\"]' WHERE object_type='M32' AND action='workforce.read'");await assert.rejects(f.read('workforce',{generation:g,limit:'20',cursor:first.nextCursor}),e=>e.machineCode==='CURSOR_STALE');await assert.rejects(f.read('workforce',{snapshot:'saved',columns:JSON.stringify(['workforce.c07'])}),e=>e.machineCode==='FIELD_NOT_ALLOWED');f.sqlite.close();});
test('P3-M32-03: projection resume is idempotent and source cutoff is stable across build pages; audit failure cannot publish partial ready snapshot',async()=>{const f=await reportFixture();for(let i=0;i<25;i++)f.seed('p'+String(i).padStart(2,'0'),'person','A',null,{name:'原'+i});await f.send({operation:'begin',id:'resume',datasetId:'workforce',orgId:'A'});const c=await f.intent({operation:'advance',id:'resume',expectedRevision:1});await projectReport(c.ctx,c.command,reportProducers());assert.equal((await projectReport(c.ctx,c.command,reportProducers())).replayed,true);await f.change('p24',{payload:{name:'截点之后'}});f.sqlite.exec("CREATE TRIGGER report_audit_fault BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic_report_audit_fault'); END");await assert.rejects(f.send({operation:'advance',id:'resume',expectedRevision:2}),/synthetic_report_audit_fault/);assert.equal(f.sqlite.prepare("SELECT status FROM r1_report_generations WHERE id='resume'").get().status,'building');assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_report_rows').get().n,20);f.sqlite.exec('DROP TRIGGER report_audit_fault');await f.send({operation:'advance',id:'resume',expectedRevision:2});const read=await f.read('workforce',{generation:'resume'});assert.equal(read.rows.find(r=>r.personId==='p24').cells['workforce.c02'].value,'原24');assert.throws(()=>f.sqlite.exec("UPDATE r1_report_rows SET cells='{}'"),/IMMUTABLE/);f.sqlite.close();});
test('P3-M32-07: definition publication freezes validated payload; hidden field, stale draft and audit failure publish no new version',async()=>{const f=await reportFixture(),{manageReportDefinition}=await import('../lib/hris/r1-report-definition-service.ts'),fields=['record','workforce.c01','workforce.c02'];f.grant('M32','workforce.manage',fields);const send=async payload=>{const c=await f.intent(payload,'M32.definition');return manageReportDefinition(c.ctx,c.command);},definition={datasetId:'workforce',schemaVersion:'r1-report-v1',columns:['workforce.c01','workforce.c02']};await send({operation:'save',id:'def',orgId:'A',title:'合成名册',expectedRevision:0,definition});await assert.rejects(send({operation:'save',id:'def',orgId:'A',title:'过期',expectedRevision:0,definition}),/版本/);await assert.rejects(send({operation:'save',id:'bad',orgId:'A',title:'非法字段',expectedRevision:0,definition:{...definition,columns:['workforce.c07']}}),/权限/);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM r1_report_definitions WHERE id='bad'").get().n,0);f.sqlite.exec("CREATE TRIGGER report_definition_fault BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic_definition_audit'); END");await assert.rejects(send({operation:'publish',id:'def',expectedRevision:1}),/synthetic_definition_audit/);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_report_definition_versions').get().n,0);f.sqlite.exec('DROP TRIGGER report_definition_fault');await send({operation:'publish',id:'def',expectedRevision:1});assert.throws(()=>f.sqlite.exec("UPDATE r1_report_definition_versions SET payload='{}'"),/IMMUTABLE/);await send({operation:'save',id:'def',orgId:'A',title:'合成新草稿',expectedRevision:2,definition:{...definition,columns:['workforce.c02']}});assert.equal(JSON.parse(f.sqlite.prepare('SELECT payload FROM r1_report_definition_versions').get().payload).columns.length,2);f.sqlite.close();});
test('P3-M32-03/05: direct API enforces time and unknown parameter rules without unbounded legacy context reads',async()=>{const f=await reportFixture(),route=await import('../app/api/r1/reports/route.ts');f.seed('p','person','A',null,{name:'合成'});await f.build();const prepare=f.db.prepare,sqls=[];f.db.prepare=sql=>{sqls.push(sql);return prepare(sql);};let r=await route.GET(new Request('https://example.test/api/r1/reports?dataset=workforce'));assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.ok(!sqls.some(sql=>/SELECT id,code,name,org_id|SELECT data,revision|SELECT id,kind,employee_id/.test(sql)));r=await route.GET(new Request('https://example.test/api/r1/reports?dataset=workforce&from=2026-01-01'));assert.equal(r.status,400);r=await route.GET(new Request('https://example.test/api/r1/reports?dataset=workforce&sql=DROP'));assert.equal(r.status,400);f.db.prepare=prepare;f.sqlite.close();});
test('P3-M32-05/07: summary-only grants aggregate current scope, refuse drill, count null separately and retain legal zero-denominator state',async()=>{const f=await reportFixture(),{aggregateDefinition}=await import('../lib/hris/r1-report-aggregate.ts'),{reportContext}=await import('../lib/hris/r1-report-context.ts');f.seed('p1','person','A',null,{name:'合成1'});f.seed('p2','person','A',null,{name:'合成2'});await f.build();f.grant('M32','workforce.aggregate',['record','workforce.c01','workforce.c02']);f.grant('M01','aggregate');f.sqlite.exec("DELETE FROM r1_permission_grants WHERE object_type='M32' AND action='workforce.read'");const definition={datasetId:'workforce',schemaVersion:'r1-report-v1',columns:['workforce.c01'],metrics:[{id:'people',expression:{op:'count'}},{id:'uniqueCodes',expression:{op:'countDistinct',field:'workforce.c01'}},{id:'ratio',expression:{op:'ratio',left:{op:'countDistinct',field:'workforce.c01'},right:{op:'count'},percent:true}}]};let result=await aggregateDefinition(await reportContext(),new URLSearchParams({dataset:'workforce'}),definition);assert.equal(result.groups[0].metrics.people.value,2);assert.equal(result.groups[0].metrics.ratio.value,'100');assert.equal(result.drillAllowed,false);assert.equal(result.rows,undefined);await assert.rejects(f.read(),e=>e.machineCode==='FORBIDDEN');await f.change('p2',{orgId:'B'});result=await aggregateDefinition(await reportContext(),new URLSearchParams({dataset:'workforce'}),definition);assert.equal(result.groups[0].metrics.people.value,1);result=await aggregateDefinition(await reportContext(),new URLSearchParams({dataset:'workforce'}),{...definition,filter:{op:'eq',field:'workforce.c01',value:'none'}});assert.equal(result.groups[0].metrics.people.value,0);assert.equal(result.groups[0].metrics.ratio.reasonCode,'zero_denominator');f.sqlite.close();});
test('P3-M32-05: person scope update during SQL read invalidates response before any old fields are returned',async()=>{const f=await reportFixture();f.seed('person','person','A',null,{name:'合成原范围'});await f.build();const prepare=f.db.prepare;let changed=false;f.db.prepare=sql=>{const statement=prepare(sql);if(sql.startsWith('SELECT r.row_key')){const all=statement.all.bind(statement);statement.all=async()=>{const result=await all();if(!changed){changed=true;await f.change('person',{orgId:'B'});}return result;};}return statement;};await assert.rejects(f.read(),e=>e.machineCode==='REVISION_CONFLICT');f.db.prepare=prepare;f.sqlite.close();});
test('P3-M32-03/07: sorted seek pages use unique tie-breakers; saved definition runs published version and rejects overrides',async()=>{const f=await reportFixture(),{manageReportDefinition}=await import('../lib/hris/r1-report-definition-service.ts'),{runSavedReport}=await import('../lib/hris/r1-report-run.ts'),{reportContext}=await import('../lib/hris/r1-report-context.ts');for(const [id,name] of [['a','同名'],['b','乙'],['c','同名'],['d',null],['e','甲']])f.seed(id,'person','A',null,{name});const g=await f.build(),sort=JSON.stringify([{field:'workforce.c02',direction:'desc'}]),seen=[];let cursor;do{const p=await f.read('workforce',{generation:g,sort,limit:'2',...(cursor?{cursor}:{})});seen.push(...p.rows.map(r=>r.personId));cursor=p.nextCursor;}while(cursor);assert.deepEqual(seen,['e','a','c','b','d']);f.grant('M32','workforce.manage',['record','workforce.c02']);const definition={datasetId:'workforce',schemaVersion:'r1-report-v1',columns:['workforce.c02'],sort:[{field:'workforce.c02',direction:'desc'}]};for(const payload of [{operation:'save',id:'saved-def',orgId:'A',title:'合成排序',expectedRevision:0,definition},{operation:'publish',id:'saved-def',expectedRevision:1}]){const c=await f.intent(payload,'M32.definition');await manageReportDefinition(c.ctx,c.command);}const result=await runSavedReport(await reportContext(),'saved-def',1,new URLSearchParams({generation:g}));assert.equal(result.reportDefinitionVersion,1);assert.deepEqual(result.rows.map(r=>r.personId),seen);await assert.rejects(runSavedReport(await reportContext(),'saved-def',1,new URLSearchParams({columns:'[]'})),e=>e.machineCode==='DEFINITION_OVERRIDE_FORBIDDEN');f.sqlite.close();});
test('P3-M32-01/07: fixed authorized 1:N joins deduplicate before root metrics; coverage counts people and preserves unknown coverage',async()=>{
 const f=await reportFixture(),{aggregateDefinition}=await import('../lib/hris/r1-report-aggregate.ts'),{reportContext}=await import('../lib/hris/r1-report-context.ts'),{datasetDefinition}=await import('../lib/hris/r1-report-catalog.ts');
 for(const id of ['p1','p2','p3'])f.seed(id,'person','A',null,{name:id});
 f.seed('legal','legal_entity','A',null,{name:'合成法人',validFrom:'2020-01-01',validTo:null});
 for(const id of ['c1','c2'])f.seed(id,'contract','A','p1',{number:id,start:'2020-01-01',end:'2099-12-31',legalEntityId:'legal',agreementCategory:'labor',contractType:'fixed'},'signed');
 f.seed('unknown','contract','A','p3',{number:'unknown',start:'2020-01-01'},'signed');
 const root=await f.build(),child=await f.build('contractOperations');await f.build('contractCoverage');
 for(const id of ['workforce','contractOperations','contractCoverage'])f.grant('M32',id+'.aggregate',['record',...datasetDefinition(id).fields.map(f=>f.fieldId)]);f.grant('M01','aggregate');
 for(const strategy of ['distinct_root','preaggregate']){const d={datasetId:'workforce',schemaVersion:'r1-report-v1',columns:['workforce.c01'],metrics:[{id:'people',expression:{op:'count'}}],joins:[{id:'person_contracts',strategy,generationId:child}]};const result=await aggregateDefinition(await reportContext(),new URLSearchParams({dataset:'workforce',generation:root}),d);assert.equal(result.groups[0].metrics.people.value,3);assert.equal(result.joinManifests[0].generationId,child);await assert.rejects(aggregateDefinition(await reportContext(),new URLSearchParams({dataset:'workforce',generation:root}),{...d,joins:[{id:'person_contracts',strategy}]}),e=>e.machineCode==='JOIN_GENERATION_REQUIRED');}
 const d={datasetId:'contractCoverage',schemaVersion:'r1-report-v1',columns:['contractCoverage.c01'],metrics:[{id:'covered',expression:{op:'count',where:{op:'gt',field:'contractCoverage.c08',value:0}}},{id:'ratio',expression:{op:'ratio',left:{op:'count',where:{op:'gt',field:'contractCoverage.c08',value:0}},right:{op:'count'},percent:true}}]};const result=await aggregateDefinition(await reportContext(),new URLSearchParams({dataset:'contractCoverage'}),d);assert.equal(result.groups[0].metrics.covered.value,1);assert.equal(result.groups[0].metrics.covered.missingCount,1);assert.equal(result.groups[0].metrics.ratio.reasonCode,'unknown_denominator');
 f.sqlite.exec("DELETE FROM r1_permission_grants WHERE object_type='M32' AND action='contractOperations.aggregate'");await assert.rejects(aggregateDefinition(await reportContext(),new URLSearchParams({dataset:'workforce'}),{datasetId:'workforce',schemaVersion:'r1-report-v1',columns:['workforce.c01'],metrics:[{id:'people',expression:{op:'count'}}],joins:[{id:'person_contracts',strategy:'distinct_root',generationId:child}]}),e=>e.machineCode==='FORBIDDEN');f.sqlite.close();
});
test('P3-M32-02/07: database decimal sums are exact with missing counts; money never aggregates mixed currencies',async()=>{
 const f=await reportFixture(),{aggregateDefinition}=await import('../lib/hris/r1-report-aggregate.ts'),{reportContext}=await import('../lib/hris/r1-report-context.ts'),{datasetDefinition}=await import('../lib/hris/r1-report-catalog.ts'),{reportCell}=await import('../lib/hris/r1-report-values.ts');
 for(const [dataset,field,values,currencies,expected]of [['attendance','attendance.c05',['0.1','0.2',null],[null,null,null],'0.3'],['payrollOperations','payrollOperations.c07',[100,200],['CNY','USD'],null]]){
 const d=datasetDefinition(dataset);f.grant('M32',dataset+'.read',['record',...d.fields.map(f=>f.fieldId)]);f.grant('M32',dataset+'.aggregate',['record',...d.fields.map(f=>f.fieldId)]);f.grant(d.producer,'read');f.grant(d.producer,'aggregate');const producer={producerId:d.producer,version:'synthetic-numeric-v1',mode:'simulated',async readPage(ctx,id,cutoff,orgId){return {rows:values.map((v,i)=>({rowKey:JSON.stringify(['row'+i]),keyParts:['row'+i],orgId,personId:null,policyKind:'source',policyKey:'row'+i,eventDate:dataset==='attendance'?'2026-09-10':null,currency:currencies[i],sourceVersion:'1',cells:{[field]:reportCell(d.fields.find(f=>f.fieldId===field),v)}})),nextCursor:null,complete:true,sourceManifest:{producerId:d.producer,producerVersion:'synthetic-numeric-v1',cutoff,scopeOrg:orgId,mode:'simulated'}};}};
 for(const payload of [{operation:'begin',id:dataset,datasetId:dataset,orgId:'A'},{operation:'advance',id:dataset,expectedRevision:1}]){const c=await f.intent(payload);await projectReport(c.ctx,c.command,{[dataset]:producer});}
 const definition={datasetId:dataset,schemaVersion:'r1-report-v1',columns:[field],metrics:[{id:'sum',expression:{op:'sum',field}}]},run=()=>aggregateDefinition(fctx,new URLSearchParams({dataset}),definition),fctx=await reportContext();if(expected===null)await assert.rejects(run(),e=>e.machineCode==='CURRENCY_MISMATCH');else{const r=await run();assert.deepEqual(r.groups[0].metrics.sum,{value:expected,state:'value',reasonCode:null,knownCount:2,missingCount:1});}
 }f.sqlite.close();
});
