import {database,act,request} from './support/runtime.mjs';
import {readdirSync,readFileSync} from 'node:fs';
import test from 'node:test';
import assert from 'node:assert/strict';
const {executeWorkflow}=await import('../lib/hris/r1-workflow.ts');
const {validateDefinition,resolveNode,resolveDecisions}=await import('../lib/hris/r1-workflow-model.ts');
const {memberContext}=await import('../lib/hris/context.ts');
const access=await import('../app/api/access/route.ts');
const definition=(extra={})=>({businessType:'synthetic.review',adapterVersion:'fixture-v1',entry:'review',fields:{},nodes:[{id:'review',type:'review',assignees:['a','b'],passPolicy:'all',rejectPolicy:'any_reject',next:'end'},{id:'end',type:'end'}],interventionTargets:['review'],notificationTemplateVersion:1,...extra});
async function fixture(){
 const {sqlite,db}=database();for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));
 globalThis.p2env.DB=db;act('owner');assert.equal((await access.POST(request('/api/access',{action:'setup',name:'流程隔离合成'}))).status,200);const t=(await memberContext()).member.tenantId;
 sqlite.exec('DROP TRIGGER r1_guard_hris_memberships_insert');
 for(const who of ['a','b','c','delegate'])sqlite.prepare("INSERT INTO hris_memberships(user_id,tenant_id,role,employee_id,org_scope,view_email,view_level,active) VALUES (?,?,'hr',?,'[\"A\"]',1,1,1)").run(who,t,who+'-person');
 for(const who of ['owner','a','b','c','delegate'])for(const action of ['configure','start','decide','manage.transfer','manage.intervene','manage.revoke','withdraw','remind','read'])sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(t,who+action,who,'M19',action,'scope','["A"]','["record","grade"]','current','2020-01-01',null);
 sqlite.exec('UPDATE r1_schema_state SET features_enabled=1; CREATE TABLE synthetic_workflow_source(id TEXT PRIMARY KEY,status TEXT NOT NULL,revision INTEGER NOT NULL)');
 const seed=(id='source')=>sqlite.prepare("INSERT INTO synthetic_workflow_source VALUES (?,'pending',1)").run(id);seed();
 const adapter={version:'fixture-v1',async loadBusinessSnapshot(id){const r=sqlite.prepare('SELECT * FROM synthetic_workflow_source WHERE id=?').get(id);if(!r)throw Error('source missing');return {businessType:'synthetic.review',businessId:id,applicationVersion:1,revision:r.revision,orgId:'A',personId:'subject',initiatorId:'owner',title:'合成契约测试原单',values:{},requiredFields:['record','grade'],status:r.status};},async validateStart(s){assert.equal(s.status,'pending');},async validateDecision(s){assert.equal(s.status,'pending');},async planLocalEffect(s){return {status:'applied',statements:token=>[db.prepare("UPDATE synthetic_workflow_source SET status='applied',revision=revision+1 WHERE id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(s.businessId,t,token)]};},async projectRejection(s){return token=>[db.prepare("UPDATE synthetic_workflow_source SET status='rejected',revision=revision+1 WHERE id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(s.businessId,t,token)];},async canCancel(s){return s.status==='pending';},async planLocalCancel(s){return token=>[db.prepare("UPDATE synthetic_workflow_source SET status='cancelled',revision=revision+1 WHERE id=? AND EXISTS(SELECT 1 FROM hris_workspaces WHERE owner=? AND last_mutation=?)").bind(s.businessId,t,token)];}};
 const registry={'synthetic.review':adapter};
 const intent=async(payload)=>{const ctx=await memberContext(),s=ctx.member.securityStamp,key=crypto.randomUUID();return {ctx,command:{commandId:key,idempotencyKey:key,action:'M19.'+payload.operation,payload,expectedWorkspaceRevision:ctx.row.revision,expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch}};};
 const send=async p=>{const {ctx,command}=await intent(p);return executeWorkflow(ctx,command,registry);};
 const get=id=>sqlite.prepare('SELECT * FROM r1_workflow_instances WHERE id=?').get(id);
 const target=id=>{const i=get(id),n=sqlite.prepare('SELECT * FROM r1_workflow_nodes WHERE id=?').get(i.current_node_id);return {id,expectedRevision:i.revision,generation:i.generation,nodeRevision:n.revision};};
 const start=async(id='source',d=definition())=>{await send({operation:'publish',id:'template',orgId:'A',definition:d});return (await send({operation:'start',templateId:'template',businessType:'synthetic.review',businessId:id,applicationVersion:1})).result.instanceId;};
 return {sqlite,db,t,send,intent,get,target,start,seed,adapter,registry};
}
test('P3-M19-01: graph/type validation, null/missing/multiple routes and no implicit auto pass',async()=>{
 const d=definition();assert.throws(()=>validateDefinition({...d,nodes:[{...d.nodes[0],next:'review'},d.nodes[1]]}),/环/);assert.throws(()=>validateDefinition({...d,businessType:'personnel.transfer'}),/D7/);
 const branch={id:'route',type:'branch',routes:[{when:{op:'gt',field:'amount',value:0},next:'review'},{when:{op:'lt',field:'amount',value:10},next:'review'}]},r=validateDefinition({...d,entry:'route',fields:{amount:'number'},nodes:[branch,...d.nodes]});
 assert.throws(()=>resolveNode(r,'route',{}),/缺失/);assert.throws(()=>resolveNode(r,'route',{amount:null}),/没有/);assert.throws(()=>resolveNode(r,'route',{amount:5}),/多条/);assert.equal(resolveNode(r,'route',{amount:15}).id,'review');
 const f=await fixture();await assert.rejects(f.start('source',{...d,entry:'route',nodes:[{id:'route',type:'branch',routes:[{when:{op:'isNull',field:'x'},next:'end'},{when:{op:'eq',field:'x',value:1},next:'review'}]},...d.nodes],fields:{x:'number'}}),/缺失/);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_workflow_instances').get().n,0);f.sqlite.close();
});
test('P3-M19-01: application dedup, immutable template v1 continues after v2 publication',async()=>{
 const f=await fixture(),id=await f.start();const replay=await f.send({operation:'start',templateId:'template',businessType:'synthetic.review',businessId:'source',applicationVersion:1});assert.equal(replay.result.instanceId,id);
 const v2=definition();v2.nodes[0].assignees=['c'];await f.send({operation:'publish',id:'template',orgId:'A',definition:v2});assert.equal(JSON.parse(f.get(id).template_payload).templateVersion,1);
 act('a');await f.send({operation:'decide',...f.target(id),decision:'approved',reason:'合成'});assert.equal(f.get(id).approval_status,'pending');act('b');await f.send({operation:'decide',...f.target(id),decision:'approved',reason:'合成'});assert.equal(f.get(id).effect_status,'applied');assert.throws(()=>f.sqlite.exec("UPDATE r1_workflow_templates SET digest='changed'"),/IMMUTABLE/);f.sqlite.close();
});
test('P3-M19-02: all/any and reject policies are explicit and order-independent for same collected votes',async()=>{
 const n=definition().nodes[0],votes=[{actorId:'a',decision:'approved'},{actorId:'b',decision:'rejected'}];for(const passPolicy of ['all','any'])for(const ordered of [votes,[...votes].reverse()]){assert.equal(resolveDecisions({...n,passPolicy},ordered),'rejected');assert.equal(resolveDecisions({...n,passPolicy,rejectPolicy:'block_for_review'},ordered),'blocked');}
 const f=await fixture(),id=await f.start();act('a');const first=await f.intent({operation:'decide',...f.target(id),decision:'approved',reason:'合成'});act('b');const competing=await f.intent({operation:'decide',...f.target(id),decision:'rejected',reason:'合成'});await executeWorkflow(first.ctx,first.command,f.registry);await assert.rejects(executeWorkflow(competing.ctx,competing.command,f.registry),/版本/);await f.send({operation:'decide',...f.target(id),decision:'rejected',reason:'刷新后拒绝'});assert.equal(f.get(id).approval_status,'rejected');assert.equal(f.sqlite.prepare('SELECT status FROM synthetic_workflow_source').get().status,'rejected');f.sqlite.close();
});
test('P3-M19-03: transfer and intervention invalidate old node tokens, preserve actual decisions',async()=>{
 const f=await fixture(),id=await f.start();act('a');await f.send({operation:'decide',...f.target(id),decision:'approved',reason:'原审核'});act('owner');const old=f.target(id);await f.send({operation:'transferNode',...old,assignees:['c'],reason:'合成转交'});act('b');await assert.rejects(f.send({operation:'decide',...old,decision:'approved',reason:'旧链接'}),/版本/);act('owner');const {nodeRevision,...target}=f.target(id);await f.send({operation:'intervene',...target,targetNode:'review',reason:'退回许可节点'});assert.equal(f.get(id).generation,2);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_workflow_decisions').get().n,1);assert.equal(f.sqlite.prepare("SELECT count(*) n FROM r1_workflow_nodes WHERE status='skipped_by_intervention'").get().n,1);assert.ok(f.sqlite.prepare("SELECT count(*) n FROM r1_workflow_notifications WHERE status='invalidated'").get().n>=2);f.sqlite.close();
});
test('P3-M19-04: domain cancellation SQL failure rolls back workflow/audit/receipt, success cancels both',async()=>{
 const f=await fixture(),id=await f.start(),before=f.sqlite.prepare('SELECT count(*) n FROM r1_commands').get().n;const {nodeRevision,...target}=f.target(id);
 f.sqlite.exec("CREATE TRIGGER synthetic_cancel_fail BEFORE UPDATE ON synthetic_workflow_source BEGIN SELECT RAISE(ABORT,'cancel_fault'); END");await assert.rejects(f.send({operation:'revokeFlow',...target,reason:'合成撤销'}),/cancel_fault/);assert.equal(f.get(id).approval_status,'pending');assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_commands').get().n,before);
 f.sqlite.exec('DROP TRIGGER synthetic_cancel_fail');await f.send({operation:'revokeFlow',...target,reason:'复验'});assert.equal(f.get(id).approval_status,'cancelled');assert.equal(f.sqlite.prepare('SELECT status FROM synthetic_workflow_source').get().status,'cancelled');f.sqlite.close();
});
test('P3-M19-06: delegation acceptance, intersection, no approval/proxy, revocation and commit-time expiry',async()=>{
 const f=await fixture(),id=await f.start(),base={operation:'createDelegation',delegateId:'delegate',actions:['manage.transfer'],businessTypes:['synthetic.review'],scope:['A'],fields:['record','grade'],startAt:Date.now()-1000,endAt:Date.now()+100000};
 await assert.rejects(f.send({...base,delegateId:'owner'}),/自委托/);const r=await f.send(base),delegationId=r.result.delegationId;await assert.rejects(f.send(base),/重叠/);act('delegate');await assert.rejects(f.send({operation:'transferNode',...f.target(id),assignees:['c'],reason:'未接受',delegationId}),/无效/);
 await f.send({operation:'acceptDelegation',id:delegationId,expectedRevision:1,reason:'接受'});await assert.rejects(f.send({operation:'decide',...f.target(id),decision:'approved',reason:'委托不授审批',delegationId}),/不授予/);
 f.sqlite.prepare("UPDATE r1_permission_grants SET fields='[\"record\"]' WHERE member_id='owner' AND action='manage.transfer'").run();await assert.rejects(f.send({operation:'transferNode',...f.target(id),assignees:['c'],reason:'原管理人少字段',delegationId}),/权限/);
 f.sqlite.prepare("UPDATE r1_permission_grants SET fields='[\"record\",\"grade\"]' WHERE member_id='owner' AND action='manage.transfer'").run();
 f.sqlite.prepare('UPDATE r1_admin_delegations SET end_at=? WHERE id=?').run(Date.now()+120,delegationId);const attempt=await f.intent({operation:'transferNode',...f.target(id),assignees:['c'],reason:'提交时过期',delegationId}),batch=f.db.batch;
 f.db.batch=async statements=>{if(statements.some(s=>s.sql.includes('INSERT INTO r1_workflow_commit_guard')))await new Promise(r=>setTimeout(r,160));return batch(statements);};await assert.rejects(executeWorkflow(attempt.ctx,attempt.command,f.registry),/提交时已过期/);f.db.batch=batch;assert.equal(f.get(id).revision,1);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_workflow_commit_guard').get().n,0);f.sqlite.close();
});
test('P3-M19-05: three independent items, stale/denied results fixed, lost response queries atomic receipt',async()=>{
 const {executeWorkflowBatch}=await import('../lib/hris/r1-workflow-batch.ts');const f=await fixture(),ids=[];for(const name of ['source','two','three']){if(name!=='source')f.seed(name);ids.push(await f.start(name));}
 // Keep owner configuration rights; revoke reviewer access to the third synthetic source's org.
 f.sqlite.prepare("UPDATE r1_workflow_instances SET org_id='B' WHERE id=?").run(ids[2]);act('a');const ctx=await memberContext(),s=ctx.member.securityStamp,input={batchId:crypto.randomUUID(),expectedAuthorizationRevision:s.authorizationRevision,expectedWriterEpoch:s.writerEpoch,expectedRecoveryEpoch:s.recoveryEpoch,items:ids.map((id,k)=>({itemId:String(k),commandId:crypto.randomUUID(),payload:{operation:'decide',...f.target(id),expectedRevision:k===1?99:f.get(id).revision,decision:'approved',reason:'批量合成'}}))};
 const batch=f.db.batch;let lost=false;f.db.batch=async statements=>{const result=await batch(statements);if(!lost&&statements.some(s=>s.sql.includes('INSERT INTO r1_workflow_decisions'))){lost=true;throw Error('response lost after actual SQLite COMMIT');}return result;};const a=await executeWorkflowBatch(memberContext,input,f.registry);f.db.batch=batch;assert.deepEqual(a.items.map(i=>i.status),['committed','rejected','rejected']);assert.equal(a.items[0].recovered,true);assert.equal(a.items[2].machineCode,'NOT_ACTIONABLE');const b=await executeWorkflowBatch(memberContext,input,f.registry);assert.ok(b.items.every(i=>i.replayed));assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_workflow_decisions').get().n,1);await assert.rejects(executeWorkflowBatch(memberContext,{...input,items:input.items.slice(1)},f.registry),/内容冲突/);f.sqlite.close();
});
test('P3-M19-07: approval and execution queues differ, filters preserve counts, cursor revocation rejects',async()=>{
 const {readWorkflows}=await import('../lib/hris/r1-workflow-read.ts');const f=await fixture(),id=await f.start();f.seed('waiting');const next=await f.start('waiting');f.adapter.planLocalEffect=async()=>({status:'waiting',statements:()=>[]});act('a');await f.send({operation:'decide',...f.target(next),decision:'approved',reason:'合成'});act('b');await f.send({operation:'decide',...f.target(next),decision:'approved',reason:'合成'});act('owner');
 let result=await readWorkflows(await memberContext(),new URLSearchParams({partition:'execution'}));assert.equal(result.total,1);assert.equal(result.items[0].approvalStatus,'approved');assert.equal(result.items[0].effectStatus,'waiting');assert.equal(result.partitionCounts.approval,1);assert.equal(result.counts['synthetic.review'],2);
 result=await readWorkflows(await memberContext(),new URLSearchParams({limit:'1'}));assert.ok(result.nextCursor);f.sqlite.prepare("UPDATE r1_permission_grants SET scope='[]' WHERE member_id='owner' AND action='read'").run();await assert.rejects(readWorkflows(await memberContext(),new URLSearchParams({limit:'1',cursor:result.nextCursor})),/变化/);result=await readWorkflows(await memberContext(),new URLSearchParams());assert.equal(result.items.length,0);f.sqlite.close();
});
test('P3-M19-02/04: applied instance rejects rollback; actor cannot self-approve or spoof source type',async()=>{
 const f=await fixture(),id=await f.start();await assert.rejects(f.send({operation:'transferNode',...f.target(id),assignees:['owner'],reason:'自审'}),/本人/);const old=f.adapter.loadBusinessSnapshot;f.adapter.loadBusinessSnapshot=async id=>({...await old(id),businessType:'personnel.transfer'});await assert.rejects(f.send({operation:'remind',id,expectedRevision:1,generation:1,reason:'伪造通用类型'}),/类型/);f.adapter.loadBusinessSnapshot=old;
 for(const who of ['a','b']){act(who);await f.send({operation:'decide',...f.target(id),decision:'approved',reason:'合成'});}act('owner');await assert.rejects(f.send({operation:'revokeFlow',id,expectedRevision:f.get(id).revision,generation:1,reason:'已生效不可回滚'}),/关闭/);assert.equal(f.sqlite.prepare('SELECT status FROM synthetic_workflow_source').get().status,'applied');f.sqlite.close();
});
test('P3-M19-06: delegated query uses both current grants and scope, then rejects revocation',async()=>{
 const {readWorkflows}=await import('../lib/hris/r1-workflow-read.ts');const f=await fixture();await f.start();const r=await f.send({operation:'createDelegation',delegateId:'delegate',actions:['read'],businessTypes:['synthetic.review'],scope:['A'],fields:['record'],startAt:Date.now()-1000,endAt:Date.now()+100000}),id=r.result.delegationId;act('delegate');await f.send({operation:'acceptDelegation',id,expectedRevision:1,reason:'接受只读'});assert.equal((await readWorkflows(await memberContext(),new URLSearchParams({delegationId:id}))).items.length,1);
 f.sqlite.prepare("UPDATE r1_permission_grants SET scope='[]' WHERE member_id='owner' AND action='read'").run();assert.equal((await readWorkflows(await memberContext(),new URLSearchParams({delegationId:id}))).items.length,0);await f.send({operation:'revokeDelegation',id,expectedRevision:2,reason:'撤销'});await assert.rejects(readWorkflows(await memberContext(),new URLSearchParams({delegationId:id})),/无效/);f.sqlite.close();
});
test('P3-M19-07: durable notification unknown queries original receipt after transfer without a second send',async()=>{
 const {processWorkflowNotification}=await import('../lib/hris/r1-workflow-notifications.ts'),{digest}=await import('../lib/hris/r1-command.ts');const f=await fixture(),id=await f.start(),n=f.sqlite.prepare("SELECT id FROM r1_workflow_notifications WHERE recipient_id='a'").get().id;let sends=0,queries=0,hash;const adapter={mode:'simulated',async send(id,payload){sends++;hash=await digest(payload);throw Error('synthetic provider accepted; response lost');},async query(){queries++;return {state:'sent',receiptId:'synthetic-receipt',digest:hash};}};
 const disabled=await processWorkflowNotification(memberContext,n);assert.equal(disabled.state,'not_configured');assert.equal(sends,0);const unknown=await processWorkflowNotification(memberContext,n,adapter);assert.equal(unknown.state,'unknown');assert.equal(f.sqlite.prepare('SELECT status FROM r1_workflow_notifications WHERE id=?').get(n).status,'unknown');
 await f.send({operation:'transferNode',...f.target(id),assignees:['c'],reason:'转交后只查旧回执'});const before=f.get(id).revision,r=await processWorkflowNotification(memberContext,n,adapter);assert.equal(r.action,'query_receipt');assert.equal(sends,1);assert.equal(queries,1);assert.equal(f.get(id).revision,before);assert.equal(f.sqlite.prepare('SELECT status FROM r1_workflow_notifications WHERE id=?').get(n).status,'sent');assert.ok(f.sqlite.prepare("SELECT count(*) n FROM r1_workflow_notifications WHERE status='invalidated'").get().n>0);f.sqlite.close();
});
test('P3-M19-06: forbidden attempts record only real denial audit; audit storage failure is not claimed',async()=>{
 const f=await fixture(),id=await f.start();await assert.rejects(f.send({operation:'transferNode',...f.target(id),assignees:['owner'],reason:'自审拒绝'}),e=>e.denialAuditRecorded===true);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_workflow_denials').get().n,1);
 f.sqlite.exec("CREATE TRIGGER synthetic_denial_fault BEFORE INSERT ON r1_workflow_denials BEGIN SELECT RAISE(ABORT,'denial_storage_failure'); END");await assert.rejects(f.send({operation:'intervene',id,expectedRevision:1,generation:1,targetNode:'end',reason:'禁止跳终点'}),e=>e.denialAuditRecorded===false);assert.equal(f.get(id).revision,1);f.sqlite.close();
});
test('P3-M19-02: any policy in both serial orders gives one terminal outcome and no fabricated approvals',async()=>{
 for(const first of ['approved','rejected']){const f=await fixture(),d=definition();d.nodes[0].passPolicy='any';const id=await f.start('source',d);act('a');await f.send({operation:'decide',...f.target(id),decision:first,reason:'先提交'});act('b');await assert.rejects(f.send({operation:'decide',id,expectedRevision:f.get(id).revision,generation:1,nodeRevision:1,decision:first==='approved'?'rejected':'approved',reason:'终态迟到'}),/关闭/);assert.equal(f.get(id).approval_status,first);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM r1_workflow_decisions').get().n,1);const event=JSON.parse(f.sqlite.prepare("SELECT payload FROM r1_workflow_events WHERE action='decide'").get().payload);assert.deepEqual(event.details.cancelledByResolution,['b']);f.sqlite.close();}
});
test('P3-M19-01/02: D7 blocks every generic management path; no missing policies, empty approvers or cross-org template writes',async()=>{
 const f=await fixture(),d=definition();await assert.rejects(f.start('source',{...d,nodes:[{...d.nodes[0],assignees:[]},d.nodes[1]]}));const invalid=structuredClone(d);delete invalid.nodes[0].passPolicy;await assert.rejects(f.start('source',invalid));const id=await f.start();f.sqlite.prepare("UPDATE r1_workflow_instances SET business_type='personnel.transfer' WHERE id=?").run(id);
 for(const operation of ['decide','transferNode','intervene','revokeFlow','withdraw','remind']){const base={operation,id,expectedRevision:1,generation:1,reason:'D7保护矩阵'},payload=operation==='decide'?{...base,nodeRevision:1,decision:'approved'}:operation==='transferNode'?{...base,nodeRevision:1,assignees:['c']}:operation==='intervene'?{...base,targetNode:'review'}:base;await assert.rejects(f.send(payload),e=>e.machineCode==='D7_PROTECTED');}
 f.sqlite.prepare('INSERT INTO r1_permission_grants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(f.t,'owner-config-b','owner','M19','configure','scope','["B"]','["record"]','current','2020-01-01',null);await assert.rejects(f.send({operation:'retire',id:'template',orgId:'B'}),/范围/);f.sqlite.close();
});
test('P3-M19-06: zero interval never grants and delegated creation is forbidden',async()=>{
 const f=await fixture(),id=await f.start(),now=Date.now()+10000,base={operation:'createDelegation',delegateId:'delegate',actions:['manage.transfer'],businessTypes:['synthetic.review'],scope:['A'],fields:['record','grade'],startAt:now,endAt:now};const r=await f.send(base);act('delegate');await f.send({operation:'acceptDelegation',id:r.result.delegationId,expectedRevision:1,reason:'无有效时段'});await assert.rejects(f.send({operation:'transferNode',...f.target(id),assignees:['c'],reason:'尚未生效且空区间',delegationId:r.result.delegationId}),/无效/);await assert.rejects(f.send({...base,delegateId:'c',delegationId:r.result.delegationId}));f.sqlite.close();
});
test('P3-M19-07: competing notification dispatchers claim at most once under tenant CAS',async()=>{
 const {processWorkflowNotification}=await import('../lib/hris/r1-workflow-notifications.ts'),{digest}=await import('../lib/hris/r1-command.ts');const f=await fixture();await f.start();const id=f.sqlite.prepare("SELECT id FROM r1_workflow_notifications WHERE recipient_id='a'").get().id;let sends=0;const adapter={mode:'simulated',async send(id,payload){sends++;return {state:'sent',receiptId:'synthetic-receipt',digest:await digest(payload)};},async query(){return {state:'unknown',receiptId:null,digest:null};}};
 const result=await Promise.allSettled([processWorkflowNotification(memberContext,id,adapter),processWorkflowNotification(memberContext,id,adapter)]);assert.equal(sends,1);assert.ok(result.some(r=>r.status==='fulfilled'));assert.equal(f.sqlite.prepare('SELECT attempt FROM r1_workflow_notifications WHERE id=?').get(id).attempt,1);f.sqlite.close();
});
