import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,grant} from './support/foundation-scenario.mjs';
const jobs=await import('../app/api/recruitment-jobs/route.ts'),recruitment=await import('../app/api/recruitment/route.ts');
async function cmd(api,command,status=200,revision){return expect(await api.POST(request('/api/test',{revision:revision??(await get()).revision,command})),status);}
const recruit=(c,s,r)=>cmd(recruitment,c,s,r),job=(c,s,r)=>cmd(jobs,c,s,r);
const details={category:'合成社招',employment:'全职',location:'上海',address:'合成地址',education:'企业填写的岗位学历要求',experience:'合成相关经验',duties:'使用合成数据核对招聘业务闭环',qualifications:'能够完成岗位相关的合成案例验证',salary:{mode:'range',minCents:1000000,maxCents:1500000,currency:'CNY',period:'month'}};
async function requisition(f){const q=await recruit({action:'requisition',positionId:f.position.id,title:'职位版本共用名额',headcount:1,reason:'合成需求用于验证所有职位版本累计名额',submit:true});act('manager');await recruit({action:'approveRequisition',id:q.id});act('owner');return q;}
async function candidate(q,j,name='合成职位候选人'){return recruit({action:'candidate',requisitionId:q.id,jobId:j.id,name,email:'',source:'主动登记的合成候选资料'});}
async function ready(c){await recruit({action:'interview',candidateId:c.id,rating:4,recommendation:'advance',evidence:'合成岗位技能面试已完成并建议推进'});await recruit({action:'offer',id:c.id,joined:'2026-01-01',evidence:'根据合成评价发起独立录用审批'});act('manager');await recruit({action:'approveOffer',id:c.id});act('owner');await recruit({action:'acceptOffer',id:c.id,evidence:'已登记合成候选人的书面接受依据'});}
test('internal job versions preserve candidate snapshots and all versions share requisition hire capacity',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const q=await requisition(f),j=await job({action:'create',requisitionId:q.id,title:'合成职位第一版',details});
 await recruit({action:'candidate',requisitionId:q.id,jobId:j.id,name:'草稿候选',email:'',source:'草稿版本不能接收候选人'},400);
 await job({action:'activate',id:j.id});const otherQ=await requisition(f);await recruit({action:'candidate',requisitionId:otherQ.id,jobId:j.id,name:'错误需求关联',email:'',source:'必须拒绝不同需求下的职位版本'},400);const c=await candidate(q,j);await job({action:'edit',id:j.id,title:'不得覆盖旧版',details},400);const next=await job({action:'revise',id:j.id});await job({action:'revise',id:j.id},400);await job({action:'edit',id:next.id,title:'合成职位第二版',details:{...details,location:'北京',salary:{mode:'negotiable'}}});await job({action:'activate',id:next.id});const second=await candidate(q,next,'合成第二候选人');await job({action:'archive',id:j.id});await recruit({action:'candidate',requisitionId:q.id,jobId:j.id,name:'归档版不再接收',email:'',source:'只用于验证旧版停止接收'},400);
 let r=(await expect(await recruitment.GET())).records.find(r=>r.id===c.id);assert.equal(r.payload.recruitmentJob.version,1);assert.equal(r.payload.recruitmentJob.details.location,'上海');assert.equal(r.payload.recruitmentJob.details.salary.minCents,1000000);assert.equal((await expect(await recruitment.GET())).records.find(r=>r.id===second.id).payload.recruitmentJob.version,2);
 await ready(c);await recruit({action:'hire',id:c.id,code:'JOB-HIRED-1'});await ready(second);await recruit({action:'hire',id:second.id,code:'JOB-HIRED-2'},400);assert.equal((await expect(await recruitment.GET())).records.filter(r=>r.kind==='candidate'&&r.status==='hired').length,1);
});
test('job scope, lifecycle, salary bounds, Unicode body size and audit failure are enforced',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const q=await requisition(f),base={action:'create',requisitionId:q.id,title:'合成严格职位',details};await job({...base,details:{...details,salary:{...details.salary,minCents:2000000}}},400);await job({...base,details:{...details,salary:{...details.salary,minCents:1.1}}},400);
 act('manager');await job(base,403);act('employee');await expect(await jobs.GET(),403);await grant('outsideJobs','hr',null,[f.otherOrg.id]);act('outsideJobs');await job(base,403);act('owner');await job({...base,extra:'x'.repeat(100000)},413);const before=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_job_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await job(base,503);assert.equal((await get()).revision,before);f.sqlite.exec('DROP TRIGGER reject_job_audit');const j=await job({...base,details:{...details,duties:'职'.repeat(10000),qualifications:'资'.repeat(10000)}});await job({...base,details:{...details,duties:'职'.repeat(10001)}},400);await job({action:'activate',id:j.id},409,before);await recruit({action:'closeRequisition',id:q.id,reason:'合成需求已结束，不再启用新职位'});await job({action:'activate',id:j.id},400);await job({action:'archive',id:j.id});assert.equal((await expect(await jobs.GET())).records.find(r=>r.id===j.id).status,'archived');
});

test('discarded draft does not trap an active job family or reuse historical version numbers',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const q=await requisition(f),j=await job({action:'create',requisitionId:q.id,title:'合成修订可恢复',details});await job({action:'activate',id:j.id});const draft=await job({action:'revise',id:j.id});await job({action:'archive',id:draft.id});const replacement=await job({action:'revise',id:j.id});let records=(await expect(await jobs.GET())).records;assert.equal(records.find(r=>r.id===draft.id).payload.version,2);assert.equal(records.find(r=>r.id===replacement.id).payload.version,3);await job({action:'activate',id:replacement.id});await job({action:'revise',id:j.id},400);await job({action:'archive',id:replacement.id});const fourth=await job({action:'revise',id:j.id});records=(await expect(await jobs.GET())).records;assert.equal(records.find(r=>r.id===fourth.id).payload.version,4);assert.equal(records.filter(r=>r.kind==='recruitmentJob').length,4);
});
