import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,grant} from './support/foundation-scenario.mjs';
const api=await import('../app/api/recruitment/route.ts'),inbox=await import('../app/api/work-inbox/route.ts'),reports=await import('../app/api/reports/route.ts');
async function recruit(command,status=200,revision){const d=await get();return expect(await api.POST(request('/api/recruitment',{revision:revision??d.revision,command})),status);}
const queue=async()=>expect(await inbox.GET(request('/api/work-inbox?domain=recruitment')));
const input=f=>({action:'requisition',positionId:f.position.id,title:'合成显式提交需求',headcount:1,reason:'只有明确提交后的需求可以由独立人员审批',details:{type:'replacement',urgency:'high',requestedOn:'2026-09-01',expectedOn:'2026-10-01',duties:'负责合成业务验证',qualifications:'具备合成案例处理能力'}});
test('draft and submission have separate permissions, inbox states, audit rollback, repeated request guards and contributor independence',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const q=await recruit(input(f));let r=(await expect(await api.GET())).records.find(r=>r.id===q.id);assert.equal(r.status,'draft');assert.equal(r.payload.recruitmentDetails.type,'replacement');assert.ok((await queue()).items.some(i=>i.recordId===q.id&&i.action==='招聘需求提交'));
 act('manager');assert.ok(!(await queue()).items.some(i=>i.recordId===q.id));await recruit({action:'approveRequisition',id:q.id},400);await recruit({action:'returnRequisition',id:q.id,reason:'草稿尚未提交不能退回'},400);await recruit({action:'submitRequisition',id:q.id},403);act('owner');await recruit({action:'candidate',requisitionId:q.id,name:'合成候选人',email:'',source:'草稿不得接收新的候选人'},400);
 const before=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_submit_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await recruit({action:'submitRequisition',id:q.id},503);assert.equal((await get()).revision,before);assert.equal((await expect(await api.GET())).records.find(r=>r.id===q.id).status,'draft');f.sqlite.exec('DROP TRIGGER reject_submit_audit');await recruit({action:'submitRequisition',id:q.id});await recruit({action:'submitRequisition',id:q.id},400);await recruit({action:'reviseRequisition',id:q.id,title:'不得改在审稿',headcount:2,reason:'审批中不得静默更换审阅内容'},400);
 act('manager');assert.ok((await queue()).items.some(i=>i.recordId===q.id&&i.action==='招聘需求审批'));await recruit({action:'returnRequisition',id:q.id,reason:'请完善岗位职责与人数依据'});act('hr');await recruit({action:'reviseRequisition',id:q.id,title:'已补充的合成需求',headcount:2,reason:'补充职责后重新提交独立审批'});r=(await expect(await api.GET())).records.find(r=>r.id===q.id);assert.equal(r.status,'draft');assert.deepEqual(r.payload.recruitmentDetails,input(f).details);await recruit({action:'submitRequisition',id:q.id});await grant('hr','manager',null,[f.org.id],true);act('hr');await recruit({action:'approveRequisition',id:q.id},403);act('manager');await recruit({action:'approveRequisition',id:q.id});act('owner');const report=await expect(await reports.GET(request('/api/reports?dataset=recruitmentOperations')));assert.equal(report.rows[0][report.columns.indexOf('需求状态')],'招聘中');
});
test('legacy draft approvals remain available, and invalid source-field values do not save new records',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const original=input(f);for(const details of [{type:'invented'},{urgency:'urgent'},{expectedOn:'2026-02-30'},{duties:'x'.repeat(2001)}])await recruit({...original,details},400);assert.equal((await expect(await api.GET())).records.length,0);
 const q=await recruit(original);act('manager');const {developmentContext}=await import('../lib/hris/development-repository.ts'),{applyRecruitment}=await import('../lib/hris/recruitment.ts'),c=await developmentContext(['requisition']),records=c.records.map(r=>({...r,payload:{...r.payload,requisitionSubmissionRequired:undefined}}));assert.equal(applyRecruitment(records,c.state,c.member,{action:'approveRequisition',id:q.id}).record.status,'active');
 await grant('outsideHr','hr',null,[f.otherOrg.id]);act('outsideHr');await recruit({action:'submitRequisition',id:q.id},403);
});

test('save-and-submit is one atomic revision and cannot leave a saved draft after audit failure',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const before=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_combined_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await recruit({...input(f),submit:true},503);assert.equal((await get()).revision,before);assert.equal((await expect(await api.GET())).records.length,0);f.sqlite.exec('DROP TRIGGER reject_combined_audit');const q=await recruit({...input(f),submit:true});assert.equal(q.revision,before+1);let r=(await expect(await api.GET())).records.find(r=>r.id===q.id);assert.equal(r.status,'submitted');assert.equal(r.payload.submittedBy,'owner');act('manager');await recruit({action:'returnRequisition',id:q.id,reason:'补充条件后可以一次保存并提交'});act('hr');const rev=(await get()).revision;await recruit({action:'reviseRequisition',id:q.id,title:'修订后直接提交',headcount:2,reason:'完整修订后明确发起独立审批',submit:true});r=(await expect(await api.GET())).records.find(r=>r.id===q.id);assert.equal(r.status,'submitted');assert.equal(r.payload.submittedBy,'hr');assert.equal((await get()).revision,rev+1);assert.ok(r.payload.contributors.includes('owner'));assert.ok(r.payload.contributors.includes('hr'));
});
