import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,dev} from './support/foundation-scenario.mjs';
import {moveEmployee} from './support/performance-scenario.mjs';
const api=await import('../app/api/shift-definitions/route.ts');
async function post(command,status=200,revision){return expect(await api.POST(request('/api/shift-definitions',{revision:revision??(await get()).revision,command})),status);}
const spec=f=>({action:'create',name:'合成跨日固定班',orgId:f.org.id,times:{startMinute:1320,endMinute:1800,breakStartMinute:1500,breakEndMinute:1560}});
async function sealed(f){const d=await post(spec(f));await post({action:'seal',id:d.ids[0]});return d.ids[0];}
test('fixed shifts freeze assigned version, support next-day rest, and archived draft recovery never reuses version numbers',async t=>{const f=await setup();t.after(()=>f.sqlite.close());const id=await sealed(f),a=await post({action:'assign',id,assignments:[{employeeId:f.e.id,date:'2026-02-01'}]});let shift=(await get()).records.find(r=>r.id===a.ids[0]);assert.equal(shift.payload.startAt,'2026-02-01T14:00:00.000Z');assert.equal(shift.payload.breakStart,'2026-02-01T17:00:00.000Z');assert.equal(shift.payload.shiftDefinition.version,1);await post({action:'edit',id,...Object.fromEntries(Object.entries(spec(f)).filter(([k])=>k!=='action'))},400);const v2=(await post({action:'revise',id})).ids[0];await post({action:'archive',id:v2,reason:'丢弃合成草稿但保留历史版本编号'});const v3=(await post({action:'revise',id})).ids[0];assert.equal((await get()).records.find(r=>r.id===v3).payload.version,3);await post({action:'archive',id,reason:'只停止新派班，不修改已经产生的排班'});await post({action:'assign',id,assignments:[{employeeId:f.e.id,date:'2026-02-02'}]},400);shift=(await get()).records.find(r=>r.id===a.ids[0]);assert.equal(shift.payload.shiftDefinition.version,1);const history=await expect(await dev.GET(new Request('https://hris.example/api/development?id='+shift.id)));assert.equal(history.items[0].snapshot.payload.shiftDefinition.id,id);});
test('assignment is all-or-nothing for duplicates, cross-org, departed staff and unavailable audit',async t=>{const f=await setup();t.after(()=>f.sqlite.close());const id=await sealed(f),one={employeeId:f.e.id,date:'2026-02-01'},revision=(await get()).revision;await post({action:'assign',id,assignments:[one,one]},400);await post({action:'assign',id,assignments:[one,{employeeId:f.other.id,date:'2026-02-02'}]},400);assert.equal((await get()).revision,revision);assert.equal((await get()).records.filter(r=>r.kind==='shift').length,0);f.sqlite.exec("CREATE TRIGGER deny_shift_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await post({action:'assign',id,assignments:[one,{...one,date:'2026-02-02'}]},503);f.sqlite.exec('DROP TRIGGER deny_shift_audit');assert.equal((await get()).revision,revision);assert.equal((await get()).records.filter(r=>r.kind==='shift').length,0);await post({action:'assign',id,assignments:[one]});await post({action:'assign',id,assignments:[{...one,date:'2026-02-03'}]},409,revision);await moveEmployee(f,'exit');await post({action:'assign',id,assignments:[{...one,date:'2026-02-03'}]},400);});
test('scoped managers assign but cannot maintain definitions; employee and out-of-scope HR cannot read or write',async t=>{const f=await setup();t.after(()=>f.sqlite.close());const id=await sealed(f);act('employee');await expect(await api.GET(),403);await post({action:'assign',id,assignments:[{employeeId:f.e.id,date:'2026-02-01'}]},403);act('manager');await post(spec(f),403);await post({action:'assign',id,assignments:[{employeeId:f.e.id,date:'2026-02-01'}]});act('owner');const other=(await post({...spec(f),orgId:f.otherOrg.id})).ids[0];act('hr');assert.ok(!(await expect(await api.GET())).records.some(r=>r.id===other));await post({action:'seal',id:other},403);act('owner');for(const times of [{startMinute:600,endMinute:600},{startMinute:600,endMinute:2041},{startMinute:540,endMinute:1080,breakStartMinute:540,breakEndMinute:1080},{startMinute:540,endMinute:1080,breakStartMinute:720}])await post({...spec(f),times},400);});
test('one frozen date rejects all assignments without leaving the earlier valid date persisted',async t=>{const f=await setup();t.after(()=>f.sqlite.close());const attendance=await import('../app/api/attendance/route.ts'),periods=await import('../app/api/attendance-periods/route.ts'),send=async(api,command)=>expect(await api.POST(request('/api/test',{revision:(await get()).revision,command})));const id=(await post({...spec(f),times:{startMinute:540,endMinute:1080}})).ids[0];await post({action:'seal',id});const shift=(await post({action:'assign',id,assignments:[{employeeId:f.e.id,date:'2026-01-05'}]})).ids[0],type=await send(attendance,{action:'leaveType',code:'SHIFT-FREEZE',name:'合成全覆盖假期',paid:true,requiresBalance:false});act('employee');const leave=await send(attendance,{action:'leave',employeeId:f.e.id,shiftId:shift,leaveTypeId:type.id,startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',reason:'合成全天已核实请假覆盖冻结来源'});act('manager');await send(attendance,{action:'decideLeave',id:leave.id,accepted:true,evidence:'独立审核合成全天请假事实'});act('owner');await send(periods,{action:'freeze',employeeId:f.e.id,start:'2026-01-05',end:'2026-01-06',evidence:'期间来源完整核实并完成独立审批'});const revision=(await get()).revision;await post({action:'assign',id,assignments:[{employeeId:f.e.id,date:'2026-01-07'},{employeeId:f.e.id,date:'2026-01-06'}]},409);assert.equal((await get()).revision,revision);assert.equal((await get()).records.filter(r=>r.kind==='shift').length,1);});
