import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,applyCommand} from '../lib/hris/model.ts';
import {grantSchema,validateGrant} from '../lib/hris/member-rules.ts';
const request={action:'request',employeeId:'e3',kind:'transfer',orgId:'o2',reason:'业务调动'};
function submitted(){let s=applyCommand(initialState(),{action:'workflow',kind:'transfer',steps:[{userId:'r1',name:'初审'},{userId:'r2',name:'终审'}]},undefined,'admin');return applyCommand(s,request,undefined,'applicant');}
test('多级审批仅终审通过更新组织，不能越级或重复审批',()=>{let s=submitted();const id=s.approvals[0].id;const old=s.employees.find(e=>e.id==='e3').orgId;const command={action:'decide',id,decision:'approved'};assert.throws(()=>applyCommand(s,command,undefined,'r2'),/尚未轮到/);s=applyCommand(s,command,undefined,'r1');assert.equal(s.approvals[0].currentStep,1);assert.equal(s.approvals[0].status,'pending');assert.equal(s.employees.find(e=>e.id==='e3').orgId,old);assert.throws(()=>applyCommand(s,command,undefined,'r1'),/尚未轮到/);s=applyCommand(s,command,undefined,'r2');assert.equal(s.approvals[0].status,'approved');assert.equal(s.employees.find(e=>e.id==='e3').orgId,'o2');assert.throws(()=>applyCommand(s,command,undefined,'r2'),/已处理/);});
test('驳回与撤回不修改档案，已撤回不能审批',()=>{for(const action of ['reject','withdraw']){let s=submitted();const before=structuredClone(s.employees);const id=s.approvals[0].id;s=action==='reject'?applyCommand(s,{action:'decide',id,decision:'rejected',decisionReason:'合成驳回原因'},undefined,'r1'):applyCommand(s,{action:'withdraw',id},undefined,'applicant');assert.deepEqual(s.employees,before);assert.throws(()=>applyCommand(s,{action:'decide',id,decision:'approved'},undefined,'r1'),/已处理/);}});
test('修改流程不改变已提交申请的审批人及版本',()=>{let s=submitted();s=applyCommand(s,{action:'workflow',kind:'transfer',steps:[{userId:'new',name:'新审批人'}]},undefined,'admin');assert.equal(s.workflows.transfer.version,2);assert.equal(s.approvals[0].workflowVersion,1);assert.equal(s.approvals[0].steps[0].userId,'r1');});
test('未配置流程、重复审批人与自审流程被拒绝',()=>{assert.throws(()=>applyCommand(initialState(),request,undefined,'applicant'),/配置/);assert.throws(()=>applyCommand(initialState(),{action:'workflow',kind:'transfer',steps:[{userId:'r1',name:'a'},{userId:'r1',name:'b'}]},undefined,'admin'));const s=submitted();assert.throws(()=>applyCommand({...s,approvals:[]},request,undefined,'r1'),/申请人不能/);});
test('成员验证禁止自降权、无档案员工授权与已离职关联',()=>{const state=initialState();const input=grantSchema.parse({email:'USER@EXAMPLE.COM',name:'用户',role:'admin',employeeId:null,active:true,revision:0});assert.equal(input.email,'user@example.com');assert.throws(()=>validateGrant({...input,active:false},state,'user@example.com'),/不能停用/);assert.throws(()=>validateGrant({...input,role:'employee'},state,'other@example.com'),/关联员工/);assert.throws(()=>validateGrant({...input,employeeId:'missing'},state,'other@example.com'),/在职/);});
