CREATE TABLE r1_consumer_inbox(tenant_id TEXT NOT NULL,consumer_id TEXT NOT NULL,source TEXT NOT NULL,event_id TEXT NOT NULL,sequence INTEGER NOT NULL,entity_id TEXT NOT NULL,digest TEXT NOT NULL,mapping_version INTEGER NOT NULL,received_at TEXT NOT NULL,status TEXT NOT NULL,PRIMARY KEY(tenant_id,consumer_id,source,event_id));
CREATE TABLE r1_consumer_cursors(tenant_id TEXT NOT NULL,consumer_id TEXT NOT NULL,source TEXT NOT NULL,entity_id TEXT NOT NULL,sequence INTEGER NOT NULL,PRIMARY KEY(tenant_id,consumer_id,source,entity_id));
INSERT INTO r1_consumer_inbox SELECT tenant_id,'r1.compat',source,event_id,sequence,entity_id,digest,mapping_version,received_at,status FROM r1_inbox;
INSERT INTO r1_consumer_cursors SELECT tenant_id,'r1.compat',source,entity_id,sequence FROM r1_source_cursors;
CREATE TABLE r1_callback_nonces(tenant_id TEXT NOT NULL,source TEXT NOT NULL,nonce TEXT NOT NULL,digest TEXT NOT NULL,received_at INTEGER NOT NULL,PRIMARY KEY(tenant_id,source,nonce));
CREATE TABLE r1_external_receipts(tenant_id TEXT NOT NULL,source TEXT NOT NULL,receipt_id TEXT NOT NULL,delivery_id TEXT NOT NULL,digest TEXT NOT NULL,state TEXT NOT NULL,key_id TEXT NOT NULL,received_at TEXT NOT NULL,PRIMARY KEY(tenant_id,source,receipt_id));
ALTER TABLE r1_deliveries ADD COLUMN source_namespace TEXT;
ALTER TABLE r1_deliveries ADD COLUMN payload TEXT;
ALTER TABLE r1_deliveries ADD COLUMN payload_digest TEXT;
ALTER TABLE r1_deliveries ADD COLUMN attempt INTEGER NOT NULL DEFAULT 0;
ALTER TABLE r1_deliveries ADD COLUMN next_attempt_at INTEGER;
ALTER TABLE r1_deliveries ADD COLUMN owner_id TEXT;
ALTER TABLE r1_deliveries ADD COLUMN reason_code TEXT;
ALTER TABLE r1_integration_quarantine ADD COLUMN owner_id TEXT NOT NULL DEFAULT 'integration-owner';
ALTER TABLE r1_integration_quarantine ADD COLUMN next_action TEXT NOT NULL DEFAULT 'compare_original_receipt_and_contract';
ALTER TABLE r1_integration_quarantine ADD COLUMN close_gate TEXT NOT NULL DEFAULT 'external_chain_acceptance';
CREATE TABLE r1_stable_references(tenant_id TEXT NOT NULL,source TEXT NOT NULL,object_type TEXT NOT NULL,external_id TEXT NOT NULL,version INTEGER NOT NULL,internal_id TEXT NOT NULL,org_id TEXT NOT NULL,label TEXT NOT NULL,raw_status TEXT NOT NULL,mapping_version INTEGER NOT NULL,payload TEXT NOT NULL,digest TEXT NOT NULL,PRIMARY KEY(tenant_id,source,object_type,external_id,version));
CREATE INDEX r1_reference_internal ON r1_stable_references(tenant_id,source,object_type,internal_id,version);
CREATE TRIGGER r1_references_immutable BEFORE UPDATE ON r1_stable_references BEGIN SELECT RAISE(ABORT,'IMMUTABLE_REFERENCE'); END;
CREATE TABLE r1_adapter_guard(tenant_id TEXT NOT NULL,id TEXT NOT NULL,valid INTEGER NOT NULL CHECK(valid=1),PRIMARY KEY(tenant_id,id));
ALTER TABLE r1_deliveries ADD COLUMN org_id TEXT;
