'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {ObjectiveAttempt} from '../learning-exams/objective';
import ProcessHistory from '../development/process-history';
import {learningTaskStageDeadline,learningStageSubmissionOpen,learningStageOpen} from '@/lib/hris/learning-requirements';
import {examTaskOpen} from '@/lib/hris/learning-exam-tasks';
import {businessDate} from '@/lib/hris/business-time';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];papers:R[];revision:number;role:string;employeeId:string|null;error?:string};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[definitions,setDefinitions]=useState<R[]>([]),[examId,setExam]=useState('none'),[employeeId,setEmployee]=useState('none'),[start,setStart]=useState(businessDate()),[due,setDue]=useState(''),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/learning-exam-tasks',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]);const [d,h]=await Promise.all([a.json() as Promise<Data>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok||!b.ok)throw Error(d.error??h.error);setData(d);setCore(h.state);if(['admin','hr'].includes(d.role)){const r=await fetch('/api/learning-exams',{cache:'no-store'}),v=await r.json() as {records:R[];error?:string};if(!r.ok)throw Error(v.error);setDefinitions(v.records.filter(x=>x.status==='sealed'));}else setDefinitions([]);}catch(e){setData(null);setDefinitions([]);setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 async function send(command:Record<string,unknown>){if(!data||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/learning-exam-tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const manage=!!data&&['admin','hr'].includes(data.role),exam=definitions.find(r=>r.id===examId);
 return <main className="main-content mx-auto max-w-5xl"><Link href="/learning-plans">返回学习计划</Link>{manage&&<> · <Link href="/learning-exams">管理试卷</Link></>}<div className="page-head mt-5"><h1>独立考试任务</h1><Button onClick={load} variant="outline">刷新</Button></div><p className="mb-4 text-slate-600">独立考试按任务记录作答和成绩，绑定学习计划的考试通过后计入对应阶段要求；不替代课程核验，不自动结项或发学分。按试卷冻结题型和分值评分，保留原始分及取整百分制；通过后停止重考。</p>{error&&<p role="alert">{error}</p>}
 {manage&&<form className="panel space-y-3" onSubmit={e=>{e.preventDefault();void send({action:'assign',examId,employeeId,start,due});}}><h2>派发已定版试卷</h2><Select value={examId} onValueChange={v=>{setExam(v);setEmployee('none');}}><SelectTrigger aria-label="试卷版本"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">选择试卷版本</SelectItem>{definitions.map(r=><SelectItem key={r.id} value={r.id}>{r.payload.title} · v{r.payload.version}</SelectItem>)}</SelectContent></Select><Select value={employeeId} onValueChange={setEmployee}><SelectTrigger aria-label="考试学员"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">选择同组织在职学员</SelectItem>{core?.employees.filter(e=>e.orgId===exam?.payload.orgId&&e.status!=='离职').map(e=><SelectItem key={e.id} value={e.id}>{e.name} · {e.code}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-2 gap-3"><label>开放日期<Input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>截止日期<Input type="date" required min={start} value={due} onChange={e=>setDue(e.target.value)}/></label></div><Button disabled={busy||examId==='none'||employeeId==='none'}>派发考试</Button><label className="block">取消依据<Input minLength={5} maxLength={3000} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label></form>}
 <section className="mt-5 space-y-4">{data?.records.filter(r=>r.kind==='learningExamTask').map(r=>{const paper=data.papers.find(p=>p.id===r.referenceId),attempts=data.records.filter(a=>a.kind==='learningExamAttempt'&&a.referenceId===r.id);return <article className="panel" key={r.id}><h2>{r.payload.title} · {core?.employees.find(e=>e.id===r.employeeId)?.name??'学员'}</h2>{r.payload.requirementRetiredAt&&<p>已退出计划要求 · {r.payload.requirementRetiredAt}；以下为原状态和历史成绩。</p>}<p>{r.payload.start} 至 {r.payload.due} · {({active:'进行中',completed:'已通过',failed:'次数用尽未通过',cancelled:'已取消'} as Record<string,string>)[r.status]??r.status}</p>{learningTaskStageDeadline(r,data.records)&&<p>阶段提交截止：{learningTaskStageDeadline(r,data.records)}；是否允许超期按冻结配置执行。</p>}<div className="flex gap-2 my-3"><Button variant="outline" onClick={()=>setSelected(selected===r.id?null:r.id)}>试卷与记录</Button>{manage&&!r.payload.requirementRetiredAt&&r.status==='active'&&<Button variant="outline" disabled={busy||evidence.trim().length<5} onClick={()=>send({action:'cancel',id:r.id,evidence})}>取消考试</Button>}</div>{selected===r.id&&<>{paper&&<ObjectiveAttempt key={r.id+r.updatedAt} exam={paper} task={r} attempts={attempts} busy={busy} own={r.employeeId===data.employeeId&&!!core&&examTaskOpen(r,core)&&learningStageSubmissionOpen(r,data.records)&&learningStageOpen(r,data.records,undefined,core)} send={c=>send({action:'submit',id:r.id,answers:c.answers})}/>}<ProcessHistory id={r.id} updatedAt={r.updatedAt}/></>}</article>;})}</section></main>;
}
