'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={livePlanIds:string[];records:R[];employees:{id:string;name:string;status:string}[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={submitted:'待反馈',returned:'待补充',acknowledged:'已反馈',withdrawn:'已撤回'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const response=await fetch('/api/performance-checkins',{cache:'no-store'}),d=await response.json() as Data&{error?:string};if(!response.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 const records=data?.records??[],manager=['admin','hr','manager'].includes(data?.role??''),record=records.find(r=>r.id===detail),employee=(r:R)=>data?.employees.find(e=>e.id===r.employeeId),plan=(r:R)=>records.find(p=>p.id===r.referenceId&&p.kind==='performancePlan'),live=(p:R|undefined)=>!!p&&!!data?.livePlanIds?.includes(p.id)&&p.status==='confirmed'&&employee(p)?.status!=='离职'&&records.some(c=>c.kind==='performanceCycle'&&c.id===p.referenceId&&c.status==='active')&&!records.some(r=>r.kind==='performance'&&r.payload.sourcePlanId===p.id),pendingChange=(p:R)=>records.some(r=>r.kind==='performanceGoalChange'&&r.referenceId===p.id&&r.status==='submitted'),plans=records.filter(r=>r.kind==='performancePlan'&&r.employeeId===data?.employeeId&&live(r)&&!pendingChange(r)),rows=records.filter(r=>r.kind==='performanceCheckin'&&[employee(r)?.name,r.payload.period,r.payload.checkinGoal?.title,labels[r.status]].join(' ').includes(search)).reverse();
 const sameVersion=(r:R)=>{const p=plan(r);return !!p&&(p.payload.version??1)===r.payload.basePlanVersion&&!pendingChange(p);};
 function open(action:string,r?:R,accepted?:boolean){setError('');setForm({action,id:r?.id??'',planId:r?.referenceId??'',goalIndex:String(r?.payload.goalIndex??0),progress:String(r?.payload.progressPercent??0),evidence:action==='submit'?r?.payload.evidence??'':'',actionPlan:r?.payload.actionPlan??'',accepted:String(accepted)});}
 async function submit(e:FormEvent){e.preventDefault();if(!form||!data||busy)return;setBusy(true);setError('');try{const command={...form,id:form.id||undefined,...(form.action==='submit'?{goalIndex:Number(form.goalIndex),progress:Number(form.progress)}:{}),...(form.action==='feedback'?{accepted:form.accepted==='true'}:{})},response=await fetch('/api/performance-checkins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await response.json() as {error?:string};if(!response.ok)throw Error(d.error);setForm(null);setNotice('目标执行记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const selected=plans.find(p=>p.id===form?.planId);
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex flex-wrap gap-5 text-sm"><Link href="/performance" className="text-link">绩效管理</Link><Link href="/performance-changes" className="text-link">目标调整</Link><Link href="/work-inbox" className="text-link">待办工作台</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">GOAL PROGRESS</div><h1>目标执行跟进</h1><p className="mt-2 text-sm text-slate-500">员工本人记录成果、困难与下一步，其他有权限管理者提供反馈。每条记录保留提交时的目标版本。</p></div><Button variant="outline" onClick={load}>刷新</Button></div><p className="mb-5 text-sm text-slate-500">进度为员工自报，不代表验收完成或绩效得分。跟进不阻止自评；计划进入评价或结束后保留记录，不再反馈或补充。</p>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}<div className="flex flex-wrap gap-3 mb-5"><Input aria-label="搜索执行跟进" className="max-w-sm" placeholder="搜索员工、目标、期间或状态" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{!!plans.length&&data?.employeeId&&<Button onClick={()=>open('submit')}>记录本人进展</Button>}</div><div className="grid gap-4">{rows.slice((page-1)*12,page*12).map(r=><section key={r.id} className="panel"><div className="section-head"><div><h2>{employee(r)?.name} · {r.payload.checkinGoal?.title}</h2><p className="text-sm text-slate-500">{r.payload.period} · 目标 V{r.payload.basePlanVersion} · {labels[r.status]} · 自报进度 {r.payload.progressPercent}%</p>{!live(plan(r))&&<p className="text-sm text-slate-500 mt-2">计划已不在跟进阶段，保留原记录状态。</p>}{plan(r)&&(plan(r)!.payload.version??1)!==r.payload.basePlanVersion&&<p className="text-sm text-amber-700 mt-2">此记录对应历史目标版本，不代表新版目标进展。</p>}</div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setDetail(r.id)}>详情与历史</Button>{r.employeeId===data?.employeeId&&r.createdBy===data?.userId&&['submitted','returned'].includes(r.status)&&<Button size="sm" variant="outline" onClick={()=>open('withdraw',r)}>撤回</Button>}{r.status==='returned'&&r.createdBy===data?.userId&&r.employeeId===data?.employeeId&&live(plan(r))&&sameVersion(r)&&<Button size="sm" onClick={()=>open('submit',r)}>补充记录</Button>}{r.status==='submitted'&&manager&&r.employeeId!==data?.employeeId&&r.createdBy!==data?.userId&&live(plan(r))&&<><Button size="sm" onClick={()=>open('feedback',r,true)}>提供反馈</Button><Button size="sm" variant="outline" onClick={()=>open('feedback',r,false)}>请补充</Button></>}</div></div><p className="text-sm whitespace-pre-wrap">{r.payload.evidence}</p>{r.payload.verification&&<p className="text-sm mt-3 whitespace-pre-wrap">管理者反馈：{r.payload.verification}</p>}</section>)}</div>{!rows.length&&<p className="panel empty">暂无可见的执行跟进记录</p>}<div className="flex justify-end gap-3 items-center mt-4"><span>{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*12>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{form?.action==='submit'?'记录目标执行进展':form?.action==='withdraw'?'撤回执行记录':form?.accepted==='true'?'提供目标执行反馈':'请员工补充记录'}</DialogTitle><DialogDescription>提交与反馈保留历史。反馈仅用于沟通，不修改目标权重或正式评分。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='submit'&&<><label className="field"><span>本人绩效计划</span><select required disabled={!!form.id} className="rounded border p-2" value={form.planId} onChange={e=>setForm({...form,planId:e.target.value,goalIndex:'0'})}><option value="">请选择</option>{plans.map(p=><option key={p.id} value={p.id}>{p.payload.period} · V{p.payload.version??1}</option>)}</select></label><label className="field"><span>执行目标</span><select required disabled={!!form.id} className="rounded border p-2" value={form.goalIndex} onChange={e=>setForm({...form,goalIndex:e.target.value})}>{selected?.payload.goals?.map((g,i)=><option key={i} value={i}>{i+1}. {g.title}</option>)}</select></label>{selected&&<p className="text-sm whitespace-pre-wrap">衡量标准：{selected.payload.goals?.[Number(form.goalIndex)]?.metric}</p>}<label className="field"><span>自报进度 %</span><Input type="number" required min={0} max={100} step={1} value={form.progress} onChange={e=>setForm({...form,progress:e.target.value})}/></label></>}<label className="field"><span>{form.action==='submit'?'实际进展、成果与困难':'反馈 / 撤回原因'}</span><textarea required minLength={5} maxLength={4000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label>{form.action==='submit'&&<label className="field"><span>下一步行动</span><textarea required minLength={5} maxLength={4000} rows={3} value={form.actionPlan} onChange={e=>setForm({...form,actionPlan:e.target.value})}/></label>}<Button type="submit" disabled={busy||form.action==='submit'&&!selected}>{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>执行记录与目标快照</DialogTitle><DialogDescription>{record&&`${record.payload.period} · 目标 V${record.payload.basePlanVersion} · ${labels[record.status]}`}</DialogDescription></DialogHeader>{record&&<><div className="rounded border p-4"><h3 className="font-medium">{record.payload.checkinGoal?.title} · 权重 {record.payload.checkinGoal?.weight}%</h3><p className="mt-2 whitespace-pre-wrap">{record.payload.checkinGoal?.metric}</p></div><p>自报进度：{record.payload.progressPercent}%</p><p className="whitespace-pre-wrap">{record.payload.evidence}</p><p className="whitespace-pre-wrap">下一步：{record.payload.actionPlan}</p>{record.payload.verification&&<p className="whitespace-pre-wrap">反馈：{record.payload.verification}</p>}{record.payload.closedReason&&<p>撤回原因：{record.payload.closedReason}</p>}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></>}</DialogContent></Dialog></main>;
}
