'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={canRespondIds:string[];records:R[];revision:number;role:string;employeeId:string|null;userId:string};
type Field={key:string;label:string;type?:string};
const groups:Record<string,string>={self:'本人',supervisor:'上级',peer:'同级',report:'下级'},statuses:Record<string,string>={draft:'配置中',open:'开放填报',closed:'已停止收集',assigned:'已指派',cancelled:'已移除',submitted:'已提交',published:'已发布'};
const fields:Record<string,Field[]>={project:[{key:'name',label:'项目名称'},{key:'orgId',label:'被评人组织范围',type:'org'},{key:'templateId',label:'纯量表问卷模板',type:'template'},{key:'start',label:'填报开始日',type:'date'},{key:'end',label:'填报截止日',type:'date'},{key:'minRespondents',label:'同级/下级最少有效回答人数（3–10）',type:'number'},{key:'purpose',label:'用途与反馈说明',type:'long'}],invite:[{key:'subjectId',label:'被评员工',type:'employee'},{key:'reviewerEmployeeId',label:'评估员工',type:'employee'},{key:'relationship',label:'与被评人的关系',type:'relationship'}],close:[{key:'evidence',label:'停止收集依据',type:'long'}],publishReport:[{key:'subjectId',label:'被评员工',type:'subject'},{key:'evidence',label:'报告发布依据',type:'long'}]};
export default function Feedback(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[tab,setTab]=useState('feedbackProject'),[form,setForm]=useState<Record<string,string>|null>(null),[answers,setAnswers]=useState<number[]>([]),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/feedback',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),find=(id:string|null)=>data?.records.find(r=>r.id===id),record=find(selected),emp=(id:string|null)=>core?.employees.find(e=>e.id===id)?.name??'—',project=(r:R)=>r.kind==='feedbackProject'?r:r.kind==='feedbackReply'?find(find(r.referenceId)?.referenceId??null):find(r.referenceId),invite=find(form?.inviteId??null),filling=invite?project(invite):undefined;
 function pick(value:string,change:(s:string)=>void,options:string[][],label:string){return <Select value={value||'none'} onValueChange={change}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>;}
 function open(action:string,r?:R){setError('');setForm({action,id:r?.id??'',projectId:r?.id??'',inviteId:r?.id??'',minRespondents:'3'});if(action==='respond')setAnswers(data?.records.find(x=>x.kind==='feedbackReply'&&x.referenceId===r?.id)?.payload.answers??project(r!)!.payload.surveyQuestions!.map(()=>-1));}
 async function send(command:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('360评估记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;const c:Record<string,unknown>={...form};if(!c.id)delete c.id;if(form.action==='project')c.minRespondents=Number(form.minRespondents);if(form.action==='respond')c.answers=answers;send(c);}
 function options(f:Field){if(f.type==='org')return (core?.orgs??[]).filter(o=>o.status==='启用').map(o=>[o.id,o.name]);if(f.type==='template')return (data?.records??[]).filter(r=>r.kind==='surveyTemplate'&&r.status==='published'&&r.payload.surveyQuestions?.every(q=>q.type==='rating')).map(r=>[r.id,`${r.payload.name} V${r.payload.version}`]);if(f.type==='relationship')return Object.entries(groups);if(f.type==='subject')return [...new Map((data?.records??[]).filter(r=>r.kind==='feedbackInvite'&&r.referenceId===form?.projectId&&r.status==='assigned').map(r=>[r.payload.subjectId!,r.payload.subjectName!])).entries()];return (core?.employees??[]).filter(e=>e.status!=='离职').map(e=>[e.id,e.name]);}
 function actions(r:R){const p=project(r);return <div className="flex flex-wrap gap-2"><Button variant="ghost" size="sm" onClick={()=>setSelected(r.id)}>详情</Button>{r.kind==='feedbackProject'&&hr&&<>{r.status==='draft'&&<><Button size="sm" onClick={()=>open('invite',r)}>配置评估人</Button><Button size="sm" disabled={busy} onClick={()=>send({action:'open',id:r.id})}>开放填报</Button></>}{r.status==='open'&&<Button size="sm" variant="outline" onClick={()=>open('close',r)}>停止收集</Button>}{r.status==='closed'&&<Button size="sm" onClick={()=>open('publishReport',r)}>发布个人报告</Button>}</>}{r.kind==='feedbackInvite'&&r.status==='assigned'&&<>{hr&&p?.status==='draft'&&<Button variant="outline" size="sm" disabled={busy} onClick={()=>send({action:'removeInvite',id:r.id})}>移除</Button>}{data?.canRespondIds.includes(r.id)&&<Button size="sm" onClick={()=>open('respond',r)}>填报 / 修改</Button>}</>}</div>;}
 const rows=(data?.records??[]).filter(r=>r.kind===tab&&(r.payload.name+' '+r.payload.subjectName+' '+emp(r.employeeId)+' '+project(r)?.payload.name).includes(search)).reverse();
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/surveys" className="text-link">量表模板</Link><Link href="/self-service" className="text-link">个人工作台</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">360 FEEDBACK</div><h1>360度评估</h1><p className="text-sm text-slate-500 mt-2">项目HR及管理员可审计实名答卷。被评人仅查看发布后的分组汇总；同级、下级未达最少回答人数时隐藏分数，本人和上级分组可单独展示。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}<section className="panel"><div className="section-head gap-4"><Tabs value={tab} onValueChange={v=>{setTab(v);setPage(1);}}><TabsList className="h-auto flex-wrap"><TabsTrigger value="feedbackProject">评估项目</TabsTrigger><TabsTrigger value="feedbackInvite">评估邀请</TabsTrigger><TabsTrigger value="feedbackReply">答卷记录</TabsTrigger><TabsTrigger value="feedbackReport">个人报告</TabsTrigger></TabsList></Tabs>{hr&&tab==='feedbackProject'&&<Button onClick={()=>open('project')}>新建项目</Button>}</div><div className="filters"><Input aria-label="搜索360记录" className="max-w-md" placeholder="搜索项目或员工" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><Table><TableHeader><TableRow>{['项目 / 被评人','填报人 / 期间','状态','操作'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*15,page*15).map(r=><TableRow key={r.id}><TableCell>{r.payload.name??project(r)?.payload.name}<p className="text-sm text-slate-500">{r.payload.subjectName??(r.kind==='feedbackReport'?emp(r.employeeId):'')}{r.payload.relationship?' · '+groups[r.payload.relationship]:''}</p></TableCell><TableCell>{r.kind==='feedbackProject'?`${r.payload.start} 至 ${r.payload.end}`:r.kind==='feedbackReport'?'汇总报告':emp(r.employeeId)}</TableCell><TableCell><Badge variant="outline">{statuses[r.status]}</Badge></TableCell><TableCell>{actions(r)}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">暂无可见记录</p>}<div className="flex justify-end items-center gap-3 mt-4"><span className="text-sm">{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{form?.action==='respond'?`${invite?.payload.subjectName}的360反馈`:'360项目办理'}</DialogTitle><DialogDescription>{form?.action==='respond'?'项目HR及管理员可查看实名答卷，被评人按分组查看汇总。停止收集后答卷锁定。':'发布后名单与题目锁定；报告在停止收集后生成并保持不变。'}</DialogDescription></DialogHeader>{error&&<p className="text-red-700" role="alert">{error}</p>}{form&&<form onSubmit={submit} className="edit-form">{form.action==='respond'?<><p className="text-sm whitespace-pre-wrap">{filling?.payload.purpose}</p>{filling?.payload.surveyQuestions?.map((q,i)=><label key={i} className="field border rounded p-4"><span>{i+1}. {q.prompt}</span><p className="text-sm text-slate-500">1：{q.lowLabel} · 5：{q.highLabel}</p>{pick(answers[i]>0?String(answers[i]):'none',v=>setAnswers(answers.map((x,j)=>i===j?Number(v):x)),['1','2','3','4','5'].map(v=>[v,v]),q.prompt)}</label>)}</>:fields[form.action]?.map(f=><label className="field" key={f.key}><span>{f.label}</span>{['org','template','employee','relationship','subject'].includes(f.type??'')?pick(form[f.key],v=>setForm({...form,[f.key]:v}),options(f),f.label):f.type==='long'?<textarea required minLength={5} rows={4} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<Input required type={f.type??'text'} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<Button disabled={busy} type="submit">{busy?'保存中…':'提交'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-4xl"><DialogHeader><DialogTitle>{record?.payload.name??record?.payload.subjectName??'评估记录'}</DialogTitle><DialogDescription>{record?statuses[record.status]:''}</DialogDescription></DialogHeader>{record&&<div className="space-y-4"><p className="whitespace-pre-wrap">{record.payload.purpose??project(record)?.payload.purpose}</p>{record.kind==='feedbackReport'&&<><p className="text-sm text-slate-500">不展示评估人名单，不计算跨组总分。同级与下级少于 {record.payload.minRespondents} 份回答时不显示均分。</p><Table><TableHeader><TableRow><TableHead>行为指标</TableHead>{record.payload.feedbackGroups?.map(g=><TableHead key={g.relationship}>{groups[g.relationship]}<p className="text-sm">{g.responses} 份</p></TableHead>)}</TableRow></TableHeader><TableBody>{record.payload.surveyQuestions?.map((q,i)=><TableRow key={i}><TableCell>{q.prompt}</TableCell>{record.payload.feedbackGroups?.map(g=><TableCell key={g.relationship}>{g.suppressed?'未达展示人数':g.averages?.[i]}</TableCell>)}</TableRow>)}</TableBody></Table></>}{record.kind==='feedbackReply'&&project(record)?.payload.surveyQuestions?.map((q,i)=><p key={i}>{q.prompt}：{record.payload.answers?.[i]}</p>)}{record.kind==='feedbackInvite'&&<p>被评人：{record.payload.subjectName} · 关系：{groups[record.payload.relationship??'']}</p>}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></div>}</DialogContent></Dialog>
 </main>;
}
