'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Badge} from '@/components/ui/badge';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {CadreProfile} from '@/lib/hris/cadre-profiles';
type Employee={id:string;code:string;name:string};
export default function Workspace(){
 const [employees,setEmployees]=useState<Employee[]>([]),[employeeId,setEmployeeId]=useState(''),[data,setData]=useState<CadreProfile|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[allowed,setAllowed]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch('/api/hris',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json() as {state:{employees:Employee[]};role:string;error?:string};if(!r.ok)throw Error(d.error);if(c.signal.aborted)return;const role=d.role;setAllowed(['admin','hr','manager'].includes(role));setEmployees(d.state.employees.map((e:Employee)=>({id:e.id,code:e.code,name:e.name})));const query=new URLSearchParams(window.location.search).get('employeeId');setEmployeeId(query??d.state.employees[0]?.id??'');setLoading(false);}).catch(e=>{if(!c.signal.aborted){setError(e.message);setLoading(false);}});return()=>c.abort();},[]);
 useEffect(()=>{if(!employeeId||employeeId==='none'||!allowed){setData(null);return;}const c=new AbortController();setLoading(true);setData(null);setError('');fetch('/api/cadre-profiles?'+new URLSearchParams({employeeId}),{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json() as CadreProfile&{error?:string};if(!r.ok)throw Error(d.error);if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[employeeId,allowed,refresh]);
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link className="text-link" href="/">导航台</Link><Link className="text-link" href="/cadres">干部提名与考察</Link><Link className="text-link" href="/development">人才与发展</Link></nav><div className="page-head mt-5"><div><h1>干部人才档案</h1><p className="mt-2 text-sm text-slate-500">按管理范围汇集现有任用、资格、盘点、绩效与发展记录。未记录的信息保留为空。</p></div><Button variant="outline" disabled={loading} onClick={()=>setRefresh(v=>v+1)}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{!loading&&!allowed?<p className="panel">此档案供有组织管理权限的管理员、HR和经理查阅；个人任务请进入<Link href="/self-service" className="text-link">员工自助</Link>。</p>:<><section className="panel mb-5"><label className="field max-w-md"><span>选择员工</span><Select value={employeeId||'none'} onValueChange={setEmployeeId}><SelectTrigger aria-label="选择档案员工"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{employees.map(e=><SelectItem key={e.id} value={e.id}>{e.name} · {e.code}</SelectItem>)}</SelectContent></Select></label>{data&&<div className="mt-4 flex flex-wrap gap-4"><strong>{data.employee.name}</strong><span>{data.employee.code}</span><span>{data.employee.org}</span><span>{data.employee.job}</span><Badge variant="outline">{data.employee.status}</Badge></div>}</section>{loading?<p className="panel" role="status">正在读取当前档案…</p>:data?.sections.map(s=><section className="panel mb-5" key={s.key}><h2 className="text-lg font-semibold mb-3">{s.title} <span className="text-slate-500 text-sm">{s.items.length} 条</span></h2>{s.items.length?<Table><TableHeader><TableRow>{['事项 / 期间','状态','摘要','截止 / 有效期 / 更新日期','来源'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{s.items.map(r=><TableRow key={r.id}><TableCell>{r.title}</TableCell><TableCell>{r.status}</TableCell><TableCell className="max-w-lg whitespace-pre-wrap">{r.detail}</TableCell><TableCell>{r.date}</TableCell><TableCell><Link className="text-link" href={r.href}>查看业务记录</Link></TableCell></TableRow>)}</TableBody></Table>:<p className="text-sm text-slate-500">暂无权限范围内的相关记录；不代表已评估或不符合资格。</p>}</section>)}{data&&<p className="text-sm text-slate-500">最新盘点和绩效按各期间的版本更正链展示，原记录在来源模块保留。此页不生成综合人才排名，不替代提名审议或人事审批。</p>}</>}</main>;
}
