'use client';
import {businessDate} from '@/lib/hris/business-time';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];revision:number;role:string;employeeId:string|null;userId:string};
type Field={key:string;label:string;type?:string;optional?:boolean};
const fields:Record<string,Field[]>={nominate:[{key:'employeeId',label:'提名员工',type:'employee'},{key:'positionId',label:'目标岗位',type:'position'},{key:'qualificationId',label:'引用内部资格',type:'qualification',optional:true},{key:'successionId',label:'引用后备记录',type:'succession',optional:true},{key:'evidence',label:'提名依据',type:'long'}],decide:[{key:'evidence',label:'独立审议意见',type:'long'}],withdraw:[{key:'evidence',label:'撤回依据',type:'long'}],recordAppointment:[{key:'approvalId',label:'已终审通过的岗位调动',type:'approval'},{key:'evidence',label:'任用核对依据',type:'long'}],observation:[{key:'due',label:'考察截止日',type:'date'},{key:'objectives',label:'考察目标与验收要求',type:'long'}],submitReview:[{key:'evidence',label:'本人述职与成果依据',type:'long'}],returnReview:[{key:'evidence',label:'退回补充意见',type:'long'}],completeReview:[{key:'evidence',label:'考察核验意见',type:'long'}]};
const statuses:Record<string,string>={submitted:'待审议 / 核验',approved:'提名已批准',rejected:'未通过',withdrawn:'已撤回',appointed:'任用已核对',active:'考察中',returned:'待补充述职',completed:'考察目标达成',development_needed:'需继续发展'};
export default function Cadres(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[tab,setTab]=useState('cadreNomination'),[form,setForm]=useState<Record<string,string>|null>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/cadres',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),manager=hr||data?.role==='manager',approver=['admin','manager'].includes(data?.role??''),emp=(id:string|null)=>core?.employees.find(e=>e.id===id)?.name??'—',record=data?.records.find(r=>r.id===selected);
 function open(action:string,r?:R,extra:Record<string,string>={}){setError('');setForm({action,id:r?.id??'',employeeId:r?.employeeId??'none',positionId:r?.positionId??'none',nominationId:r?.id??'',...extra});}
 async function send(command:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/cadres',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('干部业务记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;const c:Record<string,unknown>={...form};if(!c.id)delete c.id;for(const f of fields[form.action])if(f.optional&&(!form[f.key]||form[f.key]==='none'))delete c[f.key];if(form.accepted)c.accepted=form.accepted==='true';send(c);}
 function options(f:Field){if(f.type==='employee')return (core?.employees??[]).filter(e=>e.status!=='离职'&&e.id!==data?.employeeId).map(e=>[e.id,e.name]);if(f.type==='position')return (core?.positions??[]).filter(p=>p.status==='启用').map(p=>[p.id,p.name]);if(f.type==='approval')return (core?.approvals??[]).filter(a=>a.kind==='transfer'&&a.status==='approved'&&a.employeeId===form?.employeeId&&a.positionId===form?.positionId).map(a=>[a.id,`${businessDate(a.created)} · ${emp(a.employeeId)} · ${a.reason}`]);return (data?.records??[]).filter(r=>r.kind===(f.type==='qualification'?'qualificationApplication':'succession')&&r.employeeId===form?.employeeId&&(f.type==='qualification'?r.status==='certified':r.status==='active'&&r.positionId===form?.positionId)).map(r=>[r.id,f.type==='qualification'?`${r.payload.name} · ${r.payload.certificateNumber}`:`后备 · ${r.payload.readiness}`]);}
 function actions(r:R){const self=r.employeeId===data?.employeeId,independent=manager&&!self&&r.createdBy!==data?.userId;return <div className="flex flex-wrap gap-2"><Button variant="ghost" size="sm" onClick={()=>setSelected(r.id)}>详情</Button>{r.kind==='cadreNomination'?<>{r.status==='submitted'&&approver&&independent&&<><Button size="sm" onClick={()=>open('decide',r,{accepted:'true'})}>批准提名</Button><Button size="sm" variant="outline" onClick={()=>open('decide',r,{accepted:'false'})}>不通过</Button></>}{['submitted','approved'].includes(r.status)&&r.createdBy===data?.userId&&<Button size="sm" variant="outline" onClick={()=>open('withdraw',r)}>撤回</Button>}{r.status==='approved'&&hr&&!self&&<><Button asChild size="sm" variant="outline"><Link href="/approvals">办理岗位调动</Link></Button><Button size="sm" onClick={()=>open('recordAppointment',r)}>核对任用</Button></>}{r.status==='appointed'&&hr&&!data?.records.some(x=>x.kind==='cadreObservation'&&x.referenceId===r.id)&&<Button size="sm" onClick={()=>open('observation',r)}>建立考察计划</Button>}</>:<>{['active','returned'].includes(r.status)&&self&&<Button size="sm" onClick={()=>open('submitReview',r)}>提交述职</Button>}{r.status==='submitted'&&independent&&<><Button size="sm" onClick={()=>open('completeReview',r,{accepted:'true'})}>目标达成</Button><Button size="sm" variant="outline" onClick={()=>open('completeReview',r,{accepted:'false'})}>需继续发展</Button><Button size="sm" variant="outline" onClick={()=>open('returnReview',r)}>退回补充</Button></>}</>}</div>;}
 const rows=(data?.records??[]).filter(r=>r.kind===tab&&(emp(r.employeeId)+' '+r.payload.targetPositionName).includes(search)).reverse();
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/cadre-interviews" className="text-link">干部访谈记录（HR）</Link><Link href="/cadre-terms" className="text-link">干部任期登记</Link><Link href="/cadre-profiles" className="text-link">干部人才档案</Link><Link href="/development" className="text-link">后备与人才发展</Link><Link href="/qualifications" className="text-link">任职资格</Link><Link href="/approvals" className="text-link">人事审批</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">CADRE DEVELOPMENT</div><h1>干部提名与考察</h1><p className="text-sm text-slate-500 mt-2">提名经独立审议后，仍须完成岗位调动审批。任用核对与考察记录保留依据，不直接替代人员异动。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}<section className="panel"><div className="section-head gap-4"><Tabs value={tab} onValueChange={v=>{setTab(v);setPage(1);}}><TabsList><TabsTrigger value="cadreNomination">选拔提名</TabsTrigger><TabsTrigger value="cadreObservation">任职考察与述职</TabsTrigger></TabsList></Tabs>{manager&&tab==='cadreNomination'&&<Button onClick={()=>open('nominate')}>发起提名</Button>}</div><div className="filters"><Input aria-label="搜索干部业务" className="max-w-md" placeholder="搜索员工或目标岗位" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><Table><TableHeader><TableRow>{['员工','目标岗位','状态 / 截止日','操作'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*15,page*15).map(r=><TableRow key={r.id}><TableCell>{emp(r.employeeId)}</TableCell><TableCell>{r.payload.targetPositionName}</TableCell><TableCell><Badge variant="outline">{statuses[r.status]}</Badge>{r.payload.due&&<p className="text-sm text-slate-500">{r.payload.due}</p>}</TableCell><TableCell>{actions(r)}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">暂无可见记录</p>}<div className="flex justify-end items-center gap-3 mt-4"><span className="text-sm">{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>干部业务办理</DialogTitle><DialogDescription>{form?.action==='recordAppointment'?'请选择提名批准后发起且已终审通过的同人员、同岗位调动审批。':'依据实际人才决策与岗位要求填写，记录不自动变更员工任职。'}</DialogDescription></DialogHeader>{error&&<p className="text-red-700" role="alert">{error}</p>}{form&&<form onSubmit={submit} className="edit-form">{fields[form.action].map(f=><label className="field" key={f.key}><span>{f.label}{f.optional?'（选填）':''}</span>{['employee','position','qualification','succession','approval'].includes(f.type??'')?<Select value={form[f.key]||'none'} onValueChange={v=>setForm({...form,[f.key]:v,...(['employeeId','positionId'].includes(f.key)?{qualificationId:'none',successionId:'none'}:{})})}><SelectTrigger aria-label={f.label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{options(f).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>:f.type==='long'?<textarea rows={4} required minLength={5} maxLength={3000} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<Input required={!f.optional} type={f.type??'text'} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}<Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{record?emp(record.employeeId):''} · {record?.payload.targetPositionName}</DialogTitle><DialogDescription>{record?statuses[record.status]:''}</DialogDescription></DialogHeader>{record&&<div className="space-y-4">{Object.entries({提名依据:record.payload.evidence,审议意见:record.payload.verification,任用核对:record.payload.appointmentEvidence,考察目标:record.payload.objectives,本人述职:record.payload.selfEvidence,关闭原因:record.payload.closedReason}).filter(([,v])=>v).map(([k,v])=><div key={k}><p className="text-sm text-slate-500">{k}</p><p className="whitespace-pre-wrap">{v}</p></div>)}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></div>}</DialogContent></Dialog>
 </main>;
}
