'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Form={id?:string;name:string;orgId:string;start:string;end:string;next:boolean;rest:boolean;restStart:string;restEnd:string;restStartNext:boolean;restEndNext:boolean};
const time=(n:number)=>`${String(Math.floor(n%1440/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`,offset=(s:string,next=false)=>Number(s.split(':')[0])*60+Number(s.split(':')[1])+(next?1440:0),display=(n:number)=>`${n>=1440?'次日 ':''}${time(n)}`,select='w-full rounded border bg-white p-2';
export default function Workspace(){const [data,setData]=useState<{records:R[];revision:number;role:string}|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<Form|null>(null),[assign,setAssign]=useState<R|null>(null),[dates,setDates]=useState(''),[employeeId,setEmployee]=useState(''),[archive,setArchive]=useState<R|null>(null),[reason,setReason]=useState(''),[detail,setDetail]=useState<R|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const [r,h]=await Promise.all([fetch('/api/shift-definitions',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),d=await r.json() as {records:R[];revision:number;role:string;error?:string},c=await h.json() as {state:State;error?:string};if(!r.ok||!h.ok)throw Error(d.error??c.error??'加载失败');setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}useEffect(()=>{void load();},[]);
 const manage=['admin','hr'].includes(data?.role??'');
 function open(r?:R){const s=r?.payload.fixedShift;setError('');setForm({id:r?.id,name:r?.payload.name??'',orgId:r?.payload.orgId??'',start:time(s?.startMinute??540),end:time(s?.endMinute??1080),next:(s?.endMinute??0)>=1440,rest:s?.breakStartMinute!==undefined,restStart:time(s?.breakStartMinute??720),restEnd:time(s?.breakEndMinute??780),restStartNext:(s?.breakStartMinute??0)>=1440,restEndNext:(s?.breakEndMinute??0)>=1440});}
 async function send(command:unknown){if(busy||!data)return;setBusy(true);setError('');try{const r=await fetch('/api/shift-definitions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error??'保存失败');setForm(null);setAssign(null);setArchive(null);setNotice('已保存。已产生的员工排班保留派班时的版本与时段。');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-6xl space-y-5"><Link href="/attendance" className="text-link">返回假勤管理</Link><div className="page-head"><div><h1>固定班次与派班</h1><p className="mt-2 text-sm text-slate-500">适用于同组织、单一连续工作时段及一次休息，支持跨日。按北京时间登记。</p></div>{manage&&<Button onClick={()=>open()}>新建班次草稿</Button>}</div>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel space-y-3">{data?.records.slice().reverse().map(r=><article className="rounded border p-4 space-y-2" key={r.id}><h2>{r.payload.name} · V{r.payload.version} · {{draft:'草稿',sealed:'已定版',archived:'已归档'}[r.status]??r.status}</h2><p>{core?.orgs.find(o=>o.id===r.payload.orgId)?.name} · {r.payload.fixedShift&&`${display(r.payload.fixedShift.startMinute)}—${display(r.payload.fixedShift.endMinute)}`}</p>{r.payload.fixedShift?.breakStartMinute!==undefined&&<p>休息 {display(r.payload.fixedShift.breakStartMinute)}—{display(r.payload.fixedShift.breakEndMinute!)}</p>}<div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setDetail(r)}>历史</Button>{manage&&r.status==='draft'&&<><Button variant="outline" disabled={busy} onClick={()=>open(r)}>编辑</Button><Button disabled={busy} onClick={()=>send({action:'seal',id:r.id})}>定版</Button></>}{r.status==='sealed'&&<><Button disabled={busy} onClick={()=>{setEmployee('');setDates('');setAssign(r);setError('');}}>派班</Button>{manage&&!data.records.some(x=>x.payload.definitionRootId===r.payload.definitionRootId&&(x.status==='draft'||x.status==='sealed'&&(x.payload.version??0)>(r.payload.version??0)))&&<Button variant="outline" disabled={busy} onClick={()=>send({action:'revise',id:r.id})}>创建修订草稿</Button>}</>}{manage&&r.status!=='archived'&&<Button variant="ghost" disabled={busy} onClick={()=>{setReason('');setArchive(r);}}>归档此版本</Button>}</div></article>)}{data&&!data.records.length&&<p>暂无可见班次定义。</p>}</section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>固定班次草稿</DialogTitle><DialogDescription>定版后时段不可直接覆盖；修改请创建新版本。派班前请核对实际排班规则。</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();void send({action:form.id?'edit':'create',...(form.id?{id:form.id}:{}),name:form.name,orgId:form.orgId,times:{startMinute:offset(form.start),endMinute:offset(form.end,form.next),...(form.rest?{breakStartMinute:offset(form.restStart,form.restStartNext),breakEndMinute:offset(form.restEnd,form.restEndNext)}:{})}});}}><fieldset disabled={busy} className="space-y-3">{error&&<p role="alert">{error}</p>}<label className="field">班次名称<Input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field">所属组织<select required disabled={!!form.id} className={select} value={form.orgId} onChange={e=>setForm({...form,orgId:e.target.value})}><option value="">请选择</option>{core?.orgs.filter(o=>o.status==='启用').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="field">开始时间<Input type="time" required value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label className="field">结束时间<Input type="time" required value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label><label><input type="checkbox" checked={form.next} onChange={e=>setForm({...form,next:e.target.checked})}/> 结束在次日</label><div><label><input type="checkbox" checked={form.rest} onChange={e=>setForm({...form,rest:e.target.checked})}/> 设置一次休息</label></div>{form.rest&&<div className="space-y-2"><label className="field">休息开始<Input type="time" required value={form.restStart} onChange={e=>setForm({...form,restStart:e.target.value})}/></label><label><input type="checkbox" checked={form.restStartNext} onChange={e=>setForm({...form,restStartNext:e.target.checked})}/> 休息开始在次日</label><label className="field">休息结束<Input type="time" required value={form.restEnd} onChange={e=>setForm({...form,restEnd:e.target.value})}/></label><label><input type="checkbox" checked={form.restEndNext} onChange={e=>setForm({...form,restEndNext:e.target.checked})}/> 休息结束在次日</label></div>}<Button>保存草稿</Button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!assign} onOpenChange={v=>!v&&!busy&&setAssign(null)}><DialogContent><DialogHeader><DialogTitle>派班 · {assign?.payload.name}</DialogTitle><DialogDescription>每行一个业务日期，格式YYYY-MM-DD，最多20日。所有日期一起校验和保存，冲突或冻结时整批拒绝。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();if(assign)void send({action:'assign',id:assign.id,assignments:dates.split(/\s+/).filter(Boolean).map(date=>({employeeId,date}))});}}>{error&&<p role="alert">{error}</p>}<label className="field">员工<select required className={select} value={employeeId} onChange={e=>setEmployee(e.target.value)}><option value="">请选择同组织在职员工</option>{core?.employees.filter(e=>e.orgId===assign?.payload.orgId&&e.status!=='离职').map(e=><option value={e.id} key={e.id}>{e.name} · {e.code}</option>)}</select></label><label className="field">业务日期<textarea required rows={6} maxLength={240} className={select} value={dates} onChange={e=>setDates(e.target.value)}/></label><Button disabled={busy}>确认整批派班</Button></form></DialogContent></Dialog>
 <Dialog open={!!archive} onOpenChange={v=>!v&&!busy&&setArchive(null)}><DialogContent><DialogHeader><DialogTitle>归档班次版本</DialogTitle><DialogDescription>停止使用此版本新派班，既有员工排班继续有效，不会自动取消。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();if(archive)void send({action:'archive',id:archive.id,reason});}}><label className="field">原因<textarea required minLength={5} maxLength={1500} className={select} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy}>保存归档</Button></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent><DialogHeader><DialogTitle>班次版本历史</DialogTitle><DialogDescription>{detail?.payload.name} · V{detail?.payload.version}</DialogDescription></DialogHeader>{detail&&<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/>}</DialogContent></Dialog></main>;
}
