'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Usage={items:{id:string;kind:string;employeeName:string;period:string;status:string;occurrences:number;href:string}[];counts:{plans:number;pendingChanges:number;publishedResults:number};page:number;hasMore:boolean;note:string};
type Data={records:R[];revision:number;role:string};
type Form={id?:string;orgId:string;indicator:NonNullable<R['payload']['indicator']>};
const labels:Record<string,string>={draft:'草稿',sealed:'已定版',archived:'已归档'},field='w-full rounded border bg-white p-2';
export default function Workspace(){
 const [data,setData]=useState<{records:R[];revision:number;role:string}|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<Form|null>(null),[detail,setDetail]=useState<R|null>(null),[archive,setArchive]=useState<R|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const [usageFor,setUsageFor]=useState<R|null>(null),[usage,setUsage]=useState<Usage|null>(null),[usageError,setUsageError]=useState(''),[usageBusy,setUsageBusy]=useState(false);
 async function loadUsage(r:R,page=1){setUsageFor(r);setUsage(null);setUsageError('');setUsageBusy(true);try{const response=await fetch('/api/performance-indicators?'+new URLSearchParams({usageId:r.id,page:String(page)}),{cache:'no-store'}),body=await response.json() as Usage&{error?:string};if(!response.ok)throw Error(body.error??'引用情况加载失败');setUsage(body);}catch(e){setUsageError((e as Error).message);}finally{setUsageBusy(false);}}
 const hr=['admin','hr'].includes(data?.role??'');
 async function load(){try{const [r,h]=await Promise.all([fetch('/api/performance-indicators',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),d=await r.json() as Data&{error?:string},c=await h.json() as {state:State;error?:string};if(!r.ok||!h.ok)throw Error(d.error??c.error??'加载失败');setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[]);
 function open(r?:R){setError('');setForm({id:r?.id,orgId:r?.payload.orgId??'',indicator:r?.payload.indicator?{...r.payload.indicator}:{code:'',title:'',category:'',description:'',metric:'',type:'qualitative'}});}
 async function send(command:unknown){if(!data||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/performance-indicators',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error??'保存失败');setForm(null);setArchive(null);setNotice('指标已保存，既有目标继续保留原引用快照。');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-5xl space-y-5"><Link className="text-link" href="/performance">返回绩效管理</Link><div className="page-head"><div><h1>定性绩效指标</h1><p className="mt-2 text-sm text-slate-500">维护衡量标准，供同组织目标选用。选择指标不会自动评分或指定评价人。</p></div>{hr&&<Button onClick={()=>open()}>新建指标草稿</Button>}</div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<Input aria-label="搜索指标" placeholder="搜索编号、名称或分类" value={search} onChange={e=>setSearch(e.target.value)}/>
 <section className="panel space-y-3">{data?.records.filter(r=>[r.payload.indicator?.code,r.payload.indicator?.title,r.payload.indicator?.category].join(' ').includes(search)).slice().reverse().map(r=><article key={r.id} className="rounded border p-4 space-y-2"><h2>{r.payload.indicator?.code} · {r.payload.indicator?.title} · V{r.payload.version}</h2><p className="text-sm">{r.payload.indicator?.category} · {core?.orgs.find(o=>o.id===r.payload.orgId)?.name} · {labels[r.status]}</p><div className="flex gap-2 flex-wrap"><Button variant="ghost" onClick={()=>setDetail(r)}>内容与历史</Button>{hr&&<Button variant="ghost" disabled={usageBusy} onClick={()=>void loadUsage(r)}>引用情况</Button>}{hr&&r.status==='draft'&&<><Button variant="outline" onClick={()=>open(r)}>编辑</Button><Button disabled={busy} onClick={()=>send({action:'seal',id:r.id})}>定版</Button></>}{hr&&r.status==='sealed'&&!data.records.some(x=>x.payload.definitionRootId===r.payload.definitionRootId&&(x.status==='draft'||x.status==='sealed'&&(x.payload.version??0)>(r.payload.version??0)))&&<Button variant="outline" disabled={busy} onClick={()=>send({action:'revise',id:r.id})}>修订新版本</Button>}{hr&&r.status!=='archived'&&<Button variant="ghost" onClick={()=>{setReason('');setArchive(r);}}>归档</Button>}</div></article>)}{data&&!data.records.length&&<p>暂无可见指标，仍可手工编写目标。</p>}</section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>定性指标草稿</DialogTitle><DialogDescription>编号和组织在新建后保持不变；已定版版本通过修订更新。</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();void send({...form,action:form.id?'edit':'create'});}}><fieldset disabled={busy} className="space-y-3">{error&&<p role="alert">{error}</p>}<label className="field">所属组织<select required disabled={!!form.id} className={field} value={form.orgId} onChange={e=>setForm({...form,orgId:e.target.value})}><option value="">请选择</option>{core?.orgs.filter(o=>o.status==='启用').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{(['code','title','category'] as const).map(k=><label key={k} className="field">{{code:'编号（字母、数字、下划线或短横线）',title:'指标名称',category:'分类名称'}[k]}<Input required disabled={k==='code'&&!!form.id} maxLength={k==='code'?60:200} pattern={k==='code'?'[A-Za-z0-9_-]+':undefined} value={form.indicator[k]} onChange={e=>setForm({...form,indicator:{...form.indicator,[k]:e.target.value}})}/></label>)}{(['description','metric'] as const).map(k=><label className="field" key={k}>{k==='description'?'指标描述':'衡量标准'}<textarea className={field} maxLength={4000} rows={4} value={form.indicator[k]} onChange={e=>setForm({...form,indicator:{...form.indicator,[k]:e.target.value}})}/></label>)}<Button>保存草稿</Button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!archive} onOpenChange={v=>!v&&!busy&&setArchive(null)}><DialogContent><DialogHeader><DialogTitle>归档指标版本</DialogTitle><DialogDescription>停止新引用，保留已有目标来源与历史。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();if(archive)void send({action:'archive',id:archive.id,reason});}}><textarea className={field} aria-label="归档依据" required minLength={5} maxLength={1500} value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={busy}>保存归档</Button></form></DialogContent></Dialog>
 <Dialog open={!!usageFor} onOpenChange={v=>!v&&!usageBusy&&setUsageFor(null)}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>指标引用情况 · V{usageFor?.payload.version}</DialogTitle><DialogDescription>{usageFor?.payload.indicator?.title} · 仅当前管理范围</DialogDescription></DialogHeader>{usageBusy&&<p role="status">正在读取引用情况…</p>}{usageError&&<p role="alert">{usageError}</p>}{usage&&<><p className="text-sm">目标计划 {usage.counts.plans} · 待审调整 {usage.counts.pendingChanges} · 已发布结果 {usage.counts.publishedResults}</p><p className="text-sm text-slate-500">{usage.note}</p>{usage.items.map(item=><article key={item.id} className="rounded border p-3 text-sm"><p>{item.employeeName} · {item.period} · {item.kind}</p><p className="my-2">引用目标数：{item.occurrences}</p><Link href={item.href} className="text-link">查看办理记录</Link></article>)}{!usage.items.length&&<p>本页没有可见引用记录。</p>}<div className="flex items-center gap-3"><Button variant="outline" disabled={usage.page===1||usageBusy} onClick={()=>usageFor&&void loadUsage(usageFor,usage.page-1)}>上一页</Button><span className="text-sm">第 {usage.page} 页</span><Button variant="outline" disabled={!usage.hasMore||usageBusy} onClick={()=>usageFor&&void loadUsage(usageFor,usage.page+1)}>下一页</Button></div></>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{detail?.payload.indicator?.title} · V{detail?.payload.version}</DialogTitle><DialogDescription>{detail?.payload.indicator?.code} · {detail?.payload.indicator?.category}</DialogDescription></DialogHeader><p className="whitespace-pre-wrap">{detail?.payload.indicator?.description||'暂无描述'}</p><p className="whitespace-pre-wrap">衡量标准：{detail?.payload.indicator?.metric||'选用到目标时需补充衡量标准'}</p>{detail&&<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/>}</DialogContent></Dialog></main>;
}
