'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {State} from '@/lib/hris/model';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={records:R[];revision:number;role:string};
const statuses:Record<string,string>={registered:'已登记',ended:'已结束',voided:'已作废'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<R|null>(null);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/cadre-terms',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]);const [d,h]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok||!b.ok)throw Error(d.error??h.error);setData(d);setCore(h.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 const writer=['admin','hr'].includes(data?.role??''),employee=(id:string|null)=>core?.employees.find(e=>e.id===id),rows=(data?.records??[]).filter(r=>(filter==='all'||r.status===filter)&&[employee(r.employeeId)?.name,employee(r.employeeId)?.code,r.payload.targetPositionName].join(' ').includes(search));
 function open(action:string,r?:R){setError('');const t=r?.payload.cadreTerm;setForm({action,id:r?.id??'',employeeId:r?.employeeId??'',orgId:t?.orgId??'',positionId:r?.positionId??'',appointmentType:'主职',start:t?.start??'',expectedEnd:t?.expectedEnd??'',observationEnd:t?.observationEnd??'',supervisorId:t?.supervisorId??'',actualEnd:'',endReason:'免职',evidence:''});}
 async function submit(e:FormEvent){e.preventDefault();if(!form||!data||busy)return;setBusy(true);try{const command=Object.fromEntries(Object.entries(form).filter(([,v])=>v!=='')),r=await fetch('/api/cadre-terms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const pick=(key:string,label:string,options:string[][])=><label className="field"><span>{label}</span><Select value={form?.[key]||'none'} onValueChange={v=>setForm({...form!,[key]:v==='none'?'':v,...(key==='orgId'?{positionId:''}:{})})}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{options.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></label>;
 const date=(key:string,label:string,required=false)=><label className="field"><span>{label}</span><Input type="date" required={required} value={form?.[key]??''} onChange={e=>setForm({...form!,[key]:e.target.value})}/></label>;
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5"><Link href="/cadres">提名与考察</Link><Link href="/cadre-profiles">人才档案</Link></nav><div className="page-head mt-5"><div><h1>干部任期登记</h1><p className="text-sm text-slate-500 mt-2">按任用凭证登记主职任期。登记不自动变更员工岗位，不发送通知。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p role="alert" className="panel error">{error}</p>}<section className="panel"><div className="flex gap-3 mb-5 flex-wrap"><Input className="max-w-sm" aria-label="搜索任期" placeholder="员工、工号或岗位" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-36" aria-label="任期状态"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部记录</SelectItem>{Object.entries(statuses).map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select>{writer&&<Button onClick={()=>open('register')}>登记任期</Button>}</div><Table><TableHeader><TableRow>{['员工','任用岗位','任期开始','预计结束','实际结束 / 原因','登记状态','操作'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell>{employee(r.employeeId)?.name}<p className="text-sm text-slate-500">{employee(r.employeeId)?.status}</p></TableCell><TableCell>{r.payload.targetPositionName}</TableCell><TableCell>{r.payload.cadreTerm?.start}</TableCell><TableCell>{r.payload.cadreTerm?.expectedEnd??'未登记'}</TableCell><TableCell>{r.payload.cadreTerm?.actualEnd??'—'} {r.payload.cadreTerm?.endReason}</TableCell><TableCell>{statuses[r.status]}</TableCell><TableCell><Button size="sm" variant="ghost" onClick={()=>setSelected(r)}>详情与历史</Button>{writer&&r.status==='registered'&&<><Button size="sm" variant="outline" onClick={()=>open('correct',r)}>更正</Button><Button size="sm" variant="outline" onClick={()=>open('end',r)}>结束任期</Button><Button size="sm" variant="ghost" onClick={()=>open('void',r)}>作废</Button></>}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">暂无权限范围内的任期记录</p>}</section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>干部任期办理</DialogTitle><DialogDescription>凭证与更正原因保留历史。结束任期不会自动办理离职或退休。</DialogDescription></DialogHeader>{error&&<p role="alert">{error}</p>}{form&&<form onSubmit={submit} className="edit-form">{['register','correct'].includes(form.action)&&<>{form.action==='register'&&pick('employeeId','员工',(core?.employees??[]).filter(e=>e.status!=='离职').map(e=>[e.id,e.name]))}{pick('orgId','任用部门',(core?.orgs??[]).map(o=>[o.id,o.name]))}{pick('positionId','任用岗位',(core?.positions??[]).filter(p=>p.orgId===form.orgId&&p.status==='启用').map(p=>[p.id,p.name]))}<p>任用类型：主职</p>{date('start','任期开始日期',true)}{date('expectedEnd','预计任期结束日期（选填）')}{date('observationEnd','考察结束日期（选填）')}{pick('supervisorId','汇报上级（选填）',(core?.employees??[]).filter(e=>e.status!=='离职'&&e.id!==form.employeeId).map(e=>[e.id,e.name]))}</>}{form.action==='end'&&<>{date('actualEnd','实际任期结束日期',true)}{pick('endReason','结束原因',['免职','离职','退休'].map(v=>[v,v]))}</>}<label className="field"><span>登记凭证或办理依据</span><textarea required minLength={5} maxLength={3000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button type="submit" disabled={busy}>{busy?'保存中…':'保存登记'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent><DialogHeader><DialogTitle>任期依据与历史</DialogTitle><DialogDescription>{selected?.payload.targetPositionName}</DialogDescription></DialogHeader>{selected&&<dl className="grid grid-cols-2 gap-3 text-sm">{Object.entries({'员工':employee(selected.employeeId)?.name,'任用部门':core?.orgs.find(o=>o.id===selected.payload.cadreTerm?.orgId)?.name,'任用类型':selected.payload.cadreTerm?.appointmentType,'任期开始':selected.payload.cadreTerm?.start,'预计结束':selected.payload.cadreTerm?.expectedEnd,'考察结束':selected.payload.cadreTerm?.observationEnd,'汇报上级':employee(selected.payload.cadreTerm?.supervisorId??null)?.name,'实际结束':selected.payload.cadreTerm?.actualEnd,'结束原因':selected.payload.cadreTerm?.endReason}).map(([k,v])=><div key={k}><dt className="text-slate-500">{k}</dt><dd>{v??'未登记'}</dd></div>)}</dl>}<p className="whitespace-pre-wrap">{selected?.payload.evidence}</p>{selected&&<ProcessHistory id={selected.id} updatedAt={selected.updatedAt}/>}</DialogContent></Dialog>
 </main>;
}
