'use client';
import {useState,type FormEvent} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {DevelopmentRecord} from '@/lib/hris/development';
type Send=(c:Record<string,unknown>)=>Promise<void>;
export function ExamEditor({courseId,send,busy,initial,standalone=false}:{courseId:string;send:Send;busy:boolean;initial?:{questions:{prompt:string;options:string[];correct:number}[];passingScore:number;maxAttempts:number};standalone?:boolean}){
 const [questions,setQuestions]=useState(initial?.questions??[{prompt:'',options:['','','',''],correct:0}]),[passingScore,setScore]=useState(initial?.passingScore??60),[maxAttempts,setMax]=useState(initial?.maxAttempts??3);
 function submit(e:FormEvent){e.preventDefault();send({action:'exam',courseId,questions,passingScore,maxAttempts});}
 return <form className="space-y-4 rounded border p-4" onSubmit={submit}><h3 className="font-semibold">{standalone?'编辑独立试卷（单选题）':'配置课程考试'}</h3><p className="text-xs text-slate-500">{standalone?'试卷草稿可修改，定版后需创建新版本。请明确设置及格线与次数；本页尚不派发考试。':'每个课程版本保存一份固定试卷。保存前请校对题目与答案。'}</p><div className="grid grid-cols-2 gap-3"><label>及格分数<Input type="number" required min={1} max={100} value={passingScore} onChange={e=>setScore(Number(e.target.value))}/></label><label>最多考试次数<Input type="number" required min={1} max={10} value={maxAttempts} onChange={e=>setMax(Number(e.target.value))}/></label></div>{questions.map((q,i)=><fieldset key={i} className="space-y-2 border-t pt-3"><legend>第 {i+1} 题</legend><textarea className="w-full rounded border p-2" placeholder="请输入题目（至少5字）" aria-label={'第'+(i+1)+'题题目'} minLength={5} maxLength={4000} required value={q.prompt} onChange={e=>setQuestions(questions.map((x,j)=>j===i?{...x,prompt:e.target.value}:x))}/>{q.options.map((o,k)=><Input key={k} aria-label={`第 ${i+1} 题选项 ${k+1}`} placeholder={`选项 ${k+1}`} required maxLength={200} value={o} onChange={e=>setQuestions(questions.map((x,j)=>j===i?{...x,options:x.options.map((v,l)=>l===k?e.target.value:v)}:x))}/>)}<Select value={String(q.correct)} onValueChange={v=>setQuestions(questions.map((x,j)=>j===i?{...x,correct:Number(v)}:x))}><SelectTrigger aria-label={'第'+(i+1)+'题正确答案'}><SelectValue/></SelectTrigger><SelectContent>{q.options.map((_,k)=><SelectItem key={k} value={String(k)}>正确答案：选项 {k+1}</SelectItem>)}</SelectContent></Select>{questions.length>1&&<Button type="button" variant="ghost" onClick={()=>setQuestions(questions.filter((_,j)=>j!==i))}>删除此题</Button>}</fieldset>)}<div className="flex gap-3"><Button type="button" variant="outline" disabled={questions.length>=20||busy} onClick={()=>setQuestions([...questions,{prompt:'',options:['','','',''],correct:0}])}>增加题目</Button><Button disabled={busy}>保存试卷</Button></div></form>;
}
export function ExamAttempt({exam,enrollment,attempts,send,busy,own,standalone=false}:{standalone?:boolean;exam:DevelopmentRecord;enrollment:DevelopmentRecord;attempts:DevelopmentRecord[];send:Send;busy:boolean;own:boolean}){
 const [answers,setAnswers]=useState<Record<number,number>>({});const passed=attempts.some(a=>a.payload.passed),remaining=(exam.payload.maxAttempts??0)-attempts.length;
 return <section className="space-y-4 rounded border p-4"><h3 className="font-semibold">{standalone?'独立考试':'课程考试'}</h3><p>及格线 {exam.payload.passingScore} 分 · 剩余 {remaining} 次</p>{attempts.map(a=><p key={a.id}>{a.createdAt} · {a.payload.score} 分 · {a.payload.passed?'通过':'未通过'}</p>)}{own&&!passed&&remaining>0&&['active','returned'].includes(enrollment.status)&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();send({action:'attemptExam',enrollmentId:enrollment.id,answers:exam.payload.questions!.map((_,i)=>answers[i]??-1)});}}>{exam.payload.questions?.map((q,i)=><fieldset key={i} className="space-y-2"><legend className="mb-2">{i+1}. {q.prompt}</legend><Select value={answers[i]===undefined?'none':String(answers[i])} onValueChange={v=>setAnswers({...answers,[i]:Number(v)})}><SelectTrigger aria-label={'第'+(i+1)+'题答案'}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{q.options.map((o,k)=><SelectItem value={String(k)} key={k}>{o}</SelectItem>)}</SelectContent></Select></fieldset>)}<Button disabled={busy||Object.keys(answers).length!==exam.payload.questions?.length}>提交试卷</Button></form>}{passed&&<p className="text-green-700">{standalone?'独立考试已通过；不自动记为课程或计划完成。':'考试已通过，可继续提交学习实践成果。'}</p>}</section>;
}
