import {recruitmentTargetCurrent} from '@/lib/hris/recruitment-status';
import {visibleRecord} from '@/lib/hris/development';
import {assertStaffingCapacity} from '@/lib/hris/workforce';
import {z} from 'zod';
import {developmentContext,visibleDevelopment,saveDevelopment,saveDevelopmentMany} from '@/lib/hris/development-repository';
import {applyRecruitment,recruitmentCommand} from '@/lib/hris/recruitment';
import {applyCommand} from '@/lib/hris/model';
import {stateStatements} from '@/lib/hris/repository';
import {json,failure,readBody,HttpError} from '@/lib/hris/http';
export async function GET(){try{const ctx=await developmentContext(['interviewAppointment','interviewDefinition','recruitmentJob','requisition', 'candidate', 'interview', 'staffingPlan']);const visible=visibleDevelopment(ctx);return json({targetValidity:Object.fromEntries(visible.filter(r=>r.kind==='candidate').map(r=>{const original=ctx.records.find(x=>x.id===r.id)!;return [r.id,{position:recruitmentTargetCurrent(ctx.state,original,false),offer:recruitmentTargetCurrent(ctx.state,original)}]})),records:visible.filter(r=>['interviewAppointment','interviewDefinition','recruitmentJob','requisition','candidate','interview'].includes(r.kind)),revision:ctx.row.revision,role:ctx.member.role,userId:ctx.member.userId,permissions:{viewEmail:ctx.member.role==='admin'||!!ctx.member.viewEmail,viewLevel:ctx.member.role==='admin'||!!ctx.member.viewLevel}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const body=z.object({revision:z.number().int().nonnegative(),command:z.unknown()}).parse(await readBody(request,65536));const command=recruitmentCommand.parse(body.command),rawKey=request.headers.get('Idempotency-Key'),key=rawKey===null?undefined:z.string().regex(/^[A-Za-z0-9_-]{8,100}$/).parse(rawKey);if(key&&!['requisition','candidate','interview','structuredInterview'].includes(command.action))throw new HttpError(400,'此请求键仅用于新增需求、候选人和面试记录');const hash=key?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(command))))).map(v=>v.toString(16).padStart(2,'0')).join(''):undefined;
 const ctx=await developmentContext(['interviewAppointment','interviewDefinition','recruitmentJob','requisition', 'candidate', 'interview', 'staffingPlan']);if(key){if(!(['interview','structuredInterview'].includes(command.action)?['admin','hr','manager']:['admin','hr']).includes(ctx.member.role))throw new HttpError(403,'当前角色不能办理或恢复此创建请求');const previous=ctx.records.find(r=>r.payload.creationRequest?.key===key&&r.payload.creationRequest.actor===ctx.member.userId);if(previous){if(!visibleRecord(previous,ctx.records,ctx.state,ctx.member))throw new HttpError(403,'原请求记录已不在当前可访问范围');if(previous.payload.creationRequest!.hash!==hash)throw new HttpError(409,'同一请求键的内容已经改变，请先核对原记录再发起新请求');return json({id:previous.id,revision:ctx.row.revision,originalRevision:previous.payload.creationRequest!.revision,replayed:true});}}
 const {record,employeeInput,completedAppointment}=applyRecruitment(ctx.records,ctx.state,ctx.member,command);if(key)record.payload.creationRequest={key,hash:hash!,actor:ctx.member.userId,revision:body.revision+1};let extra:((token:string)=>D1PreparedStatement[])|undefined;if(employeeInput){const next=applyCommand(ctx.state,employeeInput,undefined,ctx.member.userId);assertStaffingCapacity(ctx.records,ctx.state,next);const employee=next.employees.find(e=>!ctx.state.employees.some(old=>old.id===e.id))!;record.payload.hiredEmployeeId=employee.id;extra=token=>stateStatements(ctx.db,ctx.member.tenantId,token,ctx.state,next,ctx.member.userId,record.updatedAt);}if(completedAppointment)await saveDevelopmentMany(ctx,body.revision,[record,completedAppointment],'招聘：结构化排期评价');else await saveDevelopment(ctx,body.revision,record,'招聘：'+String((body.command as {action:string}).action),extra);return json({id:record.id,revision:body.revision+1});}catch(e){return failure(e);}}
