'use client';
import {useEffect,useState} from 'react';
import scope from '@/docs/delivery/Scope_Register.json';
import queue from '@/docs/delivery/Module_Queue.json';
import evidence from '@/lib/delivery/evidence.json';
import {aggregate,statuses} from '@/lib/delivery/aggregate.mjs';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
const model=aggregate(scope,queue);
const stamp=(s:string)=>new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+' 北京时间';
export default function DeliveryDashboard(){
 const [tab,setTab]=useState('overview'),[query,setQuery]=useState(''),[status,setStatus]=useState('全部');
 useEffect(()=>{const sync=()=>{if(location.hash){setTab('register');requestAnimationFrame(()=>document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView());}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 useEffect(()=>{const timer=setInterval(async()=>{try{const response=await fetch('/api/delivery-evidence',{cache:'no-store'});if(response.ok){const next=await response.json();if(next&&typeof next==='object'&&'generatedAt' in next&&typeof next.generatedAt==='string'&&next.generatedAt!==evidence.generatedAt)location.reload();}}catch{/* Keep the last verified snapshot on network failure. */}},60000);return()=>clearInterval(timer)},[]);
 const jump=(id:string)=>{setQuery('');setTab('register');location.hash=id;setTimeout(()=>document.getElementById(id)?.scrollIntoView({block:'start'}),50)};
 const tasks=model.tasks.filter(t=>(status==='全部'||t.status===status)&&[t.id,t.title,...t.criteria.map(c=>c.text)].join(' ').includes(query));
 return <Tabs value={tab} onValueChange={setTab} className="space-y-5"><TabsList aria-label="建设交付视图"><TabsTrigger value="overview">总览</TabsTrigger><TabsTrigger value="register">建设清单</TabsTrigger></TabsList>
 <TabsContent value="overview" className="space-y-5">
 <section className="panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">项目建设总进度</h2><p className="mt-2 text-sm text-slate-600">已验收子任务 / 已登记验收子任务</p><p className="my-3 text-3xl font-semibold">{model.accepted} / {model.total} <span className="text-blue-700">{model.percent??'—'}%</span></p></div><Button variant="outline" onClick={()=>location.reload()}>刷新已发布数据</Button></div><Progress value={model.percent??0} aria-label="已登记子任务验收进度"/><p className="mt-3 text-sm text-amber-800">{scope.acceptancePolicy.note}</p><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-5">{statuses.map(s=><button key={s} className="rounded border p-3 text-left hover:bg-slate-50" onClick={()=>setStatus(s)}><span className="text-sm">{s}</span><strong className="mt-1 block text-xl">{model.counts[s]}</strong></button>)}</div></section>
 <section className="grid gap-3 md:grid-cols-3">{model.phases.map(p=><div key={p.id} className={'panel '+(p.id==='P3'?'border-blue-500 bg-blue-50/40':'')}><h3 className="font-semibold">{p.id} · {p.id==='P1'?'原站盘点':p.id==='P2'?'设计与基础':'业务模块（重点）'}</h3><p className="my-3 text-2xl">{p.total?`${p.accepted} / ${p.total} · ${p.percent}%`:'待登记验收项'}</p><Progress value={p.percent??0} aria-label={p.id+'验收进度'}/></div>)}</section>
 <section className="panel"><h2 className="text-lg font-semibold">P3 模块 → 子任务 → 验收项</h2><div className="my-4 flex flex-wrap gap-3"><Input aria-label="搜索子任务" placeholder="搜索编号或验收内容" value={query} onChange={e=>setQuery(e.target.value)} className="max-w-md"/><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="任务状态" className="w-36"><SelectValue/></SelectTrigger><SelectContent>{['全部',...statuses].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>{scope.modules.map(m=>{const children=tasks.filter(t=>t.phase==='P3'&&t.moduleId===m.id);if(!children.length&&(query||status!=='全部'))return null;return <details key={m.id} className="border-b py-3" open={m.id==='M16'||undefined}><summary className="cursor-pointer font-semibold">{m.id} · {m.name} <span className="text-sm font-normal text-slate-500">{children.filter(t=>t.accepted).length}/{model.tasks.filter(t=>t.phase==='P3'&&t.moduleId===m.id).length} 已验收</span></summary>{children.map(t=><div key={t.id} className="my-3 border-l-2 border-blue-200 pl-4"><button className="text-left text-sm font-semibold text-blue-700 underline" onClick={()=>jump('task-'+t.id)}>{t.id} · {t.title}</button><span className="ml-3 text-sm">{t.status}</span><ul className="my-2 list-disc space-y-2 pl-5 text-sm">{t.criteria.map(c=><li key={c.id}>{c.id} · {c.text}<span className="text-slate-500">（{t.accepted?'已验收':'待独立验收'}）</span></li>)}</ul><p className="text-sm text-slate-500">下一步：{t.execution?.next??'依据现有证据完成业务核验并登记验收人、时间与证据'}</p></div>)}<p className="my-3 text-sm text-slate-600">尚需细化的保留范围：{m.remaining}</p><button className="text-sm text-blue-700 underline" onClick={()=>jump('scope-'+m.id)}>查看 {m.name} 建设清单</button></details>})}{tasks.filter(t=>t.phase==='P3').length===0&&(query||status!=='全部')&&<p className="py-4 text-sm">没有匹配的 P3 子任务。</p>}</section>
 <div className="grid gap-5 lg:grid-cols-2"><section className="panel"><h2 className="text-lg font-semibold">最近增量开发</h2><p className="my-2 text-sm text-slate-500">完成时间按 Git 提交时间记录；提交不等于验收或发布。</p>{evidence.commits.map(c=><div key={c.sha} className="border-b py-3"><p className="text-sm font-medium">{c.title}</p><p className="my-1 break-all font-mono text-xs">{c.sha}</p><p className="text-sm text-slate-500">{stamp(c.time)}</p></div>)}</section>
 <section className="panel"><h2 className="text-lg font-semibold">私有发布与测试证据</h2><p className="my-3 text-sm">{evidence.deployment.environment}</p><p className="text-sm text-amber-800">{evidence.deployment.note}</p><p className="mt-3 text-sm">最近已核验发布：v{evidence.deployment.verified.version} · {evidence.deployment.verified.status}</p><p className="my-2 text-sm">{stamp(evidence.deployment.verified.time)}</p><p className="break-all font-mono text-xs">{evidence.deployment.verified.commit}</p><p className="mt-4 text-sm">最近一批测试（范围见下）：{evidence.tests.passed}/{evidence.tests.tests}，失败 {evidence.tests.failed}</p><p className="mt-2 break-all text-sm text-slate-500">{evidence.tests.path} · {evidence.tests.note}</p><p className="mt-4 text-sm">历史构建证据：{evidence.verification.build.status} · 类型检查：{evidence.verification.typecheck}</p><p className="mt-2 text-sm text-slate-500">{evidence.verification.limitation}</p><details className="mt-3 text-sm"><summary className="cursor-pointer">各批测试证据（不累加重复场景）</summary>{evidence.testRuns.map(run=><p key={run.path} className="my-3 break-words">{stamp(run.completedAt)} · {run.passed}/{run.tests}，失败{run.failed} · {run.scope} · {run.path}</p>)}</details><p className="mt-4 text-sm">最近保存版本：v{evidence.deployment.latestSavedVersion}</p></section></div>
 <section className="panel"><h2 className="text-lg font-semibold">阻塞、恢复条件与下一步</h2>{model.blockers.map(b=><div key={b.id} className="my-3 border-l-2 border-amber-500 pl-4"><p className="font-medium">{b.id} · {b.status}</p><p className="mt-2 text-sm">{b.next}</p><p className="mt-2 text-sm">恢复条件：{b.recoveryCondition??'按上述下一步解除阻塞并重新保留验证证据；未解除前不计完成。'}</p></div>)}<details className="mt-4"><summary className="cursor-pointer text-sm">查看执行检查点原文</summary><pre className="mt-3 whitespace-pre-wrap break-words text-sm">{evidence.checkpoint}</pre></details></section>
 <section className="panel text-sm"><h2 className="font-semibold">刷新与数据来源</h2><p className="my-2">证据快照生成：{stamp(evidence.generatedAt)}。构建时聚合，每60秒检测新发布并自动刷新；不会读取云端未发布的工作区。</p><p className="mb-3">建设清单是范围和验收台账；总览聚合台账、队列、检查点、Git、测试及部署证据，不独立维护任务状态。</p>{evidence.sources.map(s=><p className="my-2 break-all" key={s.path}>{s.path}<span className="block font-mono text-xs text-slate-500">SHA-256 {s.sha256}</span></p>)}</section>
 </TabsContent>
 <TabsContent value="register" className="space-y-4"><section className="panel"><h2 className="text-lg font-semibold">全量范围与验收台账 · {scope.modules.length} 组</h2><Input aria-label="搜索建设清单" placeholder="搜索模块或子任务" className="my-3 max-w-md" value={query} onChange={e=>setQuery(e.target.value)}/><p className="text-sm text-slate-600">范围及验收事实源：Scope_Register.json；编号链接可直接定位。</p></section>{scope.modules.filter(m=>[m.id,m.name,m.scope,m.remaining,...model.tasks.filter(t=>t.moduleId===m.id).map(t=>t.title+' '+t.id)].join(' ').includes(query)).map(m=><section id={'scope-'+m.id} key={m.id} className="panel scroll-mt-5"><h3 className="text-lg font-semibold">{m.id} · {m.name}</h3><dl className="my-4 grid gap-2 text-sm"><dt className="font-semibold">范围 / 需求核实</dt><dd>{m.scope} · {m.requirements}</dd><dt className="font-semibold">已开发范围</dt><dd>{m.developed}</dd><dt className="font-semibold">保留范围</dt><dd>{m.remaining}</dd><dt className="font-semibold">测试 / 生产验收</dt><dd>{m.tested} · {m.productionAccepted}</dd></dl>{model.tasks.filter(t=>t.moduleId===m.id).map(t=><div id={'task-'+t.id} key={t.id} className="scroll-mt-5 border-t py-3 text-sm"><h4 className="font-semibold">{t.id} · {t.title} · {t.status}</h4>{t.criteria.map(c=><p className="mt-2" key={c.id}>{c.id} · {c.text}</p>)}<dl className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(t.dimensions??{requirements:m.requirements,development:m.developed,testing:m.tested,production:m.productionAccepted}).map(([key,value])=><div key={key}><dt className="font-medium">{{requirements:"需求核实",development:"功能开发",testing:"测试证据",production:"生产验收"}[key]}</dt><dd className="mt-1 text-slate-600">{value}</dd></div>)}</dl><p className="mt-2 text-slate-500">事实来源：{t.source}</p></div>)}</section>)}</TabsContent></Tabs>;
}
