'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={today:string;records:R[];readiness:{id:string;items:NonNullable<R['payload']['qualificationProof']>}[];revision:number;role:string;employeeId:string|null;userId:string};
const statuses:Record<string,string>={draft:'草稿',published:'已发布',archived:'已停用',submitted:'待评审',certified:'已认证',rejected:'未通过',withdrawn:'已撤回',revoked:'已撤销'};
const labels:Record<string,string>={standard:'新建资格标准',apply:'申请内部认证',review:'独立评审',withdraw:'撤回申请',revoke:'撤销认证'};
export default function Qualifications(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[tab,setTab]=useState('qualificationStandard'),[form,setForm]=useState<Record<string,string>|null>(null),[requirements,setRequirements]=useState([{standardId:'none',target:3}]),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/qualifications',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),manager=hr||data?.role==='manager',employee=(id:string|null)=>core?.employees.find(e=>e.id===id)?.name??'—',record=data?.records.find(r=>r.id===selected),proof=(r:R)=>data?.readiness.find(x=>x.id===r.id)?.items??r.payload.qualificationProof??[];
 function open(action:string,r?:R,extra:Record<string,string>={}){setError('');setForm({action,id:r?.id??'',standardId:r?.kind==='qualificationStandard'?r.id:'none',employeeId:data?.employeeId??'none',...extra});if(action==='standard')setRequirements([{standardId:'none',target:3}]);}
 async function send(command:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/qualifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('资格记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;const c:Record<string,unknown>={...form};if(!c.id)delete c.id;if(form.action==='standard')c.requirements=requirements;if(form.action==='review'){c.accepted=form.accepted==='true';if(!c.validUntil)delete c.validUntil;}send(c);}
 function pick(value:string,change:(s:string)=>void,options:string[][],label:string){return <Select value={value||'none'} onValueChange={change}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>;}
 function actions(r:R){const independent=manager&&r.employeeId!==data?.employeeId&&r.createdBy!==data?.userId;return <div className="flex flex-wrap gap-2"><Button variant="ghost" size="sm" onClick={()=>setSelected(r.id)}>详情</Button>{r.kind==='qualificationStandard'?<>{hr&&r.status==='draft'&&<Button size="sm" disabled={busy} onClick={()=>send({action:'publishStandard',id:r.id})}>发布</Button>}{hr&&r.status==='published'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>send({action:'archiveStandard',id:r.id})}>停用</Button>}{r.status==='published'&&(hr||data?.employeeId)&&<Button size="sm" onClick={()=>open('apply',r)}>申请认证</Button>}</>:<>{r.status==='submitted'&&r.createdBy===data?.userId&&<Button size="sm" variant="outline" onClick={()=>open('withdraw',r)}>撤回</Button>}{r.status==='submitted'&&independent&&<><Button size="sm" disabled={!proof(r).length||!proof(r).every(p=>p.met)} onClick={()=>open('review',r,{accepted:'true'})}>通过认证</Button><Button size="sm" variant="outline" onClick={()=>open('review',r,{accepted:'false'})}>不通过</Button></>}{r.status==='certified'&&hr&&independent&&<Button size="sm" variant="outline" onClick={()=>open('revoke',r)}>撤销</Button>}</>}</div>;}
 const rows=(data?.records??[]).filter(r=>r.kind===tab&&(r.payload.name+' '+r.payload.code+' '+employee(r.employeeId)+' '+r.payload.certificateNumber).includes(search)).reverse();
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/development" className="text-link">能力标准与评估</Link><Link href="/learning" className="text-link">学习发展</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">QUALIFICATIONS</div><h1>任职资格</h1><p className="text-sm text-slate-500 mt-2">依据指定版本的能力标准与评估记录开展内部认证。缺少评估不计为零分，认证不自动调整岗位或职级。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}<section className="panel"><div className="section-head gap-4"><Tabs value={tab} onValueChange={v=>{setTab(v);setPage(1);}}><TabsList><TabsTrigger value="qualificationStandard">资格标准</TabsTrigger><TabsTrigger value="qualificationApplication">申请与认证</TabsTrigger></TabsList></Tabs>{hr&&tab==='qualificationStandard'&&<Button onClick={()=>open('standard')}>新建版本</Button>}</div><div className="filters"><Input aria-label="搜索资格记录" className="max-w-md" placeholder="搜索名称、员工、编码或认证编号" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><Table><TableHeader><TableRow>{['名称 / 员工','版本 / 认证信息','状态','操作'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*15,page*15).map(r=><TableRow key={r.id}><TableCell>{r.payload.name}<p className="text-sm text-slate-500">{r.employeeId?employee(r.employeeId):r.payload.code}</p></TableCell><TableCell>V{r.payload.version}{r.payload.certificateNumber&&<p className="text-sm break-all">{r.payload.certificateNumber}</p>}{r.payload.validUntil&&<p className="text-sm">有效至 {r.payload.validUntil}</p>}{r.status==='submitted'&&<p className="text-sm text-slate-500">已达标 {proof(r).filter(x=>x.met).length} / {proof(r).length}</p>}</TableCell><TableCell><Badge variant="outline">{statuses[r.status]}</Badge>{r.status==='certified'&&r.payload.validUntil&&r.payload.validUntil<data!.today&&<p className="text-sm text-amber-700">已过有效期</p>}</TableCell><TableCell>{actions(r)}</TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">暂无可见资格记录</p>}<div className="flex justify-end items-center gap-3 mt-4"><span className="text-sm">{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{labels[form?.action??'']}</DialogTitle><DialogDescription>{form?.action==='standard'?'同一编码建立新的不可变版本；每项要求关联明确的能力标准版本。':'请提交可复核的真实依据。内部认证不代替外部执业许可。'}</DialogDescription></DialogHeader>{error&&<p className="text-red-700" role="alert">{error}</p>}{form&&<form onSubmit={submit} className="edit-form">{form.action==='standard'?<><label className="field"><span>资格编码</span><Input required value={form.code??''} onChange={e=>setForm({...form,code:e.target.value})}/></label><label className="field"><span>资格名称</span><Input required value={form.name??''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>资格规则与适用范围</span><textarea required minLength={5} rows={3} value={form.criteria??''} onChange={e=>setForm({...form,criteria:e.target.value})}/></label>{requirements.map((q,i)=><div key={i} className="grid gap-3 sm:grid-cols-[1fr_110px_auto] items-end border rounded p-3"><label className="field"><span>能力标准版本</span>{pick(q.standardId,v=>setRequirements(requirements.map((r,j)=>i===j?{...r,standardId:v}:r)),(data?.records??[]).filter(r=>r.kind==='standard').map(r=>[r.id,`${r.payload.name} V${r.payload.version}`]),'能力标准版本')}</label><label className="field"><span>要求等级</span><Input type="number" min={1} max={5} required value={q.target} onChange={e=>setRequirements(requirements.map((r,j)=>i===j?{...r,target:Number(e.target.value)}:r))}/></label><Button type="button" variant="ghost" disabled={requirements.length<=1} onClick={()=>setRequirements(requirements.filter((_,j)=>i!==j))}>移除</Button></div>)}<Button type="button" variant="outline" disabled={requirements.length>=20} onClick={()=>setRequirements([...requirements,{standardId:'none',target:3}])}>添加能力要求</Button></>:<>{form.action==='apply'&&<label className="field"><span>申请员工</span>{pick(form.employeeId,v=>setForm({...form,employeeId:v}),(core?.employees??[]).filter(e=>e.status!=='离职'&&(hr||e.id===data?.employeeId)).map(e=>[e.id,e.name]),'申请员工')}</label>}{form.action==='review'&&form.accepted==='true'&&<label className="field"><span>有效截止日期（选填）</span><Input type="date" value={form.validUntil??''} onChange={e=>setForm({...form,validUntil:e.target.value})}/></label>}<label className="field"><span>申请或评审依据</span><textarea required minLength={5} maxLength={3000} rows={4} value={form.evidence??''} onChange={e=>setForm({...form,evidence:e.target.value})}/></label></>}<Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{record?.payload.name}</DialogTitle><DialogDescription>标准版本 V{record?.payload.version} · {record?statuses[record.status]:''}</DialogDescription></DialogHeader>{record&&<div className="space-y-4"><p className="whitespace-pre-wrap">{record.payload.criteria??String(record.payload.qualificationSnapshot?.criteria??'')}</p><Table><TableHeader><TableRow><TableHead>能力及版本</TableHead><TableHead>要求</TableHead><TableHead>实际</TableHead></TableRow></TableHeader><TableBody>{(record.kind==='qualificationStandard'?record.payload.qualificationRequirements??[]:proof(record)).map((q,i)=><TableRow key={i}><TableCell>{q.name} V{q.version}</TableCell><TableCell>{q.target}</TableCell><TableCell>{'rating'in q?q.rating===null?'未评定':String(q.rating):'—'}</TableCell></TableRow>)}</TableBody></Table>{Object.entries({申请依据:record.payload.evidence,评审意见:record.payload.verification,撤销依据:record.payload.revocationReason,认证编号:record.payload.certificateNumber}).filter(([,v])=>v).map(([k,v])=><p key={k} className="whitespace-pre-wrap"><span className="text-slate-500">{k}：</span>{v}</p>)}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></div>}</DialogContent></Dialog>
 </main>;
}
