'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import ProcessHistory from '../development/process-history';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {RecruitmentJobDetails} from '@/lib/hris/recruitment-jobs';
const status:Record<string,string>={draft:'草稿',active:'内部启用',archived:'已归档'};
const salary=(d?:RecruitmentJobDetails)=>!d?'—':d.salary.mode==='negotiable'?'面议':`${(d.salary.minCents/100).toFixed(2)}–${(d.salary.maxCents/100).toFixed(2)} 元/月`;
export default function Workspace(){
 const [data,setData]=useState<{records:R[];revision:number;role:string}|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(1);
 async function load(){try{const r=await fetch('/api/recruitment-jobs',{cache:'no-store'}),d=await r.json() as {records:R[];revision:number;role:string;error?:string};if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),get=(id?:string|null)=>data?.records.find(r=>r.id===id),detail=get(selected);
 function open(r?:R){const d=r?.payload.jobDetails;setError('');setForm({id:r?.id??'',requisitionId:r?.referenceId??'none',title:r?.payload.title??'',category:d?.category??'',employment:d?.employment??'',location:d?.location??'',address:d?.address??'',education:d?.education??'',experience:d?.experience??'',duties:d?.duties??'',qualifications:d?.qualifications??'',salaryMode:d?.salary.mode??'negotiable',min:d?.salary.mode==='range'?String(d.salary.minCents/100):'',max:d?.salary.mode==='range'?String(d.salary.maxCents/100):''});}
 async function send(command:unknown){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/recruitment-jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('内部招聘职位已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;const details={category:form.category,employment:form.employment,location:form.location,address:form.address,education:form.education,experience:form.experience,duties:form.duties,qualifications:form.qualifications,salary:form.salaryMode==='negotiable'?{mode:'negotiable'}:{mode:'range',minCents:Math.round(Number(form.min)*100),maxCents:Math.round(Number(form.max)*100),currency:'CNY',period:'month'}};send({action:form.id?'edit':'create',...(form.id?{id:form.id}:{requisitionId:form.requisitionId}),title:form.title,details});}
 const rows=(data?.records??[]).filter(r=>r.kind==='recruitmentJob'&&(filter==='all'||r.status===filter)&&`${r.payload.title} ${r.payload.jobDetails?.location} ${get(r.referenceId)?.payload.title}`.toLowerCase().includes(search.toLowerCase())).reverse();
 return <main className="main-content mx-auto max-w-7xl"><Link href="/recruitment" className="text-link">招聘需求与候选人</Link><div className="page-head mt-5"><div><h1>内部招聘职位</h1><p className="mt-2 text-sm text-slate-500">关联已批准需求，明确职责、条件和薪资范围。启用后供系统内登记候选人；不会发布外部广告。</p></div>{hr&&<Button disabled={busy} onClick={()=>open()}>新建职位</Button>}</div>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel"><div className="filters"><Input className="max-w-md" aria-label="搜索内部招聘职位" placeholder="职位、地点或需求" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><Select value={filter} onValueChange={v=>{setFilter(v);setPage(1);}}><SelectTrigger className="w-40" aria-label="职位状态"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部状态</SelectItem>{Object.entries(status).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div><Table><TableHeader><TableRow>{['职位 / 地点','关联需求','薪资范围','版本 / 状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*12,page*12).map(r=><TableRow key={r.id}><TableCell><b>{r.payload.title}</b><p>{r.payload.jobDetails?.location}</p></TableCell><TableCell>{get(r.referenceId)?.payload.title}<p className="text-sm text-slate-500">共用需求人数 {get(r.referenceId)?.payload.headcount??'—'}</p></TableCell><TableCell>{salary(r.payload.jobDetails)}</TableCell><TableCell>v{r.payload.version} · {status[r.status]}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setSelected(r.id)}>详情</Button>{hr&&r.status==='draft'&&<><Button variant="outline" disabled={busy} onClick={()=>open(r)}>编辑</Button><Button disabled={busy} onClick={()=>send({action:'activate',id:r.id})}>内部启用</Button></>}{hr&&r.status==='active'&&!data?.records.some(x=>x.kind==='recruitmentJob'&&x.payload.definitionRootId===r.payload.definitionRootId&&(x.status==='draft'||(x.status==='active'&&x.payload.version!>r.payload.version!)))&&<Button variant="outline" disabled={busy} onClick={()=>send({action:'revise',id:r.id})}>新版本</Button>}{hr&&r.status!=='archived'&&<Button variant="ghost" disabled={busy} onClick={()=>send({action:'archive',id:r.id})}>归档</Button>}</div></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="p-6 text-slate-500">暂无可见职位</p>}<div className="flex justify-end items-center gap-3 p-4"><span>{rows.length} 条</span><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*12>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>招聘职位草稿</DialogTitle><DialogDescription>启用版本不能覆盖，后续修订不改变已关联候选人的职位快照。当前沿用面试、录用和入职办理流程。</DialogDescription></DialogHeader>{form&&<form className="space-y-4" onSubmit={submit}>{error&&<p role="alert" className="text-red-700">{error}</p>}<label className="field"><span>已批准招聘需求</span><Select disabled={!!form.id} value={form.requisitionId} onValueChange={v=>setForm({...form,requisitionId:v,title:form.title||get(v)?.payload.title||''})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择需求</SelectItem>{data?.records.filter(r=>r.kind==='requisition'&&(r.status==='active'||r.id===form.requisitionId)).map(r=><SelectItem key={r.id} value={r.id}>{r.payload.title}</SelectItem>)}</SelectContent></Select></label>{[['title','职位名称'],['category','招聘类别'],['employment','工作性质'],['location','工作地点'],['address','详细地址（可选）'],['education','学历要求（可选）'],['experience','工作经验（可选）']].map(([k,l])=><label className="field" key={k}><span>{l}</span><Input required={['title','category','employment','location'].includes(k)} maxLength={['address','education','experience'].includes(k)?500:200} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}{[['duties','工作职责'],['qualifications','任职资格']].map(([k,l])=><label className="field" key={k}><span>{l}</span><textarea className="w-full rounded border p-2" rows={5} required minLength={5} maxLength={10000} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="field"><span>薪资说明</span><Select value={form.salaryMode} onValueChange={v=>setForm({...form,salaryMode:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="negotiable">面议</SelectItem><SelectItem value="range">人民币月薪范围</SelectItem></SelectContent></Select></label>{form.salaryMode==='range'&&<div className="form-grid">{[['min','最低月薪（元）'],['max','最高月薪（元）']].map(([k,l])=><label className="field" key={k}><span>{l}</span><Input type="number" required min={0} step="0.01" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div>}<div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setForm(null)}>取消</Button><Button disabled={busy||form.requisitionId==='none'}>保存草稿</Button></div></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{detail?.payload.title} · v{detail?.payload.version}</DialogTitle><DialogDescription>{detail?status[detail.status]:''} · 不包含外部广告发布</DialogDescription></DialogHeader>{detail?.payload.jobDetails&&<div className="space-y-3"><p>{detail.payload.jobDetails.category} · {detail.payload.jobDetails.employment} · {detail.payload.jobDetails.location}</p><p>{salary(detail.payload.jobDetails)}</p>{Object.entries({详细地址:detail.payload.jobDetails.address,学历要求:detail.payload.jobDetails.education,工作经验:detail.payload.jobDetails.experience,工作职责:detail.payload.jobDetails.duties,任职资格:detail.payload.jobDetails.qualifications}).filter(([,v])=>!!v).map(([l,v])=><div key={l}><b>{l}</b><p className="whitespace-pre-wrap">{v}</p></div>)}<p className="text-sm text-slate-500">候选人使用登记时的职位版本，归档不删除已登记人员的历史资料。</p><ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/></div>}</DialogContent></Dialog></main>;
}
