'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
const categories={education:'教育经历',employment:'工作履历',project:'项目经历'};
type Data={records:R[];employees:{id:string;name:string;code:string}[];revision:number;role:string;employeeId:string|null};
type Form={action:'save'|'cancel';id?:string;employeeId:string;category:string;institution:string;title:string;startMonth:string;endMonth:string;ongoing:boolean;description:string;evidence:string};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Form|null>(null),[detail,setDetail]=useState<string|null>(null),[search,setSearch]=useState(''),[page,setPage]=useState(1),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/employee-experiences',{cache:'no-store'}),d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),employee=(id:string|null)=>data?.employees.find(e=>e.id===id),selected=data?.records.find(r=>r.id===detail),rows=(data?.records??[]).filter(r=>[employee(r.employeeId)?.name,employee(r.employeeId)?.code,r.payload.title,r.payload.institution,categories[r.payload.experienceCategory!]].join(' ').includes(search)).slice().reverse();
 function open(r?:R,action:'save'|'cancel'='save'){setError('');setForm({action,id:r?.id,employeeId:r?.employeeId??'',category:r?.payload.experienceCategory??'education',institution:r?.payload.institution??'',title:r?.payload.title??'',startMonth:r?.payload.startMonth??'',endMonth:r?.payload.endMonth??'',ongoing:r?.payload.ongoing??false,description:r?.payload.description??'',evidence:''});}
 async function submit(e:FormEvent){e.preventDefault();if(!form||!data)return;setBusy(true);setError('');try{const command=form.action==='cancel'?{action:'cancel',id:form.id,evidence:form.evidence}:{...form,endMonth:form.ongoing?undefined:form.endMonth};const r=await fetch('/api/employee-experiences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('经历已保存，原版本和办理历史保留。');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/employees" className="text-link">员工名册</Link><Link href="/self-service" className="text-link">员工自助</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">EMPLOYEE HISTORY</div><h1>人员经历</h1><p className="mt-2 text-sm text-slate-500">HR按资料登记教育、工作和项目经历，员工本人可查阅。登记不代表外部核验，不自动改变劳动关系、岗位或资格。</p></div>{hr&&<Button onClick={()=>open()}>新增经历</Button>}</div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}<section className="panel"><Input aria-label="搜索人员经历" placeholder="搜索姓名、工号、机构或经历名称" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><Table><TableHeader><TableRow>{['员工','类别与名称','学校 / 单位 / 项目组织','起止月份','状态与版本','操作'].map(c=><TableHead key={c}>{c}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice((page-1)*20,page*20).map(r=><TableRow key={r.id}><TableCell>{employee(r.employeeId)?.name}<p className="text-xs text-slate-500">{employee(r.employeeId)?.code}</p></TableCell><TableCell>{categories[r.payload.experienceCategory!]}<p>{r.payload.title}</p></TableCell><TableCell>{r.payload.institution}</TableCell><TableCell>{r.payload.startMonth} 至 {r.payload.ongoing?'今':r.payload.endMonth}</TableCell><TableCell>{r.status==='active'?'有效登记':'已作废'} · V{r.payload.version}</TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={()=>setDetail(r.id)}>详情</Button>{hr&&r.status==='active'&&<><Button size="sm" variant="outline" onClick={()=>open(r)}>更正</Button><Button size="sm" variant="ghost" onClick={()=>open(r,'cancel')}>作废</Button></>}</div></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty">暂无可见经历记录</p>}<div className="flex items-center justify-end gap-3 mt-4"><span>{rows.length}条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><span>第{page}页</span><Button variant="outline" disabled={page*20>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{form?.action==='cancel'?'作废经历':form?.id?'更正经历':'新增经历'}</DialogTitle><DialogDescription>更正保留原版本；不能更换所属员工或类别。起止按月份登记，进行中不填结束月份。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='save'&&<><label className="field"><span>员工</span><Select disabled={!!form.id} value={form.employeeId||'none'} onValueChange={v=>setForm({...form,employeeId:v})}><SelectTrigger aria-label="员工"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{data?.employees.map(e=><SelectItem key={e.id} value={e.id}>{e.name} · {e.code}</SelectItem>)}</SelectContent></Select></label><label className="field"><span>类别</span><Select disabled={!!form.id} value={form.category} onValueChange={v=>setForm({...form,category:v})}><SelectTrigger aria-label="经历类别"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(categories).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>{(['institution','title','startMonth'] as const).map(key=><label className="field" key={key}><span>{{institution:'学校 / 单位 / 项目组织',title:'学历专业 / 职位 / 项目名称',startMonth:'开始月份'}[key]}</span><Input required maxLength={200} type={key==='startMonth'?'month':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="flex items-center gap-2"><input type="checkbox" checked={form.ongoing} onChange={e=>setForm({...form,ongoing:e.target.checked,endMonth:e.target.checked?'':form.endMonth})}/>目前仍在进行</label>{!form.ongoing&&<label className="field"><span>结束月份</span><Input required type="month" value={form.endMonth} onChange={e=>setForm({...form,endMonth:e.target.value})}/></label>}<label className="field"><span>经历说明（本人可见）</span><textarea required minLength={5} maxLength={3000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></>}<label className="field"><span>{form.action==='cancel'?'作废原因':'登记 / 更正依据'}（本人可见）</span><textarea required minLength={5} maxLength={3000} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{selected?.payload.title}</DialogTitle><DialogDescription>经历资料与更正历史</DialogDescription></DialogHeader>{selected&&<><p className="whitespace-pre-wrap">{selected.payload.description}</p><p className="whitespace-pre-wrap">登记依据：{selected.payload.evidence}</p>{selected.payload.closedReason&&<p>作废原因：{selected.payload.closedReason}</p>}<ProcessHistory id={selected.id} updatedAt={selected.updatedAt}/></>}</DialogContent></Dialog></main>;
}
