'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={managedIds:string[];records:R[];totals:{id:string;grossCents:number;deductionCents:number;netCents:number}[];revision:number;role:string;employeeId:string|null;userId:string};
type Line={name:string;category:'earning'|'deduction'|'employer';amount:string;source:string};
const money=(n?:number)=>((n??0)/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),blank=():Line=>({name:'',category:'earning',amount:'',source:''});
const status:Record<string,string>={submitted:'待处理',approved:'已批准待发布',published:'已发布',rejected:'已驳回',cancelled:'已取消',answered:'已答复',withdrawn:'已撤回'};
const labels:Record<string,string>={query:'提出工资条异议',withdrawQuery:'撤回异议',answerQuery:'答复工资条异议',adjustment:'登记已核定差额',approveAdjustment:'批准补差',rejectAdjustment:'驳回补差',publishAdjustment:'发布补差记录',cancelAdjustment:'取消补差'};
function cents(s:string){if(!/^-?\d+(\.\d{1,2})?$/.test(s))throw Error('差额须为数字且最多两位小数');const [a,b='']=s.replace('-','').split('.'),n=(Number(a)*100+Number(b.padEnd(2,'0')))*(s.startsWith('-')?-1:1);if(!Number.isSafeInteger(n)||Math.abs(n)>1_000_000_000||n===0)throw Error('单项差额须非零且在允许范围内');return n;}
export default function PayrollAdjustments(){
 const [data,setData]=useState<Data|null>(null),[selected,setSelected]=useState('none'),[detail,setDetail]=useState<string|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[lines,setLines]=useState<Line[]>([blank()]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/payroll-adjustments',{cache:'no-store'}),d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error);setData(d);setSelected(v=>v==='none'?d.records.find(r=>r.kind==='paySlip')?.id??'none':v);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const admin=['admin','payroll_editor','payroll_reviewer'].includes(data?.role??''),writer=['admin','payroll_editor'].includes(data?.role??''),reviewer=['admin','payroll_reviewer'].includes(data?.role??''),slips=data?.records.filter(r=>r.kind==='paySlip')??[],slip=slips.find(r=>r.id===selected),total=data?.totals.find(r=>r.id===selected),rows=(data?.records??[]).filter(r=>['payAdjustment','payQuery'].includes(r.kind)&&r.referenceId===selected),record=data?.records.find(r=>r.id===detail),own=slip?.employeeId===data?.employeeId;
 function open(action:string,r?:R){setError('');setForm({action,id:r?.id??'',slipId:selected,name:'',evidence:'',adjustmentId:'none'});if(action==='adjustment')setLines([blank()]);}
 async function send(command:Record<string,unknown>){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/payroll-adjustments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('办理记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();if(!form)return;try{const c:Record<string,unknown>={...form};if(form.action==='adjustment'){c.reason=form.evidence;c.items=lines.map(l=>({name:l.name,category:l.category,amountCents:cents(l.amount),source:l.source}));}if(form.adjustmentId==='none')delete c.adjustmentId;send(c);}catch(e){setError((e as Error).message);}}
 function pick(v:string,onChange:(s:string)=>void,options:string[][],label:string){return <Select value={v||'none'} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{options.map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select>;}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/payroll" className="text-link">工资条</Link><Link href="/self-service" className="text-link">员工自助</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">PAYROLL ADJUSTMENTS</div><h1>工资条异议与补差</h1><p className="mt-2 text-sm text-slate-500">依据已核定金额登记差额，保留原工资条；发布补差记录不表示已付款或已完成税费申报。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}<section className="panel"><div className="flex flex-wrap gap-3 items-center">{pick(selected,setSelected,slips.map(r=>[r.id,`${r.payload.employeeSnapshot?.name} · ${r.payload.employeeSnapshot?.code} · ${r.payload.period}`]),'已发布工资条')}{slip&&own&&<Button onClick={()=>open('query')}>提出异议</Button>}{slip&&writer&&!own&&data?.managedIds.includes(slip.id)&&<Button onClick={()=>open('adjustment')}>登记差额</Button>}</div>{slip&&<div className="grid sm:grid-cols-3 gap-5 mt-6">{[['原工资条实发',slip.payload.netCents],['已发布实发差额',(total?.netCents??0)-(slip.payload.netCents??0)],['原单加已发布差额',total?.netCents]].map(([l,v])=><div key={String(l)}><p className="text-sm text-slate-500">{l}</p><strong className="text-xl">{money(v as number)} 元</strong></div>)}</div>}{!slips.length&&<p className="empty">暂无可见的已发布工资条</p>}</section>
 {['payQuery','payAdjustment'].map(kind=><section className="panel" key={kind}><div className="section-head"><h2>{kind==='payQuery'?'异议与答复':'补差记录'}</h2></div><Table><TableHeader><TableRow>{['事项','状态','实发差额（元）','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.filter(r=>r.kind===kind).reverse().map(r=><TableRow key={r.id}><TableCell>{r.payload.name??'工资条异议'}</TableCell><TableCell><Badge variant="outline">{status[r.status]}</Badge></TableCell><TableCell>{kind==='payAdjustment'?money(r.payload.netCents):'—'}</TableCell><TableCell><div className="flex gap-2 flex-wrap"><Button size="sm" variant="ghost" onClick={()=>setDetail(r.id)}>详情</Button>{kind==='payQuery'?<>{r.status==='submitted'&&own&&<Button size="sm" variant="outline" onClick={()=>open('withdrawQuery',r)}>撤回</Button>}{r.status==='submitted'&&writer&&!own&&<Button size="sm" onClick={()=>open('answerQuery',r)}>答复</Button>}</>:<>{reviewer&&!own&&r.status==='submitted'&&r.createdBy!==data?.userId&&<><Button size="sm" onClick={()=>open('approveAdjustment',r)}>批准</Button><Button size="sm" variant="outline" onClick={()=>open('rejectAdjustment',r)}>驳回</Button></>}{writer&&!own&&r.status==='approved'&&<Button size="sm" onClick={()=>open('publishAdjustment',r)}>发布</Button>}{writer&&!own&&['submitted','approved'].includes(r.status)&&r.createdBy===data?.userId&&<Button size="sm" variant="outline" onClick={()=>open('cancelAdjustment',r)}>取消</Button>}</>}</div></TableCell></TableRow>)}</TableBody></Table>{!rows.some(r=>r.kind===kind)&&<p className="empty">暂无记录</p>}</section>)}
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{labels[form?.action??'']}</DialogTitle><DialogDescription>{form?.action==='adjustment'?'差额以人民币元填写：正数增加对应项目，负数冲减对应项目。增加个人扣款会减少实发；冲减个人扣款会增加实发。':'请填写可核实的办理依据。已发布补差保留不变，纠错须另登记反向差额并重新复核。'}</DialogDescription></DialogHeader>{error&&<p className="text-red-700" role="alert">{error}</p>}{form&&<form onSubmit={submit} className="space-y-4">{form.action==='adjustment'&&<><label className="field"><span>补差事项名称</span><Input required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>{lines.map((l,i)=><div key={i} className="border rounded p-4 space-y-3"><div className="grid sm:grid-cols-3 gap-3"><label className="field"><span>项目名称</span><Input required value={l.name} onChange={e=>setLines(lines.map((x,j)=>i===j?{...x,name:e.target.value}:x))}/></label><label className="field"><span>类别</span>{pick(l.category,v=>setLines(lines.map((x,j)=>i===j?{...x,category:v as Line['category']}:x)),[['earning','应发项目'],['deduction','个人扣款'],['employer','企业承担']],'差额类别')}</label><label className="field"><span>差额（元）</span><Input required value={l.amount} onChange={e=>setLines(lines.map((x,j)=>i===j?{...x,amount:e.target.value}:x))}/></label></div><label className="field"><span>核定依据</span><Input required minLength={5} value={l.source} onChange={e=>setLines(lines.map((x,j)=>i===j?{...x,source:e.target.value}:x))}/></label><Button type="button" size="sm" variant="ghost" disabled={lines.length<=1} onClick={()=>setLines(lines.filter((_,j)=>i!==j))}>移除项目</Button></div>)}<Button type="button" variant="outline" disabled={lines.length>=40} onClick={()=>setLines([...lines,blank()])}>添加差额项目</Button></>}{form.action==='answerQuery'&&<label className="field"><span>关联已发布补差（选填）</span>{pick(form.adjustmentId,v=>setForm({...form,adjustmentId:v}),rows.filter(r=>r.kind==='payAdjustment'&&r.status==='published').map(r=>[r.id,r.payload.name??'补差']),'关联补差')}</label>}<label className="field"><span>{form.action==='query'?'异议内容与依据':'办理说明与依据'}</span><textarea required minLength={5} maxLength={2000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{record?.payload.name??'工资条异议'}</DialogTitle><DialogDescription>{record?.payload.period} · {record?status[record.status]:''}</DialogDescription></DialogHeader>{record&&<div className="space-y-4">{Object.entries({异议内容:record.kind==='payQuery'?record.payload.evidence:undefined,差额说明:record.payload.reason,答复:record.kind==='payQuery'?record.payload.verification:undefined,关联补差:record.kind==='payQuery'?data?.records.find(r=>r.id===record.payload.source)?.payload.name:undefined}).filter(([,v])=>v).map(([k,v])=><p key={k} className="whitespace-pre-wrap"><span className="text-slate-500">{k}：</span>{v}</p>)}{record.payload.payItems&&<Table><TableHeader><TableRow><TableHead>项目</TableHead><TableHead>类别</TableHead><TableHead>差额（元）</TableHead>{admin&&<TableHead>依据</TableHead>}</TableRow></TableHeader><TableBody>{record.payload.payItems.map((x,i)=><TableRow key={i}><TableCell>{x.name}</TableCell><TableCell>{{earning:'应发',deduction:'个人扣款',employer:'企业承担'}[x.category]}</TableCell><TableCell>{money(x.amountCents)}</TableCell>{admin&&<TableCell>{x.source}</TableCell>}</TableRow>)}</TableBody></Table>}{(data?.managedIds.includes(record.id)||record.kind==='payQuery')&&<ProcessHistory id={record.id} updatedAt={record.updatedAt}/>}</div>}</DialogContent></Dialog>
 </main>;
}
