'use client';
import {businessDate} from '@/lib/hris/business-time';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={records:R[];employees:{id:string;name:string;status:string}[];revision:number;role:string;employeeId:string|null;userId:string};
const status:Record<string,string>={active:'学习中',submitted:'待成果核验',returned:'待补充成果',completed:'已独立核验完成',cancelled:'学习任务已取消'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
 async function load(){try{const response=await fetch('/api/instructor-development',{cache:'no-store'}),d=await response.json() as Data&{error?:string};if(!response.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 const hr=['admin','hr'].includes(data?.role??''),records=data?.records??[],links=records.filter(r=>r.kind==='instructorDevelopment'),record=links.find(r=>r.id===detail),employee=(r:R)=>data?.employees.find(e=>e.id===r.employeeId),profile=(r:R)=>records.find(p=>p.kind==='instructorProfile'&&p.id===r.referenceId),task=(r:R)=>records.find(t=>t.kind==='enrollment'&&t.id===r.payload.learningEnrollmentId),rows=links.filter(r=>[employee(r)?.name,r.payload.title,r.status==='removed'?'已移除':status[task(r)?.status??'']].join(' ').includes(search)).reverse();
 function open(action:string,r?:R){setError('');setForm({action,id:r?.id??'',profileId:'',enrollmentId:'',courseId:'',due:businessDate(),mandatory:'true',evidence:''});}
 async function submit(e:FormEvent){e.preventDefault();if(!data||!form||busy)return;setBusy(true);setError('');try{const response=await fetch('/api/instructor-development',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command:{...form,...(['link','assign'].includes(form.action)?{mandatory:form.mandatory==='true'}:{})}})}),d=await response.json() as {error?:string};if(!response.ok)throw Error(d.error);setForm(null);setNotice('培养任务关联已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex flex-wrap gap-5 text-sm"><Link href="/instructor-campaigns" className="text-link">认证报名</Link><Link href="/instructor-directory" className="text-link">内部讲师名册</Link><Link href="/instructor-trials" className="text-link">试讲评审</Link><Link href="/learning" className="text-link">学习任务</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">INSTRUCTOR DEVELOPMENT</div><h1>认证培养任务</h1><p className="mt-2 text-sm text-slate-500">HR引用员工已有的真实学习任务，明确作为必修培养或参考学习。必修任务须完成独立成果核验，才能核对入册。</p></div><Button variant="outline" onClick={load}>刷新</Button></div><p className="mb-5 text-sm text-slate-500">可直接派发已发布课程并关联培养，也可引用已有学习任务。同员工同课程版本不重复派发；移除关联不会取消学习任务。入册前可说明原因移除关联，入册后保留关联及核对快照。</p>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}<div className="flex justify-between gap-4 mb-5"><Input className="max-w-md" aria-label="搜索培养关联" placeholder="搜索员工、任务或状态" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{hr&&<div className="flex gap-2"><Button variant="outline" onClick={()=>open('assign')}>派课并关联</Button><Button onClick={()=>open('link')}>关联学习任务</Button></div>}</div><div className="grid gap-4">{rows.slice((page-1)*12,page*12).map(r=><section className="panel" key={r.id}><div className="section-head"><div><h2>{r.payload.title}</h2><p className="text-sm text-slate-500">{employee(r)?.name} · 提名 V{profile(r)?.payload.version} · {r.payload.mandatory?'必修培养':'参考学习'}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setDetail(r.id)}>关联记录</Button>{hr&&r.employeeId!==data?.employeeId&&r.status==='active'&&profile(r)?.status==='submitted'&&<Button size="sm" variant="outline" onClick={()=>open('remove',r)}>移除关联</Button>}</div></div><p>{r.status==='removed'?'关联已移除':status[task(r)?.status??'']??'学习任务暂不可读取，请HR核对'}</p><p className="mt-2 text-sm text-slate-500">截止 {task(r)?.payload.due??'—'} · 成果核验 {task(r)?.payload.verifiedAt??'尚无'}</p></section>)}</div>{!rows.length&&<p className="panel empty">暂无可见的培养任务关联</p>}<div className="flex justify-end items-center gap-3 mt-4"><span>{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*12>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent><DialogHeader><DialogTitle>{form?.action==='assign'?'派课并关联培养':form?.action==='link'?'关联真实学习任务':'移除培养关联'}</DialogTitle><DialogDescription>必修或参考由HR根据培养安排明确。移除只改变提名与任务的关联，原始学习过程继续保留。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{['link','assign'].includes(form.action)&&<><label className="field"><span>待复核提名</span><select required className="rounded border p-2" value={form.profileId} onChange={e=>setForm({...form,profileId:e.target.value,enrollmentId:''})}><option value="">请选择</option>{records.filter(r=>r.kind==='instructorProfile'&&r.status==='submitted'&&r.employeeId!==data?.employeeId&&employee(r)?.status!=='离职').map(r=><option key={r.id} value={r.id}>{r.payload.name} · {r.payload.title} · V{r.payload.version}</option>)}</select></label>{form.action==='link'?<label className="field"><span>同员工学习任务</span><select required className="rounded border p-2" value={form.enrollmentId} onChange={e=>setForm({...form,enrollmentId:e.target.value})}><option value="">请选择已创建的真实学习任务</option>{records.filter(r=>r.kind==='enrollment'&&r.employeeId===records.find(p=>p.id===form.profileId)?.employeeId&&r.status!=='cancelled'&&!links.some(l=>l.referenceId===form.profileId&&l.payload.learningEnrollmentId===r.id&&l.status==='active')).map(r=><option key={r.id} value={r.id}>{r.payload.title} · {status[r.status]??r.status} · {r.payload.due}</option>)}</select></label>:<><label className="field"><span>已发布课程</span><select required className="rounded border p-2" value={form.courseId} onChange={e=>setForm({...form,courseId:e.target.value})}><option value="">请选择未领取的课程版本</option>{records.filter(r=>r.kind==='course'&&r.status==='published'&&!records.some(t=>t.kind==='enrollment'&&t.referenceId===r.id&&t.employeeId===records.find(p=>p.id===form.profileId)?.employeeId)).map(r=><option key={r.id} value={r.id}>{r.payload.title}</option>)}</select></label><label className="field"><span>学习截止日期</span><Input required type="date" min={businessDate()} value={form.due} onChange={e=>setForm({...form,due:e.target.value})}/></label></>}<label className="field"><span>培养要求</span><select className="rounded border p-2" value={form.mandatory} onChange={e=>setForm({...form,mandatory:e.target.value})}><option value="true">必修：独立核验完成后方可入册</option><option value="false">参考：不作为入册前置要求</option></select></label></>}<label className="field"><span>关联依据 / 移除原因</span><textarea required minLength={5} maxLength={2000} rows={3} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{record?.payload.title}</DialogTitle><DialogDescription>关联不会改变原学习结果。</DialogDescription></DialogHeader>{record&&<><p className="whitespace-pre-wrap">{record.payload.evidence}</p>{record.payload.closedReason&&<p>{record.payload.closedReason}</p>}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></>}</DialogContent></Dialog></main>;
}
