'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {InboxItem} from '@/lib/hris/work-inbox';
type Data={items:InboxItem[];total:number;page:number;hasMore:boolean;counts:Record<string,number>};
const domains=[['all','全部'],['cadres','干部人才'],['personnel','人事与档案'],['attendance','假勤'],['development','发展学习'],['learning','师资与出勤'],['onboarding','入职融入'],['payroll','薪酬'],['performance','绩效'],['recruitment','招聘']];
export default function Workspace(){const [data,setData]=useState<Data|null>(null),[domain,setDomain]=useState('all'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/work-inbox?'+new URLSearchParams({domain,q:search,page:String(page)}),{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error);if(!controller.signal.aborted)setData(d);}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setData(null);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[domain,search,page,refresh]);
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link className="text-link" href="/">导航台</Link><Link className="text-link" href="/self-service">我的任务与申请</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">WORK INBOX</div><h1>待我处理</h1><p className="mt-2 text-sm text-slate-500">按当前权限汇集人事、假勤、干部人才、发展学习、师资出勤、融入、薪酬、绩效及招聘待办。进入对应模块查看依据后办理。</p></div><Button variant="outline" disabled={loading} onClick={()=>setRefresh(x=>x+1)}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}<section className="panel"><Tabs value={domain} onValueChange={v=>{setDomain(v);setPage(1);}}><TabsList className="flex h-auto flex-wrap">{domains.map(([v,l])=><TabsTrigger key={v} value={v}>{l} {data?(v==='all'?Object.values(data.counts).reduce((a,b)=>a+b,0):data.counts[v]??0):''}</TabsTrigger>)}</TabsList></Tabs><form className="filters" onSubmit={e=>{e.preventDefault();setSearch(query);setPage(1);}}><Input aria-label="搜索待办" placeholder="搜索员工或办理事项" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} className="max-w-md"/><Button type="submit" variant="outline">搜索</Button></form>{loading?<p className="empty" role="status">正在更新待办…</p>:<><Table><TableHeader><TableRow>{['员工','事项','待处理环节','更新时间','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.items.map(r=><TableRow key={r.id}><TableCell>{r.employeeName}</TableCell><TableCell>{r.title}{r.due&&<p className="text-sm text-slate-500">截止 {r.due}</p>}</TableCell><TableCell>{r.action}</TableCell><TableCell>{new Date(r.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</TableCell><TableCell><Button asChild variant="outline"><Link href={r.href}>进入办理</Link></Button></TableCell></TableRow>)}</TableBody></Table>{!error&&!data?.items.length&&<p className="empty">当前条件下没有待处理事项</p>}</>}<div className="flex items-center justify-end gap-3 mt-4"><span className="text-sm">共 {data?.total??0} 项 · 第 {page} 页</span><Button variant="outline" disabled={loading||page<=1} onClick={()=>setPage(x=>x-1)}>上一页</Button><Button variant="outline" disabled={loading||!data?.hasMore} onClick={()=>setPage(x=>x+1)}>下一页</Button></div><p className="mt-4 text-sm text-slate-500">共享角色下的待办可能同时对多位管理者可见；他人处理或权限变化后，以业务模块的最新状态为准。列表仅汇集已接入的审批、核验及发布环节，其他业务操作仍在各自模块办理。</p></section></main>;
}
