'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import PersonnelNavigation from '../personnel-navigation';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import type {State,Position,Grade} from '@/lib/hris/model';
type Data={state:State;revision:number;role:string;permissions:{viewLevel:boolean}};
export default function Catalogs(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState('position'),[search,setSearch]=useState(''),[form,setForm]=useState<Record<string,string>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{setError('');try{const r=await fetch('/api/hris',{cache:'no-store'});const d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}};useEffect(()=>{load();},[]);
 const edit=(record?:Position|Grade)=>{setError('');setNotice('');setForm(record?Object.fromEntries(Object.entries(record).map(([k,v])=>[k,String(v)])):{code:'',name:'',orgId:data?.state.orgs.find(o=>o.status==='启用')?.id??'',family:'',responsibilities:'',sequence:'1',status:'启用'});};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!form||!data)return;setBusy(true);setError('');try{const r=await fetch('/api/hris',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command:{...form,action:tab,sequence:Number(form.sequence)}})});const d=await r.json() as Data&{error?:string};if(!r.ok){if(r.status===409)await load();throw Error(d.error);}setData(d);setForm(null);setNotice('已保存');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const list=(tab==='position'?data?.state.positions:data?.state.grades)??[];const allowed=tab==='position'?['admin','hr'].includes(data?.role??''):data?.role==='admin';
 const input=(key:string,required=true)=><Input value={form?.[key]??''} required={required} maxLength={100} onChange={e=>setForm({...form!,[key]:e.target.value})}/>;
 return <main className="main-content mx-auto max-w-6xl"><Link href="/" className="text-link">返回导航台</Link><div className="page-head mt-4"><h1>岗位与职级</h1><Button variant="outline" onClick={load}>刷新</Button></div><PersonnelNavigation current="/positions" admin={data?.role==='admin'}/>{error&&<div className="panel error" role="alert">{error}</div>}{notice&&<p role="status" className="my-4 text-green-700">{notice}</p>}<section className="panel"><div className="section-head"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="position">岗位目录</TabsTrigger><TabsTrigger value="grade">职级体系</TabsTrigger></TabsList></Tabs>{allowed&&<Button onClick={()=>edit()}>新增{tab==='position'?'岗位':'职级'}</Button>}</div><div className="filters"><Input className="max-w-md" placeholder="搜索编码或名称" aria-label="搜索" value={search} onChange={e=>setSearch(e.target.value)}/></div><Table><TableHeader><TableRow>{['编码','名称',tab==='position'?'所属组织':'排序',tab==='position'?'岗位族':'关联人数','状态','操作'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{list.filter(r=>(r.code+' '+r.name).toLowerCase().includes(search.toLowerCase())).map(r=><TableRow key={r.id}><TableCell>{r.code}</TableCell><TableCell>{r.name}</TableCell><TableCell>{'orgId'in r?data?.state.orgs.find(o=>o.id===r.orgId)?.name:r.sequence}</TableCell><TableCell>{'family'in r?r.family:data?.state.employees.filter(e=>e.gradeId===r.id&&e.status!=='离职').length}</TableCell><TableCell>{r.status}</TableCell><TableCell>{allowed&&<Button variant="ghost" onClick={()=>edit(r)}>编辑</Button>}</TableCell></TableRow>)}</TableBody></Table>{!list.length&&<p className="p-6 text-slate-500">{tab==='grade'&&!data?.permissions?.viewLevel?'没有职级字段查看权限':'暂无可见记录'}</p>}</section>
 <Dialog open={!!form} onOpenChange={open=>!open&&!busy&&setForm(null)}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{form?.id?'编辑':'新增'}{tab==='position'?'岗位':'职级'}</DialogTitle><DialogDescription>已被在职人员或待审批申请使用的记录，不能停用或改变标识及归属。</DialogDescription></DialogHeader>{form&&<form className="edit-form" onSubmit={submit}>{error&&<p role="alert" className="text-red-700">{error}</p>}<label className="field"><span>编码</span>{input('code')}</label><label className="field"><span>名称</span>{input('name')}</label>{tab==='position'?<><div className="field"><span>所属组织</span><Select value={form.orgId} onValueChange={v=>setForm({...form,orgId:v})}><SelectTrigger aria-label="所属组织"><SelectValue/></SelectTrigger><SelectContent>{data?.state.orgs.filter(o=>o.status==='启用').map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></div><label className="field"><span>岗位族</span>{input('family')}</label><label className="field"><span>岗位职责</span><textarea rows={4} maxLength={4000} value={form.responsibilities} onChange={e=>setForm({...form,responsibilities:e.target.value})}/></label></>:<label className="field"><span>排序值</span><Input type="number" min={0} max={999} step={1} required value={form.sequence} onChange={e=>setForm({...form,sequence:e.target.value})}/></label>}<div className="field"><span>状态</span><Select value={form.status} onValueChange={v=>setForm({...form,status:v})}><SelectTrigger aria-label="状态"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="启用">启用</SelectItem><SelectItem value="停用">停用</SelectItem></SelectContent></Select></div><div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setForm(null)}>取消</Button><Button disabled={busy}>{busy?'保存中…':'保存'}</Button></div></form>}</DialogContent></Dialog>
 </main>;
}
