'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={records:R[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={request:'申请内部课程',decide:'独立审批',withdraw:'撤回申请',arrange:'核对学习安排'},states:Record<string,string>={submitted:'待审批',approved:'待安排学习',rejected:'未通过',withdrawn:'已撤回',arranged:'已核对安排'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[names,setNames]=useState<Record<string,string>>({}),[form,setForm]=useState<Record<string,string>|null>(null),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/training-requests',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),d=await a.json() as Data&{error?:string},c=await b.json() as {state:{employees:{id:string;name:string}[]};error?:string};if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setNames(Object.fromEntries(c.state.employees.map(e=>[e.id,e.name])));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),manager=hr||data?.role==='manager',records=data?.records??[],record=records.find(r=>r.id===selected),request=records.find(r=>r.id===form?.id),rows=records.filter(r=>r.kind==='trainingRequest'&&[r.payload.title,names[r.employeeId??''],states[r.status]].join(' ').includes(search)).reverse();
 function open(action:string,r?:R,accepted=false){setError('');setForm({action,id:r?.id??'',courseId:'none',enrollmentId:'none',accepted:String(accepted),evidence:''});}
 async function submit(e:FormEvent){e.preventDefault();if(!form||!data)return;setBusy(true);setError('');try{const r=await fetch('/api/training-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command:{...form,accepted:form.accepted==='true'}})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const enrollments=records.filter(r=>r.kind==='enrollment'&&r.employeeId===request?.employeeId&&r.referenceId===request?.referenceId&&r.status!=='cancelled'&&r.createdAt>(request?.payload.approvedAt??''));
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/learning" className="text-link">学习中心</Link><Link href="/self-service" className="text-link">员工自助</Link></nav><div className="page-head mt-5"><div><h1>培训申请</h1><p className="mt-2 text-sm text-slate-500">本人申请已发布的内部课程，经独立审批后，由HR在学习中心安排任务并核对关联。</p></div><div className="flex gap-2"><Button variant="outline" onClick={load}>刷新</Button>{data?.employeeId&&<Button onClick={()=>open('request')}>申请课程</Button>}</div></div>{error&&<p className="panel error" role="alert">{error}</p>}<section className="panel"><Input className="max-w-md mb-4" aria-label="搜索培训申请" placeholder="员工、课程或状态" value={search} onChange={e=>setSearch(e.target.value)}/><Table><TableHeader><TableRow>{['申请人','课程版本','状态','申请时间','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=>{const self=r.employeeId===data?.employeeId,independent=manager&&!self&&r.createdBy!==data?.userId;return <TableRow key={r.id}><TableCell>{names[r.employeeId!]??'—'}</TableCell><TableCell>{r.payload.title} · V{r.payload.version??1}</TableCell><TableCell>{states[r.status]}</TableCell><TableCell>{new Date(r.createdAt).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'})}</TableCell><TableCell><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setSelected(r.id)}>详情</Button>{r.status==='submitted'&&independent&&<><Button size="sm" onClick={()=>open('decide',r,true)}>批准</Button><Button size="sm" variant="outline" onClick={()=>open('decide',r,false)}>不通过</Button></>}{self&&r.createdBy===data?.userId&&['submitted','approved'].includes(r.status)&&<Button variant="outline" size="sm" onClick={()=>open('withdraw',r)}>撤回</Button>}{r.status==='approved'&&hr&&independent&&<><Button asChild size="sm" variant="outline"><Link href="/learning">安排学习任务</Link></Button><Button size="sm" onClick={()=>open('arrange',r)}>核对关联</Button></>}{r.status==='arranged'&&<Link href="/learning" className="text-link text-sm">查看学习任务</Link>}</div></TableCell></TableRow>;})}</TableBody></Table>{!rows.length&&<p className="empty">暂无符合条件的培训申请</p>}<p className="text-sm text-slate-500 mt-4">已核对安排不代表学习完成；完成状态以学习任务的独立成果核验为准。课程原有领取方式继续适用，此申请不构成所有课程的访问门槛。</p></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent><DialogHeader><DialogTitle>{labels[form?.action??'']}</DialogTitle><DialogDescription>{form?.action==='arrange'?'仅关联申请批准后创建、同员工同课程版本的有效学习任务；先在学习中心安排，再返回核对。':'此流程仅适用于内部课程需求，不包含外训采购、费用报销或支付。'}</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='request'&&<label className="field"><span>已发布课程</span><Select value={form.courseId} onValueChange={v=>setForm({...form,courseId:v})}><SelectTrigger aria-label="申请课程"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{records.filter(r=>r.kind==='course'&&r.status==='published').map(r=><SelectItem key={r.id} value={r.id}>{r.payload.title} · V{r.payload.version??1}</SelectItem>)}</SelectContent></Select></label>}{form.action==='arrange'&&<label className="field"><span>已安排的学习任务</span><Select value={form.enrollmentId} onValueChange={v=>setForm({...form,enrollmentId:v})}><SelectTrigger aria-label="关联学习任务"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择</SelectItem>{enrollments.map(r=><SelectItem key={r.id} value={r.id}>{r.payload.title} · 截止{r.payload.due}</SelectItem>)}</SelectContent></Select>{!enrollments.length&&<p className="text-sm text-amber-700">暂无符合条件的任务，请先安排后刷新。</p>}</label>}<label className="field"><span>{form.action==='request'?'需求描述':'办理依据'}</span><textarea required minLength={5} maxLength={3000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button type="submit" disabled={busy||form.action==='request'&&form.courseId==='none'||form.action==='arrange'&&form.enrollmentId==='none'}>{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setSelected('');}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{record?.payload.title}</DialogTitle><DialogDescription>{states[record?.status??'']}</DialogDescription></DialogHeader>{record&&<>{Object.entries({需求描述:record.payload.evidence,审批意见:record.payload.verification,安排依据:record.payload.arrangementEvidence,撤回原因:record.payload.closedReason}).filter(([,v])=>v).map(([k,v])=><div key={k}><p className="text-sm text-slate-500">{k}</p><p className="whitespace-pre-wrap">{v}</p></div>)}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></>}</DialogContent></Dialog>
 </main>;
}
