import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,dev} from './support/foundation-scenario.mjs';
import {moveEmployee} from './support/performance-scenario.mjs';
const attendance=await import('../app/api/attendance/route.ts'),periods=await import('../app/api/attendance-periods/route.ts');
async function post(api,command,status=200,revision){return expect(await api.POST(request('/api/test',{revision:revision??(await get()).revision,command})),status);}
const attend=(c,s,r)=>post(attendance,c,s,r),period=(c,s,r)=>post(periods,c,s,r);
async function fixture(approve=true){const f=await setup(),shift=await attend({action:'shift',employeeId:f.e.id,date:'2026-01-05',name:'合成期间白班',startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',breakStart:'2026-01-05T12:00:00+08:00',breakEnd:'2026-01-05T13:00:00+08:00'}),type=await attend({action:'leaveType',code:'PERIOD-FULL',name:'合成已审核非额度假',paid:true,requiresBalance:false});act('employee');const leave=await attend({action:'leave',employeeId:f.e.id,shiftId:shift.id,leaveTypeId:type.id,startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',reason:'合成全天请假用于核对冻结前的覆盖结果'});if(approve){act('manager');await attend({action:'decideLeave',id:leave.id,accepted:true,evidence:'独立核验合成全天请假依据完整'});}act('owner');return {...f,shift,type,leave};}
const freeze=f=>({action:'freeze',employeeId:f.e.id,start:'2026-01-05',end:'2026-01-06',evidence:'合成期间来源已逐项核对且没有待处理异常'});
test('frozen attendance guards new shifts and corrections and approved leave changes; reopening and refreezing retain prior snapshot',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const p=await period(freeze(f));let record=(await get()).records.find(r=>r.id===p.id);assert.equal(record.payload.attendanceSnapshot.totals.plannedMinutes,480);assert.equal(record.payload.attendanceSnapshot.totals.approvedLeaveMinutes,480);assert.equal(record.payload.version,1);assert.ok(record.payload.attendanceSnapshot.sources.some(r=>r.id===f.leave.id));
 await attend({action:'shift',employeeId:f.e.id,date:'2026-01-06',name:'冻结期不可新增',startAt:'2026-01-06T09:00:00+08:00',endAt:'2026-01-06T18:00:00+08:00'},409);act('employee');await attend({action:'correction',shiftId:f.shift.id,inAt:'2026-01-05T09:00:00+08:00',outAt:'2026-01-05T18:00:00+08:00',evidence:'冻结期间不得直接补录有效时间'},409);act('manager');await attend({action:'cancelApprovedLeave',id:f.leave.id,reason:'冻结后不能直接更改已确认期间结果'},409);await period({action:'reopen',id:p.id,reason:'经理只读不能直接解冻期间'},403);act('owner');await period({action:'reopen',id:p.id,reason:'有新证据，显式重新开放合成期间'});await attend({action:'cancelApprovedLeave',id:f.leave.id,reason:'更正合成请假事实，转为实际出勤'});act('employee');const correction=await attend({action:'correction',shiftId:f.shift.id,inAt:'2026-01-05T09:00:00+08:00',outAt:'2026-01-05T18:00:00+08:00',evidence:'重新核对合成出勤依据并提交更正'});act('manager');await attend({action:'decideCorrection',id:correction.id,accepted:true,evidence:'独立核验更正后的出勤依据'});act('owner');await period({action:'refreeze',id:p.id,evidence:'重新核验出勤替代请假后再次冻结'});record=(await get()).records.find(r=>r.id===p.id);assert.equal(record.payload.version,2);assert.equal(record.payload.attendanceSnapshot.totals.approvedLeaveMinutes,0);const history=await expect(await dev.GET(new Request('https://hris.example/api/development?id='+p.id)));assert.ok(history.items.some(e=>e.snapshot.payload.version===1&&e.snapshot.payload.attendanceSnapshot.totals.approvedLeaveMinutes===480));assert.ok(history.items.some(e=>e.snapshot.payload.version===2));
});
test('incomplete, empty, future, overlapping or out-of-scope periods cannot freeze; audit failure leaves attendance writable',async t=>{
 const f=await fixture(false);t.after(()=>f.sqlite.close());await period(freeze(f),400);act('manager');await attend({action:'decideLeave',id:f.leave.id,accepted:false,evidence:'合成拒绝应留下未覆盖时段而非自动正常'});act('owner');await period(freeze(f),400);await period({...freeze(f),start:'2026-02-01',end:'2026-02-28'},400);await period({...freeze(f),start:'2099-01-01',end:'2099-01-02'},400);await period({...freeze(f),end:'2026-02-28'},400);act('hr');await period({...freeze(f),employeeId:f.other.id},403);act('employee');await expect(await periods.GET(),403);act('owner');const correction=await attend({action:'correction',shiftId:f.shift.id,inAt:'2026-01-05T09:00:00+08:00',outAt:'2026-01-05T18:00:00+08:00',evidence:'合成完整出勤核对后待独立审批'});act('manager');await attend({action:'decideCorrection',id:correction.id,accepted:true,evidence:'独立核实原始合成出勤依据'});act('owner');const revision=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_period_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await period(freeze(f),503);f.sqlite.exec('DROP TRIGGER reject_period_audit');assert.equal((await get()).revision,revision);assert.equal((await get()).records.filter(r=>r.kind==='attendancePeriod').length,0);const p=await period(freeze(f));await period(freeze(f),400);await period({action:'reopen',id:p.id,reason:'旧版本不能覆盖新冻结状态'},409,revision);act('employee');assert.ok(!(await get()).records.some(r=>r.kind==='attendancePeriod'));act('owner');await period({action:'reopen',id:p.id,reason:'原期间范围需修订，保留原始依据'});await period({action:'void',id:p.id,reason:'作废错误范围但不删除历史冻结快照'});const replacement=await period({...freeze(f),end:'2026-01-05'});assert.notEqual(replacement.id,p.id);
});
test('current personnel scope governs historical period access while the employee lock survives a transfer',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const p=await period(freeze(f));await moveEmployee(f,'transfer');act('hr');assert.equal((await expect(await periods.GET())).records.length,0);await period({action:'reopen',id:p.id,reason:'原组织HR已失去当前人员范围'},403);act('owner');await attend({action:'shift',employeeId:f.e.id,date:'2026-01-06',name:'调动不绕过冻结',startAt:'2026-01-06T09:00:00+08:00',endAt:'2026-01-06T18:00:00+08:00'},409);await period({action:'reopen',id:p.id,reason:'由当前有权限人员核对历史期间'});await period({action:'refreeze',id:p.id,evidence:'历史来源不因人员调动而被删除'});assert.equal((await get()).records.find(r=>r.id===p.id).payload.version,2);
});

test('preview is read-only, scope checked and stale revisions do not freeze changed sources; employee receives only visible lock identifiers',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const revision=(await get()).revision,preview=await period({action:'preview',employeeId:f.e.id,start:'2026-01-05',end:'2026-01-06'});assert.equal((await get()).revision,revision);assert.equal(preview.totals.plannedMinutes,480);assert.deepEqual(preview.blockers,[]);assert.equal(preview.source,undefined);await period({...freeze(f),extraClientSnapshot:preview},400);const frozen=await period(freeze(f));await period({action:'preview',employeeId:f.e.id,start:'2026-01-05',end:'2026-01-06'},409,revision);act('employee');const d=await expect(await attendance.GET());assert.deepEqual(d.frozenShiftIds,[f.shift.id]);assert.equal(d.frozenPeriods.length,0);await expect(await dev.GET(new Request('https://hris.example/api/development?id='+frozen.id)),403);act('hr');await period({action:'preview',employeeId:f.other.id,start:'2026-01-05',end:'2026-01-06'},403);
});
