import test from 'node:test';
import assert from 'node:assert/strict';
import {setup,core,grant,hris,members,expect,act,request} from './support/foundation-scenario.mjs';
const {businessDate}=await import('../lib/hris/business-time.ts');
const history=await import('../app/api/history/route.ts');
const attachments=await import('../app/api/attachments/route.ts');
async function post(command,status=200,revision){const d=await expect(await hris.GET());return expect(await hris.POST(request('/api/hris',{revision:revision??d.revision,command})),status);}
async function fixture(t){const f=await setup();t.after(()=>f.sqlite.close());await core({action:'position',code:'F-UAT-B',name:'合成B岗位',orgId:f.otherOrg.id,family:'验收',responsibilities:'仅合成数据',status:'启用'});await core({action:'grade',code:'F-T1',name:'合成T1',sequence:1,status:'启用'});await core({action:'grade',code:'F-T2',name:'合成T2',sequence:2,status:'启用'});let d=await expect(await hris.GET());f.target=d.state.positions.find(x=>x.code==='F-UAT-B');f.g1=d.state.grades.find(x=>x.code==='F-T1');f.g2=d.state.grades.find(x=>x.code==='F-T2');await core({action:'employee',...f.e,positionId:f.position.id,gradeId:f.g1.id});await grant('hrAB','hr',null,[f.org.id,f.otherOrg.id]);await grant('reviewB','approver',null,[f.otherOrg.id]);await grant('outsiderB','approver',null,[f.otherOrg.id]);f.permission=async(id,role,scope,viewLevel)=>{act('owner');const d=await expect(await members.GET());await expect(await members.POST(request('/api/members',{revision:d.revision,email:id+'@example.com',name:'合成'+id,role,employeeId:null,orgScope:scope,viewEmail:false,viewLevel,active:true})));};f.rows=()=>['hris_workspaces','hris_employees','hris_approvals','hris_approval_steps','hris_employment_history','hris_audit_events'].map(table=>f.sqlite.prepare('SELECT * FROM '+table+' ORDER BY rowid').all());f.command={action:'request',kind:'transfer',employeeId:f.e.id,orgId:f.otherOrg.id,positionId:f.target.id,gradeId:f.g2.id,effectiveOn:businessDate(),reason:'F01-F04合成跨组织调动'};f.ready=async()=>{await f.permission('hrAB','hr',[f.org.id,f.otherOrg.id],true);await f.permission('approver','approver',[f.org.id],true);await f.permission('reviewB','approver',[f.otherOrg.id],true);await core({action:'workflow',kind:'transfer',steps:[{userId:'approver',name:'调出方'},{userId:'reviewB',name:'调入方'}]});};f.submit=async(extra={})=>{act('hrAB');const d=await post({...f.command,...extra});return d.state.approvals.find(a=>a.status==='pending'&&a.employeeId===f.e.id);};f.approve=async a=>{act('approver');await post({action:'decide',id:a.id,decision:'approved'});act('reviewB');return post({action:'decide',id:a.id,decision:'approved'});};return f;}

test('D3–D5: 双范围指定HR发起，来源/目标两级；目标仅见申请快照，职级变化不能盲审',async t=>{
 const f=await fixture(t);await f.ready();let before=f.rows();act('hr');await post({...f.command,gradeId:f.g1.id},403);assert.deepEqual(f.rows(),before);act('manager');await post(f.command,403);assert.deepEqual(f.rows(),before);
 await f.permission('hrAB','hr',[f.org.id,f.otherOrg.id],false);before=f.rows();act('hrAB');await post(f.command,403);assert.deepEqual(f.rows(),before);
 await f.permission('hrAB','hr',[f.org.id,f.otherOrg.id],true);await f.permission('reviewB','approver',[f.otherOrg.id],false);before=f.rows();act('hrAB');await post(f.command,400);assert.deepEqual(f.rows(),before);await f.permission('reviewB','approver',[f.otherOrg.id],true);
 const a=await f.submit();act('reviewB');let d=await expect(await hris.GET());assert.ok(!d.state.employees.some(e=>e.id===f.e.id));assert.ok(!d.state.orgs.some(o=>o.id===f.org.id));const summary=d.state.approvals.find(x=>x.id===a.id).details.transfer;assert.equal(summary.source.orgName,f.org.name);assert.equal(summary.target.gradeId,f.g2.id);assert.equal(summary.source.gradeId,f.g1.id);assert.ok(!JSON.stringify(summary).includes('@'));await expect(await history.GET(request('/api/history?employeeId='+f.e.id)),403);await expect(await attachments.GET(request('/api/attachments?employeeId='+f.e.id)),403);before=f.rows();await post({action:'decide',id:a.id,decision:'approved'},403);assert.deepEqual(f.rows(),before);
 act('outsiderB');assert.ok(!(await expect(await hris.GET())).state.approvals.some(x=>x.id===a.id));
 act('approver');await post({action:'decide',id:a.id,decision:'approved'});await f.permission('reviewB','approver',[f.otherOrg.id],false);act('reviewB');d=await expect(await hris.GET());const hidden=d.state.approvals.find(x=>x.id===a.id);assert.equal(hidden.details.transfer.source.level,'');assert.equal(hidden.details.transfer.target.gradeId,null);assert.equal(hidden.details.transfer.gradeChanged,true);before=f.rows();await post({action:'decide',id:a.id,decision:'approved'},403);assert.deepEqual(f.rows(),before);await f.permission('reviewB','approver',[f.otherOrg.id],true);act('reviewB');await post({action:'decide',id:a.id,decision:'approved'});
 act('hrAB');d=await expect(await hris.GET());assert.equal(d.state.employees.find(e=>e.id===f.e.id).orgId,f.org.id,'批准尚未生效');await post({action:'executeTransfer',id:a.id});act('owner');d=await expect(await hris.GET());assert.equal(d.state.employees.find(e=>e.id===f.e.id).orgId,f.otherOrg.id);assert.equal(d.state.employees.find(e=>e.id===f.e.id).gradeId,f.g2.id);assert.equal(d.state.approvals.find(x=>x.id===a.id).details.transfer.execution,'applied');const h=await expect(await history.GET(request('/api/history?employeeId='+f.e.id)));assert.equal(h.items[0].toOrg,f.otherOrg.name);
 act('hr');assert.ok(!(await expect(await hris.GET())).state.employees.some(e=>e.id===f.e.id));
});

test('D1: 北京时间00:00边界；批准不改档案；执行与历史审计原子一致，重复请求不重复写',async t=>{
 t.mock.timers.enable({apis:['Date'],now:Date.parse('2026-09-08T15:59:59Z')});const f=await fixture(t);await f.ready();const a=await f.submit({effectiveOn:'2026-09-09'});await f.approve(a);act('hrAB');let before=f.rows();await post({action:'executeTransfer',id:a.id},400);assert.deepEqual(f.rows(),before);
 t.mock.timers.setTime(Date.parse('2026-09-08T16:00:00Z'));f.sqlite.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable'); END");before=f.rows();await post({action:'executeTransfer',id:a.id},503);assert.deepEqual(f.rows(),before,'审计异常整笔回滚，结果先刷新核对');f.sqlite.exec('DROP TRIGGER fail_audit');const revision=(await expect(await hris.GET())).revision;let d=await post({action:'executeTransfer',id:a.id});const applied=d.state.approvals.find(x=>x.id===a.id).details.transfer;assert.equal(applied.appliedAt,'2026-09-08T16:00:00.000Z');assert.equal(applied.attempts,1);assert.equal(f.sqlite.prepare('SELECT at FROM hris_employment_history WHERE employee_id=? ORDER BY rowid DESC').get(f.e.id).at,applied.appliedAt);before=f.rows();await post({action:'executeTransfer',id:a.id},409,revision);assert.deepEqual(f.rows(),before);await post({action:'executeTransfer',id:a.id},400);assert.deepEqual(f.rows(),before);
});

test('D1: 执行失败保留审批与计划日期；修复后重试仅产生一次任职变更，不倒写历史',async t=>{
 t.mock.timers.enable({apis:['Date'],now:Date.parse('2026-09-08T01:00:00Z')});const f=await fixture(t);await f.ready();const a=await f.submit();await f.approve(a);act('owner');await post({action:'position',...f.target,status:'停用'});t.mock.timers.setTime(Date.parse('2026-09-09T03:00:00Z'));act('hrAB');let d=await post({action:'executeTransfer',id:a.id});let saved=d.state.approvals.find(x=>x.id===a.id);assert.equal(saved.status,'approved');assert.equal(saved.details.transfer.execution,'failed');assert.match(saved.details.transfer.failure,/岗位/);assert.equal(saved.details.transfer.appliedAt,undefined);assert.equal(d.state.employees.find(e=>e.id===f.e.id).orgId,f.org.id);act('owner');await post({action:'position',...f.target,status:'启用'});act('hrAB');d=await post({action:'executeTransfer',id:a.id});saved=d.state.approvals.find(x=>x.id===a.id);assert.equal(saved.details.transfer.effectiveOn,'2026-09-08');assert.equal(saved.details.transfer.appliedAt,'2026-09-09T03:00:00.000Z');assert.equal(saved.details.transfer.attempts,2);assert.equal(saved.details.transfer.failure,undefined);
});

test('D2/D6: 不允许回溯或晚批；改日期终止原单，关联新申请重走两级；驳回原因必填',async t=>{
 t.mock.timers.enable({apis:['Date'],now:Date.parse('2026-09-08T01:00:00Z')});const f=await fixture(t);await f.ready();act('hrAB');let before=f.rows();await post({...f.command,effectiveOn:'2026-09-07'},400);assert.deepEqual(f.rows(),before);const a=await f.submit();act('approver');await post({action:'decide',id:a.id,decision:'approved'});t.mock.timers.setTime(Date.parse('2026-09-08T16:00:00Z'));act('reviewB');before=f.rows();await post({action:'decide',id:a.id,decision:'approved'},400);assert.deepEqual(f.rows(),before);act('hrAB');await post({action:'withdraw',id:a.id});before=f.rows();await post({...f.command,effectiveOn:'2026-09-09'},400);assert.deepEqual(f.rows(),before,'改日不得绕过关联原单');const b=await f.submit({effectiveOn:'2026-09-09',previousApprovalId:a.id});assert.equal(b.currentStep,0);assert.ok(b.steps.every(s=>!s.decision));act('approver');before=f.rows();await post({action:'decide',id:b.id,decision:'rejected'},400);assert.deepEqual(f.rows(),before);await post({action:'decide',id:b.id,decision:'rejected',decisionReason:'目标岗位安排需重新核实'});const c=await f.submit({effectiveOn:'2026-09-09',previousApprovalId:b.id});assert.equal(c.details.previousApprovalId,b.id);assert.ok(c.steps.every(s=>!s.decision));await f.approve(c);act('hrAB');await post({action:'cancelTransfer',id:c.id,reason:'生效日改为下一日，重新审批'});const d=await f.submit({effectiveOn:'2026-09-10',previousApprovalId:c.id});assert.equal(d.currentStep,0);const all=(await expect(await hris.GET())).state.approvals;assert.equal(all.find(x=>x.id===a.id).status,'withdrawn');assert.equal(all.find(x=>x.id===b.id).details.rejectionReason,'目标岗位安排需重新核实');assert.equal(all.find(x=>x.id===c.id).status,'approved');assert.equal(all.find(x=>x.id===c.id).details.transfer.execution,'cancelled');assert.equal(all.find(x=>x.id===c.id).details.transfer.effectiveOn,'2026-09-09');
});

test('D7: 新调动必须提供日期和两级独立流程；来源范围不能替代目标范围',async t=>{
 const f=await fixture(t);await f.ready();let before=f.rows();act('hrAB');const {effectiveOn,...missing}=f.command;await post(missing,400);assert.deepEqual(f.rows(),before);act('owner');await post({action:'workflow',kind:'transfer',steps:[{userId:'approver',name:'仅一级'}]},400);await post({action:'workflow',kind:'transfer',steps:[{userId:'approver',name:'一'},{userId:'reviewB',name:'二'},{userId:'manager',name:'三'}]},400);await post({action:'workflow',kind:'transfer',steps:[{userId:'approver',name:'一'},{userId:'manager',name:'来源二'}]});act('hrAB');before=f.rows();await post(f.command,400);assert.deepEqual(f.rows(),before);
});


test('D1/F03: 到期编制不足记录可恢复失败，批准和历史不被改写；修复编制后重试',async t=>{
 const f=await fixture(t);await f.ready();const workforce=await import('../app/api/workforce/route.ts');async function work(command){const d=await expect(await workforce.GET());return expect(await workforce.POST(request('/api/workforce',{revision:d.revision,command})));}
 await grant('managerB','manager',null,[f.otherOrg.id]);act('owner');let p=await work({action:'staffing',positionId:f.target.id,start:'2020-01-01',end:'2099-12-31',headcount:0,evidence:'合成目标编制暂为零人'});act('managerB');await work({action:'approveStaffing',id:p.id,evidence:'合成独立复核零人编制'});const a=await f.submit();await f.approve(a);act('hrAB');const historyBefore=f.sqlite.prepare('SELECT * FROM hris_employment_history ORDER BY rowid').all();let d=await post({action:'executeTransfer',id:a.id});assert.equal(d.state.approvals.find(x=>x.id===a.id).details.transfer.execution,'failed');assert.match(d.state.approvals.find(x=>x.id===a.id).details.transfer.failure,/编制/);assert.deepEqual(f.sqlite.prepare('SELECT * FROM hris_employment_history ORDER BY rowid').all(),historyBefore);assert.equal(d.state.employees.find(x=>x.id===f.e.id).orgId,f.org.id);
 act('owner');const revised=await work({action:'staffing',positionId:f.target.id,start:'2020-01-01',end:'2099-12-31',headcount:1,supersedes:p.id,evidence:'合成允许一人，独立批准后重试'});act('managerB');await work({action:'approveStaffing',id:revised.id,evidence:'合成复核一人编制'});await f.permission('hrAB','hr',[f.org.id],true);act('hrAB');let before=f.rows();await post({action:'executeTransfer',id:a.id},403);assert.deepEqual(f.rows(),before);await f.permission('hrAB','hr',[f.org.id,f.otherOrg.id],true);act('hrAB');d=await post({action:'executeTransfer',id:a.id});assert.equal(d.state.approvals.find(x=>x.id===a.id).details.transfer.execution,'applied');assert.equal(d.state.approvals.find(x=>x.id===a.id).details.transfer.attempts,2);
});
