import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,grant,members,core,hris,dev} from './support/foundation-scenario.mjs';
import {moveEmployee} from './support/performance-scenario.mjs';
const api=await import('../app/api/interview-schedule/route.ts'),defs=await import('../app/api/interview-definitions/route.ts'),recruitment=await import('../app/api/recruitment/route.ts');
async function post(a,command,status=200,revision){return expect(await a.POST(request('/api/test',{revision:revision??(await get()).revision,command})),status);}
const schedule=(c,s,r)=>post(api,c,s,r),recruit=(c,s,r)=>post(recruitment,c,s,r);
async function fixture(){const f=await setup();await core({action:'employee',code:'SCHEDULE-REVIEWER',name:'合成独立面试官',orgId:f.org.id,job:'面试负责人',level:'',joined:'2026-01-01',email:''});f.e=(await expect(await hris.GET())).state.employees.find(e=>e.code==='SCHEDULE-REVIEWER');await grant('scheduledReviewer','manager',f.e.id,[f.org.id]);const q=await recruit({action:'requisition',positionId:f.position.id,title:'合成排期需求',headcount:1,reason:'合成面试排期验证指定人员和时间冲突',submit:true});act('manager');await recruit({action:'approveRequisition',id:q.id});act('owner');const c=await recruit({action:'candidate',requisitionId:q.id,name:'合成排期候选',email:'',source:'仅用于排期与评价原子集成验证'}),d=await post(defs,{action:'create',orgId:f.org.id,title:'合成排期表',criteria:[{id:'skill',dimension:'能力',title:'合成技能',description:'依据合成事实评分',labels:['一','二','三','四']}]});await post(defs,{action:'seal',id:d.id});return {...f,q,c,d};}
const input=f=>({action:'schedule',candidateId:f.c.id,title:'合成第一轮',method:'video',startAt:'2026-01-01T01:00:00Z',endAt:'2026-01-01T02:00:00Z',timeZone:'Asia/Shanghai',location:'内部合成会议地点，不发邀约',interviewerEmployeeId:f.e.id,definitionId:f.d.id});
const evaluate=(f,id)=>({action:'structuredInterview',candidateId:f.c.id,appointmentId:id,definitionId:f.d.id,scores:{skill:4},comments:{},recommendation:'advance',evidence:'由指定人员独立记录合成面试结论'});
test('schedule validates scope, time ranges, candidate and interviewer conflicts; cancel retains evidence and releases the slot',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const c=input(f);await schedule({...c,endAt:c.startAt},400);await schedule({...c,endAt:'2026-01-03T02:00:00Z'},400);await schedule({...c,interviewerEmployeeId:f.other.id},400);const unprivileged=(await expect(await hris.GET())).state.employees.find(e=>e.code==='A');await schedule({...c,interviewerEmployeeId:unprivileged.id},400);act('manager');await schedule(c,403);act('employee');await expect(await api.GET(),403);act('owner');const a=await schedule(c);await schedule(c,400);const second=await recruit({action:'candidate',requisitionId:f.q.id,name:'合成冲突候选',email:'',source:'用于验证同一面试官跨候选冲突'});await schedule({...c,candidateId:second.id},400);const adjacent=await schedule({...c,candidateId:second.id,startAt:c.endAt,endAt:'2026-01-01T03:00:00Z'});await schedule({action:'cancel',id:a.id,reason:'明确取消此合成安排释放时间'});await schedule({...c,candidateId:second.id});await schedule({action:'cancel',id:a.id,reason:'不能重复取消已处理安排'},400);assert.equal((await get()).records.find(r=>r.id===a.id).status,'cancelled');assert.equal((await get()).records.find(r=>r.id===adjacent.id).status,'scheduled');
});
test('only assigned current manager can complete ended appointment using frozen archived template; result and completion roll back together',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const a=await schedule(input(f)),c=evaluate(f,a.id);await post(defs,{action:'archive',id:f.d.id});await recruit(c,403);act('manager');await recruit(c,403);act('scheduledReviewer');assert.equal((await expect(await api.GET())).availability.find(x=>x.id===a.id).canEvaluate,true);const revision=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_scheduled_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await recruit(c,503);f.sqlite.exec('DROP TRIGGER reject_scheduled_audit');assert.equal((await get()).revision,revision);assert.equal((await get()).records.find(r=>r.id===a.id).status,'scheduled');assert.equal((await get()).records.filter(r=>r.kind==='interview').length,0);const result=await recruit(c);let records=(await get()).records;assert.equal(records.find(r=>r.id===a.id).payload.interviewResultId,result.id);assert.equal(records.find(r=>r.id===a.id).status,'completed');assert.equal(records.find(r=>r.id===result.id).payload.interviewEvaluation.title,'合成排期表');await recruit(c,403);act('owner');await recruit({action:'offer',id:f.c.id,joined:'2026-01-01',evidence:'指定排期完成后依照明确结论发起录用'});
});
test('future, cancelled, moved and revoked appointments cannot be signed and pending schedules block legacy-offer bypass',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const a=await schedule({...input(f),startAt:'2099-01-01T01:00:00Z',endAt:'2099-01-01T02:00:00Z'});act('scheduledReviewer');await recruit(evaluate(f,a.id),403);await recruit({action:'interview',candidateId:f.c.id,rating:4,recommendation:'advance',evidence:'旧模式补录不能替代仍未完成的指定排期'});act('owner');await recruit({action:'offer',id:f.c.id,joined:'2026-01-01',evidence:'未完成排期不得绕过而直接办理录用'},400);await schedule({action:'cancel',id:a.id,reason:'合成未来安排取消，不再授权评价'});act('scheduledReviewer');await recruit(evaluate(f,a.id),403);act('owner');const b=await schedule(input(f));await moveEmployee(f,'transfer');act('scheduledReviewer');await recruit(evaluate(f,b.id),403);assert.equal((await expect(await api.GET())).availability.find(x=>x.id===b.id)?.canEvaluate,false);act('owner');await schedule({action:'cancel',id:b.id,reason:'指定人员已调离，保留取消记录'});
 const current=await expect(await members.GET());await expect(await members.POST(request('/api/members',{revision:current.revision,email:'scheduledReviewer@example.com',name:'合成独立面试官',role:'manager',employeeId:f.e.id,orgScope:[f.org.id],viewEmail:false,viewLevel:false,active:false})));act('scheduledReviewer');await expect(await api.GET(),403);
});

test('rescheduling retains archived frozen form, transfers evaluation authority and preserves earlier schedule history',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const a=await schedule(input(f));await post(defs,{action:'archive',id:f.d.id});await core({action:'employee',code:'NEXT-INTERVIEWER',name:'合成接任面试官',orgId:f.org.id,job:'面试负责人',level:'',joined:'2026-01-01',email:''});const next=(await expect(await hris.GET())).state.employees.find(e=>e.code==='NEXT-INTERVIEWER');await grant('nextInterviewer','manager',next.id,[f.org.id]);const {candidateId,...fields}=input(f),c={...fields,action:'reschedule',id:a.id,interviewerEmployeeId:next.id,startAt:'2026-01-02T01:00:00Z',endAt:'2026-01-02T02:00:00Z'},revision=(await get()).revision;await schedule(c);await schedule(c,409,revision);act('scheduledReviewer');await recruit(evaluate(f,a.id),403);act('nextInterviewer');await recruit(evaluate(f,a.id));const history=await expect(await dev.GET(new Request('https://hris.example/api/development?id='+a.id)));assert.ok(history.items.some(e=>e.snapshot.payload.interviewSchedule.interviewerEmployeeId===f.e.id));assert.ok(history.items.some(e=>e.snapshot.payload.interviewSchedule.interviewerEmployeeId===next.id));assert.equal((await get()).records.find(r=>r.id===a.id).payload.interviewSchedule.definition.id,f.d.id);
});
test('unified inbox shows only currently designated ended interviews and removes completed or cancelled work',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());const inbox=await import('../app/api/work-inbox/route.ts'),tasks=async()=>expect(await inbox.GET(new Request('https://hris.example/api/work-inbox?domain=recruitment'))),a=await schedule(input(f));act('manager');assert.ok(!(await tasks()).items.some(x=>x.recordId===a.id));act('scheduledReviewer');const task=(await tasks()).items.find(x=>x.recordId===a.id);assert.equal(task.action,'指定面试评价');assert.equal(new URL(task.href,'https://hris.example').searchParams.get('appointmentId'),a.id);await recruit(evaluate(f,a.id));assert.ok(!(await tasks()).items.some(x=>x.recordId===a.id));act('owner');const future=await schedule({...input(f),startAt:'2099-01-01T01:00:00Z',endAt:'2099-01-01T02:00:00Z'});act('scheduledReviewer');assert.ok(!(await tasks()).items.some(x=>x.recordId===future.id));act('owner');await schedule({action:'cancel',id:future.id,reason:'合成取消不留下不可操作待办'});act('scheduledReviewer');assert.ok(!(await tasks()).items.some(x=>x.recordId===future.id));});
