import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,core,grant,hris,get,send,act,expect,request} from './support/foundation-scenario.mjs';
const plans=await import('../app/api/learning-plans/route.ts'),assign=await import('../app/api/learning-assignments/route.ts'),exams=await import('../app/api/learning-exams/route.ts'),tasks=await import('../app/api/learning-exam-tasks/route.ts'),updates=await import('../app/api/learning-content-update/route.ts');
async function cmd(api,command,status=200){const d=await expect(await api.GET());return expect(await api.POST(request('/api/test',{revision:d.revision,command})),status);}
async function update(command,action='preview',status=200,revision){const d=await get();return expect(await updates.POST(request('/api/learning-content-update',{revision:revision??d.revision,action,command,evidence:'合成计划内容版本更新核对'})),status);}
async function fixture(t){const f=await setup();t.after(()=>f.sqlite.close());const course=await send({action:'course',code:'UPDATE',title:'原课程',description:'内容更新追溯',content:'完成合成业务实践后由独立人员核验，保留原始完成证据。'});await send({action:'publishCourse',id:course.id});const config={mode:'relative',durationDays:30,allowOverdue:false,orderedStages:false,progressSync:false},definition=await cmd(plans,{action:'create',title:'内容更新合成计划',orgId:f.org.id,courseIds:[course.id],config});await cmd(plans,{action:'seal',id:definition.id});await cmd(assign,{action:'assign',definitionId:definition.id,employeeId:f.e.id});let rows=(await get()).records;const instance=rows.find(r=>r.kind==='learningAssignment'),enrollment=rows.find(r=>r.kind==='enrollment');const exam=await cmd(exams,{action:'create',title:'新增独立考试',orgId:f.org.id,questions:[{prompt:'合成业务应如何处理',options:['独立核验','自行审批'],correct:0}],passingScore:80,maxAttempts:2});await cmd(exams,{action:'seal',id:exam.id});const next=await cmd(plans,{action:'revise',id:definition.id});await cmd(plans,{action:'edit',id:next.id,title:'追加考试的计划',orgId:f.org.id,courseIds:[course.id],examIds:[exam.id],config});await cmd(plans,{action:'grading',id:next.id,rule:{mode:'allHighest',attempts:'all',decimals:2}});await cmd(plans,{action:'seal',id:next.id});return {...f,course,config,definition,instance,enrollment,exam,next,command:{assignmentId:instance.id,definitionId:next.id}};}
test('content update preview is read-only; application retains evidence, rejects stale/duplicate writes, rolls back atomically and completes added exam',async t=>{
 const f=await fixture(t);act('employee');await send({action:'submitLearning',id:f.enrollment.id,evidence:'合成原课程实践成果已完成'});act('hr');await send({action:'verifyLearning',id:f.enrollment.id,accepted:true,evidence:'独立核验原课程成果符合要求'});
 const before=await get(),original=before.records.find(r=>r.id===f.enrollment.id),events=f.sqlite.prepare('SELECT count(*) AS n FROM hris_development_events').get().n;
 const p=await update(f.command);assert.equal(p.preview.canApply,true);assert.equal(p.preview.retained.length,1);assert.equal(p.preview.added.length,1);assert.equal(p.preview.beforeProgress.complete,true);assert.equal(p.preview.afterProgress.complete,false);assert.equal((await get()).revision,before.revision);assert.equal(f.sqlite.prepare('SELECT count(*) AS n FROM hris_development_events').get().n,events);assert.ok(!('projected' in p.preview));
 await update(f.command,'apply',409,before.revision-1);
 f.sqlite.exec("CREATE TRIGGER content_update_fail BEFORE INSERT ON hris_development_events BEGIN SELECT RAISE(ABORT,'synthetic content update audit failure'); END");await update(f.command,'apply',503);f.sqlite.exec('DROP TRIGGER content_update_fail');assert.equal((await get()).revision,before.revision);assert.equal((await get()).records.length,before.records.length);
 const applied=await update(f.command,'apply');assert.equal(applied.ids.length,2);let rows=(await get()).records,current=rows.find(r=>r.id===f.instance.id),task=rows.find(r=>r.kind==='learningExamTask');assert.equal(current.referenceId,f.next.id);assert.equal(current.payload.contentUpdateFromId,f.definition.id);assert.deepEqual(rows.find(r=>r.id===f.enrollment.id),original);assert.equal(current.payload.start,f.instance.payload.start);assert.equal(current.payload.due,f.instance.payload.due);assert.equal(rows.filter(r=>r.kind==='learningCredit').length,0);await update(f.command,'apply',400);await cmd(assign,{action:'assign',definitionId:f.definition.id,employeeId:f.e.id},400);
 act('employee');await cmd(tasks,{action:'submit',id:task.id,answers:[0]});act('hr');await cmd(assign,{action:'closeAssignment',id:f.instance.id});assert.equal((await get()).records.find(r=>r.id===f.instance.id).status,'completed');
 const history=f.sqlite.prepare('SELECT snapshot FROM hris_development_events WHERE record_id=?').all(f.instance.id).map(x=>JSON.parse(x.snapshot));assert.ok(history.some(r=>r.referenceId===f.definition.id));assert.ok(history.some(r=>r.referenceId===f.next.id));
});
test('content update rejects scope leaks and preserves completed/cancelled/version-conflicting instances',async t=>{
 const f=await fixture(t);act('employee');await expect(await updates.POST(request('/api/learning-content-update',{revision:(await get()).revision,action:'preview',command:f.command})),403);act('manager');await expect(await updates.POST(request('/api/learning-content-update',{revision:(await get()).revision,action:'preview',command:f.command})),403);act('hr');
 await cmd(assign,{action:'cancelAssignment',id:f.instance.id,evidence:'合成暂停实例更新'});assert.equal((await update(f.command)).preview.canApply,false);await update(f.command,'apply',400);await cmd(assign,{action:'restoreAssignment',id:f.instance.id,evidence:'合成恢复原任务后检查'});
 await cmd(assign,{action:'assign',definitionId:f.next.id,employeeId:f.e.id});assert.ok((await update(f.command)).preview.blockers.some(s=>s.includes('已有目标版本')));await update(f.command,'apply',400);
 const {previewLearningContentUpdate}=await import('../lib/hris/learning-content-update.ts');const {developmentContext}=await import('../lib/hris/development-repository.ts');const ctx=await developmentContext(['learningAssignment','learningDefinition','enrollment','course','learningExamDefinition','learningExamTask'],['admin','hr']);const base=ctx.records.filter(r=>!(r.kind==='learningAssignment'&&r.id!==f.instance.id));
 for(const [changed,text] of [[{...f.instance,status:'completed'},'已结项'],[{...f.instance,payload:{...f.instance.payload,due:'2020-01-01'}},'已到期']])assert.ok(previewLearningContentUpdate(base.map(r=>r.id===changed.id?changed:r),ctx.state,ctx.member,f.command).blockers.some(s=>s.includes(text)));
 const target=base.find(r=>r.id===f.next.id);const removed={...target,payload:{...target.payload,courseIds:[],learningRequirements:target.payload.learningRequirements.filter(r=>r.kind==='exam')}};assert.equal(previewLearningContentUpdate(base.map(r=>r.id===removed.id?removed:r),ctx.state,ctx.member,f.command).removed.length,1);
 const other={...target,payload:{...target.payload,orgId:f.otherOrg.id}};assert.throws(()=>previewLearningContentUpdate(base.map(r=>r.id===other.id?other:r),ctx.state,ctx.member,f.command),/管理权限/);
 const exited={...ctx.state,employees:ctx.state.employees.map(e=>e.id===f.e.id?{...e,status:'离职'}:e)};assert.equal(previewLearningContentUpdate(base,exited,ctx.member,f.command).canApply,false);
});


test('content update binds new course and homework with an independent reviewer and keeps all original deadlines',async t=>{
 const f=await fixture(t);act('owner');await core({action:'employee',code:'U-REVIEW',name:'合成内容更新批阅人',orgId:f.org.id,job:'批阅人',level:'',joined:'2026-01-01',email:''});const reviewer=(await expect(await hris.GET())).state.employees.find(e=>e.code==='U-REVIEW');await grant('updateReviewer','employee',reviewer.id);
 const homework=await import('../app/api/learning-homework/route.ts'),description='使用合成资料完成业务实践并说明判断依据，本任务必须由独立批阅人核验。';
 const hw=(await cmd(homework,{action:'create',title:'内容更新新增作业',orgId:f.org.id,content:description,maxSubmissions:2})).ids[0];await cmd(homework,{action:'seal',id:hw});const course=await send({action:'course',code:'UPDATE-NEW',title:'内容更新新增课程',description:'追加课程要求',content:description});await send({action:'publishCourse',id:course.id});
 const next=await cmd(plans,{action:'revise',id:f.next.id});await cmd(plans,{action:'edit',id:next.id,title:'追加三类内容',orgId:f.org.id,courseIds:[f.course.id,course.id],examIds:[f.exam.id],homeworkIds:[hw],config:f.config});await cmd(plans,{action:'seal',id:next.id});const command={assignmentId:f.instance.id,definitionId:next.id};
 assert.equal((await update(command)).preview.canApply,false);await update({...command,homeworkReviewers:{[hw]:f.e.id}},'apply',400);const valid={...command,homeworkReviewers:{[hw]:reviewer.id}};assert.equal((await update(valid)).preview.canApply,true);const applied=await update(valid,'apply');assert.equal(applied.ids.length,4);
 let rows=(await get()).records,newTasks=rows.filter(r=>r.payload.learningAssignmentId===f.instance.id);assert.equal(newTasks.length,4);assert.ok(newTasks.every(r=>r.payload.due===f.instance.payload.due));const hwTask=newTasks.find(r=>r.kind==='homeworkTask');assert.equal(hwTask.payload.reviewerEmployeeId,reviewer.id);assert.equal(newTasks.find(r=>r.referenceId===course.id).status,'active');
 act('employee');await cmd(homework,{action:'submit',id:hwTask.id,content:description});let submission=(await expect(await homework.GET())).records.find(r=>r.kind==='homeworkSubmission');act('updateReviewer');await cmd(homework,{action:'review',id:hwTask.id,submissionId:submission.id,accepted:true,score:88,evidence:'独立核验新增作业符合要求'});act('hr');await cmd(assign,{action:'closeAssignment',id:f.instance.id},400);assert.equal((await get()).records.find(r=>r.id===hwTask.id).status,'completed');
});


test('content retirement preserves passed course and failed exam history and credit while replacing requirements atomically',async t=>{
 const f=await fixture(t);const credits=await import('../app/api/learning-credits/route.ts'),self=await import('../app/api/self-service/route.ts'),reports=await import('../app/api/reports/route.ts');act('employee');await send({action:'submitLearning',id:f.enrollment.id,evidence:'合成课程成果完整并已提交'});act('hr');await send({action:'verifyLearning',id:f.enrollment.id,accepted:true,evidence:'独立核验完成，随后保留原核验'});await cmd(credits,{action:'policy',courseId:f.course.id,creditUnits:2,evidence:'合成课程学分规则'});await cmd(credits,{action:'award',enrollmentId:f.enrollment.id,evidence:'原课程完成后独立登记学分'});const award=(await get()).records.find(r=>r.kind==='learningCredit');
 await update(f.command,'apply');let rows=(await get()).records,examTask=rows.find(r=>r.kind==='learningExamTask');act('employee');await cmd(tasks,{action:'submit',id:examTask.id,answers:[1]});act('hr');const attempt=(await get()).records.find(r=>r.kind==='learningExamAttempt');
 const replacement=await send({action:'course',code:'REPLACE',title:'替换后的新课程',description:'替换内容验证',content:'这是新的课程版本要求，不能把原课程成果直接视为此课程完成。'});await send({action:'publishCourse',id:replacement.id});const next=await cmd(plans,{action:'revise',id:f.next.id});await cmd(plans,{action:'edit',id:next.id,title:'替换为新课程',orgId:f.org.id,courseIds:[replacement.id],examIds:[],homeworkIds:[],config:f.config});await cmd(plans,{action:'seal',id:next.id});const command={assignmentId:f.instance.id,definitionId:next.id};const preview=await update(command);assert.equal(preview.preview.removed.length,2);assert.equal(preview.preview.added.length,1);assert.equal(preview.preview.canApply,true);
 const before=(await get()).revision;f.sqlite.exec("CREATE TRIGGER retire_fail BEFORE INSERT ON hris_development_events BEGIN SELECT RAISE(ABORT,'synthetic retirement failure'); END");await update(command,'apply',503);f.sqlite.exec('DROP TRIGGER retire_fail');assert.equal((await get()).revision,before);assert.equal((await get()).records.find(r=>r.id===examTask.id).payload.requirementRetiredAt,undefined);
 await update(command,'apply');rows=(await get()).records;assert.deepEqual(rows.find(r=>r.id===award.id),award);assert.deepEqual(rows.find(r=>r.id===attempt.id),attempt);assert.equal(rows.find(r=>r.id===f.enrollment.id).status,'completed');assert.ok(rows.find(r=>r.id===examTask.id).payload.requirementRetiredAt);await cmd(credits,{action:'award',enrollmentId:f.enrollment.id,evidence:'退出不能再次授予学分'},400);await cmd(tasks,{action:'cancel',id:examTask.id,evidence:'退出任务不能改变原状态'},400);await send({action:'restoreEnrollment',id:f.enrollment.id,due:f.instance.payload.due,evidence:'退出要求不能恢复到原计划'},400);
 act('employee');assert.ok(!(await expect(await self.GET())).tasks.some(r=>r.id===examTask.id));await cmd(tasks,{action:'submit',id:examTask.id,answers:[0]},400);act('hr');await cmd(assign,{action:'cancelAssignment',id:f.instance.id,evidence:'取消仅处理当前有效要求'});await cmd(assign,{action:'restoreAssignment',id:f.instance.id,evidence:'恢复不能重新激活退出要求'});assert.ok((await get()).records.find(r=>r.id===examTask.id).payload.requirementRetiredAt);await cmd(assign,{action:'closeAssignment',id:f.instance.id},400);
 rows=(await get()).records;const task=rows.find(r=>r.kind==='enrollment'&&r.referenceId===replacement.id);act('employee');await send({action:'submitLearning',id:task.id,evidence:'新课程实践单独完成'});act('hr');await send({action:'verifyLearning',id:task.id,accepted:true,evidence:'新课程独立核验不借用旧课程'});await cmd(assign,{action:'closeAssignment',id:f.instance.id});const report=await expect(await reports.GET(request('/api/reports?dataset=learning')));assert.ok(report.columns.includes('退出要求时间'));assert.equal((await get()).records.find(r=>r.id===f.instance.id).status,'completed');
});

test('retired pending homework remains readable but cannot be reviewed, restored, reassigned or silently reintroduced',async t=>{
 const f=await fixture(t);act('owner');await core({action:'employee',code:'RET-REVIEW',name:'合成退出核验人',orgId:f.org.id,job:'批阅人',level:'',joined:'2026-01-01',email:''});const reviewer=(await expect(await hris.GET())).state.employees.find(e=>e.code==='RET-REVIEW');await grant('retireReviewer','employee',reviewer.id);
 const homework=await import('../app/api/learning-homework/route.ts'),inbox=await import('../app/api/work-inbox/route.ts'),description='合成作业保留提交成果，在计划内容移除后不得继续批准或恢复原待办。';
 const hw=(await cmd(homework,{action:'create',title:'待审后退出作业',orgId:f.org.id,content:description,maxSubmissions:2})).ids[0];await cmd(homework,{action:'seal',id:hw});
 const third=await cmd(plans,{action:'revise',id:f.next.id});await cmd(plans,{action:'edit',id:third.id,title:'追加待审作业',orgId:f.org.id,courseIds:[f.course.id],examIds:[],homeworkIds:[hw],config:f.config});await cmd(plans,{action:'seal',id:third.id});await update({assignmentId:f.instance.id,definitionId:third.id,homeworkReviewers:{[hw]:reviewer.id}},'apply');const task=(await get()).records.find(r=>r.kind==='homeworkTask');act('employee');await cmd(homework,{action:'submit',id:task.id,content:description});const submission=(await expect(await homework.GET())).records.find(r=>r.kind==='homeworkSubmission');act('hr');
 const fourth=await cmd(plans,{action:'revise',id:third.id});await cmd(plans,{action:'edit',id:fourth.id,title:'移除未审作业',orgId:f.org.id,courseIds:[f.course.id],examIds:[],homeworkIds:[],config:f.config});await cmd(plans,{action:'seal',id:fourth.id});await update({assignmentId:f.instance.id,definitionId:fourth.id},'apply');let rows=(await get()).records;assert.equal(rows.find(r=>r.id===task.id).status,'submitted');assert.deepEqual(rows.find(r=>r.id===submission.id),submission);
 act('retireReviewer');assert.ok((await expect(await homework.GET())).records.some(r=>r.id===submission.id));assert.ok(!(await expect(await inbox.GET(request('/api/work-inbox')))).items.some(r=>r.recordId===task.id));await cmd(homework,{action:'review',id:task.id,submissionId:submission.id,accepted:true,evidence:'内容已退出不能继续批阅'},400);act('hr');await cmd(homework,{action:'restore',id:task.id,evidence:'不允许恢复退出要求'},400);await cmd(homework,{action:'reassignReviewer',id:task.id,reviewerEmployeeId:reviewer.id,evidence:'退出要求不再转交批阅'},400);
 const fifth=await cmd(plans,{action:'revise',id:fourth.id});await cmd(plans,{action:'edit',id:fifth.id,title:'尝试重新加入原作业',orgId:f.org.id,courseIds:[f.course.id],examIds:[],homeworkIds:[hw],config:f.config});await cmd(plans,{action:'seal',id:fifth.id});const command={assignmentId:f.instance.id,definitionId:fifth.id,homeworkReviewers:{[hw]:reviewer.id}};assert.ok((await update(command)).preview.blockers.some(s=>s.includes('重新加入')));await update(command,'apply',400);
});

test('added course progress sync previews original evidence and preserves credit uniqueness without copying attempts',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const courses=[];for(let i=0;i<2;i++){const c=await send({action:'course',code:'SYNC-UP-'+i,title:'同步更新合成课程'+i,description:'版本同步更新',content:'合成课程完成后由独立人员核验，仅同版本已完成成果可以被同步引用。'});await send({action:'publishCourse',id:c.id});courses.push(c.id);}
 const origin=await send({action:'enroll',employeeId:f.e.id,courseId:courses[1],due:'2099-12-31'});act('employee');await send({action:'submitLearning',id:origin.id,evidence:'已完成第二门课程的原始实践'});act('hr');await send({action:'verifyLearning',id:origin.id,accepted:true,evidence:'独立核验原始同版本课程成果'});
 const config={mode:'relative',durationDays:30,allowOverdue:false,orderedStages:false,progressSync:true},first=await cmd(plans,{action:'create',title:'开启同步的内容更新',orgId:f.org.id,courseIds:[courses[0]],config});await cmd(plans,{action:'seal',id:first.id});await cmd(assign,{action:'assign',definitionId:first.id,employeeId:f.e.id});const instance=(await get()).records.find(r=>r.kind==='learningAssignment'),next=await cmd(plans,{action:'revise',id:first.id});await cmd(plans,{action:'edit',id:next.id,title:'同步追加第二门课程',orgId:f.org.id,courseIds:courses,config});await cmd(plans,{action:'seal',id:next.id});const command={assignmentId:instance.id,definitionId:next.id},before=await get(),preview=await update(command);assert.equal(preview.preview.reusedCourses.length,1);assert.equal(preview.preview.reusedCourses[0].sourceEnrollmentId,origin.id);assert.equal(preview.preview.afterProgress.completed,1);assert.equal((await get()).revision,before.revision);
 await update(command,'apply');const rows=(await get()).records,added=rows.find(r=>r.kind==='enrollment'&&r.referenceId===courses[1]&&r.payload.learningAssignmentId===instance.id);assert.equal(added.status,'completed');assert.equal(added.payload.sourceEnrollmentId,origin.id);assert.equal(rows.filter(r=>r.kind==='attempt'||r.kind==='learningCredit').length,0);assert.deepEqual(rows.find(r=>r.id===origin.id),before.records.find(r=>r.id===origin.id));
 const {reuseCompletedCourse}=await import('../lib/hris/learning-course-reuse.ts'),{developmentContext}=await import('../lib/hris/development-repository.ts');const ctx=await developmentContext(['enrollment','course','attempt','learningAssignment'],['admin','hr']),fresh={...added,status:'active',payload:{learningAssignmentId:instance.id,learningRequirementId:added.payload.learningRequirementId}};assert.equal(reuseCompletedCourse(fresh,ctx.records,ctx.state,ctx.member,false).status,'active');assert.equal(reuseCompletedCourse(fresh,ctx.records.filter(r=>r.id!==origin.id),ctx.state,ctx.member,true).status,'active');
});
