import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,core,grant,hris,dev,get,send,act,expect,request} from './support/foundation-scenario.mjs';
const {moveEmployee}=await import('./support/performance-scenario.mjs');
const plans=await import('../app/api/learning-plans/route.ts'),assign=await import('../app/api/learning-assignments/route.ts'),exams=await import('../app/api/learning-exams/route.ts'),examTasks=await import('../app/api/learning-exam-tasks/route.ts');
const reports=await import('../app/api/reports/route.ts'),profiles=await import('../app/api/cadre-profiles/route.ts');
const api=await import('../app/api/learning-homework/route.ts'),self=await import('../app/api/self-service/route.ts'),inbox=await import('../app/api/work-inbox/route.ts');
const {businessDate}=await import('../lib/hris/business-time.ts');
async function cmd(command,status=200){const d=await expect(await api.GET());return expect(await api.POST(request('/api/test',{revision:d.revision,command})),status);}
async function fixture(){const f=await setup();for(const code of ['C','D'])await core({action:'employee',code,name:'合成批阅人'+code,orgId:f.org.id,job:'批阅人',level:'',joined:'2026-01-01',email:''});const s=(await expect(await hris.GET())).state,reviewer=s.employees.find(e=>e.code==='C'),nextReviewer=s.employees.find(e=>e.code==='D');await grant('reviewer','employee',reviewer.id);await grant('reviewer2','employee',nextReviewer.id);return {...f,reviewer,nextReviewer};}
const description='根据合成案例形成完整实践报告，列出判断依据和行动结果；本作业不含真实人员资料。';
test('homework versions and submissions remain independent through return, reassignment and cancellation',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const definition=(await cmd({action:'create',title:'合成独立作业',orgId:f.org.id,content:description,maxSubmissions:3})).ids[0];await cmd({action:'seal',id:definition});
 await cmd({action:'assign',definitionId:definition,employeeId:f.e.id,reviewerEmployeeId:f.e.id,start:businessDate(),due:'2099-12-31'},400);
 const taskId=(await cmd({action:'assign',definitionId:definition,employeeId:f.e.id,reviewerEmployeeId:f.reviewer.id,start:businessDate(),due:'2099-12-31'})).ids[0];await cmd({action:'assign',definitionId:definition,employeeId:f.e.id,reviewerEmployeeId:f.reviewer.id,start:businessDate(),due:'2099-12-31'},400);
 act('employee');assert.ok((await expect(await self.GET())).tasks.some(t=>t.id===taskId));await cmd({action:'submit',id:taskId,content:description});await cmd({action:'submit',id:taskId,content:description},400);let rows=(await expect(await api.GET())).records;const first=rows.find(r=>r.kind==='homeworkSubmission');await cmd({action:'review',id:taskId,submissionId:first.id,accepted:true,evidence:'本人不能批阅自己的作业'},403);
 const {canReviewHomework}=await import('../lib/hris/learning-homework.ts');act('owner');const state=(await expect(await hris.GET())).state;const pendingTask=(await get()).records.find(r=>r.id===taskId);assert.equal(canReviewHomework(pendingTask,state,{role:'employee',employeeId:f.reviewer.id,userId:pendingTask.payload.submittedBy}),false);act('reviewer');assert.ok((await expect(await inbox.GET(request('/api/work-inbox')))).items.some(r=>r.recordId===taskId));await cmd({action:'review',id:taskId,submissionId:first.id,accepted:false,score:40,evidence:'需要补充实践判断的具体依据'});
 act('employee');await cmd({action:'submit',id:taskId,content:description+'第二次提交补充了判断依据。'});rows=(await expect(await api.GET())).records;const second=rows.find(r=>r.kind==='homeworkSubmission'&&r.payload.submissionVersion===2);assert.equal(rows.find(r=>r.id===first.id).status,'returned');assert.equal(rows.find(r=>r.id===taskId).payload.score,undefined);
 act('reviewer');await cmd({action:'review',id:taskId,submissionId:first.id,accepted:true,evidence:'旧提交版本不能覆盖当前批阅'},400);
 act('hr');await cmd({action:'cancel',id:taskId,evidence:'合成暂停以检查待审版本保留'});act('reviewer');await cmd({action:'review',id:taskId,submissionId:second.id,accepted:true,evidence:'暂停期间不允许批阅'},403);act('hr');await cmd({action:'restore',id:taskId,evidence:'恢复同一作业及原待审提交'});assert.equal((await expect(await api.GET())).records.find(r=>r.id===taskId).status,'submitted');
 await cmd({action:'reassignReviewer',id:taskId,reviewerEmployeeId:f.nextReviewer.id,evidence:'合成批阅职责转交给另一位人员'});act('reviewer');assert.equal((await expect(await api.GET())).records.length,0);await expect(await dev.GET(request('/api/development?id='+second.id)),403);await expect(await dev.GET(request('/api/development?id='+taskId)),403);assert.ok(!(await expect(await inbox.GET(request('/api/work-inbox')))).items.some(r=>r.recordId===taskId));await cmd({action:'review',id:taskId,submissionId:second.id,accepted:true,evidence:'旧批阅人不得继续审批'},403);
 act('reviewer2');assert.equal((await expect(await api.GET())).records.filter(r=>r.kind==='homeworkSubmission').length,2);await cmd({action:'review',id:taskId,submissionId:second.id,accepted:true,score:0,evidence:'通过结论与可选评分分别记录'});await cmd({action:'review',id:taskId,submissionId:second.id,accepted:true,evidence:'重复审批不允许'},403);
 act('hr');rows=(await get()).records;assert.equal(rows.find(r=>r.id===taskId).status,'completed');assert.equal(rows.find(r=>r.id===taskId).payload.score,0);const report=await expect(await reports.GET(request('/api/reports?dataset=homework')));assert.equal(report.rows[0][10],0);const profile=await expect(await profiles.GET(request('/api/cadre-profiles?employeeId='+f.e.id)));assert.ok(profile.sections.find(s=>s.key==='homework').items.some(i=>i.id===taskId));assert.ok(!rows.some(r=>r.kind==='enrollment'||r.kind==='learningCredit'));
 const next=(await cmd({action:'revise',id:definition})).ids[0];await cmd({action:'edit',id:next,title:'新版独立作业',orgId:f.org.id,content:description+'新版要求。',maxSubmissions:2});assert.equal((await get()).records.find(r=>r.id===taskId).payload.content,description);
});
test('homework audit failure rolls back both records and reviewer transfer removes access and actionable tasks',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const definition=(await cmd({action:'create',title:'故障与越权合成作业',orgId:f.org.id,content:description,maxSubmissions:1})).ids[0];await cmd({action:'seal',id:definition});const taskId=(await cmd({action:'assign',definitionId:definition,employeeId:f.e.id,reviewerEmployeeId:f.reviewer.id,start:businessDate(),due:'2099-12-31'})).ids[0];
 const before=(await get()).records.length,revision=(await get()).revision;f.sqlite.exec("CREATE TRIGGER homework_audit_failure BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic homework audit failure'); END");act('employee');await cmd({action:'submit',id:taskId,content:description},503);f.sqlite.exec('DROP TRIGGER homework_audit_failure');act('owner');assert.equal((await get()).records.length,before);assert.equal((await get()).revision,revision);
 act('employee');await cmd({action:'submit',id:taskId,content:description});act('reviewer');const submission=(await expect(await api.GET())).records.find(r=>r.kind==='homeworkSubmission');await cmd({action:'review',id:taskId,submissionId:submission.id,accepted:false,evidence:'达到配置次数后不允许重交'});act('employee');await cmd({action:'submit',id:taskId,content:description},400);assert.ok(!(await expect(await self.GET())).tasks.some(r=>r.id===taskId));
 await moveEmployee({...f,e:f.reviewer},'transfer');act('reviewer');assert.equal((await expect(await api.GET())).records.length,0);act('hr');await cmd({action:'reassignReviewer',id:taskId,reviewerEmployeeId:f.nextReviewer.id,evidence:'转交给原组织有效批阅人员'});act('reviewer2');assert.ok((await expect(await api.GET())).records.some(r=>r.id===taskId));
});

async function otherCmd(api,command,status=200){const d=await expect(await api.GET());return expect(await api.POST(request('/api/test',{revision:d.revision,command})),status);}
test('homework requirements bind mixed plans, keep submission release distinct from completion and survive instance recovery',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());
 const homework=(await cmd({action:'create',title:'计划独立作业',orgId:f.org.id,content:description,maxSubmissions:3})).ids[0];await cmd({action:'seal',id:homework});
 const course=await send({action:'course',code:'HWCOURSE',title:'作业后的实践',description:'合成课程与作业要求',content:description});await send({action:'publishCourse',id:course.id});
 const exam=await otherCmd(exams,{action:'create',title:'末阶段独立考试',orgId:f.org.id,questions:[{prompt:'合成任务如何核验',options:['独立核验','自行核验'],correct:0}],passingScore:80,maxAttempts:2});await otherCmd(exams,{action:'seal',id:exam.id});
 const config={mode:'recurring',durationDays:30,allowOverdue:false,orderedStages:true,progressSync:true,repeatCredit:false,repeatPoints:false};
 const plan=await otherCmd(plans,{action:'create',title:'作业课程考试混合闭环',orgId:f.org.id,courseIds:[course.id],examIds:[exam.id],homeworkIds:[homework],config});
 await otherCmd(plans,{action:'edit',id:plan.id,title:'作业课程考试混合闭环',orgId:f.org.id,courseIds:[course.id],examIds:[exam.id],config});assert.deepEqual((await expect(await plans.GET())).records.find(r=>r.id===plan.id).payload.homeworkIds,[homework]);
 const gradeRule={mode:'contentWeighted',attempts:'passed',decimals:2,items:[{requirementId:'homework:'+homework,source:'homeworkLatest',weight:60},{requirementId:'exam:'+exam.id,source:'examHighest',weight:40}]};
 await otherCmd(plans,{action:'grading',id:plan.id,rule:{...gradeRule,items:[{requirementId:'course:'+course.id,source:'homeworkLatest',weight:100}]}},400);
 await otherCmd(plans,{action:'grading',id:plan.id,rule:gradeRule});
 await otherCmd(plans,{action:'stages',id:plan.id,stages:[{title:'作业与实践',courseIds:[homework,course.id],orderedTasks:true,homeworkSubmissionUnlock:true},{title:'独立考试',courseIds:[exam.id]}]});await otherCmd(plans,{action:'seal',id:plan.id});
 const before=(await get()).records.length;await otherCmd(assign,{action:'assign',definitionId:plan.id,employeeId:f.e.id},400);await otherCmd(assign,{action:'assign',definitionId:plan.id,employeeId:f.e.id,homeworkReviewers:{[homework]:f.e.id}},400);assert.equal((await get()).records.length,before);
 await otherCmd(assign,{action:'assign',definitionId:plan.id,employeeId:f.e.id,homeworkReviewers:{[homework]:f.reviewer.id}});let rows=(await get()).records;const instance=rows.find(r=>r.kind==='learningAssignment'),task=rows.find(r=>r.kind==='homeworkTask'),enrollment=rows.find(r=>r.kind==='enrollment'),examTask=rows.find(r=>r.kind==='learningExamTask');
 assert.equal(task.payload.learningRequirementId,'homework:'+homework);act('employee');await send({action:'submitLearning',id:enrollment.id,evidence:'作业尚未提交不得提前实践'},400);await cmd({action:'submit',id:task.id,content:description});await send({action:'submitLearning',id:enrollment.id,evidence:'已提交作业，完成课程实践成果'});
 act('hr');await send({action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'独立核验课程成果，作业尚待批阅'});await otherCmd(assign,{action:'closeAssignment',id:instance.id},400);act('employee');assert.equal((await expect(await examTasks.GET())).papers.length,0);await otherCmd(examTasks,{action:'submit',id:examTask.id,answers:[0]},400);
 act('hr');await cmd({action:'cancel',id:task.id,evidence:'先单独取消作业保留原待审状态'});await otherCmd(assign,{action:'cancelAssignment',id:instance.id,evidence:'整单取消保留作业待审提交'});act('reviewer');const submission=(await expect(await api.GET())).records.find(r=>r.kind==='homeworkSubmission');await cmd({action:'review',id:task.id,submissionId:submission.id,accepted:true,evidence:'实例取消后不得继续批阅'},403);act('hr');await otherCmd(assign,{action:'restoreAssignment',id:instance.id,evidence:'恢复原作业提交而不生成新版本'});assert.equal((await expect(await api.GET())).records.find(r=>r.id===task.id).status,'cancelled');await cmd({action:'restore',id:task.id,evidence:'整单恢复后再恢复单独取消的作业'});assert.equal((await expect(await api.GET())).records.find(r=>r.id===task.id).status,'submitted');await otherCmd(assign,{action:'cancelAssignment',id:instance.id,evidence:'再次整单暂停核对待审状态'});await otherCmd(assign,{action:'restoreAssignment',id:instance.id,evidence:'整体恢复应恢复待审而非待提交'});assert.equal((await expect(await api.GET())).records.find(r=>r.id===task.id).status,'submitted');
 act('reviewer');await cmd({action:'review',id:task.id,submissionId:submission.id,accepted:true,score:85,evidence:'独立批阅作业达到本轮要求'});act('employee');assert.equal((await expect(await examTasks.GET())).papers.length,1);await otherCmd(examTasks,{action:'submit',id:examTask.id,answers:[0]});act('hr');await otherCmd(assign,{action:'closeAssignment',id:instance.id});
 const gradeReport=await expect(await reports.GET(request('/api/reports?dataset=learningPlanProgress')));assert.equal(gradeReport.rows[0][10],91);
 const {learningRequirementProgress}=await import('../lib/hris/learning-requirements.ts');rows=(await get()).records;assert.equal(learningRequirementProgress(instance,rows).complete,true);assert.equal(learningRequirementProgress(instance,rows.filter(r=>r.id!==submission.id)).complete,false);
 await otherCmd(assign,{action:'nextRound',id:instance.id,start:businessDate()});rows=(await get()).records;const second=rows.find(r=>r.kind==='learningAssignment'&&r.payload.round===2),secondWork=rows.find(r=>r.kind==='homeworkTask'&&r.payload.learningAssignmentId===second.id);assert.equal(secondWork.status,'active');assert.equal(secondWork.payload.submissionVersion,0);assert.equal(secondWork.payload.reviewerEmployeeId,f.reviewer.id);assert.notEqual(secondWork.id,task.id);const revised=await otherCmd(plans,{action:'revise',id:plan.id});await otherCmd(plans,{action:'edit',id:revised.id,title:'移除作业的新版本',orgId:f.org.id,courseIds:[course.id],examIds:[exam.id],homeworkIds:[],config});assert.equal((await expect(await plans.GET())).records.find(r=>r.id===revised.id).payload.gradeRule,undefined);
});
