import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,core,grant,hris,get,send,act,expect,request} from './support/foundation-scenario.mjs';
const plans=await import('../app/api/learning-plans/route.ts'),assign=await import('../app/api/learning-assignments/route.ts'),exams=await import('../app/api/learning-exams/route.ts'),homework=await import('../app/api/learning-homework/route.ts');
const {learningStageDeadline,learningStageSubmissionOpen}=await import('../lib/hris/learning-requirements.ts');
async function cmd(api,command,status=200){const d=await expect(await api.GET());return expect(await api.POST(request('/api/test',{revision:d.revision,command})),status);}
test('explicit scheduled-inclusive stage deadlines preserve China calendar boundaries and legacy open-ended stages',()=>{
 const stage={title:'阶段',courseIds:['course'],startAfterDays:2,deadline:{days:2,allowOverdue:false,policy:'scheduled-inclusive'}};
 const assignment={id:'instance',kind:'learningAssignment',createdAt:'2026-09-01T16:00:00Z',payload:{start:'2026-09-01',learningMode:{mode:'relative'},trainingStages:[stage]}},task={payload:{learningAssignmentId:'instance'},referenceId:'course'};
 assert.equal(learningStageDeadline(assignment,stage),'2026-09-05');assert.equal(learningStageSubmissionOpen(task,[assignment],'2026-09-05T15:59:59Z'),true);assert.equal(learningStageSubmissionOpen(task,[assignment],'2026-09-05T16:00:00Z'),false);
 assert.equal(learningStageSubmissionOpen(task,[{...assignment,payload:{...assignment.payload,trainingStages:[{...stage,deadline:undefined}]}}],'2099-01-01T00:00:00Z'),true);
 assert.equal(learningStageSubmissionOpen(task,[{...assignment,payload:{...assignment.payload,trainingStages:[{...stage,deadline:{...stage.deadline,allowOverdue:true}}]}}],'2026-09-06T00:00:00Z'),true);
 const fixed={...assignment,payload:{...assignment.payload,learningMode:{mode:'fixed',start:'2026-09-01'}}};assert.equal(learningStageDeadline(fixed,stage),'2026-09-04');
});
test('stage expiry blocks new course/exam/homework submissions but preserves independent review of already submitted work',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());await core({action:'employee',code:'D-REVIEW',name:'合成阶段批阅人',orgId:f.org.id,job:'批阅人',level:'',joined:'2026-01-01',email:''});const reviewer=(await expect(await hris.GET())).state.employees.find(e=>e.code==='D-REVIEW');await grant('stageReviewer','employee',reviewer.id);
 const course=await send({action:'course',code:'DEADLINE',title:'限时课程',description:'阶段期限核对',content:'合成课程提交发生在期限内，独立核验可以在提交期限之后处理。'});await send({action:'publishCourse',id:course.id});const exam=await cmd(exams,{action:'create',title:'限时考试',orgId:f.org.id,questions:[{prompt:'应如何处理合成任务',options:['独立核验','自审'],correct:0}],passingScore:80,maxAttempts:2});await cmd(exams,{action:'seal',id:exam.id});const hw=(await cmd(homework,{action:'create',title:'限时作业',orgId:f.org.id,content:'用合成业务案例完成实践报告并提交，由独立指定批阅人核验处理。',maxSubmissions:2})).ids[0];await cmd(homework,{action:'seal',id:hw});
 const definition=await cmd(plans,{action:'create',title:'单日阶段期限',orgId:f.org.id,courseIds:[course.id],examIds:[exam.id],homeworkIds:[hw],config:{mode:'relative',durationDays:30,allowOverdue:false,orderedStages:false,progressSync:false}}),stage={title:'提交阶段',courseIds:[course.id,exam.id,hw],deadline:{days:1,allowOverdue:false,policy:'scheduled-inclusive'}};await cmd(plans,{action:'stages',id:definition.id,stages:[{...stage,deadline:{...stage.deadline,policy:'unknown'}}]},400);await cmd(plans,{action:'stages',id:definition.id,stages:[stage]});await cmd(plans,{action:'seal',id:definition.id});await cmd(assign,{action:'assign',definitionId:definition.id,employeeId:f.e.id,homeworkReviewers:{[hw]:reviewer.id}});
 const {developmentContext}=await import('../lib/hris/development-repository.ts'),{applyDevelopment}=await import('../lib/hris/development.ts'),{applyHomework}=await import('../lib/hris/learning-homework.ts'),{applyLearningExamTask}=await import('../lib/hris/learning-exam-tasks.ts');
 const kinds=['learningAssignment','learningDefinition','enrollment','course','exam','attempt','learningExamDefinition','learningExamTask','learningExamAttempt','homeworkDefinition','homeworkTask','homeworkSubmission'];act('hr');const hr=(await developmentContext(kinds,['hr','admin'])).member;act('stageReviewer');const marker=(await developmentContext(kinds)).member;act('employee');const c=await developmentContext(kinds),rows=c.records,instance=rows.find(r=>r.kind==='learningAssignment'),enrollment=rows.find(r=>r.kind==='enrollment'),examTask=rows.find(r=>r.kind==='learningExamTask'),hwTask=rows.find(r=>r.kind==='homeworkTask'),now=new Date().toISOString(),later=new Date(Date.parse(now)+86400000).toISOString();
 assert.throws(()=>applyDevelopment(rows,c.state,c.member,{action:'submitLearning',id:enrollment.id,evidence:'期限之后不能再提交新成果'},later),/期间/);assert.throws(()=>applyLearningExamTask(rows,c.state,c.member,{action:'submit',id:examTask.id,answers:[0]},later),/关闭|过期/);assert.throws(()=>applyHomework(rows,c.state,c.member,{action:'submit',id:hwTask.id,content:'超出阶段提交期限的新作业不得被保存，仍应保留旧有历史。'},later),/不可提交/);
 const submitted=applyDevelopment(rows,c.state,c.member,{action:'submitLearning',id:enrollment.id,evidence:'期限内提交合成实践成果'},now),courseRows=rows.map(r=>r.id===submitted.id?submitted:r);assert.equal(applyDevelopment(courseRows,c.state,hr,{action:'verifyLearning',id:enrollment.id,accepted:true,evidence:'提交期限后独立核验此前成果'},later).status,'completed');
 const changes=applyHomework(rows,c.state,c.member,{action:'submit',id:hwTask.id,content:'期限内提交完整合成作业，审批可以在截止之后独立办理。'},now),workRows=[...rows.filter(r=>!changes.some(x=>x.id===r.id)),...changes],submission=changes.find(r=>r.kind==='homeworkSubmission');assert.equal(applyHomework(workRows,c.state,marker,{action:'review',id:hwTask.id,submissionId:submission.id,accepted:true,evidence:'期限后批阅已提交作业'},later).find(r=>r.kind==='homeworkTask').status,'completed');
 const allowed={...instance,payload:{...instance.payload,trainingStages:[{...stage,deadline:{...stage.deadline,allowOverdue:true}}]}};assert.equal(applyLearningExamTask(rows.map(r=>r.id===instance.id?allowed:r),c.state,c.member,{action:'submit',id:examTask.id,answers:[0]},later).find(r=>r.kind==='learningExamTask').status,'completed');
});

test('expired incomplete stage configurations cannot create fresh instances or migrate live instances into closed submission windows',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const course=await send({action:'course',code:'PAST-STAGE',title:'合成过期阶段',description:'过期窗口防护',content:'该场景使用合成日期验证不能派发已过期且无法完成的阶段内容。'});await send({action:'publishCourse',id:course.id});
 const config={mode:'fixed',start:'2020-01-01',end:'2099-12-31',progressSync:false,orderedStages:false},definition=await cmd(plans,{action:'create',title:'固定模式阶段已过期',orgId:f.org.id,courseIds:[course.id],config});await cmd(plans,{action:'stages',id:definition.id,stages:[{title:'过期阶段',courseIds:[course.id],deadline:{days:1,allowOverdue:false,policy:'scheduled-inclusive'}}]});await cmd(plans,{action:'seal',id:definition.id});const before=await get();await cmd(assign,{action:'assign',definitionId:definition.id,employeeId:f.e.id},400);assert.equal((await get()).revision,before.revision);assert.equal((await get()).records.length,before.records.length);
 const next=await cmd(plans,{action:'revise',id:definition.id});await cmd(plans,{action:'stages',id:next.id,stages:[{title:'允许超期阶段',courseIds:[course.id],deadline:{days:1,allowOverdue:true,policy:'scheduled-inclusive'}}]});await cmd(plans,{action:'seal',id:next.id});await cmd(assign,{action:'assign',definitionId:next.id,employeeId:f.e.id});const instance=(await get()).records.find(r=>r.kind==='learningAssignment');
 const third=await cmd(plans,{action:'revise',id:next.id});await cmd(plans,{action:'stages',id:third.id,stages:[{title:'重新关闭的阶段',courseIds:[course.id],deadline:{days:1,allowOverdue:false,policy:'scheduled-inclusive'}}]});await cmd(plans,{action:'seal',id:third.id});const updates=await import('../app/api/learning-content-update/route.ts'),data=await get(),body={revision:data.revision,action:'preview',command:{assignmentId:instance.id,definitionId:third.id}};const preview=await expect(await updates.POST(request('/api/learning-content-update',body)));assert.ok(preview.preview.blockers.some(s=>s.includes('已经截止')));await expect(await updates.POST(request('/api/learning-content-update',{...body,action:'apply',evidence:'不能把实例变为过期不可办理'})),400);assert.equal((await get()).revision,data.revision);
});
