import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,dev} from './support/foundation-scenario.mjs';
import {moveEmployee} from './support/performance-scenario.mjs';
const api=await import('../app/api/attendance/route.ts');
async function post(command,status=200,revision){return expect(await api.POST(request('/api/attendance',{revision:revision??(await get()).revision,command})),status);}
const definition=f=>({action:'leaveType',code:'SYNTHETIC-SCOPED',name:'合成组织限时假',orgId:f.org.id,paid:true,requiresBalance:true,minMinutes:60,maxMinutes:120,policyText:'合成制度：按班次扣除休息后的工作分钟核验，非企业正式规则。'});
async function fixture(){const f=await setup(),type=await post(definition(f)),shift=await post({action:'shift',employeeId:f.e.id,date:'2026-01-05',name:'合成午休班',startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T18:00:00+08:00',breakStart:'2026-01-05T12:00:00+08:00',breakEnd:'2026-01-05T13:00:00+08:00'});await post({action:'leaveCredit',employeeId:f.e.id,leaveTypeId:type.id,year:2026,minutes:240,source:'合成已核验期初额度四小时'});return {...f,type,shift};}
const leave=f=>({action:'leave',employeeId:f.e.id,shiftId:f.shift.id,leaveTypeId:f.type.id,startAt:'2026-01-05T11:00:00+08:00',endAt:'2026-01-05T14:00:00+08:00',reason:'合成休假扣除午休后正好两小时'});
test('duration limits use working minutes after rest; historical application freezes the exact rule',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());act('employee');await post({...leave(f),startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T09:30:00+08:00'},400);await post({...leave(f),startAt:'2026-01-05T10:00:00+08:00'},400);const l=await post(leave(f)),r=(await get()).records.find(r=>r.id===l.id);assert.equal(r.payload.minutes,120);assert.equal(r.payload.leaveTypeSnapshot.rules.maxMinutes,120);assert.equal((await expect(await api.GET())).balances[0].reserved,120);await post({action:'decideLeave',id:l.id,accepted:true,evidence:'本人仍不能核验自己的申请'},403);act('manager');await post({action:'decideLeave',id:l.id,accepted:true,evidence:'独立核实合成休假时段和工作分钟'});const history=await expect(await dev.GET(new Request('https://hris.example/api/development?id='+l.id)));assert.ok(history.items.every(e=>e.snapshot.payload.leaveTypeSnapshot.rules.policyText===definition(f).policyText));});
test('scoped HR cannot create global or foreign rules; managers cannot retire; foreign staff cannot use the definition',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());act('hr');await post({...definition(f),code:'NO-GLOBAL',orgId:undefined},403);await post({...definition(f),code:'NO-FOREIGN',orgId:f.otherOrg.id},403);await post({...definition(f),code:'BAD-LIMIT',minMinutes:121,maxMinutes:120},400);act('manager');await post({action:'retireLeaveType',id:f.type.id,reason:'经理不能维护组织假期规则'},403);act('owner');await post({action:'leaveCredit',employeeId:f.other.id,leaveTypeId:f.type.id,year:2026,minutes:60,source:'不能跨组织登记不适用额度'},400);const foreign=await post({...definition(f),code:'FOREIGN',orgId:f.otherOrg.id});act('employee');assert.ok(!(await expect(await api.GET())).records.some(r=>r.id===foreign.id));await expect(await dev.GET(new Request('https://hris.example/api/development?id='+foreign.id)),403);await post({...leave(f),leaveTypeId:foreign.id},403);});
test('retirement blocks new requests and credits but retains pending independent decisions, reversals and balances',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());act('employee');const l=await post(leave(f));act('owner');await post({action:'retireLeaveType',id:f.type.id,reason:'合成假种停止新增，保留历史审批与余额'});await post({action:'leaveCredit',employeeId:f.e.id,leaveTypeId:f.type.id,year:2026,minutes:60,source:'停止新增后不能继续登记额度'},400);act('employee');await post({...leave(f),startAt:'2026-01-05T09:00:00+08:00',endAt:'2026-01-05T10:00:00+08:00'},400);act('manager');await post({action:'decideLeave',id:l.id,accepted:true,evidence:'按原申请冻结规则独立核验'});await post({action:'cancelApprovedLeave',id:l.id,reason:'合成申请最终未发生，保留更正依据'});assert.equal((await expect(await api.GET())).balances[0].available,240);});
test('transfer hides old organization rules but keeps own credited balance and rule snapshots readable',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());await moveEmployee(f,'transfer');act('employee');const d=await expect(await api.GET());assert.ok(!d.records.some(r=>r.id===f.type.id));assert.equal(d.balances[0].available,240);assert.equal(d.records.find(r=>r.kind==='leaveCredit').payload.leaveTypeSnapshot.name,definition(f).name);await post(leave(f),403);act('owner');await post(leave(f),400);});
