import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,dev} from './support/foundation-scenario.mjs';
import {perf,performance,cycleInput,goals,change,revisedGoals} from './support/performance-scenario.mjs';
const api=await import('../app/api/performance-templates/route.ts');
async function template(command,status=200){return expect(await api.POST(request('/api/performance-templates',{revision:(await get()).revision,command})),status);}
const fields=f=>({title:'合成单维文本模板',orgId:f.org.id,description:'仅合成模板，不改变既有加权公式',prompts:[{id:'selfProof',title:'本人关键成果',stage:'selfReview',required:true},{id:'reviewProof',title:'独立核实意见',stage:'evaluation',required:true}]});
async function fixture(){const f=await setup(),d=await template({action:'create',...fields(f)});await template({action:'seal',id:d.id});const cy=await perf({...cycleInput(f.org.id),templateId:d.id});await perf({action:'startCycle',id:cy.id});act('employee');const p=await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals});act('manager');await perf({action:'confirmGoals',id:p.id});act('owner');return {...f,d,cy,p};}
test('sealed template snapshots enforce stage-specific required responses and hide unpublished management responses',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());await template({action:'archive',id:f.d.id,reason:'旧模板停用但已有活动保留快照'});act('employee');await perf({action:'selfReview',id:f.p.id,evidence:'合成自评不能漏填必填文本'},400);await perf({action:'selfReview',id:f.p.id,responses:{selfProof:'合成果',reviewProof:'不能替管理者录入'},evidence:'拒绝写入非本人阶段文本'},400);await perf({action:'selfReview',id:f.p.id,responses:{selfProof:'合成已交付事实'},evidence:'另有合成自评总述依据'});act('manager');await perf({action:'evaluate',id:f.p.id,scores:[70,80],evidence:'缺少管理必填项应该拒绝'},400);await perf({action:'evaluate',id:f.p.id,scores:[70,80],responses:{reviewProof:'合成管理核实内容'},evidence:'独立核实合成评分依据'});act('employee');assert.equal((await expect(await performance.GET())).records.find(r=>r.id===f.p.id).payload.evaluationResponses,undefined);const history=await expect(await dev.GET(new Request('https://hris.example/api/development?id='+f.p.id)));assert.ok(history.items.every(e=>e.snapshot.payload.evaluationResponses===undefined));act('owner');const result=await perf({action:'publishPerformance',id:f.p.id,evidence:'核对合成模板与评价后正式发布'});act('employee');const published=(await get()).records.find(r=>r.id===result.id);assert.equal(published.payload.performanceSnapshot.cycle.performanceTemplate.version,1);assert.equal(published.payload.performanceSnapshot.plan.evaluationResponses.reviewProof,'合成管理核实内容');assert.equal(published.payload.score,74);});
test('template revisions cannot silently replace active cycles; archived drafts do not trap future version numbers',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());await perf({...cycleInput(f.org.id),action:'editCycle',id:f.cy.id,templateId:null},400);await template({action:'edit',id:f.d.id,...fields(f)},400);const v2=await template({action:'revise',id:f.d.id});await template({action:'archive',id:v2.id,reason:'丢弃合成修订草稿但保留版本'});const v3=await template({action:'revise',id:f.d.id});assert.equal((await get()).records.find(r=>r.id===v3.id).payload.version,3);await template({action:'edit',id:v3.id,...fields(f),prompts:[]});await template({action:'seal',id:v3.id});assert.equal((await get()).records.find(r=>r.id===f.cy.id).payload.performanceTemplate.prompts.length,2);const draft=await perf({...cycleInput(f.org.id,'NEW-TEMPLATE-CYCLE'),templateId:v3.id});assert.equal((await get()).records.find(r=>r.id===draft.id).payload.performanceTemplate.version,3);await template({action:'archive',id:v3.id,reason:'已引用的模板版本停止新选择'});await perf({...cycleInput(f.org.id,'NEW-TEMPLATE-CYCLE'),action:'editCycle',id:draft.id,name:'修改草稿名称仍保留模板'});assert.equal((await get()).records.find(r=>r.id===draft.id).payload.performanceTemplate.version,3);});
test('template boundaries reject foreign scope and duplicate IDs; draft edits and response writes are atomic',async t=>{const f=await fixture();t.after(()=>f.sqlite.close());act('hr');await template({action:'create',...fields(f),orgId:f.otherOrg.id},403);act('manager');await expect(await api.GET(),403);await template({action:'create',...fields(f)},403);act('owner');await template({action:'create',...fields(f),prompts:[fields(f).prompts[0],fields(f).prompts[0]]},400);await template({action:'create',...fields(f),description:'文'.repeat(201)},400);act('employee');const revision=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_template_answer BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit unavailable'); END");await perf({action:'selfReview',id:f.p.id,responses:{selfProof:'合成已交付成果'},evidence:'审计失败不得产生半份自评'},503);f.sqlite.exec('DROP TRIGGER reject_template_answer');assert.equal((await get()).revision,revision);assert.equal((await get()).records.find(r=>r.id===f.p.id).status,'confirmed');});

test('approved goal changes clear stale stage answers while preserving the prior self-review audit',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());act('employee');await perf({action:'selfReview',id:f.p.id,responses:{selfProof:'原目标下的合成回答'},evidence:'原目标合成自评事实与成果'});act('manager');await perf({action:'evaluate',id:f.p.id,scores:[70,80],responses:{reviewProof:'原目标合成管理意见'},evidence:'按原目标完成合成独立评价'});await perf({action:'returnPerformance',id:f.p.id,evidence:'目标需调整，退回员工补充修改'});act('employee');const pending=await change({action:'request',planId:f.p.id,goals:revisedGoals,evidence:'合成目标权重变化需要重新说明成果'});act('manager');await change({action:'review',id:pending.id,accepted:true,evidence:'同意新的合成目标，原回答保留历史'});
 const p=(await get()).records.find(r=>r.id===f.p.id);assert.equal(p.payload.selfResponses,undefined);assert.equal(p.payload.evaluationResponses,undefined);act('employee');await perf({action:'selfReview',id:f.p.id,evidence:'修改目标之后必须重新填写模板'},400);const history=await expect(await dev.GET(request('/api/development?id='+f.p.id)));assert.ok(history.items.some(e=>e.snapshot.payload.selfResponses?.selfProof==='原目标下的合成回答'));assert.ok(history.items.every(e=>e.snapshot.payload.evaluationResponses===undefined));
});

test('frozen goal limits apply to creation and changes; revisions cannot alter old cycles and impossible configurations are rejected',async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());const rules={minCount:2,maxCount:3,minWeight:20,maxWeight:70};
 await template({action:'create',...fields(f),goalRules:{...rules,minCount:3,maxCount:2}},400);await template({action:'create',...fields(f),goalRules:{minCount:3,maxCount:3,minWeight:40,maxWeight:60}},400);
 const d=await template({action:'create',...fields(f),goalRules:rules});await template({action:'seal',id:d.id});const cy=await perf({...cycleInput(f.org.id),templateId:d.id});await perf({action:'startCycle',id:cy.id});
 act('employee');const revision=(await get()).revision;await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:[{...goals[0],weight:100}]},400);await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:[{...goals[0],weight:80},{...goals[1],weight:20}]},400);assert.equal((await get()).revision,revision);
 const p=await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals});act('manager');await perf({action:'confirmGoals',id:p.id});act('owner');const newer=await template({action:'revise',id:d.id});await template({action:'edit',id:newer.id,...fields(f),goalRules:{minCount:1,maxCount:1,minWeight:100,maxWeight:100}});await template({action:'seal',id:newer.id});await template({action:'archive',id:d.id,reason:'合成版本归档，原周期仍守旧范围'});
 act('employee');await change({action:'request',planId:p.id,goals:[{...goals[0],weight:100}],evidence:'不能采用新模板覆盖旧周期约束'},400);const pending=await change({action:'request',planId:p.id,goals:revisedGoals,evidence:'权重恰为边界的合成目标调整'});act('manager');await change({action:'review',id:pending.id,accepted:true,evidence:'合成独立复核范围和权重通过'});assert.deepEqual((await get()).records.find(r=>r.id===cy.id).payload.performanceTemplate.goalRules,rules);
});

for(const mode of ['count','weight','both'])test(`advisory ${mode} limits retain universal constraints and immutable cycle rules`,async t=>{
 const f=await setup();t.after(()=>f.sqlite.close());act('owner');
 const rules={minCount:3,maxCount:3,minWeight:40,maxWeight:60,enforceCount:mode==='weight',enforceWeight:mode==='count'};
 const d=await template({action:'create',...fields(f),prompts:[],goalRules:rules});await template({action:'seal',id:d.id});
 const cy=await perf({...cycleInput(f.org.id),templateId:d.id});await perf({action:'startCycle',id:cy.id});
 const weights=mode==='count'?[50,50]:mode==='weight'?[34,33,33]:[100];
 const acceptedGoals=weights.map((weight,i)=>({title:'合成目标'+i,metric:'合成范围提示与强制限制验证',weight}));
 const {goalRangeFeedback}=await import('../lib/hris/performance-goal-feedback.ts');const messages=goalRangeFeedback(rules,acceptedGoals);assert.ok(messages.length);assert.ok(messages.every(x=>!x.blocking));
 act('employee');await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:[{...acceptedGoals[0],weight:99}]},400);
 if(mode!=='both')await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:[{...acceptedGoals[0],weight:100}]},400);
 const p=await perf({action:'goals',employeeId:f.e.id,cycleId:cy.id,goals:acceptedGoals});act('manager');await perf({action:'confirmGoals',id:p.id});
 act('owner');const v2=await template({action:'revise',id:d.id});await template({action:'edit',id:v2.id,...fields(f),prompts:[],goalRules:{minCount:1,maxCount:1,minWeight:100,maxWeight:100}});await template({action:'seal',id:v2.id});
 act('employee');const pending=await change({action:'request',planId:p.id,goals:acceptedGoals.map(g=>({...g,title:g.title+'调整'})),evidence:'提示模式仍允许提交符合通用约束的目标'});act('manager');await change({action:'review',id:pending.id,accepted:true,evidence:'独立复核沿用原周期提示规则'});
 assert.deepEqual((await get()).records.find(r=>r.id===cy.id).payload.performanceTemplate.goalRules,rules);
});
