import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setup,act,get,expect,request,grant} from './support/foundation-scenario.mjs';
const api=await import('../app/api/interview-definitions/route.ts'),recruitment=await import('../app/api/recruitment/route.ts');
const criteria=[{id:'skill',dimension:'专业',title:'合成技能',description:'依据合成岗位案例评分',labels:['欠缺','具备','掌握','卓越']},{id:'integrity',dimension:'能力',title:'合成履责',description:'依据合成行为事实评分',labels:['欠缺','具备','掌握','卓越']}];
async function post(a,command,status=200,revision){return expect(await a.POST(request('/api/test',{revision:revision??(await get()).revision,command})),status);}
const def=(c,s,r)=>post(api,c,s,r),recruit=(c,s,r)=>post(recruitment,c,s,r);
async function fixture(){const f=await setup(),q=await recruit({action:'requisition',positionId:f.position.id,title:'合成结构化面试需求',headcount:1,reason:'使用合成候选验证结构化评分与录用关联',submit:true});act('manager');await recruit({action:'approveRequisition',id:q.id});act('owner');const c=await recruit({action:'candidate',requisitionId:q.id,name:'合成四档候选',email:'',source:'仅用于四档评价模板集成验证'}),d=await def({action:'create',orgId:f.org.id,title:'合成四档评价',criteria});return {...f,q,c,d};}
const evaluate=f=>({action:'structuredInterview',candidateId:f.c.id,definitionId:f.d.id,scores:{skill:4,integrity:3},comments:{专业:'独立观察技能证据'},recommendation:'advance',evidence:'根据合成指标证据明确建议推进'});
test('structured evaluation freezes four-level criteria and explicit recommendation without inventing aggregate or altering prior results',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());await recruit(evaluate(f),400);await def({action:'seal',id:f.d.id});act('manager');const result=await recruit(evaluate(f));let record=(await get()).records.find(r=>r.id===result.id);assert.equal(record.payload.rating,undefined);assert.equal(record.payload.interviewEvaluation.aggregation,'not-configured');assert.equal(record.payload.interviewEvaluation.scores.skill,4);assert.equal(record.payload.version,1);
 act('owner');const next=await def({action:'revise',id:f.d.id});await def({action:'edit',id:next.id,orgId:f.org.id,title:'合成后续评价',criteria:criteria.map(i=>({...i,title:i.title+'新版'}))});await def({action:'seal',id:next.id});await def({action:'archive',id:f.d.id});await recruit(evaluate(f),400);record=(await get()).records.find(r=>r.id===result.id);assert.equal(record.payload.interviewEvaluation.criteria[0].title,'合成技能');await recruit({action:'offer',id:f.c.id,joined:'2026-01-01',evidence:'原面试建议仍可作为录用审批来源'});
 act('manager');await recruit({action:'approveOffer',id:f.c.id});act('owner');await recruit({action:'acceptOffer',id:f.c.id,evidence:'登记合成候选明确接受录用的依据'});await recruit({action:'hire',id:f.c.id,code:'STRUCT-HIRE'});await recruit({...evaluate(f),definitionId:next.id},400);
});
test('unknown or incomplete scores, unauthorized templates, audit failure and latest rejecting result enforce workflow boundaries',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());await def({action:'seal',id:f.d.id});const c=evaluate(f);for(const scores of [{skill:5,integrity:3},{skill:0,integrity:3},{skill:2.5,integrity:3},{skill:4},{skill:4,integrity:3,unknown:1}])await recruit({...c,scores},400);await recruit({...c,comments:{未知:'不得伪造维度'}},400);
 act('employee');await expect(await api.GET(),403);await recruit(c,403);act('manager');await def({action:'revise',id:f.d.id},403);await grant('outsideEval','hr',null,[f.otherOrg.id]);act('outsideEval');await recruit(c,403);act('owner');const outside=await def({action:'create',orgId:f.otherOrg.id,title:'合成异组织评价',criteria});await def({action:'seal',id:outside.id});await recruit({...c,definitionId:outside.id},400);
 const revision=(await get()).revision;f.sqlite.exec("CREATE TRIGGER reject_eval_audit BEFORE INSERT ON hris_audit_events BEGIN SELECT RAISE(ABORT,'synthetic audit failure'); END");await recruit(c,503);assert.equal((await get()).revision,revision);f.sqlite.exec('DROP TRIGGER reject_eval_audit');await recruit(c);await recruit(c,409,revision);const rejected=await recruit({...c,scores:{},comments:{},recommendation:'reject',evidence:'依据合成结论明确不予推进，不补零分'});const r=(await get()).records.find(r=>r.id===rejected.id);assert.deepEqual(r.payload.interviewEvaluation.scores,{});await recruit({action:'offer',id:f.c.id,joined:'2026-01-01',evidence:'最近明确拒绝不能被较早通过覆盖'},400);await recruit({action:'interview',candidateId:f.c.id,rating:4,recommendation:'advance',evidence:'旧评价模式仍按原规则保留兼容'});await recruit({action:'offer',id:f.c.id,joined:'2026-01-01',evidence:'最近旧模式评价明确通过可办理录用'});
});

test('maximum Chinese criteria and comments fit explicit bounded endpoints while oversized bodies are rejected',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());const long=Array.from({length:20},(_,n)=>({id:'k'+n,dimension:'维'.repeat(198)+String(n%10),title:'项'.repeat(200),description:'据'.repeat(1500),labels:Array.from({length:4},()=> '档'.repeat(200))}));const d=await def({action:'create',title:'满长中文模板',orgId:f.org.id,criteria:long});await def({action:'seal',id:d.id});await recruit({...evaluate(f),definitionId:d.id,scores:Object.fromEntries(long.map(i=>[i.id,4])),comments:Object.fromEntries(long.map(i=>[i.dimension,'评'.repeat(1500)])),evidence:'据'.repeat(1500)});await def({action:'create',title:'超限请求',orgId:f.org.id,criteria:long,extra:'x'.repeat(200000)},413);await recruit({...evaluate(f),extra:'x'.repeat(66000)},413);
});

test('structured interview response recovery keeps a single original evaluation and enforces key-content identity',async t=>{
 const f=await fixture();t.after(()=>f.sqlite.close());await def({action:'seal',id:f.d.id});act('manager');const body=evaluate(f);async function call(command,status=200){const req=request('/api/recruitment',{revision:(await get()).revision,command});req.headers.set('Idempotency-Key','structured-evaluation-recovery');return expect(await recruitment.POST(req),status);}const first=await call(body),revision=(await get()).revision,replay=await call(body);assert.equal(replay.id,first.id);assert.equal(replay.replayed,true);assert.equal((await get()).revision,revision);await call({...body,evidence:'改变意见必须核对原评价后明确发起新记录'},409);const records=(await get()).records.filter(r=>r.kind==='interview');assert.equal(records.length,1);assert.equal(records[0].payload.creationRequest,undefined);
});
