'use client';
import {useState} from 'react';
import {learningRequirements} from '@/lib/hris/learning-requirements';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {LearningGradeRule} from '@/lib/hris/learning-grades';
export const gradeModes={contentWeighted:'按内容权重计算',none:'不设置计划成绩',allHighest:'全部考试最高分',allAttemptsAverage:'全部作答成绩平均',eachExamHighestAverage:'各考试最高分的平均',specifiedExamHighest:'指定一场考试最高分'};
export default function Grading({definition,records,busy,send}:{definition:R;records:R[];busy:boolean;send:(command:Record<string,unknown>)=>unknown}){
 const initial=definition.payload.gradeRule??{mode:'none'},[mode,setMode]=useState<LearningGradeRule['mode']>(initial.mode),[attempts,setAttempts]=useState(initial.mode==='none'?'all':initial.attempts),[decimals,setDecimals]=useState(initial.mode==='none'?2:initial.decimals),[examId,setExam]=useState(initial.mode==='specifiedExamHighest'?initial.examId:'none');
 const requirements=learningRequirements(definition).filter(r=>r.kind==='exam'||r.kind==='homework');
 const [weights,setWeights]=useState<Record<string,number>>(Object.fromEntries(initial.mode==='contentWeighted'?initial.items.map(i=>[i.requirementId,i.weight]):[]));
 const [sources,setSources]=useState<Record<string,'examHighest'|'examAverage'|'homeworkLatest'>>(Object.fromEntries(initial.mode==='contentWeighted'?initial.items.map(i=>[i.requirementId,i.source]):[]));
 const items=requirements.filter(r=>(weights[r.id]??0)>0).map(r=>({requirementId:r.id,source:r.kind==='homework'?'homeworkLatest':sources[r.id]??'examHighest',weight:weights[r.id]})),total=items.reduce((n,i)=>n+i.weight,0);
 return <form className="border rounded p-4 mt-4 space-y-3" onSubmit={e=>{e.preventDefault();send({action:'grading',id:definition.id,rule:mode==='none'?{mode}:{mode,attempts,decimals,...(mode==='specifiedExamHighest'?{examId}:mode==='contentWeighted'?{items}:{})}});}}><h3>计划成绩规则</h3><p className="text-sm text-slate-500">以下为本系统显式配置，尚未确认与企业原站细则完全一致。仅计算本实例的独立考试或作业批阅证据，缺少任何所选内容的有效成绩时保持待定；课程完成、学分不换算成成绩。定版后规则冻结。</p><Select value={mode} onValueChange={v=>setMode(v as LearningGradeRule['mode'])}><SelectTrigger aria-label="计划成绩算法"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(gradeModes).map(([value,label])=><SelectItem key={value} value={value} disabled={value==='contentWeighted'?!requirements.length:value!=='none'&&!definition.payload.examIds?.length}>{label}</SelectItem>)}</SelectContent></Select>{mode!=='none'&&<><Select value={attempts} onValueChange={v=>{if(v==='all'||v==='passed')setAttempts(v);}}><SelectTrigger aria-label="计入哪些作答"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">计入全部有效考试／当前作业批阅（含未通过）</SelectItem><SelectItem value="passed">仅计入已通过考试／作业批阅</SelectItem></SelectContent></Select><Select value={String(decimals)} onValueChange={v=>setDecimals(Number(v))}><SelectTrigger aria-label="四舍五入小数位"><SelectValue/></SelectTrigger><SelectContent>{[0,1,2].map(n=><SelectItem key={n} value={String(n)}>四舍五入保留 {n} 位小数</SelectItem>)}</SelectContent></Select>{mode==='contentWeighted'&&<fieldset className="space-y-3"><legend>计分内容权重（整数百分比）</legend><p className="text-sm text-slate-500">0表示不参与，总计须100%。考试取最高或平均；作业取当前提交的最后批阅分，重新提交尚未批阅时待定。无分数的课程不参与，不赋予满分。</p>{requirements.map(r=><div key={r.id} className="border rounded p-3"><label>{records.find(x=>x.id===r.resourceId)?.payload.title??'计分内容'}<Input type="number" min={0} max={100} value={weights[r.id]??0} onChange={e=>setWeights({...weights,[r.id]:Number(e.target.value)})}/></label>{r.kind==='exam'?<label>考试取分<select className="block border rounded p-2" value={sources[r.id]??'examHighest'} onChange={e=>{if(e.target.value==='examHighest'||e.target.value==='examAverage')setSources({...sources,[r.id]:e.target.value});}}><option value="examHighest">最高分</option><option value="examAverage">平均分</option></select></label>:<p>当前提交的批阅评分</p>}</div>)}<p>总权重：{total}%</p></fieldset>}{mode==='specifiedExamHighest'&&<Select value={examId} onValueChange={setExam}><SelectTrigger aria-label="指定考试"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">请选择本计划考试</SelectItem>{records.filter(r=>definition.payload.examIds?.includes(r.id)).map(r=><SelectItem key={r.id} value={r.id}>{r.payload.title}</SelectItem>)}</SelectContent></Select>}</>}<Button disabled={busy||mode==='specifiedExamHighest'&&examId==='none'||mode==='contentWeighted'&&total!==100}>保存成绩规则</Button></form>;
}
