'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import {activeContractFields} from '@/lib/hris/contract-field-model';
import ProcessHistory from '../development/process-history';
type Data={records:R[];orgs:{id:string;name:string;status:string}[];revision:number};
type Form={id?:string;orgId:string;code:string;name:string;inheritPrevious:boolean};
const control='w-full rounded border p-2 bg-white',labels:Record<string,string>={draft:'草稿',sealed:'已定版',archived:'已归档'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Form|null>(null),[archive,setArchive]=useState<R|null>(null),[reason,setReason]=useState(''),[detail,setDetail]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){try{const r=await fetch('/api/contract-fields',{cache:'no-store'}),d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error??'加载失败');setData(d);}catch(e){setData(null);setError((e as Error).message)}}useEffect(()=>{void load()},[]);
 function open(r?:R){setError('');setForm({...(r?{id:r.id}:{}),orgId:r?.payload.orgId??'',code:r?.payload.contractField?.code??'',name:r?.payload.contractField?.name??'',inheritPrevious:r?.payload.contractField?.inheritPrevious??true})}
 async function send(command:unknown){if(!data||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/contract-fields',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error??'保存失败');setForm(null);setArchive(null);setNotice('字段版本已保存；既有合同快照保持不变。');}catch(e){setError((e as Error).message)}finally{await load();setBusy(false)}}
 return <main className="main-content mx-auto max-w-5xl space-y-5"><Link href="/workforce">返回编制与合同</Link><div className="page-head"><div><h1>合同自定义文本字段</h1><p className="mt-2 text-sm text-slate-600">每组织最多20项活动字段，每项1000字以内。续签按当前定版设置继承，旧合同继续保留当时的值和来源。</p></div><Button disabled={!data} onClick={()=>open()}>新建字段草稿</Button></div>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel space-y-3">{data?.records.slice().reverse().map(r=>{const field=r.payload.contractField!,active=activeContractFields(data.records,r.payload.orgId!).some(x=>x.id===r.id),latest=!data.records.some(x=>x.payload.definitionRootId===r.payload.definitionRootId&&(x.payload.version??0)>(r.payload.version??0));return <article className="rounded border p-4 space-y-2" key={r.id}><h2 className="font-semibold">{field.name} · {field.code} · V{r.payload.version}</h2><p className="text-sm">{data.orgs.find(o=>o.id===r.payload.orgId)?.name} · {labels[r.status]} · {active?'用于新合同':'不用于新合同'} · {field.inheritPrevious?'默认继承上份合同值':'不继承上份合同值'}</p><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={()=>setDetail(r)}>历史</Button>{r.status==='draft'&&<><Button variant="outline" onClick={()=>open(r)}>编辑草稿</Button><Button disabled={busy} onClick={()=>send({action:'seal',id:r.id})}>定版</Button></>}{r.status!=='draft'&&latest&&<Button variant="outline" disabled={busy} onClick={()=>send({action:'revise',id:r.id})}>创建修订草稿</Button>}{r.status!=='archived'&&<Button variant="ghost" onClick={()=>{setError('');setReason('');setArchive(r)}}>归档版本</Button>}</div></article>})}{data&&!data.records.length&&<p>尚无字段定义，已有合同流程可正常使用。</p>}</section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent><DialogHeader><DialogTitle>合同字段草稿</DialogTitle><DialogDescription>编号和组织在修订中保持不变。字段为选填文本，当前仅供HR管理，不扩大员工字段访问。</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();void send({...form,action:form.id?'edit':'create'})}}><fieldset disabled={busy} className="space-y-3">{error&&<p role="alert">{error}</p>}<label className="field">所属组织<select required disabled={!!form.id} className={control} value={form.orgId} onChange={e=>setForm({...form,orgId:e.target.value})}><option value="">请选择</option>{data?.orgs.filter(o=>o.status==='启用').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="field">稳定编号<Input required disabled={!!form.id} pattern="[A-Za-z0-9_-]{1,60}" maxLength={60} value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label className="field">字段名称<Input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="flex gap-2"><input type="checkbox" checked={form.inheritPrevious} onChange={e=>setForm({...form,inheritPrevious:e.target.checked})}/> 续签默认继承原合同该字段的值</label><Button>保存草稿</Button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!archive} onOpenChange={v=>!v&&!busy&&setArchive(null)}><DialogContent><DialogHeader><DialogTitle>归档字段版本</DialogTitle><DialogDescription>归档当前活动版本将停止新合同使用此字段，不回退到旧版本。丢弃修订草稿不会停用当前已定版字段。历史合同值保留。</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={e=>{e.preventDefault();if(archive)void send({action:'archive',id:archive.id,reason})}}><label className="field">归档依据<textarea required minLength={5} maxLength={3000} className={control} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy}>保存归档</Button></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{detail?.payload.contractField?.name} · V{detail?.payload.version}</DialogTitle><DialogDescription>版本变更与依据</DialogDescription></DialogHeader>{detail&&<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/>}</DialogContent></Dialog></main>;
}
