'use client';
import GoalRuleNotice from '../performance/goal-rule-notice';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import IndicatorPicker,{editableGoals,goalCommands,IndicatorSource,type EditableGoal} from '../performance/indicator-picker';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Goal=EditableGoal;type Data={livePlanIds:string[];records:R[];employees:{id:string;name:string;status:string;orgId:string}[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={submitted:'待独立复核',approved:'已通过并更新目标',rejected:'未通过',withdrawn:'已撤回'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[goals,setGoals]=useState<Goal[]>([]),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[planFilter,setPlanFilter]=useState('');
 async function load(){try{const response=await fetch('/api/performance-changes',{cache:'no-store'}),d=await response.json() as Data&{error?:string};if(!response.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();setPlanFilter(new URLSearchParams(window.location.search).get('planId')??'');},[]);
 const manager=['admin','hr','manager'].includes(data?.role??''),records=data?.records??[],record=records.find(r=>r.id===detail),employee=(r:R)=>data?.employees.find(e=>e.id===r.employeeId),plans=records.filter(p=>p.kind==='performancePlan'&&!!data?.livePlanIds?.includes(p.id)&&p.status==='confirmed'&&employee(p)?.status!=='离职'&&records.some(c=>c.kind==='performanceCycle'&&c.id===p.referenceId&&c.status==='active')&&!records.some(c=>c.kind==='performanceGoalChange'&&c.referenceId===p.id&&c.status==='submitted')),rows=records.filter(r=>r.kind==='performanceGoalChange'&&(!planFilter||r.referenceId===planFilter)&&[employee(r)?.name,r.payload.period,labels[r.status]].join(' ').includes(search)).reverse();
 function open(action:string,r?:R,accepted?:boolean){setError('');const p=plans.find(p=>p.id===planFilter);setForm({action,id:r?.id??'',planId:p?.id??'',evidence:'',accepted:String(accepted)});setGoals(editableGoals(p?.payload.goals??[]));}
 async function submit(e:FormEvent){e.preventDefault();if(!data||!form||busy)return;setBusy(true);setError('');try{const response=await fetch('/api/performance-changes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command:{...form,...(form.action==='request'?{goals:goalCommands(goals)}:{}),...(form.action==='review'?{accepted:form.accepted==='true'}:{})}})}),d=await response.json() as {error?:string};if(!response.ok)throw Error(d.error);setForm(null);setNotice('目标调整及相关计划已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const formPlan=records.find(r=>r.id===form?.planId),goalRules=records.find(r=>r.id===formPlan?.referenceId)?.payload.performanceTemplate?.goalRules;
 const showGoals=(items:Goal[]|undefined)=><ol className="space-y-3">{items?.map((g,i)=><li key={i} className="rounded border p-3"><p className="font-medium">{i+1}. {g.title} · {g.weight}%</p><IndicatorSource source={g.indicatorSource}/><p className="text-sm whitespace-pre-wrap mt-2">{g.metric}</p></li>)}</ol>;
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/performance" className="text-link">绩效管理</Link><Link href="/work-inbox" className="text-link">待办工作台</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">PERFORMANCE GOAL CHANGES</div><h1>绩效目标调整</h1><p className="mt-2 text-sm text-slate-500">已确认目标在自评提交前可申请调整，由其他有权限管理者独立复核。通过后同时保存调整记录与新版目标。</p></div><Button variant="outline" onClick={load}>刷新</Button></div><p className="mb-5 text-sm text-slate-500">调整待审时暂不提交自评或取消计划，可先撤回调整。目标权重合计须为100%；已发布结果使用申诉更正流程，不能通过此处改写。</p>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}<div className="flex flex-wrap gap-3 mb-5"><Input aria-label="搜索目标调整" className="max-w-sm" value={search} placeholder="搜索员工、期间或状态" onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{planFilter&&<Button variant="outline" onClick={()=>{setPlanFilter('');setPage(1);}}>显示全部可见计划</Button>}<Button disabled={!plans.length} onClick={()=>open('request')}>申请目标调整</Button></div><div className="grid gap-4">{rows.slice((page-1)*12,page*12).map(r=><section className="panel" key={r.id}><div className="section-head"><div><h2>{employee(r)?.name} · {r.payload.period}</h2><p className="text-sm text-slate-500">基于目标 V{r.payload.basePlanVersion} · {labels[r.status]}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setDetail(r.id)}>调整对照</Button>{r.status==='submitted'&&r.createdBy===data?.userId&&<Button size="sm" variant="outline" onClick={()=>open('withdraw',r)}>撤回</Button>}{r.status==='submitted'&&manager&&r.employeeId!==data?.employeeId&&r.createdBy!==data?.userId&&<><Button size="sm" disabled={!data?.livePlanIds?.includes(r.referenceId??'')} onClick={()=>open('review',r,true)}>复核通过</Button><Button size="sm" variant="outline" onClick={()=>open('review',r,false)}>不通过</Button></>}</div></div><p className="text-sm whitespace-pre-wrap">{r.payload.evidence}</p></section>)}</div>{!rows.length&&<p className="panel empty">暂无可见的目标调整申请</p>}<div className="flex justify-end items-center gap-3 mt-4"><span>{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*12>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{form?.action==='request'?'申请目标调整':form?.action==='withdraw'?'撤回目标调整':form?.accepted==='true'?'独立复核并更新目标':'独立复核不予通过'}</DialogTitle><DialogDescription>原目标和调整依据保留历史；通过时将重新确认新版目标。申请人和绩效本人不能自审。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='request'&&<><label className="field"><span>已确认、待自评的计划</span><select required className="rounded border p-2" value={form.planId} onChange={e=>{setForm({...form,planId:e.target.value});setGoals(editableGoals(plans.find(p=>p.id===e.target.value)?.payload.goals??[]));}}><option value="">请选择</option>{plans.map(p=><option key={p.id} value={p.id}>{employee(p)?.name} · {p.payload.period} · V{p.payload.version??1}</option>)}</select></label><GoalRuleNotice rules={goalRules} goals={goals}/>{goals.map((g,i)=><fieldset key={i} className="rounded border p-3 space-y-3"><legend>目标 {i+1}</legend><IndicatorPicker goal={g} records={records} orgId={data?.employees.find(e=>e.id===formPlan?.employeeId)?.orgId} onChange={v=>setGoals(goals.map((x,j)=>j===i?v:x))}/><Input aria-label={`目标${i+1}名称`} required maxLength={200} value={g.title} onChange={e=>setGoals(goals.map((v,j)=>j===i?{...v,title:e.target.value}:v))}/><textarea aria-label={`目标${i+1}衡量标准`} required minLength={5} maxLength={4000} rows={3} value={g.metric} onChange={e=>setGoals(goals.map((v,j)=>j===i?{...v,metric:e.target.value}:v))}/><div className="flex gap-3 items-center"><label className="flex gap-2 items-center">权重 %<Input className="w-24" type="number" required min={1} max={100} step={1} value={g.weight} onChange={e=>setGoals(goals.map((v,j)=>j===i?{...v,weight:Number(e.target.value)}:v))}/></label><Button type="button" size="sm" variant="outline" disabled={goals.length<=1} onClick={()=>setGoals(goals.filter((_,j)=>j!==i))}>移除此目标</Button></div></fieldset>)}<div className="flex gap-3 items-center"><Button type="button" variant="outline" disabled={goals.length>=20||!form.planId} onClick={()=>setGoals([...goals,{title:'',metric:'',weight:1}])}>增加目标</Button><span>权重合计 {goals.reduce((s,g)=>s+g.weight,0)}%</span></div></>}<label className="field"><span>调整原因 / 复核意见</span><textarea required minLength={5} maxLength={4000} rows={3} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button type="submit" disabled={busy||form.action==='request'&&(!goals.length||goals.reduce((s,g)=>s+g.weight,0)!==100)}>{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-4xl"><DialogHeader><DialogTitle>目标调整对照</DialogTitle><DialogDescription>{record&&labels[record.status]}</DialogDescription></DialogHeader>{record&&<><GoalRuleNotice rules={records.find(c=>c.id===records.find(p=>p.id===record.referenceId)?.referenceId)?.payload.performanceTemplate?.goalRules} goals={record.payload.goals}/><div className="grid gap-5 md:grid-cols-2"><div><h3 className="mb-3 font-medium">原目标 V{record.payload.basePlanVersion}</h3>{showGoals(record.payload.originalGoals)}</div><div><h3 className="mb-3 font-medium">申请调整后的目标</h3>{showGoals(record.payload.goals)}</div></div><p className="whitespace-pre-wrap">{record.payload.evidence}</p>{record.payload.verification&&<p>{record.payload.verification}</p>}<ProcessHistory id={record.id} updatedAt={record.updatedAt}/></>}</DialogContent></Dialog></main>;
}
