'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
type Data={records:R[];managedOrgIds:string[];orgs:{id:string;name:string;status:string}[];employees:{id:string;name:string;status:string}[];revision:number;role:string;employeeId:string|null;userId:string};
const labels:Record<string,string>={draft:'草稿',published:'已发布',closed:'已停止报名',cancelled:'草稿已取消',submitted:'待资格复核',approved:'资格通过',rejected:'未通过',withdrawn:'已撤回'};
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[form,setForm]=useState<Record<string,string>|null>(null),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1),[tab,setTab]=useState<'campaigns'|'applications'>('campaigns');
 async function load(){try{const response=await fetch('/api/instructor-campaigns',{cache:'no-store'}),d=await response.json() as Data&{error?:string};if(!response.ok)throw Error(d.error);setData(d);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);
 const hr=['admin','hr'].includes(data?.role??''),records=data?.records??[],record=records.find(r=>r.id===detail),today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date()),profile=(r:R)=>records.find(p=>p.kind==='instructorProfile'&&p.payload.instructorApplicationId===r.id),employee=(r:R)=>data?.employees.find(e=>e.id===r.employeeId),rows=records.filter(r=>r.kind===(tab==='campaigns'?'instructorCampaign':'instructorApplication')&&[r.payload.title,r.payload.instructorLevel,employee(r)?.name,labels[r.status]].join(' ').includes(search)).reverse();
 function open(action:string,r?:R,accepted?:boolean){setError('');setForm({action,id:r?.id??'',campaignId:r?.id??'',employeeId:r?.employeeId??'',instructorApplicationId:r?.id??'',title:r?.payload.instructorLevel??'',description:r?.payload.description??'',orgId:'',instructorLevel:'',criteria:'',start:'',end:'',evidence:'',accepted:String(accepted)});}
 async function submit(e:FormEvent){e.preventDefault();if(!data||!form||busy)return;setBusy(true);setError('');try{const command={...form,...(form.action==='review'?{accepted:form.accepted==='true'}:{})},response=await fetch(form.action==='nominate'?'/api/instructor-directory':'/api/instructor-campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await response.json() as {error?:string};if(!response.ok)throw Error(d.error);setForm(null);setNotice(form.action==='nominate'?'提名已创建并关联报名，请进入试讲评审安排评委':'认证报名记录已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 const title=(action:string)=>({create:'创建认证报名活动',publish:'发布报名活动',closeSignup:'停止新报名',cancelDraft:'取消活动草稿',apply:'本人报名',review:'独立资格复核',withdraw:'撤回本人报名',nominate:'根据已通过报名创建讲师提名'})[action]??'办理';
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex flex-wrap gap-5 text-sm"><Link href="/reports?dataset=instructorCampaignProgress" className="text-link">活动进度</Link><Link href="/instructor-directory" className="text-link">内部讲师名册</Link><Link href="/instructor-development" className="text-link">培养任务</Link><Link href="/instructor-trials" className="text-link">试讲评审</Link><Link href="/learning" className="text-link">学习中心</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">INSTRUCTOR APPLICATIONS</div><h1>师资认证报名</h1><p className="mt-2 text-sm text-slate-500">活动发布后，范围内员工本人报名，由其他HR复核资格。通过后创建讲师提名，再安排试讲并独立核对入册。</p></div><Button variant="outline" onClick={load}>刷新</Button></div><p className="mb-5 text-sm text-slate-500">本页支持内部讲师报名。活动发布后等级、条件和报名期间固定；停止报名保留既有申请。报名通过不代表已成为讲师，活动关联提名必须完成试讲。</p>{error&&<p role="alert" className="panel error">{error}</p>}{notice&&<p role="status" className="my-3 text-green-700">{notice}</p>}
 <div className="flex flex-wrap gap-3 mb-5"><Button variant={tab==='campaigns'?'default':'outline'} onClick={()=>{setTab('campaigns');setPage(1);}}>报名活动</Button><Button variant={tab==='applications'?'default':'outline'} onClick={()=>{setTab('applications');setPage(1);}}>报名明细</Button><Input className="max-w-sm" aria-label="搜索认证报名" placeholder="搜索活动、等级、员工或状态" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>{hr&&<Button onClick={()=>open('create')}>创建活动</Button>}</div><div className="grid gap-4">{rows.slice((page-1)*12,page*12).map(r=><section className="panel" key={r.id}><div className="section-head"><div><h2>{r.payload.title}</h2><p className="text-sm text-slate-500">{r.kind==='instructorApplication'?employee(r)?.name:data?.orgs.find(o=>o.id===r.payload.orgId)?.name} · {r.payload.instructorLevel} · {profile(r)?'已关联提名':labels[r.status]}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setDetail(r.id)}>详情</Button>{r.kind==='instructorCampaign'?<>{hr&&data?.managedOrgIds.includes(r.payload.orgId!)&&r.status==='draft'&&<><Button size="sm" onClick={()=>open('publish',r)}>发布</Button><Button size="sm" variant="outline" onClick={()=>open('cancelDraft',r)}>取消草稿</Button></>}{hr&&data?.managedOrgIds.includes(r.payload.orgId!)&&r.status==='published'&&<Button size="sm" variant="outline" onClick={()=>open('closeSignup',r)}>停止报名</Button>}{data?.employeeId&&r.status==='published'&&r.payload.start!<=today&&r.payload.end!>=today&&<Button size="sm" onClick={()=>open('apply',r)}>本人报名</Button>}</>:<>{!profile(r)&&r.employeeId===data?.employeeId&&['submitted','approved'].includes(r.status)&&<Button size="sm" variant="outline" onClick={()=>open('withdraw',r)}>撤回</Button>}{!profile(r)&&hr&&r.employeeId!==data?.employeeId&&r.createdBy!==data?.userId&&<>{r.status==='submitted'&&<><Button size="sm" onClick={()=>open('review',r,true)}>资格通过</Button><Button size="sm" variant="outline" onClick={()=>open('review',r,false)}>不通过</Button></>}{r.status==='approved'&&<Button size="sm" onClick={()=>open('nominate',r)}>创建提名</Button>}</>}{profile(r)&&<Link className="text-link text-sm" href="/instructor-directory">查看关联提名</Link>}</>}</div></div><p className="text-sm whitespace-pre-wrap">{r.payload.criteria}</p>{r.kind==='instructorCampaign'&&<p className="text-sm mt-3">报名期间：{r.payload.start} 至 {r.payload.end}（北京时间）</p>}</section>)}</div>{!rows.length&&<p className="panel empty">暂无可见记录</p>}<div className="flex justify-end items-center gap-3 mt-4"><span>{rows.length} 条</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={page*12>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{form&&title(form.action)}</DialogTitle><DialogDescription>报名条件与认证等级依据企业活动规则填写。资格复核及入册保持独立办理；停止报名后，已有申请仍可继续处理。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='create'&&<><label className="field"><span>活动名称</span><Input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="field"><span>活动组织（含下级组织）</span><select required className="rounded border p-2" value={form.orgId} onChange={e=>setForm({...form,orgId:e.target.value})}><option value="">请选择</option>{data?.orgs.filter(o=>o.status==='启用'&&data.managedOrgIds.includes(o.id)).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="field"><span>认证等级</span><Input required maxLength={100} value={form.instructorLevel} onChange={e=>setForm({...form,instructorLevel:e.target.value})}/></label><label className="field"><span>授课领域说明</span><textarea required minLength={5} maxLength={1000} rows={2} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="field"><span>报名条件说明</span><textarea required minLength={10} maxLength={1000} rows={3} value={form.criteria} onChange={e=>setForm({...form,criteria:e.target.value})}/></label><div className="grid grid-cols-2 gap-3">{[['start','报名开始日'],['end','报名结束日']].map(([key,label])=><label className="field" key={key}><span>{label}</span><Input required type="date" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div></>}{form.action==='nominate'&&<p>将按已通过报名的等级“{form.title}”创建提名，活动授课领域说明同步到名册。之后须完成试讲。</p>}{form.action!=='publish'&&<label className="field"><span>活动依据 / 报名材料 / 办理意见</span><textarea required minLength={5} maxLength={2000} rows={3} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label>}<Button type="submit" disabled={busy}>{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>{record?.payload.title}</DialogTitle><DialogDescription>{record&&labels[record.status]}</DialogDescription></DialogHeader>{record&&<><p className="whitespace-pre-wrap">{record.payload.criteria}</p>{Object.entries({依据或材料:record.payload.evidence,复核意见:record.payload.verification,停止或撤回原因:record.payload.closedReason}).filter(([,v])=>v).map(([k,v])=><div key={k}><p className="text-sm text-slate-500">{k}</p><p className="whitespace-pre-wrap">{v}</p></div>)}{(hr||record.kind==='instructorApplication')&&<ProcessHistory id={record.id} updatedAt={record.updatedAt}/>}</>}</DialogContent></Dialog></main>;
}
