'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {courseCreditAlreadyGranted,repeatCreditInstance} from '@/lib/hris/learning-credits';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ProcessHistory from '../development/process-history';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import type {State} from '@/lib/hris/model';
type Data={records:R[];summary:{employeeId:string;awardedUnits:number;reversedUnits:number;netUnits:number;expiredUnits:number;availableUnits:number}[];asOf:string;revision:number;role:string;employeeId:string|null;userId:string};
const credits=(n?:number)=>((n??0)/100).toFixed(2);
export default function LearningCredits(){
 const [data,setData]=useState<Data|null>(null),[core,setCore]=useState<State|null>(null),[form,setForm]=useState<{action:string;id:string;evidence:string;units:string;days:string}|null>(null),[detail,setDetail]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/learning-credits',{cache:'no-store'}),fetch('/api/hris',{cache:'no-store'})]),[d,c]=await Promise.all([a.json() as Promise<Data&{error?:string}>,b.json() as Promise<{state:State;error?:string}>]);if(!a.ok)throw Error(d.error);if(!b.ok)throw Error(c.error);setData(d);setCore(c.state);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{load();},[]);const hr=['admin','hr'].includes(data?.role??''),rows=data?.records??[],record=rows.find(r=>r.id===detail),employee=(id:string|null)=>core?.employees.find(e=>e.id===id)?.name??'—';
 function open(action:string,id:string){setError('');setForm({action,id,evidence:'',units:'',days:''});}
 async function submit(e:FormEvent){e.preventDefault();if(!data||!form)return;setBusy(true);setError('');try{let units=0;if(form.action==='policy'){if(!/^\d+(\.\d{1,2})?$/.test(form.units))throw Error('学分最多保留两位小数');const [a,b='']=form.units.split('.');units=Number(a)*100+Number(b.padEnd(2,'0'));}const command={action:form.action,evidence:form.evidence,...(form.action==='policy'?{courseId:form.id,creditUnits:units,...(form.days?{validityDays:Number(form.days)}:{})}:form.action==='award'?{enrollmentId:form.id}:{awardId:form.id})};const r=await fetch('/api/learning-credits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setForm(null);setNotice('学分台账已保存');}catch(e){setError((e as Error).message);}finally{await load();setBusy(false);}}
 return <main className="main-content mx-auto max-w-7xl"><nav className="flex gap-5 text-sm"><Link href="/" className="text-link">导航台</Link><Link href="/learning" className="text-link">学习中心</Link><Link href="/training-sessions" className="text-link">培训出勤</Link></nav><div className="page-head mt-5"><div><div className="eyebrow">LEARNING CREDITS</div><h1>学习学分</h1><p className="mt-2 text-sm text-slate-500">学分绑定课程版本，学习成果核验完成后登记。撤销保留原授予记录，不改变学习完成状态。</p></div><Button variant="outline" onClick={load}>刷新</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p className="my-3 text-green-700" role="status">{notice}</p>}
 <section className="panel"><h2 className="font-semibold mb-4">学分汇总</h2><p className="mb-3 text-sm text-slate-500">按北京时间 {data?.asOf} 核对。到期不删除授予记录；已撤销学分不重复计入到期。未配置有效期的记录暂不扣减到期学分。</p><Table><TableHeader><TableRow>{['员工','累计授予','累计撤销','账面净额','未撤销但已到期','当前可用'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{data?.summary.map(r=><TableRow key={r.employeeId}><TableCell>{employee(r.employeeId)}</TableCell><TableCell>{credits(r.awardedUnits)}</TableCell><TableCell>{credits(r.reversedUnits)}</TableCell><TableCell>{credits(r.netUnits)}</TableCell><TableCell>{credits(r.expiredUnits)}</TableCell><TableCell className="font-semibold">{credits(r.availableUnits)}</TableCell></TableRow>)}</TableBody></Table>{!data?.summary.length&&<p className="empty">暂无已登记学分</p>}</section>
 <section className="panel"><h2 className="font-semibold mb-4">课程学分规则</h2><Table><TableHeader><TableRow><TableHead>课程及版本</TableHead><TableHead>学分</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{rows.filter(r=>r.kind==='course').map(course=>{const p=rows.find(r=>r.kind==='courseCreditPolicy'&&r.referenceId===course.id);return <TableRow key={course.id}><TableCell>{course.payload.title} · V{course.payload.version}</TableCell><TableCell>{p?credits(p.payload.creditUnits):'未配置'}</TableCell><TableCell>{p?<Button variant="ghost" size="sm" onClick={()=>setDetail(p.id)}>规则记录</Button>:hr&&course.status!=='archived'&&<Button size="sm" onClick={()=>open('policy',course.id)}>配置学分</Button>}</TableCell></TableRow>;})}</TableBody></Table></section>
 {hr&&<section className="panel"><h2 className="font-semibold mb-4">已完成学习 · 待登记学分</h2><Table><TableHeader><TableRow><TableHead>员工</TableHead><TableHead>课程</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{rows.filter(r=>r.kind==='enrollment'&&r.status==='completed'&&!courseCreditAlreadyGranted(rows,r)).map(r=><TableRow key={r.id}><TableCell>{employee(r.employeeId)}</TableCell><TableCell>{r.payload.title}</TableCell><TableCell><Button size="sm" disabled={!!repeatCreditInstance(rows,r)&&repeatCreditInstance(rows,r)?.status!=='completed'||r.employeeId===data?.employeeId||!rows.some(x=>x.kind==='courseCreditPolicy'&&x.referenceId===r.referenceId)} onClick={()=>open('award',r.id)}>登记学分</Button></TableCell></TableRow>)}</TableBody></Table></section>}
 <section className="panel"><h2 className="font-semibold mb-4">授予与撤销记录</h2><Table><TableHeader><TableRow>{['员工','课程','学分变动','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.filter(r=>['learningCredit','creditReversal'].includes(r.kind)).reverse().map(r=><TableRow key={r.id}><TableCell>{employee(r.employeeId)}</TableCell><TableCell>{r.payload.title} · V{r.payload.version}{r.payload.round?` · 第${r.payload.round}轮`:''}{r.payload.repeatCreditApplied?' · 循环重复授予':''}</TableCell><TableCell>{r.kind==='creditReversal'?'-':'+'}{credits(r.payload.creditUnits)}</TableCell><TableCell><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={()=>setDetail(r.id)}>详情</Button>{hr&&r.kind==='learningCredit'&&r.createdBy!==data?.userId&&r.employeeId!==data?.employeeId&&!rows.some(x=>x.kind==='creditReversal'&&x.referenceId===r.id)&&<Button size="sm" variant="outline" onClick={()=>open('reverse',r.id)}>撤销学分</Button>}</div></TableCell></TableRow>)}</TableBody></Table></section>
 <Dialog open={!!form} onOpenChange={v=>{if(!v&&!busy)setForm(null);}}><DialogContent><DialogHeader><DialogTitle>{form?.action==='policy'?'配置课程学分':form?.action==='award'?'登记学习学分':'独立核实并撤销学分'}</DialogTitle><DialogDescription>课程版本的学分规则固定；同员工同课程版本只授予一次，跨计划重学、历史复用及撤销后均不会重复授予。</DialogDescription></DialogHeader>{error&&<p role="alert" className="text-red-700">{error}</p>}{form&&<form className="edit-form" onSubmit={submit}>{form.action==='policy'&&<label className="field"><span>有效天数（选填，1至36500，授予登记日为第1天）</span><Input type="number" min={1} max={36500} step={1} value={form.days} onChange={e=>setForm({...form,days:e.target.value})}/></label>}{form.action==='policy'&&<label className="field"><span>学分（0.01至10000）</span><Input required inputMode="decimal" value={form.units} onChange={e=>setForm({...form,units:e.target.value})}/></label>}<label className="field"><span>依据</span><textarea required minLength={5} maxLength={2000} rows={4} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy} type="submit">{busy?'保存中…':'保存'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={!!record} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent><DialogHeader><DialogTitle>{record?.payload.title}</DialogTitle><DialogDescription>课程版本 V{record?.payload.version} · {credits(record?.payload.creditUnits)} 学分</DialogDescription></DialogHeader>{record&&<><p className="whitespace-pre-wrap">{record.payload.evidence}</p><p>有效期：{record.payload.validityDays?record.payload.validityDays+'天（登记授予日起）':'未配置到期'}{record.payload.validUntil?'；最后有效日：'+record.payload.validUntil:''}</p><ProcessHistory id={record.id} updatedAt={record.updatedAt}/></>}</DialogContent></Dialog></main>;
}
