import {dispatchTrainingStage} from '@/lib/hris/training-dispatch';
import {readConsistent} from '@/lib/hris/context';
import {payrollRecordAccess} from '@/lib/hris/payroll-access';
import {z} from 'zod';
import {json,failure,readBody,HttpError} from '@/lib/hris/http';
import {developmentContext,visibleDevelopment,saveDevelopment,saveDevelopmentMany} from '@/lib/hris/development-repository';
import {applyDevelopment,competencyGaps,projectRecord} from '@/lib/hris/development';
export async function GET(request?:Request){try{const ctx=await developmentContext();const url=request?new URL(request.url):null,id=url?.searchParams.get('id');if(url?.searchParams.get('report')==='gaps')return json({items:competencyGaps(ctx.records,ctx.state,ctx.member),revision:ctx.row.revision});if(id){if(ctx.records.some(r=>r.id===id&&r.kind==='instructorTrial'&&(!['admin','hr'].includes(ctx.member.role)||r.employeeId===ctx.member.employeeId||!!ctx.member.employeeId&&r.payload.participantIds?.includes(ctx.member.employeeId))))throw new HttpError(403,'试讲原始评分历史仅非参评的有权限HR可查看');if(!['admin','hr'].includes(ctx.member.role)&&ctx.records.some(r=>r.id===id&&r.kind==='instructorProfile'))throw new HttpError(403,'讲师提名办理过程仅有权限HR可查看');if(!["admin","hr"].includes(ctx.member.role)&&ctx.records.some(r=>r.id===id&&r.kind==="employeeFieldValue"&&r.employeeId!==ctx.member.employeeId))throw new HttpError(403,"员工字段变更过程仅本人和有权限的HR可查看");if(!['admin','hr'].includes(ctx.member.role)&&ctx.records.some(r=>r.id===id&&r.kind==='employmentContract'))throw new HttpError(403,'合同办理过程仅HR和管理员可查看');if(ctx.records.some(r=>r.id===id&&['payBatch','paySlip','payAdjustment'].includes(r.kind)&&!payrollRecordAccess(r,ctx.records,ctx.state,ctx.member)))throw new HttpError(403,'工资编制过程仅薪酬管理授权人员可查看');if(!visibleDevelopment(ctx).some(r=>r.id===id))throw new HttpError(403,'没有此记录的访问权限');const page=z.coerce.number().int().min(1).max(10000).parse(url?.searchParams.get('page')??1);const [rows]=await readConsistent(ctx,[ctx.db.prepare('SELECT revision,action,actor_id AS actorId,at,snapshot FROM hris_development_events WHERE tenant_id=? AND record_id=? ORDER BY revision DESC LIMIT 21 OFFSET ?').bind(ctx.member.tenantId,id,(page-1)*20)]);return json({items:(rows.results as {revision:number;action:string;actorId:string;at:string;snapshot:string}[]).slice(0,20).map(r=>({...r,snapshot:projectRecord(JSON.parse(String(r.snapshot)),ctx.member,payrollRecordAccess(JSON.parse(String(r.snapshot)),ctx.records,ctx.state,ctx.member))})),page,hasMore:rows.results.length>20});}return json({records:visibleDevelopment(ctx),revision:ctx.row.revision,role:ctx.member.role,employeeId:ctx.member.employeeId,userId:ctx.member.userId});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const body=z.object({revision:z.number().int().nonnegative(),command:z.unknown()}).parse(await readBody(request));const ctx=await developmentContext();if((body.command as {action?:string}|null)?.action==='dispatchTrainingStage'){const records=dispatchTrainingStage(ctx.records,ctx.state,ctx.member,body.command);await saveDevelopmentMany(ctx,body.revision,records,'课程阶段：批量派课');return json({ids:records.map(r=>r.id),count:records.length,revision:body.revision+1});}const record=applyDevelopment(ctx.records,ctx.state,ctx.member,body.command);await saveDevelopment(ctx,body.revision,record,'人才与学习：'+String((body.command as {action:string}).action));return json({id:record.id,revision:body.revision+1});}catch(e){return failure(e);}}
