/** DEC-005 / 17 §1 / 22 §1：仅简体中文标准字段；元数据不是 JSON 实体存储。 */
export type FieldKind = 'text' | 'email' | 'date' | 'uuid' | 'boolean' | 'integer' | 'decimal';
export interface PersonnelField {
  readonly code: string;
  readonly kind: FieldKind;
  readonly system?: boolean;
}
export const EMPLOYEE_EDITABLE_FIELDS: readonly PersonnelField[] = [
  { code: 'name', kind: 'text' },
  { code: 'displayName', kind: 'text', system: true },
  { code: 'engName', kind: 'text' },
  { code: 'lastname', kind: 'text' },
  { code: 'firstname', kind: 'text' },
  { code: 'gender', kind: 'text' },
  { code: 'birthday', kind: 'date' },
  { code: 'nation', kind: 'text' },
  { code: 'nationality', kind: 'text' },
  { code: 'registAddress', kind: 'text' },
  { code: 'marryCategory', kind: 'text' },
  { code: 'politicalStatus', kind: 'text' },
  { code: 'workDate', kind: 'date' },
  { code: 'idPhoto', kind: 'uuid' },
  { code: 'idType', kind: 'text' },
  { code: 'idNumber', kind: 'text' },
  { code: 'idStartDate', kind: 'date' },
  { code: 'idEndDate', kind: 'date' },
  { code: 'idLongTerm', kind: 'boolean' },
  { code: 'idIssuer', kind: 'text' },
  { code: 'idFront', kind: 'uuid' },
  { code: 'idBack', kind: 'uuid' },
  { code: 'mobilePhone', kind: 'text' },
  { code: 'email', kind: 'email' },
  { code: 'workEmail', kind: 'email' },
  { code: 'backupMail', kind: 'email' },
  { code: 'officePhone', kind: 'text' },
  { code: 'homePhone', kind: 'text' },
  { code: 'contactAddress', kind: 'text' },
  { code: 'householdAddress', kind: 'text' },
  { code: 'householdCategory', kind: 'text' },
  { code: 'emergencyContact', kind: 'text' },
  { code: 'emergencyPhone', kind: 'text' },
  { code: 'emergencyRelationship', kind: 'text' },
  { code: 'isRehire', kind: 'boolean' },
  { code: 'rehireType', kind: 'text' },
  { code: 'confirmRehireUserId', kind: 'uuid' },
  { code: 'expectedRetirementDate', kind: 'date' },
  { code: 'actualRetirementDate', kind: 'date' },
  { code: 'allowToLoginIn', kind: 'boolean' },
  { code: 'namePinyin', kind: 'text' },
  { code: 'pinyinInitials', kind: 'text' },
  { code: 'lastNamePinyin', kind: 'text' },
  { code: 'firstNamePinyin', kind: 'text' },
];
export const EMPLOYEE_REFLECTED_FIELDS: readonly PersonnelField[] = [
  { code: 'educationLevel', kind: 'text', system: true },
  { code: 'lastSchool', kind: 'text', system: true },
  { code: 'major', kind: 'text', system: true },
  { code: 'graduateDate', kind: 'date', system: true },
  { code: 'firstEducationLevel', kind: 'text', system: true },
  { code: 'highestDegree', kind: 'text', system: true },
  { code: 'highestTechnicalLevel', kind: 'text', system: true },
  { code: 'highestVocationalLevel', kind: 'text', system: true },
  { code: 'accountActivationStatus', kind: 'text', system: true },
  { code: 'invitationStatus', kind: 'text', system: true },
  { code: 'approvalStatus', kind: 'text', system: true },
  { code: 'approvalObjectDataId', kind: 'uuid', system: true },
  { code: 'approvalObjectDataId2', kind: 'uuid', system: true },
  { code: 'approvalType', kind: 'text', system: true },
  { code: 'currentApproverId', kind: 'uuid', system: true },
];
export const EMPLOYEE_FIELDS = [...EMPLOYEE_EDITABLE_FIELDS, ...EMPLOYEE_REFLECTED_FIELDS];
export const SUBSETS = {
  education: {
    table: 'personnel_education',
    objectCode: 'TenantBase.Education',
    fields: [
      { code: 'educationLevel', kind: 'text' },
      { code: 'degree', kind: 'text' },
      { code: 'school', kind: 'text' },
      { code: 'schoolType', kind: 'text' },
      { code: 'major', kind: 'text' },
      { code: 'majorCategory', kind: 'text' },
      { code: 'majorDescription', kind: 'text' },
      { code: 'mainCourses', kind: 'text' },
      { code: 'startDate', kind: 'date' },
      { code: 'endDate', kind: 'date' },
      { code: 'learningForm', kind: 'text' },
      { code: 'schoolingLength', kind: 'text' },
      { code: 'graduationType', kind: 'text' },
      { code: 'trainingMode', kind: 'text' },
      { code: 'isFirstEducation', kind: 'boolean' },
      { code: 'isHighestEducation', kind: 'boolean' },
      { code: 'isHighestDegree', kind: 'boolean' },
      { code: 'isMainMajor', kind: 'boolean' },
      { code: 'educationCertificate', kind: 'uuid' },
      { code: 'educationCertificateNumber', kind: 'text' },
      { code: 'degreeCertificate', kind: 'uuid' },
      { code: 'degreeCertificateNumber', kind: 'text' },
      { code: 'degreeCountry', kind: 'text' },
      { code: 'gpa', kind: 'decimal' },
      { code: 'classRank', kind: 'integer' },
      { code: 'majorRank', kind: 'integer' },
      { code: 'attachmentId', kind: 'uuid' },
    ],
  },
  jobhistory: {
    table: 'personnel_job_history',
    objectCode: 'TenantBase.jobhistory',
    fields: [
      { code: 'company', kind: 'text' },
      { code: 'department', kind: 'text' },
      { code: 'post', kind: 'text' },
      { code: 'position', kind: 'text' },
      { code: 'level', kind: 'text' },
      { code: 'startDate', kind: 'date' },
      { code: 'endDate', kind: 'date' },
      { code: 'entryDate', kind: 'date' },
      { code: 'leaveDate', kind: 'date' },
      { code: 'leaveReason', kind: 'text' },
      { code: 'responsibilities', kind: 'text' },
      { code: 'achievements', kind: 'text' },
      { code: 'referenceName', kind: 'text' },
      { code: 'referenceTitle', kind: 'text' },
      { code: 'referencePhone', kind: 'text' },
      { code: 'companyType', kind: 'text' },
      { code: 'industry', kind: 'text' },
      { code: 'companySize', kind: 'text' },
      { code: 'subordinateCount', kind: 'integer' },
      { code: 'reportsTo', kind: 'text' },
      { code: 'monthlySalary', kind: 'decimal' },
      { code: 'isThisCompany', kind: 'boolean', system: true },
      { code: 'employmentRecordId', kind: 'uuid', system: true },
      { code: 'employmentType', kind: 'text' },
      { code: 'departmentFullName', kind: 'text' },
    ],
  },
  family: {
    table: 'personnel_family',
    objectCode: 'TenantBase.Family',
    fields: [
      { code: 'name', kind: 'text' },
      { code: 'relationship', kind: 'text' },
      { code: 'gender', kind: 'text' },
      { code: 'birthday', kind: 'date' },
      { code: 'company', kind: 'text' },
      { code: 'post', kind: 'text' },
      { code: 'phone', kind: 'text' },
      { code: 'mobilePhone', kind: 'text' },
      { code: 'email', kind: 'email' },
      { code: 'nationality', kind: 'text' },
      { code: 'nation', kind: 'text' },
      { code: 'politicalStatus', kind: 'text' },
      { code: 'idNumber', kind: 'text' },
      { code: 'idFront', kind: 'uuid' },
      { code: 'idBack', kind: 'uuid' },
      { code: 'idStartDate', kind: 'date' },
      { code: 'idEndDate', kind: 'date' },
      { code: 'idIssuer', kind: 'text' },
      { code: 'previousChildcareDays', kind: 'decimal' },
      { code: 'childcareStartYear', kind: 'integer' },
    ],
  },
  training: {
    table: 'personnel_training',
    objectCode: 'TenantBase.Training',
    fields: [
      { code: 'name', kind: 'text' },
      { code: 'category', kind: 'text' },
      { code: 'institution', kind: 'text' },
      { code: 'startDate', kind: 'date' },
      { code: 'endDate', kind: 'date' },
      { code: 'hours', kind: 'decimal' },
      { code: 'score', kind: 'decimal' },
      { code: 'passed', kind: 'boolean' },
      { code: 'completed', kind: 'boolean' },
      { code: 'credits', kind: 'decimal' },
      { code: 'certificate', kind: 'text' },
      { code: 'lecturer', kind: 'text' },
      { code: 'mentor', kind: 'text' },
      { code: 'activityNumber', kind: 'text' },
      { code: 'hasMedal', kind: 'boolean' },
    ],
  },
  certificate: {
    table: 'personnel_certificate',
    objectCode: 'TenantBase.Certificate',
    fields: [
      { code: 'name', kind: 'text' },
      { code: 'type', kind: 'text' },
      { code: 'number', kind: 'text' },
      { code: 'issuer', kind: 'text' },
      { code: 'obtainedDate', kind: 'date' },
      { code: 'startDate', kind: 'date' },
      { code: 'endDate', kind: 'date' },
      { code: 'attachmentId', kind: 'uuid' },
      { code: 'learningCertificateId', kind: 'text' },
    ],
  },
  awards: {
    table: 'personnel_awards',
    objectCode: 'TenantBase.Awards',
    fields: [
      { code: 'name', kind: 'text' },
      { code: 'category', kind: 'text' },
      { code: 'level', kind: 'text' },
      { code: 'awardDate', kind: 'date' },
      { code: 'description', kind: 'text' },
    ],
  },
  'project-experience': {
    table: 'personnel_project_experience',
    objectCode: 'TenantBase.ProjectExperience',
    fields: [
      { code: 'name', kind: 'text' },
      { code: 'startDate', kind: 'date' },
      { code: 'endDate', kind: 'date' },
      { code: 'post', kind: 'text' },
      { code: 'position', kind: 'text' },
      { code: 'responsibilities', kind: 'text' },
      { code: 'results', kind: 'text' },
      { code: 'headcount', kind: 'integer' },
      { code: 'description', kind: 'text' },
      { code: 'hardwareEnvironment', kind: 'text' },
      { code: 'softwareEnvironment', kind: 'text' },
      { code: 'developmentTools', kind: 'text' },
    ],
  },
  skill: {
    table: 'personnel_skill',
    objectCode: 'TenantBase.Skill',
    fields: [
      { code: 'name', kind: 'text' },
      { code: 'category', kind: 'text' },
      { code: 'proficiency', kind: 'text' },
      { code: 'months', kind: 'decimal' },
    ],
  },
  'language-ability': {
    table: 'personnel_language_ability',
    objectCode: 'TenantBase.Languageability',
    fields: [
      { code: 'language', kind: 'text' },
      { code: 'proficiency', kind: 'text' },
      { code: 'listening', kind: 'text' },
      { code: 'speaking', kind: 'text' },
      { code: 'reading', kind: 'text' },
      { code: 'writing', kind: 'text' },
      { code: 'isNative', kind: 'boolean' },
      { code: 'description', kind: 'text' },
    ],
  },
  'estimation-result': {
    table: 'personnel_estimation_result',
    objectCode: 'TenantBase.EstimationResult',
    fields: [
      { code: 'year', kind: 'integer' },
      { code: 'cycleName', kind: 'text' },
      { code: 'cycleOrder', kind: 'integer' },
      { code: 'cycleStartDate', kind: 'date' },
      { code: 'cycleEndDate', kind: 'date' },
      { code: 'activity', kind: 'text' },
      { code: 'performanceId', kind: 'text' },
      { code: 'department', kind: 'text' },
      { code: 'finalScore', kind: 'decimal' },
      { code: 'totalGrade', kind: 'text' },
      { code: 'abilityGrade', kind: 'text' },
      { code: 'abilityScore', kind: 'decimal' },
      { code: 'valuesGrade', kind: 'text' },
      { code: 'valuesScore', kind: 'decimal' },
      { code: 'coefficient', kind: 'decimal' },
      { code: 'nineBoxResult', kind: 'text' },
      { code: 'comments', kind: 'text' },
      { code: 'developmentPlan', kind: 'text' },
    ],
  },
  punish: {
    table: 'personnel_punish',
    objectCode: 'TenantBase.Punish',
    fields: [
      { code: 'month', kind: 'text' },
      { code: 'description', kind: 'text' },
    ],
  },
  'professional-technical-post': {
    table: 'personnel_professional_technical_post',
    objectCode: 'TenantBase.ProfessionalTechnicalPostInfo',
    fields: [
      { code: 'qualificationName', kind: 'text' },
      { code: 'level', kind: 'text' },
      { code: 'appointedPost', kind: 'text' },
      { code: 'appointedLevel', kind: 'text' },
      { code: 'company', kind: 'text' },
      { code: 'startDate', kind: 'date' },
      { code: 'endDate', kind: 'date' },
      { code: 'assessmentDate', kind: 'date' },
      { code: 'assessmentInstitution', kind: 'text' },
      { code: 'qualificationRoute', kind: 'text' },
      { code: 'isHighestLevel', kind: 'boolean' },
    ],
  },
  'vocational-qualification': {
    table: 'personnel_vocational_qualification',
    objectCode: 'TenantBase.VocationalQualificationInfo',
    fields: [
      { code: 'name', kind: 'text' },
      { code: 'type', kind: 'text' },
      { code: 'level', kind: 'text' },
      { code: 'certificateNumber', kind: 'text' },
      { code: 'issuer', kind: 'text' },
      { code: 'obtainedDate', kind: 'date' },
      { code: 'endDate', kind: 'date' },
      { code: 'durationType', kind: 'text' },
      { code: 'major', kind: 'text' },
      { code: 'qualificationRoute', kind: 'text' },
      { code: 'isHighestLevel', kind: 'boolean' },
      { code: 'attachmentId', kind: 'uuid' },
    ],
  },
} as const satisfies Record<string, { table: string; objectCode: string; fields: readonly PersonnelField[] }>;
export type SubsetKind = keyof typeof SUBSETS;
