'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {interviewTypes,interviewRoles} from '@/lib/hris/cadre-interview-fields';
import type {DevelopmentRecord as R} from '@/lib/hris/development';
import ProcessHistory from '../development/process-history';
type Data={records:R[];employees:{id:string;name:string;code:string}[];employeeId:string|null;revision:number;total:number;hasMore:boolean};
const control='w-full rounded border p-2 bg-white';
export default function Workspace(){
 const [data,setData]=useState<Data|null>(null),[page,setPage]=useState(1),[search,setSearch]=useState(''),[id,setId]=useState(''),[form,setForm]=useState<Record<string,string>|null>(null),[detail,setDetail]=useState<R|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{setId(new URLSearchParams(location.search).get('recordId')??'')},[]);
 useEffect(()=>{let ignore=false;setError('');void fetch('/api/cadre-interviews?'+new URLSearchParams({page:String(page),search,...(id?{id}:{})}),{cache:'no-store'}).then(async r=>{const d=await r.json() as Data&{error?:string};if(!r.ok)throw Error(d.error??'加载失败');if(!ignore)setData(d);}).catch(e=>{if(!ignore){setData(null);setError((e as Error).message)}});return()=>{ignore=true}},[page,search,id,notice]);
 function open(r?:R){const v=r?.payload.cadreInterview;setError('');setForm({action:'save',...(r?{id:r.id}:{}),employeeId:r?.employeeId??'',interviewerId:v?.interviewerId??'',type:v?.type??interviewTypes[0],role:v?.role??interviewRoles[0],date:v?.date??'',location:v?.location??'',content:v?.content??'',evidence:''});}
 async function save(){if(!data||!form||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/cadre-interviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.revision,command:form})}),d=await r.json() as {error?:string;revision:number};if(!r.ok)throw Error(d.error??'保存失败');setForm(null);setNotice('已保存记录 · 修订 '+d.revision);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const choices=data?.employees??[];
 return <main className="main-content mx-auto max-w-5xl space-y-5"><nav className="flex gap-4 text-sm"><Link href="/cadres">干部管理</Link><Link href="/cadre-profiles">人才档案</Link></nav><div className="page-head"><div><h1>干部访谈记录</h1><p className="mt-2 text-sm text-slate-600">登记已发生访谈，保留更正与作废历史。访谈角色是记录分类；不自动认定组织关系或触发任用审批。</p></div><Button disabled={!data} onClick={()=>open()}>登记访谈</Button></div>{error&&<p className="panel error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel space-y-4"><div className="flex flex-wrap gap-3"><Input aria-label="搜索访谈" placeholder="姓名、类型、角色或日期" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} className="max-w-md"/>{id&&<Button variant="outline" onClick={()=>{setId('');setPage(1)}}>查看全部访谈</Button>}<Button variant="outline" onClick={()=>setNotice('已请求刷新 · '+new Date().toLocaleTimeString())}>刷新</Button></div>{data?.records.map(r=>{const v=r.payload.cadreInterview!;return <article key={r.id} className="rounded border p-4 space-y-2"><h2 className="font-semibold">{v.employeeName} · {v.type} · {v.date}</h2><p className="text-sm">访谈人：{v.interviewerName} · {v.role} · {r.status==='active'?'已登记':'已作废'} · V{r.payload.version}</p><div className="flex gap-3"><Button variant="outline" onClick={()=>setDetail(r)}>查看内容与历史</Button>{r.status==='active'&&r.employeeId!==data.employeeId&&<><Button variant="outline" onClick={()=>open(r)}>更正</Button><Button variant="ghost" onClick={()=>{setError('');setForm({action:'cancel',id:r.id,evidence:''})}}>作废</Button></>}</div></article>})}{data&&!data.total&&<p className="py-5 text-sm">当前范围内没有匹配记录。</p>}<div className="flex justify-end items-center gap-3"><span className="text-sm">{data?.total??0} 条 · 第 {page} 页</span><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</Button><Button variant="outline" disabled={!data?.hasMore} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!form} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{form?.action==='cancel'?'作废访谈记录':form?.id?'更正访谈记录':'登记访谈'}</DialogTitle><DialogDescription>由有双方当前组织权限的HR登记；更正不更换人员或访谈人，误选请作废后重登。不会发送通知。</DialogDescription></DialogHeader>{form&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy} className="space-y-3">{error&&<p role="alert" className="text-red-700">{error}</p>}{form.action==='save'&&<>{(['employeeId','interviewerId'] as const).map(k=><label className="field" key={k}>{k==='employeeId'?'人员':'访谈人'}<select required disabled={!!form.id} className={control} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}><option value="">请选择</option>{choices.filter(e=>k!=='employeeId'||e.id!==data?.employeeId).map(e=><option value={e.id} key={e.id}>{e.name} · {e.code}</option>)}</select></label>)}<label className="field">访谈类型<select className={control} value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{interviewTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">访谈角色<select className={control} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{interviewRoles.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">访谈日期<Input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label className="field">访谈地点<Input maxLength={200} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label className="field">访谈内容<textarea required maxLength={200} rows={4} className={control} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/><span className="text-xs text-slate-500">{form.content.length}/200</span></label></>}<label className="field">登记 / 更正 / 作废依据<textarea required minLength={5} maxLength={3000} rows={3} className={control} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><Button disabled={busy}>{busy?'保存中…':'保存'}</Button></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogContent className="max-h-[85vh] overflow-auto"><DialogHeader><DialogTitle>访谈内容与历史</DialogTitle><DialogDescription>{detail?.payload.cadreInterview?.employeeName} · {detail?.payload.cadreInterview?.date}</DialogDescription></DialogHeader>{detail&&<div className="space-y-3 text-sm"><p>地点：{detail.payload.cadreInterview?.location||'未登记'}</p><p className="whitespace-pre-wrap">{detail.payload.cadreInterview?.content}</p><p className="whitespace-pre-wrap">登记依据：{detail.payload.evidence}</p>{detail.payload.closedReason&&<p>作废依据：{detail.payload.closedReason}</p>}<ProcessHistory id={detail.id} updatedAt={detail.updatedAt}/></div>}</DialogContent></Dialog></main>;
}
